1. Project Setup and Data Access

In [9]:
## 1.1. Google Drive Mounting

from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
## 1.2. Input Data Verification

import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
  if 'final_simulation_inputs' in root.lower():
      print("FOUND:", root)
      print("FILES:", files)

FOUND: /content/drive/MyDrive/final_simulation_inputs
FILES: ['walr_scaled.csv', 'cpi_historical_calibration.csv', 'cpi_scaled.csv', 'market_credit_scenarios.csv', 'market_scaled.csv', 'household_profiles.csv', 'household_scaled.csv']

2. HCES Data Loading and Exploratory Analysis

In [13]:
## 2.1. HCES Data Loading

import pandas as pd

base_path = "/content/drive/MyDrive/final_simulation_inputs"

household_path = f"{base_path}/household_profiles.csv"

household_df = pd.read_csv(household_path)

print("Shape:", household_df.shape)

print("\nColumns:")
print(household_df.columns.tolist())

print("\nFirst 5 rows:")
display(household_df.head())

Shape: (227114, 14)

Columns:
['FSU_Serial_No', 'Sample_Household_No', 'State', 'District', 'household_size', 'expenditure', 'consumption_value', 'monthly_expenditure', 'online_spending', 'expense_per_member', 'online_spending_ratio', 'consumption_ratio', 'out_of_home_ratio', 'MULTIPLIER']

First 5 rows:

,FSU_Serial_No,Sample_Household_No,State,District,household_size,expenditure,consumption_value,monthly_expenditure,online_spending,expense_per_member,online_spending_ratio,consumption_ratio,out_of_home_ratio,MULTIPLIER
0,46956,1,5.0,6.0,7,50720.0,138.0,24000.0,3000.0,7245.714286,0.059148,0.002721,0.003352,57986
1,46956,2,5.0,6.0,6,50790.0,290.0,24000.0,300.0,8465.000000,0.005907,0.005710,0.002560,57986
2,46956,3,5.0,6.0,1,15300.0,3880.0,15000.0,6700.0,15300.000000,0.437908,0.253595,0.009272,57986
3,46956,4,5.0,6.0,4,10810.0,190.0,21500.0,500.0,2702.500000,0.046253,0.017576,0.009436,57986
4,46956,5,5.0,6.0,2,17040.0,94.0,14000.0,0.0,8520.000000,0.000000,0.005516,0.009272,57986

In [14]:
## 2.2. Descriptive Statistics of Core Variables

import pandas as pd

# Basic statistics
print("Monthly Expenditure Statistics")
print("-" * 40)

print(
    household_df["monthly_expenditure"]
    .describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

print("\nHousehold Size Statistics")
print("-" * 40)

print(
    household_df["household_size"]
    .describe()
)


print("\nExpense Per Member Statistics")
print("-" * 40)

print(
    household_df["expense_per_member"]
    .describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

Monthly Expenditure Statistics
----------------------------------------
count    227114.000000
mean      44617.178122
std       35869.062728
min         600.000000
1%         7300.000000
5%        13000.000000
25%       24000.000000
50%       36000.000000
75%       52000.000000
95%      108000.000000
99%      190800.000000
max      725000.000000
Name: monthly_expenditure, dtype: float64

Household Size Statistics
----------------------------------------
count    227114.000000
mean          4.328549
std           2.116959
min           1.000000
25%           3.000000
50%           4.000000
75%           5.000000
max          31.000000
Name: household_size, dtype: float64

Expense Per Member Statistics
----------------------------------------
count    2.271140e+05
mean     1.020330e+04
std      2.348349e+04
min      1.500000e+01
1%       3.600000e+02
5%       9.200000e+02
25%      2.696000e+03
50%      5.346667e+03
75%      1.080000e+04
95%      3.232000e+04
99%      7.515088e+04
max      2.242050e+06
Name: expense_per_member, dtype: float64

In [15]:
## 2.3. Spending Behaviour Analysis and Missing-Value Assessment

columns_to_check = [
    "online_spending_ratio",
    "consumption_ratio",
    "out_of_home_ratio"
]

print("Spending Behaviour Statistics")
print("-" * 50)

display(
    household_df[columns_to_check].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)


print("Missing values:")
print(
    household_df[
        [
            "household_size",
            "monthly_expenditure",
            "expense_per_member",
            "online_spending_ratio",
            "consumption_ratio",
            "out_of_home_ratio"
        ]
    ].isna().sum()
)

Spending Behaviour Statistics
--------------------------------------------------

       online_spending_ratio  consumption_ratio  out_of_home_ratio
count          227114.000000      227114.000000      227114.000000
mean                0.066459           0.078013           0.034986
std                 0.290121           0.543173           0.144991
min                 0.000000           0.000028           0.000000
1%                  0.000000           0.002107           0.000000
5%                  0.000000           0.005196           0.000000
25%                 0.000000           0.014963           0.007192
50%                 0.003230           0.029194           0.009272
75%                 0.064767           0.057692           0.011694
95%                 0.284643           0.189655           0.154914
99%                 0.703812           0.750000           0.422360
max                70.000000          66.666667          26.666667

Missing values:
household_size           0
monthly_expenditure      0
expense_per_member       0
online_spending_ratio    0
consumption_ratio        0
out_of_home_ratio        0
dtype: int64

In [16]:
## 2.4. Raw Spending Statistics and Correlation Analysis

spending_columns = [
    "monthly_expenditure",
    "online_spending",
    "consumption_value"
]

print("Raw Spending Variables")
print("-" * 50)

display(
    household_df[spending_columns].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)


print("\nCorrelations")
print("-" * 50)

display(
    household_df[
        [
            "monthly_expenditure",
            "online_spending",
            "consumption_value",
            "expense_per_member"
        ]
    ].corr()
)

Raw Spending Variables
--------------------------------------------------

       monthly_expenditure  online_spending  consumption_value
count        227114.000000    227114.000000      227114.000000
mean          44617.178122      2069.626060         959.814454
std           35869.062728      5496.615736        1117.222472
min             600.000000         0.000000           2.000000
1%             7300.000000         0.000000          60.000000
5%            13000.000000         0.000000         130.000000
25%           24000.000000         0.000000         340.000000
50%           36000.000000       150.000000         640.000000
75%           52000.000000      2000.000000        1180.000000
95%          108000.000000      9500.000000        2800.000000
99%          190800.000000     25000.000000        5435.220000
max          725000.000000    205000.000000       70600.000000

Correlations
--------------------------------------------------

,monthly_expenditure,online_spending,consumption_value,expense_per_member
monthly_expenditure,1.000000,0.588476,0.498059,0.270489
online_spending,0.588476,1.000000,0.418272,0.283132
consumption_value,0.498059,0.418272,1.000000,0.201989
expense_per_member,0.270489,0.283132,0.201989,1.000000

In [17]:
## 2.5. Expenditure Group Analysis

# Calculate expenditure thresholds from the actual HCES data

q25 = household_df["monthly_expenditure"].quantile(0.25)
q50 = household_df["monthly_expenditure"].quantile(0.50)
q75 = household_df["monthly_expenditure"].quantile(0.75)
q95 = household_df["monthly_expenditure"].quantile(0.95)

print("HCES Expenditure Thresholds")
print("-" * 40)

print(f"25th percentile: ₹{q25:,.2f}")
print(f"50th percentile: ₹{q50:,.2f}")
print(f"75th percentile: ₹{q75:,.2f}")
print(f"95th percentile: ₹{q95:,.2f}")


def expenditure_group(x):
    if x <= q25:
        return "low"
    elif x <= q50:
        return "moderate_low"
    elif x <= q75:
        return "moderate_high"
    elif x <= q95:
        return "high"
    else:
        return "very_high"


household_df["expenditure_group"] = (
    household_df["monthly_expenditure"]
    .apply(expenditure_group)
)

print("\nExpenditure Group Counts")
print("-" * 40)

print(
    household_df["expenditure_group"]
    .value_counts()
    .sort_index()
)


print("\nExpenditure Group Percentages")
print("-" * 40)

print(
    (
        household_df["expenditure_group"]
        .value_counts(normalize=True)
        .sort_index()
        * 100
    ).round(2)
)

HCES Expenditure Thresholds
----------------------------------------
25th percentile: ₹24,000.00
50th percentile: ₹36,000.00
75th percentile: ₹52,000.00
95th percentile: ₹108,000.00

Expenditure Group Counts
----------------------------------------
expenditure_group
high             45295
low              57439
moderate_high    53311
moderate_low     59807
very_high        11262
Name: count, dtype: int64

Expenditure Group Percentages
----------------------------------------
expenditure_group
high             19.94
low              25.29
moderate_high    23.47
moderate_low     26.33
very_high         4.96
Name: proportion, dtype: float64

In [18]:
## 2.6. Geographical Distribution Analysis

print("Number of States:", household_df["State"].nunique())

print("\nHouseholds by State:")
print(
    household_df["State"]
    .value_counts()
    .head(20)
)

print("\nState proportions:")
print(
    (
        household_df["State"]
        .value_counts(normalize=True)
        .head(20)
        * 100
    ).round(2)
)

Number of States: 36

Households by State:
State
9.0     26149
27.0    19498
19.0    16415
10.0    15837
33.0    12897
23.0    12037
8.0     10894
29.0    10828
28.0     9491
24.0     9452
21.0     8204
18.0     7857
36.0     6192
32.0     6099
20.0     5641
3.0      4908
16.0     4575
6.0      4382
22.0     4265
14.0     3577
Name: count, dtype: int64

State proportions:
State
9.0     11.51
27.0     8.59
19.0     7.23
10.0     6.97
33.0     5.68
23.0     5.30
8.0      4.80
29.0     4.77
28.0     4.18
24.0     4.16
21.0     3.61
18.0     3.46
36.0     2.73
32.0     2.69
20.0     2.48
3.0      2.16
16.0     2.01
6.0      1.93
22.0     1.88
14.0     1.57
Name: proportion, dtype: float64

In [19]:
## 2.7. Household Composition and Expenditure Analysis

print("Household Size vs Monthly Expenditure")
print("-" * 50)

size_exp = (
    household_df
    .groupby("household_size")["monthly_expenditure"]
    .agg(["count", "mean", "median"])
)

display(size_exp.head(15))


correlation = household_df[
    ["household_size", "monthly_expenditure"]
].corr().iloc[0, 1]

print(
    f"Correlation between household size and monthly expenditure: "
    f"{correlation:.4f}"
)

Household Size vs Monthly Expenditure
--------------------------------------------------

                count          mean   median
household_size
1               17122  20075.888214  17000.0
2               25173  29222.854964  24000.0
3               35202  39664.982586  32762.0
4               55373  46252.021798  37500.0
5               41262  49174.956958  39000.0
6               25308  53247.356567  42000.0
7               12305  55135.385616  44400.0
8                6453  60670.429568  48000.0
9                3710  67567.390027  54000.0
10               2380  73680.183193  60000.0
11               1160  73762.819828  60000.0
12                660  75928.725758  63250.0
13                371  80112.016173  68000.0
14                253  83875.035573  74500.0
15                157  86069.757962  75000.0

Correlation between household size and monthly expenditure: 0.3111

In [20]:
## 2.8. State-wise Expenditure Analysis


print("State-wise Household Distribution")
print("-" * 50)

state_distribution = (
    household_df
    .groupby("State")
    .agg(
        households=("State", "count"),
        avg_monthly_expenditure=("monthly_expenditure", "mean"),
        median_monthly_expenditure=("monthly_expenditure", "median")
    )
    .sort_values("households", ascending=False)
)

display(state_distribution)

State-wise Household Distribution
--------------------------------------------------

       households  avg_monthly_expenditure  median_monthly_expenditure
State
9.0         26149             36063.573674                     28000.0
27.0        19498             48814.985332                     38000.0
19.0        16415             41508.036917                     34500.0
10.0        15837             33432.690219                     28500.0
33.0        12897             43350.429092                     37500.0
23.0        12037             40888.014289                     32000.0
8.0         10894             49181.012484                     39000.0
29.0        10828             45848.254064                     37000.0
28.0         9491             39723.718154                     36300.0
24.0         9452             54186.007617                     44000.0
21.0         8204             36353.828011                     29900.0
18.0         7857             35416.120275                     30000.0
36.0         6192             51900.871770                     43600.0
32.0         6099             59792.294966                     48000.0
20.0         5641             33070.521539                     26500.0
3.0          4908             58124.616544                     45000.0
16.0         4575             43555.265574                     38000.0
6.0          4382             73194.041305                     53000.0
22.0         4265             33071.523329                     26000.0
14.0         3577             46241.332122                     40500.0
15.0         3112             43688.299807                     34000.0
7.0          3067             54841.050212                     44490.0
1.0          2990             54755.537793                     43750.0
12.0         2984             59333.513740                     44000.0
17.0         2826             49426.928875                     38150.0
5.0          2387             41848.273984                     33000.0
13.0         2063             78750.415899                     60000.0
11.0         1874             35866.856990                     31000.0
2.0          1867             49936.877879                     39500.0
34.0          947             61177.930306                     53000.0
35.0          857             58474.224037                     51000.0
25.0          630             46235.571429                     40900.0
31.0          596             52430.704698                     51000.0
37.0          579             54883.174439                     48000.0
4.0           578             82475.605536                     54000.0
30.0          559             69324.579606                     56000.0

3. Synthetic Population Generation

In [21]:
## 3.1. Base Synthetic Population Generation

import pandas as pd
import numpy as np

# Load HCES profiles
household_df = pd.read_csv(
    "/content/drive/MyDrive/final_simulation_inputs/household_profiles.csv"
)

# Number of synthetic users
N_USERS = 10000

# Reproducibility
np.random.seed(42)

# Sample HCES profiles
synthetic_users = household_df.sample(
    n=N_USERS,
    replace=True,
    random_state=42
).reset_index(drop=True)

# Create synthetic user IDs
synthetic_users.insert(
    0,
    "user_id",
    [f"USER_{i:05d}" for i in range(1, N_USERS + 1)]
)

print("Synthetic population created successfully.")
print("Number of users:", len(synthetic_users))
print("Number of variables:", len(synthetic_users.columns))

display(synthetic_users.head())

Synthetic population created successfully.
Number of users: 10000
Number of variables: 15

,user_id,FSU_Serial_No,Sample_Household_No,State,District,household_size,expenditure,consumption_value,monthly_expenditure,online_spending,expense_per_member,online_spending_ratio,consumption_ratio,out_of_home_ratio,MULTIPLIER
0,USER_00001,46260,7,6.0,6.0,4,36640.0,586.0,36870.0,0.0,9160.000000,0.000000,0.015993,0.009272,139646
1,USER_00002,48445,1,28.0,8.0,3,3920.0,600.0,27500.0,0.0,1306.666667,0.000000,0.153061,0.009272,136531
2,USER_00003,26622,10,1.0,10.0,3,29700.0,720.0,42000.0,300.0,9900.000000,0.010101,0.024242,0.009272,22296
3,USER_00004,49968,9,18.0,6.0,3,9400.0,620.0,25500.0,0.0,3133.333333,0.000000,0.065957,0.009272,113276
4,USER_00005,46554,5,3.0,7.0,4,20740.0,1278.0,51000.0,600.0,5185.000000,0.028930,0.061620,0.009272,121439

4. Simulation Environment and Data Persistence

In [22]:
## 4.1. GoalPilot Simulation Directory Structure

import os

# Main GoalPilot simulation directory
BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI/simulation"

# Required folders
folders = [
    "01_input_data",
    "02_synthetic_population",
    "03_financial_profiles",
    "04_economic_environment",
    "05_simulation_runs",
    "06_results",
    "07_validation"
]

for folder in folders:
    os.makedirs(os.path.join(BASE_DIR, folder), exist_ok=True)

print("GoalPilot simulation folder structure created.")
print()
print("Location:")
print(BASE_DIR)

print("\nFolders:")
for folder in folders:
    print("✓", folder)

GoalPilot simulation folder structure created.

Location:
/content/drive/MyDrive/GoalPilot_AI/simulation

Folders:
✓ 01_input_data
✓ 02_synthetic_population
✓ 03_financial_profiles
✓ 04_economic_environment
✓ 05_simulation_runs
✓ 06_results
✓ 07_validation

In [23]:
## 4.2. Base Synthetic Population Persistence

population_path = os.path.join(
    BASE_DIR,
    "02_synthetic_population",
    "synthetic_population_base.csv"
)

synthetic_users.to_csv(
    population_path,
    index=False
)

print("\nBase synthetic population saved successfully.")
print(population_path)

Base synthetic population saved successfully.
/content/drive/MyDrive/GoalPilot_AI/simulation/02_synthetic_population/synthetic_population_base.csv

 5. Synthetic Income Model

In [24]:
## 5.1. Synthetic Income Generation

import numpy as np
import pandas as pd

np.random.seed(42)

# Number of synthetic users
n = len(synthetic_users)

# Financial situation probabilities
financial_situation = np.random.choice(
    [
        "high_saving",
        "moderate_saving",
        "low_saving",
        "financial_stress"
    ],
    size=n,
    p=[0.20, 0.45, 0.30, 0.05]
)

# Generate an expense-to-income ratio for each user
expense_ratio = np.zeros(n)

expense_ratio[financial_situation == "high_saving"] = np.random.uniform(
    0.50, 0.65,
    (financial_situation == "high_saving").sum()
)

expense_ratio[financial_situation == "moderate_saving"] = np.random.uniform(
    0.65, 0.80,
    (financial_situation == "moderate_saving").sum()
)

expense_ratio[financial_situation == "low_saving"] = np.random.uniform(
    0.80, 0.95,
    (financial_situation == "low_saving").sum()
)

expense_ratio[financial_situation == "financial_stress"] = np.random.uniform(
    0.95, 1.10,
    (financial_situation == "financial_stress").sum()
)

# Calculate synthetic monthly income
synthetic_income = (
    synthetic_users["monthly_expenditure"] / expense_ratio
)

income_test = pd.DataFrame({
    "monthly_expenditure": synthetic_users["monthly_expenditure"],
    "expense_ratio": expense_ratio,
    "synthetic_income": synthetic_income,
    "financial_situation": financial_situation
})

display(income_test.head(10))

   monthly_expenditure  expense_ratio  synthetic_income financial_situation
0              36870.0       0.717995      51351.335334     moderate_saving
1              27500.0       1.041059      26415.417334    financial_stress
2              42000.0       0.944509      44467.548430          low_saving
3              25500.0       0.758966      33598.333991     moderate_saving
4              51000.0       0.556046      91719.010189         high_saving
5              27000.0       0.549937      49096.549442         high_saving
6              30000.0       0.526423      56988.382060         high_saving
7             100000.0       0.832270     120153.382912          low_saving
8              54000.0       0.664330      81284.850834     moderate_saving
9              38000.0       0.882752      43047.201045          low_saving

In [25]:
## 5.2. Income Distribution Analysis

print("Synthetic Income Distribution")
print("-" * 50)

display(
    income_test["synthetic_income"].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

Synthetic Income Distribution
--------------------------------------------------

count     10000.000000
mean      61588.311653
std       53908.829380
min        1257.339650
1%         9549.229838
5%        16671.181726
25%       32005.389162
50%       47770.485750
75%       71013.157446
95%      155062.553290
99%      280994.810603
max      845993.172582
Name: synthetic_income, dtype: float64

In [26]:
## 5.3. Financial Situation Distribution

print("Financial Situation Distribution")
print("-" * 50)

display(
    income_test["financial_situation"]
    .value_counts()
    .to_frame("users")
)

Financial Situation Distribution
--------------------------------------------------

                     users
financial_situation
moderate_saving       4560
low_saving            2923
high_saving           2043
financial_stress       474

In [27]:
## 5.4. Income Model Validation: Surplus and Savings Rate

income_test["monthly_surplus"] = (
    income_test["synthetic_income"]
    - income_test["monthly_expenditure"]
)

income_test["savings_rate"] = (
    income_test["monthly_surplus"]
    / income_test["synthetic_income"]
)

print("Income Model Validation")
print("-" * 50)

print(
    "Users with positive surplus:",
    (income_test["monthly_surplus"] > 0).sum()
)

print(
    "Users with deficit:",
    (income_test["monthly_surplus"] < 0).sum()
)

print(
    "Users approximately break-even:",
    (income_test["monthly_surplus"].abs() < 1).sum()
)

print("\nSurplus distribution:")
display(
    income_test["monthly_surplus"].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

print("\nSavings-rate distribution:")
display(
    income_test["savings_rate"].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

Income Model Validation
--------------------------------------------------
Users with positive surplus: 9676
Users with deficit: 324
Users approximately break-even: 0

Surplus distribution:

count     10000.000000
mean      16616.850453
std       20322.014544
min      -26064.617300
1%        -2137.088001
5%         1091.074538
25%        5320.922534
50%       11230.541488
75%       20929.409174
95%       49336.972525
99%       94201.872819
max      401353.251371
Name: monthly_surplus, dtype: float64

Savings-rate distribution:

count    10000.000000
mean         0.246901
std          0.129109
min         -0.099824
1%          -0.065928
5%           0.050911
25%          0.150370
50%          0.253111
75%          0.335655
95%          0.462706
99%          0.493317
max          0.499976
Name: savings_rate, dtype: float64

In [28]:
## 5.5. Income Model Validation: Financial Situation Summary

print("Financial Situation vs Average Savings Rate")
print("-" * 50)

situation_summary = (
    income_test
    .groupby("financial_situation")
    .agg(
        users=("financial_situation", "count"),
        avg_income=("synthetic_income", "mean"),
        avg_expense=("monthly_expenditure", "mean"),
        avg_surplus=("monthly_surplus", "mean"),
        avg_savings_rate=("savings_rate", "mean")
    )
)

display(situation_summary)

Financial Situation vs Average Savings Rate
--------------------------------------------------

,users,avg_income,avg_expense,avg_surplus,avg_savings_rate
financial_situation,,,,,
financial_stress,474,43319.191463,44371.508439,-1052.316976,-0.025355
high_saving,2043,79370.359871,45512.565835,33857.794037,0.424045
low_saving,2923,51661.583451,45178.231269,6483.352182,0.122917
moderate_saving,4560,61883.632923,44658.854167,17224.778756,0.275310

In [32]:
## 5.6  FINALIZE SYNTHETIC INCOME

# ============================================================
# STEP 2.3 — FINALIZE SYNTHETIC INCOME
# ============================================================

# Add income-related variables to the synthetic population
synthetic_users["expense_ratio"] = expense_ratio
synthetic_users["monthly_income"] = synthetic_income
synthetic_users["financial_situation"] = financial_situation

# Calculate monthly surplus
synthetic_users["monthly_surplus"] = (
    synthetic_users["monthly_income"]
    - synthetic_users["monthly_expenditure"]
)

# Calculate savings rate
synthetic_users["savings_rate"] = (
    synthetic_users["monthly_surplus"]
    / synthetic_users["monthly_income"]
)

# Display the result
print("Synthetic income variables added successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "household_size",
            "monthly_expenditure",
            "expense_ratio",
            "monthly_income",
            "monthly_surplus",
            "savings_rate",
            "financial_situation"
        ]
    ].head(10)
)


# Save the income-enhanced synthetic population

income_population_path = os.path.join(
    BASE_DIR,
    "02_synthetic_population",
    "synthetic_population_income.csv"
)

synthetic_users.to_csv(
    income_population_path,
    index=False
)

print("Income-enhanced synthetic population saved successfully.")
print(income_population_path)

Synthetic income variables added successfully.

,user_id,household_size,monthly_expenditure,expense_ratio,monthly_income,monthly_surplus,savings_rate,financial_situation
0,USER_00001,4,36870.0,0.717995,51351.335334,14481.335334,0.282005,moderate_saving
1,USER_00002,3,27500.0,1.041059,26415.417334,-1084.582666,-0.041059,financial_stress
2,USER_00003,3,42000.0,0.944509,44467.548430,2467.548430,0.055491,low_saving
3,USER_00004,3,25500.0,0.758966,33598.333991,8098.333991,0.241034,moderate_saving
4,USER_00005,4,51000.0,0.556046,91719.010189,40719.010189,0.443954,high_saving
5,USER_00006,4,27000.0,0.549937,49096.549442,22096.549442,0.450063,high_saving
6,USER_00007,4,30000.0,0.526423,56988.382060,26988.382060,0.473577,high_saving
7,USER_00008,7,100000.0,0.832270,120153.382912,20153.382912,0.167730,low_saving
8,USER_00009,4,54000.0,0.664330,81284.850834,27284.850834,0.335670,moderate_saving
9,USER_00010,6,38000.0,0.882752,43047.201045,5047.201045,0.117248,low_saving

Income-enhanced synthetic population saved successfully.
/content/drive/MyDrive/GoalPilot_AI/simulation/02_synthetic_population/synthetic_population_income.csv

6. Synthetic Savings Model

In [33]:
## 6.1. Initial Savings Model Generation

# ============================================================
# STEP 2.4A — TEST INITIAL SAVINGS MODEL
# ============================================================

np.random.seed(43)

n = len(synthetic_users)

# Savings level based on financial situation
savings_months = np.zeros(n)

# High-saving users: approximately 3–12 months of expenses
mask = synthetic_users["financial_situation"] == "high_saving"
savings_months[mask] = np.random.uniform(
    3, 12, mask.sum()
)

# Moderate-saving users: approximately 1–6 months
mask = synthetic_users["financial_situation"] == "moderate_saving"
savings_months[mask] = np.random.uniform(
    1, 6, mask.sum()
)

# Low-saving users: approximately 0.25–3 months
mask = synthetic_users["financial_situation"] == "low_saving"
savings_months[mask] = np.random.uniform(
    0.25, 3, mask.sum()
)

# Financial-stress users: approximately 0–1.5 months
mask = synthetic_users["financial_situation"] == "financial_stress"
savings_months[mask] = np.random.uniform(
    0, 1.5, mask.sum()
)

# Convert months of expenses into rupee savings
initial_savings = (
    synthetic_users["monthly_expenditure"]
    * savings_months
)

savings_test = pd.DataFrame({
    "monthly_expenditure": synthetic_users["monthly_expenditure"],
    "financial_situation": synthetic_users["financial_situation"],
    "savings_months": savings_months,
    "initial_savings": initial_savings
})

display(savings_test.head(10))

   monthly_expenditure financial_situation  savings_months  initial_savings
0              36870.0     moderate_saving        4.847672    178733.652470
1              27500.0    financial_stress        0.496704     13659.350863
2              42000.0          low_saving        2.031394     85318.549015
3              25500.0     moderate_saving        4.223629    107702.527041
4              51000.0         high_saving        4.035491    205810.045973
5              27000.0         high_saving        8.481599    229003.169045
6              30000.0         high_saving        4.200519    126015.560330
7             100000.0          low_saving        0.264815     26481.524416
8              54000.0     moderate_saving        3.066221    165575.931991
9              38000.0          low_saving        2.023146     76879.539877

In [34]:
## 6.2. Initial Savings Distribution Analysis

print("Initial Savings Distribution")
print("-" * 50)

display(
    savings_test["initial_savings"].describe(
        percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
    )
)

Initial Savings Distribution
--------------------------------------------------

count    1.000000e+04
mean     1.667948e+05
std      2.175347e+05
min      7.776881e+00
1%       6.171317e+03
5%       1.514821e+04
25%      4.960833e+04
50%      1.042297e+05
75%      2.029707e+05
95%      5.146845e+05
99%      1.044677e+06
max      4.946443e+06
Name: initial_savings, dtype: float64

In [35]:
## 6.3. Savings Profile Validation by Financial Situation

print("Savings by Financial Situation")
print("-" * 50)

savings_summary = (
    savings_test
    .groupby("financial_situation")
    .agg(
        users=("financial_situation", "count"),
        avg_savings_months=("savings_months", "mean"),
        avg_initial_savings=("initial_savings", "mean"),
        median_initial_savings=("initial_savings", "median")
    )
)

display(savings_summary)

Savings by Financial Situation
--------------------------------------------------

,users,avg_savings_months,avg_initial_savings,median_initial_savings
financial_situation,,,,
financial_stress,474,0.791725,35920.292822,25115.005270
high_saving,2043,7.609117,347327.063376,255991.483135
low_saving,2923,1.617128,73540.104727,52257.372560
moderate_saving,4560,3.544531,159292.655370,118085.160533

In [36]:
# ============================================================
# 6.4. SAVE SYNTHETIC SAVINGS POPULATION
# ============================================================

# Add savings-related variables to the synthetic population
synthetic_users["savings_months"] = savings_months
synthetic_users["initial_savings"] = initial_savings

# Display a quick check
print("Synthetic savings variables added successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "monthly_income",
            "monthly_expenditure",
            "monthly_surplus",
            "savings_rate",
            "financial_situation",
            "savings_months",
            "initial_savings"
        ]
    ].head(10)
)


# Save the savings-enhanced synthetic population

savings_population_path = os.path.join(
    BASE_DIR,
    "03_financial_profiles",
    "synthetic_population_savings.csv"
)

synthetic_users.to_csv(
    savings_population_path,
    index=False
)

print("Savings-enhanced synthetic population saved successfully.")
print(savings_population_path)

Synthetic savings variables added successfully.

,user_id,monthly_income,monthly_expenditure,monthly_surplus,savings_rate,financial_situation,savings_months,initial_savings
0,USER_00001,51351.335334,36870.0,14481.335334,0.282005,moderate_saving,4.847672,178733.652470
1,USER_00002,26415.417334,27500.0,-1084.582666,-0.041059,financial_stress,0.496704,13659.350863
2,USER_00003,44467.548430,42000.0,2467.548430,0.055491,low_saving,2.031394,85318.549015
3,USER_00004,33598.333991,25500.0,8098.333991,0.241034,moderate_saving,4.223629,107702.527041
4,USER_00005,91719.010189,51000.0,40719.010189,0.443954,high_saving,4.035491,205810.045973
5,USER_00006,49096.549442,27000.0,22096.549442,0.450063,high_saving,8.481599,229003.169045
6,USER_00007,56988.382060,30000.0,26988.382060,0.473577,high_saving,4.200519,126015.560330
7,USER_00008,120153.382912,100000.0,20153.382912,0.167730,low_saving,0.264815,26481.524416
8,USER_00009,81284.850834,54000.0,27284.850834,0.335670,moderate_saving,3.066221,165575.931991
9,USER_00010,43047.201045,38000.0,5047.201045,0.117248,low_saving,2.023146,76879.539877

Savings-enhanced synthetic population saved successfully.
/content/drive/MyDrive/GoalPilot_AI/simulation/03_financial_profiles/synthetic_population_savings.csv

7. Synthetic Debt Model

In [37]:
# 7.1. Synthetic Debt Profile Generation

import numpy as np

np.random.seed(44)

# Probability of having debt based on financial situation
debt_probability = {
    "high_saving": 0.30,
    "moderate_saving": 0.40,
    "low_saving": 0.50,
    "financial_stress": 0.60
}

# Generate debt status
has_debt = np.array([
    np.random.random() < debt_probability[situation]
    for situation in synthetic_users["financial_situation"]
])

# Generate debt-to-income ratio for users who have debt
debt_to_income_ratio = np.zeros(len(synthetic_users))

for i, situation in enumerate(synthetic_users["financial_situation"]):

    if has_debt[i]:

        if situation == "high_saving":
            debt_to_income_ratio[i] = np.random.uniform(0.10, 0.50)

        elif situation == "moderate_saving":
            debt_to_income_ratio[i] = np.random.uniform(0.20, 0.80)

        elif situation == "low_saving":
            debt_to_income_ratio[i] = np.random.uniform(0.30, 1.00)

        else:
            debt_to_income_ratio[i] = np.random.uniform(0.40, 1.20)

print("Synthetic debt status and debt ratios generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "monthly_income",
            "financial_situation"
        ]
    ].head(10)
)

Synthetic debt status and debt ratios generated successfully.

      user_id  monthly_income financial_situation
0  USER_00001    51351.335334     moderate_saving
1  USER_00002    26415.417334    financial_stress
2  USER_00003    44467.548430          low_saving
3  USER_00004    33598.333991     moderate_saving
4  USER_00005    91719.010189         high_saving
5  USER_00006    49096.549442         high_saving
6  USER_00007    56988.382060         high_saving
7  USER_00008   120153.382912          low_saving
8  USER_00009    81284.850834     moderate_saving
9  USER_00010    43047.201045          low_saving

In [38]:
# 7.2. Calculate Outstanding Debt

annual_income = synthetic_users["monthly_income"] * 12

outstanding_debt = np.where(
    has_debt,
    annual_income * debt_to_income_ratio,
    0
)

synthetic_users["has_debt"] = has_debt
synthetic_users["debt_to_income_ratio"] = debt_to_income_ratio
synthetic_users["outstanding_debt"] = outstanding_debt

print("Outstanding debt generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "monthly_income",
            "financial_situation",
            "has_debt",
            "debt_to_income_ratio",
            "outstanding_debt"
        ]
    ].head(10)
)

Outstanding debt generated successfully.

,user_id,monthly_income,financial_situation,has_debt,debt_to_income_ratio,outstanding_debt
0,USER_00001,51351.335334,moderate_saving,False,0.000000,0.000000e+00
1,USER_00002,26415.417334,financial_stress,True,1.082606,3.431697e+05
2,USER_00003,44467.548430,low_saving,False,0.000000,0.000000e+00
3,USER_00004,33598.333991,moderate_saving,True,0.639167,2.576993e+05
4,USER_00005,91719.010189,high_saving,False,0.000000,0.000000e+00
5,USER_00006,49096.549442,high_saving,False,0.000000,0.000000e+00
6,USER_00007,56988.382060,high_saving,False,0.000000,0.000000e+00
7,USER_00008,120153.382912,low_saving,True,0.965010,1.391391e+06
8,USER_00009,81284.850834,moderate_saving,False,0.000000,0.000000e+00
9,USER_00010,43047.201045,low_saving,False,0.000000,0.000000e+00

In [39]:
# 7.3. Synthetic EMI Generation

np.random.seed(45)

emi_ratio = np.zeros(len(synthetic_users))

for i, situation in enumerate(synthetic_users["financial_situation"]):

    if not has_debt[i]:
        emi_ratio[i] = 0

    elif situation == "high_saving":
        emi_ratio[i] = np.random.uniform(0.05, 0.20)

    elif situation == "moderate_saving":
        emi_ratio[i] = np.random.uniform(0.10, 0.30)

    elif situation == "low_saving":
        emi_ratio[i] = np.random.uniform(0.15, 0.35)

    else:
        emi_ratio[i] = np.random.uniform(0.20, 0.45)

monthly_emi = synthetic_users["monthly_income"].values * emi_ratio

synthetic_users["emi_ratio"] = emi_ratio
synthetic_users["monthly_emi"] = monthly_emi

print("Synthetic EMI generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "monthly_income",
            "financial_situation",
            "has_debt",
            "outstanding_debt",
            "emi_ratio",
            "monthly_emi"
        ]
    ].head(10)
)

Synthetic EMI generated successfully.

,user_id,monthly_income,financial_situation,has_debt,outstanding_debt,emi_ratio,monthly_emi
0,USER_00001,51351.335334,moderate_saving,False,0.000000e+00,0.000000,0.000000
1,USER_00002,26415.417334,financial_stress,True,3.431697e+05,0.447253,11814.371436
2,USER_00003,44467.548430,low_saving,False,0.000000e+00,0.000000,0.000000
3,USER_00004,33598.333991,moderate_saving,True,2.576993e+05,0.209909,7052.590854
4,USER_00005,91719.010189,high_saving,False,0.000000e+00,0.000000,0.000000
5,USER_00006,49096.549442,high_saving,False,0.000000e+00,0.000000,0.000000
6,USER_00007,56988.382060,high_saving,False,0.000000e+00,0.000000,0.000000
7,USER_00008,120153.382912,low_saving,True,1.391391e+06,0.206289,24786.376525
8,USER_00009,81284.850834,moderate_saving,False,0.000000e+00,0.000000,0.000000
9,USER_00010,43047.201045,low_saving,False,0.000000e+00,0.000000,0.000000

In [40]:
# 7.4. Synthetic Debt Population Validation

print("===== DEBT POPULATION SUMMARY =====")

print(f"Total users: {len(synthetic_users):,}")
print(f"Users with debt: {synthetic_users['has_debt'].sum():,}")
print(
    f"Debt prevalence: "
    f"{synthetic_users['has_debt'].mean() * 100:.2f}%"
)

print(
    f"Average outstanding debt among debt users: "
    f"₹{synthetic_users.loc[synthetic_users['has_debt'], 'outstanding_debt'].mean():,.2f}"
)

print(
    f"Average monthly EMI among debt users: "
    f"₹{synthetic_users.loc[synthetic_users['has_debt'], 'monthly_emi'].mean():,.2f}"
)

print(
    f"Average EMI ratio among debt users: "
    f"{synthetic_users.loc[synthetic_users['has_debt'], 'emi_ratio'].mean() * 100:.2f}%"
)

print("\n===== DEBT BY FINANCIAL SITUATION =====")

debt_summary = (
    synthetic_users
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        debt_users=("has_debt", "sum"),
        debt_rate=("has_debt", "mean"),
        avg_debt=("outstanding_debt", "mean"),
        avg_emi=("monthly_emi", "mean"),
        avg_emi_ratio=("emi_ratio", "mean")
    )
    .reset_index()
)

debt_summary["debt_rate"] *= 100
debt_summary["avg_emi_ratio"] *= 100

display(debt_summary)

===== DEBT POPULATION SUMMARY =====
Total users: 10,000
Users with debt: 4,208
Debt prevalence: 42.08%
Average outstanding debt among debt users: ₹370,234.26
Average monthly EMI among debt users: ₹12,346.70
Average EMI ratio among debt users: 21.40%

===== DEBT BY FINANCIAL SITUATION =====

,financial_situation,users,debt_users,debt_rate,avg_debt,avg_emi,avg_emi_ratio
0,financial_stress,474,293,61.814346,265451.322728,9045.223189,20.126615
1,high_saving,2043,637,31.179638,92781.849835,3164.789191,3.852801
2,low_saving,2923,1472,50.359220,201615.063391,6416.244247,12.464445
3,moderate_saving,4560,1806,39.605263,143256.072577,4922.615363,7.938276

In [41]:
# 7.5. Save Debt-Enhanced Synthetic Population

debt_population_path = os.path.join(
    BASE_DIR,
    "03_financial_profiles",
    "synthetic_population_debt.csv"
)

synthetic_users.to_csv(
    debt_population_path,
    index=False
)

print("Debt-enhanced synthetic population saved successfully.")
print(debt_population_path)

print("\nDataset shape:", synthetic_users.shape)
print("Number of users:", len(synthetic_users))

Debt-enhanced synthetic population saved successfully.
/content/drive/MyDrive/GoalPilot_AI/simulation/03_financial_profiles/synthetic_population_debt.csv

Dataset shape: (10000, 27)
Number of users: 10000

8. Synthetic Investment Profile

In [42]:
# 8.1. Investment Capacity Calculation

# Positive monthly surplus available after regular expenditure
positive_surplus = np.maximum(
    synthetic_users["monthly_surplus"].values,
    0
)

# Surplus remaining after EMI obligations
post_emi_surplus = np.maximum(
    synthetic_users["monthly_surplus"].values
    - synthetic_users["monthly_emi"].values,
    0
)

# Investment capacity relative to monthly income
investment_capacity_ratio = np.divide(
    post_emi_surplus,
    synthetic_users["monthly_income"].values,
    out=np.zeros(len(synthetic_users)),
    where=synthetic_users["monthly_income"].values > 0
)

# Savings buffer measured in months of expenditure
savings_buffer_months = synthetic_users["savings_months"].values

# Store the calculated variables
synthetic_users["positive_surplus"] = positive_surplus
synthetic_users["post_emi_surplus"] = post_emi_surplus
synthetic_users["investment_capacity_ratio"] = investment_capacity_ratio
synthetic_users["savings_buffer_months"] = savings_buffer_months

print("Investment capacity calculated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "monthly_income",
            "monthly_expenditure",
            "monthly_surplus",
            "monthly_emi",
            "post_emi_surplus",
            "savings_rate",
            "savings_buffer_months",
            "investment_capacity_ratio",
            "financial_situation"
        ]
    ].head(10)
)

Investment capacity calculated successfully.

,user_id,monthly_income,monthly_expenditure,monthly_surplus,monthly_emi,post_emi_surplus,savings_rate,savings_buffer_months,investment_capacity_ratio,financial_situation
0,USER_00001,51351.335334,36870.0,14481.335334,0.000000,14481.335334,0.282005,4.847672,0.282005,moderate_saving
1,USER_00002,26415.417334,27500.0,-1084.582666,11814.371436,0.000000,-0.041059,0.496704,0.000000,financial_stress
2,USER_00003,44467.548430,42000.0,2467.548430,0.000000,2467.548430,0.055491,2.031394,0.055491,low_saving
3,USER_00004,33598.333991,25500.0,8098.333991,7052.590854,1045.743136,0.241034,4.223629,0.031125,moderate_saving
4,USER_00005,91719.010189,51000.0,40719.010189,0.000000,40719.010189,0.443954,4.035491,0.443954,high_saving
5,USER_00006,49096.549442,27000.0,22096.549442,0.000000,22096.549442,0.450063,8.481599,0.450063,high_saving
6,USER_00007,56988.382060,30000.0,26988.382060,0.000000,26988.382060,0.473577,4.200519,0.473577,high_saving
7,USER_00008,120153.382912,100000.0,20153.382912,24786.376525,0.000000,0.167730,0.264815,0.000000,low_saving
8,USER_00009,81284.850834,54000.0,27284.850834,0.000000,27284.850834,0.335670,3.066221,0.335670,moderate_saving
9,USER_00010,43047.201045,38000.0,5047.201045,0.000000,5047.201045,0.117248,2.023146,0.117248,low_saving

In [45]:
# 8.2. Revised Investment Participation Generation

np.random.seed(47)

# Investment propensity is derived from the user's
# financial capacity, savings buffer, and surplus.
#
# It is interpreted as a probability-like propensity
# rather than using a fixed category-level probability.

investment_probability = np.clip(
    synthetic_users["investment_propensity"].values,
    0,
    1
)

# Generate investment participation stochastically.
# Each user's probability depends on their own financial profile.
has_investments = (
    np.random.random(len(synthetic_users))
    < investment_probability
)

synthetic_users["investment_probability"] = investment_probability
synthetic_users["has_investments"] = has_investments

print("Revised synthetic investment participation generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "investment_capacity_ratio",
            "savings_buffer_months",
            "investment_propensity",
            "investment_probability",
            "has_investments"
        ]
    ].head(10)
)

Revised synthetic investment participation generated successfully.

,user_id,financial_situation,investment_capacity_ratio,savings_buffer_months,investment_propensity,investment_probability,has_investments
0,USER_00001,moderate_saving,0.282005,4.847672,0.724389,0.724389,True
1,USER_00002,financial_stress,0.000000,0.496704,0.024835,0.024835,False
2,USER_00003,low_saving,0.055491,2.031394,0.357061,0.357061,False
3,USER_00004,moderate_saving,0.031125,4.223629,0.442306,0.442306,True
4,USER_00005,high_saving,0.443954,4.035491,0.845728,0.845728,True
5,USER_00006,high_saving,0.450063,8.481599,0.950063,0.950063,True
6,USER_00007,high_saving,0.473577,4.200519,0.883603,0.883603,True
7,USER_00008,low_saving,0.000000,0.264815,0.213241,0.213241,False
8,USER_00009,moderate_saving,0.335670,3.066221,0.688981,0.688981,False
9,USER_00010,low_saving,0.117248,2.023146,0.418405,0.418405,True

In [46]:
# 8.3. Revised Investment Participation Validation

print("===== INVESTMENT PARTICIPATION SUMMARY =====")

total_users = len(synthetic_users)
investment_users = synthetic_users["has_investments"].sum()

print(f"Total users: {total_users:,}")
print(f"Users with investments: {investment_users:,}")
print(
    f"Investment participation: "
    f"{investment_users / total_users * 100:.2f}%"
)

print(
    f"Average investment probability: "
    f"{synthetic_users['investment_probability'].mean():.4f}"
)

print("\n===== INVESTMENT PARTICIPATION BY FINANCIAL SITUATION =====")

investment_summary = (
    synthetic_users
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        investment_users=("has_investments", "sum"),
        participation_rate=("has_investments", "mean"),
        avg_probability=("investment_probability", "mean"),
        avg_capacity_ratio=("investment_capacity_ratio", "mean")
    )
    .reset_index()
)

investment_summary["participation_rate"] *= 100

display(investment_summary)

===== INVESTMENT PARTICIPATION SUMMARY =====
Total users: 10,000
Users with investments: 5,445
Investment participation: 54.45%
Average investment probability: 0.5435

===== INVESTMENT PARTICIPATION BY FINANCIAL SITUATION =====

,financial_situation,users,investment_users,participation_rate,avg_probability,avg_capacity_ratio
0,financial_stress,474,51,10.759494,0.106230,0.003352
1,high_saving,2043,1740,85.168869,0.861943,0.385517
2,low_saving,2923,1002,34.279849,0.342259,0.061403
3,moderate_saving,4560,2652,58.157895,0.575384,0.198158

In [47]:
# 8.4. Initial Investment Amount Generation

np.random.seed(48)

# Determine the proportion of savings allocated to investments.
# The range depends on the user's financial situation.

investment_allocation_ratio = np.zeros(len(synthetic_users))

for i, situation in enumerate(synthetic_users["financial_situation"]):

    if not synthetic_users.loc[i, "has_investments"]:
        investment_allocation_ratio[i] = 0

    elif situation == "high_saving":
        investment_allocation_ratio[i] = np.random.uniform(0.40, 0.80)

    elif situation == "moderate_saving":
        investment_allocation_ratio[i] = np.random.uniform(0.25, 0.60)

    elif situation == "low_saving":
        investment_allocation_ratio[i] = np.random.uniform(0.10, 0.40)

    else:
        investment_allocation_ratio[i] = np.random.uniform(0.05, 0.25)

# Calculate initial investment value
initial_investment = (
    synthetic_users["initial_savings"].values
    * investment_allocation_ratio
)

synthetic_users["investment_allocation_ratio"] = investment_allocation_ratio
synthetic_users["initial_investment"] = initial_investment

# Investment as a percentage of total savings
investment_to_savings_ratio = np.divide(
    initial_investment,
    synthetic_users["initial_savings"].values,
    out=np.zeros(len(synthetic_users)),
    where=synthetic_users["initial_savings"].values > 0
)

synthetic_users["investment_to_savings_ratio"] = (
    investment_to_savings_ratio
)

print("Initial investment amounts generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "initial_savings",
            "has_investments",
            "investment_probability",
            "investment_allocation_ratio",
            "initial_investment",
            "investment_to_savings_ratio"
        ]
    ].head(10)
)

Initial investment amounts generated successfully.

,user_id,financial_situation,initial_savings,has_investments,investment_probability,investment_allocation_ratio,initial_investment,investment_to_savings_ratio
0,USER_00001,moderate_saving,178733.652470,True,0.724389,0.256122,45777.548120,0.256122
1,USER_00002,financial_stress,13659.350863,False,0.024835,0.000000,0.000000,0.000000
2,USER_00003,low_saving,85318.549015,False,0.357061,0.000000,0.000000,0.000000
3,USER_00004,moderate_saving,107702.527041,True,0.442306,0.562051,60534.274631,0.562051
4,USER_00005,high_saving,205810.045973,True,0.845728,0.513944,105774.934379,0.513944
5,USER_00006,high_saving,229003.169045,True,0.950063,0.519591,118987.882781,0.519591
6,USER_00007,high_saving,126015.560330,True,0.883603,0.716814,90329.680595,0.716814
7,USER_00008,low_saving,26481.524416,False,0.213241,0.000000,0.000000,0.000000
8,USER_00009,moderate_saving,165575.931991,False,0.688981,0.000000,0.000000,0.000000
9,USER_00010,low_saving,76879.539877,True,0.418405,0.197341,15171.499059,0.197341

In [48]:
# 8.5. Save Investment-Enhanced Synthetic Population

investment_output_path = (
    "/content/drive/MyDrive/GoalPilot_AI/"
    "simulation/03_financial_profiles/"
    "synthetic_population_investment.csv"
)

synthetic_users.to_csv(investment_output_path, index=False)

print("Investment-enhanced synthetic population saved successfully.")
print(f"File path: {investment_output_path}")
print(f"Dataset shape: {synthetic_users.shape}")

print("\nInvestment-related columns:")
print([
    "has_investments",
    "investment_probability",
    "investment_allocation_ratio",
    "initial_investment",
    "investment_to_savings_ratio"
])

Investment-enhanced synthetic population saved successfully.
File path: /content/drive/MyDrive/GoalPilot_AI/simulation/03_financial_profiles/synthetic_population_investment.csv
Dataset shape: (10000, 41)

Investment-related columns:
['has_investments', 'investment_probability', 'investment_allocation_ratio', 'initial_investment', 'investment_to_savings_ratio']

9. Synthetic Risk Profile

In [49]:
# 9.1. Calculate Risk-Related Indicators

# Debt burden relative to annual income
synthetic_users["debt_burden_ratio"] = np.where(
    synthetic_users["monthly_income"] > 0,
    synthetic_users["outstanding_debt"] /
    (synthetic_users["monthly_income"] * 12),
    0
)

# EMI burden relative to monthly income
synthetic_users["emi_burden_ratio"] = np.where(
    synthetic_users["monthly_income"] > 0,
    synthetic_users["monthly_emi"] /
    synthetic_users["monthly_income"],
    0
)

# Savings buffer already represents months of expenditure covered
synthetic_users["savings_buffer_months"] = (
    synthetic_users["initial_savings"] /
    synthetic_users["monthly_expenditure"]
)

# Investment exposure relative to total savings
synthetic_users["investment_exposure_ratio"] = np.where(
    synthetic_users["initial_savings"] > 0,
    synthetic_users["initial_investment"] /
    synthetic_users["initial_savings"],
    0
)

print("Risk-related indicators calculated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "savings_buffer_months",
            "debt_burden_ratio",
            "emi_burden_ratio",
            "investment_capacity_ratio",
            "investment_exposure_ratio"
        ]
    ].head(10)
)

Risk-related indicators calculated successfully.

,user_id,financial_situation,savings_buffer_months,debt_burden_ratio,emi_burden_ratio,investment_capacity_ratio,investment_exposure_ratio
0,USER_00001,moderate_saving,4.847672,0.000000,0.000000,0.282005,0.256122
1,USER_00002,financial_stress,0.496704,1.082606,0.447253,0.000000,0.000000
2,USER_00003,low_saving,2.031394,0.000000,0.000000,0.055491,0.000000
3,USER_00004,moderate_saving,4.223629,0.639167,0.209909,0.031125,0.562051
4,USER_00005,high_saving,4.035491,0.000000,0.000000,0.443954,0.513944
5,USER_00006,high_saving,8.481599,0.000000,0.000000,0.450063,0.519591
6,USER_00007,high_saving,4.200519,0.000000,0.000000,0.473577,0.716814
7,USER_00008,low_saving,0.264815,0.965010,0.206289,0.000000,0.000000
8,USER_00009,moderate_saving,3.066221,0.000000,0.000000,0.335670,0.000000
9,USER_00010,low_saving,2.023146,0.000000,0.000000,0.117248,0.197341

In [51]:
# 9.2. Generate Data-Driven Risk Capacity Score

# Convert each financial indicator into its percentile rank
# within the synthetic population.
synthetic_users["savings_buffer_percentile"] = (
    synthetic_users["savings_buffer_months"].rank(pct=True)
)

synthetic_users["investment_capacity_percentile"] = (
    synthetic_users["investment_capacity_ratio"].rank(pct=True)
)

synthetic_users["debt_burden_percentile"] = (
    synthetic_users["debt_burden_ratio"].rank(pct=True)
)

synthetic_users["emi_burden_percentile"] = (
    synthetic_users["emi_burden_ratio"].rank(pct=True)
)

# Higher savings and investment capacity increase risk capacity.
# Higher debt and EMI burden reduce risk capacity.
#
# Equal contribution is used because there is no empirical basis
# in our available data for assigning different weights.
synthetic_users["risk_score"] = (
    synthetic_users["savings_buffer_percentile"]
    + synthetic_users["investment_capacity_percentile"]
    + (1 - synthetic_users["debt_burden_percentile"])
    + (1 - synthetic_users["emi_burden_percentile"])
) / 4

print("Data-driven risk capacity scores generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "savings_buffer_months",
            "investment_capacity_ratio",
            "debt_burden_ratio",
            "emi_burden_ratio",
            "risk_score"
        ]
    ].head(10)
)

Data-driven risk capacity scores generated successfully.

,user_id,financial_situation,savings_buffer_months,investment_capacity_ratio,debt_burden_ratio,emi_burden_ratio,risk_score
0,USER_00001,moderate_saving,4.847672,0.282005,0.000000,0.000000,0.710500
1,USER_00002,financial_stress,0.496704,0.000000,1.082606,0.447253,0.038363
2,USER_00003,low_saving,2.031394,0.055491,0.000000,0.000000,0.505350
3,USER_00004,moderate_saving,4.223629,0.031125,0.639167,0.209909,0.313650
4,USER_00005,high_saving,4.035491,0.443954,0.000000,0.000000,0.750750
5,USER_00006,high_saving,8.481599,0.450063,0.000000,0.000000,0.823150
6,USER_00007,high_saving,4.200519,0.473577,0.000000,0.000000,0.762325
7,USER_00008,low_saving,0.264815,0.000000,0.965010,0.206289,0.087587
8,USER_00009,moderate_saving,3.066221,0.335670,0.000000,0.000000,0.688500
9,USER_00010,low_saving,2.023146,0.117248,0.000000,0.000000,0.533300

In [52]:
# 9.3. Convert Risk Score into Synthetic Risk Profile

# Determine population-based boundaries from the generated risk scores.
risk_lower_boundary = synthetic_users["risk_score"].quantile(1 / 3)
risk_upper_boundary = synthetic_users["risk_score"].quantile(2 / 3)

# Assign relative risk-capacity profiles.
synthetic_users["risk_profile"] = np.select(
    [
        synthetic_users["risk_score"] <= risk_lower_boundary,
        synthetic_users["risk_score"] <= risk_upper_boundary
    ],
    [
        "conservative",
        "moderate"
    ],
    default="aggressive"
)

print("Synthetic risk profiles generated successfully.")

print("\nRisk boundaries derived from the synthetic population:")
print(f"Conservative / Moderate boundary: {risk_lower_boundary:.4f}")
print(f"Moderate / Aggressive boundary: {risk_upper_boundary:.4f}")

print("\nRisk profile distribution:")
print(
    synthetic_users["risk_profile"]
    .value_counts()
    .sort_index()
)

display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "risk_score",
            "risk_profile"
        ]
    ].head(10)
)

Synthetic risk profiles generated successfully.

Risk boundaries derived from the synthetic population:
Conservative / Moderate boundary: 0.4109
Moderate / Aggressive boundary: 0.6349

Risk profile distribution:
risk_profile
aggressive      3333
conservative    3333
moderate        3334
Name: count, dtype: int64

      user_id financial_situation  risk_score  risk_profile
0  USER_00001     moderate_saving    0.710500    aggressive
1  USER_00002    financial_stress    0.038363  conservative
2  USER_00003          low_saving    0.505350      moderate
3  USER_00004     moderate_saving    0.313650  conservative
4  USER_00005         high_saving    0.750750    aggressive
5  USER_00006         high_saving    0.823150    aggressive
6  USER_00007         high_saving    0.762325    aggressive
7  USER_00008          low_saving    0.087587  conservative
8  USER_00009     moderate_saving    0.688500    aggressive
9  USER_00010          low_saving    0.533300      moderate

In [53]:
# 9.4. Validate Risk Profile Against Financial Characteristics

risk_validation = (
    synthetic_users
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        avg_risk_score=("risk_score", "mean"),
        avg_savings_buffer_months=("savings_buffer_months", "mean"),
        avg_investment_capacity=("investment_capacity_ratio", "mean"),
        avg_debt_burden=("debt_burden_ratio", "mean"),
        avg_emi_burden=("emi_burden_ratio", "mean"),
        investment_participation=("has_investments", "mean")
    )
    .reset_index()
)

risk_validation["investment_participation"] = (
    risk_validation["investment_participation"] * 100
)

risk_validation = risk_validation.sort_values(
    "avg_risk_score"
).reset_index(drop=True)

print("Risk profile validation completed.")

display(risk_validation)

Risk profile validation completed.

,risk_profile,users,avg_risk_score,avg_savings_buffer_months,avg_investment_capacity,avg_debt_burden,avg_emi_burden,investment_participation
0,conservative,3333,0.227601,2.292554,0.029605,0.586335,0.233120,33.633363
1,moderate,3334,0.535065,2.966863,0.187888,0.090582,0.035133,51.049790
2,aggressive,3333,0.737324,5.783985,0.344191,0.005279,0.001893,78.667867

In [54]:
# 9.5. Save Risk-Enhanced Synthetic Population

risk_output_path = (
    "/content/drive/MyDrive/GoalPilot_AI/"
    "simulation/03_financial_profiles/"
    "synthetic_population_risk.csv"
)

synthetic_users.to_csv(risk_output_path, index=False)

print("Risk-enhanced synthetic population saved successfully.")
print(f"File path: {risk_output_path}")
print(f"Dataset shape: {synthetic_users.shape}")

print("\nRisk-related columns:")
print([
    "savings_buffer_percentile",
    "investment_capacity_percentile",
    "debt_burden_percentile",
    "emi_burden_percentile",
    "risk_score",
    "risk_profile"
])

Risk-enhanced synthetic population saved successfully.
File path: /content/drive/MyDrive/GoalPilot_AI/simulation/03_financial_profiles/synthetic_population_risk.csv
Dataset shape: (10000, 50)

Risk-related columns:
['savings_buffer_percentile', 'investment_capacity_percentile', 'debt_burden_percentile', 'emi_burden_percentile', 'risk_score', 'risk_profile']

10. Financial Goal Generation

In [55]:
# 10.1. Determine Goal Funding Capacity

synthetic_users["goal_funding_capacity"] = np.maximum(
    synthetic_users["post_emi_surplus"],
    0
)

print("Goal funding capacity calculated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "monthly_surplus",
            "post_emi_surplus",
            "goal_funding_capacity"
        ]
    ].head(10)
)

Goal funding capacity calculated successfully.

,user_id,monthly_income,monthly_expenditure,monthly_emi,monthly_surplus,post_emi_surplus,goal_funding_capacity
0,USER_00001,51351.335334,36870.0,0.000000,14481.335334,14481.335334,14481.335334
1,USER_00002,26415.417334,27500.0,11814.371436,-1084.582666,0.000000,0.000000
2,USER_00003,44467.548430,42000.0,0.000000,2467.548430,2467.548430,2467.548430
3,USER_00004,33598.333991,25500.0,7052.590854,8098.333991,1045.743136,1045.743136
4,USER_00005,91719.010189,51000.0,0.000000,40719.010189,40719.010189,40719.010189
5,USER_00006,49096.549442,27000.0,0.000000,22096.549442,22096.549442,22096.549442
6,USER_00007,56988.382060,30000.0,0.000000,26988.382060,26988.382060,26988.382060
7,USER_00008,120153.382912,100000.0,24786.376525,20153.382912,0.000000,0.000000
8,USER_00009,81284.850834,54000.0,0.000000,27284.850834,27284.850834,27284.850834
9,USER_00010,43047.201045,38000.0,0.000000,5047.201045,5047.201045,5047.201045

In [56]:
# 10.2. Goal Structure

goal_columns = [
    "goal_id",
    "user_id",
    "goal_name",
    "goal_type",
    "target_amount",
    "current_goal_funding",
    "target_date",
    "priority",
    "goal_horizon_months"
]

print("Goal structure defined successfully.")

print("\nGoal fields:")
for column in goal_columns:
    print(f"- {column}")

Goal structure defined successfully.

Goal fields:
- goal_id
- user_id
- goal_name
- goal_type
- target_amount
- current_goal_funding
- target_date
- priority
- goal_horizon_months

In [57]:
# 10.3. Generate Synthetic Goal Records

# Create one generic, user-defined financial goal for every synthetic user.
# The goal type is "custom" because the available datasets do not provide
# reliable information about the actual goal preferences of individuals.

synthetic_goals = pd.DataFrame({
    "goal_id": [
        f"GOAL_{i:05d}"
        for i in range(1, len(synthetic_users) + 1)
    ],

    "user_id": synthetic_users["user_id"].values,

    "goal_name": "Personal Financial Goal",

    "goal_type": "custom"
})

print("Synthetic goal records generated successfully.")

print(f"Number of goals: {len(synthetic_goals):,}")
print(f"Number of users: {synthetic_goals['user_id'].nunique():,}")

display(synthetic_goals.head(10))

Synthetic goal records generated successfully.
Number of goals: 10,000
Number of users: 10,000

      goal_id     user_id                goal_name goal_type
0  GOAL_00001  USER_00001  Personal Financial Goal    custom
1  GOAL_00002  USER_00002  Personal Financial Goal    custom
2  GOAL_00003  USER_00003  Personal Financial Goal    custom
3  GOAL_00004  USER_00004  Personal Financial Goal    custom
4  GOAL_00005  USER_00005  Personal Financial Goal    custom
5  GOAL_00006  USER_00006  Personal Financial Goal    custom
6  GOAL_00007  USER_00007  Personal Financial Goal    custom
7  GOAL_00008  USER_00008  Personal Financial Goal    custom
8  GOAL_00009  USER_00009  Personal Financial Goal    custom
9  GOAL_00010  USER_00010  Personal Financial Goal    custom

In [58]:
# 10.4.1. Analyze Goal Funding Capacity

goal_capacity_analysis = synthetic_users[
    [
        "user_id",
        "monthly_income",
        "monthly_expenditure",
        "monthly_emi",
        "monthly_surplus",
        "post_emi_surplus",
        "goal_funding_capacity"
    ]
].copy()

print("Goal funding capacity analysis")
print(f"Number of users: {len(goal_capacity_analysis):,}")
print()

display(
    goal_capacity_analysis[
        [
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "monthly_surplus",
            "post_emi_surplus",
            "goal_funding_capacity"
        ]
    ].describe()
)

Goal funding capacity analysis
Number of users: 10,000

,monthly_income,monthly_expenditure,monthly_emi,monthly_surplus,post_emi_surplus,goal_funding_capacity
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,61588.311653,44971.461200,5195.490810,16616.850453,12896.268636,12896.268636
std,53908.829380,37632.718833,9746.159467,20322.014544,18795.227379,18795.227379
min,1257.339650,850.000000,0.000000,-26064.617300,0.000000,0.000000
25%,32005.389162,24000.000000,0.000000,5320.922534,1218.354377,1218.354377
50%,47770.485750,35750.000000,0.000000,11230.541488,7604.489602,7604.489602
75%,71013.157446,51316.500000,8042.871110,20929.409174,17068.422123,17068.422123
max,845993.172582,530500.000000,139834.651410,401353.251371,401353.251371,401353.251371

In [59]:
# 10.4.2. Goal Funding Capacity Percentile Analysis

capacity_percentiles = synthetic_users["goal_funding_capacity"].quantile(
    [0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

print("Goal Funding Capacity Percentiles")
print()

for percentile, value in capacity_percentiles.items():
    print(f"{percentile:.0%} percentile: ₹{value:,.2f}")

print()
print(
    "Users with zero goal funding capacity:",
    (synthetic_users["goal_funding_capacity"] == 0).sum()
)

print(
    "Users with positive goal funding capacity:",
    (synthetic_users["goal_funding_capacity"] > 0).sum()
)

Goal Funding Capacity Percentiles

10% percentile: ₹0.00
25% percentile: ₹1,218.35
50% percentile: ₹7,604.49
75% percentile: ₹17,068.42
90% percentile: ₹31,026.47
95% percentile: ₹43,980.82
99% percentile: ₹85,998.40

Users with zero goal funding capacity: 2130
Users with positive goal funding capacity: 7870

In [60]:
# 10.4.3. Calculate Data-Driven Goal Capacity Percentile

synthetic_users["goal_capacity_percentile"] = (
    synthetic_users["goal_funding_capacity"]
    .rank(method="average", pct=True)
)

print("Goal capacity percentile generated successfully.")
print()

display(
    synthetic_users[
        [
            "user_id",
            "goal_funding_capacity",
            "goal_capacity_percentile"
        ]
    ].head(10)
)

print()
print("Capacity percentile range:")
print(
    f"Minimum: {synthetic_users['goal_capacity_percentile'].min():.4f}"
)
print(
    f"Maximum: {synthetic_users['goal_capacity_percentile'].max():.4f}"
)

Goal capacity percentile generated successfully.

      user_id  goal_funding_capacity  goal_capacity_percentile
0  USER_00001           14481.335334                   0.69770
1  USER_00002               0.000000                   0.10655
2  USER_00003            2467.548430                   0.30330
3  USER_00004            1045.743136                   0.24420
4  USER_00005           40719.010189                   0.94170
5  USER_00006           22096.549442                   0.82320
6  USER_00007           26988.382060                   0.87160
7  USER_00008               0.000000                   0.10655
8  USER_00009           27284.850834                   0.87490
9  USER_00010            5047.201045                   0.40940

Capacity percentile range:
Minimum: 0.1066
Maximum: 1.0000

In [61]:
# 10.4.4. Generate Synthetic Goal Horizon

np.random.seed(49)

# NISM-aligned horizon boundaries:
# Immediate: 0–6 months
# Short-term: 7–36 months
# Medium-term: 37–72 months
# Long-term: >72 months

# Generate a continuous horizon between 6 months and 120 months.
# The exact horizon is synthetic because actual user goal dates
# are not available in HCES or the financial profile data.

synthetic_users["goal_horizon_months"] = np.random.randint(
    6,
    121,
    size=len(synthetic_users)
)

# Assign the corresponding NISM-aligned horizon category
synthetic_users["goal_horizon_type"] = pd.cut(
    synthetic_users["goal_horizon_months"],
    bins=[0, 6, 36, 72, np.inf],
    labels=[
        "immediate",
        "short_term",
        "medium_term",
        "long_term"
    ],
    include_lowest=True
)

print("Synthetic goal horizons generated successfully.")
print()

display(
    synthetic_users[
        [
            "user_id",
            "goal_horizon_months",
            "goal_horizon_type"
        ]
    ].head(10)
)

print("\nGoal horizon distribution:")
display(
    synthetic_users["goal_horizon_type"]
    .value_counts()
    .sort_index()
)

Synthetic goal horizons generated successfully.

      user_id  goal_horizon_months goal_horizon_type
0  USER_00001                   48       medium_term
1  USER_00002                   51       medium_term
2  USER_00003                   46       medium_term
3  USER_00004                   60       medium_term
4  USER_00005                  120         long_term
5  USER_00006                   18        short_term
6  USER_00007                   75         long_term
7  USER_00008                   11        short_term
8  USER_00009                   55       medium_term
9  USER_00010                   24        short_term

Goal horizon distribution:

goal_horizon_type
immediate        91
short_term     2669
medium_term    3081
long_term      4159
Name: count, dtype: int64

In [62]:
# 10.4.5. Analyze Synthetic Goal Horizon Distribution

horizon_analysis = (
    synthetic_users["goal_horizon_months"]
    .describe(percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95])
)

print("Synthetic Goal Horizon Statistics")
display(horizon_analysis.to_frame(name="months"))

print("\nHorizon category statistics:")
display(
    synthetic_users.groupby("goal_horizon_type", observed=True)[
        "goal_horizon_months"
    ].agg(
        count="count",
        minimum="min",
        median="median",
        mean="mean",
        maximum="max"
    )
)

Synthetic Goal Horizon Statistics

             months
count  10000.000000
mean      62.697000
std       33.431233
min        6.000000
10%       17.000000
25%       33.000000
50%       63.000000
75%       92.000000
90%      109.000000
95%      115.000000
max      120.000000

Horizon category statistics:

                   count  minimum  median       mean  maximum
goal_horizon_type
immediate             91        6     6.0   6.000000        6
short_term          2669        7    21.0  21.331585       36
medium_term         3081       37    55.0  54.492048       72
long_term           4159       73    97.0  96.561673      120

In [63]:
# 10.4.6. Examine Financial Characteristics Across Synthetic Goal Horizons

horizon_financial_analysis = (
    synthetic_users
    .groupby("goal_horizon_type", observed=True)
    [
        [
            "monthly_income",
            "monthly_expenditure",
            "initial_savings",
            "goal_funding_capacity",
            "investment_capacity_ratio"
        ]
    ]
    .agg(["count", "median", "mean"])
)

display(horizon_financial_analysis)

                  monthly_income                              \
                           count        median          mean
goal_horizon_type
immediate                     91  54722.619355  65514.149376
short_term                  2669  47575.755277  60739.007025
medium_term                 3081  47036.274433  60571.517248
long_term                   4159  48141.069206  62800.691162

                  monthly_expenditure                        initial_savings  \
                                count   median          mean           count
goal_horizon_type
immediate                          91  41000.0  48965.351648              91
short_term                       2669  35000.0  44103.921319            2669
medium_term                      3081  35000.0  44278.221032            3081
long_term                        4159  36000.0  45954.364030            4159

                                                goal_funding_capacity  \
                          median           mean                 count
goal_horizon_type
immediate           94256.307184  154713.297624                    91
short_term         102413.935731  167755.282364                  2669
medium_term        102792.887328  164660.428572                  3081
long_term          106147.824405  168023.828982                  4159

                                             investment_capacity_ratio  \
                        median          mean                     count
goal_horizon_type
immediate          6878.255261  11380.605557                        91
short_term         7993.184441  12926.220682                      2669
medium_term        7195.183402  12469.548419                      3081
long_term          7637.413372  13226.325937                      4159


                     median      mean
goal_horizon_type
immediate          0.172943  0.166261
short_term         0.196049  0.190815
medium_term        0.188562  0.186600
long_term          0.186614  0.185850

In [64]:
# 10.5.1. Analyze Financial Capacity Available for Goal Funding

goal_capacity_components = synthetic_users[
    [
        "user_id",
        "monthly_income",
        "monthly_expenditure",
        "monthly_emi",
        "monthly_surplus",
        "post_emi_surplus",
        "goal_funding_capacity",
        "initial_savings",
        "initial_investment",
        "investment_capacity_ratio"
    ]
].copy()

print("Goal Funding Capacity Components")
print()

display(
    goal_capacity_components.describe()
)

Goal Funding Capacity Components

,monthly_income,monthly_expenditure,monthly_emi,monthly_surplus,post_emi_surplus,goal_funding_capacity,initial_savings,initial_investment,investment_capacity_ratio
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04,10000.000000
mean,61588.311653,44971.461200,5195.490810,16616.850453,12896.268636,12896.268636,1.667948e+05,5.696853e+04,0.187228
std,53908.829380,37632.718833,9746.159467,20322.014544,18795.227379,18795.227379,2.175347e+05,1.216104e+05,0.149113
min,1257.339650,850.000000,0.000000,-26064.617300,0.000000,0.000000,7.776881e+00,0.000000e+00,0.000000
25%,32005.389162,24000.000000,0.000000,5320.922534,1218.354377,1218.354377,4.960833e+04,0.000000e+00,0.036815
50%,47770.485750,35750.000000,0.000000,11230.541488,7604.489602,7604.489602,1.042297e+05,9.154055e+03,0.189573
75%,71013.157446,51316.500000,8042.871110,20929.409174,17068.422123,17068.422123,2.029707e+05,6.791043e+04,0.306529
max,845993.172582,530500.000000,139834.651410,401353.251371,401353.251371,401353.251371,4.946443e+06,3.880240e+06,0.499976

In [65]:
# 10.5.1. Calculate Baseline Goal Funding Potential

synthetic_users["baseline_goal_funding"] = (
    synthetic_users["goal_funding_capacity"]
    * synthetic_users["goal_horizon_months"]
)

print("Baseline goal funding potential calculated successfully.")
print()

display(
    synthetic_users[
        [
            "user_id",
            "goal_funding_capacity",
            "goal_horizon_months",
            "baseline_goal_funding"
        ]
    ].head(10)
)

print("\nBaseline Goal Funding Statistics:")
display(
    synthetic_users["baseline_goal_funding"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    ).to_frame(name="baseline_goal_funding")
)

Baseline goal funding potential calculated successfully.

,user_id,goal_funding_capacity,goal_horizon_months,baseline_goal_funding
0,USER_00001,14481.335334,48,6.951041e+05
1,USER_00002,0.000000,51,0.000000e+00
2,USER_00003,2467.548430,46,1.135072e+05
3,USER_00004,1045.743136,60,6.274459e+04
4,USER_00005,40719.010189,120,4.886281e+06
5,USER_00006,22096.549442,18,3.977379e+05
6,USER_00007,26988.382060,75,2.024129e+06
7,USER_00008,0.000000,11,0.000000e+00
8,USER_00009,27284.850834,55,1.500667e+06
9,USER_00010,5047.201045,24,1.211328e+05

Baseline Goal Funding Statistics:

       baseline_goal_funding
count           1.000000e+04
mean            8.180679e+05
std             1.476724e+06
min             0.000000e+00
10%             0.000000e+00
25%             4.329421e+04
50%             3.370647e+05
75%             1.015484e+06
90%             2.056281e+06
95%             3.078346e+06
99%             6.883259e+06
max             4.374750e+07

In [66]:
# 10.5.2. Analyze Existing Savings Relative to Baseline Goal Funding

synthetic_users["existing_savings_to_goal_ratio"] = np.where(
    synthetic_users["baseline_goal_funding"] > 0,
    synthetic_users["initial_savings"]
    / synthetic_users["baseline_goal_funding"],
    0
)

print("Existing savings relative to baseline goal funding:")
print()

display(
    synthetic_users[
        [
            "user_id",
            "initial_savings",
            "baseline_goal_funding",
            "existing_savings_to_goal_ratio"
        ]
    ].head(10)
)

print("\nRatio statistics:")
display(
    synthetic_users["existing_savings_to_goal_ratio"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    ).to_frame(name="savings_to_goal_ratio")
)

Existing savings relative to baseline goal funding:

,user_id,initial_savings,baseline_goal_funding,existing_savings_to_goal_ratio
0,USER_00001,178733.652470,6.951041e+05,0.257132
1,USER_00002,13659.350863,0.000000e+00,0.000000
2,USER_00003,85318.549015,1.135072e+05,0.751657
3,USER_00004,107702.527041,6.274459e+04,1.716523
4,USER_00005,205810.045973,4.886281e+06,0.042120
5,USER_00006,229003.169045,3.977379e+05,0.575764
6,USER_00007,126015.560330,2.024129e+06,0.062257
7,USER_00008,26481.524416,0.000000e+00,0.000000
8,USER_00009,165575.931991,1.500667e+06,0.110335
9,USER_00010,76879.539877,1.211328e+05,0.634671

Ratio statistics:

       savings_to_goal_ratio
count           10000.000000
mean                0.581180
std                 4.536309
min                 0.000000
10%                 0.000000
25%                 0.049199
50%                 0.147151
75%                 0.355030
90%                 0.905410
95%                 1.536778
max               222.479924

In [67]:
# 10.5.2. Analyze Annual Financial Scale for Goal Generation

synthetic_users["annual_income"] = (
    synthetic_users["monthly_income"] * 12
)

synthetic_users["annual_expenditure"] = (
    synthetic_users["monthly_expenditure"] * 12
)

annual_financial_scale = synthetic_users[
    [
        "annual_income",
        "annual_expenditure",
        "initial_savings",
        "baseline_goal_funding"
    ]
].describe(
    percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

print("Annual Financial Scale of Synthetic Population")
display(annual_financial_scale)

Annual Financial Scale of Synthetic Population

,annual_income,annual_expenditure,initial_savings,baseline_goal_funding
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04
mean,7.390597e+05,5.396575e+05,1.667948e+05,8.180679e+05
std,6.469060e+05,4.515926e+05,2.175347e+05,1.476724e+06
min,1.508808e+04,1.020000e+04,7.776881e+00,0.000000e+00
10%,2.623030e+05,1.980000e+05,2.463442e+04,0.000000e+00
25%,3.840647e+05,2.880000e+05,4.960833e+04,4.329421e+04
50%,5.732458e+05,4.290000e+05,1.042297e+05,3.370647e+05
75%,8.521579e+05,6.157980e+05,2.029707e+05,1.015484e+06
90%,1.342365e+06,9.720000e+05,3.621169e+05,2.056281e+06
95%,1.860751e+06,1.332000e+06,5.146845e+05,3.078346e+06
99%,3.371938e+06,2.502060e+06,1.044677e+06,6.883259e+06
max,1.015192e+07,6.366000e+06,4.946443e+06,4.374750e+07

In [68]:
# 10.5.3. Calculate Population-Relative Annual Income Percentile

synthetic_users["annual_income_percentile"] = (
    synthetic_users["annual_income"]
    .rank(method="average", pct=True)
)

print("Annual income percentile generated successfully.")
print()

display(
    synthetic_users[
        [
            "user_id",
            "annual_income",
            "annual_income_percentile"
        ]
    ].head(10)
)

print("\nIncome percentile distribution:")
display(
    synthetic_users["annual_income_percentile"].describe()
)

Annual income percentile generated successfully.

      user_id  annual_income  annual_income_percentile
0  USER_00001   6.162160e+05                    0.5540
1  USER_00002   3.169850e+05                    0.1573
2  USER_00003   5.336106e+05                    0.4484
3  USER_00004   4.031800e+05                    0.2770
4  USER_00005   1.100628e+06                    0.8497
5  USER_00006   5.891586e+05                    0.5226
6  USER_00007   6.838606e+05                    0.6220
7  USER_00008   1.441841e+06                    0.9142
8  USER_00009   9.754182e+05                    0.8105
9  USER_00010   5.165664e+05                    0.4293

Income percentile distribution:

count    10000.000000
mean         0.500050
std          0.288690
min          0.000100
25%          0.250075
50%          0.500050
75%          0.750025
max          1.000000
Name: annual_income_percentile, dtype: float64

In [69]:
# 10.5.4. Generate Population-Relative Goal Difficulty Factor

synthetic_users["goal_difficulty_factor"] = np.sqrt(
    synthetic_users["annual_income_percentile"]
    * synthetic_users["goal_capacity_percentile"]
)

print("Goal difficulty factor generated successfully.")
print()

display(
    synthetic_users[
        [
            "user_id",
            "annual_income_percentile",
            "goal_capacity_percentile",
            "goal_difficulty_factor"
        ]
    ].head(10)
)

print("\nGoal difficulty factor statistics:")
display(
    synthetic_users["goal_difficulty_factor"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    ).to_frame(name="goal_difficulty_factor")
)

Goal difficulty factor generated successfully.

,user_id,annual_income_percentile,goal_capacity_percentile,goal_difficulty_factor
0,USER_00001,0.5540,0.69770,0.621712
1,USER_00002,0.1573,0.10655,0.129462
2,USER_00003,0.4484,0.30330,0.368781
3,USER_00004,0.2770,0.24420,0.260083
4,USER_00005,0.8497,0.94170,0.894518
5,USER_00006,0.5226,0.82320,0.655900
6,USER_00007,0.6220,0.87160,0.736298
7,USER_00008,0.9142,0.10655,0.312103
8,USER_00009,0.8105,0.87490,0.842085
9,USER_00010,0.4293,0.40940,0.419232

Goal difficulty factor statistics:

       goal_difficulty_factor
count            10000.000000
mean                 0.472921
std                  0.269415
min                  0.004729
10%                  0.143660
25%                  0.240157
50%                  0.437352
75%                  0.698498
90%                  0.872864
95%                  0.934319
99%                  0.986940
max                  0.999950

In [72]:
# 10.5.5. Analyze Financial Scale for Synthetic Goal Target

goal_scale_columns = [
    "annual_income",
    "annual_expenditure",
    "initial_savings",
    "goal_funding_capacity",
    "baseline_goal_funding"
]

print("Financial scale statistics for synthetic goal modelling:")

display(
    synthetic_users[goal_scale_columns].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    ).T
)

print("\nFinancial scale by goal horizon:")

display(
    synthetic_users.groupby("goal_horizon_type", observed=False)[
        ["annual_income", "annual_expenditure", "initial_savings",
         "goal_funding_capacity", "baseline_goal_funding"]
    ]
    .median()
)

print("\nFinancial scale by financial situation:")

display(
    synthetic_users.groupby("financial_situation")[
        ["annual_income", "annual_expenditure", "initial_savings",
         "goal_funding_capacity", "baseline_goal_funding"]
    ]
    .median()
)

Financial scale statistics for synthetic goal modelling:

,count,mean,std,min,10%,25%,50%,75%,90%,95%,99%,max
annual_income,10000.0,739059.739831,6.469060e+05,15088.075801,262302.991082,384064.669948,573245.829004,8.521579e+05,1.342365e+06,1.860751e+06,3.371938e+06,1.015192e+07
annual_expenditure,10000.0,539657.534400,4.515926e+05,10200.000000,198000.000000,288000.000000,429000.000000,6.157980e+05,9.720000e+05,1.332000e+06,2.502060e+06,6.366000e+06
initial_savings,10000.0,166794.764388,2.175347e+05,7.776881,24634.419878,49608.326314,104229.701508,2.029707e+05,3.621169e+05,5.146845e+05,1.044677e+06,4.946443e+06
goal_funding_capacity,10000.0,12896.268636,1.879523e+04,0.000000,0.000000,1218.354377,7604.489602,1.706842e+04,3.102647e+04,4.398082e+04,8.599840e+04,4.013533e+05
baseline_goal_funding,10000.0,818067.853431,1.476724e+06,0.000000,0.000000,43294.213441,337064.657326,1.015484e+06,2.056281e+06,3.078346e+06,6.883259e+06,4.374750e+07

Financial scale by goal horizon:

,annual_income,annual_expenditure,initial_savings,goal_funding_capacity,baseline_goal_funding
goal_horizon_type,,,,,
immediate,656671.432257,492000.0,94256.307184,6878.255261,41269.531566
short_term,570909.063324,420000.0,102413.935731,7993.184441,142387.618151
medium_term,564435.293194,420000.0,102792.887328,7195.183402,382640.776390
long_term,577692.830477,432000.0,106147.824405,7637.413372,722749.126439

Financial scale by financial situation:

,annual_income,annual_expenditure,initial_savings,goal_funding_capacity,baseline_goal_funding
financial_situation,,,,,
financial_stress,411816.486638,420000.0,25115.005270,0.000000,0.000000e+00
high_saving,743010.591055,420000.0,255991.483135,23219.907212,1.301208e+06
low_saving,486794.977343,432000.0,52257.372560,789.359726,2.172763e+04
moderate_saving,588127.967210,426000.0,118085.160533,9334.052441,4.467739e+05

In [73]:
# 10.5.6. Generate Population-Relative Financial Scale

synthetic_users["financial_scale_percentile"] = (
    synthetic_users["annual_income"]
    .rank(method="average", pct=True)
)

print("Financial scale percentile generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "annual_income",
            "annual_expenditure",
            "initial_savings",
            "financial_scale_percentile"
        ]
    ].head(10)
)

print("\nFinancial scale percentile statistics:")

display(
    synthetic_users["financial_scale_percentile"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

Financial scale percentile generated successfully.

,user_id,annual_income,annual_expenditure,initial_savings,financial_scale_percentile
0,USER_00001,6.162160e+05,442440.0,178733.652470,0.5540
1,USER_00002,3.169850e+05,330000.0,13659.350863,0.1573
2,USER_00003,5.336106e+05,504000.0,85318.549015,0.4484
3,USER_00004,4.031800e+05,306000.0,107702.527041,0.2770
4,USER_00005,1.100628e+06,612000.0,205810.045973,0.8497
5,USER_00006,5.891586e+05,324000.0,229003.169045,0.5226
6,USER_00007,6.838606e+05,360000.0,126015.560330,0.6220
7,USER_00008,1.441841e+06,1200000.0,26481.524416,0.9142
8,USER_00009,9.754182e+05,648000.0,165575.931991,0.8105
9,USER_00010,5.165664e+05,456000.0,76879.539877,0.4293

Financial scale percentile statistics:

count    10000.000000
mean         0.500050
std          0.288690
min          0.000100
10%          0.100090
25%          0.250075
50%          0.500050
75%          0.750025
90%          0.900010
95%          0.950005
99%          0.990001
max          1.000000
Name: financial_scale_percentile, dtype: float64

In [75]:
# 10.5.7. Calculate Savings-to-Income Scale

synthetic_users["savings_to_annual_income_ratio"] = (
    synthetic_users["initial_savings"]
    / synthetic_users["annual_income"]
)

print("Savings-to-annual-income ratio generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "annual_income",
            "initial_savings",
            "savings_to_annual_income_ratio"
        ]
    ].head(10)
)

print("\nSavings-to-annual-income ratio statistics:")

display(
    synthetic_users["savings_to_annual_income_ratio"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

Savings-to-annual-income ratio generated successfully.

      user_id  annual_income  initial_savings  savings_to_annual_income_ratio
0  USER_00001   6.162160e+05    178733.652470                        0.290050
1  USER_00002   3.169850e+05     13659.350863                        0.043091
2  USER_00003   5.336106e+05     85318.549015                        0.159889
3  USER_00004   4.031800e+05    107702.527041                        0.267133
4  USER_00005   1.100628e+06    205810.045973                        0.186993
5  USER_00006   5.891586e+05    229003.169045                        0.388695
6  USER_00007   6.838606e+05    126015.560330                        0.184271
7  USER_00008   1.441841e+06     26481.524416                        0.018366
8  USER_00009   9.754182e+05    165575.931991                        0.169749
9  USER_00010   5.165664e+05     76879.539877                        0.148828

Savings-to-annual-income ratio statistics:

count    10000.000000
mean         0.210045
std          0.127768
min          0.000107
10%          0.065335
25%          0.111463
50%          0.187203
75%          0.288394
90%          0.378997
95%          0.476714
99%          0.569511
max          0.644658
Name: savings_to_annual_income_ratio, dtype: float64

In [76]:
# 10.5.8. Generate Population-Derived Goal Scale Factor

synthetic_users["goal_scale_percentile"] = (
    synthetic_users["savings_to_annual_income_ratio"]
    .rank(method="average", pct=True)
)

print("Goal scale percentile generated successfully.")

display(
    synthetic_users[
        [
            "user_id",
            "annual_income",
            "initial_savings",
            "savings_to_annual_income_ratio",
            "goal_scale_percentile"
        ]
    ].head(10)
)

print("\nGoal scale percentile statistics:")

display(
    synthetic_users["goal_scale_percentile"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

Goal scale percentile generated successfully.

,user_id,annual_income,initial_savings,savings_to_annual_income_ratio,goal_scale_percentile
0,USER_00001,6.162160e+05,178733.652470,0.290050,0.7533
1,USER_00002,3.169850e+05,13659.350863,0.043091,0.0527
2,USER_00003,5.336106e+05,85318.549015,0.159889,0.4064
3,USER_00004,4.031800e+05,107702.527041,0.267133,0.7055
4,USER_00005,1.100628e+06,205810.045973,0.186993,0.4995
5,USER_00006,5.891586e+05,229003.169045,0.388695,0.9072
6,USER_00007,6.838606e+05,126015.560330,0.184271,0.4895
7,USER_00008,1.441841e+06,26481.524416,0.018366,0.0071
8,USER_00009,9.754182e+05,165575.931991,0.169749,0.4380
9,USER_00010,5.165664e+05,76879.539877,0.148828,0.3711

Goal scale percentile statistics:

count    10000.000000
mean         0.500050
std          0.288690
min          0.000100
10%          0.100090
25%          0.250075
50%          0.500050
75%          0.750025
90%          0.900010
95%          0.950005
99%          0.990001
max          1.000000
Name: goal_scale_percentile, dtype: float64

In [77]:
# 10.5.9. Generate Synthetic Goal Target Amount

# Use the population's median savings-to-income ratio
# as the central synthetic goal-scale reference.
goal_scale_reference = (
    synthetic_users["savings_to_annual_income_ratio"].median()
)

synthetic_users["target_amount"] = (
    synthetic_users["annual_income"]
    * goal_scale_reference
)

print("Synthetic goal target amount generated successfully.")

print(
    f"Population median savings-to-annual-income ratio used as "
    f"goal-scale reference: {goal_scale_reference:.4f}"
)

display(
    synthetic_users[
        [
            "user_id",
            "annual_income",
            "goal_horizon_months",
            "initial_savings",
            "goal_funding_capacity",
            "target_amount"
        ]
    ].head(10)
)

print("\nTarget amount statistics:")

display(
    synthetic_users["target_amount"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

Synthetic goal target amount generated successfully.
Population median savings-to-annual-income ratio used as goal-scale reference: 0.1872

,user_id,annual_income,goal_horizon_months,initial_savings,goal_funding_capacity,target_amount
0,USER_00001,6.162160e+05,48,178733.652470,14481.335334,115357.183592
1,USER_00002,3.169850e+05,51,13659.350863,0.000000,59340.387689
2,USER_00003,5.336106e+05,46,85318.549015,2467.548430,99893.237726
3,USER_00004,4.031800e+05,60,107702.527041,1045.743136,75476.307623
4,USER_00005,1.100628e+06,120,205810.045973,40719.010189,206040.342056
5,USER_00006,5.891586e+05,18,229003.169045,22096.549442,110291.964774
6,USER_00007,6.838606e+05,75,126015.560330,26988.382060,128020.414837
7,USER_00008,1.441841e+06,11,26481.524416,0.000000,269916.171830
8,USER_00009,9.754182e+05,55,165575.931991,27284.850834,182600.732773
9,USER_00010,5.165664e+05,24,76879.539877,5047.201045,96702.526658

Target amount statistics:

count    1.000000e+04
mean     1.383538e+05
std      1.211024e+05
min      2.824526e+03
10%      4.910378e+04
25%      7.189787e+04
50%      1.073131e+05
75%      1.595261e+05
90%      2.512942e+05
95%      3.483372e+05
99%      6.312352e+05
max      1.900464e+06
Name: target_amount, dtype: float64

In [78]:
# 10.5.10. Validate Synthetic Goal Target Amount

synthetic_users["target_to_annual_income_ratio"] = (
    synthetic_users["target_amount"]
    / synthetic_users["annual_income"]
)

synthetic_users["target_to_savings_ratio"] = (
    synthetic_users["target_amount"]
    / synthetic_users["initial_savings"]
)

synthetic_users["target_funding_months"] = (
    synthetic_users["target_amount"]
    / synthetic_users["goal_funding_capacity"].replace(0, np.nan)
)

print("Target validation metrics generated successfully.")

print("\nTarget relative to annual income:")
display(
    synthetic_users["target_to_annual_income_ratio"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nTarget relative to existing savings:")
display(
    synthetic_users["target_to_savings_ratio"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nTarget funding months for users with positive funding capacity:")
display(
    synthetic_users["target_funding_months"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nTarget amount by financial situation:")
display(
    synthetic_users.groupby("financial_situation")["target_amount"]
    .agg(
        count="count",
        mean="mean",
        median="median",
        minimum="min",
        maximum="max"
    )
)

Target validation metrics generated successfully.

Target relative to annual income:

count    1.000000e+04
mean     1.872025e-01
std      8.493555e-15
min      1.872025e-01
10%      1.872025e-01
25%      1.872025e-01
50%      1.872025e-01
75%      1.872025e-01
90%      1.872025e-01
95%      1.872025e-01
99%      1.872025e-01
max      1.872025e-01
Name: target_to_annual_income_ratio, dtype: float64

Target relative to existing savings:

count    10000.000000
mean         1.854005
std         18.381793
min          0.290390
10%          0.493942
25%          0.649122
50%          1.000000
75%          1.679511
90%          2.865267
95%          4.522871
99%          9.331715
max       1751.784507
Name: target_to_savings_ratio, dtype: float64

Target funding months for users with positive funding capacity:

count     7870.000000
mean        29.069985
std        236.698735
min          4.493073
10%          5.405043
25%          6.772005
50%          9.371060
75%         17.533320
90%         34.316365
95%         57.081389
99%        262.451922
max      13840.977053
Name: target_funding_months, dtype: float64

Target amount by financial situation:

,count,mean,median,minimum,maximum
financial_situation,,,,,
financial_stress,474,97313.534110,77093.078084,10772.910878,7.425246e+05
high_saving,2043,178299.962715,139093.444220,4534.836199,1.900464e+06
low_saving,2923,116054.134290,91129.239398,4532.800884,1.035134e+06
moderate_saving,4560,139017.253553,110099.028986,2824.525592,1.525645e+06

In [79]:
# 10.5.11. Validate Target Affordability Against Financial Capacity

# Calculate how many months of available goal funding are required
# to reach the synthetic target amount.
positive_capacity = synthetic_users["goal_funding_capacity"] > 0

synthetic_users["target_funding_months"] = np.nan

synthetic_users.loc[positive_capacity, "target_funding_months"] = (
    synthetic_users.loc[positive_capacity, "target_amount"]
    / synthetic_users.loc[positive_capacity, "goal_funding_capacity"]
)

# Compare target size with existing savings
synthetic_users["target_to_savings_ratio"] = (
    synthetic_users["target_amount"]
    / synthetic_users["initial_savings"]
)

# Create affordability categories using population-relative percentiles.
funding_months_positive = synthetic_users.loc[
    positive_capacity, "target_funding_months"
]

funding_months_percentile = funding_months_positive.rank(
    method="average",
    pct=True
)

synthetic_users.loc[
    positive_capacity, "target_funding_months_percentile"
] = funding_months_percentile

print("Target funding months:")
display(
    synthetic_users["target_funding_months"]
    .describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nTarget-to-savings ratio:")
display(
    synthetic_users["target_to_savings_ratio"]
    .describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nTarget funding months by financial situation:")

target_affordability_summary = (
    synthetic_users
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        median_target=("target_amount", "median"),
        median_capacity=("goal_funding_capacity", "median"),
        median_funding_months=("target_funding_months", "median"),
        median_target_savings_ratio=("target_to_savings_ratio", "median")
    )
)

display(target_affordability_summary)

Target funding months:

count     7870.000000
mean        29.069985
std        236.698735
min          4.493073
10%          5.405043
25%          6.772005
50%          9.371060
75%         17.533320
90%         34.316365
95%         57.081389
99%        262.451922
max      13840.977053
Name: target_funding_months, dtype: float64

Target-to-savings ratio:

count    10000.000000
mean         1.854005
std         18.381793
min          0.290390
10%          0.493942
25%          0.649122
50%          1.000000
75%          1.679511
90%          2.865267
95%          4.522871
99%          9.331715
max       1751.784507
Name: target_to_savings_ratio, dtype: float64

Target funding months by financial situation:

,users,median_target,median_capacity,median_funding_months,median_target_savings_ratio
financial_situation,,,,,
financial_stress,474,77093.078084,0.000000,85.714354,2.791554
high_saving,2043,139093.444220,23219.907212,5.704815,0.511482
low_saving,2923,91129.239398,789.359726,19.002382,1.598537
moderate_saving,4560,110099.028986,9334.052441,9.630772,0.870146

In [80]:
# 10.5.12. Investigate Extreme Goal Funding Requirements

# Identify users with the largest target funding requirements
extreme_funding_users = (
    synthetic_users[
        synthetic_users["goal_funding_capacity"] > 0
    ]
    .sort_values("target_funding_months", ascending=False)
    [
        [
            "user_id",
            "financial_situation",
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "goal_funding_capacity",
            "annual_income",
            "initial_savings",
            "target_amount",
            "target_funding_months"
        ]
    ]
    .head(20)
)

print("Users with the largest target funding requirements:")
display(extreme_funding_users)

Users with the largest target funding requirements:

,user_id,financial_situation,monthly_income,monthly_expenditure,monthly_emi,goal_funding_capacity,annual_income,initial_savings,target_amount,target_funding_months
4228,USER_04229,moderate_saving,124030.194414,91000.0,33010.063959,20.130454,1.488362e+06,438434.593959,278625.157747,13840.977053
4842,USER_04843,moderate_saving,49236.105854,38000.0,11225.011889,11.093965,5.908333e+05,206688.692539,110605.468493,9969.877557
3821,USER_03822,moderate_saving,38750.650261,30000.0,8737.292195,13.358065,4.650078e+05,47310.674172,87050.625799,6516.709150
1029,USER_01030,low_saving,40069.997058,33000.0,7044.420975,25.576083,4.808400e+05,41637.503036,90014.446111,3519.477384
4374,USER_04375,moderate_saving,16511.003833,13000.0,3499.295293,11.708540,1.981320e+05,54100.015472,37090.815420,3167.842839
678,USER_00679,financial_stress,51039.252999,51000.0,0.000000,39.252999,6.124710e+05,17545.882288,114656.112451,2920.951663
8688,USER_08689,moderate_saving,72132.656251,54000.0,18076.779914,55.876337,8.655919e+05,148943.336450,162040.967699,2899.992648
7966,USER_07967,moderate_saving,60691.917068,48000.0,12644.878440,47.038628,7.283030e+05,56449.621045,136340.147228,2898.472008
6073,USER_06074,moderate_saving,65475.829206,51000.0,14413.275627,62.553579,7.857100e+05,126191.408333,147086.871284,2351.374200
4699,USER_04700,financial_stress,43042.674553,43000.0,0.000000,42.674553,5.165121e+05,60827.313506,96692.358211,2265.808327
3956,USER_03957,low_saving,78913.416637,66000.0,12826.189836,87.226801,9.469610e+05,98781.881133,177273.471696,2032.328017
5986,USER_05987,moderate_saving,68141.856663,54200.0,13863.459501,78.397162,8.177023e+05,319750.596354,153075.915519,1952.569603
3505,USER_03506,moderate_saving,118463.348794,84500.0,33819.791554,143.557241,1.421560e+06,174343.927983,266119.628378,1853.752742
580,USER_00581,moderate_saving,48311.371918,34500.0,13750.830954,60.540964,5.797365e+05,162963.355801,108528.118377,1792.639409
4966,USER_04967,financial_stress,35045.780001,35000.0,0.000000,45.780001,4.205494e+05,44980.340960,78727.893859,1719.700566
1537,USER_01538,low_saving,186349.805207,150000.0,36085.563158,264.242048,2.236198e+06,184556.518271,418621.805094,1584.236150
5192,USER_05193,low_saving,59581.266669,49700.0,9794.098929,87.167740,7.149752e+05,28371.605504,133845.148779,1535.489490
5938,USER_05939,moderate_saving,37811.886444,27700.0,10053.843162,58.043282,4.537426e+05,107103.380905,84941.758536,1463.421020
1878,USER_01879,moderate_saving,245761.714593,177000.0,68370.372227,391.342366,2.949141e+06,370939.323255,552086.504582,1410.750670
1311,USER_01312,low_saving,22114.740510,18000.0,4077.528346,37.212164,2.653769e+05,35441.806408,49679.217970,1335.026317

In [81]:
# 10.5.13. Derive Data-Driven Goal Allocation Capacity

# Positive post-EMI surplus is the maximum theoretical funding capacity.
positive_post_emi = np.maximum(
    synthetic_users["post_emi_surplus"],
    0
)

# Calculate the population-relative percentile of available surplus.
synthetic_users["surplus_capacity_percentile"] = (
    positive_post_emi.rank(method="average", pct=True)
)

# Combine surplus capacity with existing savings-buffer strength.
# Equal contribution is used because the available synthetic data
# does not provide empirical evidence for unequal weighting.
synthetic_users["goal_allocation_strength"] = (
    synthetic_users["surplus_capacity_percentile"]
    + synthetic_users["goal_capacity_percentile"]
) / 2

# Convert the relative strength into a goal allocation factor.
# The factor remains population-derived rather than using a fixed
# percentage such as 20%, 30%, or 50%.
synthetic_users["goal_allocation_factor"] = (
    synthetic_users["goal_allocation_strength"]
)

# Calculate the amount of monthly surplus available specifically
# for this synthetic goal.
synthetic_users["goal_specific_monthly_capacity"] = (
    positive_post_emi
    * synthetic_users["goal_allocation_factor"]
)

print("Goal allocation factor:")
display(
    synthetic_users["goal_allocation_factor"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nGoal-specific monthly capacity:")
display(
    synthetic_users["goal_specific_monthly_capacity"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nComparison with previous capacity:")
display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "post_emi_surplus",
            "goal_funding_capacity",
            "goal_allocation_factor",
            "goal_specific_monthly_capacity"
        ]
    ].head(10)
)

Goal allocation factor:

count    10000.000000
mean         0.500050
std          0.287291
min          0.106550
10%          0.106550
25%          0.250075
50%          0.500050
75%          0.750025
90%          0.900010
95%          0.950005
99%          0.990001
max          1.000000
Name: goal_allocation_factor, dtype: float64

Goal-specific monthly capacity:

count     10000.000000
mean      10408.069934
std       18578.095127
min           0.000000
10%           0.000000
25%         304.680019
50%        3802.625086
75%       12801.743318
90%       27924.132321
95%       41781.994413
99%       85138.504241
max      401353.251371
Name: goal_specific_monthly_capacity, dtype: float64

Comparison with previous capacity:

,user_id,financial_situation,post_emi_surplus,goal_funding_capacity,goal_allocation_factor,goal_specific_monthly_capacity
0,USER_00001,moderate_saving,14481.335334,14481.335334,0.69770,10103.627663
1,USER_00002,financial_stress,0.000000,0.000000,0.10655,0.000000
2,USER_00003,low_saving,2467.548430,2467.548430,0.30330,748.407439
3,USER_00004,moderate_saving,1045.743136,1045.743136,0.24420,255.370474
4,USER_00005,high_saving,40719.010189,40719.010189,0.94170,38345.091895
5,USER_00006,high_saving,22096.549442,22096.549442,0.82320,18189.879501
6,USER_00007,high_saving,26988.382060,26988.382060,0.87160,23523.073803
7,USER_00008,low_saving,0.000000,0.000000,0.10655,0.000000
8,USER_00009,moderate_saving,27284.850834,27284.850834,0.87490,23871.515994
9,USER_00010,low_saving,5047.201045,5047.201045,0.40940,2066.324108

In [82]:
# 10.5.14. Generate Population-Relative Goal Allocation Capacity

# Use post-EMI surplus as the underlying financial capacity measure.
positive_post_emi = np.maximum(
    synthetic_users["post_emi_surplus"],
    0
)

# Rank users relative to the synthetic population.
# This gives each user a population-relative measure of available capacity.
synthetic_users["goal_allocation_percentile"] = (
    positive_post_emi.rank(method="average", pct=True)
)

# Allocate the user's available surplus according to
# their population-relative financial capacity.
synthetic_users["goal_specific_monthly_capacity"] = (
    positive_post_emi
    * synthetic_users["goal_allocation_percentile"]
)

print("Population-relative goal allocation:")
display(
    synthetic_users["goal_allocation_percentile"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nGoal-specific monthly capacity:")
display(
    synthetic_users["goal_specific_monthly_capacity"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nSample comparison:")
display(
    synthetic_users[
        [
            "user_id",
            "financial_situation",
            "post_emi_surplus",
            "goal_allocation_percentile",
            "goal_specific_monthly_capacity"
        ]
    ].head(10)
)

Population-relative goal allocation:

count    10000.000000
mean         0.500050
std          0.287291
min          0.106550
10%          0.106550
25%          0.250075
50%          0.500050
75%          0.750025
90%          0.900010
95%          0.950005
99%          0.990001
max          1.000000
Name: goal_allocation_percentile, dtype: float64

Goal-specific monthly capacity:

count     10000.000000
mean      10408.069934
std       18578.095127
min           0.000000
10%           0.000000
25%         304.680019
50%        3802.625086
75%       12801.743318
90%       27924.132321
95%       41781.994413
99%       85138.504241
max      401353.251371
Name: goal_specific_monthly_capacity, dtype: float64

Sample comparison:

,user_id,financial_situation,post_emi_surplus,goal_allocation_percentile,goal_specific_monthly_capacity
0,USER_00001,moderate_saving,14481.335334,0.69770,10103.627663
1,USER_00002,financial_stress,0.000000,0.10655,0.000000
2,USER_00003,low_saving,2467.548430,0.30330,748.407439
3,USER_00004,moderate_saving,1045.743136,0.24420,255.370474
4,USER_00005,high_saving,40719.010189,0.94170,38345.091895
5,USER_00006,high_saving,22096.549442,0.82320,18189.879501
6,USER_00007,high_saving,26988.382060,0.87160,23523.073803
7,USER_00008,low_saving,0.000000,0.10655,0.000000
8,USER_00009,moderate_saving,27284.850834,0.87490,23871.515994
9,USER_00010,low_saving,5047.201045,0.40940,2066.324108

In [83]:
# 10.5.15. Validate Target Amount Across Goal Horizons

target_horizon_summary = (
    synthetic_users
    .groupby("goal_horizon_type", observed=True)
    .agg(
        users=("user_id", "count"),
        median_target=("target_amount", "median"),
        mean_target=("target_amount", "mean"),
        median_income=("annual_income", "median"),
        median_capacity=("goal_specific_monthly_capacity", "median"),
        median_target_to_savings=("target_to_savings_ratio", "median")
    )
)

print("Target amount across goal horizons:")
display(target_horizon_summary)

print("\nTarget amount correlation with key financial variables:")

correlation_columns = [
    "target_amount",
    "annual_income",
    "initial_savings",
    "goal_specific_monthly_capacity",
    "goal_horizon_months"
]

display(
    synthetic_users[correlation_columns]
    .corr()["target_amount"]
    .sort_values(ascending=False)
)

Target amount across goal horizons:

,users,median_target,mean_target,median_income,median_capacity,median_target_to_savings
goal_horizon_type,,,,,,
immediate,91,122930.537375,147172.954867,656671.432257,3272.673853,1.139987
short_term,2669,106875.607038,136445.931522,570909.063324,4112.493395,0.990967
medium_term,3081,105663.701050,136069.677451,564435.293194,3499.737207,1.004200
long_term,4159,108145.545245,141077.360754,577692.830477,3826.344099,0.997125

Target amount correlation with key financial variables:

annual_income                     1.000000
target_amount                     1.000000
initial_savings                   0.793652
goal_specific_monthly_capacity    0.763039
goal_horizon_months               0.014456
Name: target_amount, dtype: float64

11. Economic Environment Construction

In [84]:
# 11.1. Load and Inspect Economic Environment Data

import os
import pandas as pd
import numpy as np

# Define the economic-data directory
economic_data_path = "/content/drive/MyDrive/final_simulation_inputs"

# Load prepared economic datasets
cpi_data = pd.read_csv(
    os.path.join(economic_data_path, "cpi_scaled.csv")
)

market_data = pd.read_csv(
    os.path.join(economic_data_path, "market_scaled.csv")
)

walr_data = pd.read_csv(
    os.path.join(economic_data_path, "walr_scaled.csv")
)

# Display basic dataset information
print("CPI dataset shape:", cpi_data.shape)
print("Market dataset shape:", market_data.shape)
print("WALR dataset shape:", walr_data.shape)

print("\nCPI columns:")
print(cpi_data.columns.tolist())

print("\nMarket columns:")
print(market_data.columns.tolist())

print("\nWALR columns:")
print(walr_data.columns.tolist())

CPI dataset shape: (48, 11)
Market dataset shape: (144, 13)
WALR dataset shape: (47, 7)

CPI columns:
['period', 'rural_cpi', 'urban_cpi', 'combined_cpi', 'rural_inflation', 'urban_inflation', 'combined_inflation', 'combined_cpi_change', 'combined_cpi_pct_change', 'rural_urban_avg_cpi', 'combined_cpi_3m_ma']

Market columns:
['period', 'nifty_open', 'nifty_high', 'nifty_low', 'nifty_close', 'nifty_avg_close', 'nifty_total_volume', 'nifty_avg_daily_return', 'nifty_return_volatility', 'nifty_monthly_return', 'nifty_3m_volatility', 'nifty_3m_ma', 'nifty_ma_gap']

WALR columns:
['period', 'average_walr', 'walr_change', 'walr_pct_change', 'credit_pressure', 'walr_3period_ma', 'walr_momentum']

In [85]:
# Inspect the first few observations

print("CPI data:")
display(cpi_data.head())

print("\nMarket data:")
display(market_data.head())

print("\nWALR data:")
display(walr_data.head())

CPI data:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
0,2011-01-01,0.014634,0.012723,0.014925,0.681068,0.739506,0.762137,0.622888,0.622888,0.013733,0.515980
1,2011-02-01,0.000000,0.000000,0.000000,0.681068,0.739506,0.762137,0.157750,0.157750,0.000000,0.515980
2,2011-03-01,0.009756,0.005089,0.007463,0.681068,0.739506,0.762137,0.464605,0.464605,0.007491,0.000000
3,2011-04-01,0.024390,0.020356,0.022388,0.681068,0.739506,0.762137,0.566694,0.566694,0.022472,0.002523
4,2011-05-01,0.053659,0.033079,0.044776,0.681068,0.739506,0.762137,0.667339,0.667339,0.043695,0.017662

Market data:

,period,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap
0,2015-01-01,0.063711,0.020308,0.049571,0.094810,0.055464,0.098835,0.468737,0.027470,0.637516,0.175845,0.342082,0.714584
1,2015-02-01,0.061725,0.020557,0.045385,0.096667,0.059289,0.094047,0.445944,0.218661,0.623620,0.175845,0.342082,0.714584
2,2015-03-01,0.080619,0.022784,0.051830,0.078266,0.052741,0.117774,0.347115,0.169805,0.507522,0.175845,0.069138,0.590410
3,2015-04-01,0.078900,0.018634,0.041618,0.062159,0.046457,0.127190,0.361995,0.237883,0.516826,0.123433,0.057887,0.545167
4,2015-05-01,0.060833,0.019485,0.059884,0.075281,0.046950,0.113081,0.473738,0.064071,0.694196,0.205132,0.050518,0.712124

WALR data:

,period,average_walr,walr_change,walr_pct_change,credit_pressure,walr_3period_ma,walr_momentum
0,2014-03-01,1.000000,0.433333,0.419612,1.0,0.404880,0.315726
1,2014-12-01,0.939462,0.266330,0.296640,1.0,0.404880,0.315726
2,2015-03-01,0.920344,0.437711,0.434739,1.0,1.000000,0.289898
3,2015-06-01,0.888482,0.384979,0.390690,1.0,0.958939,0.315726
4,2015-09-01,0.856620,0.384979,0.389755,1.0,0.928436,0.295064

In [86]:
# Check missing values in the economic datasets

print("Missing values in CPI:")
display(cpi_data.isnull().sum())

print("\nMissing values in Market:")
display(market_data.isnull().sum())

print("\nMissing values in WALR:")
display(walr_data.isnull().sum())

Missing values in CPI:

period                     0
rural_cpi                  0
urban_cpi                  0
combined_cpi               0
rural_inflation            0
urban_inflation            0
combined_inflation         0
combined_cpi_change        0
combined_cpi_pct_change    0
rural_urban_avg_cpi        0
combined_cpi_3m_ma         0
dtype: int64

Missing values in Market:

period                     0
nifty_open                 0
nifty_high                 0
nifty_low                  0
nifty_close                0
nifty_avg_close            0
nifty_total_volume         0
nifty_avg_daily_return     0
nifty_return_volatility    0
nifty_monthly_return       0
nifty_3m_volatility        0
nifty_3m_ma                0
nifty_ma_gap               0
dtype: int64

Missing values in WALR:

period             0
average_walr       0
walr_change        0
walr_pct_change    0
credit_pressure    0
walr_3period_ma    0
walr_momentum      0
dtype: int64

In [87]:
# Summary statistics for numerical variables

print("CPI numerical summary:")
display(cpi_data.describe())

print("\nMarket numerical summary:")
display(market_data.describe())

print("\nWALR numerical summary:")
display(walr_data.describe())

CPI numerical summary:

,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,0.508283,0.524597,0.515703,0.652026,0.660159,0.699445,0.603733,0.603733,0.517556,0.516225
std,0.319573,0.322372,0.320968,0.186102,0.228809,0.209673,0.225761,0.225761,0.321552,0.308186
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.215854,0.229644,0.218284,0.638211,0.530718,0.644574,0.472662,0.472662,0.220350,0.225610
50%,0.502439,0.527990,0.513682,0.681068,0.739506,0.762137,0.622888,0.622888,0.515605,0.515980
75%,0.806098,0.804071,0.805970,0.736363,0.809633,0.807043,0.771392,0.771392,0.806492,0.808242
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Market numerical summary:

,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap
count,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000
mean,0.404616,0.450249,0.428847,0.434477,0.435123,0.294905,0.449984,0.189451,0.634001,0.196064,0.423568,0.709424
std,0.319635,0.362754,0.349694,0.317240,0.339966,0.183783,0.114484,0.156633,0.119870,0.142460,0.323828,0.120829
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.146928,0.139501,0.102929,0.162235,0.137167,0.165754,0.394563,0.099576,0.567605,0.119920,0.152702,0.648008
50%,0.310506,0.407175,0.323472,0.354973,0.355264,0.257196,0.449489,0.152372,0.637516,0.175845,0.342082,0.714584
75%,0.619320,0.786795,0.711324,0.767077,0.749268,0.351845,0.503064,0.216249,0.705347,0.235785,0.705034,0.785683
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

WALR numerical summary:

,average_walr,walr_change,walr_pct_change,credit_pressure,walr_3period_ma,walr_momentum
count,47.000000,47.000000,47.000000,47.000000,47.000000,47.000000
mean,0.448440,0.437368,0.428339,0.680851,0.435865,0.358015
std,0.258002,0.201217,0.199765,0.471186,0.262696,0.215208
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.266040,0.295336,0.296669,0.000000,0.257659,0.195387
50%,0.422150,0.433333,0.419612,1.000000,0.404880,0.315726
75%,0.573918,0.515116,0.498426,1.000000,0.531814,0.468658
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [88]:
# 11.2. Economic Time Period Alignment

# Convert period columns to datetime
cpi_data["period"] = pd.to_datetime(cpi_data["period"])
market_data["period"] = pd.to_datetime(market_data["period"])
walr_data["period"] = pd.to_datetime(walr_data["period"])

# Sort chronologically
cpi_data = cpi_data.sort_values("period").reset_index(drop=True)
market_data = market_data.sort_values("period").reset_index(drop=True)
walr_data = walr_data.sort_values("period").reset_index(drop=True)

# Display date ranges
print("CPI period:")
print(cpi_data["period"].min(), "to", cpi_data["period"].max())

print("\nMarket period:")
print(market_data["period"].min(), "to", market_data["period"].max())

print("\nWALR period:")
print(walr_data["period"].min(), "to", walr_data["period"].max())

CPI period:
2011-01-01 00:00:00 to 2014-12-01 00:00:00

Market period:
2015-01-01 00:00:00 to 2026-12-01 00:00:00

WALR period:
2014-03-01 00:00:00 to 2026-03-01 00:00:00

In [89]:
# Check the actual time gaps between observations

def inspect_period_gaps(data, name):
    periods = data["period"].sort_values()

    gaps = periods.diff().dropna()

    print(f"\n{name}")
    print("Number of observations:", len(data))
    print("Unique periods:", data["period"].nunique())
    print("Most common time gaps:")
    display(gaps.value_counts().head(10))


inspect_period_gaps(cpi_data, "CPI")
inspect_period_gaps(market_data, "Market")
inspect_period_gaps(walr_data, "WALR")

CPI
Number of observations: 48
Unique periods: 48
Most common time gaps:

period
31 days    27
30 days    16
28 days     3
29 days     1
Name: count, dtype: int64

Market
Number of observations: 144
Unique periods: 144
Most common time gaps:

period
31 days    83
30 days    48
28 days     9
29 days     3
Name: count, dtype: int64

WALR
Number of observations: 47
Unique periods: 47
Most common time gaps:

period
92 days     22
91 days     14
90 days      9
275 days     1
Name: count, dtype: int64

In [90]:
# Determine the overlapping period shared by all three datasets

common_start = max(
    cpi_data["period"].min(),
    market_data["period"].min(),
    walr_data["period"].min()
)

common_end = min(
    cpi_data["period"].max(),
    market_data["period"].max(),
    walr_data["period"].max()
)

print("Common economic simulation period:")
print(common_start, "to", common_end)

print("\nNumber of observations within common period:")

print(
    "CPI:",
    ((cpi_data["period"] >= common_start) &
     (cpi_data["period"] <= common_end)).sum()
)

print(
    "Market:",
    ((market_data["period"] >= common_start) &
     (market_data["period"] <= common_end)).sum()
)

print(
    "WALR:",
    ((walr_data["period"] >= common_start) &
     (walr_data["period"] <= common_end)).sum()
)

Common economic simulation period:
2015-01-01 00:00:00 to 2014-12-01 00:00:00

Number of observations within common period:
CPI: 0
Market: 0
WALR: 0

In [91]:
# 11.2.1. Determine the Usable Economic Simulation Period

print("===== Economic Dataset Coverage =====")

print(f"CPI:")
print(f"  Start: {cpi_data['period'].min().date()}")
print(f"  End:   {cpi_data['period'].max().date()}")
print(f"  Observations: {len(cpi_data)}")

print("\nMarket:")
print(f"  Start: {market_data['period'].min().date()}")
print(f"  End:   {market_data['period'].max().date()}")
print(f"  Observations: {len(market_data)}")

print("\nWALR:")
print(f"  Start: {walr_data['period'].min().date()}")
print(f"  End:   {walr_data['period'].max().date()}")
print(f"  Observations: {len(walr_data)}")


# Check whether CPI has complete monthly coverage
cpi_months = cpi_data["period"].dt.to_period("M")
market_months = market_data["period"].dt.to_period("M")
walr_months = walr_data["period"].dt.to_period("M")

print("\n===== Unique Month Coverage =====")

print("CPI unique months:", cpi_months.nunique())
print("Market unique months:", market_months.nunique())
print("WALR unique months:", walr_months.nunique())


# Display the actual CPI periods
print("\n===== CPI Periods =====")
display(cpi_data[["period", "combined_inflation"]].head(10))
display(cpi_data[["period", "combined_inflation"]].tail(10))

===== Economic Dataset Coverage =====
CPI:
  Start: 2011-01-01
  End:   2014-12-01
  Observations: 48

Market:
  Start: 2015-01-01
  End:   2026-12-01
  Observations: 144

WALR:
  Start: 2014-03-01
  End:   2026-03-01
  Observations: 47

===== Unique Month Coverage =====
CPI unique months: 48
Market unique months: 144
WALR unique months: 47

===== CPI Periods =====

      period  combined_inflation
0 2011-01-01            0.762137
1 2011-02-01            0.762137
2 2011-03-01            0.762137
3 2011-04-01            0.762137
4 2011-05-01            0.762137
5 2011-06-01            0.762137
6 2011-07-01            0.762137
7 2011-08-01            0.762137
8 2011-09-01            0.762137
9 2011-10-01            0.762137

       period  combined_inflation
38 2014-03-01            0.582386
39 2014-04-01            0.622428
40 2014-05-01            0.577699
41 2014-06-01            0.457041
42 2014-07-01            0.531141
43 2014-08-01            0.496370
44 2014-09-01            0.310969
45 2014-10-01            0.179194
46 2014-11-01            0.000000
47 2014-12-01            0.086300

In [92]:
# 11.2.2. Inspect Economic Feature Ranges and Relationships

print("===== CPI Feature Ranges =====")
display(
    cpi_data.describe()
    .T[["min", "25%", "50%", "75%", "max"]]
)

print("\n===== Market Feature Ranges =====")
display(
    market_data.describe()
    .T[["min", "25%", "50%", "75%", "max"]]
)

print("\n===== WALR Feature Ranges =====")
display(
    walr_data.describe()
    .T[["min", "25%", "50%", "75%", "max"]]
)

===== CPI Feature Ranges =====

,min,25%,50%,75%,max
period,2011-01-01 00:00:00,2011-12-24 06:00:00,2012-12-16 12:00:00,2013-12-08 18:00:00,2014-12-01 00:00:00
rural_cpi,0.0,0.215854,0.502439,0.806098,1.0
urban_cpi,0.0,0.229644,0.52799,0.804071,1.0
combined_cpi,0.0,0.218284,0.513682,0.80597,1.0
rural_inflation,0.0,0.638211,0.681068,0.736363,1.0
urban_inflation,0.0,0.530718,0.739506,0.809633,1.0
combined_inflation,0.0,0.644574,0.762137,0.807043,1.0
combined_cpi_change,0.0,0.472662,0.622888,0.771392,1.0
combined_cpi_pct_change,0.0,0.472662,0.622888,0.771392,1.0
rural_urban_avg_cpi,0.0,0.22035,0.515605,0.806492,1.0
combined_cpi_3m_ma,0.0,0.22561,0.51598,0.808242,1.0

===== Market Feature Ranges =====

,min,25%,50%,75%,max
period,2015-01-01 00:00:00,2017-12-24 06:00:00,2020-12-16 12:00:00,2023-12-08 18:00:00,2026-12-01 00:00:00
nifty_open,0.0,0.146928,0.310506,0.61932,1.0
nifty_high,0.0,0.139501,0.407175,0.786795,1.0
nifty_low,0.0,0.102929,0.323472,0.711324,1.0
nifty_close,0.0,0.162235,0.354973,0.767077,1.0
nifty_avg_close,0.0,0.137167,0.355264,0.749268,1.0
nifty_total_volume,0.0,0.165754,0.257196,0.351845,1.0
nifty_avg_daily_return,0.0,0.394563,0.449489,0.503064,1.0
nifty_return_volatility,0.0,0.099576,0.152372,0.216249,1.0
nifty_monthly_return,0.0,0.567605,0.637516,0.705347,1.0
nifty_3m_volatility,0.0,0.11992,0.175845,0.235785,1.0
nifty_3m_ma,0.0,0.152702,0.342082,0.705034,1.0
nifty_ma_gap,0.0,0.648008,0.714584,0.785683,1.0

===== WALR Feature Ranges =====

,min,25%,50%,75%,max
period,2014-03-01 00:00:00,2017-07-17 00:00:00,2020-06-01 00:00:00,2023-04-16 00:00:00,2026-03-01 00:00:00
average_walr,0.0,0.26604,0.42215,0.573918,1.0
walr_change,0.0,0.295336,0.433333,0.515116,1.0
walr_pct_change,0.0,0.296669,0.419612,0.498426,1.0
credit_pressure,0.0,0.0,1.0,1.0,1.0
walr_3period_ma,0.0,0.257659,0.40488,0.531814,1.0
walr_momentum,0.0,0.195387,0.315726,0.468658,1.0

In [93]:
# 11.3. Analyze Economic Regimes Using Population Quantiles

def add_regime(data, column):
    q33 = data[column].quantile(1/3)
    q67 = data[column].quantile(2/3)

    return pd.cut(
        data[column],
        bins=[-np.inf, q33, q67, np.inf],
        labels=["low", "medium", "high"],
        include_lowest=True
    )


# CPI inflation regime
cpi_data["inflation_regime"] = add_regime(
    cpi_data,
    "combined_inflation"
)

# Market return regime
market_data["market_return_regime"] = add_regime(
    market_data,
    "nifty_monthly_return"
)

# Market volatility regime
market_data["market_volatility_regime"] = add_regime(
    market_data,
    "nifty_return_volatility"
)

# WALR regime
walr_data["walr_regime"] = add_regime(
    walr_data,
    "average_walr"
)


print("===== CPI Inflation Regimes =====")
display(
    cpi_data["inflation_regime"]
    .value_counts()
    .sort_index()
)

print("\n===== Market Return Regimes =====")
display(
    market_data["market_return_regime"]
    .value_counts()
    .sort_index()
)

print("\n===== Market Volatility Regimes =====")
display(
    market_data["market_volatility_regime"]
    .value_counts()
    .sort_index()
)

print("\n===== WALR Regimes =====")
display(
    walr_data["walr_regime"]
    .value_counts()
    .sort_index()
)

===== CPI Inflation Regimes =====

inflation_regime
low       16
medium    16
high      16
Name: count, dtype: int64

===== Market Return Regimes =====

market_return_regime
low       48
medium    48
high      48
Name: count, dtype: int64

===== Market Volatility Regimes =====

market_volatility_regime
low       48
medium    48
high      48
Name: count, dtype: int64

===== WALR Regimes =====

walr_regime
low       16
medium    15
high      16
Name: count, dtype: int64

In [94]:
# 11.4. Create Monthly Simulation Calendar

simulation_calendar = pd.DataFrame({
    "period": market_data["period"]
})

simulation_calendar = (
    simulation_calendar
    .drop_duplicates()
    .sort_values("period")
    .reset_index(drop=True)
)

print("===== Monthly Simulation Calendar =====")

print("Start period:", simulation_calendar["period"].min().date())
print("End period:", simulation_calendar["period"].max().date())
print("Number of months:", len(simulation_calendar))

print("\nFirst 5 periods:")
display(simulation_calendar.head())

print("\nLast 5 periods:")
display(simulation_calendar.tail())

# Verify that the calendar is continuous month-by-month
month_difference = (
    simulation_calendar["period"]
    .dt.to_period("M")
    .diff()
    .dropna()
)

print("\nUnique month differences:")
display(month_difference.value_counts())

===== Monthly Simulation Calendar =====
Start period: 2015-01-01
End period: 2026-12-01
Number of months: 144

First 5 periods:

      period
0 2015-01-01
1 2015-02-01
2 2015-03-01
3 2015-04-01
4 2015-05-01

Last 5 periods:

        period
139 2026-08-01
140 2026-09-01
141 2026-10-01
142 2026-11-01
143 2026-12-01

Unique month differences:

period
<MonthEnd>    143
Name: count, dtype: int64

In [95]:
# 11.5. Inflation Calibration from Historical CPI Data

inflation_features = [
    "combined_inflation",
    "combined_cpi_change",
    "combined_cpi_pct_change",
    "combined_cpi_3m_ma"
]

print("===== Historical CPI Inflation Calibration =====")

inflation_calibration = cpi_data[inflation_features].describe().T[
    ["min", "25%", "50%", "75%", "max", "mean", "std"]
]

display(inflation_calibration)


print("\n===== Inflation Regime Distribution =====")

inflation_regime_summary = (
    cpi_data["inflation_regime"]
    .value_counts()
    .sort_index()
    .to_frame("observations")
)

inflation_regime_summary["proportion"] = (
    inflation_regime_summary["observations"]
    / len(cpi_data)
)

display(inflation_regime_summary)


print("\n===== Historical Inflation Regime Thresholds =====")

inflation_q33 = cpi_data["combined_inflation"].quantile(1/3)
inflation_q67 = cpi_data["combined_inflation"].quantile(2/3)

print(f"33rd percentile: {inflation_q33:.6f}")
print(f"67th percentile: {inflation_q67:.6f}")

===== Historical CPI Inflation Calibration =====

,min,25%,50%,75%,max,mean,std
combined_inflation,0.0,0.644574,0.762137,0.807043,1.0,0.699445,0.209673
combined_cpi_change,0.0,0.472662,0.622888,0.771392,1.0,0.603733,0.225761
combined_cpi_pct_change,0.0,0.472662,0.622888,0.771392,1.0,0.603733,0.225761
combined_cpi_3m_ma,0.0,0.225610,0.515980,0.808242,1.0,0.516225,0.308186

===== Inflation Regime Distribution =====

                  observations  proportion
inflation_regime
low                         16    0.333333
medium                      16    0.333333
high                        16    0.333333

===== Historical Inflation Regime Thresholds =====
33rd percentile: 0.731774
67th percentile: 0.778697

In [96]:
# 11.6. Construct Monthly Inflation Environment

np.random.seed(50)

inflation_source = cpi_data[
    [
        "combined_inflation",
        "combined_cpi_change",
        "combined_cpi_pct_change",
        "combined_cpi_3m_ma",
        "inflation_regime"
    ]
].copy()

# Sample historical CPI observations for each simulation month
sampled_inflation = inflation_source.sample(
    n=len(simulation_calendar),
    replace=True,
    random_state=50
).reset_index(drop=True)

# Attach sampled inflation conditions to the simulation calendar
simulation_calendar["inflation_level"] = (
    sampled_inflation["combined_inflation"]
)

simulation_calendar["inflation_change"] = (
    sampled_inflation["combined_cpi_change"]
)

simulation_calendar["inflation_pct_change"] = (
    sampled_inflation["combined_cpi_pct_change"]
)

simulation_calendar["inflation_trend"] = (
    sampled_inflation["combined_cpi_3m_ma"]
)

simulation_calendar["inflation_regime"] = (
    sampled_inflation["inflation_regime"]
)

print("===== Monthly Inflation Environment =====")

print("Number of simulation months:", len(simulation_calendar))

print("\nInflation regime distribution:")
display(
    simulation_calendar["inflation_regime"]
    .value_counts()
    .sort_index()
)

print("\nInflation feature summary:")
display(
    simulation_calendar[
        [
            "inflation_level",
            "inflation_change",
            "inflation_pct_change",
            "inflation_trend"
        ]
    ].describe().T
)

print("\nFirst 10 simulation months:")
display(
    simulation_calendar[
        [
            "period",
            "inflation_level",
            "inflation_change",
            "inflation_pct_change",
            "inflation_trend",
            "inflation_regime"
        ]
    ].head(10)
)

===== Monthly Inflation Environment =====
Number of simulation months: 144

Inflation regime distribution:

inflation_regime
low       46
medium    61
high      37
Name: count, dtype: int64

Inflation feature summary:

,count,mean,std,min,25%,50%,75%,max
inflation_level,144.0,0.677915,0.212971,0.0,0.651957,0.762137,0.783425,0.945091
inflation_change,144.0,0.599643,0.242116,0.0,0.464605,0.634226,0.789164,1.000000
inflation_pct_change,144.0,0.599643,0.242116,0.0,0.464605,0.634226,0.789164,1.000000
inflation_trend,144.0,0.526449,0.318339,0.0,0.225610,0.539108,0.811606,1.000000

First 10 simulation months:

,period,inflation_level,inflation_change,inflation_pct_change,inflation_trend,inflation_regime
0,2015-01-01,0.805801,0.790319,0.790319,0.732548,high
1,2015-02-01,0.762137,0.204009,0.204009,0.207738,medium
2,2015-03-01,0.179194,0.411640,0.411640,0.995795,low
3,2015-04-01,0.854063,0.732367,0.732367,0.770395,high
4,2015-05-01,0.776332,0.828178,0.828178,0.646762,medium
5,2015-06-01,0.762137,0.667339,0.667339,0.017662,medium
6,2015-07-01,0.762137,0.925027,0.925027,0.080740,medium
7,2015-08-01,0.540113,0.335703,0.335703,0.806560,low
8,2015-09-01,0.762137,0.925027,0.925027,0.080740,medium
9,2015-10-01,0.794167,0.506200,0.506200,0.483600,high

In [97]:
# 11.7. Attach Historical Market Environment

market_environment = market_data[
    [
        "period",
        "nifty_monthly_return",
        "nifty_return_volatility",
        "nifty_3m_volatility",
        "nifty_ma_gap",
        "market_return_regime",
        "market_volatility_regime"
    ]
].copy()

# Ensure one observation exists for each simulation month
market_environment = (
    market_environment
    .drop_duplicates(subset=["period"])
    .sort_values("period")
    .reset_index(drop=True)
)

# Merge the historical market conditions with the simulation calendar
simulation_calendar = simulation_calendar.merge(
    market_environment,
    on="period",
    how="left",
    validate="one_to_one"
)

print("===== Market Environment Validation =====")

print("Simulation months:", len(simulation_calendar))

print(
    "Months with missing market data:",
    simulation_calendar["nifty_monthly_return"].isna().sum()
)

print("\nMarket return regime distribution:")
display(
    simulation_calendar["market_return_regime"]
    .value_counts()
    .sort_index()
)

print("\nMarket volatility regime distribution:")
display(
    simulation_calendar["market_volatility_regime"]
    .value_counts()
    .sort_index()
)

print("\nFirst 10 months:")
display(
    simulation_calendar[
        [
            "period",
            "nifty_monthly_return",
            "nifty_return_volatility",
            "nifty_3m_volatility",
            "nifty_ma_gap",
            "market_return_regime",
            "market_volatility_regime"
        ]
    ].head(10)
)

===== Market Environment Validation =====
Simulation months: 144
Months with missing market data: 0

Market return regime distribution:

market_return_regime
low       48
medium    48
high      48
Name: count, dtype: int64

Market volatility regime distribution:

market_volatility_regime
low       48
medium    48
high      48
Name: count, dtype: int64

First 10 months:

,period,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,market_return_regime,market_volatility_regime
0,2015-01-01,0.637516,0.027470,0.175845,0.714584,medium,low
1,2015-02-01,0.623620,0.218661,0.175845,0.714584,medium,high
2,2015-03-01,0.507522,0.169805,0.175845,0.590410,low,medium
3,2015-04-01,0.516826,0.237883,0.123433,0.545167,low,high
4,2015-05-01,0.694196,0.064071,0.205132,0.712124,high,low
5,2015-06-01,0.592566,0.073268,0.172611,0.701635,low,low
6,2015-07-01,0.664716,0.226140,0.098883,0.721744,medium,high
7,2015-08-01,0.439413,0.188240,0.224933,0.543599,low,medium
8,2015-09-01,0.605525,0.113610,0.228449,0.593640,medium,low
9,2015-10-01,0.651710,0.118239,0.218102,0.715961,medium,medium

In [98]:
# 11.8. Align WALR Conditions to the Monthly Simulation Calendar

walr_environment = walr_data[
    [
        "period",
        "average_walr",
        "walr_change",
        "walr_pct_change",
        "credit_pressure",
        "walr_3period_ma",
        "walr_momentum",
        "walr_regime"
    ]
].copy()

walr_environment = (
    walr_environment
    .drop_duplicates(subset=["period"])
    .sort_values("period")
    .reset_index(drop=True)
)

# Keep only WALR observations that can contribute to the simulation period.
# merge_asof selects the most recent WALR observation at or before each
# simulation month.
simulation_calendar = pd.merge_asof(
    simulation_calendar.sort_values("period"),
    walr_environment.sort_values("period"),
    on="period",
    direction="backward"
)

print("===== WALR Monthly Alignment Validation =====")

print("Simulation months:", len(simulation_calendar))

print(
    "Months with missing WALR data:",
    simulation_calendar["average_walr"].isna().sum()
)

print("\nWALR regime distribution after monthly alignment:")
display(
    simulation_calendar["walr_regime"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nFirst 15 simulation months:")
display(
    simulation_calendar[
        [
            "period",
            "average_walr",
            "walr_change",
            "credit_pressure",
            "walr_3period_ma",
            "walr_momentum",
            "walr_regime"
        ]
    ].head(15)
)

===== WALR Monthly Alignment Validation =====
Simulation months: 144
Months with missing WALR data: 0

WALR regime distribution after monthly alignment:

walr_regime
low       55
medium    45
high      44
Name: count, dtype: int64

First 15 simulation months:

,period,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum,walr_regime
0,2015-01-01,0.939462,0.266330,1.0,0.404880,0.315726,high
1,2015-02-01,0.939462,0.266330,1.0,0.404880,0.315726,high
2,2015-03-01,0.920344,0.437711,1.0,1.000000,0.289898,high
3,2015-04-01,0.920344,0.437711,1.0,1.000000,0.289898,high
4,2015-05-01,0.920344,0.437711,1.0,1.000000,0.289898,high
5,2015-06-01,0.888482,0.384979,1.0,0.958939,0.315726,high
6,2015-07-01,0.888482,0.384979,1.0,0.958939,0.315726,high
7,2015-08-01,0.888482,0.384979,1.0,0.958939,0.315726,high
8,2015-09-01,0.856620,0.384979,1.0,0.928436,0.295064,high
9,2015-10-01,0.856620,0.384979,1.0,0.928436,0.295064,high
10,2015-11-01,0.856620,0.384979,1.0,0.928436,0.295064,high
11,2015-12-01,0.792896,0.253147,1.0,0.881510,0.191752,high
12,2016-01-01,0.792896,0.253147,1.0,0.881510,0.191752,high
13,2016-02-01,0.792896,0.253147,1.0,0.881510,0.191752,high
14,2016-03-01,0.776965,0.450895,1.0,0.840449,0.295064,high

In [99]:
# 11.9. Validate the Complete Economic Environment

economic_environment_columns = [
    "period",

    # Inflation environment
    "inflation_level",
    "inflation_change",
    "inflation_pct_change",
    "inflation_trend",
    "inflation_regime",

    # Market environment
    "nifty_monthly_return",
    "nifty_return_volatility",
    "nifty_3m_volatility",
    "nifty_ma_gap",
    "market_return_regime",
    "market_volatility_regime",

    # Credit / interest-rate environment
    "average_walr",
    "walr_change",
    "credit_pressure",
    "walr_3period_ma",
    "walr_momentum",
    "walr_regime"
]

economic_environment = simulation_calendar[
    economic_environment_columns
].copy()

print("===== Complete Economic Environment Validation =====")

print("Number of months:", len(economic_environment))
print(
    "Unique periods:",
    economic_environment["period"].nunique()
)

print(
    "Duplicate periods:",
    economic_environment["period"].duplicated().sum()
)

print(
    "Chronologically sorted:",
    economic_environment["period"].is_monotonic_increasing
)

print("\nMissing values:")
display(
    economic_environment.isna().sum().to_frame("missing_values")
)

print("\nEconomic environment shape:")
print(economic_environment.shape)

print("\nFirst 5 months:")
display(economic_environment.head())

print("\nLast 5 months:")
display(economic_environment.tail())

===== Complete Economic Environment Validation =====
Number of months: 144
Unique periods: 144
Duplicate periods: 0
Chronologically sorted: True

Missing values:

                          missing_values
period                                 0
inflation_level                        0
inflation_change                       0
inflation_pct_change                   0
inflation_trend                        0
inflation_regime                       0
nifty_monthly_return                   0
nifty_return_volatility                0
nifty_3m_volatility                    0
nifty_ma_gap                           0
market_return_regime                   0
market_volatility_regime               0
average_walr                           0
walr_change                            0
credit_pressure                        0
walr_3period_ma                        0
walr_momentum                          0
walr_regime                            0

Economic environment shape:
(144, 18)

First 5 months:

,period,inflation_level,inflation_change,inflation_pct_change,inflation_trend,inflation_regime,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,market_return_regime,market_volatility_regime,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum,walr_regime
0,2015-01-01,0.805801,0.790319,0.790319,0.732548,high,0.637516,0.027470,0.175845,0.714584,medium,low,0.939462,0.266330,1.0,0.40488,0.315726,high
1,2015-02-01,0.762137,0.204009,0.204009,0.207738,medium,0.623620,0.218661,0.175845,0.714584,medium,high,0.939462,0.266330,1.0,0.40488,0.315726,high
2,2015-03-01,0.179194,0.411640,0.411640,0.995795,low,0.507522,0.169805,0.175845,0.590410,low,medium,0.920344,0.437711,1.0,1.00000,0.289898,high
3,2015-04-01,0.854063,0.732367,0.732367,0.770395,high,0.516826,0.237883,0.123433,0.545167,low,high,0.920344,0.437711,1.0,1.00000,0.289898,high
4,2015-05-01,0.776332,0.828178,0.828178,0.646762,medium,0.694196,0.064071,0.205132,0.712124,high,low,0.920344,0.437711,1.0,1.00000,0.289898,high

Last 5 months:

,period,inflation_level,inflation_change,inflation_pct_change,inflation_trend,inflation_regime,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,market_return_regime,market_volatility_regime,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum,walr_regime
139,2026-08-01,0.000000,0.436391,0.436391,1.000000,low,0.565757,0.320699,0.099112,0.662735,low,high,0.117761,0.418627,0.0,0.119482,0.263391,low
140,2026-09-01,0.540113,0.335703,0.335703,0.806560,low,0.621849,0.264550,0.091721,0.670086,medium,high,0.117761,0.418627,0.0,0.119482,0.263391,low
141,2026-10-01,0.762137,0.925027,0.925027,0.080740,medium,0.639793,0.353508,0.071440,0.712623,medium,high,0.117761,0.418627,0.0,0.119482,0.263391,low
142,2026-11-01,0.776332,0.828178,0.828178,0.646762,medium,0.499077,0.394138,0.147690,0.589674,low,high,0.117761,0.418627,0.0,0.119482,0.263391,low
143,2026-12-01,0.457041,0.696811,0.696811,0.869638,low,0.665448,0.462584,0.173760,0.677595,medium,high,0.117761,0.418627,0.0,0.119482,0.263391,low

12. Portfolio and Asset Behaviour

In [100]:
## 12.1. Load Final Synthetic User Population

final_population_path = (
    "/content/drive/MyDrive/GoalPilot_AI/"
    "simulation/03_financial_profiles/"
    "synthetic_population_risk.csv"
)

final_population = pd.read_csv(final_population_path)

print("===== Final Synthetic Population =====")

print("Population size:", len(final_population))
print("Number of features:", len(final_population.columns))

print("\nShape:")
print(final_population.shape)

print("\nKey financial columns:")
display(
    final_population[
        [
            "user_id",
            "monthly_income",
            "monthly_expenditure",
            "monthly_surplus",
            "monthly_emi",
            "initial_savings",
            "initial_investment",
            "investment_capacity_ratio",
            "has_investments",
            "risk_score",
            "risk_profile"
        ]
    ].head(10)
)

print("\nMissing values in key columns:")

key_columns = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_surplus",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "has_investments",
    "risk_score",
    "risk_profile"
]

display(
    final_population[key_columns]
    .isna()
    .sum()
    .to_frame("missing_values")
)

===== Final Synthetic Population =====
Population size: 10000
Number of features: 50

Shape:
(10000, 50)

Key financial columns:

,user_id,monthly_income,monthly_expenditure,monthly_surplus,monthly_emi,initial_savings,initial_investment,investment_capacity_ratio,has_investments,risk_score,risk_profile
0,USER_00001,51351.335334,36870.0,14481.335334,0.000000,178733.652470,45777.548120,0.282005,True,0.710500,aggressive
1,USER_00002,26415.417334,27500.0,-1084.582666,11814.371436,13659.350863,0.000000,0.000000,False,0.038363,conservative
2,USER_00003,44467.548430,42000.0,2467.548430,0.000000,85318.549015,0.000000,0.055491,False,0.505350,moderate
3,USER_00004,33598.333991,25500.0,8098.333991,7052.590854,107702.527041,60534.274631,0.031125,True,0.313650,conservative
4,USER_00005,91719.010189,51000.0,40719.010189,0.000000,205810.045973,105774.934379,0.443954,True,0.750750,aggressive
5,USER_00006,49096.549442,27000.0,22096.549442,0.000000,229003.169045,118987.882781,0.450063,True,0.823150,aggressive
6,USER_00007,56988.382060,30000.0,26988.382060,0.000000,126015.560330,90329.680595,0.473577,True,0.762325,aggressive
7,USER_00008,120153.382912,100000.0,20153.382912,24786.376525,26481.524416,0.000000,0.000000,False,0.087587,conservative
8,USER_00009,81284.850834,54000.0,27284.850834,0.000000,165575.931991,0.000000,0.335670,False,0.688500,aggressive
9,USER_00010,43047.201045,38000.0,5047.201045,0.000000,76879.539877,15171.499059,0.117248,True,0.533300,moderate

Missing values in key columns:

                           missing_values
user_id                                 0
monthly_income                          0
monthly_expenditure                     0
monthly_surplus                         0
monthly_emi                             0
initial_savings                         0
initial_investment                      0
investment_capacity_ratio               0
has_investments                         0
risk_score                              0
risk_profile                            0

In [101]:
# 12.2. Inspect Market Return Calibration

market_calibration_path = (
    "/content/drive/MyDrive/final_simulation_inputs/"
    "market_credit_scenarios.csv"
)

market_calibration = pd.read_csv(market_calibration_path)

print("===== Market Calibration Dataset =====")

print("Shape:", market_calibration.shape)

print("\nColumns:")
print(market_calibration.columns.tolist())

print("\nFirst 10 rows:")
display(market_calibration.head(10))

print("\nData types:")
display(market_calibration.dtypes.to_frame("data_type"))

print("\nMissing values:")
display(
    market_calibration.isna()
    .sum()
    .to_frame("missing_values")
)

print("\nDescriptive statistics:")
display(market_calibration.describe(include="all").T)

===== Market Calibration Dataset =====
Shape: (146, 17)

Columns:
['period', 'nifty_open', 'nifty_high', 'nifty_low', 'nifty_close', 'nifty_avg_close', 'nifty_total_volume', 'nifty_avg_daily_return', 'nifty_return_volatility', 'nifty_monthly_return', 'nifty_3m_volatility', 'nifty_3m_ma', 'nifty_ma_gap', 'average_walr', 'walr_change', 'walr_pct_change', 'walr_momentum']

First 10 rows:

,period,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap,average_walr,walr_change,walr_pct_change,walr_momentum
0,2014-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.04,-0.063321,-0.006237,-0.086667
1,2014-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.85,-0.190000,-0.015781,-0.086667
2,2015-01-01,8433.400391,8952.349609,7785.850098,8808.900391,8517.880561,3155600.0,0.001717,0.024584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-02-01,8395.450195,8956.750000,7717.000000,8844.599609,8586.427707,3075000.0,0.001173,0.044847,0.004053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-03-01,8756.549805,8996.250000,7823.000000,8491.000000,8469.088216,3474400.0,-0.001184,0.039669,-0.039979,NaN,8714.833333,-0.025684,11.79,-0.060000,-0.005063,-0.103333
5,2015-04-01,8723.700195,8922.650391,7655.049805,8181.500000,8356.472510,3632900.0,-0.000829,0.046884,-0.036450,0.024467,8505.699870,-0.038116,NaN,NaN,NaN,NaN
6,2015-05-01,8378.400391,8937.750000,7955.450195,8433.650391,8365.304827,3395400.0,0.001836,0.028463,0.030820,0.039896,8368.716797,0.007759,NaN,NaN,NaN,NaN
7,2015-06-01,8127.350098,8661.049805,7954.299805,8368.500000,8293.854981,3023200.0,0.000025,0.029438,-0.007725,0.033754,8327.883464,0.004877,11.69,-0.100000,-0.008482,-0.086667
8,2015-07-01,8102.100098,8660.299805,7558.799805,8532.849609,8389.460746,3281700.0,0.001853,0.045639,0.019639,0.019830,8445.000000,0.010403,NaN,NaN,NaN,NaN
9,2015-08-01,8234.599609,8714.400391,7688.250000,7971.299805,8164.611909,3994000.0,-0.002411,0.041623,-0.065810,0.043635,8290.883138,-0.038546,NaN,NaN,NaN,NaN

Data types:

                        data_type
period                     object
nifty_open                float64
nifty_high                float64
nifty_low                 float64
nifty_close               float64
nifty_avg_close           float64
nifty_total_volume        float64
nifty_avg_daily_return    float64
nifty_return_volatility   float64
nifty_monthly_return      float64
nifty_3m_volatility       float64
nifty_3m_ma               float64
nifty_ma_gap              float64
average_walr              float64
walr_change               float64
walr_pct_change           float64
walr_momentum             float64

Missing values:

                         missing_values
period                                0
nifty_open                            2
nifty_high                            2
nifty_low                             2
nifty_close                           2
nifty_avg_close                       2
nifty_total_volume                    2
nifty_avg_daily_return                2
nifty_return_volatility               2
nifty_monthly_return                  3
nifty_3m_volatility                   5
nifty_3m_ma                           4
nifty_ma_gap                          4
average_walr                         99
walr_change                          99
walr_pct_change                      99
walr_momentum                        99

Descriptive statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
period,146,146,2014-03-01,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nifty_open,144.0,NaN,NaN,NaN,14949.068092,6109.132367,7215.700195,10023.912601,13150.3501,19052.663085,26328.55078
nifty_high,144.0,NaN,NaN,NaN,16577.951775,6433.954273,8592.150391,11066.40015,15813.9751,22547.062012,26328.55078
nifty_low,144.0,NaN,NaN,NaN,14023.394134,5751.053259,6970.600098,8663.362549,12290.399905,18669.000488,23416.55078
nifty_close,144.0,NaN,NaN,NaN,15335.913208,6096.043063,6987.049805,10104.550052,13808.174805,21727.124512,26202.94922
nifty_avg_close,144.0,NaN,NaN,NaN,15321.488133,6092.296249,7523.944773,9982.019589,13890.395379,20951.065679,25444.260059
nifty_total_volume,144.0,NaN,NaN,NaN,6456068.055556,3093641.358664,1491900.0,4282050.0,5821300.0,7414550.0,18325000.0
nifty_avg_daily_return,144.0,NaN,NaN,NaN,0.00127,0.002731,-0.009463,-0.000052,0.001258,0.002536,0.014388
nifty_return_volatility,144.0,NaN,NaN,NaN,0.041751,0.0166,0.021673,0.032226,0.037821,0.044591,0.127653
nifty_monthly_return,143.0,NaN,NaN,NaN,0.007981,0.045622,-0.232464,-0.017425,0.009323,0.035068,0.1468
nifty_3m_volatility,141.0,NaN,NaN,NaN,0.038265,0.027185,0.001156,0.023173,0.034365,0.046136,0.190009
nifty_3m_ma,142.0,NaN,NaN,NaN,15324.518087,6059.318625,7429.666504,10167.266437,13788.466635,20976.241699,26018.216147
nifty_ma_gap,142.0,NaN,NaN,NaN,0.006997,0.033434,-0.187911,-0.010089,0.008435,0.028266,0.086859
average_walr,47.0,NaN,NaN,NaN,10.308919,0.809744,8.901485,9.736456,10.226409,10.702734,12.04
walr_change,47.0,NaN,NaN,NaN,-0.06026,0.152631,-0.392022,-0.167997,-0.063321,-0.001286,0.366519
walr_pct_change,47.0,NaN,NaN,NaN,-0.00556,0.015503,-0.038802,-0.015778,-0.006237,-0.000121,0.038805
walr_momentum,47.0,NaN,NaN,NaN,-0.059378,0.138873,-0.290404,-0.164321,-0.086667,0.01202,0.354893

In [102]:
# 12.3. Prepare Historical Market Returns

market_returns = market_calibration[
    [
        "period",
        "nifty_monthly_return",
        "nifty_return_volatility",
        "nifty_3m_volatility",
        "nifty_ma_gap"
    ]
].copy()

# Convert period to datetime
market_returns["period"] = pd.to_datetime(market_returns["period"])

# Keep only rows with an actual monthly return
market_returns = market_returns.dropna(
    subset=["nifty_monthly_return"]
).copy()

# Sort chronologically
market_returns = (
    market_returns
    .sort_values("period")
    .reset_index(drop=True)
)

print("===== Historical Market Return Series =====")

print("Number of observations:", len(market_returns))

print("\nPeriod coverage:")
print("Start:", market_returns["period"].min().date())
print("End:", market_returns["period"].max().date())

print("\nMissing values:")
display(
    market_returns.isna()
    .sum()
    .to_frame("missing_values")
)

print("\nReturn statistics:")

display(
    market_returns["nifty_monthly_return"]
    .describe()
    .to_frame("monthly_return")
)

print("\nFirst 10 observations:")

display(
    market_returns.head(10)
)

print("\nLargest positive monthly returns:")

display(
    market_returns.nlargest(
        5,
        "nifty_monthly_return"
    )[
        ["period", "nifty_monthly_return"]
    ]
)

print("\nLargest negative monthly returns:")

display(
    market_returns.nsmallest(
        5,
        "nifty_monthly_return"
    )[
        ["period", "nifty_monthly_return"]
    ]
)

===== Historical Market Return Series =====
Number of observations: 143

Period coverage:
Start: 2015-02-01
End: 2026-12-01

Missing values:

                         missing_values
period                                0
nifty_monthly_return                  0
nifty_return_volatility               0
nifty_3m_volatility                   2
nifty_ma_gap                          1

Return statistics:

       monthly_return
count      143.000000
mean         0.007981
std          0.045622
min         -0.232464
25%         -0.017425
50%          0.009323
75%          0.035068
max          0.146800

First 10 observations:

,period,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap
0,2015-02-01,0.004053,0.044847,NaN,NaN
1,2015-03-01,-0.039979,0.039669,NaN,-0.025684
2,2015-04-01,-0.036450,0.046884,0.024467,-0.038116
3,2015-05-01,0.030820,0.028463,0.039896,0.007759
4,2015-06-01,-0.007725,0.029438,0.033754,0.004877
5,2015-07-01,0.019639,0.045639,0.019830,0.010403
6,2015-08-01,-0.065810,0.041623,0.043635,-0.038546
7,2015-09-01,-0.002810,0.033713,0.044299,-0.024796
8,2015-10-01,0.014706,0.034204,0.042345,0.008813
9,2015-11-01,-0.016186,0.034582,0.015492,-0.006021

Largest positive monthly returns:

       period  nifty_monthly_return
62 2020-04-01              0.146800
69 2020-11-01              0.113941
13 2016-03-01              0.107535
89 2022-07-01              0.087324
78 2021-08-01              0.086858

Largest negative monthly returns:

        period  nifty_monthly_return
61  2020-03-01             -0.232464
133 2026-03-01             -0.113082
12  2016-02-01             -0.076221
6   2015-08-01             -0.065810
43  2018-09-01             -0.064214

In [103]:
# 12.4. Validate Market Return Behaviour

returns = market_returns["nifty_monthly_return"]

positive_months = (returns > 0).sum()
negative_months = (returns < 0).sum()
zero_months = (returns == 0).sum()

print("===== Market Return Behaviour =====")

print("\nNumber of observations:", len(returns))

print("\nPositive-return months:", positive_months)
print("Negative-return months:", negative_months)
print("Zero-return months:", zero_months)

print("\nPositive-return proportion:",
      round(positive_months / len(returns), 4))

print("Negative-return proportion:",
      round(negative_months / len(returns), 4))

print("\nReturn percentiles:")

display(
    returns.quantile(
        [0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    ).to_frame("monthly_return")
)

print("\nMean monthly return:",
      round(returns.mean(), 6))

print("Median monthly return:",
      round(returns.median(), 6))

print("Monthly return standard deviation:",
      round(returns.std(), 6))

print("\nMinimum monthly return:",
      round(returns.min(), 6))

print("Maximum monthly return:",
      round(returns.max(), 6))

===== Market Return Behaviour =====

Number of observations: 143

Positive-return months: 81
Negative-return months: 62
Zero-return months: 0

Positive-return proportion: 0.5664
Negative-return proportion: 0.4336

Return percentiles:

      monthly_return
0.01       -0.097600
0.05       -0.058664
0.10       -0.042541
0.25       -0.017425
0.50        0.009323
0.75        0.035068
0.90        0.062801
0.95        0.075295
0.99        0.111250

Mean monthly return: 0.007981
Median monthly return: 0.009323
Monthly return standard deviation: 0.045622

Minimum monthly return: -0.232464
Maximum monthly return: 0.1468

In [104]:
# 12.5. Generate Risk-Adjusted Portfolio Return Samples

portfolio_return_test = final_population[
    [
        "user_id",
        "risk_score",
        "risk_profile",
        "initial_investment"
    ]
].copy()

# Use the historical market return distribution
market_return_sample = market_returns[
    "nifty_monthly_return"
].sample(
    n=len(portfolio_return_test),
    replace=True,
    random_state=51
).reset_index(drop=True)

portfolio_return_test["market_return"] = market_return_sample

# Risk-adjusted portfolio return
portfolio_return_test["portfolio_return"] = (
    portfolio_return_test["risk_score"]
    * portfolio_return_test["market_return"]
)

print("===== Risk-Adjusted Portfolio Return Test =====")

print("\nSample observations:")

display(
    portfolio_return_test.head(10)
)

print("\nPortfolio return statistics:")

display(
    portfolio_return_test["portfolio_return"]
    .describe()
    .to_frame("portfolio_return")
)

print("\nPortfolio return by risk profile:")

display(
    portfolio_return_test
    .groupby("risk_profile")["portfolio_return"]
    .agg(
        count="count",
        mean="mean",
        std="std",
        minimum="min",
        median="median",
        maximum="max"
    )
    .round(6)
)

print("\nMarket return statistics for comparison:")

display(
    portfolio_return_test["market_return"]
    .describe()
    .to_frame("market_return")
)

===== Risk-Adjusted Portfolio Return Test =====

Sample observations:

,user_id,risk_score,risk_profile,initial_investment,market_return,portfolio_return
0,USER_00001,0.710500,aggressive,45777.548120,0.015037,0.010684
1,USER_00002,0.038363,conservative,0.000000,0.015643,0.000600
2,USER_00003,0.505350,moderate,0.000000,0.055219,0.027905
3,USER_00004,0.313650,conservative,60534.274631,0.034646,0.010867
4,USER_00005,0.750750,aggressive,105774.934379,0.012449,0.009346
5,USER_00006,0.823150,aggressive,118987.882781,-0.036134,-0.029744
6,USER_00007,0.762325,aggressive,90329.680595,-0.063563,-0.048456
7,USER_00008,0.087587,conservative,0.000000,-0.034814,-0.003049
8,USER_00009,0.688500,aggressive,0.000000,-0.010430,-0.007181
9,USER_00010,0.533300,moderate,15171.499059,-0.031485,-0.016791

Portfolio return statistics:

       portfolio_return
count      10000.000000
mean           0.003308
std            0.025566
min           -0.196769
25%           -0.007415
50%            0.002185
75%            0.014783
max            0.124406

Portfolio return by risk profile:

              count      mean       std   minimum    median   maximum
risk_profile
aggressive     3333  0.004778  0.034236 -0.196769  0.005297  0.124406
conservative   3333  0.001802  0.011648 -0.093468  0.001465  0.057182
moderate       3334  0.003346  0.025476 -0.146807  0.002466  0.092543

Market return statistics for comparison:

       market_return
count   10000.000000
mean        0.006836
std         0.046778
min        -0.232464
25%        -0.018744
50%         0.008901
75%         0.035030
max         0.146800

In [105]:
# 12.6. Build Final Market Scenario Timeline

market_scenario = market_returns[
    [
        "period",
        "nifty_monthly_return"
    ]
].copy()

market_scenario["period"] = pd.to_datetime(
    market_scenario["period"]
)

market_scenario = (
    market_scenario
    .sort_values("period")
    .reset_index(drop=True)
)

print("===== Final Market Scenario Timeline =====")

print("\nNumber of simulation months with market returns:",
      len(market_scenario))

print("\nStart period:",
      market_scenario["period"].min().date())

print("End period:",
      market_scenario["period"].max().date())

print("\nDuplicate periods:",
      market_scenario["period"].duplicated().sum())

print("\nMissing market returns:",
      market_scenario["nifty_monthly_return"].isna().sum())

print("\nFirst 10 months:")

display(
    market_scenario.head(10)
)

print("\nLast 10 months:")

display(
    market_scenario.tail(10)
)

print("\nMarch 2020 market return:")

display(
    market_scenario[
        market_scenario["period"] == pd.Timestamp("2020-03-01")
    ]
)

===== Final Market Scenario Timeline =====

Number of simulation months with market returns: 143

Start period: 2015-02-01
End period: 2026-12-01

Duplicate periods: 0

Missing market returns: 0

First 10 months:

      period  nifty_monthly_return
0 2015-02-01              0.004053
1 2015-03-01             -0.039979
2 2015-04-01             -0.036450
3 2015-05-01              0.030820
4 2015-06-01             -0.007725
5 2015-07-01              0.019639
6 2015-08-01             -0.065810
7 2015-09-01             -0.002810
8 2015-10-01              0.014706
9 2015-11-01             -0.016186

Last 10 months:

        period  nifty_monthly_return
133 2026-03-01             -0.113082
134 2026-04-01              0.074610
135 2026-05-01             -0.018744
136 2026-06-01              0.013504
137 2026-07-01              0.018914
138 2026-08-01             -0.017893
139 2026-09-01              0.003381
140 2026-10-01              0.010187
141 2026-11-01             -0.043182
142 2026-12-01              0.019917

March 2020 market return:

       period  nifty_monthly_return
61 2020-03-01             -0.232464

In [106]:
# 12.7. Generate User Market Exposure

portfolio_population = final_population[
    [
        "user_id",
        "initial_investment",
        "risk_score",
        "risk_profile"
    ]
].copy()

# Market exposure is directly derived from the continuous
# financial risk-capacity score.
portfolio_population["market_exposure"] = (
    portfolio_population["risk_score"]
)

print("===== User Market Exposure =====")

print("\nExposure statistics:")

display(
    portfolio_population["market_exposure"]
    .describe()
    .to_frame("market_exposure")
)

print("\nExposure by risk profile:")

display(
    portfolio_population
    .groupby("risk_profile")["market_exposure"]
    .agg(
        count="count",
        mean="mean",
        minimum="min",
        median="median",
        maximum="max"
    )
    .round(6)
)

print("\nSample users:")

display(
    portfolio_population.head(10)
)

print("\nExposure validation:")

print(
    "Minimum exposure:",
    portfolio_population["market_exposure"].min()
)

print(
    "Maximum exposure:",
    portfolio_population["market_exposure"].max()
)

print(
    "Values outside [0, 1]:",
    (
        (portfolio_population["market_exposure"] < 0) |
        (portfolio_population["market_exposure"] > 1)
    ).sum()
)

===== User Market Exposure =====

Exposure statistics:

       market_exposure
count     10000.000000
mean          0.500000
std           0.223233
min           0.028262
25%           0.313572
50%           0.540337
75%           0.682412
max           0.854000

Exposure by risk profile:

              count      mean   minimum    median   maximum
risk_profile
aggressive     3333  0.737324  0.634950  0.728550  0.854000
conservative   3333  0.227601  0.028262  0.216588  0.410750
moderate       3334  0.535065  0.410925  0.540337  0.634875

Sample users:

      user_id  initial_investment  risk_score  risk_profile  market_exposure
0  USER_00001        45777.548120    0.710500    aggressive         0.710500
1  USER_00002            0.000000    0.038363  conservative         0.038363
2  USER_00003            0.000000    0.505350      moderate         0.505350
3  USER_00004        60534.274631    0.313650  conservative         0.313650
4  USER_00005       105774.934379    0.750750    aggressive         0.750750
5  USER_00006       118987.882781    0.823150    aggressive         0.823150
6  USER_00007        90329.680595    0.762325    aggressive         0.762325
7  USER_00008            0.000000    0.087587  conservative         0.087587
8  USER_00009            0.000000    0.688500    aggressive         0.688500
9  USER_00010        15171.499059    0.533300      moderate         0.533300

Exposure validation:
Minimum exposure: 0.0282624999999999
Maximum exposure: 0.854
Values outside [0, 1]: 0

In [107]:
# 12.8. Simulate Initial Portfolio Value

# Create user-level portfolio inputs
portfolio_users = portfolio_population[
    [
        "user_id",
        "initial_investment",
        "risk_score",
        "risk_profile",
        "market_exposure"
    ]
].copy()

# Use the final historical market scenario
portfolio_market = market_scenario.copy()

print("===== Portfolio Simulation Setup =====")

print("Number of users:",
      len(portfolio_users))

print("Number of market months:",
      len(portfolio_market))

print(
    "Initial total investment:",
    round(
        portfolio_users["initial_investment"].sum(),
        2
    )
)

print(
    "Users with initial investments:",
    (
        portfolio_users["initial_investment"] > 0
    ).sum()
)

print(
    "Users without initial investments:",
    (
        portfolio_users["initial_investment"] == 0
    ).sum()
)

# Show the two components before creating the simulation
print("\nSample users:")

display(
    portfolio_users.head(10)
)

print("\nSample market months:")

display(
    portfolio_market.head(10)
)

===== Portfolio Simulation Setup =====
Number of users: 10000
Number of market months: 143
Initial total investment: 569685348.34
Users with initial investments: 5445
Users without initial investments: 4555

Sample users:

      user_id  initial_investment  risk_score  risk_profile  market_exposure
0  USER_00001        45777.548120    0.710500    aggressive         0.710500
1  USER_00002            0.000000    0.038363  conservative         0.038363
2  USER_00003            0.000000    0.505350      moderate         0.505350
3  USER_00004        60534.274631    0.313650  conservative         0.313650
4  USER_00005       105774.934379    0.750750    aggressive         0.750750
5  USER_00006       118987.882781    0.823150    aggressive         0.823150
6  USER_00007        90329.680595    0.762325    aggressive         0.762325
7  USER_00008            0.000000    0.087587  conservative         0.087587
8  USER_00009            0.000000    0.688500    aggressive         0.688500
9  USER_00010        15171.499059    0.533300      moderate         0.533300

Sample market months:

      period  nifty_monthly_return
0 2015-02-01              0.004053
1 2015-03-01             -0.039979
2 2015-04-01             -0.036450
3 2015-05-01              0.030820
4 2015-06-01             -0.007725
5 2015-07-01              0.019639
6 2015-08-01             -0.065810
7 2015-09-01             -0.002810
8 2015-10-01              0.014706
9 2015-11-01             -0.016186

In [108]:
# 12.9. Generate Monthly Portfolio Returns

# Create the user-month combination
user_month = (
    portfolio_users.assign(key=1)
    .merge(
        portfolio_market.assign(key=1),
        on="key",
        how="outer"
    )
    .drop(columns="key")
)

# Calculate user-specific portfolio return
user_month["portfolio_return"] = (
    user_month["market_exposure"]
    * user_month["nifty_monthly_return"]
)

# Sort for correct chronological simulation
user_month = (
    user_month
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

print("===== Monthly Portfolio Return Dataset =====")

print("\nShape:")
print(user_month.shape)

print("\nExpected observations:",
      len(portfolio_users) * len(portfolio_market))

print("\nMissing values in key fields:")

display(
    user_month[
        [
            "user_id",
            "period",
            "initial_investment",
            "market_exposure",
            "nifty_monthly_return",
            "portfolio_return"
        ]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nSample for USER_00001:")

display(
    user_month[
        user_month["user_id"] == "USER_00001"
    ].head(10)
)

print("\nPortfolio return statistics:")

display(
    user_month["portfolio_return"]
    .describe()
    .to_frame("portfolio_return")
)

===== Monthly Portfolio Return Dataset =====

Shape:
(1430000, 8)

Expected observations: 1430000

Missing values in key fields:

                      missing_values
user_id                            0
period                             0
initial_investment                 0
market_exposure                    0
nifty_monthly_return               0
portfolio_return                   0

Sample for USER_00001:

,user_id,initial_investment,risk_score,risk_profile,market_exposure,period,nifty_monthly_return,portfolio_return
0,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-02-01,0.004053,0.002879
1,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-03-01,-0.039979,-0.028405
2,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-04-01,-0.036450,-0.025898
3,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-05-01,0.030820,0.021897
4,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-06-01,-0.007725,-0.005489
5,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-07-01,0.019639,0.013954
6,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-08-01,-0.065810,-0.046758
7,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-09-01,-0.002810,-0.001997
8,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-10-01,0.014706,0.010449
9,USER_00001,45777.54812,0.7105,aggressive,0.7105,2015-11-01,-0.016186,-0.011500

Portfolio return statistics:

       portfolio_return
count      1.430000e+06
mean       3.990393e-03
std        2.495718e-02
min       -1.985240e-01
25%       -6.784056e-03
50%        2.440093e-03
75%        1.526364e-02
max        1.253673e-01

In [109]:
# 12.10. Calculate Portfolio Wealth Over Time

# Start each user's portfolio from their initial investment
user_month["portfolio_value"] = 0.0

# Calculate cumulative portfolio growth for each user
user_month["portfolio_value"] = (
    user_month
    .groupby("user_id")["portfolio_return"]
    .transform(lambda x: (1 + x).cumprod())
    * user_month["initial_investment"]
)

print("===== Portfolio Wealth Simulation =====")

print("\nShape:")
print(user_month.shape)

print("\nMissing values:")

display(
    user_month[
        [
            "user_id",
            "period",
            "portfolio_return",
            "portfolio_value"
        ]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nUSER_00001 portfolio trajectory:")

display(
    user_month[
        user_month["user_id"] == "USER_00001"
    ][
        [
            "user_id",
            "period",
            "initial_investment",
            "portfolio_return",
            "portfolio_value"
        ]
    ].head(10)
)

print("\nPortfolio value summary:")

display(
    user_month["portfolio_value"]
    .describe()
    .to_frame("portfolio_value")
)

===== Portfolio Wealth Simulation =====

Shape:
(1430000, 9)

Missing values:

                  missing_values
user_id                        0
period                         0
portfolio_return               0
portfolio_value                0

USER_00001 portfolio trajectory:

,user_id,period,initial_investment,portfolio_return,portfolio_value
0,USER_00001,2015-02-01,45777.54812,0.002879,45909.359714
1,USER_00001,2015-03-01,45777.54812,-0.028405,44605.295682
2,USER_00001,2015-04-01,45777.54812,-0.025898,43450.108617
3,USER_00001,2015-05-01,45777.54812,0.021897,44401.549173
4,USER_00001,2015-06-01,45777.54812,-0.005489,44157.844623
5,USER_00001,2015-07-01,45777.54812,0.013954,44774.003918
6,USER_00001,2015-08-01,45777.54812,-0.046758,42680.449741
7,USER_00001,2015-09-01,45777.54812,-0.001997,42595.235915
8,USER_00001,2015-10-01,45777.54812,0.010449,43040.309924
9,USER_00001,2015-11-01,45777.54812,-0.011500,42545.352023

Portfolio value summary:

       portfolio_value
count     1.430000e+06
mean      8.373652e+04
std       1.953896e+05
min       0.000000e+00
25%       0.000000e+00
50%       1.082873e+04
75%       9.154806e+04
max       9.941608e+06

In [110]:
# 12.11. Validate Portfolio Wealth Behaviour

print("===== Portfolio Wealth Validation =====")

# --------------------------------------------------
# 1. Check portfolio values are non-negative
# --------------------------------------------------

negative_values = (
    user_month["portfolio_value"] < 0
).sum()

print("\nNegative portfolio values:", negative_values)


# --------------------------------------------------
# 2. Check zero-investment users
# --------------------------------------------------

zero_investment_users = (
    portfolio_users["initial_investment"] == 0
)

zero_user_ids = set(
    portfolio_users.loc[
        zero_investment_users,
        "user_id"
    ]
)

zero_investment_values = user_month[
    user_month["user_id"].isin(zero_user_ids)
]["portfolio_value"]

print(
    "Zero-investment users:",
    len(zero_user_ids)
)

print(
    "Non-zero values among zero-investment users:",
    (zero_investment_values != 0).sum()
)


# --------------------------------------------------
# 3. Calculate each user's initial and final value
# --------------------------------------------------

portfolio_summary = (
    user_month
    .sort_values(["user_id", "period"])
    .groupby("user_id")
    .agg(
        initial_investment=("initial_investment", "first"),
        final_portfolio_value=("portfolio_value", "last"),
        risk_score=("risk_score", "first"),
        risk_profile=("risk_profile", "first"),
        market_exposure=("market_exposure", "first")
    )
    .reset_index()
)

# Absolute change
portfolio_summary["portfolio_change"] = (
    portfolio_summary["final_portfolio_value"]
    - portfolio_summary["initial_investment"]
)

# Percentage change for users with initial investment
portfolio_summary["portfolio_growth_rate"] = np.where(
    portfolio_summary["initial_investment"] > 0,
    (
        portfolio_summary["final_portfolio_value"]
        / portfolio_summary["initial_investment"]
    ) - 1,
    np.nan
)


# --------------------------------------------------
# 4. Overall portfolio outcome
# --------------------------------------------------

invested_users = portfolio_summary[
    portfolio_summary["initial_investment"] > 0
].copy()

print("\nUsers with initial investments:", len(invested_users))

print(
    "Users with portfolio growth:",
    (invested_users["portfolio_change"] > 0).sum()
)

print(
    "Users with portfolio decline:",
    (invested_users["portfolio_change"] < 0).sum()
)

print(
    "Users with approximately unchanged value:",
    np.isclose(
        invested_users["portfolio_change"],
        0
    ).sum()
)


# --------------------------------------------------
# 5. Outcome by risk profile
# --------------------------------------------------

risk_validation = (
    invested_users
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        mean_initial_investment=("initial_investment", "mean"),
        mean_final_value=("final_portfolio_value", "mean"),
        median_final_value=("final_portfolio_value", "median"),
        mean_growth_rate=("portfolio_growth_rate", "mean"),
        median_growth_rate=("portfolio_growth_rate", "median"),
        mean_change=("portfolio_change", "mean")
    )
    .reset_index()
)

print("\nOutcome by risk profile:")

display(risk_validation)


# --------------------------------------------------
# 6. Final portfolio value distribution
# --------------------------------------------------

print("\nFinal portfolio value distribution:")

display(
    invested_users[
        "final_portfolio_value"
    ]
    .describe()
    .to_frame("final_portfolio_value")
)


# --------------------------------------------------
# 7. Growth-rate distribution
# --------------------------------------------------

print("\nPortfolio growth-rate distribution:")

display(
    invested_users[
        "portfolio_growth_rate"
    ]
    .describe()
    .to_frame("portfolio_growth_rate")
)

===== Portfolio Wealth Validation =====

Negative portfolio values: 0
Zero-investment users: 4555
Non-zero values among zero-investment users: 0

Users with initial investments: 5445
Users with portfolio growth: 5445
Users with portfolio decline: 0
Users with approximately unchanged value: 0

Outcome by risk profile:

,risk_profile,users,mean_initial_investment,mean_final_value,median_final_value,mean_growth_rate,median_growth_rate,mean_change
0,aggressive,2622,145530.246764,321066.947020,205749.582001,1.151977,1.140295,175536.700256
1,conservative,1121,47457.688335,66316.663202,38867.008833,0.327288,0.334121,18858.974867
2,moderate,1702,79262.616159,142689.293674,61325.294118,0.780391,0.793583,63426.677515

Final portfolio value distribution:

       final_portfolio_value
count           5.445000e+03
mean            2.128624e+05
std             3.257183e+05
min             1.255651e+02
25%             4.250750e+04
50%             1.123900e+05
75%             2.600770e+05
max             9.121935e+06

Portfolio growth-rate distribution:

       portfolio_growth_rate
count            5445.000000
mean                0.866042
std                 0.340167
min                 0.050520
25%                 0.653108
50%                 0.921879
75%                 1.133375
max                 1.368191

In [114]:
# 12.12. Analyze Portfolio Response to Market Shocks

# Identify the 10 market months with the largest absolute movements
market_shocks = (
    market_scenario
    .assign(abs_market_move=market_scenario["nifty_monthly_return"].abs())
    .nlargest(10, "abs_market_move")
    .sort_values("period")
)

print("===== Major Historical Market Movements =====")

display(
    market_shocks[
        ["period", "nifty_monthly_return"]
    ]
)


# Select these months from the user-month simulation
shock_data = user_month[
    user_month["period"].isin(
        market_shocks["period"]
    )
].copy()


# Summarise portfolio returns by risk profile
shock_summary = (
    shock_data
    .groupby(
        ["period", "risk_profile"]
    )
    .agg(
        market_return=("nifty_monthly_return", "first"),
        mean_exposure=("market_exposure", "mean"),
        mean_portfolio_return=("portfolio_return", "mean"),
        min_portfolio_return=("portfolio_return", "min"),
        max_portfolio_return=("portfolio_return", "max")
    )
    .reset_index()
    .sort_values(["period", "risk_profile"])
)

print("\n===== Portfolio Response to Market Shocks =====")

display(shock_summary)


# Identify the single largest negative market month
worst_market_month = market_scenario.loc[
    market_scenario["nifty_monthly_return"].idxmin()
]

print("\n===== Largest Negative Market Month =====")

print(
    "Period:",
    worst_market_month["period"]
)

print(
    "NIFTY return:",
    round(
        worst_market_month["nifty_monthly_return"],
        6
    )
)


display(
    shock_summary[
        shock_summary["period"]
        == worst_market_month["period"]
    ]
)

===== Major Historical Market Movements =====

        period  nifty_monthly_return
12  2016-02-01             -0.076221
13  2016-03-01              0.107535
61  2020-03-01             -0.232464
62  2020-04-01              0.146800
69  2020-11-01              0.113941
70  2020-12-01              0.078094
78  2021-08-01              0.086858
89  2022-07-01              0.087324
106 2023-12-01              0.079384
133 2026-03-01             -0.113082

===== Portfolio Response to Market Shocks =====

,period,risk_profile,market_return,mean_exposure,mean_portfolio_return,min_portfolio_return,max_portfolio_return
0,2016-02-01,aggressive,-0.076221,0.737324,-0.056199,-0.065093,-0.048396
1,2016-02-01,conservative,-0.076221,0.227601,-0.017348,-0.031308,-0.002154
2,2016-02-01,moderate,-0.076221,0.535065,-0.040783,-0.048391,-0.031321
3,2016-03-01,aggressive,0.107535,0.737324,0.079288,0.068279,0.091835
4,2016-03-01,conservative,0.107535,0.227601,0.024475,0.003039,0.044170
5,2016-03-01,moderate,0.107535,0.535065,0.057538,0.044189,0.068271
6,2020-03-01,aggressive,-0.232464,0.737324,-0.171401,-0.198524,-0.147603
7,2020-03-01,conservative,-0.232464,0.227601,-0.052909,-0.095484,-0.006570
8,2020-03-01,moderate,-0.232464,0.535065,-0.124383,-0.147585,-0.095525
9,2020-04-01,aggressive,0.146800,0.737324,0.108239,0.093211,0.125367
10,2020-04-01,conservative,0.146800,0.227601,0.033412,0.004149,0.060298
11,2020-04-01,moderate,0.146800,0.535065,0.078548,0.060324,0.093200
12,2020-11-01,aggressive,0.113941,0.737324,0.084012,0.072347,0.097306
13,2020-11-01,conservative,0.113941,0.227601,0.025933,0.003220,0.046801
14,2020-11-01,moderate,0.113941,0.535065,0.060966,0.046821,0.072338
15,2020-12-01,aggressive,0.078094,0.737324,0.057581,0.049586,0.066692
16,2020-12-01,conservative,0.078094,0.227601,0.017774,0.002207,0.032077
17,2020-12-01,moderate,0.078094,0.535065,0.041785,0.032091,0.049580
18,2021-08-01,aggressive,0.086858,0.737324,0.064043,0.055151,0.074177
19,2021-08-01,conservative,0.086858,0.227601,0.019769,0.002455,0.035677
20,2021-08-01,moderate,0.086858,0.535065,0.046475,0.035692,0.055144
21,2022-07-01,aggressive,0.087324,0.737324,0.064386,0.055447,0.074575
22,2022-07-01,conservative,0.087324,0.227601,0.019875,0.002468,0.035868
23,2022-07-01,moderate,0.087324,0.535065,0.046724,0.035884,0.055440
24,2023-12-01,aggressive,0.079384,0.737324,0.058532,0.050405,0.067794
25,2023-12-01,conservative,0.079384,0.227601,0.018068,0.002244,0.032607
26,2023-12-01,moderate,0.079384,0.535065,0.042476,0.032621,0.050399
27,2026-03-01,aggressive,-0.113082,0.737324,-0.083378,-0.096572,-0.071801
28,2026-03-01,conservative,-0.113082,0.227601,-0.025738,-0.046448,-0.003196
29,2026-03-01,moderate,-0.113082,0.535065,-0.060506,-0.071793,-0.046468

===== Largest Negative Market Month =====
Period: 2020-03-01 00:00:00
NIFTY return: -0.232464

,period,risk_profile,market_return,mean_exposure,mean_portfolio_return,min_portfolio_return,max_portfolio_return
6,2020-03-01,aggressive,-0.232464,0.737324,-0.171401,-0.198524,-0.147603
7,2020-03-01,conservative,-0.232464,0.227601,-0.052909,-0.095484,-0.006570
8,2020-03-01,moderate,-0.232464,0.535065,-0.124383,-0.147585,-0.095525

In [115]:
# 12.13. Save Validated Portfolio Simulation

portfolio_simulation_path = (
    "/content/drive/MyDrive/GoalPilot_AI/"
    "simulation/05_simulation_runs/"
    "portfolio_simulation_validated.csv"
)

# Keep only the columns required for the validated portfolio layer
portfolio_simulation = user_month[
    [
        "user_id",
        "period",
        "initial_investment",
        "risk_score",
        "risk_profile",
        "market_exposure",
        "nifty_monthly_return",
        "portfolio_return",
        "portfolio_value"
    ]
].copy()

# Save to Google Drive
portfolio_simulation.to_csv(
    portfolio_simulation_path,
    index=False
)

print("===== Portfolio Simulation Saved =====")

print("\nFile:")
print(portfolio_simulation_path)

print("\nShape:")
print(portfolio_simulation.shape)

print("\nColumns:")
print(portfolio_simulation.columns.tolist())

print("\nFile size (MB):")

import os

print(
    round(
        os.path.getsize(portfolio_simulation_path)
        / (1024 ** 2),
        2
    )
)

===== Portfolio Simulation Saved =====

File:
/content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/portfolio_simulation_validated.csv

Shape:
(1430000, 9)

Columns:
['user_id', 'period', 'initial_investment', 'risk_score', 'risk_profile', 'market_exposure', 'nifty_monthly_return', 'portfolio_return', 'portfolio_value']

File size (MB):
161.28

13. Monthly Financial Simulation

In [116]:
# 13.1. Prepare Monthly Financial Simulation Base

# Load the final synthetic financial population
financial_population = final_population[
    [
        "user_id",
        "monthly_income",
        "monthly_expenditure",
        "monthly_surplus",
        "monthly_emi",
        "initial_savings",
        "initial_investment",
        "investment_capacity_ratio",
        "risk_score",
        "risk_profile"
    ]
].copy()

# Load the validated portfolio simulation timeline
financial_market = portfolio_simulation[
    [
        "user_id",
        "period",
        "portfolio_return",
        "portfolio_value"
    ]
].copy()

# Create the monthly financial simulation base
monthly_financial_simulation = financial_market.merge(
    financial_population,
    on="user_id",
    how="left"
)

# Sort chronologically for each user
monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

print("===== Monthly Financial Simulation Base =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nExpected observations:")
print(
    len(financial_population)
    * len(financial_market["period"].unique())
)

print("\nMissing values in key financial fields:")

display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "initial_savings",
            "initial_investment",
            "portfolio_return"
        ]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nSample financial simulation records:")

display(
    monthly_financial_simulation.head(10)
)

===== Monthly Financial Simulation Base =====

Shape:
(1430000, 13)

Expected observations:
1430000

Missing values in key financial fields:

                     missing_values
user_id                           0
period                            0
monthly_income                    0
monthly_expenditure               0
monthly_emi                       0
initial_savings                   0
initial_investment                0
portfolio_return                  0

Sample financial simulation records:

,user_id,period,portfolio_return,portfolio_value,monthly_income,monthly_expenditure,monthly_surplus,monthly_emi,initial_savings,initial_investment,investment_capacity_ratio,risk_score,risk_profile
0,USER_00001,2015-02-01,0.002879,45909.359714,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
1,USER_00001,2015-03-01,-0.028405,44605.295682,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
2,USER_00001,2015-04-01,-0.025898,43450.108617,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
3,USER_00001,2015-05-01,0.021897,44401.549173,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
4,USER_00001,2015-06-01,-0.005489,44157.844623,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
5,USER_00001,2015-07-01,0.013954,44774.003918,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
6,USER_00001,2015-08-01,-0.046758,42680.449741,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
7,USER_00001,2015-09-01,-0.001997,42595.235915,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
8,USER_00001,2015-10-01,0.010449,43040.309924,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive
9,USER_00001,2015-11-01,-0.011500,42545.352023,51351.335334,36870.0,14481.335334,0.0,178733.65247,45777.54812,0.282005,0.7105,aggressive

In [117]:
# 13.2. Add Economic Environment

# Select the economic variables needed for the monthly simulation
simulation_economic_environment = economic_environment[
    [
        "period",
        "inflation_level",
        "inflation_change",
        "inflation_pct_change",
        "inflation_trend",
        "inflation_regime",
        "nifty_monthly_return",
        "nifty_return_volatility",
        "nifty_3m_volatility",
        "nifty_ma_gap",
        "market_return_regime",
        "market_volatility_regime",
        "average_walr",
        "walr_change",
        "credit_pressure",
        "walr_3period_ma",
        "walr_momentum",
        "walr_regime"
    ]
].copy()

# Make sure period has the same datetime type
simulation_economic_environment["period"] = pd.to_datetime(
    simulation_economic_environment["period"]
)

monthly_financial_simulation["period"] = pd.to_datetime(
    monthly_financial_simulation["period"]
)

# Add economic conditions to each user-month
monthly_financial_simulation = monthly_financial_simulation.merge(
    simulation_economic_environment,
    on="period",
    how="left"
)

# Sort again after the merge
monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

print("===== Economic Environment Added =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nExpected observations:")
print(143 * 10000)

print("\nMissing economic values:")

display(
    monthly_financial_simulation[
        [
            "period",
            "inflation_level",
            "inflation_regime",
            "nifty_monthly_return",
            "average_walr",
            "walr_regime"
        ]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nEconomic environment sample:")

display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "inflation_level",
            "inflation_regime",
            "nifty_monthly_return",
            "average_walr",
            "walr_regime"
        ]
    ].head(10)
)

===== Economic Environment Added =====

Shape:
(1430000, 30)

Expected observations:
1430000

Missing economic values:

                      missing_values
period                             0
inflation_level                    0
inflation_regime                   0
nifty_monthly_return               0
average_walr                       0
walr_regime                        0

Economic environment sample:

,user_id,period,monthly_income,monthly_expenditure,monthly_emi,inflation_level,inflation_regime,nifty_monthly_return,average_walr,walr_regime
0,USER_00001,2015-02-01,51351.335334,36870.0,0.0,0.762137,medium,0.623620,0.939462,high
1,USER_00001,2015-03-01,51351.335334,36870.0,0.0,0.179194,low,0.507522,0.920344,high
2,USER_00001,2015-04-01,51351.335334,36870.0,0.0,0.854063,high,0.516826,0.920344,high
3,USER_00001,2015-05-01,51351.335334,36870.0,0.0,0.776332,medium,0.694196,0.920344,high
4,USER_00001,2015-06-01,51351.335334,36870.0,0.0,0.762137,medium,0.592566,0.888482,high
5,USER_00001,2015-07-01,51351.335334,36870.0,0.0,0.762137,medium,0.664716,0.888482,high
6,USER_00001,2015-08-01,51351.335334,36870.0,0.0,0.540113,low,0.439413,0.888482,high
7,USER_00001,2015-09-01,51351.335334,36870.0,0.0,0.762137,medium,0.605525,0.856620,high
8,USER_00001,2015-10-01,51351.335334,36870.0,0.0,0.794167,high,0.651710,0.856620,high
9,USER_00001,2015-11-01,51351.335334,36870.0,0.0,0.179194,low,0.570258,0.856620,high

In [118]:
# 13.3. Inspect Actual CPI Inflation Calibration

cpi_calibration_path = os.path.join(
    economic_data_path,
    "cpi_historical_calibration.csv"
)

cpi_calibration = pd.read_csv(
    cpi_calibration_path
)

print("===== Actual CPI Inflation Calibration =====")

print("\nShape:")
print(cpi_calibration.shape)

print("\nColumns:")
print(cpi_calibration.columns.tolist())

print("\nMissing values:")

display(
    cpi_calibration.isna()
    .sum()
    .to_frame("missing_values")
)

print("\nFirst 10 rows:")

display(
    cpi_calibration.head(10)
)

print("\nLast 10 rows:")

display(
    cpi_calibration.tail(10)
)

print("\nNumeric summary:")

display(
    cpi_calibration.describe()
)

===== Actual CPI Inflation Calibration =====

Shape:
(48, 11)

Columns:
['period', 'rural_cpi', 'urban_cpi', 'combined_cpi', 'rural_inflation', 'urban_inflation', 'combined_inflation', 'combined_cpi_change', 'combined_cpi_pct_change', 'rural_urban_avg_cpi', 'combined_cpi_3m_ma']

Missing values:

                         missing_values
period                                0
rural_cpi                             0
urban_cpi                             0
combined_cpi                          0
rural_inflation                       0
urban_inflation                       0
combined_inflation                    0
combined_cpi_change                   0
combined_cpi_pct_change               0
rural_urban_avg_cpi                   0
combined_cpi_3m_ma                    0

First 10 rows:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
0,2011-01-01,107.1,104.2,105.9,9.236837,9.70493,9.540669,0.007241,0.007241,105.65,126.050000
1,2011-02-01,106.5,103.7,105.3,9.236837,9.70493,9.540669,-0.005666,-0.005666,105.10,126.050000
2,2011-03-01,106.9,103.9,105.6,9.236837,9.70493,9.540669,0.002849,0.002849,105.40,105.600000
3,2011-04-01,107.5,104.5,106.2,9.236837,9.70493,9.540669,0.005682,0.005682,106.00,105.700000
4,2011-05-01,108.7,105.0,107.1,9.236837,9.70493,9.540669,0.008475,0.008475,106.85,106.300000
5,2011-06-01,109.9,107.3,108.8,9.236837,9.70493,9.540669,0.015873,0.015873,108.60,107.366667
6,2011-07-01,111.7,108.9,110.5,9.236837,9.70493,9.540669,0.015625,0.015625,110.30,108.800000
7,2011-08-01,113.1,109.9,111.7,9.236837,9.70493,9.540669,0.010860,0.010860,111.50,110.333333
8,2011-09-01,114.4,111.1,113.0,9.236837,9.70493,9.540669,0.011638,0.011638,112.75,111.733333
9,2011-10-01,115.2,112.0,113.8,9.236837,9.70493,9.540669,0.007080,0.007080,113.60,112.833333

Last 10 rows:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
38,2014-03-01,139.7,136.0,138.1,8.927875,7.509881,8.313725,0.005827,0.005827,137.85,137.600000
39,2014-04-01,140.5,137.2,139.1,9.168609,7.692308,8.587041,0.007241,0.007241,138.85,138.166667
40,2014-05-01,141.3,138.1,139.9,8.859784,7.554517,8.281734,0.005751,0.005751,139.70,139.033333
41,2014-06-01,142.5,139.4,141.2,7.872824,6.819923,7.458143,0.009292,0.009292,140.95,140.066667
42,2014-07-01,145.0,141.9,143.7,8.370703,7.377980,7.963937,0.017705,0.017705,143.45,141.600000
43,2014-08-01,146.6,143.0,145.0,8.271787,7.035928,7.726597,0.009047,0.009047,144.80,143.300000
44,2014-09-01,147.0,142.5,145.0,6.676343,6.343284,6.461087,0.000000,0.000000,144.75,144.566667
45,2014-10-01,147.2,142.7,145.2,5.557548,5.625463,5.561614,0.001379,0.001379,144.95,145.066667
46,2014-11-01,147.5,142.8,145.5,4.056437,4.692082,4.338473,0.002066,0.002066,145.15,145.233333
47,2014-12-01,146.6,142.5,144.8,4.639543,5.321508,4.927536,-0.004811,-0.004811,144.55,145.166667

Numeric summary:

,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,127.339583,124.316667,126.031250,9.015934,9.167066,9.112749,0.006710,0.006710,125.828125,126.059722
std,13.102505,12.669235,12.902913,1.415549,1.551018,1.431187,0.006265,0.006265,12.878148,12.214456
min,106.500000,103.700000,105.300000,4.056437,4.692082,4.338473,-0.010043,-0.010043,105.100000,105.600000
25%,115.350000,112.725000,114.075000,8.910853,8.289629,8.738209,0.003073,0.003073,113.925000,114.541667
50%,127.100000,124.450000,125.950000,9.236837,9.704930,9.540669,0.007241,0.007241,125.750000,126.050000
75%,139.550000,135.300000,137.700000,9.657430,10.180299,9.847185,0.011362,0.011362,137.400000,137.633333
max,147.500000,143.000000,145.500000,11.662727,11.470728,11.164274,0.017705,0.017705,145.150000,145.233333

In [119]:
# 13.4. Add Actual Inflation Rate to Simulation

# Prepare historical CPI inflation scenarios
cpi_inflation_reference = cpi_calibration[
    [
        "period",
        "combined_inflation"
    ]
].copy()

cpi_inflation_reference["period"] = pd.to_datetime(
    cpi_inflation_reference["period"]
)

# Reproduce the same inflation scenario sampling used in Section 11
inflation_reference_sample = cpi_inflation_reference[
    ["combined_inflation"]
].sample(
    n=len(simulation_calendar),
    replace=True,
    random_state=50
).reset_index(drop=True)

# Attach actual annual inflation rate to the simulation calendar
simulation_calendar_with_inflation = simulation_calendar.copy()

simulation_calendar_with_inflation[
    "annual_inflation_rate"
] = inflation_reference_sample[
    "combined_inflation"
].values

# Convert annual inflation into an equivalent monthly rate
simulation_calendar_with_inflation[
    "monthly_inflation_rate"
] = (
    (1 + simulation_calendar_with_inflation["annual_inflation_rate"] / 100)
    ** (1 / 12)
    - 1
)

print("===== Actual Inflation Rate Added =====")

print("\nShape:")
print(simulation_calendar_with_inflation.shape)

print("\nAnnual inflation statistics:")

display(
    simulation_calendar_with_inflation[
        "annual_inflation_rate"
    ].describe()
)

print("\nMonthly inflation statistics:")

display(
    simulation_calendar_with_inflation[
        "monthly_inflation_rate"
    ].describe()
)

print("\nSample:")

display(
    simulation_calendar_with_inflation[
        [
            "period",
            "inflation_level",
            "inflation_regime",
            "annual_inflation_rate",
            "monthly_inflation_rate"
        ]
    ].head(10)
)

print("\nMissing values:")

display(
    simulation_calendar_with_inflation[
        [
            "annual_inflation_rate",
            "monthly_inflation_rate"
        ]
    ].isna().sum().to_frame("missing_values")
)

===== Actual Inflation Rate Added =====

Shape:
(144, 21)

Annual inflation statistics:

count    144.000000
mean       8.965789
std        1.453701
min        4.338473
25%        8.788599
50%        9.540669
75%        9.685980
max       10.789474
Name: annual_inflation_rate, dtype: float64

Monthly inflation statistics:

count    144.000000
mean       0.007174
std        0.001133
min        0.003545
25%        0.007044
50%        0.007623
75%        0.007734
max        0.008575
Name: monthly_inflation_rate, dtype: float64

Sample:

,period,inflation_level,inflation_regime,annual_inflation_rate,monthly_inflation_rate
0,2015-01-01,0.805801,high,9.838710,0.007851
1,2015-02-01,0.762137,medium,9.540669,0.007623
2,2015-03-01,0.179194,low,5.561614,0.004521
3,2015-04-01,0.854063,high,10.168135,0.008102
4,2015-05-01,0.776332,medium,9.637562,0.007697
5,2015-06-01,0.762137,medium,9.540669,0.007623
6,2015-07-01,0.762137,medium,9.540669,0.007623
7,2015-08-01,0.540113,low,8.025177,0.006454
8,2015-09-01,0.762137,medium,9.540669,0.007623
9,2015-10-01,0.794167,high,9.759300,0.007790

Missing values:

                        missing_values
annual_inflation_rate                0
monthly_inflation_rate               0

In [120]:
# 13.5. Add Actual Inflation Rates to Monthly Financial Simulation

inflation_environment = simulation_calendar_with_inflation[
    [
        "period",
        "annual_inflation_rate",
        "monthly_inflation_rate"
    ]
].copy()

inflation_environment["period"] = pd.to_datetime(
    inflation_environment["period"]
)

monthly_financial_simulation["period"] = pd.to_datetime(
    monthly_financial_simulation["period"]
)

monthly_financial_simulation = monthly_financial_simulation.merge(
    inflation_environment,
    on="period",
    how="left"
)

monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

print("===== Actual Inflation Added to User-Month Simulation =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nMissing inflation values:")

display(
    monthly_financial_simulation[
        [
            "annual_inflation_rate",
            "monthly_inflation_rate"
        ]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nInflation sample:")

display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "monthly_expenditure",
            "annual_inflation_rate",
            "monthly_inflation_rate"
        ]
    ].head(10)
)

print("\nUnique inflation rates by month:")

monthly_inflation_check = (
    monthly_financial_simulation
    .groupby("period")["monthly_inflation_rate"]
    .nunique()
)

print(
    "Maximum number of different inflation rates "
    "within a single month:",
    monthly_inflation_check.max()
)

===== Actual Inflation Added to User-Month Simulation =====

Shape:
(1430000, 32)

Missing inflation values:

                        missing_values
annual_inflation_rate                0
monthly_inflation_rate               0

Inflation sample:

,user_id,period,monthly_expenditure,annual_inflation_rate,monthly_inflation_rate
0,USER_00001,2015-02-01,36870.0,9.540669,0.007623
1,USER_00001,2015-03-01,36870.0,5.561614,0.004521
2,USER_00001,2015-04-01,36870.0,10.168135,0.008102
3,USER_00001,2015-05-01,36870.0,9.637562,0.007697
4,USER_00001,2015-06-01,36870.0,9.540669,0.007623
5,USER_00001,2015-07-01,36870.0,9.540669,0.007623
6,USER_00001,2015-08-01,36870.0,8.025177,0.006454
7,USER_00001,2015-09-01,36870.0,9.540669,0.007623
8,USER_00001,2015-10-01,36870.0,9.759300,0.007790
9,USER_00001,2015-11-01,36870.0,5.561614,0.004521

Unique inflation rates by month:
Maximum number of different inflation rates within a single month: 1

In [121]:
# 13.6. Generate Inflation-Adjusted Monthly Expenditure

monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

# Accumulated inflation factor for the simulation timeline
monthly_financial_simulation["cumulative_inflation_factor"] = (
    (1 + monthly_financial_simulation["monthly_inflation_rate"])
    .groupby(monthly_financial_simulation["user_id"])
    .cumprod()
)

# Inflation-adjusted expenditure
monthly_financial_simulation["monthly_expenditure_dynamic"] = (
    monthly_financial_simulation["monthly_expenditure"]
    * monthly_financial_simulation["cumulative_inflation_factor"]
)

print("===== Inflation-Adjusted Expenditure =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nMissing values:")

display(
    monthly_financial_simulation[
        [
            "cumulative_inflation_factor",
            "monthly_expenditure_dynamic"
        ]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nUSER_00001 expenditure evolution:")

display(
    monthly_financial_simulation[
        monthly_financial_simulation["user_id"] == "USER_00001"
    ][
        [
            "period",
            "monthly_expenditure",
            "monthly_inflation_rate",
            "cumulative_inflation_factor",
            "monthly_expenditure_dynamic"
        ]
    ].head(12)
)

print("\nExpenditure comparison:")

expenditure_comparison = pd.DataFrame({
    "baseline_expenditure": [
        monthly_financial_simulation["monthly_expenditure"].min(),
        monthly_financial_simulation["monthly_expenditure"].median(),
        monthly_financial_simulation["monthly_expenditure"].max()
    ],
    "dynamic_expenditure": [
        monthly_financial_simulation["monthly_expenditure_dynamic"].min(),
        monthly_financial_simulation["monthly_expenditure_dynamic"].median(),
        monthly_financial_simulation["monthly_expenditure_dynamic"].max()
    ]
}, index=["Minimum", "Median", "Maximum"])

display(expenditure_comparison)

===== Inflation-Adjusted Expenditure =====

Shape:
(1430000, 34)

Missing values:

                             missing_values
cumulative_inflation_factor               0
monthly_expenditure_dynamic               0

USER_00001 expenditure evolution:

,period,monthly_expenditure,monthly_inflation_rate,cumulative_inflation_factor,monthly_expenditure_dynamic
0,2015-02-01,36870.0,0.007623,1.007623,37151.049489
1,2015-03-01,36870.0,0.004521,1.012178,37318.993471
2,2015-04-01,36870.0,0.008102,1.020379,37621.368410
3,2015-05-01,36870.0,0.007697,1.028233,37910.938491
4,2015-06-01,36870.0,0.007623,1.036071,38199.922756
5,2015-07-01,36870.0,0.007623,1.043968,38491.109867
6,2015-08-01,36870.0,0.006454,1.050706,38739.515313
7,2015-09-01,36870.0,0.007623,1.058715,39034.815584
8,2015-10-01,36870.0,0.007790,1.066962,39338.902774
9,2015-11-01,36870.0,0.004521,1.071786,39516.737103
10,2015-12-01,36870.0,0.007623,1.079956,39817.961914
11,2016-01-01,36870.0,0.007623,1.088188,40121.482875

Expenditure comparison:

         baseline_expenditure  dynamic_expenditure
Minimum                 850.0         8.564793e+02
Median                35750.0         5.931989e+04
Maximum              530500.0         1.473339e+06

In [122]:
# 13.7. Validate Inflation-Adjusted Expenditure

print("===== Inflation-Adjusted Expenditure Validation =====")

# 1. Check for invalid expenditure values
negative_expenditure = (
    monthly_financial_simulation["monthly_expenditure_dynamic"] < 0
).sum()

zero_expenditure = (
    monthly_financial_simulation["monthly_expenditure_dynamic"] == 0
).sum()

# 2. Compare dynamic expenditure against baseline
below_baseline = (
    monthly_financial_simulation["monthly_expenditure_dynamic"]
    < monthly_financial_simulation["monthly_expenditure"]
).sum()

# 3. Verify mathematical relationship
expected_dynamic_expenditure = (
    monthly_financial_simulation["monthly_expenditure"]
    * monthly_financial_simulation["cumulative_inflation_factor"]
)

calculation_difference = (
    monthly_financial_simulation["monthly_expenditure_dynamic"]
    - expected_dynamic_expenditure
).abs().max()

print("\nInvalid expenditure checks:")
print("Negative expenditure:", negative_expenditure)
print("Zero expenditure:", zero_expenditure)
print("Below baseline expenditure:", below_baseline)

print("\nMaximum calculation difference:")
print(calculation_difference)

# 4. Long-term inflation effect
expenditure_growth = (
    monthly_financial_simulation
    .groupby("user_id")
    .apply(
        lambda x:
        x["monthly_expenditure_dynamic"].iloc[-1]
        / x["monthly_expenditure_dynamic"].iloc[0]
    )
)

print("\nUser expenditure growth statistics:")

display(
    expenditure_growth.describe()
)

# 5. Check final simulation month
print("\nFinal-month expenditure sample:")

display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "monthly_expenditure",
            "cumulative_inflation_factor",
            "monthly_expenditure_dynamic"
        ]
    ].tail(10)
)

===== Inflation-Adjusted Expenditure Validation =====

Invalid expenditure checks:
Negative expenditure: 0
Zero expenditure: 0
Below baseline expenditure: 0

Maximum calculation difference:
0.0

User expenditure growth statistics:

/tmp/ipykernel_1336/272038393.py:43: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

count    1.000000e+04
mean     2.756255e+00
std      2.977341e-13
min      2.756255e+00
25%      2.756255e+00
50%      2.756255e+00
75%      2.756255e+00
max      2.756255e+00
dtype: float64

Final-month expenditure sample:

,user_id,period,monthly_expenditure,cumulative_inflation_factor,monthly_expenditure_dynamic
1429990,USER_10000,2026-03-01,105000.0,2.608821,273926.163544
1429991,USER_10000,2026-04-01,105000.0,2.629958,276145.634096
1429992,USER_10000,2026-05-01,105000.0,2.649254,278171.655009
1429993,USER_10000,2026-06-01,105000.0,2.671070,280462.344812
1429994,USER_10000,2026-07-01,105000.0,2.691878,282647.189419
1429995,USER_10000,2026-08-01,105000.0,2.701422,283649.296548
1429996,USER_10000,2026-09-01,105000.0,2.718856,285479.849899
1429997,USER_10000,2026-10-01,105000.0,2.739581,287655.981329
1429998,USER_10000,2026-11-01,105000.0,2.760667,289870.057246
1429999,USER_10000,2026-12-01,105000.0,2.777265,291612.834245

In [123]:
# 13.8. Generate Dynamic Monthly Income

# Baseline income is kept unchanged because no empirical
# individual salary-growth model is currently available.
monthly_financial_simulation["monthly_income_dynamic"] = (
    monthly_financial_simulation["monthly_income"]
)

print("===== Dynamic Monthly Income =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nMissing values:")

display(
    monthly_financial_simulation[
        ["monthly_income_dynamic"]
    ]
    .isna()
    .sum()
    .to_frame("missing_values")
)

print("\nIncome comparison:")

display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "monthly_income",
            "monthly_income_dynamic"
        ]
    ].head(10)
)

print("\nIncome difference validation:")

income_difference = (
    monthly_financial_simulation["monthly_income_dynamic"]
    - monthly_financial_simulation["monthly_income"]
)

print("Maximum absolute difference:", income_difference.abs().max())

===== Dynamic Monthly Income =====

Shape:
(1430000, 35)

Missing values:

                        missing_values
monthly_income_dynamic               0

Income comparison:

      user_id     period  monthly_income  monthly_income_dynamic
0  USER_00001 2015-02-01    51351.335334            51351.335334
1  USER_00001 2015-03-01    51351.335334            51351.335334
2  USER_00001 2015-04-01    51351.335334            51351.335334
3  USER_00001 2015-05-01    51351.335334            51351.335334
4  USER_00001 2015-06-01    51351.335334            51351.335334
5  USER_00001 2015-07-01    51351.335334            51351.335334
6  USER_00001 2015-08-01    51351.335334            51351.335334
7  USER_00001 2015-09-01    51351.335334            51351.335334
8  USER_00001 2015-10-01    51351.335334            51351.335334
9  USER_00001 2015-11-01    51351.335334            51351.335334

Income difference validation:
Maximum absolute difference: 0.0

In [124]:
# 13.9. Calculate Dynamic Monthly Cash Flow

monthly_financial_simulation["monthly_surplus_dynamic"] = (
    monthly_financial_simulation["monthly_income_dynamic"]
    - monthly_financial_simulation["monthly_expenditure_dynamic"]
    - monthly_financial_simulation["monthly_emi"]
)

# Separate positive and negative cash-flow capacity
monthly_financial_simulation["positive_cash_flow"] = (
    monthly_financial_simulation["monthly_surplus_dynamic"]
    .clip(lower=0)
)

monthly_financial_simulation["cash_flow_status"] = np.where(
    monthly_financial_simulation["monthly_surplus_dynamic"] >= 0,
    "surplus",
    "deficit"
)

print("===== Dynamic Monthly Cash Flow =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nMissing values:")

display(
    monthly_financial_simulation[
        [
            "monthly_surplus_dynamic",
            "positive_cash_flow",
            "cash_flow_status"
        ]
    ].isna()
    .sum()
    .to_frame("missing_values")
)

print("\nUSER_00001 cash-flow evolution:")

display(
    monthly_financial_simulation[
        monthly_financial_simulation["user_id"] == "USER_00001"
    ][
        [
            "period",
            "monthly_income_dynamic",
            "monthly_expenditure_dynamic",
            "monthly_emi",
            "monthly_surplus_dynamic",
            "cash_flow_status"
        ]
    ].head(12)
)

print("\nOverall cash-flow status:")

display(
    monthly_financial_simulation[
        "cash_flow_status"
    ].value_counts()
)

print("\nDynamic surplus statistics:")

display(
    monthly_financial_simulation[
        "monthly_surplus_dynamic"
    ].describe()
)

===== Dynamic Monthly Cash Flow =====

Shape:
(1430000, 38)

Missing values:

                         missing_values
monthly_surplus_dynamic               0
positive_cash_flow                    0
cash_flow_status                      0

USER_00001 cash-flow evolution:

,period,monthly_income_dynamic,monthly_expenditure_dynamic,monthly_emi,monthly_surplus_dynamic,cash_flow_status
0,2015-02-01,51351.335334,37151.049489,0.0,14200.285845,surplus
1,2015-03-01,51351.335334,37318.993471,0.0,14032.341863,surplus
2,2015-04-01,51351.335334,37621.368410,0.0,13729.966924,surplus
3,2015-05-01,51351.335334,37910.938491,0.0,13440.396843,surplus
4,2015-06-01,51351.335334,38199.922756,0.0,13151.412578,surplus
5,2015-07-01,51351.335334,38491.109867,0.0,12860.225467,surplus
6,2015-08-01,51351.335334,38739.515313,0.0,12611.820021,surplus
7,2015-09-01,51351.335334,39034.815584,0.0,12316.519750,surplus
8,2015-10-01,51351.335334,39338.902774,0.0,12012.432560,surplus
9,2015-11-01,51351.335334,39516.737103,0.0,11834.598231,surplus
10,2015-12-01,51351.335334,39817.961914,0.0,11533.373420,surplus
11,2016-01-01,51351.335334,40121.482875,0.0,11229.852459,surplus

Overall cash-flow status:

cash_flow_status
deficit    1110904
surplus     319096
Name: count, dtype: int64

Dynamic surplus statistics:

count    1.430000e+06
mean    -2.221933e+04
std      3.944013e+04
min     -7.977432e+05
25%     -3.378622e+04
50%     -1.416201e+04
75%     -1.322949e+03
max      3.979993e+05
Name: monthly_surplus_dynamic, dtype: float64

In [126]:
# 13.10. Add Financial Situation and Validate Dynamic Cash Flow

# Load financial situation from the final synthetic population
financial_situation_reference = final_population[
    [
        "user_id",
        "financial_situation"
    ]
].drop_duplicates("user_id")

# Make sure the simulation does not already contain the column
if "financial_situation" in monthly_financial_simulation.columns:
    monthly_financial_simulation = monthly_financial_simulation.drop(
        columns=["financial_situation"]
    )

# Add financial situation to every user's monthly simulation
monthly_financial_simulation = monthly_financial_simulation.merge(
    financial_situation_reference,
    on="user_id",
    how="left"
)

monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

print("===== Financial Situation Added =====")

print("\nShape:")
print(monthly_financial_simulation.shape)

print("\nMissing financial situations:")

display(
    monthly_financial_simulation[
        ["financial_situation"]
    ].isna()
    .sum()
    .to_frame("missing_values")
)

print("\nFinancial situation distribution:")

display(
    monthly_financial_simulation[
        ["financial_situation"]
    ].drop_duplicates()
)

# ---------------------------------------------------------
# User-level cash-flow validation
# ---------------------------------------------------------

cashflow_user_summary = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        financial_situation=("financial_situation", "first"),
        initial_surplus=("monthly_surplus_dynamic", "first"),
        final_surplus=("monthly_surplus_dynamic", "last"),
        minimum_surplus=("monthly_surplus_dynamic", "min"),
        maximum_surplus=("monthly_surplus_dynamic", "max"),
        deficit_months=(
            "cash_flow_status",
            lambda x: (x == "deficit").sum()
        ),
        surplus_months=(
            "cash_flow_status",
            lambda x: (x == "surplus").sum()
        ),
        initial_expenditure=(
            "monthly_expenditure_dynamic",
            "first"
        ),
        final_expenditure=(
            "monthly_expenditure_dynamic",
            "last"
        )
    )
    .reset_index()
)

# Whether the user ever experiences a deficit
cashflow_user_summary["ever_deficit"] = (
    cashflow_user_summary["deficit_months"] > 0
)

# Whether the user stays in surplus for the complete simulation
cashflow_user_summary["always_surplus"] = (
    cashflow_user_summary["deficit_months"] == 0
)

# Proportion of months spent in deficit
cashflow_user_summary["deficit_month_ratio"] = (
    cashflow_user_summary["deficit_months"] / 143
)

# Expenditure growth factor
cashflow_user_summary["expenditure_growth_factor"] = (
    cashflow_user_summary["final_expenditure"]
    / cashflow_user_summary["initial_expenditure"]
)

print("\n===== Dynamic Cash-Flow Validation =====")

print("\nUser-level summary shape:")
print(cashflow_user_summary.shape)

print("\nCash-flow outcomes by financial situation:")

cashflow_by_situation = (
    cashflow_user_summary
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        median_initial_surplus=("initial_surplus", "median"),
        median_final_surplus=("final_surplus", "median"),
        median_minimum_surplus=("minimum_surplus", "median"),
        median_deficit_month_ratio=(
            "deficit_month_ratio",
            "median"
        ),
        users_ever_deficit=("ever_deficit", "sum"),
        users_always_surplus=("always_surplus", "sum"),
        median_expenditure_growth=(
            "expenditure_growth_factor",
            "median"
        )
    )
)

display(cashflow_by_situation)

print("\nOverall user-level outcomes:")

display(
    cashflow_user_summary[
        [
            "initial_surplus",
            "final_surplus",
            "minimum_surplus",
            "deficit_month_ratio",
            "expenditure_growth_factor"
        ]
    ].describe()
)

print("\nUsers entering deficit at least once:")

print(
    cashflow_user_summary["ever_deficit"].sum(),
    "out of",
    len(cashflow_user_summary)
)

print("\nUsers remaining in surplus throughout:")

print(
    cashflow_user_summary["always_surplus"].sum(),
    "out of",
    len(cashflow_user_summary)
)

===== Financial Situation Added =====

Shape:
(1430000, 39)

Missing financial situations:

                     missing_values
financial_situation               0

Financial situation distribution:

    financial_situation
0       moderate_saving
143    financial_stress
286          low_saving
572         high_saving

===== Dynamic Cash-Flow Validation =====

User-level summary shape:
(10000, 14)

Cash-flow outcomes by financial situation:

,users,median_initial_surplus,median_final_surplus,median_minimum_surplus,median_deficit_month_ratio,users_ever_deficit,users_always_surplus,median_expenditure_growth
financial_situation,,,,,,,,
financial_stress,474,-7452.632230,-69215.916648,-69215.916648,1.000000,474,0,2.756255
high_saving,2043,22899.753197,-37766.034900,-37766.034900,0.503497,2043,0,2.756255
low_saving,2923,603.926065,-62915.828042,-62915.828042,0.972028,2923,0,2.756255
moderate_saving,4560,9078.004515,-52816.806699,-52816.806699,0.748252,4560,0,2.756255

Overall user-level outcomes:

,initial_surplus,final_surplus,minimum_surplus,deficit_month_ratio,expenditure_growth_factor
count,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04
mean,11078.555027,-68504.848306,-68504.848306,0.776856,2.756255e+00
std,20245.410131,59959.711018,59959.711018,0.187740,2.977341e-13
min,-166688.687167,-797743.157523,-797743.157523,0.321678,2.756255e+00
25%,1006.603133,-80167.301601,-80167.301601,0.636364,2.756255e+00
50%,7339.043285,-53125.299709,-53125.299709,0.783217,2.756255e+00
75%,16737.478182,-35195.845900,-35195.845900,0.958042,2.756255e+00
max,397999.256931,-1103.335675,-1103.335675,1.000000,2.756255e+00

Users entering deficit at least once:
10000 out of 10000

Users remaining in surplus throughout:
0 out of 10000

In [128]:
# 13.11. Inspect Income-Evolution Requirements
# Corrected version

print("===== Income Evolution Requirements =====")

# ---------------------------------------------------------
# 1. Current income distribution
# ---------------------------------------------------------

print("\nCurrent synthetic monthly income:")

display(
    final_population["monthly_income"].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    ).to_frame("monthly_income")
)

# ---------------------------------------------------------
# 2. Current income by financial situation
# ---------------------------------------------------------

print("\nIncome by financial situation:")

income_by_situation = (
    final_population
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        median_income=("monthly_income", "median"),
        mean_income=("monthly_income", "mean"),
        median_expenditure=("monthly_expenditure", "median"),
        median_surplus=("monthly_surplus", "median")
    )
    .sort_values("median_income")
)

display(income_by_situation)

# ---------------------------------------------------------
# 3. Inspect inflation variables from the monthly
#    financial simulation
# ---------------------------------------------------------

print("\nInflation variables currently available in simulation:")

inflation_columns = [
    column
    for column in monthly_financial_simulation.columns
    if "inflation" in column.lower()
]

print(inflation_columns)

display(
    monthly_financial_simulation[
        [
            "period",
            "annual_inflation_rate",
            "monthly_inflation_rate",
            "inflation_level",
            "inflation_regime"
        ]
    ].head(10)
)

# ---------------------------------------------------------
# 4. Check whether any income-growth variable already exists
# ---------------------------------------------------------

income_related_columns = [
    column
    for column in monthly_financial_simulation.columns
    if any(
        keyword in column.lower()
        for keyword in [
            "income",
            "salary",
            "wage",
            "earning"
        ]
    )
]

print("\nIncome-related columns currently available:")

print(income_related_columns)

# ---------------------------------------------------------
# 5. Inspect available economic variables
# ---------------------------------------------------------

print("\nEconomic environment columns:")

print(
    economic_environment.columns.tolist()
)

# ---------------------------------------------------------
# 6. Current income behaviour
# ---------------------------------------------------------

print("\n===== Current Income Behaviour =====")

income_variation = (
    monthly_financial_simulation
    .groupby("user_id")["monthly_income_dynamic"]
    .nunique()
)

print(
    "Maximum number of different monthly income values "
    "for any user:",
    income_variation.max()
)

print(
    "Users whose income currently changes:",
    (income_variation > 1).sum()
)

print(
    "Users whose income currently remains constant:",
    (income_variation == 1).sum()
)

print("\nCurrent expenditure behaviour:")

expenditure_variation = (
    monthly_financial_simulation
    .groupby("user_id")["monthly_expenditure_dynamic"]
    .nunique()
)

print(
    "Maximum number of different monthly expenditure values "
    "for any user:",
    expenditure_variation.max()
)

print(
    "Users whose expenditure changes:",
    (expenditure_variation > 1).sum()
)

===== Income Evolution Requirements =====

Current synthetic monthly income:

       monthly_income
count    10000.000000
mean     61588.311653
std      53908.829380
min       1257.339650
10%      21858.582590
25%      32005.389162
50%      47770.485750
75%      71013.157446
90%     111863.791130
95%     155062.553290
max     845993.172582

Income by financial situation:

,users,median_income,mean_income,median_expenditure,median_surplus
financial_situation,,,,,
financial_stress,474,34318.040553,43319.191463,35000.0,-703.725642
low_saving,2923,40566.248112,51661.583451,36000.0,4757.603999
moderate_saving,4560,49010.663934,61883.632923,35500.0,13328.679492
high_saving,2043,61917.549255,79370.359871,35000.0,26164.509534

Inflation variables currently available in simulation:
['inflation_level', 'inflation_change', 'inflation_pct_change', 'inflation_trend', 'inflation_regime', 'annual_inflation_rate', 'monthly_inflation_rate', 'cumulative_inflation_factor']

,period,annual_inflation_rate,monthly_inflation_rate,inflation_level,inflation_regime
0,2015-02-01,9.540669,0.007623,0.762137,medium
1,2015-03-01,5.561614,0.004521,0.179194,low
2,2015-04-01,10.168135,0.008102,0.854063,high
3,2015-05-01,9.637562,0.007697,0.776332,medium
4,2015-06-01,9.540669,0.007623,0.762137,medium
5,2015-07-01,9.540669,0.007623,0.762137,medium
6,2015-08-01,8.025177,0.006454,0.540113,low
7,2015-09-01,9.540669,0.007623,0.762137,medium
8,2015-10-01,9.759300,0.007790,0.794167,high
9,2015-11-01,5.561614,0.004521,0.179194,low

Income-related columns currently available:
['monthly_income', 'monthly_income_dynamic']

Economic environment columns:
['period', 'inflation_level', 'inflation_change', 'inflation_pct_change', 'inflation_trend', 'inflation_regime', 'nifty_monthly_return', 'nifty_return_volatility', 'nifty_3m_volatility', 'nifty_ma_gap', 'market_return_regime', 'market_volatility_regime', 'average_walr', 'walr_change', 'credit_pressure', 'walr_3period_ma', 'walr_momentum', 'walr_regime']

===== Current Income Behaviour =====
Maximum number of different monthly income values for any user: 1
Users whose income currently changes: 0
Users whose income currently remains constant: 10000

Current expenditure behaviour:
Maximum number of different monthly expenditure values for any user: 143
Users whose expenditure changes: 10000

In [129]:
# 13.12. Inspect Inflation-Based Income Adjustment
#
# Purpose:
# Understand how income would evolve relative to inflation
# before selecting the final income-evolution model.

print("===== Inflation-Based Income Adjustment Inspection =====")

# ---------------------------------------------------------
# 1. Obtain the common inflation path
# ---------------------------------------------------------

inflation_path = (
    monthly_financial_simulation[
        [
            "period",
            "annual_inflation_rate",
            "monthly_inflation_rate",
            "cumulative_inflation_factor"
        ]
    ]
    .drop_duplicates("period")
    .sort_values("period")
    .reset_index(drop=True)
)

print("\nInflation path:")

display(
    inflation_path.head(10)
)

print("\nFinal inflation factor:")

print(
    inflation_path["cumulative_inflation_factor"].iloc[-1]
)

# ---------------------------------------------------------
# 2. Define income adjustment scenarios
#
# These are NOT yet being applied to the simulation.
# They are only used to understand the effect of
# different degrees of inflation adjustment.
# ---------------------------------------------------------

adjustment_levels = {
    "no_adjustment": 0.00,
    "partial_adjustment": 0.50,
    "full_adjustment": 1.00
}

scenario_results = []

for scenario_name, adjustment_level in adjustment_levels.items():

    # Income multiplier based on cumulative inflation
    income_multiplier = (
        inflation_path["cumulative_inflation_factor"]
        ** adjustment_level
    )

    scenario_results.append(
        {
            "scenario": scenario_name,
            "adjustment_level": adjustment_level,
            "initial_multiplier": income_multiplier.iloc[0],
            "final_multiplier": income_multiplier.iloc[-1]
        }
    )

income_scenario_summary = pd.DataFrame(
    scenario_results
)

print("\nIncome adjustment scenario comparison:")

display(
    income_scenario_summary
)

# ---------------------------------------------------------
# 3. Calculate what happens to the population median income
# ---------------------------------------------------------

population_median_income = (
    final_population["monthly_income"].median()
)

scenario_income_impact = []

for scenario_name, adjustment_level in adjustment_levels.items():

    final_multiplier = (
        inflation_path["cumulative_inflation_factor"].iloc[-1]
        ** adjustment_level
    )

    final_income = (
        population_median_income
        * final_multiplier
    )

    scenario_income_impact.append(
        {
            "scenario": scenario_name,
            "adjustment_level": adjustment_level,
            "initial_median_income": population_median_income,
            "final_median_income": final_income,
            "income_growth_factor": final_multiplier
        }
    )

scenario_income_impact = pd.DataFrame(
    scenario_income_impact
)

print("\nImpact on population median income:")

display(
    scenario_income_impact
)

# ---------------------------------------------------------
# 4. Compare final income adjustment with final expenditure
# ---------------------------------------------------------

final_expenditure_multiplier = (
    inflation_path["cumulative_inflation_factor"].iloc[-1]
)

print("\nFinal expenditure growth factor:")
print(final_expenditure_multiplier)

print("\nRelative final income-to-expenditure adjustment:")

relative_adjustment = []

for scenario_name, adjustment_level in adjustment_levels.items():

    income_multiplier = (
        final_expenditure_multiplier
        ** adjustment_level
    )

    relative_to_expenses = (
        income_multiplier
        / final_expenditure_multiplier
    )

    relative_adjustment.append(
        {
            "scenario": scenario_name,
            "income_growth_factor": income_multiplier,
            "expenditure_growth_factor": final_expenditure_multiplier,
            "income_growth_relative_to_expenditure":
                relative_to_expenses
        }
    )

relative_adjustment = pd.DataFrame(
    relative_adjustment
)

display(relative_adjustment)

print("\n===== Inspection Complete =====")
print(
    "No income values have been modified in this step."
)

===== Inflation-Based Income Adjustment Inspection =====

Inflation path:

,period,annual_inflation_rate,monthly_inflation_rate,cumulative_inflation_factor
0,2015-02-01,9.540669,0.007623,1.007623
1,2015-03-01,5.561614,0.004521,1.012178
2,2015-04-01,10.168135,0.008102,1.020379
3,2015-05-01,9.637562,0.007697,1.028233
4,2015-06-01,9.540669,0.007623,1.036071
5,2015-07-01,9.540669,0.007623,1.043968
6,2015-08-01,8.025177,0.006454,1.050706
7,2015-09-01,9.540669,0.007623,1.058715
8,2015-10-01,9.759300,0.007790,1.066962
9,2015-11-01,5.561614,0.004521,1.071786

Final inflation factor:
2.7772650880434084

Income adjustment scenario comparison:

             scenario  adjustment_level  initial_multiplier  final_multiplier
0       no_adjustment               0.0            1.000000          1.000000
1  partial_adjustment               0.5            1.003804          1.666513
2     full_adjustment               1.0            1.007623          2.777265

Impact on population median income:

,scenario,adjustment_level,initial_median_income,final_median_income,income_growth_factor
0,no_adjustment,0.0,47770.48575,47770.485750,1.000000
1,partial_adjustment,0.5,47770.48575,79610.128480,1.666513
2,full_adjustment,1.0,47770.48575,132671.302313,2.777265

Final expenditure growth factor:
2.7772650880434084

Relative final income-to-expenditure adjustment:

,scenario,income_growth_factor,expenditure_growth_factor,income_growth_relative_to_expenditure
0,no_adjustment,1.000000,2.777265,0.360066
1,partial_adjustment,1.666513,2.777265,0.600055
2,full_adjustment,2.777265,2.777265,1.000000

===== Inspection Complete =====
No income values have been modified in this step.

In [130]:
# 13.13. Compare Income Adjustment Scenarios
#
# Purpose:
# Evaluate how different inflation-linked income adjustments
# affect final monthly cash flow before selecting the
# simulation's baseline income model.
#
# IMPORTANT:
# This cell does NOT modify monthly_income_dynamic.

# ---------------------------------------------------------
# 1. Obtain the final cumulative inflation factor
# ---------------------------------------------------------

final_inflation_factor = (
    inflation_path["cumulative_inflation_factor"].iloc[-1]
)

# ---------------------------------------------------------
# 2. Define scenario levels
# ---------------------------------------------------------

income_adjustment_scenarios = {
    "no_adjustment": 0.00,
    "partial_adjustment": 0.50,
    "full_adjustment": 1.00
}

scenario_cashflow_results = []

# ---------------------------------------------------------
# 3. Evaluate each scenario
# ---------------------------------------------------------

for scenario_name, adjustment_level in income_adjustment_scenarios.items():

    # Income multiplier at the end of the simulation
    income_multiplier = (
        final_inflation_factor ** adjustment_level
    )

    # Final income for every user
    scenario_income = (
        final_population["monthly_income"]
        * income_multiplier
    )

    # Final inflation-adjusted expenditure
    scenario_expenditure = (
        monthly_financial_simulation
        .loc[
            monthly_financial_simulation["period"]
            == monthly_financial_simulation["period"].max(),
            [
                "user_id",
                "monthly_expenditure_dynamic",
                "monthly_emi"
            ]
        ]
        .drop_duplicates("user_id")
    )

    # Match income with final expenditure
    scenario_final = (
        final_population[
            [
                "user_id",
                "financial_situation"
            ]
        ]
        .copy()
    )

    scenario_final["scenario_income"] = (
        scenario_income.values
    )

    scenario_final = scenario_final.merge(
        scenario_expenditure,
        on="user_id",
        how="left"
    )

    # Calculate final cash flow
    scenario_final["final_cash_flow"] = (
        scenario_final["scenario_income"]
        - scenario_final["monthly_expenditure_dynamic"]
        - scenario_final["monthly_emi"]
    )

    # Calculate deficit indicator
    scenario_final["final_deficit"] = (
        scenario_final["final_cash_flow"] < 0
    )

    # Store summary
    scenario_cashflow_results.append(
        {
            "scenario": scenario_name,
            "adjustment_level": adjustment_level,
            "income_growth_factor": income_multiplier,
            "median_final_income": scenario_final[
                "scenario_income"
            ].median(),
            "median_final_cash_flow": scenario_final[
                "final_cash_flow"
            ].median(),
            "mean_final_cash_flow": scenario_final[
                "final_cash_flow"
            ].mean(),
            "users_final_deficit": scenario_final[
                "final_deficit"
            ].sum(),
            "percentage_final_deficit": (
                scenario_final["final_deficit"].mean() * 100
            )
        }
    )

# ---------------------------------------------------------
# 4. Display comparison
# ---------------------------------------------------------

scenario_cashflow_summary = pd.DataFrame(
    scenario_cashflow_results
)

print("===== Income Adjustment Scenario Comparison =====")

display(
    scenario_cashflow_summary
)

# ---------------------------------------------------------
# 5. Show results by financial situation
# ---------------------------------------------------------

print("\nFinal cash flow by financial situation:")

for scenario_name, adjustment_level in income_adjustment_scenarios.items():

    income_multiplier = (
        final_inflation_factor ** adjustment_level
    )

    scenario_final = (
        final_population[
            [
                "user_id",
                "financial_situation",
                "monthly_income"
            ]
        ]
        .copy()
    )

    scenario_final["scenario_income"] = (
        scenario_final["monthly_income"]
        * income_multiplier
    )

    scenario_final = scenario_final.merge(
        scenario_expenditure,
        on="user_id",
        how="left"
    )

    scenario_final["final_cash_flow"] = (
        scenario_final["scenario_income"]
        - scenario_final["monthly_expenditure_dynamic"]
        - scenario_final["monthly_emi"]
    )

    situation_summary = (
        scenario_final
        .groupby("financial_situation")
        .agg(
            users=("user_id", "count"),
            median_final_cash_flow=(
                "final_cash_flow",
                "median"
            ),
            users_final_deficit=(
                "final_cash_flow",
                lambda x: (x < 0).sum()
            )
        )
    )

    situation_summary["scenario"] = scenario_name

    print(f"\n--- {scenario_name} ---")

    display(
        situation_summary
    )

print("\n===== Scenario Analysis Complete =====")
print("No simulation income values were modified.")

===== Income Adjustment Scenario Comparison =====

,scenario,adjustment_level,income_growth_factor,median_final_income,median_final_cash_flow,mean_final_cash_flow,users_final_deficit,percentage_final_deficit
0,no_adjustment,0.0,1.000000,47770.485750,-53125.299709,-68504.848306,10000,100.00
1,partial_adjustment,0.5,1.666513,79610.128480,-20884.227933,-27455.447017,8837,88.37
2,full_adjustment,1.0,2.777265,132671.302313,27348.749057,40953.907825,817,8.17

Final cash flow by financial situation:

--- no_adjustment ---

,users,median_final_cash_flow,users_final_deficit,scenario
financial_situation,,,,
financial_stress,474,-69215.916648,474,no_adjustment
high_saving,2043,-37766.034900,2043,no_adjustment
low_saving,2923,-62915.828042,2923,no_adjustment
moderate_saving,4560,-52816.806699,4560,no_adjustment

--- partial_adjustment ---

,users,median_final_cash_flow,users_final_deficit,scenario
financial_situation,,,,
financial_stress,474,-46646.743781,474,partial_adjustment
high_saving,2043,1522.047227,880,partial_adjustment
low_saving,2923,-35547.046023,2923,partial_adjustment
moderate_saving,4560,-19783.212088,4560,partial_adjustment

--- full_adjustment ---

,users,median_final_cash_flow,users_final_deficit,scenario
financial_situation,,,,
financial_stress,474,-8443.239237,414,full_adjustment
high_saving,2043,70004.518337,0,full_adjustment
low_saving,2923,7883.125067,403,full_adjustment
moderate_saving,4560,32967.749330,0,full_adjustment

===== Scenario Analysis Complete =====
No simulation income values were modified.

In [131]:
# 13.14. Implement Dynamic Income Evolution
#
# Baseline assumption:
# Income adjusts with the same cumulative inflation factor
# used to evolve expenditure.
#
# This is a synthetic modelling assumption because the
# available datasets do not contain individual salary-growth
# histories.

# ---------------------------------------------------------
# 1. Calculate dynamic monthly income
# ---------------------------------------------------------

monthly_financial_simulation["monthly_income_dynamic"] = (
    monthly_financial_simulation["monthly_income"]
    * monthly_financial_simulation["cumulative_inflation_factor"]
)

# ---------------------------------------------------------
# 2. Calculate income growth factor for each user
# ---------------------------------------------------------

income_growth_validation = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        initial_income=("monthly_income_dynamic", "first"),
        final_income=("monthly_income_dynamic", "last")
    )
    .reset_index()
)

income_growth_validation["income_growth_factor"] = (
    income_growth_validation["final_income"]
    / income_growth_validation["initial_income"]
)

# ---------------------------------------------------------
# 3. Validate income evolution
# ---------------------------------------------------------

print("===== Dynamic Income Evolution =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing dynamic income values:")

print(
    monthly_financial_simulation[
        "monthly_income_dynamic"
    ].isna().sum()
)

print("\nDynamic income statistics:")

display(
    monthly_financial_simulation[
        "monthly_income_dynamic"
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    ).to_frame("monthly_income_dynamic")
)

print("\nIncome growth factor across users:")

display(
    income_growth_validation[
        "income_growth_factor"
    ].describe()
)

print("\nExpected final inflation factor:")

print(
    inflation_path[
        "cumulative_inflation_factor"
    ].iloc[-1]
)

print("\nActual median income growth factor:")

print(
    income_growth_validation[
        "income_growth_factor"
    ].median()
)

print("\nMaximum difference between income growth and inflation factor:")

print(
    abs(
        income_growth_validation["income_growth_factor"]
        - inflation_path["cumulative_inflation_factor"].iloc[-1]
    ).max()
)

# ---------------------------------------------------------
# 4. Display one user's income evolution
# ---------------------------------------------------------

print("\nSample user income evolution:")

display(
    monthly_financial_simulation[
        monthly_financial_simulation["user_id"] == "USER_00001"
    ][
        [
            "period",
            "monthly_income",
            "cumulative_inflation_factor",
            "monthly_income_dynamic"
        ]
    ].head(12)
)

print("\n===== Dynamic Income Evolution Complete =====")

===== Dynamic Income Evolution =====

Simulation shape:
(1430000, 39)

Missing dynamic income values:
0

Dynamic income statistics:

       monthly_income_dynamic
count            1.430000e+06
mean             1.076592e+05
std              1.030418e+05
min              1.266924e+03
10%              3.329880e+04
25%              5.085573e+04
50%              7.988276e+04
75%              1.272062e+05
90%              2.033180e+05
95%              2.813168e+05
max              2.349547e+06

Income growth factor across users:

count    1.000000e+04
mean     2.756255e+00
std      2.977617e-13
min      2.756255e+00
25%      2.756255e+00
50%      2.756255e+00
75%      2.756255e+00
max      2.756255e+00
Name: income_growth_factor, dtype: float64

Expected final inflation factor:
2.7772650880434084

Actual median income growth factor:
2.756254943144745

Maximum difference between income growth and inflation factor:
0.02101014489866415

Sample user income evolution:

,period,monthly_income,cumulative_inflation_factor,monthly_income_dynamic
0,2015-02-01,51351.335334,1.007623,51742.771909
1,2015-03-01,51351.335334,1.012178,51976.678819
2,2015-04-01,51351.335334,1.020379,52397.816787
3,2015-05-01,51351.335334,1.028233,52801.120566
4,2015-06-01,51351.335334,1.036071,53203.608440
5,2015-07-01,51351.335334,1.043968,53609.164365
6,2015-08-01,51351.335334,1.050706,53955.135382
7,2015-09-01,51351.335334,1.058715,54366.419982
8,2015-10-01,51351.335334,1.066962,54789.942717
9,2015-11-01,51351.335334,1.071786,55037.624581
10,2015-12-01,51351.335334,1.079956,55457.160687
11,2016-01-01,51351.335334,1.088188,55879.894798

===== Dynamic Income Evolution Complete =====

In [132]:
# 13.15. Recalculate Dynamic Monthly Cash Flow
#
# Dynamic cash flow:
# Income - Inflation-adjusted Expenses - EMI

# ---------------------------------------------------------
# 1. Recalculate monthly dynamic surplus
# ---------------------------------------------------------

monthly_financial_simulation["monthly_surplus_dynamic"] = (
    monthly_financial_simulation["monthly_income_dynamic"]
    - monthly_financial_simulation["monthly_expenditure_dynamic"]
    - monthly_financial_simulation["monthly_emi"]
)

# ---------------------------------------------------------
# 2. Calculate positive cash flow
# ---------------------------------------------------------

monthly_financial_simulation["positive_cash_flow"] = (
    monthly_financial_simulation["monthly_surplus_dynamic"]
    .clip(lower=0)
)

# ---------------------------------------------------------
# 3. Classify monthly cash-flow status
# ---------------------------------------------------------

monthly_financial_simulation["cash_flow_status"] = np.where(
    monthly_financial_simulation["monthly_surplus_dynamic"] >= 0,
    "surplus",
    "deficit"
)

# ---------------------------------------------------------
# 4. Basic validation
# ---------------------------------------------------------

print("===== Dynamic Cash Flow Recalculated =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing dynamic cash-flow values:")

display(
    monthly_financial_simulation[
        [
            "monthly_surplus_dynamic",
            "positive_cash_flow",
            "cash_flow_status"
        ]
    ].isna().sum().to_frame("missing_values")
)

print("\nDynamic monthly cash-flow statistics:")

display(
    monthly_financial_simulation[
        "monthly_surplus_dynamic"
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    ).to_frame("monthly_surplus_dynamic")
)

# ---------------------------------------------------------
# 5. Surplus vs deficit observations
# ---------------------------------------------------------

print("\nMonthly cash-flow status:")

display(
    monthly_financial_simulation[
        "cash_flow_status"
    ].value_counts()
    .to_frame("observations")
)

# ---------------------------------------------------------
# 6. User-level final cash-flow check
# ---------------------------------------------------------

final_month = (
    monthly_financial_simulation["period"].max()
)

final_month_cashflow = (
    monthly_financial_simulation[
        monthly_financial_simulation["period"] == final_month
    ][
        [
            "user_id",
            "financial_situation",
            "monthly_income_dynamic",
            "monthly_expenditure_dynamic",
            "monthly_emi",
            "monthly_surplus_dynamic"
        ]
    ]
    .drop_duplicates("user_id")
)

print("\nFinal-month cash-flow summary:")

display(
    final_month_cashflow[
        "monthly_surplus_dynamic"
    ].describe()
)

print("\nUsers in final-month deficit:")

print(
    (
        final_month_cashflow["monthly_surplus_dynamic"] < 0
    ).sum(),
    "out of",
    len(final_month_cashflow)
)

print("\nUsers in final-month surplus:")

print(
    (
        final_month_cashflow["monthly_surplus_dynamic"] >= 0
    ).sum(),
    "out of",
    len(final_month_cashflow)
)

print("\n===== Dynamic Cash Flow Recalculation Complete =====")

===== Dynamic Cash Flow Recalculated =====

Simulation shape:
(1430000, 39)

Missing dynamic cash-flow values:

                         missing_values
monthly_surplus_dynamic               0
positive_cash_flow                    0
cash_flow_status                      0

Dynamic monthly cash-flow statistics:

       monthly_surplus_dynamic
count             1.430000e+06
mean              2.385152e+04
std               3.706327e+04
min              -2.102942e+05
10%              -2.247990e+03
25%               4.534104e+03
50%               1.471881e+04
75%               3.159846e+04
90%               5.813459e+04
95%               8.289771e+04
max               1.114664e+06

Monthly cash-flow status:

                  observations
cash_flow_status
surplus                1229420
deficit                 200580

Final-month cash-flow summary:

count    1.000000e+04
mean     4.095391e+04
std      5.498329e+04
min     -2.102942e+05
25%      1.059199e+04
50%      2.734875e+04
75%      5.308667e+04
max      1.114664e+06
Name: monthly_surplus_dynamic, dtype: float64

Users in final-month deficit:
817 out of 10000

Users in final-month surplus:
9183 out of 10000

===== Dynamic Cash Flow Recalculation Complete =====

In [133]:
# 13.16. Validate Dynamic Cash Flow by Financial Situation

# ---------------------------------------------------------
# 1. User-level cash-flow summary
# ---------------------------------------------------------

cashflow_by_user = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        financial_situation=("financial_situation", "first"),
        initial_surplus=("monthly_surplus_dynamic", "first"),
        final_surplus=("monthly_surplus_dynamic", "last"),
        minimum_surplus=("monthly_surplus_dynamic", "min"),
        maximum_surplus=("monthly_surplus_dynamic", "max"),
        deficit_months=(
            "cash_flow_status",
            lambda x: (x == "deficit").sum()
        ),
        total_months=("period", "count")
    )
    .reset_index()
)

# ---------------------------------------------------------
# 2. Deficit-month ratio
# ---------------------------------------------------------

cashflow_by_user["deficit_month_ratio"] = (
    cashflow_by_user["deficit_months"]
    / cashflow_by_user["total_months"]
)

# ---------------------------------------------------------
# 3. Ever-deficit indicator
# ---------------------------------------------------------

cashflow_by_user["ever_deficit"] = (
    cashflow_by_user["deficit_months"] > 0
)

# ---------------------------------------------------------
# 4. Always-surplus indicator
# ---------------------------------------------------------

cashflow_by_user["always_surplus"] = (
    cashflow_by_user["deficit_months"] == 0
)

# ---------------------------------------------------------
# 5. Summary by financial situation
# ---------------------------------------------------------

situation_cashflow_summary = (
    cashflow_by_user
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        median_initial_surplus=("initial_surplus", "median"),
        median_final_surplus=("final_surplus", "median"),
        median_minimum_surplus=("minimum_surplus", "median"),
        mean_deficit_month_ratio=("deficit_month_ratio", "mean"),
        median_deficit_month_ratio=("deficit_month_ratio", "median"),
        users_ever_deficit=("ever_deficit", "sum"),
        users_always_surplus=("always_surplus", "sum")
    )
    .reset_index()
)

print("===== Cash Flow Validation by Financial Situation =====")

print("\nUser-level cash-flow summary:")
display(cashflow_by_user.head(10))

print("\nCash-flow behaviour by financial situation:")
display(situation_cashflow_summary)

# ---------------------------------------------------------
# 6. Overall user-level statistics
# ---------------------------------------------------------

print("\nOverall user-level cash-flow statistics:")

display(
    cashflow_by_user[
        [
            "initial_surplus",
            "final_surplus",
            "minimum_surplus",
            "deficit_month_ratio"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

print("\nUsers who experienced at least one deficit:")
print(
    cashflow_by_user["ever_deficit"].sum(),
    "out of",
    len(cashflow_by_user)
)

print("\nUsers who remained surplus in every simulated month:")
print(
    cashflow_by_user["always_surplus"].sum(),
    "out of",
    len(cashflow_by_user)
)

print("\n===== Cash Flow Validation Complete =====")

===== Cash Flow Validation by Financial Situation =====

User-level cash-flow summary:

,user_id,financial_situation,initial_surplus,final_surplus,minimum_surplus,maximum_surplus,deficit_months,total_months,deficit_month_ratio,ever_deficit,always_surplus
0,USER_00001,moderate_saving,14591.722421,40218.507051,14591.722421,40218.507051,0,143,0.000000,False,True
1,USER_00002,financial_stress,-12907.221566,-14826.545009,-14826.545009,-12907.221566,143,143,1.000000,True,False
2,USER_00003,low_saving,2486.357847,6853.036106,2486.357847,6853.036106,0,143,0.000000,False,True
3,USER_00004,moderate_saving,1107.474425,15438.629409,1107.474425,15438.629409,0,143,0.000000,False,True
4,USER_00005,high_saving,41029.399584,113087.485418,41029.399584,113087.485418,0,143,0.000000,False,True
5,USER_00006,high_saving,22264.985133,61367.975332,22264.985133,61367.975332,0,143,0.000000,False,True
6,USER_00007,high_saving,27194.106795,74953.891278,27194.106795,74953.891278,0,143,0.000000,False,True
7,USER_00008,low_saving,-4479.370126,31184.910241,-4479.370126,31184.910241,29,143,0.202797,True,False
8,USER_00009,moderate_saving,27492.835466,75777.263653,27492.835466,75777.263653,0,143,0.000000,False,True
9,USER_00010,low_saving,5085.674418,14017.415255,5085.674418,14017.415255,0,143,0.000000,False,True

Cash-flow behaviour by financial situation:

,financial_situation,users,median_initial_surplus,median_final_surplus,median_minimum_surplus,mean_deficit_month_ratio,median_deficit_month_ratio,users_ever_deficit,users_always_surplus
0,financial_stress,474,-7165.318009,-8443.239237,-8898.885126,0.873418,1.0,414,60
1,high_saving,2043,23425.312797,70004.518337,23425.312797,0.000000,0.0,0,2043
2,low_saving,2923,800.810655,7883.125067,800.810655,0.324832,0.0,1411,1512
3,moderate_saving,4560,9473.284833,32967.749330,9473.284833,0.008591,0.0,293,4267

Overall user-level cash-flow statistics:

       initial_surplus  final_surplus  minimum_surplus  deficit_month_ratio
count     10000.000000   1.000000e+04     10000.000000         10000.000000
mean      11548.025152   4.095391e+04     11428.090727             0.140266
std       20517.223040   5.498329e+04     20747.111219             0.314513
min     -164169.110267  -2.102942e+05   -210294.161487             0.000000
10%       -4928.871005   1.478813e+03     -5180.282714             0.000000
25%        1261.371743   1.059199e+04      1261.371743             0.000000
50%        7698.089191   2.734875e+04      7698.089191             0.000000
75%       17221.991194   5.308667e+04     17221.991194             0.000000
90%       31277.657346   9.252935e+04     31277.657346             0.804196
95%       44366.155972   1.301457e+05     44366.155972             1.000000
max      404412.652675   1.114664e+06    404412.652675             1.000000

Users who experienced at least one deficit:
2118 out of 10000

Users who remained surplus in every simulated month:
7882 out of 10000

===== Cash Flow Validation Complete =====

In [134]:
# 13.17. Build Monthly Savings Evolution
#
# Savings balance evolves from:
#
# Previous savings + monthly dynamic cash flow
#
# Investment portfolio is kept separate for now.

# ---------------------------------------------------------
# 1. Prepare initial savings
# ---------------------------------------------------------

monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

# ---------------------------------------------------------
# 2. Calculate cumulative cash-flow change
# ---------------------------------------------------------

monthly_financial_simulation["cumulative_cash_flow"] = (
    monthly_financial_simulation
    .groupby("user_id")["monthly_surplus_dynamic"]
    .cumsum()
)

# ---------------------------------------------------------
# 3. Calculate savings balance
# ---------------------------------------------------------

monthly_financial_simulation["savings_balance"] = (
    monthly_financial_simulation["initial_savings"]
    + monthly_financial_simulation["cumulative_cash_flow"]
)

# ---------------------------------------------------------
# 4. Check whether savings became negative
# ---------------------------------------------------------

monthly_financial_simulation["savings_balance_status"] = np.where(
    monthly_financial_simulation["savings_balance"] >= 0,
    "positive",
    "depleted"
)

# ---------------------------------------------------------
# 5. Basic validation
# ---------------------------------------------------------

print("===== Monthly Savings Evolution =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing savings values:")

display(
    monthly_financial_simulation[
        [
            "cumulative_cash_flow",
            "savings_balance",
            "savings_balance_status"
        ]
    ].isna().sum().to_frame("missing_values")
)

# ---------------------------------------------------------
# 6. Savings statistics
# ---------------------------------------------------------

print("\nSavings balance statistics:")

display(
    monthly_financial_simulation[
        "savings_balance"
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    ).to_frame("savings_balance")
)

# ---------------------------------------------------------
# 7. Depleted savings observations
# ---------------------------------------------------------

print("\nSavings balance status:")

display(
    monthly_financial_simulation[
        "savings_balance_status"
    ].value_counts()
    .to_frame("observations")
)

# ---------------------------------------------------------
# 8. User-level savings summary
# ---------------------------------------------------------

savings_validation = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        initial_savings=("initial_savings", "first"),
        final_savings=("savings_balance", "last"),
        minimum_savings=("savings_balance", "min"),
        maximum_savings=("savings_balance", "max")
    )
    .reset_index()
)

savings_validation["savings_change"] = (
    savings_validation["final_savings"]
    - savings_validation["initial_savings"]
)

savings_validation["ever_depleted"] = (
    savings_validation["minimum_savings"] < 0
)

print("\nUser-level savings validation:")

display(
    savings_validation[
        [
            "initial_savings",
            "final_savings",
            "minimum_savings",
            "maximum_savings",
            "savings_change"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

print("\nUsers whose savings became negative at least once:")

print(
    savings_validation["ever_depleted"].sum(),
    "out of",
    len(savings_validation)
)

# ---------------------------------------------------------
# 9. Sample user
# ---------------------------------------------------------

print("\nSample user savings evolution:")

display(
    monthly_financial_simulation[
        monthly_financial_simulation["user_id"] == "USER_00001"
    ][
        [
            "period",
            "initial_savings",
            "monthly_surplus_dynamic",
            "cumulative_cash_flow",
            "savings_balance"
        ]
    ]
    .head(12)
)

print("\n===== Monthly Savings Evolution Complete =====")

===== Monthly Savings Evolution =====

Simulation shape:
(1430000, 42)

Missing savings values:

                        missing_values
cumulative_cash_flow                 0
savings_balance                      0
savings_balance_status               0

Savings balance statistics:

       savings_balance
count     1.430000e+06
mean      1.537519e+06
std       2.849463e+06
min      -2.596801e+07
10%      -1.104723e+05
25%       1.712770e+05
50%       7.126089e+05
75%       1.940703e+06
90%       4.032432e+06
95%       6.025795e+06
max       1.052729e+08

Savings balance status:

                        observations
savings_balance_status
positive                     1227634
depleted                      202366

User-level savings validation:

,initial_savings,final_savings,minimum_savings,maximum_savings,savings_change
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04
mean,1.667948e+05,3.577562e+06,3.510055e+04,3.710318e+06,3.410767e+06
std,2.175347e+05,5.126315e+06,6.864705e+05,4.992844e+06,4.943350e+06
min,7.776881e+00,-2.596801e+07,-2.596801e+07,-2.672695e+04,-2.623592e+07
10%,2.463442e+04,-2.038133e+05,-2.707017e+05,6.430996e+04,-2.531067e+05
25%,4.960833e+04,8.055944e+05,3.637084e+04,8.055944e+05,7.464637e+05
50%,1.042297e+05,2.346685e+06,1.039422e+05,2.346685e+06,2.244242e+06
75%,2.029707e+05,4.794795e+06,2.137716e+05,4.794795e+06,4.581755e+06
90%,3.621169e+05,8.415756e+06,3.860432e+05,8.415756e+06,8.067221e+06
95%,5.146845e+05,1.189619e+07,5.431705e+05,1.189619e+07,1.143608e+07
max,4.946443e+06,1.052729e+08,5.350855e+06,1.052729e+08,1.003265e+08

Users whose savings became negative at least once:
1631 out of 10000

Sample user savings evolution:

,period,initial_savings,monthly_surplus_dynamic,cumulative_cash_flow,savings_balance
0,2015-02-01,178733.65247,14591.722421,14591.722421,193325.374891
1,2015-03-01,178733.65247,14657.685348,29249.407769,207983.060239
2,2015-04-01,178733.65247,14776.448377,44025.856146,222759.508616
3,2015-05-01,178733.65247,14890.182075,58916.038221,237649.690691
4,2015-06-01,178733.65247,15003.685684,73919.723905,252653.376375
5,2015-07-01,178733.65247,15118.054498,89037.778403,267771.430874
6,2015-08-01,178733.65247,15215.620069,104253.398472,282987.050942
7,2015-09-01,178733.65247,15331.604398,119585.002870,298318.655341
8,2015-10-01,178733.65247,15451.039944,135036.042814,313769.695285
9,2015-11-01,178733.65247,15520.887478,150556.930292,329290.582762
10,2015-12-01,178733.65247,15639.198774,166196.129066,344929.781536
11,2016-01-01,178733.65247,15758.411923,181954.540989,360688.193459

===== Monthly Savings Evolution Complete =====

In [135]:
# 13.18. Handle Savings Depletion and Unfunded Deficits
#
# Savings cannot become negative.
# Any deficit beyond available savings is tracked separately.

# ---------------------------------------------------------
# 1. Sort simulation chronologically
# ---------------------------------------------------------

monthly_financial_simulation = (
    monthly_financial_simulation
    .sort_values(["user_id", "period"])
    .reset_index(drop=True)
)

# ---------------------------------------------------------
# 2. Calculate pre-savings balance
# ---------------------------------------------------------

monthly_financial_simulation["pre_savings_balance"] = (
    monthly_financial_simulation["initial_savings"]
    + monthly_financial_simulation["cumulative_cash_flow"]
)

# ---------------------------------------------------------
# 3. Actual available savings balance
# ---------------------------------------------------------

monthly_financial_simulation["savings_balance"] = (
    monthly_financial_simulation["pre_savings_balance"]
    .clip(lower=0)
)

# ---------------------------------------------------------
# 4. Track unfunded deficit
# ---------------------------------------------------------

monthly_financial_simulation["unfunded_deficit"] = (
    -monthly_financial_simulation["pre_savings_balance"]
).clip(lower=0)

# ---------------------------------------------------------
# 5. Savings status
# ---------------------------------------------------------

monthly_financial_simulation["savings_balance_status"] = np.where(
    monthly_financial_simulation["savings_balance"] > 0,
    "positive",
    "depleted"
)

# ---------------------------------------------------------
# 6. Validate savings balance
# ---------------------------------------------------------

print("===== Savings Depletion Handling =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing values:")

display(
    monthly_financial_simulation[
        [
            "pre_savings_balance",
            "savings_balance",
            "unfunded_deficit",
            "savings_balance_status"
        ]
    ].isna().sum().to_frame("missing_values")
)

# ---------------------------------------------------------
# 7. Savings statistics
# ---------------------------------------------------------

print("\nCorrected savings balance statistics:")

display(
    monthly_financial_simulation[
        "savings_balance"
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    ).to_frame("savings_balance")
)

# ---------------------------------------------------------
# 8. Unfunded deficit statistics
# ---------------------------------------------------------

print("\nUnfunded deficit statistics:")

display(
    monthly_financial_simulation[
        "unfunded_deficit"
    ].describe(
        percentiles=[
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    ).to_frame("unfunded_deficit")
)

# ---------------------------------------------------------
# 9. Count depleted observations
# ---------------------------------------------------------

print("\nSavings balance status:")

display(
    monthly_financial_simulation[
        "savings_balance_status"
    ].value_counts()
    .to_frame("observations")
)

# ---------------------------------------------------------
# 10. User-level validation
# ---------------------------------------------------------

savings_depletion_validation = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        initial_savings=("initial_savings", "first"),
        final_savings=("savings_balance", "last"),
        minimum_savings=("savings_balance", "min"),
        maximum_savings=("savings_balance", "max"),
        maximum_unfunded_deficit=("unfunded_deficit", "max"),
        total_unfunded_deficit=("unfunded_deficit", "sum")
    )
    .reset_index()
)

savings_depletion_validation["ever_depleted"] = (
    savings_depletion_validation["minimum_savings"] == 0
)

print("\nUser-level savings validation:")

display(
    savings_depletion_validation[
        [
            "initial_savings",
            "final_savings",
            "minimum_savings",
            "maximum_savings",
            "maximum_unfunded_deficit",
            "total_unfunded_deficit"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

print("\nUsers whose savings were depleted at least once:")

print(
    savings_depletion_validation["ever_depleted"].sum(),
    "out of",
    len(savings_depletion_validation)
)

print("\nUsers with at least one unfunded deficit:")

print(
    (
        savings_depletion_validation["maximum_unfunded_deficit"] > 0
    ).sum(),
    "out of",
    len(savings_depletion_validation)
)

# ---------------------------------------------------------
# 11. Verify savings never becomes negative
# ---------------------------------------------------------

print("\nMinimum savings balance:")
print(
    monthly_financial_simulation["savings_balance"].min()
)

print("\n===== Savings Depletion Handling Complete =====")

===== Savings Depletion Handling =====

Simulation shape:
(1430000, 44)

Missing values:

                        missing_values
pre_savings_balance                  0
savings_balance                      0
unfunded_deficit                     0
savings_balance_status               0

Corrected savings balance statistics:

       savings_balance
count     1.430000e+06
mean      1.606891e+06
std       2.787638e+06
min       0.000000e+00
10%       0.000000e+00
25%       1.712770e+05
50%       7.126089e+05
75%       1.940703e+06
90%       4.032432e+06
95%       6.025795e+06
max       1.052729e+08

Unfunded deficit statistics:

       unfunded_deficit
count      1.430000e+06
mean       6.937227e+04
std        3.543536e+05
min        0.000000e+00
50%        0.000000e+00
75%        0.000000e+00
90%        1.104723e+05
95%        3.938739e+05
99%        1.436058e+06
max        2.596801e+07

Savings balance status:

                        observations
savings_balance_status
positive                     1227634
depleted                      202366

User-level savings validation:

,initial_savings,final_savings,minimum_savings,maximum_savings,maximum_unfunded_deficit,total_unfunded_deficit
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04
mean,1.667948e+05,3.703610e+06,1.682523e+05,3.710366e+06,1.331517e+05,9.920235e+06
std,2.175347e+05,4.997736e+06,2.375290e+05,4.992808e+06,6.082854e+05,4.322844e+07
min,7.776881e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
10%,2.463442e+04,0.000000e+00,0.000000e+00,6.430996e+04,0.000000e+00,0.000000e+00
25%,4.960833e+04,8.055944e+05,3.637084e+04,8.055944e+05,0.000000e+00,0.000000e+00
50%,1.042297e+05,2.346685e+06,1.039422e+05,2.346685e+06,0.000000e+00,0.000000e+00
75%,2.029707e+05,4.794795e+06,2.137716e+05,4.794795e+06,0.000000e+00,0.000000e+00
90%,3.621169e+05,8.415756e+06,3.860432e+05,8.415756e+06,2.707017e+05,2.225324e+07
95%,5.146845e+05,1.189619e+07,5.431705e+05,1.189619e+07,7.927332e+05,6.248997e+07
max,4.946443e+06,1.052729e+08,5.350855e+06,1.052729e+08,2.596801e+07,1.773038e+09

Users whose savings were depleted at least once:
1631 out of 10000

Users with at least one unfunded deficit:
1631 out of 10000

Minimum savings balance:
0.0

===== Savings Depletion Handling Complete =====

In [136]:
# 13.19. Validate Savings Behaviour by Financial Situation

# ---------------------------------------------------------
# 1. User-level savings summary
# ---------------------------------------------------------

savings_by_user = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        financial_situation=("financial_situation", "first"),
        initial_savings=("initial_savings", "first"),
        final_savings=("savings_balance", "last"),
        minimum_savings=("savings_balance", "min"),
        maximum_savings=("savings_balance", "max"),
        maximum_unfunded_deficit=("unfunded_deficit", "max"),
        total_unfunded_deficit=("unfunded_deficit", "sum"),
        depleted_months=(
            "savings_balance_status",
            lambda x: (x == "depleted").sum()
        ),
        total_months=("period", "count")
    )
    .reset_index()
)

# ---------------------------------------------------------
# 2. Depletion ratio
# ---------------------------------------------------------

savings_by_user["depleted_month_ratio"] = (
    savings_by_user["depleted_months"]
    / savings_by_user["total_months"]
)

# ---------------------------------------------------------
# 3. Ever depleted indicator
# ---------------------------------------------------------

savings_by_user["ever_depleted"] = (
    savings_by_user["depleted_months"] > 0
)

# ---------------------------------------------------------
# 4. Always positive savings indicator
# ---------------------------------------------------------

savings_by_user["always_positive"] = (
    savings_by_user["depleted_months"] == 0
)

# ---------------------------------------------------------
# 5. Summary by financial situation
# ---------------------------------------------------------

situation_savings_summary = (
    savings_by_user
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        median_initial_savings=("initial_savings", "median"),
        median_final_savings=("final_savings", "median"),
        median_minimum_savings=("minimum_savings", "median"),
        median_depleted_month_ratio=("depleted_month_ratio", "median"),
        mean_depleted_month_ratio=("depleted_month_ratio", "mean"),
        users_ever_depleted=("ever_depleted", "sum"),
        users_always_positive=("always_positive", "sum"),
        median_max_unfunded_deficit=(
            "maximum_unfunded_deficit",
            "median"
        )
    )
    .reset_index()
)

print("===== Savings Validation by Financial Situation =====")

print("\nUser-level savings summary:")
display(savings_by_user.head(10))

print("\nSavings behaviour by financial situation:")
display(situation_savings_summary)

# ---------------------------------------------------------
# 6. Overall user-level statistics
# ---------------------------------------------------------

print("\nOverall user-level savings statistics:")

display(
    savings_by_user[
        [
            "initial_savings",
            "final_savings",
            "minimum_savings",
            "maximum_savings",
            "depleted_month_ratio",
            "maximum_unfunded_deficit"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

# ---------------------------------------------------------
# 7. Overall depletion statistics
# ---------------------------------------------------------

print("\nUsers whose savings were depleted at least once:")

print(
    savings_by_user["ever_depleted"].sum(),
    "out of",
    len(savings_by_user)
)

print("\nUsers who never depleted their savings:")

print(
    savings_by_user["always_positive"].sum(),
    "out of",
    len(savings_by_user)
)

print("\nAverage depleted-month ratio:")

print(
    savings_by_user["depleted_month_ratio"].mean()
)

print("\n===== Savings Validation Complete =====")

===== Savings Validation by Financial Situation =====

User-level savings summary:

,user_id,financial_situation,initial_savings,final_savings,minimum_savings,maximum_savings,maximum_unfunded_deficit,total_unfunded_deficit,depleted_months,total_months,depleted_month_ratio,ever_depleted,always_positive
0,USER_00001,moderate_saving,178733.652470,3.798640e+06,193325.374891,3.798640e+06,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
1,USER_00002,financial_stress,13659.350863,0.000000e+00,0.000000,7.521293e+02,1.946909e+06,1.359735e+08,142,143,0.993007,True,False
2,USER_00003,low_saving,85318.549015,7.021328e+05,87804.906862,7.021328e+05,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
3,USER_00004,moderate_saving,107702.527041,1.123526e+06,108810.001466,1.123526e+06,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
4,USER_00005,high_saving,205810.045973,1.038436e+07,246839.445557,1.038436e+07,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
5,USER_00006,high_saving,229003.169045,5.752488e+06,251268.154178,5.752488e+06,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
6,USER_00007,high_saving,126015.560330,6.872314e+06,153209.667125,6.872314e+06,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
7,USER_00008,low_saving,26481.524416,1.519781e+06,0.000000,1.519781e+06,4.101197e+04,1.163169e+06,43,143,0.300699,True,False
8,USER_00009,moderate_saving,165575.931991,6.985983e+06,193068.767457,6.985983e+06,0.000000e+00,0.000000e+00,0,143,0.000000,False,True
9,USER_00010,low_saving,76879.539877,1.338531e+06,81965.214295,1.338531e+06,0.000000e+00,0.000000e+00,0,143,0.000000,False,True

Savings behaviour by financial situation:

,financial_situation,users,median_initial_savings,median_final_savings,median_minimum_savings,median_depleted_month_ratio,mean_depleted_month_ratio,users_ever_depleted,users_always_positive,median_max_unfunded_deficit
0,financial_stress,474,25115.005270,0.000000e+00,0.000000,0.979021,0.827048,413,61,1.072627e+06
1,high_saving,2043,255991.483135,6.416404e+06,283878.695616,0.000000,0.000000,0,2043,0.000000e+00
2,low_saving,2923,52257.372560,5.516714e+05,20671.683092,0.000000,0.349571,1212,1711,0.000000e+00
3,moderate_saving,4560,118085.160533,2.871893e+06,127283.153319,0.000000,0.000291,6,4554,0.000000e+00

Overall user-level savings statistics:

,initial_savings,final_savings,minimum_savings,maximum_savings,depleted_month_ratio,maximum_unfunded_deficit
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,1.000000e+04
mean,1.667948e+05,3.703610e+06,1.682523e+05,3.710366e+06,0.141515,1.331517e+05
std,2.175347e+05,4.997736e+06,2.375290e+05,4.992808e+06,0.328689,6.082854e+05
min,7.776881e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
10%,2.463442e+04,0.000000e+00,0.000000e+00,6.430996e+04,0.000000,0.000000e+00
25%,4.960833e+04,8.055944e+05,3.637084e+04,8.055944e+05,0.000000,0.000000e+00
50%,1.042297e+05,2.346685e+06,1.039422e+05,2.346685e+06,0.000000,0.000000e+00
75%,2.029707e+05,4.794795e+06,2.137716e+05,4.794795e+06,0.000000,0.000000e+00
90%,3.621169e+05,8.415756e+06,3.860432e+05,8.415756e+06,0.916084,2.707017e+05
95%,5.146845e+05,1.189619e+07,5.431705e+05,1.189619e+07,0.972028,7.927332e+05
max,4.946443e+06,1.052729e+08,5.350855e+06,1.052729e+08,1.000000,2.596801e+07

Users whose savings were depleted at least once:
1631 out of 10000

Users who never depleted their savings:
8369 out of 10000

Average depleted-month ratio:
0.1415146853146853

===== Savings Validation Complete =====

In [137]:
# 13.20. Integrate Investment Portfolio Wealth
#
# Total financial wealth:
#
# Savings balance + Portfolio value
#
# Goals are intentionally NOT included as wealth.

# ---------------------------------------------------------
# 1. Verify portfolio value exists
# ---------------------------------------------------------

required_columns = [
    "portfolio_value",
    "portfolio_return",
    "initial_investment"
]

missing_columns = [
    col for col in required_columns
    if col not in monthly_financial_simulation.columns
]

print("Missing portfolio columns:", missing_columns)

# ---------------------------------------------------------
# 2. Calculate total financial wealth
# ---------------------------------------------------------

monthly_financial_simulation["total_financial_wealth"] = (
    monthly_financial_simulation["savings_balance"]
    + monthly_financial_simulation["portfolio_value"]
)

# ---------------------------------------------------------
# 3. Calculate portfolio share of wealth
# ---------------------------------------------------------

monthly_financial_simulation["portfolio_wealth_ratio"] = np.where(
    monthly_financial_simulation["total_financial_wealth"] > 0,
    monthly_financial_simulation["portfolio_value"]
    / monthly_financial_simulation["total_financial_wealth"],
    0
)

# ---------------------------------------------------------
# 4. Validate wealth values
# ---------------------------------------------------------

print("\n===== Investment Wealth Integration =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing wealth values:")

display(
    monthly_financial_simulation[
        [
            "total_financial_wealth",
            "portfolio_wealth_ratio"
        ]
    ].isna().sum().to_frame("missing_values")
)

# ---------------------------------------------------------
# 5. Wealth statistics
# ---------------------------------------------------------

print("\nTotal financial wealth statistics:")

display(
    monthly_financial_simulation[
        "total_financial_wealth"
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    ).to_frame("total_financial_wealth")
)

# ---------------------------------------------------------
# 6. Portfolio ratio statistics
# ---------------------------------------------------------

print("\nPortfolio share of total financial wealth:")

display(
    monthly_financial_simulation[
        "portfolio_wealth_ratio"
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    ).to_frame("portfolio_wealth_ratio")
)

# ---------------------------------------------------------
# 7. Check for invalid negative wealth
# ---------------------------------------------------------

print("\nNegative total financial wealth observations:")

print(
    (
        monthly_financial_simulation["total_financial_wealth"] < 0
    ).sum()
)

# ---------------------------------------------------------
# 8. Check portfolio ratio boundaries
# ---------------------------------------------------------

print("\nPortfolio ratio outside [0, 1]:")

print(
    (
        (monthly_financial_simulation["portfolio_wealth_ratio"] < 0)
        |
        (monthly_financial_simulation["portfolio_wealth_ratio"] > 1)
    ).sum()
)

# ---------------------------------------------------------
# 9. Sample user
# ---------------------------------------------------------

print("\nSample user wealth evolution:")

display(
    monthly_financial_simulation[
        monthly_financial_simulation["user_id"] == "USER_00001"
    ][
        [
            "period",
            "savings_balance",
            "portfolio_value",
            "total_financial_wealth",
            "portfolio_wealth_ratio"
        ]
    ]
    .head(12)
)

print("\n===== Investment Wealth Integration Complete =====")

Missing portfolio columns: []

===== Investment Wealth Integration =====

Simulation shape:
(1430000, 46)

Missing wealth values:

                        missing_values
total_financial_wealth               0
portfolio_wealth_ratio               0

Total financial wealth statistics:

       total_financial_wealth
count            1.430000e+06
mean             1.690628e+06
std              2.929987e+06
min              0.000000e+00
10%              0.000000e+00
25%              1.847024e+05
50%              7.557139e+05
75%              2.036040e+06
90%              4.233154e+06
95%              6.325997e+06
max              1.143948e+08

Portfolio share of total financial wealth:

       portfolio_wealth_ratio
count            1.430000e+06
mean             8.001034e-02
std              1.857089e-01
min              0.000000e+00
10%              0.000000e+00
25%              0.000000e+00
50%              2.193819e-02
75%              7.919744e-02
90%              1.664506e-01
95%              2.805258e-01
max              1.000000e+00

Negative total financial wealth observations:
0

Portfolio ratio outside [0, 1]:
0

Sample user wealth evolution:

,period,savings_balance,portfolio_value,total_financial_wealth,portfolio_wealth_ratio
0,2015-02-01,193325.374891,45909.359714,239234.734605,0.191901
1,2015-03-01,207983.060239,44605.295682,252588.355921,0.176593
2,2015-04-01,222759.508616,43450.108617,266209.617233,0.163218
3,2015-05-01,237649.690691,44401.549173,282051.239865,0.157424
4,2015-06-01,252653.376375,44157.844623,296811.220998,0.148774
5,2015-07-01,267771.430874,44774.003918,312545.434791,0.143256
6,2015-08-01,282987.050942,42680.449741,325667.500684,0.131055
7,2015-09-01,298318.655341,42595.235915,340913.891256,0.124944
8,2015-10-01,313769.695285,43040.309924,356810.005209,0.120625
9,2015-11-01,329290.582762,42545.352023,371835.934785,0.114420
10,2015-12-01,344929.781536,42587.636640,387517.418176,0.109899
11,2016-01-01,360688.193459,41129.990226,401818.183685,0.102360

===== Investment Wealth Integration Complete =====

In [138]:
# 13.21. Validate Wealth Evolution by Risk Profile

# ---------------------------------------------------------
# 1. User-level wealth summary
# ---------------------------------------------------------

wealth_by_user = (
    monthly_financial_simulation
    .groupby("user_id")
    .agg(
        risk_profile=("risk_profile", "first"),
        risk_score=("risk_score", "first"),
        initial_investment=("initial_investment", "first"),
        initial_savings=("initial_savings", "first"),
        initial_wealth=("total_financial_wealth", "first"),
        final_wealth=("total_financial_wealth", "last"),
        minimum_wealth=("total_financial_wealth", "min"),
        maximum_wealth=("total_financial_wealth", "max"),
        final_portfolio_value=("portfolio_value", "last"),
        final_savings=("savings_balance", "last")
    )
    .reset_index()
)

# ---------------------------------------------------------
# 2. Wealth change
# ---------------------------------------------------------

wealth_by_user["wealth_change"] = (
    wealth_by_user["final_wealth"]
    - wealth_by_user["initial_wealth"]
)

wealth_by_user["wealth_growth_factor"] = np.where(
    wealth_by_user["initial_wealth"] > 0,
    wealth_by_user["final_wealth"]
    / wealth_by_user["initial_wealth"],
    np.nan
)

# ---------------------------------------------------------
# 3. Portfolio contribution to final wealth
# ---------------------------------------------------------

wealth_by_user["final_portfolio_share"] = np.where(
    wealth_by_user["final_wealth"] > 0,
    wealth_by_user["final_portfolio_value"]
    / wealth_by_user["final_wealth"],
    0
)

# ---------------------------------------------------------
# 4. Summary by risk profile
# ---------------------------------------------------------

risk_wealth_summary = (
    wealth_by_user
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        median_risk_score=("risk_score", "median"),
        median_initial_wealth=("initial_wealth", "median"),
        median_final_wealth=("final_wealth", "median"),
        median_wealth_change=("wealth_change", "median"),
        mean_wealth_growth_factor=("wealth_growth_factor", "mean"),
        median_wealth_growth_factor=("wealth_growth_factor", "median"),
        median_final_portfolio_value=(
            "final_portfolio_value",
            "median"
        ),
        median_final_savings=("final_savings", "median"),
        median_final_portfolio_share=(
            "final_portfolio_share",
            "median"
        )
    )
    .reset_index()
)

print("===== Wealth Validation by Risk Profile =====")

print("\nUser-level wealth summary:")
display(wealth_by_user.head(10))

print("\nWealth behaviour by risk profile:")
display(risk_wealth_summary)

# ---------------------------------------------------------
# 5. Overall wealth statistics
# ---------------------------------------------------------

print("\nOverall user-level wealth statistics:")

display(
    wealth_by_user[
        [
            "initial_wealth",
            "final_wealth",
            "wealth_change",
            "wealth_growth_factor",
            "final_portfolio_share"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

# ---------------------------------------------------------
# 6. Validate risk-score ordering
# ---------------------------------------------------------

print("\nMedian risk score by profile:")

display(
    wealth_by_user
    .groupby("risk_profile")["risk_score"]
    .median()
    .sort_values()
    .to_frame("median_risk_score")
)

print("\nMedian final portfolio share by profile:")

display(
    wealth_by_user
    .groupby("risk_profile")["final_portfolio_share"]
    .median()
    .sort_values()
    .to_frame("median_final_portfolio_share")
)

print("\n===== Wealth Validation Complete =====")

===== Wealth Validation by Risk Profile =====

User-level wealth summary:

,user_id,risk_profile,risk_score,initial_investment,initial_savings,initial_wealth,final_wealth,minimum_wealth,maximum_wealth,final_portfolio_value,final_savings,wealth_change,wealth_growth_factor,final_portfolio_share
0,USER_00001,aggressive,0.710500,45777.548120,178733.652470,239234.734605,3.893939e+06,239234.734605,3.893939e+06,95298.759053,3.798640e+06,3.654704e+06,16.276645,0.024474
1,USER_00002,conservative,0.038363,0.000000,13659.350863,752.129297,0.000000e+00,0.000000,7.521293e+02,0.000000,0.000000e+00,-7.521293e+02,0.000000,0.000000
2,USER_00003,moderate,0.505350,0.000000,85318.549015,87804.906862,7.021328e+05,87804.906862,7.021328e+05,0.000000,7.021328e+05,6.143279e+05,7.996510,0.000000
3,USER_00004,conservative,0.313650,60534.274631,107702.527041,169421.221671,1.208823e+06,169421.221671,1.208823e+06,85296.198075,1.123526e+06,1.039401e+06,7.135013,0.070561
4,USER_00005,aggressive,0.750750,105774.934379,205810.045973,352936.201476,1.061282e+07,352936.201476,1.061282e+07,228458.998450,1.038436e+07,1.025988e+07,30.070080,0.021527
5,USER_00006,aggressive,0.823150,118987.882781,229003.169045,370652.971345,6.026725e+06,370652.971345,6.026725e+06,274237.112721,5.752488e+06,5.656072e+06,16.259752,0.045504
6,USER_00007,aggressive,0.762325,90329.680595,126015.560330,243818.414178,7.069472e+06,243818.414178,7.069472e+06,197157.391015,6.872314e+06,6.825653e+06,28.994823,0.027889
7,USER_00008,conservative,0.087587,0.000000,26481.524416,22002.154289,1.519781e+06,0.000000,1.519781e+06,0.000000,1.519781e+06,1.497778e+06,69.074170,0.000000
8,USER_00009,aggressive,0.688500,0.000000,165575.931991,193068.767457,6.985983e+06,193068.767457,6.985983e+06,0.000000,6.985983e+06,6.792915e+06,36.183912,0.000000
9,USER_00010,moderate,0.533300,15171.499059,76879.539877,97169.503027,1.365225e+06,97169.503027,1.365225e+06,26694.224964,1.338531e+06,1.268056e+06,14.049933,0.019553

Wealth behaviour by risk profile:

,risk_profile,users,median_risk_score,median_initial_wealth,median_final_wealth,median_wealth_change,mean_wealth_growth_factor,median_wealth_growth_factor,median_final_portfolio_value,median_final_savings,median_final_portfolio_share
0,aggressive,3333,0.728550,278710.747854,4.940566e+06,4.628062e+06,19.077052,16.937328,151020.010414,4.755586e+06,0.034425
1,conservative,3333,0.216587,73588.213742,4.632599e+05,3.982331e+05,10.126486,6.351933,0.000000,4.590599e+05,0.000000
2,moderate,3334,0.540337,97063.276312,2.270425e+06,2.159831e+06,25.756051,20.565317,3611.064253,2.237351e+06,0.003787

Overall user-level wealth statistics:

,initial_wealth,final_wealth,wealth_change,wealth_growth_factor,final_portfolio_share
count,1.000000e+04,1.000000e+04,1.000000e+04,9944.000000,10000.000000
mean,2.355158e+05,3.819514e+06,3.583998e+06,18.366752,0.049856
std,3.398067e+05,5.196515e+06,4.897259e+06,14.689268,0.166929
min,0.000000e+00,0.000000e+00,-5.709712e+05,0.000000,0.000000
10%,2.567170e+04,3.501316e+02,-1.433661e+04,0.172990,0.000000
25%,5.842354e+04,8.178118e+05,7.520191e+05,9.790195,0.000000
50%,1.318028e+05,2.407304e+06,2.261963e+06,15.557080,0.011903
75%,2.826437e+05,4.924234e+06,4.636250e+06,24.120982,0.039663
90%,5.431411e+05,8.699641e+06,8.224047e+06,36.792329,0.064327
95%,7.637677e+05,1.220594e+07,1.157152e+07,46.585389,0.087744
max,9.244393e+06,1.143948e+08,1.051505e+08,114.597937,1.000000

Median risk score by profile:

              median_risk_score
risk_profile
conservative           0.216587
moderate               0.540337
aggressive             0.728550

Median final portfolio share by profile:

              median_final_portfolio_share
risk_profile
conservative                      0.000000
moderate                          0.003787
aggressive                        0.034425

===== Wealth Validation Complete =====

In [139]:
# 13.22. Save Complete Monthly Financial Simulation

simulation_output_path = (
    "/content/drive/MyDrive/GoalPilot_AI/simulation/"
    "05_simulation_runs/monthly_financial_simulation_base.csv"
)

monthly_financial_simulation.to_csv(
    simulation_output_path,
    index=False
)

print("===== Monthly Financial Simulation Saved =====")
print(f"File: {simulation_output_path}")
print(f"Shape: {monthly_financial_simulation.shape}")
print(f"File saved successfully: {os.path.exists(simulation_output_path)}")
print("===== Save Complete =====")

===== Monthly Financial Simulation Saved =====
File: /content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/monthly_financial_simulation_base.csv
Shape: (1430000, 46)
File saved successfully: True
===== Save Complete =====

In [141]:
# 13.23A. Inspect Available Goal Data

print("Synthetic goals shape:", synthetic_goals.shape)

print("\nSynthetic goals columns:")
print(synthetic_goals.columns.tolist())

print("\nSynthetic goals sample:")
display(synthetic_goals.head(10))

print("\nData types:")
display(synthetic_goals.dtypes)

print("\nMissing values:")
display(synthetic_goals.isna().sum())

print("\n===== Goal Data Inspection Complete =====")

Synthetic goals shape: (10000, 4)

Synthetic goals columns:
['goal_id', 'user_id', 'goal_name', 'goal_type']

Synthetic goals sample:

      goal_id     user_id                goal_name goal_type
0  GOAL_00001  USER_00001  Personal Financial Goal    custom
1  GOAL_00002  USER_00002  Personal Financial Goal    custom
2  GOAL_00003  USER_00003  Personal Financial Goal    custom
3  GOAL_00004  USER_00004  Personal Financial Goal    custom
4  GOAL_00005  USER_00005  Personal Financial Goal    custom
5  GOAL_00006  USER_00006  Personal Financial Goal    custom
6  GOAL_00007  USER_00007  Personal Financial Goal    custom
7  GOAL_00008  USER_00008  Personal Financial Goal    custom
8  GOAL_00009  USER_00009  Personal Financial Goal    custom
9  GOAL_00010  USER_00010  Personal Financial Goal    custom

Data types:

goal_id      object
user_id      object
goal_name    object
goal_type    object
dtype: object

Missing values:

goal_id      0
user_id      0
goal_name    0
goal_type    0
dtype: int64

===== Goal Data Inspection Complete =====

In [142]:
# 13.23B. Find DataFrame Containing Detailed Goal Information

print("Checking currently available DataFrames for goal-related columns...\n")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        goal_columns_found = [
            col for col in obj.columns
            if any(
                keyword in col.lower()
                for keyword in [
                    "goal",
                    "target",
                    "horizon",
                    "priority"
                ]
            )
        ]

        if goal_columns_found:
            print(f"DataFrame: {name}")
            print(f"Shape: {obj.shape}")
            print(f"Relevant columns: {goal_columns_found}")
            print("-" * 70)

Checking currently available DataFrames for goal-related columns...

DataFrame: synthetic_users
Shape: (10000, 74)
Relevant columns: ['goal_funding_capacity', 'goal_capacity_percentile', 'goal_horizon_months', 'goal_horizon_type', 'baseline_goal_funding', 'existing_savings_to_goal_ratio', 'goal_difficulty_factor', 'target_amount', 'goal_reference_amount', 'goal_scale_percentile', 'target_to_annual_income_ratio', 'target_to_savings_ratio', 'target_funding_months', 'target_funding_months_percentile', 'goal_allocation_strength', 'goal_allocation_factor', 'goal_specific_monthly_capacity', 'goal_allocation_percentile']
----------------------------------------------------------------------
DataFrame: synthetic_goals
Shape: (10000, 4)
Relevant columns: ['goal_id', 'goal_name', 'goal_type']
----------------------------------------------------------------------
DataFrame: goal_capacity_analysis
Shape: (10000, 7)
Relevant columns: ['goal_funding_capacity']
----------------------------------------------------------------------

AttributeError: 'tuple' object has no attribute 'lower'

In [143]:
# 13.23. Integrate Detailed Goal Information

# Select the goal-related information actually available
goal_detail_columns = [
    "user_id",
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "goal_reference_amount",
    "target_to_annual_income_ratio",
    "target_to_savings_ratio",
    "target_funding_months",
    "target_funding_months_percentile",
    "goal_allocation_strength",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "goal_allocation_percentile"
]

goal_details = synthetic_users[goal_detail_columns].copy()

print("Detailed goal data shape:", goal_details.shape)

# Check that each user appears exactly once
print(
    "\nUsers with exactly one detailed goal record:",
    (goal_details["user_id"].value_counts() == 1).all()
)

# Remove any goal-detail columns if the cell is rerun
columns_to_remove = [
    col for col in goal_detail_columns
    if col != "user_id" and col in monthly_financial_simulation.columns
]

monthly_financial_simulation = monthly_financial_simulation.drop(
    columns=columns_to_remove,
    errors="ignore"
)

# Merge detailed goal information into every monthly record
monthly_financial_simulation = monthly_financial_simulation.merge(
    goal_details,
    on="user_id",
    how="left",
    validate="many_to_one"
)

# Validate integration
goal_validation_columns = [
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "goal_specific_monthly_capacity"
]

print("\nMissing goal-detail values:")
display(
    monthly_financial_simulation[goal_validation_columns]
    .isna()
    .sum()
)

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nUnique users:")
print(monthly_financial_simulation["user_id"].nunique())

print("\nRecords per user:")
display(
    monthly_financial_simulation
    .groupby("user_id")
    .size()
    .value_counts()
    .sort_index()
)

print("\nSample integrated goal information:")
display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "goal_horizon_months",
            "goal_horizon_type",
            "target_amount",
            "goal_reference_amount",
            "goal_specific_monthly_capacity",
            "goal_allocation_percentile"
        ]
    ].head(10)
)

print("\n===== Detailed Goal Integration Complete =====")

Detailed goal data shape: (10000, 13)

Users with exactly one detailed goal record: True

Missing goal-detail values:

goal_horizon_months               0
goal_horizon_type                 0
target_amount                     0
goal_specific_monthly_capacity    0
dtype: int64

Simulation shape:
(1430000, 58)

Unique users:
10000

Records per user:

143    10000
Name: count, dtype: int64

Sample integrated goal information:

,user_id,period,goal_horizon_months,goal_horizon_type,target_amount,goal_reference_amount,goal_specific_monthly_capacity,goal_allocation_percentile
0,USER_00001,2015-02-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
1,USER_00001,2015-03-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
2,USER_00001,2015-04-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
3,USER_00001,2015-05-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
4,USER_00001,2015-06-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
5,USER_00001,2015-07-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
6,USER_00001,2015-08-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
7,USER_00001,2015-09-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
8,USER_00001,2015-10-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977
9,USER_00001,2015-11-01,48,medium_term,115357.183592,616236.724135,10103.627663,0.6977

===== Detailed Goal Integration Complete =====

In [144]:
# 13.24. Calculate Monthly Goal Funding Capacity

# Goal-specific monthly amount available for the goal
monthly_financial_simulation["goal_monthly_contribution"] = (
    monthly_financial_simulation["goal_specific_monthly_capacity"]
)

# Cumulative contributions toward the goal
monthly_financial_simulation["cumulative_goal_contribution"] = (
    monthly_financial_simulation
    .groupby("user_id")["goal_monthly_contribution"]
    .cumsum()
)

# Goal funding progress relative to target
monthly_financial_simulation["goal_funding_progress"] = np.where(
    monthly_financial_simulation["target_amount"] > 0,
    monthly_financial_simulation["cumulative_goal_contribution"]
    / monthly_financial_simulation["target_amount"],
    0
)

# Cap progress at 100% for interpretation
monthly_financial_simulation["goal_funding_progress_capped"] = (
    monthly_financial_simulation["goal_funding_progress"].clip(upper=1)
)

# Remaining amount required to reach the target
monthly_financial_simulation["goal_remaining_amount"] = (
    monthly_financial_simulation["target_amount"]
    - monthly_financial_simulation["cumulative_goal_contribution"]
).clip(lower=0)

print("===== Goal Funding Progress =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing values:")
display(
    monthly_financial_simulation[
        [
            "goal_monthly_contribution",
            "cumulative_goal_contribution",
            "goal_funding_progress",
            "goal_funding_progress_capped",
            "goal_remaining_amount"
        ]
    ].isna().sum()
)

print("\nOverall goal funding statistics:")
display(
    monthly_financial_simulation[
        [
            "goal_monthly_contribution",
            "cumulative_goal_contribution",
            "goal_funding_progress_capped",
            "goal_remaining_amount"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

print("\nSample goal progression:")
display(
    monthly_financial_simulation[
        [
            "user_id",
            "period",
            "target_amount",
            "goal_monthly_contribution",
            "cumulative_goal_contribution",
            "goal_funding_progress_capped",
            "goal_remaining_amount"
        ]
    ].head(12)
)

print("\n===== Goal Funding Calculation Complete =====")

===== Goal Funding Progress =====

Simulation shape:
(1430000, 63)

Missing values:

goal_monthly_contribution       0
cumulative_goal_contribution    0
goal_funding_progress           0
goal_funding_progress_capped    0
goal_remaining_amount           0
dtype: int64

Overall goal funding statistics:

,goal_monthly_contribution,cumulative_goal_contribution,goal_funding_progress_capped,goal_remaining_amount
count,1.430000e+06,1.430000e+06,1.430000e+06,1.430000e+06
mean,1.040807e+04,7.493810e+05,6.804863e-01,3.657699e+04
std,1.857717e+04,1.600537e+06,4.331567e-01,7.213802e+04
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
10%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.046800e+02,9.948972e+03,1.282396e-01,0.000000e+00
50%,3.802625e+03,1.862379e+05,1.000000e+00,0.000000e+00
75%,1.280174e+04,7.989254e+05,1.000000e+00,5.678126e+04
90%,2.792413e+04,2.047823e+06,1.000000e+00,1.112085e+05
95%,4.178199e+04,3.283354e+06,1.000000e+00,1.542256e+05
max,4.013533e+05,5.739351e+07,1.000000e+00,1.585003e+06

Sample goal progression:

,user_id,period,target_amount,goal_monthly_contribution,cumulative_goal_contribution,goal_funding_progress_capped,goal_remaining_amount
0,USER_00001,2015-02-01,115357.183592,10103.627663,10103.627663,0.087586,105253.555929
1,USER_00001,2015-03-01,115357.183592,10103.627663,20207.255325,0.175171,95149.928267
2,USER_00001,2015-04-01,115357.183592,10103.627663,30310.882988,0.262757,85046.300604
3,USER_00001,2015-05-01,115357.183592,10103.627663,40414.510650,0.350342,74942.672942
4,USER_00001,2015-06-01,115357.183592,10103.627663,50518.138313,0.437928,64839.045279
5,USER_00001,2015-07-01,115357.183592,10103.627663,60621.765975,0.525514,54735.417617
6,USER_00001,2015-08-01,115357.183592,10103.627663,70725.393638,0.613099,44631.789954
7,USER_00001,2015-09-01,115357.183592,10103.627663,80829.021300,0.700685,34528.162292
8,USER_00001,2015-10-01,115357.183592,10103.627663,90932.648963,0.788270,24424.534629
9,USER_00001,2015-11-01,115357.183592,10103.627663,101036.276625,0.875856,14320.906967
10,USER_00001,2015-12-01,115357.183592,10103.627663,111139.904288,0.963442,4217.279304
11,USER_00001,2016-01-01,115357.183592,10103.627663,121243.531950,1.000000,0.000000

===== Goal Funding Calculation Complete =====

In [145]:
# 13.25. Calculate Goal Deadline and On-Time Progress

# Number each monthly observation from the beginning of the simulation
monthly_financial_simulation["months_since_start"] = (
    monthly_financial_simulation
    .groupby("user_id")
    .cumcount() + 1
)

# Identify the month corresponding to the user's goal horizon
monthly_financial_simulation["within_goal_horizon"] = (
    monthly_financial_simulation["months_since_start"]
    <= monthly_financial_simulation["goal_horizon_months"]
)

# Funding accumulated by the goal horizon
goal_horizon_funding = (
    monthly_financial_simulation[
        monthly_financial_simulation["within_goal_horizon"]
    ]
    .groupby("user_id")
    .agg(
        goal_horizon_funding=(
            "cumulative_goal_contribution",
            "last"
        ),
        target_amount=("target_amount", "first"),
        goal_horizon_months=("goal_horizon_months", "first")
    )
    .reset_index()
)

# Calculate the amount still required at the deadline
goal_horizon_funding["goal_horizon_shortfall"] = (
    goal_horizon_funding["target_amount"]
    - goal_horizon_funding["goal_horizon_funding"]
).clip(lower=0)

# Funding percentage achieved by the deadline
goal_horizon_funding["goal_horizon_progress"] = np.where(
    goal_horizon_funding["target_amount"] > 0,
    goal_horizon_funding["goal_horizon_funding"]
    / goal_horizon_funding["target_amount"],
    0
)

# Goal achieved within the specified horizon
goal_horizon_funding["goal_achieved_on_time"] = (
    goal_horizon_funding["goal_horizon_funding"]
    >= goal_horizon_funding["target_amount"]
)

# Merge user-level deadline results back into monthly simulation
deadline_columns = [
    "user_id",
    "goal_horizon_funding",
    "goal_horizon_shortfall",
    "goal_horizon_progress",
    "goal_achieved_on_time"
]

monthly_financial_simulation = monthly_financial_simulation.merge(
    goal_horizon_funding[deadline_columns],
    on="user_id",
    how="left",
    validate="many_to_one"
)

print("===== Goal Deadline Analysis =====")

print("\nSimulation shape:")
print(monthly_financial_simulation.shape)

print("\nMissing deadline-analysis values:")
display(
    monthly_financial_simulation[
        [
            "goal_horizon_funding",
            "goal_horizon_shortfall",
            "goal_horizon_progress",
            "goal_achieved_on_time"
        ]
    ].isna().sum()
)

print("\nUser-level goal outcome:")
display(
    goal_horizon_funding[
        [
            "goal_horizon_months",
            "target_amount",
            "goal_horizon_funding",
            "goal_horizon_progress",
            "goal_horizon_shortfall",
            "goal_achieved_on_time"
        ]
    ].describe()
)

print("\nGoal achievement counts:")
print(
    goal_horizon_funding["goal_achieved_on_time"]
    .value_counts()
)

print("\nGoal achievement rate:")
print(
    goal_horizon_funding["goal_achieved_on_time"].mean()
)

print("\nGoal outcome sample:")
display(
    goal_horizon_funding.head(10)
)

print("\n===== Goal Deadline Analysis Complete =====")

===== Goal Deadline Analysis =====

Simulation shape:
(1430000, 69)

Missing deadline-analysis values:

goal_horizon_funding      0
goal_horizon_shortfall    0
goal_horizon_progress     0
goal_achieved_on_time     0
dtype: int64

User-level goal outcome:

,goal_horizon_months,target_amount,goal_horizon_funding,goal_horizon_progress,goal_horizon_shortfall
count,10000.000000,1.000000e+04,1.000000e+04,10000.000000,1.000000e+04
mean,62.697000,1.383538e+05,6.631026e+05,3.660095,3.552495e+04
std,33.431233,1.211024e+05,1.440565e+06,4.572643,7.074162e+04
min,6.000000,2.824526e+03,0.000000e+00,0.000000,0.000000e+00
25%,33.000000,7.189787e+04,1.226529e+04,0.168514,0.000000e+00
50%,63.000000,1.073131e+05,1.726636e+05,1.772006,0.000000e+00
75%,92.000000,1.595261e+05,7.077399e+05,5.586522,5.343402e+04
max,120.000000,1.900464e+06,4.374750e+07,25.384325,1.034294e+06

Goal achievement counts:
goal_achieved_on_time
True     5963
False    4037
Name: count, dtype: int64

Goal achievement rate:
0.5963

Goal outcome sample:

,user_id,goal_horizon_funding,target_amount,goal_horizon_months,goal_horizon_shortfall,goal_horizon_progress,goal_achieved_on_time
0,USER_00001,4.849741e+05,115357.183592,48,0.000000,4.204109,True
1,USER_00002,0.000000e+00,59340.387689,51,59340.387689,0.000000,False
2,USER_00003,3.442674e+04,99893.237726,46,65466.495547,0.344635,False
3,USER_00004,1.532223e+04,75476.307623,60,60154.079188,0.203007,False
4,USER_00005,4.601411e+06,206040.342056,120,0.000000,22.332573,True
5,USER_00006,3.274178e+05,110291.964774,18,0.000000,2.968646,True
6,USER_00007,1.764231e+06,128020.414837,75,0.000000,13.780853,True
7,USER_00008,0.000000e+00,269916.171830,11,269916.171830,0.000000,False
8,USER_00009,1.312933e+06,182600.732773,55,0.000000,7.190187,True
9,USER_00010,4.959178e+04,96702.526658,24,47110.748070,0.512828,False

===== Goal Deadline Analysis Complete =====

In [146]:
# 13.26. Analyze Goal Success and Shortfall

# Create user-level goal outcome dataset
goal_outcomes = (
    goal_horizon_funding
    .merge(
        synthetic_users[
            [
                "user_id",
                "risk_profile",
                "risk_score",
                "financial_situation"
            ]
        ],
        on="user_id",
        how="left",
        validate="one_to_one"
    )
)

# Separate successful and unsuccessful goals
successful_goals = goal_outcomes[
    goal_outcomes["goal_achieved_on_time"]
].copy()

failed_goals = goal_outcomes[
    ~goal_outcomes["goal_achieved_on_time"]
].copy()

print("===== Goal Outcome Analysis =====")

print("\nTotal users:", len(goal_outcomes))
print("Successful goals:", len(successful_goals))
print("Unsuccessful goals:", len(failed_goals))

print(
    "\nOverall goal success rate:",
    goal_outcomes["goal_achieved_on_time"].mean()
)

# Shortfall statistics among unsuccessful goals only
print("\n===== Shortfall Among Unsuccessful Goals =====")

if len(failed_goals) > 0:
    display(
        failed_goals[
            [
                "goal_horizon_months",
                "target_amount",
                "goal_horizon_funding",
                "goal_horizon_progress",
                "goal_horizon_shortfall"
            ]
        ].describe(
            percentiles=[
                0.10,
                0.25,
                0.50,
                0.75,
                0.90,
                0.95
            ]
        )
    )

# Goal success by horizon type
goal_horizon_summary = (
    goal_outcomes
    .assign(
        goal_horizon_type=goal_outcomes["goal_horizon_months"].apply(
            lambda x:
                "short_term" if x <= 36
                else "medium_term" if x <= 72
                else "long_term"
        )
    )
    .groupby("goal_horizon_type")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time", "sum"),
        success_rate=("goal_achieved_on_time", "mean"),
        median_target=("target_amount", "median"),
        median_horizon_funding=("goal_horizon_funding", "median"),
        median_shortfall=("goal_horizon_shortfall", "median")
    )
    .reset_index()
)

print("\n===== Goal Success by Horizon =====")
display(goal_horizon_summary)

# Goal success by risk profile
goal_risk_summary = (
    goal_outcomes
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time", "sum"),
        success_rate=("goal_achieved_on_time", "mean"),
        median_target=("target_amount", "median"),
        median_horizon_funding=("goal_horizon_funding", "median"),
        median_shortfall=("goal_horizon_shortfall", "median")
    )
    .reset_index()
)

print("\n===== Goal Success by Risk Profile =====")
display(goal_risk_summary)

# Overall goal outcome distribution
print("\n===== Goal Progress Distribution =====")

display(
    goal_outcomes[
        [
            "goal_horizon_progress",
            "goal_horizon_shortfall"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

# Check whether every user has a valid outcome
print("\nMissing outcome values:")
display(
    goal_outcomes[
        [
            "goal_horizon_progress",
            "goal_horizon_shortfall",
            "goal_achieved_on_time"
        ]
    ].isna().sum()
)

print("\n===== Goal Outcome Analysis Complete =====")

===== Goal Outcome Analysis =====

Total users: 10000
Successful goals: 5963
Unsuccessful goals: 4037

Overall goal success rate: 0.5963

===== Shortfall Among Unsuccessful Goals =====

,goal_horizon_months,target_amount,goal_horizon_funding,goal_horizon_progress,goal_horizon_shortfall
count,4037.000000,4.037000e+03,4037.000000,4037.000000,4.037000e+03
mean,53.382710,1.127253e+05,24726.861434,0.221087,8.799839e+04
std,34.342362,9.429752e+04,48507.564696,0.306403,8.820083e+04
min,6.000000,4.369779e+03,0.000000,0.000000,6.467811e+01
10%,11.000000,4.251716e+04,0.000000,0.000000,1.823467e+04
25%,22.000000,6.148173e+04,0.000000,0.000000,3.681155e+04
50%,49.000000,8.979766e+04,0.000000,0.000000,6.819891e+04
75%,82.000000,1.307623e+05,32698.555105,0.423901,1.083090e+05
90%,105.000000,1.963237e+05,77151.156811,0.749507,1.661192e+05
95%,114.000000,2.699201e+05,109635.203911,0.866653,2.312034e+05
max,120.000000,1.035134e+06,868830.328781,0.998689,1.034294e+06

===== Goal Success by Horizon =====

,goal_horizon_type,users,successful_users,success_rate,median_target,median_horizon_funding,median_shortfall
0,long_term,4159,2864,0.688627,108145.545245,364935.602677,0.000000
1,medium_term,3081,1924,0.624473,105663.701050,186983.154048,0.000000
2,short_term,2760,1175,0.425725,107416.237015,72726.802052,21891.597955

===== Goal Success by Risk Profile =====

,risk_profile,users,successful_users,success_rate,median_target,median_horizon_funding,median_shortfall
0,aggressive,3333,3181,0.954395,121651.618117,764663.633745,0.000000
1,conservative,3333,418,0.125413,96588.133241,0.000000,72957.949992
2,moderate,3334,2364,0.709058,103938.497527,203445.364300,0.000000

===== Goal Progress Distribution =====

       goal_horizon_progress  goal_horizon_shortfall
count           10000.000000            1.000000e+04
mean                3.660095            3.552495e+04
std                 4.572643            7.074162e+04
min                 0.000000            0.000000e+00
10%                 0.000000            0.000000e+00
25%                 0.168514            0.000000e+00
50%                 1.772006            0.000000e+00
75%                 5.586522            5.343402e+04
90%                10.350493            1.087779e+05
95%                13.353360            1.504219e+05
max                25.384325            1.034294e+06

Missing outcome values:

goal_horizon_progress     0
goal_horizon_shortfall    0
goal_achieved_on_time     0
dtype: int64

===== Goal Outcome Analysis Complete =====

In [147]:
# 13.27. Integrate Goal Contributions with Cash/Savings Balance

# Available monthly surplus after expenses and EMI
monthly_financial_simulation["available_goal_funding"] = (
    monthly_financial_simulation["monthly_surplus_dynamic"]
    .clip(lower=0)
)

# Goal contribution based on the existing population-derived allocation factor
monthly_financial_simulation["intended_goal_contribution"] = (
    monthly_financial_simulation["available_goal_funding"]
    * monthly_financial_simulation["goal_allocation_factor"]
)

# Do not allow goal contribution to exceed the actual available surplus
monthly_financial_simulation["actual_goal_contribution"] = np.minimum(
    monthly_financial_simulation["intended_goal_contribution"],
    monthly_financial_simulation["available_goal_funding"]
)

# Remaining surplus stays as cash/savings
monthly_financial_simulation["remaining_monthly_savings"] = (
    monthly_financial_simulation["available_goal_funding"]
    - monthly_financial_simulation["actual_goal_contribution"]
)

print("===== Goal-Cash Allocation Validation =====")

print("\nSimulation shape:",
      monthly_financial_simulation.shape)

print("\nMissing values:")
print(
    monthly_financial_simulation[
        [
            "available_goal_funding",
            "intended_goal_contribution",
            "actual_goal_contribution",
            "remaining_monthly_savings"
        ]
    ].isna().sum()
)

print("\nNegative values:")
print(
    (monthly_financial_simulation[
        [
            "available_goal_funding",
            "actual_goal_contribution",
            "remaining_monthly_savings"
        ]
    ] < 0).sum()
)

# Verify that goal contribution + remaining savings
# exactly equals available surplus
allocation_difference = (
    monthly_financial_simulation["available_goal_funding"]
    - (
        monthly_financial_simulation["actual_goal_contribution"]
        + monthly_financial_simulation["remaining_monthly_savings"]
    )
).abs()

print("\nMaximum allocation difference:",
      allocation_difference.max())

print("\n===== Allocation Statistics =====")

print(
    monthly_financial_simulation[
        [
            "available_goal_funding",
            "actual_goal_contribution",
            "remaining_monthly_savings"
        ]
    ].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

print("\n===== Goal Contribution Utilisation =====")

goal_utilisation = np.where(
    monthly_financial_simulation["available_goal_funding"] > 0,
    monthly_financial_simulation["actual_goal_contribution"]
    / monthly_financial_simulation["available_goal_funding"],
    0
)

print(
    pd.Series(goal_utilisation).describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

print("\n===== 13.27 Complete =====")

===== Goal-Cash Allocation Validation =====

Simulation shape: (1430000, 73)

Missing values:
available_goal_funding        0
intended_goal_contribution    0
actual_goal_contribution      0
remaining_monthly_savings     0
dtype: int64

Negative values:
available_goal_funding       0
actual_goal_contribution     0
remaining_monthly_savings    0
dtype: int64

Maximum allocation difference: 1.4551915228366852e-11

===== Allocation Statistics =====
       available_goal_funding  actual_goal_contribution  \
count            1.430000e+06              1.430000e+06
mean             2.486346e+04              1.929746e+04
std              3.609988e+04              3.556072e+04
min              0.000000e+00              0.000000e+00
10%              0.000000e+00              0.000000e+00
25%              4.534104e+03              1.082192e+03
50%              1.471881e+04              7.161922e+03
75%              3.159846e+04              2.280590e+04
90%              5.813459e+04              5.057274e+04
95%              8.289771e+04              7.683919e+04
max              1.114664e+06              1.114664e+06

       remaining_monthly_savings
count               1.430000e+06
mean                5.565998e+03
std                 4.774485e+03
min                 0.000000e+00
10%                 0.000000e+00
25%                 2.565995e+03
50%                 5.081952e+03
75%                 7.726681e+03
90%                 1.047826e+04
95%                 1.234805e+04
max                 1.695623e+05

===== Goal Contribution Utilisation =====
count    1.430000e+06
mean     4.851047e-01
std      3.092881e-01
min      0.000000e+00
10%      0.000000e+00
25%      2.500750e-01
50%      5.000500e-01
75%      7.500250e-01
90%      9.000100e-01
95%      9.500050e-01
max      1.000000e+00
dtype: float64

===== 13.27 Complete =====

In [148]:
# 13.28. Recalculate Goal Progress Using Actual Contributions

# Use the financially consistent actual contribution
# instead of the previously modeled goal capacity.
monthly_financial_simulation["goal_monthly_contribution_actual"] = (
    monthly_financial_simulation["actual_goal_contribution"]
)

# Cumulative amount actually allocated toward the goal
monthly_financial_simulation["cumulative_goal_contribution_actual"] = (
    monthly_financial_simulation
    .groupby("user_id")["goal_monthly_contribution_actual"]
    .cumsum()
)

# Uncapped goal progress
monthly_financial_simulation["goal_funding_progress_actual"] = np.where(
    monthly_financial_simulation["target_amount"] > 0,
    monthly_financial_simulation["cumulative_goal_contribution_actual"]
    / monthly_financial_simulation["target_amount"],
    0
)

# Progress capped at 100%
monthly_financial_simulation["goal_funding_progress_actual_capped"] = (
    monthly_financial_simulation["goal_funding_progress_actual"]
    .clip(upper=1)
)

# Remaining goal amount
monthly_financial_simulation["goal_remaining_amount_actual"] = (
    monthly_financial_simulation["target_amount"]
    - monthly_financial_simulation["cumulative_goal_contribution_actual"]
).clip(lower=0)


print("===== Actual Goal Funding Validation =====")

print("\nSimulation shape:",
      monthly_financial_simulation.shape)

print("\nMissing values:")

print(
    monthly_financial_simulation[
        [
            "goal_monthly_contribution_actual",
            "cumulative_goal_contribution_actual",
            "goal_funding_progress_actual",
            "goal_funding_progress_actual_capped",
            "goal_remaining_amount_actual"
        ]
    ].isna().sum()
)

print("\nNegative values:")

print(
    (monthly_financial_simulation[
        [
            "goal_monthly_contribution_actual",
            "cumulative_goal_contribution_actual",
            "goal_funding_progress_actual_capped",
            "goal_remaining_amount_actual"
        ]
    ] < 0).sum()
)


print("\n===== Actual Goal Contribution Statistics =====")

display(
    monthly_financial_simulation[
        [
            "goal_monthly_contribution_actual",
            "cumulative_goal_contribution_actual",
            "goal_funding_progress_actual",
            "goal_remaining_amount_actual"
        ]
    ].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)


print("\n===== Goal Progress Range Validation =====")

print(
    "Progress below 0:",
    (
        monthly_financial_simulation["goal_funding_progress_actual_capped"] < 0
    ).sum()
)

print(
    "Progress above 1:",
    (
        monthly_financial_simulation["goal_funding_progress_actual_capped"] > 1
    ).sum()
)


print("\n===== Sample User: USER_00001 =====")

display(
    monthly_financial_simulation[
        monthly_financial_simulation["user_id"] == "USER_00001"
    ][
        [
            "period",
            "monthly_surplus_dynamic",
            "actual_goal_contribution",
            "remaining_monthly_savings",
            "cumulative_goal_contribution_actual",
            "target_amount",
            "goal_funding_progress_actual_capped",
            "goal_remaining_amount_actual"
        ]
    ].head(12)
)


print("\n===== 13.28 Complete =====")

===== Actual Goal Funding Validation =====

Simulation shape: (1430000, 78)

Missing values:
goal_monthly_contribution_actual       0
cumulative_goal_contribution_actual    0
goal_funding_progress_actual           0
goal_funding_progress_actual_capped    0
goal_remaining_amount_actual           0
dtype: int64

Negative values:
goal_monthly_contribution_actual       0
cumulative_goal_contribution_actual    0
goal_funding_progress_actual_capped    0
goal_remaining_amount_actual           0
dtype: int64

===== Actual Goal Contribution Statistics =====

,goal_monthly_contribution_actual,cumulative_goal_contribution_actual,goal_funding_progress_actual,goal_remaining_amount_actual
count,1.430000e+06,1.430000e+06,1.430000e+06,1.430000e+06
mean,1.929746e+04,1.141134e+06,6.391589e+00,3.113184e+04
std,3.556072e+04,2.548692e+06,8.548319e+00,6.627415e+04
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
10%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.082192e+03,2.599216e+04,3.113713e-01,0.000000e+00
50%,7.161922e+03,2.715823e+05,2.779863e+00,0.000000e+00
75%,2.280590e+04,1.156751e+06,9.177995e+00,4.461266e+04
90%,5.057274e+04,3.080218e+06,1.853689e+01,1.011949e+05
95%,7.683919e+04,5.053340e+06,2.514400e+01,1.409104e+05
max,1.114664e+06,1.003265e+08,5.501597e+01,1.582598e+06

===== Goal Progress Range Validation =====
Progress below 0: 0
Progress above 1: 0

===== Sample User: USER_00001 =====

,period,monthly_surplus_dynamic,actual_goal_contribution,remaining_monthly_savings,cumulative_goal_contribution_actual,target_amount,goal_funding_progress_actual_capped,goal_remaining_amount_actual
0,2015-02-01,14591.722421,10180.644733,4411.077688,10180.644733,115357.183592,0.088253,105176.538859
1,2015-03-01,14657.685348,10226.667067,4431.018281,20407.311800,115357.183592,0.176905,94949.871792
2,2015-04-01,14776.448377,10309.528033,4466.920344,30716.839833,115357.183592,0.266276,84640.343759
3,2015-05-01,14890.182075,10388.880034,4501.302041,41105.719867,115357.183592,0.356334,74251.463725
4,2015-06-01,15003.685684,10468.071502,4535.614182,51573.791369,115357.183592,0.447079,63783.392223
5,2015-07-01,15118.054498,10547.866624,4570.187875,62121.657992,115357.183592,0.538516,53235.525600
6,2015-08-01,15215.620069,10615.938122,4599.681947,72737.596114,115357.183592,0.630542,42619.587478
7,2015-09-01,15331.604398,10696.860389,4634.744010,83434.456503,115357.183592,0.723271,31922.727089
8,2015-10-01,15451.039944,10780.190569,4670.849375,94214.647072,115357.183592,0.816721,21142.536520
9,2015-11-01,15520.887478,10828.923193,4691.964284,105043.570265,115357.183592,0.910594,10313.613327
10,2015-12-01,15639.198774,10911.468984,4727.729789,115955.039249,115357.183592,1.000000,0.000000
11,2016-01-01,15758.411923,10994.643999,4763.767924,126949.683248,115357.183592,1.000000,0.000000

===== 13.28 Complete =====

In [149]:
# 13.29. Recalculate Goal Deadline Success and Shortfall

# Months elapsed since the beginning of the simulation
monthly_financial_simulation["months_since_start_actual"] = (
    monthly_financial_simulation.groupby("user_id").cumcount()
)

# Identify observations that fall within the user's goal horizon
monthly_financial_simulation["within_goal_horizon_actual"] = (
    monthly_financial_simulation["months_since_start_actual"]
    < monthly_financial_simulation["goal_horizon_months"]
)

# Calculate actual funding accumulated up to the goal deadline
goal_deadline_outcomes = (
    monthly_financial_simulation[
        monthly_financial_simulation["within_goal_horizon_actual"]
    ]
    .groupby("user_id")
    .agg(
        goal_horizon_funding_actual=(
            "goal_monthly_contribution_actual",
            "sum"
        ),
        target_amount=("target_amount", "first"),
        goal_horizon_months=("goal_horizon_months", "first"),
        goal_horizon_type=("goal_horizon_type", "first")
    )
    .reset_index()
)

# Calculate progress achieved by the deadline
goal_deadline_outcomes["goal_progress_at_deadline_actual"] = np.where(
    goal_deadline_outcomes["target_amount"] > 0,
    goal_deadline_outcomes["goal_horizon_funding_actual"]
    / goal_deadline_outcomes["target_amount"],
    0
)

# Cap progress at 100%
goal_deadline_outcomes["goal_progress_at_deadline_actual_capped"] = (
    goal_deadline_outcomes["goal_progress_at_deadline_actual"]
    .clip(upper=1)
)

# Calculate remaining amount at deadline
goal_deadline_outcomes["goal_shortfall_actual"] = (
    goal_deadline_outcomes["target_amount"]
    - goal_deadline_outcomes["goal_horizon_funding_actual"]
).clip(lower=0)

# Goal is successful if the target was fully funded by the deadline
goal_deadline_outcomes["goal_achieved_on_time_actual"] = (
    goal_deadline_outcomes["goal_horizon_funding_actual"]
    >= goal_deadline_outcomes["target_amount"]
)

print("===== Actual Goal Deadline Validation =====")

print("\nNumber of users:", len(goal_deadline_outcomes))

print(
    "Missing outcome values:",
    goal_deadline_outcomes[
        [
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_shortfall_actual",
            "goal_achieved_on_time_actual"
        ]
    ].isna().sum().sum()
)

print(
    "\nSuccessful goals:",
    goal_deadline_outcomes["goal_achieved_on_time_actual"].sum()
)

print(
    "Unsuccessful goals:",
    (~goal_deadline_outcomes["goal_achieved_on_time_actual"]).sum()
)

print(
    "Actual goal success rate:",
    goal_deadline_outcomes["goal_achieved_on_time_actual"].mean()
)


print("\n===== Actual Goal Outcome Statistics =====")

display(
    goal_deadline_outcomes[
        [
            "goal_horizon_months",
            "target_amount",
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_shortfall_actual"
        ]
    ].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)


print("\n===== Actual Goal Success by Horizon =====")

goal_horizon_actual_summary = (
    goal_deadline_outcomes
    .groupby("goal_horizon_type")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

display(goal_horizon_actual_summary)


print("\n===== Actual Goal Success by Risk Profile =====")

# Merge risk information for analysis
goal_deadline_analysis = goal_deadline_outcomes.merge(
    synthetic_users[
        [
            "user_id",
            "risk_profile",
            "risk_score",
            "financial_situation"
        ]
    ],
    on="user_id",
    how="left",
    validate="one_to_one"
)

goal_risk_actual_summary = (
    goal_deadline_analysis
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

display(goal_risk_actual_summary)


print("\n===== Unsuccessful Goal Shortfall =====")

failed_actual_goals = goal_deadline_outcomes[
    ~goal_deadline_outcomes["goal_achieved_on_time_actual"]
]

if len(failed_actual_goals) > 0:
    display(
        failed_actual_goals[
            [
                "goal_horizon_months",
                "target_amount",
                "goal_horizon_funding_actual",
                "goal_progress_at_deadline_actual",
                "goal_shortfall_actual"
            ]
        ].describe(
            percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
        )
    )


print("\n===== 13.29 Complete =====")

===== Actual Goal Deadline Validation =====

Number of users: 10000
Missing outcome values: 0

Successful goals: 6451
Unsuccessful goals: 3549
Actual goal success rate: 0.6451

===== Actual Goal Outcome Statistics =====

,goal_horizon_months,target_amount,goal_horizon_funding_actual,goal_progress_at_deadline_actual,goal_shortfall_actual
count,10000.000000,1.000000e+04,1.000000e+04,10000.000000,10000.000000
mean,62.697000,1.383538e+05,9.449648e+05,5.191022,30580.490391
std,33.431233,1.211024e+05,2.156857e+06,6.739802,66032.898324
min,6.000000,2.824526e+03,0.000000e+00,0.000000,0.000000
10%,17.000000,4.910378e+04,0.000000e+00,0.000000,0.000000
25%,33.000000,7.189787e+04,2.676139e+04,0.341658,0.000000
50%,63.000000,1.073131e+05,2.364985e+05,2.399176,0.000000
75%,92.000000,1.595261e+05,9.683717e+05,7.586860,42376.022555
90%,109.000000,2.512942e+05,2.459436e+06,14.717067,99283.938837
95%,115.000000,3.483372e+05,4.051083e+06,19.810376,137160.695246
max,120.000000,1.900464e+06,6.659288e+07,40.211537,996069.975005

===== Actual Goal Success by Horizon =====

/tmp/ipykernel_1336/1812361076.py:111: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("goal_horizon_type")

,goal_horizon_type,users,successful_users,success_rate,median_target,median_funding,median_shortfall
0,immediate,91,6,0.065934,122930.537375,20121.874303,76053.605027
1,short_term,2669,1225,0.458973,106875.607038,83959.234680,12740.296613
2,medium_term,3081,2076,0.673807,105663.701050,250115.776529,0.000000
3,long_term,4159,3144,0.755951,108145.545245,578143.368349,0.000000

===== Actual Goal Success by Risk Profile =====

,risk_profile,users,successful_users,success_rate,median_target,median_funding,median_shortfall
0,aggressive,3333,3197,0.959196,121651.618117,984113.676988,0.000000
1,conservative,3333,721,0.216322,96588.133241,2497.185588,63600.979192
2,moderate,3334,2533,0.759748,103938.497527,263730.053050,0.000000

===== Unsuccessful Goal Shortfall =====

,goal_horizon_months,target_amount,goal_horizon_funding_actual,goal_progress_at_deadline_actual,goal_shortfall_actual
count,3549.000000,3.549000e+03,3549.000000,3549.000000,3549.000000
mean,50.328261,1.116816e+05,25515.089629,0.228844,86166.498706
std,33.878008,9.252131e+04,46679.185271,0.300823,86587.246625
min,6.000000,4.369779e+03,0.000000,0.000000,42.678602
10%,10.000000,4.192740e+04,0.000000,0.000000,17687.755423
25%,20.000000,6.140104e+04,0.000000,0.000000,36575.068283
50%,44.000000,8.887893e+04,3375.253770,0.045822,66881.764908
75%,78.000000,1.292169e+05,35085.740674,0.418055,104660.108959
90%,103.000000,1.949574e+05,77632.970987,0.758035,161579.091546
95%,113.000000,2.637767e+05,109660.092917,0.856412,229146.854506
max,120.000000,1.035134e+06,943108.339412,0.998001,996069.975005

===== 13.29 Complete =====

In [150]:
# 13.30. Final Financial Consistency Validation

print("===== FINAL FINANCIAL CONSISTENCY VALIDATION =====")

# ---------------------------------------------------------
# 1. Goal contribution cannot exceed available surplus
# ---------------------------------------------------------

contribution_exceeds_surplus = (
    monthly_financial_simulation["actual_goal_contribution"]
    > monthly_financial_simulation["available_goal_funding"]
    + 1e-9
).sum()

print("\n1. Goal contribution exceeds available surplus:",
      contribution_exceeds_surplus)


# ---------------------------------------------------------
# 2. Remaining savings cannot be negative
# ---------------------------------------------------------

negative_remaining_savings = (
    monthly_financial_simulation["remaining_monthly_savings"] < -1e-9
).sum()

print("2. Negative remaining monthly savings:",
      negative_remaining_savings)


# ---------------------------------------------------------
# 3. Allocation identity
# ---------------------------------------------------------

allocation_error = (
    monthly_financial_simulation["available_goal_funding"]
    -
    (
        monthly_financial_simulation["actual_goal_contribution"]
        +
        monthly_financial_simulation["remaining_monthly_savings"]
    )
).abs()

print("3. Maximum allocation error:",
      allocation_error.max())


# ---------------------------------------------------------
# 4. Goal progress validity
# ---------------------------------------------------------

invalid_progress = (
    (monthly_financial_simulation["goal_funding_progress_actual_capped"] < -1e-9)
    |
    (monthly_financial_simulation["goal_funding_progress_actual_capped"] > 1 + 1e-9)
).sum()

print("4. Invalid capped goal progress:",
      invalid_progress)


# ---------------------------------------------------------
# 5. User count
# ---------------------------------------------------------

unique_users = monthly_financial_simulation["user_id"].nunique()

print("5. Unique users in simulation:",
      unique_users)


# ---------------------------------------------------------
# 6. Records per user
# ---------------------------------------------------------

records_per_user = (
    monthly_financial_simulation
    .groupby("user_id")
    .size()
)

print("6. Minimum records per user:",
      records_per_user.min())

print("   Maximum records per user:",
      records_per_user.max())

print("   Expected records per user: 143")


# ---------------------------------------------------------
# 7. Goal outcome uniqueness
# ---------------------------------------------------------

goal_outcome_user_count = goal_deadline_outcomes["user_id"].nunique()

print("7. Users with goal outcomes:",
      goal_outcome_user_count)


# ---------------------------------------------------------
# 8. Goal success consistency
# ---------------------------------------------------------

success_consistency = (
    goal_deadline_outcomes["goal_achieved_on_time_actual"]
    ==
    (
        goal_deadline_outcomes["goal_shortfall_actual"] <= 1e-9
    )
).all()

print("8. Goal success/shortfall consistency:",
      success_consistency)


# ---------------------------------------------------------
# 9. Missing values in final goal outcomes
# ---------------------------------------------------------

final_goal_columns = [
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual"
]

missing_final_goal_values = (
    goal_deadline_outcomes[final_goal_columns]
    .isna()
    .sum()
)

print("\n9. Missing values in final goal outcomes:")
print(missing_final_goal_values)


# ---------------------------------------------------------
# 10. Final outcome summary
# ---------------------------------------------------------

successful_count = (
    goal_deadline_outcomes["goal_achieved_on_time_actual"]
    .sum()
)

total_goals = len(goal_deadline_outcomes)

success_rate = successful_count / total_goals

failed_count = total_goals - successful_count

print("\n===== FINAL GOAL OUTCOME =====")

print("Total goals:", total_goals)
print("Successful goals:", successful_count)
print("Unsuccessful goals:", failed_count)
print("Success rate:", success_rate)


# ---------------------------------------------------------
# 11. Overall validation flag
# ---------------------------------------------------------

all_valid = (
    contribution_exceeds_surplus == 0
    and
    negative_remaining_savings == 0
    and
    allocation_error.max() < 1e-6
    and
    invalid_progress == 0
    and
    unique_users == 10000
    and
    records_per_user.min() == 143
    and
    records_per_user.max() == 143
    and
    goal_outcome_user_count == 10000
    and
    success_consistency
    and
    missing_final_goal_values.sum() == 0
)

print("\n===== OVERALL VALIDATION =====")

if all_valid:
    print("STATUS: PASSED")
else:
    print("STATUS: REVIEW REQUIRED")

print("\n===== 13.30 Complete =====")

===== FINAL FINANCIAL CONSISTENCY VALIDATION =====

1. Goal contribution exceeds available surplus: 0
2. Negative remaining monthly savings: 0
3. Maximum allocation error: 1.4551915228366852e-11
4. Invalid capped goal progress: 0
5. Unique users in simulation: 10000
6. Minimum records per user: 143
   Maximum records per user: 143
   Expected records per user: 143
7. Users with goal outcomes: 10000
8. Goal success/shortfall consistency: True

9. Missing values in final goal outcomes:
goal_horizon_funding_actual                0
goal_progress_at_deadline_actual           0
goal_progress_at_deadline_actual_capped    0
goal_shortfall_actual                      0
goal_achieved_on_time_actual               0
dtype: int64

===== FINAL GOAL OUTCOME =====
Total goals: 10000
Successful goals: 6451
Unsuccessful goals: 3549
Success rate: 0.6451

===== OVERALL VALIDATION =====
STATUS: PASSED

===== 13.30 Complete =====

14. Goal Progress and Shortfall Analysis

In [151]:
# 14.1. Create Final Goal Outcome Dataset

goal_outcome_dataset = (
    goal_deadline_analysis[
        [
            "user_id",
            "financial_situation",
            "risk_profile",
            "risk_score",
            "goal_horizon_months",
            "goal_horizon_type",
            "target_amount",
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_progress_at_deadline_actual_capped",
            "goal_shortfall_actual",
            "goal_achieved_on_time_actual"
        ]
    ]
    .copy()
)

print("===== FINAL GOAL OUTCOME DATASET =====")

print("\nShape:", goal_outcome_dataset.shape)

print("\nUnique users:",
      goal_outcome_dataset["user_id"].nunique())

print("\nMissing values:")
print(goal_outcome_dataset.isna().sum())

print("\nDuplicate user IDs:",
      goal_outcome_dataset["user_id"].duplicated().sum())

print("\n===== Goal Outcome Sample =====")

display(goal_outcome_dataset.head(10))

print("\n===== Goal Outcome Summary =====")

print(
    goal_outcome_dataset[
        [
            "target_amount",
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_shortfall_actual"
        ]
    ].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

print("\n===== Goal Success Distribution =====")

print(
    goal_outcome_dataset["goal_achieved_on_time_actual"]
    .value_counts()
    .sort_index()
)

print("\n===== 14.1 Complete =====")

===== FINAL GOAL OUTCOME DATASET =====

Shape: (10000, 12)

Unique users: 10000

Missing values:
user_id                                    0
financial_situation                        0
risk_profile                               0
risk_score                                 0
goal_horizon_months                        0
goal_horizon_type                          0
target_amount                              0
goal_horizon_funding_actual                0
goal_progress_at_deadline_actual           0
goal_progress_at_deadline_actual_capped    0
goal_shortfall_actual                      0
goal_achieved_on_time_actual               0
dtype: int64

Duplicate user IDs: 0

===== Goal Outcome Sample =====

,user_id,financial_situation,risk_profile,risk_score,goal_horizon_months,goal_horizon_type,target_amount,goal_horizon_funding_actual,goal_progress_at_deadline_actual,goal_progress_at_deadline_actual_capped,goal_shortfall_actual,goal_achieved_on_time_actual
0,USER_00001,moderate_saving,aggressive,0.710500,48,medium_term,115357.183592,5.811302e+05,5.037660,1.000000,0.000000,True
1,USER_00002,financial_stress,conservative,0.038363,51,medium_term,59340.387689,0.000000e+00,0.000000,0.000000,59340.387689,False
2,USER_00003,low_saving,moderate,0.505350,46,medium_term,99893.237726,4.093773e+04,0.409815,0.409815,58955.510123,False
3,USER_00004,moderate_saving,conservative,0.313650,60,medium_term,75476.307623,4.566919e+04,0.605080,0.605080,29807.117161,False
4,USER_00005,high_saving,aggressive,0.750750,120,long_term,206040.342056,7.318348e+06,35.519005,1.000000,0.000000,True
5,USER_00006,high_saving,aggressive,0.823150,18,short_term,110291.964774,3.502230e+05,3.175418,1.000000,0.000000,True
6,USER_00007,high_saving,aggressive,0.762325,75,long_term,128020.414837,2.348219e+06,18.342532,1.000000,0.000000,True
7,USER_00008,low_saving,conservative,0.087587,11,short_term,269916.171830,0.000000e+00,0.000000,0.000000,269916.171830,False
8,USER_00009,moderate_saving,aggressive,0.688500,55,medium_term,182600.732773,1.616717e+06,8.853834,1.000000,0.000000,True
9,USER_00010,low_saving,moderate,0.533300,24,short_term,96702.526658,5.423986e+04,0.560894,0.560894,42462.667060,False

===== Goal Outcome Summary =====
       target_amount  goal_horizon_funding_actual  \
count   1.000000e+04                 1.000000e+04
mean    1.383538e+05                 9.449648e+05
std     1.211024e+05                 2.156857e+06
min     2.824526e+03                 0.000000e+00
10%     4.910378e+04                 0.000000e+00
25%     7.189787e+04                 2.676139e+04
50%     1.073131e+05                 2.364985e+05
75%     1.595261e+05                 9.683717e+05
90%     2.512942e+05                 2.459436e+06
95%     3.483372e+05                 4.051083e+06
max     1.900464e+06                 6.659288e+07

       goal_progress_at_deadline_actual  goal_shortfall_actual
count                      10000.000000           10000.000000
mean                           5.191022           30580.490391
std                            6.739802           66032.898324
min                            0.000000               0.000000
10%                            0.000000               0.000000
25%                            0.341658               0.000000
50%                            2.399176               0.000000
75%                            7.586860           42376.022555
90%                           14.717067           99283.938837
95%                           19.810376          137160.695246
max                           40.211537          996069.975005

===== Goal Success Distribution =====
goal_achieved_on_time_actual
False    3549
True     6451
Name: count, dtype: int64

===== 14.1 Complete =====

In [152]:
# 14.2. Goal Success and Shortfall Distribution Analysis

print("===== OVERALL GOAL OUTCOME =====")

outcome_counts = (
    goal_outcome_dataset["goal_achieved_on_time_actual"]
    .value_counts()
    .rename(index={
        True: "Successful",
        False: "Unsuccessful"
    })
)

outcome_percentages = (
    goal_outcome_dataset["goal_achieved_on_time_actual"]
    .value_counts(normalize=True)
    .rename(index={
        True: "Successful",
        False: "Unsuccessful"
    })
    * 100
)

print("\nGoal counts:")
print(outcome_counts)

print("\nGoal percentages:")
print(outcome_percentages)


# ---------------------------------------------------------
# Shortfall among unsuccessful goals
# ---------------------------------------------------------

failed_goals = goal_outcome_dataset[
    ~goal_outcome_dataset["goal_achieved_on_time_actual"]
].copy()

print("\n===== SHORTFALL AMONG UNSUCCESSFUL GOALS =====")

if len(failed_goals) > 0:

    shortfall_summary = (
        failed_goals["goal_shortfall_actual"]
        .describe(
            percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
        )
    )

    display(shortfall_summary.to_frame("shortfall"))


# ---------------------------------------------------------
# Success by financial situation
# ---------------------------------------------------------

print("\n===== GOAL SUCCESS BY FINANCIAL SITUATION =====")

financial_situation_summary = (
    goal_outcome_dataset
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

display(financial_situation_summary)


# ---------------------------------------------------------
# Success by goal horizon
# ---------------------------------------------------------

print("\n===== GOAL SUCCESS BY HORIZON =====")

horizon_summary = (
    goal_outcome_dataset
    .groupby("goal_horizon_type")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

display(horizon_summary)


# ---------------------------------------------------------
# Success by risk profile
# ---------------------------------------------------------

print("\n===== GOAL SUCCESS BY RISK PROFILE =====")

risk_summary = (
    goal_outcome_dataset
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        successful_users=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

display(risk_summary)


# ---------------------------------------------------------
# Goal progress distribution
# ---------------------------------------------------------

print("\n===== GOAL PROGRESS DISTRIBUTION =====")

progress_summary = (
    goal_outcome_dataset[
        [
            "goal_progress_at_deadline_actual",
            "goal_shortfall_actual"
        ]
    ]
    .describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)

display(progress_summary)


print("\n===== 14.2 Complete =====")

===== OVERALL GOAL OUTCOME =====

Goal counts:
goal_achieved_on_time_actual
Successful      6451
Unsuccessful    3549
Name: count, dtype: int64

Goal percentages:
goal_achieved_on_time_actual
Successful      64.51
Unsuccessful    35.49
Name: proportion, dtype: float64

===== SHORTFALL AMONG UNSUCCESSFUL GOALS =====

           shortfall
count    3549.000000
mean    86166.498706
std     86587.246625
min        42.678602
10%     17687.755423
25%     36575.068283
50%     66881.764908
75%    104660.108959
90%    161579.091546
95%    229146.854506
max    996069.975005

===== GOAL SUCCESS BY FINANCIAL SITUATION =====

,financial_situation,users,successful_users,success_rate,median_target,median_funding,median_shortfall
0,financial_stress,474,0,0.000000,77093.078084,0.000000e+00,74281.113575
1,high_saving,2043,1998,0.977974,139093.444220,1.348838e+06,0.000000
2,low_saving,2923,944,0.322956,91129.239398,1.568046e+04,44567.674464
3,moderate_saving,4560,3509,0.769518,110099.028986,3.419039e+05,0.000000

===== GOAL SUCCESS BY HORIZON =====

/tmp/ipykernel_1336/1694401708.py:84: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("goal_horizon_type")

,goal_horizon_type,users,successful_users,success_rate,median_target,median_funding,median_shortfall
0,immediate,91,6,0.065934,122930.537375,20121.874303,76053.605027
1,short_term,2669,1225,0.458973,106875.607038,83959.234680,12740.296613
2,medium_term,3081,2076,0.673807,105663.701050,250115.776529,0.000000
3,long_term,4159,3144,0.755951,108145.545245,578143.368349,0.000000

===== GOAL SUCCESS BY RISK PROFILE =====

,risk_profile,users,successful_users,success_rate,median_target,median_funding,median_shortfall
0,aggressive,3333,3197,0.959196,121651.618117,984113.676988,0.000000
1,conservative,3333,721,0.216322,96588.133241,2497.185588,63600.979192
2,moderate,3334,2533,0.759748,103938.497527,263730.053050,0.000000

===== GOAL PROGRESS DISTRIBUTION =====

       goal_progress_at_deadline_actual  goal_shortfall_actual
count                      10000.000000           10000.000000
mean                           5.191022           30580.490391
std                            6.739802           66032.898324
min                            0.000000               0.000000
10%                            0.000000               0.000000
25%                            0.341658               0.000000
50%                            2.399176               0.000000
75%                            7.586860           42376.022555
90%                           14.717067           99283.938837
95%                           19.810376          137160.695246
max                           40.211537          996069.975005

===== 14.2 Complete =====

In [153]:
# 14.3. Generate Data-Driven Goal Shortfall Severity

failed_goals = goal_outcome_dataset[
    ~goal_outcome_dataset["goal_achieved_on_time_actual"]
].copy()

# ---------------------------------------------------------
# Determine population-derived progress boundaries
# among unsuccessful goals
# ---------------------------------------------------------

progress_q33 = failed_goals[
    "goal_progress_at_deadline_actual"
].quantile(1/3)

progress_q67 = failed_goals[
    "goal_progress_at_deadline_actual"
].quantile(2/3)

print("===== DATA-DERIVED SHORTFALL BOUNDARIES =====")

print("33rd percentile of unsuccessful-goal progress:",
      progress_q33)

print("67th percentile of unsuccessful-goal progress:",
      progress_q67)


# ---------------------------------------------------------
# Generate severity categories
# ---------------------------------------------------------

def classify_shortfall(progress, success):

    if success:
        return "no_shortfall"

    if progress <= progress_q33:
        return "severe_shortfall"

    elif progress <= progress_q67:
        return "moderate_shortfall"

    else:
        return "mild_shortfall"


goal_outcome_dataset["goal_shortfall_severity"] = (
    goal_outcome_dataset.apply(
        lambda row: classify_shortfall(
            row["goal_progress_at_deadline_actual"],
            row["goal_achieved_on_time_actual"]
        ),
        axis=1
    )
)


# ---------------------------------------------------------
# Validate distribution
# ---------------------------------------------------------

print("\n===== SHORTFALL SEVERITY DISTRIBUTION =====")

severity_counts = (
    goal_outcome_dataset[
        "goal_shortfall_severity"
    ]
    .value_counts()
)

severity_percentages = (
    goal_outcome_dataset[
        "goal_shortfall_severity"
    ]
    .value_counts(normalize=True)
    * 100
)

print("\nCounts:")
print(severity_counts)

print("\nPercentages:")
print(severity_percentages)


# ---------------------------------------------------------
# Validate severity against success status
# ---------------------------------------------------------

print("\n===== SEVERITY VALIDATION =====")

print(
    pd.crosstab(
        goal_outcome_dataset["goal_shortfall_severity"],
        goal_outcome_dataset["goal_achieved_on_time_actual"]
    )
)


# ---------------------------------------------------------
# Summary statistics by severity
# ---------------------------------------------------------

print("\n===== SEVERITY CHARACTERISTICS =====")

severity_summary = (
    goal_outcome_dataset
    .groupby("goal_shortfall_severity")
    .agg(
        users=("user_id", "count"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_progress=("goal_progress_at_deadline_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

display(severity_summary)


print("\n===== 14.3 Complete =====")

===== DATA-DERIVED SHORTFALL BOUNDARIES =====
33rd percentile of unsuccessful-goal progress: 0.0
67th percentile of unsuccessful-goal progress: 0.2693681367308097

===== SHORTFALL SEVERITY DISTRIBUTION =====

Counts:
goal_shortfall_severity
no_shortfall          6451
severe_shortfall      1465
mild_shortfall        1183
moderate_shortfall     901
Name: count, dtype: int64

Percentages:
goal_shortfall_severity
no_shortfall          64.51
severe_shortfall      14.65
mild_shortfall        11.83
moderate_shortfall     9.01
Name: proportion, dtype: float64

===== SEVERITY VALIDATION =====
goal_achieved_on_time_actual  False  True
goal_shortfall_severity
mild_shortfall                 1183      0
moderate_shortfall              901      0
no_shortfall                      0   6451
severe_shortfall               1465      0

===== SEVERITY CHARACTERISTICS =====

,goal_shortfall_severity,users,median_target,median_funding,median_progress,median_shortfall
0,mild_shortfall,1183,90608.498290,51186.931087,0.605080,31623.125994
1,moderate_shortfall,901,92877.746033,7346.889962,0.083415,82626.473145
2,no_shortfall,6451,118217.180789,643347.820580,5.489914,0.000000
3,severe_shortfall,1465,86727.112194,0.000000,0.000000,86727.112194

===== 14.3 Complete =====

In [154]:
# 14.4. Create Final Goal Outcome Labels

print("===== CREATING FINAL GOAL OUTCOME LABELS =====")


# ---------------------------------------------------------
# 1. Binary goal outcome
# ---------------------------------------------------------

goal_outcome_dataset["goal_outcome"] = np.where(
    goal_outcome_dataset["goal_achieved_on_time_actual"],
    "success",
    "failure"
)


# ---------------------------------------------------------
# 2. Goal risk / shortfall level
# ---------------------------------------------------------

goal_outcome_dataset["goal_risk_level"] = (
    goal_outcome_dataset["goal_shortfall_severity"]
)


# ---------------------------------------------------------
# 3. Funding ratio relative to target
# ---------------------------------------------------------

goal_outcome_dataset["goal_funding_ratio"] = np.where(
    goal_outcome_dataset["target_amount"] > 0,
    goal_outcome_dataset["goal_horizon_funding_actual"]
    / goal_outcome_dataset["target_amount"],
    0
)

# Cap at 1 because funding beyond the target is not
# required when measuring target achievement.
goal_outcome_dataset["goal_funding_ratio_capped"] = (
    goal_outcome_dataset["goal_funding_ratio"].clip(upper=1)
)


# ---------------------------------------------------------
# 4. Shortfall ratio relative to target
# ---------------------------------------------------------

goal_outcome_dataset["goal_shortfall_ratio"] = np.where(
    goal_outcome_dataset["target_amount"] > 0,
    goal_outcome_dataset["goal_shortfall_actual"]
    / goal_outcome_dataset["target_amount"],
    0
)


# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

print("\n===== OUTCOME DISTRIBUTION =====")

print(
    goal_outcome_dataset["goal_outcome"]
    .value_counts()
)


print("\n===== RISK LEVEL DISTRIBUTION =====")

print(
    goal_outcome_dataset["goal_risk_level"]
    .value_counts()
)


print("\n===== FUNDING RATIO VALIDATION =====")

print(
    goal_outcome_dataset[
        [
            "goal_funding_ratio",
            "goal_funding_ratio_capped",
            "goal_shortfall_ratio"
        ]
    ].describe(
        percentiles=[0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
    )
)


# ---------------------------------------------------------
# Consistency checks
# ---------------------------------------------------------

print("\n===== CONSISTENCY CHECKS =====")

success_mismatch = (
    (
        goal_outcome_dataset["goal_outcome"] == "success"
    )
    != goal_outcome_dataset["goal_achieved_on_time_actual"]
).sum()

risk_mismatch = (
    (
        goal_outcome_dataset["goal_risk_level"]
        != goal_outcome_dataset["goal_shortfall_severity"]
    )
).sum()

negative_funding_ratio = (
    goal_outcome_dataset["goal_funding_ratio"] < 0
).sum()

negative_shortfall_ratio = (
    goal_outcome_dataset["goal_shortfall_ratio"] < 0
).sum()

invalid_capped_ratio = (
    (goal_outcome_dataset["goal_funding_ratio_capped"] < 0)
    |
    (goal_outcome_dataset["goal_funding_ratio_capped"] > 1)
).sum()

print("Success-label mismatches:", success_mismatch)
print("Risk-label mismatches:", risk_mismatch)
print("Negative funding ratios:", negative_funding_ratio)
print("Negative shortfall ratios:", negative_shortfall_ratio)
print("Invalid capped funding ratios:", invalid_capped_ratio)


# ---------------------------------------------------------
# Sample records
# ---------------------------------------------------------

print("\n===== SAMPLE FINAL OUTCOMES =====")

display(
    goal_outcome_dataset[
        [
            "user_id",
            "financial_situation",
            "risk_profile",
            "goal_horizon_type",
            "target_amount",
            "goal_horizon_funding_actual",
            "goal_funding_ratio_capped",
            "goal_shortfall_actual",
            "goal_shortfall_ratio",
            "goal_outcome",
            "goal_risk_level"
        ]
    ].head(10)
)


print("\n===== 14.4 Complete =====")

===== CREATING FINAL GOAL OUTCOME LABELS =====

===== OUTCOME DISTRIBUTION =====
goal_outcome
success    6451
failure    3549
Name: count, dtype: int64

===== RISK LEVEL DISTRIBUTION =====
goal_risk_level
no_shortfall          6451
severe_shortfall      1465
mild_shortfall        1183
moderate_shortfall     901
Name: count, dtype: int64

===== FUNDING RATIO VALIDATION =====
       goal_funding_ratio  goal_funding_ratio_capped  goal_shortfall_ratio
count        10000.000000               10000.000000          10000.000000
mean             5.191022                   0.726317              0.273683
std              6.739802                   0.410213              0.410213
min              0.000000                   0.000000              0.000000
10%              0.000000                   0.000000              0.000000
25%              0.341658                   0.341658              0.000000
50%              2.399176                   1.000000              0.000000
75%              7.586860                   1.000000              0.658342
90%             14.717067                   1.000000              1.000000
95%             19.810376                   1.000000              1.000000
max             40.211537                   1.000000              1.000000

===== CONSISTENCY CHECKS =====
Success-label mismatches: 0
Risk-label mismatches: 0
Negative funding ratios: 0
Negative shortfall ratios: 0
Invalid capped funding ratios: 0

===== SAMPLE FINAL OUTCOMES =====

,user_id,financial_situation,risk_profile,goal_horizon_type,target_amount,goal_horizon_funding_actual,goal_funding_ratio_capped,goal_shortfall_actual,goal_shortfall_ratio,goal_outcome,goal_risk_level
0,USER_00001,moderate_saving,aggressive,medium_term,115357.183592,5.811302e+05,1.000000,0.000000,0.000000,success,no_shortfall
1,USER_00002,financial_stress,conservative,medium_term,59340.387689,0.000000e+00,0.000000,59340.387689,1.000000,failure,severe_shortfall
2,USER_00003,low_saving,moderate,medium_term,99893.237726,4.093773e+04,0.409815,58955.510123,0.590185,failure,mild_shortfall
3,USER_00004,moderate_saving,conservative,medium_term,75476.307623,4.566919e+04,0.605080,29807.117161,0.394920,failure,mild_shortfall
4,USER_00005,high_saving,aggressive,long_term,206040.342056,7.318348e+06,1.000000,0.000000,0.000000,success,no_shortfall
5,USER_00006,high_saving,aggressive,short_term,110291.964774,3.502230e+05,1.000000,0.000000,0.000000,success,no_shortfall
6,USER_00007,high_saving,aggressive,long_term,128020.414837,2.348219e+06,1.000000,0.000000,0.000000,success,no_shortfall
7,USER_00008,low_saving,conservative,short_term,269916.171830,0.000000e+00,0.000000,269916.171830,1.000000,failure,severe_shortfall
8,USER_00009,moderate_saving,aggressive,medium_term,182600.732773,1.616717e+06,1.000000,0.000000,0.000000,success,no_shortfall
9,USER_00010,low_saving,moderate,short_term,96702.526658,5.423986e+04,0.560894,42462.667060,0.439106,failure,mild_shortfall

===== 14.4 Complete =====

In [155]:
# 14.5. Validate Relationships Between Financial Characteristics
#       and Goal Outcomes

print("===== 14.5 GOAL OUTCOME RELATIONSHIP VALIDATION =====")


# ---------------------------------------------------------
# 1. Success rate by financial situation
# ---------------------------------------------------------

print("\n===== SUCCESS RATE vs FINANCIAL SITUATION =====")

financial_relationship = (
    goal_outcome_dataset
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall_ratio=("goal_shortfall_ratio", "median")
    )
    .reset_index()
)

display(financial_relationship)


# ---------------------------------------------------------
# 2. Success rate by goal horizon
# ---------------------------------------------------------

print("\n===== SUCCESS RATE vs GOAL HORIZON =====")

horizon_relationship = (
    goal_outcome_dataset
    .groupby("goal_horizon_type")
    .agg(
        users=("user_id", "count"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall_ratio=("goal_shortfall_ratio", "median")
    )
    .reset_index()
)

display(horizon_relationship)


# ---------------------------------------------------------
# 3. Success rate by risk profile
# ---------------------------------------------------------

print("\n===== SUCCESS RATE vs RISK PROFILE =====")

risk_relationship = (
    goal_outcome_dataset
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall_ratio=("goal_shortfall_ratio", "median")
    )
    .reset_index()
)

display(risk_relationship)


# ---------------------------------------------------------
# 4. Goal funding vs target
# ---------------------------------------------------------

print("\n===== FUNDING ADEQUACY =====")

funding_adequacy = pd.DataFrame({
    "users": [
        len(goal_outcome_dataset),
        (
            goal_outcome_dataset["goal_funding_ratio"] >= 1
        ).sum(),
        (
            goal_outcome_dataset["goal_funding_ratio"] < 1
        ).sum()
    ],
    "category": [
        "All users",
        "Funding >= target",
        "Funding < target"
    ]
})

funding_adequacy["percentage"] = (
    funding_adequacy["users"]
    / len(goal_outcome_dataset)
    * 100
)

display(funding_adequacy)


# ---------------------------------------------------------
# 5. Relationship between funding ratio and success
# ---------------------------------------------------------

print("\n===== FUNDING RATIO BY OUTCOME =====")

funding_by_outcome = (
    goal_outcome_dataset
    .groupby("goal_outcome")
    .agg(
        users=("user_id", "count"),
        median_funding_ratio=(
            "goal_funding_ratio",
            "median"
        ),
        median_shortfall_ratio=(
            "goal_shortfall_ratio",
            "median"
        )
    )
    .reset_index()
)

display(funding_by_outcome)


# ---------------------------------------------------------
# 6. Correlation analysis
# ---------------------------------------------------------

print("\n===== NUMERICAL RELATIONSHIPS =====")

correlation_columns = [
    "goal_funding_ratio",
    "goal_shortfall_ratio",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual"
]

correlation_matrix = (
    goal_outcome_dataset[correlation_columns]
    .corr()
)

display(correlation_matrix)


# ---------------------------------------------------------
# 7. Final logical checks
# ---------------------------------------------------------

print("\n===== LOGICAL VALIDATION =====")

success_with_shortfall = (
    (
        goal_outcome_dataset["goal_achieved_on_time_actual"]
        &
        (goal_outcome_dataset["goal_shortfall_actual"] > 0)
    ).sum()
)

failure_without_shortfall = (
    (
        ~goal_outcome_dataset["goal_achieved_on_time_actual"]
        &
        (goal_outcome_dataset["goal_shortfall_actual"] == 0)
    ).sum()
)

negative_shortfall = (
    goal_outcome_dataset["goal_shortfall_actual"] < 0
).sum()

negative_funding = (
    goal_outcome_dataset["goal_horizon_funding_actual"] < 0
).sum()

print(
    "Successful goals with positive shortfall:",
    success_with_shortfall
)

print(
    "Failed goals with zero shortfall:",
    failure_without_shortfall
)

print(
    "Negative shortfall values:",
    negative_shortfall
)

print(
    "Negative funding values:",
    negative_funding
)


print("\n===== 14.5 Complete =====")

===== 14.5 GOAL OUTCOME RELATIONSHIP VALIDATION =====

===== SUCCESS RATE vs FINANCIAL SITUATION =====

,financial_situation,users,success_rate,median_funding,median_shortfall_ratio
0,financial_stress,474,0.000000,0.000000e+00,1.000000
1,high_saving,2043,0.977974,1.348838e+06,0.000000
2,low_saving,2923,0.322956,1.568046e+04,0.797641
3,moderate_saving,4560,0.769518,3.419039e+05,0.000000

===== SUCCESS RATE vs GOAL HORIZON =====

/tmp/ipykernel_1336/2766572465.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("goal_horizon_type")

,goal_horizon_type,users,success_rate,median_funding,median_shortfall_ratio
0,immediate,91,0.065934,20121.874303,0.750395
1,short_term,2669,0.458973,83959.234680,0.165165
2,medium_term,3081,0.673807,250115.776529,0.000000
3,long_term,4159,0.755951,578143.368349,0.000000

===== SUCCESS RATE vs RISK PROFILE =====

   risk_profile  users  success_rate  median_funding  median_shortfall_ratio
0    aggressive   3333      0.959196   984113.676988                 0.00000
1  conservative   3333      0.216322     2497.185588                 0.97009
2      moderate   3334      0.759748   263730.053050                 0.00000

===== FUNDING ADEQUACY =====

   users           category  percentage
0  10000          All users      100.00
1   6451  Funding >= target       64.51
2   3549   Funding < target       35.49

===== FUNDING RATIO BY OUTCOME =====

  goal_outcome  users  median_funding_ratio  median_shortfall_ratio
0      failure   3549              0.045822                0.954178
1      success   6451              5.489914                0.000000

===== NUMERICAL RELATIONSHIPS =====

,goal_funding_ratio,goal_shortfall_ratio,goal_horizon_months,target_amount,goal_horizon_funding_actual
goal_funding_ratio,1.000000,-0.502871,0.488846,0.277858,0.719368
goal_shortfall_ratio,-0.502871,1.000000,-0.192704,-0.146653,-0.288543
goal_horizon_months,0.488846,-0.192704,1.000000,0.014456,0.292572
target_amount,0.277858,-0.146653,0.014456,1.000000,0.632572
goal_horizon_funding_actual,0.719368,-0.288543,0.292572,0.632572,1.000000

===== LOGICAL VALIDATION =====
Successful goals with positive shortfall: 0
Failed goals with zero shortfall: 0
Negative shortfall values: 0
Negative funding values: 0

===== 14.5 Complete =====

In [156]:
# 14.6. Save Final Goal Outcome Dataset

goal_outcome_output_path = (
    "/content/drive/MyDrive/GoalPilot_AI/"
    "simulation/06_results/final_goal_outcome_dataset.csv"
)

# Save the validated one-row-per-user goal outcome dataset
goal_outcome_dataset.to_csv(
    goal_outcome_output_path,
    index=False
)

print("===== FINAL GOAL OUTCOME DATASET =====")

print("Saved to:")
print(goal_outcome_output_path)

print("\nShape:")
print(goal_outcome_dataset.shape)

print("\nUnique users:")
print(goal_outcome_dataset["user_id"].nunique())

print("\nDuplicate user IDs:")
print(goal_outcome_dataset["user_id"].duplicated().sum())

print("\nMissing values:")
print(
    goal_outcome_dataset.isna().sum()
    .sum()
)

print("\nColumns:")
print(goal_outcome_dataset.columns.tolist())


# ---------------------------------------------------------
# Final outcome counts
# ---------------------------------------------------------

print("\n===== FINAL OUTCOME COUNTS =====")

print(
    goal_outcome_dataset["goal_outcome"]
    .value_counts()
)

print("\n===== FINAL RISK LEVEL COUNTS =====")

print(
    goal_outcome_dataset["goal_risk_level"]
    .value_counts()
)


# ---------------------------------------------------------
# Final success rate
# ---------------------------------------------------------

final_success_rate = (
    goal_outcome_dataset["goal_achieved_on_time_actual"]
    .mean()
)

print("\nFinal goal success rate:")
print(f"{final_success_rate:.2%}")


print("\n===== 14.6 Complete =====")

===== FINAL GOAL OUTCOME DATASET =====
Saved to:
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/final_goal_outcome_dataset.csv

Shape:
(10000, 18)

Unique users:
10000

Duplicate user IDs:
0

Missing values:
0

Columns:
['user_id', 'financial_situation', 'risk_profile', 'risk_score', 'goal_horizon_months', 'goal_horizon_type', 'target_amount', 'goal_horizon_funding_actual', 'goal_progress_at_deadline_actual', 'goal_progress_at_deadline_actual_capped', 'goal_shortfall_actual', 'goal_achieved_on_time_actual', 'goal_shortfall_severity', 'goal_outcome', 'goal_risk_level', 'goal_funding_ratio', 'goal_funding_ratio_capped', 'goal_shortfall_ratio']

===== FINAL OUTCOME COUNTS =====
goal_outcome
success    6451
failure    3549
Name: count, dtype: int64

===== FINAL RISK LEVEL COUNTS =====
goal_risk_level
no_shortfall          6451
severe_shortfall      1465
mild_shortfall        1183
moderate_shortfall     901
Name: count, dtype: int64

Final goal success rate:
64.51%

===== 14.6 Complete =====

In [157]:
# 14.7. Final Simulation Dataset Quality Check

print("====================================================")
print("FINAL GOAL SIMULATION DATASET QUALITY CHECK")
print("====================================================")


# ---------------------------------------------------------
# 1. Required columns
# ---------------------------------------------------------

required_columns = [
    "user_id",
    "financial_situation",
    "risk_profile",
    "risk_score",
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual",
    "goal_shortfall_severity",
    "goal_outcome",
    "goal_risk_level",
    "goal_funding_ratio",
    "goal_funding_ratio_capped",
    "goal_shortfall_ratio"
]

missing_required_columns = [
    col for col in required_columns
    if col not in goal_outcome_dataset.columns
]

print("\n1. Required columns missing:")
print(missing_required_columns)


# ---------------------------------------------------------
# 2. Dataset dimensions
# ---------------------------------------------------------

print("\n2. Dataset dimensions:")
print("Rows:", len(goal_outcome_dataset))
print("Columns:", len(goal_outcome_dataset.columns))


# ---------------------------------------------------------
# 3. User uniqueness
# ---------------------------------------------------------

print("\n3. User uniqueness:")

unique_users = goal_outcome_dataset["user_id"].nunique()
duplicate_users = goal_outcome_dataset["user_id"].duplicated().sum()

print("Unique users:", unique_users)
print("Duplicate user IDs:", duplicate_users)


# ---------------------------------------------------------
# 4. Missing values
# ---------------------------------------------------------

print("\n4. Missing values:")

total_missing = goal_outcome_dataset.isna().sum().sum()

print("Total missing values:", total_missing)


# ---------------------------------------------------------
# 5. Numerical validity
# ---------------------------------------------------------

print("\n5. Numerical validity:")

numeric_checks = {
    "negative_target_amount":
        (goal_outcome_dataset["target_amount"] < 0).sum(),

    "negative_goal_funding":
        (goal_outcome_dataset["goal_horizon_funding_actual"] < 0).sum(),

    "negative_shortfall":
        (goal_outcome_dataset["goal_shortfall_actual"] < 0).sum(),

    "negative_funding_ratio":
        (goal_outcome_dataset["goal_funding_ratio"] < 0).sum(),

    "negative_shortfall_ratio":
        (goal_outcome_dataset["goal_shortfall_ratio"] < 0).sum(),

    "funding_ratio_capped_below_zero":
        (goal_outcome_dataset["goal_funding_ratio_capped"] < 0).sum(),

    "funding_ratio_capped_above_one":
        (goal_outcome_dataset["goal_funding_ratio_capped"] > 1).sum(),

    "shortfall_ratio_above_one":
        (goal_outcome_dataset["goal_shortfall_ratio"] > 1).sum()
}

for check_name, count in numeric_checks.items():
    print(f"{check_name}: {count}")


# ---------------------------------------------------------
# 6. Goal outcome consistency
# ---------------------------------------------------------

print("\n6. Goal outcome consistency:")

success_mismatch = (
    (
        goal_outcome_dataset["goal_outcome"] == "success"
    )
    != goal_outcome_dataset["goal_achieved_on_time_actual"]
).sum()

print("Success-label mismatches:", success_mismatch)


# ---------------------------------------------------------
# 7. Shortfall consistency
# ---------------------------------------------------------

print("\n7. Shortfall consistency:")

successful_with_shortfall = (
    (
        goal_outcome_dataset["goal_achieved_on_time_actual"]
        &
        (goal_outcome_dataset["goal_shortfall_actual"] > 0)
    ).sum()
)

failed_without_shortfall = (
    (
        ~goal_outcome_dataset["goal_achieved_on_time_actual"]
        &
        (goal_outcome_dataset["goal_shortfall_actual"] <= 0)
    ).sum()
)

print(
    "Successful goals with positive shortfall:",
    successful_with_shortfall
)

print(
    "Failed goals without positive shortfall:",
    failed_without_shortfall
)


# ---------------------------------------------------------
# 8. Severity consistency
# ---------------------------------------------------------

print("\n8. Severity consistency:")

severity_mismatch = (
    goal_outcome_dataset["goal_risk_level"]
    != goal_outcome_dataset["goal_shortfall_severity"]
).sum()

print("Severity mismatches:", severity_mismatch)


# ---------------------------------------------------------
# 9. Valid categorical values
# ---------------------------------------------------------

print("\n9. Categorical value validation:")

expected_horizons = {
    "immediate",
    "short_term",
    "medium_term",
    "long_term"
}

expected_risk_profiles = {
    "conservative",
    "moderate",
    "aggressive"
}

expected_financial_situations = {
    "financial_stress",
    "low_saving",
    "moderate_saving",
    "high_saving"
}

expected_outcomes = {
    "success",
    "failure"
}

expected_severity = {
    "no_shortfall",
    "mild_shortfall",
    "moderate_shortfall",
    "severe_shortfall"
}

invalid_horizons = set(
    goal_outcome_dataset["goal_horizon_type"].unique()
) - expected_horizons

invalid_risk_profiles = set(
    goal_outcome_dataset["risk_profile"].unique()
) - expected_risk_profiles

invalid_financial_situations = set(
    goal_outcome_dataset["financial_situation"].unique()
) - expected_financial_situations

invalid_outcomes = set(
    goal_outcome_dataset["goal_outcome"].unique()
) - expected_outcomes

invalid_severity = set(
    goal_outcome_dataset["goal_shortfall_severity"].unique()
) - expected_severity

print("Invalid horizon values:", invalid_horizons)
print("Invalid risk profiles:", invalid_risk_profiles)
print(
    "Invalid financial situations:",
    invalid_financial_situations
)
print("Invalid outcome values:", invalid_outcomes)
print("Invalid severity values:", invalid_severity)


# ---------------------------------------------------------
# 10. Final PASS / FAIL
# ---------------------------------------------------------

all_checks_passed = (
    len(missing_required_columns) == 0
    and len(goal_outcome_dataset) == unique_users
    and duplicate_users == 0
    and total_missing == 0
    and all(count == 0 for count in numeric_checks.values())
    and success_mismatch == 0
    and successful_with_shortfall == 0
    and failed_without_shortfall == 0
    and severity_mismatch == 0
    and len(invalid_horizons) == 0
    and len(invalid_risk_profiles) == 0
    and len(invalid_financial_situations) == 0
    and len(invalid_outcomes) == 0
    and len(invalid_severity) == 0
)

print("\n====================================================")

if all_checks_passed:
    print("FINAL STATUS: PASSED")
else:
    print("FINAL STATUS: FAILED")

print("====================================================")


print("\n===== 14.7 Complete =====")

====================================================
FINAL GOAL SIMULATION DATASET QUALITY CHECK
====================================================

1. Required columns missing:
[]

2. Dataset dimensions:
Rows: 10000
Columns: 18

3. User uniqueness:
Unique users: 10000
Duplicate user IDs: 0

4. Missing values:
Total missing values: 0

5. Numerical validity:
negative_target_amount: 0
negative_goal_funding: 0
negative_shortfall: 0
negative_funding_ratio: 0
negative_shortfall_ratio: 0
funding_ratio_capped_below_zero: 0
funding_ratio_capped_above_one: 0
shortfall_ratio_above_one: 0

6. Goal outcome consistency:
Success-label mismatches: 0

7. Shortfall consistency:
Successful goals with positive shortfall: 0
Failed goals without positive shortfall: 0

8. Severity consistency:
Severity mismatches: 0

9. Categorical value validation:
Invalid horizon values: set()
Invalid risk profiles: set()
Invalid financial situations: set()
Invalid outcome values: set()
Invalid severity values: set()

====================================================
FINAL STATUS: PASSED
====================================================

===== 14.7 Complete =====

15. Simulation Dataset Generation

In [158]:
# 15.1. Inspect Simulation Features for Final Dataset

print("===== MONTHLY SIMULATION DATASET =====")

print("Shape:")
print(monthly_financial_simulation.shape)

print("\nColumns:")
for i, column in enumerate(monthly_financial_simulation.columns, start=1):
    print(f"{i:02d}. {column}")


print("\n\n===== FINAL GOAL OUTCOME DATASET =====")

print("Shape:")
print(goal_outcome_dataset.shape)

print("\nColumns:")
for i, column in enumerate(goal_outcome_dataset.columns, start=1):
    print(f"{i:02d}. {column}")


print("\n===== 15.1 Complete =====")

===== MONTHLY SIMULATION DATASET =====
Shape:
(1430000, 80)

Columns:
01. user_id
02. period
03. portfolio_return
04. portfolio_value
05. monthly_income
06. monthly_expenditure
07. monthly_surplus
08. monthly_emi
09. initial_savings
10. initial_investment
11. investment_capacity_ratio
12. risk_score
13. risk_profile
14. inflation_level
15. inflation_change
16. inflation_pct_change
17. inflation_trend
18. inflation_regime
19. nifty_monthly_return
20. nifty_return_volatility
21. nifty_3m_volatility
22. nifty_ma_gap
23. market_return_regime
24. market_volatility_regime
25. average_walr
26. walr_change
27. credit_pressure
28. walr_3period_ma
29. walr_momentum
30. walr_regime
31. annual_inflation_rate
32. monthly_inflation_rate
33. cumulative_inflation_factor
34. monthly_expenditure_dynamic
35. monthly_income_dynamic
36. monthly_surplus_dynamic
37. positive_cash_flow
38. cash_flow_status
39. financial_situation
40. cumulative_cash_flow
41. savings_balance
42. savings_balance_status
43. pre_savings_balance
44. unfunded_deficit
45. total_financial_wealth
46. portfolio_wealth_ratio
47. goal_horizon_months
48. goal_horizon_type
49. target_amount
50. goal_reference_amount
51. target_to_annual_income_ratio
52. target_to_savings_ratio
53. target_funding_months
54. target_funding_months_percentile
55. goal_allocation_strength
56. goal_allocation_factor
57. goal_specific_monthly_capacity
58. goal_allocation_percentile
59. goal_monthly_contribution
60. cumulative_goal_contribution
61. goal_funding_progress
62. goal_funding_progress_capped
63. goal_remaining_amount
64. months_since_start
65. within_goal_horizon
66. goal_horizon_funding
67. goal_horizon_shortfall
68. goal_horizon_progress
69. goal_achieved_on_time
70. available_goal_funding
71. intended_goal_contribution
72. actual_goal_contribution
73. remaining_monthly_savings
74. goal_monthly_contribution_actual
75. cumulative_goal_contribution_actual
76. goal_funding_progress_actual
77. goal_funding_progress_actual_capped
78. goal_remaining_amount_actual
79. months_since_start_actual
80. within_goal_horizon_actual


===== FINAL GOAL OUTCOME DATASET =====
Shape:
(10000, 18)

Columns:
01. user_id
02. financial_situation
03. risk_profile
04. risk_score
05. goal_horizon_months
06. goal_horizon_type
07. target_amount
08. goal_horizon_funding_actual
09. goal_progress_at_deadline_actual
10. goal_progress_at_deadline_actual_capped
11. goal_shortfall_actual
12. goal_achieved_on_time_actual
13. goal_shortfall_severity
14. goal_outcome
15. goal_risk_level
16. goal_funding_ratio
17. goal_funding_ratio_capped
18. goal_shortfall_ratio

===== 15.1 Complete =====

In [160]:
# 15.2. Create Final User-Level Simulation Dataset
# Corrected version

print("===== CREATING FINAL USER-LEVEL SIMULATION DATASET =====")


# ---------------------------------------------------------
# 1. Select final financial-state features
# ---------------------------------------------------------

financial_state_columns = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "financial_situation"
]


# ---------------------------------------------------------
# 2. Select final goal-state features
# ---------------------------------------------------------

goal_state_columns = [
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "target_to_annual_income_ratio",
    "target_to_savings_ratio",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor"
]


# ---------------------------------------------------------
# 3. Select final simulation-outcome features
# ---------------------------------------------------------

outcome_columns = [
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual",
    "goal_shortfall_severity",
    "goal_outcome",
    "goal_funding_ratio",
    "goal_funding_ratio_capped",
    "goal_shortfall_ratio"
]


# ---------------------------------------------------------
# 4. Combine feature lists
# ---------------------------------------------------------

final_simulation_columns = (
    financial_state_columns
    + goal_state_columns
    + outcome_columns
)

print("\nSelected columns:")

for i, column in enumerate(
    final_simulation_columns,
    start=1
):
    print(f"{i:02d}. {column}")


# ---------------------------------------------------------
# 5. Extract one user-level financial/goal state
# ---------------------------------------------------------
#
# The monthly simulation has 143 observations per user.
#
# Financial-state and goal-state variables are repeated
# across the monthly simulation.
#
# Therefore, one row per user is sufficient for the
# user-level optimisation dataset.
#

user_state_dataset = (
    monthly_financial_simulation[
        financial_state_columns + goal_state_columns
    ]
    .groupby("user_id", as_index=False)
    .first()
)


# ---------------------------------------------------------
# 6. Merge validated goal outcomes
# ---------------------------------------------------------

validated_outcome_columns = [
    "user_id"
] + outcome_columns

final_simulation_dataset = (
    user_state_dataset
    .merge(
        goal_outcome_dataset[
            validated_outcome_columns
        ],
        on="user_id",
        how="left",
        validate="one_to_one"
    )
)


# ---------------------------------------------------------
# 7. Validate dimensions
# ---------------------------------------------------------

print("\n===== DATASET DIMENSIONS =====")

print(
    "Rows:",
    len(final_simulation_dataset)
)

print(
    "Columns:",
    len(final_simulation_dataset.columns)
)

print(
    "Unique users:",
    final_simulation_dataset["user_id"].nunique()
)

print(
    "Duplicate user IDs:",
    final_simulation_dataset[
        "user_id"
    ].duplicated().sum()
)


# ---------------------------------------------------------
# 8. Missing-value validation
# ---------------------------------------------------------

print("\n===== MISSING VALUE CHECK =====")

total_missing = (
    final_simulation_dataset
    .isna()
    .sum()
    .sum()
)

print(
    "Total missing values:",
    total_missing
)


# ---------------------------------------------------------
# 9. Compare success outcomes
# ---------------------------------------------------------

print("\n===== OUTCOME CONSISTENCY =====")

success_difference = (
    final_simulation_dataset[
        "goal_achieved_on_time_actual"
    ].sum()
    -
    goal_outcome_dataset[
        "goal_achieved_on_time_actual"
    ].sum()
)

print(
    "Difference in successful goals:",
    success_difference
)


# ---------------------------------------------------------
# 10. Display sample
# ---------------------------------------------------------

print("\n===== SAMPLE FINAL SIMULATION RECORDS =====")

display(
    final_simulation_dataset.head(10)
)


print("\n===== 15.2 Complete =====")

===== CREATING FINAL USER-LEVEL SIMULATION DATASET =====

Selected columns:
01. user_id
02. monthly_income
03. monthly_expenditure
04. monthly_emi
05. initial_savings
06. initial_investment
07. investment_capacity_ratio
08. risk_score
09. risk_profile
10. financial_situation
11. goal_horizon_months
12. goal_horizon_type
13. target_amount
14. target_to_annual_income_ratio
15. target_to_savings_ratio
16. goal_specific_monthly_capacity
17. goal_allocation_factor
18. goal_horizon_funding_actual
19. goal_progress_at_deadline_actual
20. goal_progress_at_deadline_actual_capped
21. goal_shortfall_actual
22. goal_achieved_on_time_actual
23. goal_shortfall_severity
24. goal_outcome
25. goal_funding_ratio
26. goal_funding_ratio_capped
27. goal_shortfall_ratio

===== DATASET DIMENSIONS =====
Rows: 10000
Columns: 27
Unique users: 10000
Duplicate user IDs: 0

===== MISSING VALUE CHECK =====
Total missing values: 0

===== OUTCOME CONSISTENCY =====
Difference in successful goals: 0

===== SAMPLE FINAL SIMULATION RECORDS =====

,user_id,monthly_income,monthly_expenditure,monthly_emi,initial_savings,initial_investment,investment_capacity_ratio,risk_score,risk_profile,financial_situation,...,goal_horizon_funding_actual,goal_progress_at_deadline_actual,goal_progress_at_deadline_actual_capped,goal_shortfall_actual,goal_achieved_on_time_actual,goal_shortfall_severity,goal_outcome,goal_funding_ratio,goal_funding_ratio_capped,goal_shortfall_ratio
0,USER_00001,51351.335334,36870.0,0.000000,178733.652470,45777.548120,0.282005,0.710500,aggressive,moderate_saving,...,5.811302e+05,5.037660,1.000000,0.000000,True,no_shortfall,success,5.037660,1.000000,0.000000
1,USER_00002,26415.417334,27500.0,11814.371436,13659.350863,0.000000,0.000000,0.038363,conservative,financial_stress,...,0.000000e+00,0.000000,0.000000,59340.387689,False,severe_shortfall,failure,0.000000,0.000000,1.000000
2,USER_00003,44467.548430,42000.0,0.000000,85318.549015,0.000000,0.055491,0.505350,moderate,low_saving,...,4.093773e+04,0.409815,0.409815,58955.510123,False,mild_shortfall,failure,0.409815,0.409815,0.590185
3,USER_00004,33598.333991,25500.0,7052.590854,107702.527041,60534.274631,0.031125,0.313650,conservative,moderate_saving,...,4.566919e+04,0.605080,0.605080,29807.117161,False,mild_shortfall,failure,0.605080,0.605080,0.394920
4,USER_00005,91719.010189,51000.0,0.000000,205810.045973,105774.934379,0.443954,0.750750,aggressive,high_saving,...,7.318348e+06,35.519005,1.000000,0.000000,True,no_shortfall,success,35.519005,1.000000,0.000000
5,USER_00006,49096.549442,27000.0,0.000000,229003.169045,118987.882781,0.450063,0.823150,aggressive,high_saving,...,3.502230e+05,3.175418,1.000000,0.000000,True,no_shortfall,success,3.175418,1.000000,0.000000
6,USER_00007,56988.382060,30000.0,0.000000,126015.560330,90329.680595,0.473577,0.762325,aggressive,high_saving,...,2.348219e+06,18.342532,1.000000,0.000000,True,no_shortfall,success,18.342532,1.000000,0.000000
7,USER_00008,120153.382912,100000.0,24786.376525,26481.524416,0.000000,0.000000,0.087587,conservative,low_saving,...,0.000000e+00,0.000000,0.000000,269916.171830,False,severe_shortfall,failure,0.000000,0.000000,1.000000
8,USER_00009,81284.850834,54000.0,0.000000,165575.931991,0.000000,0.335670,0.688500,aggressive,moderate_saving,...,1.616717e+06,8.853834,1.000000,0.000000,True,no_shortfall,success,8.853834,1.000000,0.000000
9,USER_00010,43047.201045,38000.0,0.000000,76879.539877,15171.499059,0.117248,0.533300,moderate,low_saving,...,5.423986e+04,0.560894,0.560894,42462.667060,False,mild_shortfall,failure,0.560894,0.560894,0.439106

===== 15.2 Complete =====

In [161]:
# 15.3. Extract Final Financial State from Monthly Simulation

print("===== EXTRACTING FINAL FINANCIAL STATE =====")


# ---------------------------------------------------------
# 1. Identify the final simulation month
# ---------------------------------------------------------

last_period = (
    monthly_financial_simulation["period"]
    .max()
)

print("Final simulation period:", last_period)


# ---------------------------------------------------------
# 2. Extract final-month records
# ---------------------------------------------------------

final_month_simulation = (
    monthly_financial_simulation[
        monthly_financial_simulation["period"] == last_period
    ]
    .copy()
)


# ---------------------------------------------------------
# 3. Select final-state variables
# ---------------------------------------------------------

final_state_columns = [
    "user_id",
    "monthly_income_dynamic",
    "monthly_expenditure_dynamic",
    "monthly_surplus_dynamic",
    "monthly_emi",
    "savings_balance",
    "portfolio_value",
    "total_financial_wealth",
    "portfolio_wealth_ratio",
    "savings_balance_status",
    "cash_flow_status",
    "unfunded_deficit"
]

final_state_dataset = (
    final_month_simulation[
        final_state_columns
    ]
    .copy()
)


# ---------------------------------------------------------
# 4. Rename variables to indicate final state
# ---------------------------------------------------------

final_state_dataset = final_state_dataset.rename(
    columns={
        "monthly_income_dynamic":
            "final_monthly_income",

        "monthly_expenditure_dynamic":
            "final_monthly_expenditure",

        "monthly_surplus_dynamic":
            "final_monthly_surplus",

        "monthly_emi":
            "final_monthly_emi",

        "savings_balance":
            "final_savings_balance",

        "portfolio_value":
            "final_portfolio_value",

        "total_financial_wealth":
            "final_total_financial_wealth",

        "portfolio_wealth_ratio":
            "final_portfolio_wealth_ratio",

        "savings_balance_status":
            "final_savings_status",

        "cash_flow_status":
            "final_cash_flow_status",

        "unfunded_deficit":
            "final_unfunded_deficit"
    }
)


# ---------------------------------------------------------
# 5. Validate one row per user
# ---------------------------------------------------------

print("\n===== FINAL STATE VALIDATION =====")

print(
    "Rows:",
    len(final_state_dataset)
)

print(
    "Unique users:",
    final_state_dataset["user_id"].nunique()
)

print(
    "Duplicate user IDs:",
    final_state_dataset[
        "user_id"
    ].duplicated().sum()
)

print(
    "Missing values:",
    final_state_dataset.isna().sum().sum()
)


# ---------------------------------------------------------
# 6. Display summary
# ---------------------------------------------------------

print("\n===== FINAL FINANCIAL STATE SUMMARY =====")

display(
    final_state_dataset[
        [
            "final_monthly_income",
            "final_monthly_expenditure",
            "final_monthly_surplus",
            "final_savings_balance",
            "final_portfolio_value",
            "final_total_financial_wealth",
            "final_portfolio_wealth_ratio",
            "final_unfunded_deficit"
        ]
    ].describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)


# ---------------------------------------------------------
# 7. Display sample
# ---------------------------------------------------------

print("\n===== SAMPLE FINAL FINANCIAL STATES =====")

display(
    final_state_dataset.head(10)
)


print("\n===== 15.3 Complete =====")

===== EXTRACTING FINAL FINANCIAL STATE =====
Final simulation period: 2026-12-01 00:00:00

===== FINAL STATE VALIDATION =====
Rows: 10000
Unique users: 10000
Duplicate user IDs: 0
Missing values: 0

===== FINAL FINANCIAL STATE SUMMARY =====

,final_monthly_income,final_monthly_expenditure,final_monthly_surplus,final_savings_balance,final_portfolio_value,final_total_financial_wealth,final_portfolio_wealth_ratio,final_unfunded_deficit
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,1.000000e+04
mean,1.710471e+05,1.248977e+05,4.095391e+04,3.703610e+06,1.159036e+05,3.819514e+06,0.049856,1.260487e+05
std,1.497191e+05,1.045160e+05,5.498329e+04,4.997736e+06,2.626814e+05,5.196515e+06,0.166929,6.066088e+05
min,3.491966e+03,2.360675e+03,-2.102942e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
10%,6.070708e+04,4.582487e+04,1.478813e+03,0.000000e+00,0.000000e+00,3.501316e+02,0.000000,0.000000e+00
25%,8.888745e+04,6.665436e+04,1.059199e+04,8.055944e+05,0.000000e+00,8.178118e+05,0.000000,0.000000e+00
50%,1.326713e+05,9.928723e+04,2.734875e+04,2.346685e+06,1.345802e+04,2.407304e+06,0.011903,0.000000e+00
75%,1.972224e+05,1.425195e+05,5.308667e+04,4.794795e+06,1.274513e+05,4.924234e+06,0.039663,0.000000e+00
90%,3.106754e+05,2.249585e+05,9.252935e+04,8.415756e+06,3.399203e+05,8.699641e+06,0.064327,2.038133e+05
95%,4.306498e+05,3.082764e+05,1.301457e+05,1.189619e+07,5.230804e+05,1.220594e+07,0.087744,7.673434e+05
max,2.349547e+06,1.473339e+06,1.114664e+06,1.052729e+08,9.121935e+06,1.143948e+08,1.000000,2.596801e+07

===== SAMPLE FINAL FINANCIAL STATES =====

,user_id,final_monthly_income,final_monthly_expenditure,final_monthly_surplus,final_monthly_emi,final_savings_balance,final_portfolio_value,final_total_financial_wealth,final_portfolio_wealth_ratio,final_savings_status,final_cash_flow_status,final_unfunded_deficit
142,USER_00001,142616.270847,102397.763796,40218.507051,0.000000,3.798640e+06,95298.759053,3.893939e+06,0.024474,positive,surplus,0.000000e+00
285,USER_00002,73362.616348,76374.789921,-14826.545009,11814.371436,0.000000e+00,0.000000,0.000000e+00,0.000000,depleted,deficit,1.946909e+06
428,USER_00003,123498.169804,116645.133698,6853.036106,0.000000,7.021328e+05,0.000000,7.021328e+05,0.000000,positive,surplus,0.000000e+00
571,USER_00004,93311.480008,70820.259745,15438.629409,7052.590854,1.123526e+06,85296.198075,1.208823e+06,0.070561,positive,surplus,0.000000e+00
714,USER_00005,254728.004908,141640.519490,113087.485418,0.000000,1.038436e+07,228458.998450,1.061282e+07,0.021527,positive,surplus,0.000000e+00
857,USER_00006,136354.132709,74986.157377,61367.975332,0.000000,5.752488e+06,274237.112721,6.026725e+06,0.045504,positive,surplus,0.000000e+00
1000,USER_00007,158271.843919,83317.952641,74953.891278,0.000000,6.872314e+06,197157.391015,7.069472e+06,0.027889,positive,surplus,0.000000e+00
1143,USER_00008,333697.795571,277726.508804,31184.910241,24786.376525,1.519781e+06,0.000000,1.519781e+06,0.000000,positive,surplus,0.000000e+00
1286,USER_00009,225749.578407,149972.314754,75777.263653,0.000000,6.985983e+06,0.000000,6.985983e+06,0.000000,positive,surplus,0.000000e+00
1429,USER_00010,119553.488600,105536.073346,14017.415255,0.000000,1.338531e+06,26694.224964,1.365225e+06,0.019553,positive,surplus,0.000000e+00

===== 15.3 Complete =====

In [162]:
# 15.4. Create Final Optimisation Input Dataset

print("===== CREATING FINAL OPTIMISATION INPUT DATASET =====")


# ---------------------------------------------------------
# 1. Select final user-level financial and goal variables
# ---------------------------------------------------------

optimisation_input_columns = [

    # User identification
    "user_id",

    # Initial financial state
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",

    # Financial classification
    "financial_situation",
    "risk_score",
    "risk_profile",

    # Goal characteristics
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "target_to_annual_income_ratio",
    "target_to_savings_ratio",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",

    # Final simulated financial state
    "final_monthly_income",
    "final_monthly_expenditure",
    "final_monthly_surplus",
    "final_monthly_emi",
    "final_savings_balance",
    "final_portfolio_value",
    "final_total_financial_wealth",
    "final_portfolio_wealth_ratio",
    "final_savings_status",
    "final_cash_flow_status",
    "final_unfunded_deficit",

    # Goal outcome
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual",
    "goal_shortfall_severity",
    "goal_outcome",
    "goal_funding_ratio",
    "goal_funding_ratio_capped",
    "goal_shortfall_ratio"
]


# ---------------------------------------------------------
# 2. Combine the user-level datasets
# ---------------------------------------------------------

optimisation_input_dataset = (
    final_simulation_dataset[
        [
            "user_id",
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "initial_savings",
            "initial_investment",
            "investment_capacity_ratio",
            "financial_situation",
            "risk_score",
            "risk_profile",
            "goal_horizon_months",
            "goal_horizon_type",
            "target_amount",
            "target_to_annual_income_ratio",
            "target_to_savings_ratio",
            "goal_specific_monthly_capacity",
            "goal_allocation_factor",
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_progress_at_deadline_actual_capped",
            "goal_shortfall_actual",
            "goal_achieved_on_time_actual",
            "goal_shortfall_severity",
            "goal_outcome",
            "goal_funding_ratio",
            "goal_funding_ratio_capped",
            "goal_shortfall_ratio"
        ]
    ]
    .merge(
        final_state_dataset,
        on="user_id",
        how="left",
        validate="one_to_one"
    )
)


# ---------------------------------------------------------
# 3. Arrange columns in the desired order
# ---------------------------------------------------------

optimisation_input_dataset = (
    optimisation_input_dataset[
        optimisation_input_columns
    ]
)


# ---------------------------------------------------------
# 4. Validate dataset dimensions
# ---------------------------------------------------------

print("\n===== DATASET DIMENSIONS =====")

print(
    "Rows:",
    len(optimisation_input_dataset)
)

print(
    "Columns:",
    len(optimisation_input_dataset.columns)
)

print(
    "Unique users:",
    optimisation_input_dataset[
        "user_id"
    ].nunique()
)

print(
    "Duplicate user IDs:",
    optimisation_input_dataset[
        "user_id"
    ].duplicated().sum()
)


# ---------------------------------------------------------
# 5. Validate missing values
# ---------------------------------------------------------

print("\n===== MISSING VALUE CHECK =====")

missing_values = (
    optimisation_input_dataset
    .isna()
    .sum()
)

print(
    "Total missing values:",
    missing_values.sum()
)

if missing_values.sum() > 0:
    print("\nColumns containing missing values:")
    print(
        missing_values[
            missing_values > 0
        ]
    )


# ---------------------------------------------------------
# 6. Validate goal outcome consistency
# ---------------------------------------------------------

print("\n===== GOAL OUTCOME VALIDATION =====")

success_count = (
    optimisation_input_dataset[
        "goal_achieved_on_time_actual"
    ].sum()
)

failure_count = (
    len(optimisation_input_dataset)
    - success_count
)

print(
    "Successful goals:",
    success_count
)

print(
    "Failed goals:",
    failure_count
)

print(
    "Success rate:",
    round(
        success_count /
        len(optimisation_input_dataset) *
        100,
        2
    ),
    "%"
)


# ---------------------------------------------------------
# 7. Validate numerical constraints
# ---------------------------------------------------------

print("\n===== NUMERICAL VALIDATION =====")

print(
    "Negative target amounts:",
    (
        optimisation_input_dataset[
            "target_amount"
        ] < 0
    ).sum()
)

print(
    "Negative goal funding:",
    (
        optimisation_input_dataset[
            "goal_horizon_funding_actual"
        ] < 0
    ).sum()
)

print(
    "Negative shortfalls:",
    (
        optimisation_input_dataset[
            "goal_shortfall_actual"
        ] < 0
    ).sum()
)

print(
    "Invalid capped funding ratios:",
    (
        (
            optimisation_input_dataset[
                "goal_funding_ratio_capped"
            ] < 0
        )
        |
        (
            optimisation_input_dataset[
                "goal_funding_ratio_capped"
            ] > 1
        )
    ).sum()
)

print(
    "Invalid shortfall ratios:",
    (
        (
            optimisation_input_dataset[
                "goal_shortfall_ratio"
            ] < 0
        )
        |
        (
            optimisation_input_dataset[
                "goal_shortfall_ratio"
            ] > 1
        )
    ).sum()
)


# ---------------------------------------------------------
# 8. Display final dataset structure
# ---------------------------------------------------------

print("\n===== FINAL OPTIMISATION INPUT COLUMNS =====")

for i, column in enumerate(
    optimisation_input_dataset.columns,
    start=1
):
    print(
        f"{i:02d}. {column}"
    )


# ---------------------------------------------------------
# 9. Display sample records
# ---------------------------------------------------------

print("\n===== SAMPLE OPTIMISATION INPUT RECORDS =====")

display(
    optimisation_input_dataset.head(10)
)


print("\n===== 15.4 Complete =====")

===== CREATING FINAL OPTIMISATION INPUT DATASET =====

===== DATASET DIMENSIONS =====
Rows: 10000
Columns: 38
Unique users: 10000
Duplicate user IDs: 0

===== MISSING VALUE CHECK =====
Total missing values: 0

===== GOAL OUTCOME VALIDATION =====
Successful goals: 6451
Failed goals: 3549
Success rate: 64.51 %

===== NUMERICAL VALIDATION =====
Negative target amounts: 0
Negative goal funding: 0
Negative shortfalls: 0
Invalid capped funding ratios: 0
Invalid shortfall ratios: 0

===== FINAL OPTIMISATION INPUT COLUMNS =====
01. user_id
02. monthly_income
03. monthly_expenditure
04. monthly_emi
05. initial_savings
06. initial_investment
07. investment_capacity_ratio
08. financial_situation
09. risk_score
10. risk_profile
11. goal_horizon_months
12. goal_horizon_type
13. target_amount
14. target_to_annual_income_ratio
15. target_to_savings_ratio
16. goal_specific_monthly_capacity
17. goal_allocation_factor
18. final_monthly_income
19. final_monthly_expenditure
20. final_monthly_surplus
21. final_monthly_emi
22. final_savings_balance
23. final_portfolio_value
24. final_total_financial_wealth
25. final_portfolio_wealth_ratio
26. final_savings_status
27. final_cash_flow_status
28. final_unfunded_deficit
29. goal_horizon_funding_actual
30. goal_progress_at_deadline_actual
31. goal_progress_at_deadline_actual_capped
32. goal_shortfall_actual
33. goal_achieved_on_time_actual
34. goal_shortfall_severity
35. goal_outcome
36. goal_funding_ratio
37. goal_funding_ratio_capped
38. goal_shortfall_ratio

===== SAMPLE OPTIMISATION INPUT RECORDS =====

,user_id,monthly_income,monthly_expenditure,monthly_emi,initial_savings,initial_investment,investment_capacity_ratio,financial_situation,risk_score,risk_profile,...,goal_horizon_funding_actual,goal_progress_at_deadline_actual,goal_progress_at_deadline_actual_capped,goal_shortfall_actual,goal_achieved_on_time_actual,goal_shortfall_severity,goal_outcome,goal_funding_ratio,goal_funding_ratio_capped,goal_shortfall_ratio
0,USER_00001,51351.335334,36870.0,0.000000,178733.652470,45777.548120,0.282005,moderate_saving,0.710500,aggressive,...,5.811302e+05,5.037660,1.000000,0.000000,True,no_shortfall,success,5.037660,1.000000,0.000000
1,USER_00002,26415.417334,27500.0,11814.371436,13659.350863,0.000000,0.000000,financial_stress,0.038363,conservative,...,0.000000e+00,0.000000,0.000000,59340.387689,False,severe_shortfall,failure,0.000000,0.000000,1.000000
2,USER_00003,44467.548430,42000.0,0.000000,85318.549015,0.000000,0.055491,low_saving,0.505350,moderate,...,4.093773e+04,0.409815,0.409815,58955.510123,False,mild_shortfall,failure,0.409815,0.409815,0.590185
3,USER_00004,33598.333991,25500.0,7052.590854,107702.527041,60534.274631,0.031125,moderate_saving,0.313650,conservative,...,4.566919e+04,0.605080,0.605080,29807.117161,False,mild_shortfall,failure,0.605080,0.605080,0.394920
4,USER_00005,91719.010189,51000.0,0.000000,205810.045973,105774.934379,0.443954,high_saving,0.750750,aggressive,...,7.318348e+06,35.519005,1.000000,0.000000,True,no_shortfall,success,35.519005,1.000000,0.000000
5,USER_00006,49096.549442,27000.0,0.000000,229003.169045,118987.882781,0.450063,high_saving,0.823150,aggressive,...,3.502230e+05,3.175418,1.000000,0.000000,True,no_shortfall,success,3.175418,1.000000,0.000000
6,USER_00007,56988.382060,30000.0,0.000000,126015.560330,90329.680595,0.473577,high_saving,0.762325,aggressive,...,2.348219e+06,18.342532,1.000000,0.000000,True,no_shortfall,success,18.342532,1.000000,0.000000
7,USER_00008,120153.382912,100000.0,24786.376525,26481.524416,0.000000,0.000000,low_saving,0.087587,conservative,...,0.000000e+00,0.000000,0.000000,269916.171830,False,severe_shortfall,failure,0.000000,0.000000,1.000000
8,USER_00009,81284.850834,54000.0,0.000000,165575.931991,0.000000,0.335670,moderate_saving,0.688500,aggressive,...,1.616717e+06,8.853834,1.000000,0.000000,True,no_shortfall,success,8.853834,1.000000,0.000000
9,USER_00010,43047.201045,38000.0,0.000000,76879.539877,15171.499059,0.117248,low_saving,0.533300,moderate,...,5.423986e+04,0.560894,0.560894,42462.667060,False,mild_shortfall,failure,0.560894,0.560894,0.439106

===== 15.4 Complete =====

In [163]:
# 15.5. Save Final Optimisation Input Dataset

print("===== SAVING FINAL OPTIMISATION INPUT DATASET =====")


# ---------------------------------------------------------
# 1. Define output directory
# ---------------------------------------------------------

optimisation_output_dir = (
    "/content/drive/MyDrive/GoalPilot_AI/"
    "simulation/06_results"
)


# ---------------------------------------------------------
# 2. Create directory if it does not exist
# ---------------------------------------------------------

os.makedirs(
    optimisation_output_dir,
    exist_ok=True
)


# ---------------------------------------------------------
# 3. Define output path
# ---------------------------------------------------------

final_optimisation_input_path = os.path.join(
    optimisation_output_dir,
    "final_optimisation_input.csv"
)


# ---------------------------------------------------------
# 4. Save dataset
# ---------------------------------------------------------

optimisation_input_dataset.to_csv(
    final_optimisation_input_path,
    index=False
)


# ---------------------------------------------------------
# 5. Verify saved file
# ---------------------------------------------------------

print("\n===== SAVE VALIDATION =====")

print(
    "File:",
    final_optimisation_input_path
)

print(
    "Rows:",
    len(optimisation_input_dataset)
)

print(
    "Columns:",
    len(optimisation_input_dataset.columns)
)

print(
    "File exists:",
    os.path.exists(
        final_optimisation_input_path
    )
)


# ---------------------------------------------------------
# 6. Check file size
# ---------------------------------------------------------

file_size_mb = (
    os.path.getsize(
        final_optimisation_input_path
    ) / (1024 ** 2)
)

print(
    "File size:",
    round(file_size_mb, 2),
    "MB"
)


# ---------------------------------------------------------
# 7. Reload and verify
# ---------------------------------------------------------

print("\n===== RELOAD VALIDATION =====")

reloaded_optimisation_input = pd.read_csv(
    final_optimisation_input_path
)

print(
    "Reloaded shape:",
    reloaded_optimisation_input.shape
)

print(
    "Reloaded unique users:",
    reloaded_optimisation_input[
        "user_id"
    ].nunique()
)

print(
    "Reloaded missing values:",
    reloaded_optimisation_input
    .isna()
    .sum()
    .sum()
)

print(
    "Reloaded duplicate users:",
    reloaded_optimisation_input[
        "user_id"
    ].duplicated()
    .sum()
)


# ---------------------------------------------------------
# 8. Final status
# ---------------------------------------------------------

save_validation_passed = (
    reloaded_optimisation_input.shape
    == optimisation_input_dataset.shape
    and
    reloaded_optimisation_input["user_id"].nunique()
    == 10000
    and
    reloaded_optimisation_input.isna().sum().sum()
    == 0
    and
    reloaded_optimisation_input["user_id"].duplicated().sum()
    == 0
)

print("\n===== FINAL SAVE STATUS =====")

if save_validation_passed:
    print("STATUS: PASSED")
else:
    print("STATUS: FAILED")


print("\n===== 15.5 Complete =====")

===== SAVING FINAL OPTIMISATION INPUT DATASET =====

===== SAVE VALIDATION =====
File: /content/drive/MyDrive/GoalPilot_AI/simulation/06_results/final_optimisation_input.csv
Rows: 10000
Columns: 38
File exists: True
File size: 4.53 MB

===== RELOAD VALIDATION =====
Reloaded shape: (10000, 38)
Reloaded unique users: 10000
Reloaded missing values: 0
Reloaded duplicate users: 0

===== FINAL SAVE STATUS =====
STATUS: PASSED

===== 15.5 Complete =====

In [164]:
# 15.6. Final Simulation Quality and Methodology Audit

print("===== FINAL SIMULATION QUALITY & METHODOLOGY AUDIT =====")


# =========================================================
# 1. BASIC DATASET VALIDATION
# =========================================================

print("\n===== 1. BASIC DATASET VALIDATION =====")

print("Rows:", len(optimisation_input_dataset))
print(
    "Unique users:",
    optimisation_input_dataset["user_id"].nunique()
)
print(
    "Duplicate users:",
    optimisation_input_dataset["user_id"].duplicated().sum()
)
print(
    "Missing values:",
    optimisation_input_dataset.isna().sum().sum()
)


# =========================================================
# 2. FINANCIAL VALUE VALIDATION
# =========================================================

print("\n===== 2. FINANCIAL VALUE VALIDATION =====")

checks = {
    "Non-positive income":
        (
            optimisation_input_dataset["monthly_income"] <= 0
        ).sum(),

    "Non-positive expenditure":
        (
            optimisation_input_dataset["monthly_expenditure"] <= 0
        ).sum(),

    "Negative EMI":
        (
            optimisation_input_dataset["monthly_emi"] < 0
        ).sum(),

    "Negative initial savings":
        (
            optimisation_input_dataset["initial_savings"] < 0
        ).sum(),

    "Negative initial investment":
        (
            optimisation_input_dataset["initial_investment"] < 0
        ).sum(),

    "Negative final savings":
        (
            optimisation_input_dataset["final_savings_balance"] < 0
        ).sum(),

    "Negative final portfolio":
        (
            optimisation_input_dataset["final_portfolio_value"] < 0
        ).sum(),

    "Negative final wealth":
        (
            optimisation_input_dataset["final_total_financial_wealth"] < 0
        ).sum(),

    "Negative goal target":
        (
            optimisation_input_dataset["target_amount"] <= 0
        ).sum(),

    "Negative goal funding":
        (
            optimisation_input_dataset["goal_horizon_funding_actual"] < 0
        ).sum(),

    "Negative goal shortfall":
        (
            optimisation_input_dataset["goal_shortfall_actual"] < 0
        ).sum()
}

for check_name, count in checks.items():
    print(f"{check_name}: {count}")


# =========================================================
# 3. RATIO VALIDATION
# =========================================================

print("\n===== 3. RATIO VALIDATION =====")

ratio_checks = {
    "Investment capacity below 0":
        (
            optimisation_input_dataset[
                "investment_capacity_ratio"
            ] < 0
        ).sum(),

    "Investment capacity above 1":
        (
            optimisation_input_dataset[
                "investment_capacity_ratio"
            ] > 1
        ).sum(),

    "Risk score below 0":
        (
            optimisation_input_dataset["risk_score"] < 0
        ).sum(),

    "Risk score above 1":
        (
            optimisation_input_dataset["risk_score"] > 1
        ).sum(),

    "Portfolio wealth ratio below 0":
        (
            optimisation_input_dataset[
                "final_portfolio_wealth_ratio"
            ] < 0
        ).sum(),

    "Portfolio wealth ratio above 1":
        (
            optimisation_input_dataset[
                "final_portfolio_wealth_ratio"
            ] > 1
        ).sum(),

    "Funding ratio below 0":
        (
            optimisation_input_dataset[
                "goal_funding_ratio"
            ] < 0
        ).sum(),

    "Shortfall ratio below 0":
        (
            optimisation_input_dataset[
                "goal_shortfall_ratio"
            ] < 0
        ).sum(),

    "Shortfall ratio above 1":
        (
            optimisation_input_dataset[
                "goal_shortfall_ratio"
            ] > 1
        ).sum()
}

for check_name, count in ratio_checks.items():
    print(f"{check_name}: {count}")


# =========================================================
# 4. EMI AFFORDABILITY CHECK
# =========================================================

print("\n===== 4. EMI AFFORDABILITY CHECK =====")

emi_exceeds_income = (
    optimisation_input_dataset["monthly_emi"]
    >
    optimisation_input_dataset["monthly_income"]
).sum()

print(
    "Users where EMI exceeds monthly income:",
    emi_exceeds_income
)


# =========================================================
# 5. GOAL OUTCOME LOGICAL CONSISTENCY
# =========================================================

print("\n===== 5. GOAL OUTCOME LOGICAL CONSISTENCY =====")

successful_with_shortfall = (
    (
        optimisation_input_dataset[
            "goal_achieved_on_time_actual"
        ]
        == True
    )
    &
    (
        optimisation_input_dataset[
            "goal_shortfall_actual"
        ] > 0
    )
).sum()

failed_without_shortfall = (
    (
        optimisation_input_dataset[
            "goal_achieved_on_time_actual"
        ]
        == False
    )
    &
    (
        optimisation_input_dataset[
            "goal_shortfall_actual"
        ] <= 0
    )
).sum()

print(
    "Successful goals with positive shortfall:",
    successful_with_shortfall
)

print(
    "Failed goals without positive shortfall:",
    failed_without_shortfall
)


# =========================================================
# 6. VALID CATEGORY VALUES
# =========================================================

print("\n===== 6. CATEGORY VALIDATION =====")

expected_financial_situations = {
    "high_saving",
    "moderate_saving",
    "low_saving",
    "financial_stress"
}

expected_risk_profiles = {
    "conservative",
    "moderate",
    "aggressive"
}

expected_horizons = {
    "immediate",
    "short_term",
    "medium_term",
    "long_term"
}

expected_outcomes = {
    "success",
    "failure"
}

expected_severity = {
    "no_shortfall",
    "mild_shortfall",
    "moderate_shortfall",
    "severe_shortfall"
}

print(
    "Invalid financial situations:",
    set(
        optimisation_input_dataset[
            "financial_situation"
        ].dropna().unique()
    )
    -
    expected_financial_situations
)

print(
    "Invalid risk profiles:",
    set(
        optimisation_input_dataset[
            "risk_profile"
        ].dropna().unique()
    )
    -
    expected_risk_profiles
)

print(
    "Invalid goal horizons:",
    set(
        optimisation_input_dataset[
            "goal_horizon_type"
        ].dropna().unique()
    )
    -
    expected_horizons
)

print(
    "Invalid goal outcomes:",
    set(
        optimisation_input_dataset[
            "goal_outcome"
        ].dropna().unique()
    )
    -
    expected_outcomes
)

print(
    "Invalid shortfall severity:",
    set(
        optimisation_input_dataset[
            "goal_shortfall_severity"
        ].dropna().unique()
    )
    -
    expected_severity
)


# =========================================================
# 7. FINANCIAL SITUATION RELATIONSHIP CHECK
# =========================================================

print("\n===== 7. FINANCIAL SITUATION RELATIONSHIP CHECK =====")

financial_summary = (
    optimisation_input_dataset
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        median_income=("monthly_income", "median"),
        median_expenditure=("monthly_expenditure", "median"),
        median_savings=("initial_savings", "median"),
        median_investment=("initial_investment", "median"),
        goal_success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        )
    )
)

display(financial_summary)


# =========================================================
# 8. RISK PROFILE RELATIONSHIP CHECK
# =========================================================

print("\n===== 8. RISK PROFILE RELATIONSHIP CHECK =====")

risk_summary = (
    optimisation_input_dataset
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        median_risk_score=("risk_score", "median"),
        median_investment_capacity=(
            "investment_capacity_ratio",
            "median"
        ),
        median_initial_investment=(
            "initial_investment",
            "median"
        ),
        goal_success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        )
    )
)

display(risk_summary)


# =========================================================
# 9. GOAL HORIZON RELATIONSHIP CHECK
# =========================================================

print("\n===== 9. GOAL HORIZON RELATIONSHIP CHECK =====")

horizon_summary = (
    optimisation_input_dataset
    .groupby("goal_horizon_type")
    .agg(
        users=("user_id", "count"),
        median_horizon_months=(
            "goal_horizon_months",
            "median"
        ),
        median_target=(
            "target_amount",
            "median"
        ),
        median_goal_funding=(
            "goal_horizon_funding_actual",
            "median"
        ),
        goal_success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        )
    )
)

display(horizon_summary)


# =========================================================
# 10. FINAL STATUS
# =========================================================

print("\n===== FINAL AUDIT STATUS =====")

technical_failures = (
    sum(checks.values())
    + sum(ratio_checks.values())
    + emi_exceeds_income
    + successful_with_shortfall
    + failed_without_shortfall
)

category_failures = (
    len(
        set(
            optimisation_input_dataset[
                "financial_situation"
            ].dropna().unique()
        )
        -
        expected_financial_situations
    )
    +
    len(
        set(
            optimisation_input_dataset[
                "risk_profile"
            ].dropna().unique()
        )
        -
        expected_risk_profiles
    )
    +
    len(
        set(
            optimisation_input_dataset[
                "goal_horizon_type"
            ].dropna().unique()
        )
        -
        expected_horizons
    )
    +
    len(
        set(
            optimisation_input_dataset[
                "goal_outcome"
            ].dropna().unique()
        )
        -
        expected_outcomes
    )
    +
    len(
        set(
            optimisation_input_dataset[
                "goal_shortfall_severity"
            ].dropna().unique()
        )
        -
        expected_severity
    )
)

if (
    technical_failures == 0
    and category_failures == 0
):
    print("STATUS: PASSED")
else:
    print("STATUS: REVIEW REQUIRED")

print("\n===== 15.6 Complete =====")

===== FINAL SIMULATION QUALITY & METHODOLOGY AUDIT =====

===== 1. BASIC DATASET VALIDATION =====
Rows: 10000
Unique users: 10000
Duplicate users: 0
Missing values: 0

===== 2. FINANCIAL VALUE VALIDATION =====
Non-positive income: 0
Non-positive expenditure: 0
Negative EMI: 0
Negative initial savings: 0
Negative initial investment: 0
Negative final savings: 0
Negative final portfolio: 0
Negative final wealth: 0
Negative goal target: 0
Negative goal funding: 0
Negative goal shortfall: 0

===== 3. RATIO VALIDATION =====
Investment capacity below 0: 0
Investment capacity above 1: 0
Risk score below 0: 0
Risk score above 1: 0
Portfolio wealth ratio below 0: 0
Portfolio wealth ratio above 1: 0
Funding ratio below 0: 0
Shortfall ratio below 0: 0
Shortfall ratio above 1: 0

===== 4. EMI AFFORDABILITY CHECK =====
Users where EMI exceeds monthly income: 0

===== 5. GOAL OUTCOME LOGICAL CONSISTENCY =====
Successful goals with positive shortfall: 0
Failed goals without positive shortfall: 0

===== 6. CATEGORY VALIDATION =====
Invalid financial situations: set()
Invalid risk profiles: set()
Invalid goal horizons: set()
Invalid goal outcomes: set()
Invalid shortfall severity: set()

===== 7. FINANCIAL SITUATION RELATIONSHIP CHECK =====

,users,median_income,median_expenditure,median_savings,median_investment,goal_success_rate
financial_situation,,,,,,
financial_stress,474,34318.040553,35000.0,25115.005270,0.000000,0.000000
high_saving,2043,61917.549255,35000.0,255991.483135,129541.343241,0.977974
low_saving,2923,40566.248112,36000.0,52257.372560,0.000000,0.322956
moderate_saving,4560,49010.663934,35500.0,118085.160533,20311.696770,0.769518

===== 8. RISK PROFILE RELATIONSHIP CHECK =====

,users,median_risk_score,median_investment_capacity,median_initial_investment,goal_success_rate
risk_profile,,,,,
aggressive,3333,0.728550,0.338758,71125.627652,0.959196
conservative,3333,0.216587,0.000000,0.000000,0.216322
moderate,3334,0.540337,0.185813,2157.862355,0.759748

===== 9. GOAL HORIZON RELATIONSHIP CHECK =====

/tmp/ipykernel_1336/1351948085.py:387: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("goal_horizon_type")

,users,median_horizon_months,median_target,median_goal_funding,goal_success_rate
goal_horizon_type,,,,,
immediate,91,6.0,122930.537375,20121.874303,0.065934
short_term,2669,21.0,106875.607038,83959.234680,0.458973
medium_term,3081,55.0,105663.701050,250115.776529,0.673807
long_term,4159,97.0,108145.545245,578143.368349,0.755951

===== FINAL AUDIT STATUS =====
STATUS: PASSED

===== 15.6 Complete =====

In [165]:
# 15.7. Create Final Simulation Summary Report

print("===== FINAL SIMULATION SUMMARY REPORT =====")


# =========================================================
# 1. BASIC SIMULATION INFORMATION
# =========================================================

simulation_start = monthly_financial_simulation["period"].min()
simulation_end = monthly_financial_simulation["period"].max()

summary = {
    "simulation_users":
        optimisation_input_dataset["user_id"].nunique(),

    "simulation_months":
        monthly_financial_simulation["period"].nunique(),

    "simulation_start":
        simulation_start,

    "simulation_end":
        simulation_end,

    "monthly_simulation_records":
        len(monthly_financial_simulation),

    "final_user_level_records":
        len(optimisation_input_dataset)
}


# =========================================================
# 2. FINANCIAL PROFILE SUMMARY
# =========================================================

summary.update({
    "median_monthly_income":
        optimisation_input_dataset[
            "monthly_income"
        ].median(),

    "median_monthly_expenditure":
        optimisation_input_dataset[
            "monthly_expenditure"
        ].median(),

    "median_initial_savings":
        optimisation_input_dataset[
            "initial_savings"
        ].median(),

    "median_initial_investment":
        optimisation_input_dataset[
            "initial_investment"
        ].median()
})


# =========================================================
# 3. RISK PROFILE SUMMARY
# =========================================================

risk_counts = (
    optimisation_input_dataset[
        "risk_profile"
    ]
    .value_counts()
)

summary.update({
    "conservative_users":
        risk_counts.get("conservative", 0),

    "moderate_risk_users":
        risk_counts.get("moderate", 0),

    "aggressive_users":
        risk_counts.get("aggressive", 0)
})


# =========================================================
# 4. FINANCIAL SITUATION SUMMARY
# =========================================================

financial_counts = (
    optimisation_input_dataset[
        "financial_situation"
    ]
    .value_counts()
)

summary.update({
    "high_saving_users":
        financial_counts.get("high_saving", 0),

    "moderate_saving_users":
        financial_counts.get("moderate_saving", 0),

    "low_saving_users":
        financial_counts.get("low_saving", 0),

    "financial_stress_users":
        financial_counts.get("financial_stress", 0)
})


# =========================================================
# 5. GOAL SUMMARY
# =========================================================

goal_success_count = (
    optimisation_input_dataset[
        "goal_achieved_on_time_actual"
    ].sum()
)

goal_failure_count = (
    len(optimisation_input_dataset)
    - goal_success_count
)

summary.update({
    "successful_goals":
        int(goal_success_count),

    "failed_goals":
        int(goal_failure_count),

    "goal_success_rate":
        goal_success_count /
        len(optimisation_input_dataset),

    "median_goal_target":
        optimisation_input_dataset[
            "target_amount"
        ].median(),

    "median_goal_horizon_months":
        optimisation_input_dataset[
            "goal_horizon_months"
        ].median(),

    "median_goal_horizon_funding":
        optimisation_input_dataset[
            "goal_horizon_funding_actual"
        ].median(),

    "median_goal_shortfall":
        optimisation_input_dataset[
            "goal_shortfall_actual"
        ].median()
})


# =========================================================
# 6. FINAL WEALTH SUMMARY
# =========================================================

summary.update({
    "median_final_savings":
        optimisation_input_dataset[
            "final_savings_balance"
        ].median(),

    "median_final_portfolio":
        optimisation_input_dataset[
            "final_portfolio_value"
        ].median(),

    "median_final_total_financial_wealth":
        optimisation_input_dataset[
            "final_total_financial_wealth"
        ].median(),

    "median_final_portfolio_share":
        optimisation_input_dataset[
            "final_portfolio_wealth_ratio"
        ].median()
})


# =========================================================
# 7. SHORTFALL SUMMARY
# =========================================================

failed_goals = optimisation_input_dataset[
    optimisation_input_dataset[
        "goal_outcome"
    ] == "failure"
]

summary.update({
    "failed_goal_count":
        len(failed_goals),

    "median_failed_goal_shortfall":
        failed_goals[
            "goal_shortfall_actual"
        ].median()
        if len(failed_goals) > 0
        else 0,

    "mean_failed_goal_shortfall":
        failed_goals[
            "goal_shortfall_actual"
        ].mean()
        if len(failed_goals) > 0
        else 0
})


# =========================================================
# 8. PRINT SUMMARY
# =========================================================

print("\n===== SIMULATION OVERVIEW =====")

for key, value in summary.items():

    if isinstance(value, (float, np.floating)):
        print(
            f"{key}: {value:,.4f}"
        )
    else:
        print(
            f"{key}: {value}"
        )


# =========================================================
# 9. HORIZON SUCCESS SUMMARY
# =========================================================

print("\n===== GOAL SUCCESS BY HORIZON =====")

horizon_summary_final = (
    optimisation_input_dataset
    .groupby("goal_horizon_type", observed=False)
    .agg(
        users=("user_id", "count"),
        successful_goals=(
            "goal_achieved_on_time_actual",
            "sum"
        ),
        success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        ),
        median_target=(
            "target_amount",
            "median"
        ),
        median_funding=(
            "goal_horizon_funding_actual",
            "median"
        )
    )
)

display(horizon_summary_final)


# =========================================================
# 10. RISK SUCCESS SUMMARY
# =========================================================

print("\n===== GOAL SUCCESS BY RISK PROFILE =====")

risk_summary_final = (
    optimisation_input_dataset
    .groupby("risk_profile", observed=False)
    .agg(
        users=("user_id", "count"),
        successful_goals=(
            "goal_achieved_on_time_actual",
            "sum"
        ),
        success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        ),
        median_risk_score=(
            "risk_score",
            "median"
        ),
        median_funding=(
            "goal_horizon_funding_actual",
            "median"
        )
    )
)

display(risk_summary_final)


# =========================================================
# 11. FINANCIAL SITUATION SUCCESS SUMMARY
# =========================================================

print("\n===== GOAL SUCCESS BY FINANCIAL SITUATION =====")

financial_summary_final = (
    optimisation_input_dataset
    .groupby("financial_situation", observed=False)
    .agg(
        users=("user_id", "count"),
        successful_goals=(
            "goal_achieved_on_time_actual",
            "sum"
        ),
        success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        ),
        median_income=(
            "monthly_income",
            "median"
        ),
        median_savings=(
            "initial_savings",
            "median"
        ),
        median_funding=(
            "goal_horizon_funding_actual",
            "median"
        )
    )
)

display(financial_summary_final)


print("\n===== 15.7 Complete =====")

===== FINAL SIMULATION SUMMARY REPORT =====

===== SIMULATION OVERVIEW =====
simulation_users: 10000
simulation_months: 143
simulation_start: 2015-02-01 00:00:00
simulation_end: 2026-12-01 00:00:00
monthly_simulation_records: 1430000
final_user_level_records: 10000
median_monthly_income: 47,770.4858
median_monthly_expenditure: 35,750.0000
median_initial_savings: 104,229.7015
median_initial_investment: 9,154.0549
conservative_users: 3333
moderate_risk_users: 3334
aggressive_users: 3333
high_saving_users: 2043
moderate_saving_users: 4560
low_saving_users: 2923
financial_stress_users: 474
successful_goals: 6451
failed_goals: 3549
goal_success_rate: 0.6451
median_goal_target: 107,313.0554
median_goal_horizon_months: 63.0000
median_goal_horizon_funding: 236,498.4820
median_goal_shortfall: 0.0000
median_final_savings: 2,346,684.5126
median_final_portfolio: 13,458.0159
median_final_total_financial_wealth: 2,407,303.9520
median_final_portfolio_share: 0.0119
failed_goal_count: 3549
median_failed_goal_shortfall: 66,881.7649
mean_failed_goal_shortfall: 86,166.4987

===== GOAL SUCCESS BY HORIZON =====

,users,successful_goals,success_rate,median_target,median_funding
goal_horizon_type,,,,,
immediate,91,6,0.065934,122930.537375,20121.874303
short_term,2669,1225,0.458973,106875.607038,83959.234680
medium_term,3081,2076,0.673807,105663.701050,250115.776529
long_term,4159,3144,0.755951,108145.545245,578143.368349

===== GOAL SUCCESS BY RISK PROFILE =====

,users,successful_goals,success_rate,median_risk_score,median_funding
risk_profile,,,,,
aggressive,3333,3197,0.959196,0.728550,984113.676988
conservative,3333,721,0.216322,0.216587,2497.185588
moderate,3334,2533,0.759748,0.540337,263730.053050

===== GOAL SUCCESS BY FINANCIAL SITUATION =====

,users,successful_goals,success_rate,median_income,median_savings,median_funding
financial_situation,,,,,,
financial_stress,474,0,0.000000,34318.040553,25115.005270,0.000000e+00
high_saving,2043,1998,0.977974,61917.549255,255991.483135,1.348838e+06
low_saving,2923,944,0.322956,40566.248112,52257.372560,1.568046e+04
moderate_saving,4560,3509,0.769518,49010.663934,118085.160533,3.419039e+05

===== 15.7 Complete =====

In [166]:
# 15.8. Save Final Simulation Summary

import os
import pandas as pd
import numpy as np


# =========================================================
# 1. DEFINE OUTPUT DIRECTORY
# =========================================================

summary_output_dir = (
    "/content/drive/MyDrive/GoalPilot_AI/simulation/06_results"
)

os.makedirs(summary_output_dir, exist_ok=True)


# =========================================================
# 2. CREATE OVERALL SUMMARY TABLE
# =========================================================

overall_summary = pd.DataFrame({
    "metric": list(summary.keys()),
    "value": list(summary.values())
})


# =========================================================
# 3. SAVE OVERALL SUMMARY
# =========================================================

overall_summary_path = os.path.join(
    summary_output_dir,
    "final_simulation_summary.csv"
)

overall_summary.to_csv(
    overall_summary_path,
    index=False
)


# =========================================================
# 4. SAVE HORIZON SUMMARY
# =========================================================

horizon_summary_path = os.path.join(
    summary_output_dir,
    "goal_success_by_horizon.csv"
)

horizon_summary_final.to_csv(
    horizon_summary_path
)


# =========================================================
# 5. SAVE RISK SUMMARY
# =========================================================

risk_summary_path = os.path.join(
    summary_output_dir,
    "goal_success_by_risk_profile.csv"
)

risk_summary_final.to_csv(
    risk_summary_path
)


# =========================================================
# 6. SAVE FINANCIAL SITUATION SUMMARY
# =========================================================

financial_summary_path = os.path.join(
    summary_output_dir,
    "goal_success_by_financial_situation.csv"
)

financial_summary_final.to_csv(
    financial_summary_path
)


# =========================================================
# 7. VERIFY FILES
# =========================================================

output_files = [
    overall_summary_path,
    horizon_summary_path,
    risk_summary_path,
    financial_summary_path
]

print("===== SAVED SIMULATION SUMMARY FILES =====")

for file_path in output_files:

    exists = os.path.exists(file_path)

    if exists:
        size_mb = os.path.getsize(file_path) / (1024 ** 2)

        print(
            f"{os.path.basename(file_path)} | "
            f"Exists: {exists} | "
            f"Size: {size_mb:.4f} MB"
        )
    else:
        print(
            f"{os.path.basename(file_path)} | "
            f"Exists: {exists}"
        )


# =========================================================
# 8. RELOAD AND VALIDATE OVERALL SUMMARY
# =========================================================

reloaded_summary = pd.read_csv(
    overall_summary_path
)

print("\n===== OVERALL SUMMARY VALIDATION =====")

print(
    "Rows:",
    len(reloaded_summary)
)

print(
    "Columns:",
    list(reloaded_summary.columns)
)

print(
    "Missing values:",
    reloaded_summary.isna().sum().sum()
)

print(
    "Duplicate metrics:",
    reloaded_summary["metric"].duplicated().sum()
)


# =========================================================
# 9. DISPLAY SAVED SUMMARY
# =========================================================

print("\n===== FINAL SAVED SUMMARY =====")

display(reloaded_summary)


# =========================================================
# 10. FINAL STATUS
# =========================================================

all_files_exist = all(
    os.path.exists(path)
    for path in output_files
)

summary_validation_passed = (
    all_files_exist
    and len(reloaded_summary) == len(summary)
    and reloaded_summary["metric"].is_unique
    and reloaded_summary.isna().sum().sum() == 0
)

print("\n===== 15.8 VALIDATION =====")

print(
    "All files exist:",
    all_files_exist
)

print(
    "Summary rows valid:",
    len(reloaded_summary) == len(summary)
)

print(
    "Metrics unique:",
    reloaded_summary["metric"].is_unique
)

print(
    "No missing values:",
    reloaded_summary.isna().sum().sum() == 0
)

print(
    "\nSTATUS:",
    "PASSED" if summary_validation_passed else "FAILED"
)

===== SAVED SIMULATION SUMMARY FILES =====
final_simulation_summary.csv | Exists: True | Size: 0.0010 MB
goal_success_by_horizon.csv | Exists: True | Size: 0.0004 MB
goal_success_by_risk_profile.csv | Exists: True | Size: 0.0003 MB
goal_success_by_financial_situation.csv | Exists: True | Size: 0.0004 MB

===== OVERALL SUMMARY VALIDATION =====
Rows: 31
Columns: ['metric', 'value']
Missing values: 0
Duplicate metrics: 0

===== FINAL SAVED SUMMARY =====

                                 metric                 value
0                      simulation_users                 10000
1                     simulation_months                   143
2                      simulation_start   2015-02-01 00:00:00
3                        simulation_end   2026-12-01 00:00:00
4            monthly_simulation_records               1430000
5              final_user_level_records                 10000
6                 median_monthly_income     47770.48575030218
7            median_monthly_expenditure               35750.0
8                median_initial_savings    104229.70150836353
9             median_initial_investment      9154.05485134513
10                   conservative_users                  3333
11                  moderate_risk_users                  3334
12                     aggressive_users                  3333
13                    high_saving_users                  2043
14                moderate_saving_users                  4560
15                     low_saving_users                  2923
16               financial_stress_users                   474
17                     successful_goals                  6451
18                         failed_goals                  3549
19                    goal_success_rate                0.6451
20                   median_goal_target     107313.0554274146
21           median_goal_horizon_months                  63.0
22          median_goal_horizon_funding    236498.48196910552
23                median_goal_shortfall                   0.0
24                 median_final_savings    2346684.5126413014
25               median_final_portfolio    13458.015922862642
26  median_final_total_financial_wealth     2407303.952042097
27         median_final_portfolio_share  0.011903206967491455
28                    failed_goal_count                  3549
29         median_failed_goal_shortfall     66881.76490834764
30           mean_failed_goal_shortfall     86166.49870631473

===== 15.8 VALIDATION =====
All files exist: True
Summary rows valid: True
Metrics unique: True
No missing values: True

STATUS: PASSED

In [167]:
# 15.9. Final Simulation Methodology Validation

print("===== FINAL SIMULATION METHODOLOGY VALIDATION =====")


# =========================================================
# 1. VALIDATION: FINANCIAL SITUATION VS GOAL SUCCESS
# =========================================================

financial_validation = (
    optimisation_input_dataset
    .groupby("financial_situation", observed=False)
    .agg(
        users=("user_id", "count"),
        success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        ),
        median_funding=(
            "goal_horizon_funding_actual",
            "median"
        ),
        median_shortfall=(
            "goal_shortfall_actual",
            "median"
        )
    )
)

print("\n===== 1. FINANCIAL SITUATION VS GOAL SUCCESS =====")
display(financial_validation)


# =========================================================
# 2. VALIDATION: GOAL HORIZON VS SUCCESS
# =========================================================

horizon_validation = (
    optimisation_input_dataset
    .groupby("goal_horizon_type", observed=False)
    .agg(
        users=("user_id", "count"),
        success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        ),
        median_funding=(
            "goal_horizon_funding_actual",
            "median"
        ),
        median_shortfall=(
            "goal_shortfall_actual",
            "median"
        )
    )
)

print("\n===== 2. GOAL HORIZON VS SUCCESS =====")
display(horizon_validation)


# =========================================================
# 3. VALIDATION: RISK PROFILE VS GOAL SUCCESS
# =========================================================

risk_validation = (
    optimisation_input_dataset
    .groupby("risk_profile", observed=False)
    .agg(
        users=("user_id", "count"),
        median_risk_score=(
            "risk_score",
            "median"
        ),
        median_investment=(
            "initial_investment",
            "median"
        ),
        success_rate=(
            "goal_achieved_on_time_actual",
            "mean"
        )
    )
)

print("\n===== 3. RISK PROFILE VS SUCCESS =====")
display(risk_validation)


# =========================================================
# 4. VALIDATION: RISK SCORE VS INVESTMENT CAPACITY
# =========================================================

risk_capacity_correlation = (
    optimisation_input_dataset[
        [
            "risk_score",
            "investment_capacity_ratio"
        ]
    ]
    .corr()
    .iloc[0, 1]
)

print(
    "\n===== 4. RISK SCORE VS INVESTMENT CAPACITY ====="
)

print(
    "Correlation:",
    round(risk_capacity_correlation, 6)
)


# =========================================================
# 5. VALIDATION: GOAL FUNDING ADEQUACY
# =========================================================

funding_adequacy = (
    optimisation_input_dataset[
        "goal_horizon_funding_actual"
    ]
    >=
    optimisation_input_dataset[
        "target_amount"
    ]
)

print("\n===== 5. GOAL FUNDING ADEQUACY =====")

print(
    "Goals with adequate funding:",
    int(funding_adequacy.sum())
)

print(
    "Goals with inadequate funding:",
    int((~funding_adequacy).sum())
)

print(
    "Adequacy rate:",
    round(funding_adequacy.mean(), 6)
)


# =========================================================
# 6. VALIDATION: SUCCESS / SHORTFALL CONSISTENCY
# =========================================================

success_shortfall_mismatch = (
    (
        optimisation_input_dataset[
            "goal_achieved_on_time_actual"
        ]
        &
        (
            optimisation_input_dataset[
                "goal_shortfall_actual"
            ] > 0
        )
    )
    |
    (
        ~optimisation_input_dataset[
            "goal_achieved_on_time_actual"
        ]
        &
        (
            optimisation_input_dataset[
                "goal_shortfall_actual"
            ] <= 0
        )
    )
).sum()

print(
    "\n===== 6. SUCCESS / SHORTFALL CONSISTENCY ====="
)

print(
    "Inconsistent outcomes:",
    success_shortfall_mismatch
)


# =========================================================
# 7. VALIDATION: IMPOSSIBLE VALUES
# =========================================================

impossible_checks = {
    "negative_income":
        (
            optimisation_input_dataset[
                "monthly_income"
            ] < 0
        ).sum(),

    "negative_expenditure":
        (
            optimisation_input_dataset[
                "monthly_expenditure"
            ] < 0
        ).sum(),

    "negative_savings":
        (
            optimisation_input_dataset[
                "final_savings_balance"
            ] < 0
        ).sum(),

    "negative_investment":
        (
            optimisation_input_dataset[
                "initial_investment"
            ] < 0
        ).sum(),

    "negative_goal_target":
        (
            optimisation_input_dataset[
                "target_amount"
            ] < 0
        ).sum(),

    "negative_shortfall":
        (
            optimisation_input_dataset[
                "goal_shortfall_actual"
            ] < 0
        ).sum()
}

print("\n===== 7. IMPOSSIBLE VALUE CHECK =====")

for check, count in impossible_checks.items():
    print(f"{check}: {count}")


# =========================================================
# 8. FINAL USER / RECORD VALIDATION
# =========================================================

user_count = optimisation_input_dataset[
    "user_id"
].nunique()

duplicate_users = (
    optimisation_input_dataset[
        "user_id"
    ].duplicated()
    .sum()
)

missing_values = (
    optimisation_input_dataset
    .isna()
    .sum()
    .sum()
)

print("\n===== 8. DATASET INTEGRITY =====")

print("Users:", user_count)
print("Duplicate users:", duplicate_users)
print("Missing values:", missing_values)


# =========================================================
# 9. AUTOMATED LOGICAL CHECKS
# =========================================================

financial_success_rates = (
    financial_validation[
        "success_rate"
    ]
)

horizon_success_rates = (
    horizon_validation[
        "success_rate"
    ]
)

risk_success_rates = (
    risk_validation[
        "success_rate"
    ]
)

checks = {

    # Dataset integrity
    "10k_unique_users":
        user_count == 10000,

    "no_duplicate_users":
        duplicate_users == 0,

    "no_missing_values":
        missing_values == 0,

    # Financial validity
    "no_impossible_values":
        all(
            count == 0
            for count in impossible_checks.values()
        ),

    # Goal logic
    "success_shortfall_consistent":
        success_shortfall_mismatch == 0,

    # Risk construction
    "risk_score_tracks_capacity":
        risk_capacity_correlation > 0,

    # Financial situation logic
    "high_saving_above_financial_stress":
        financial_validation.loc[
            "high_saving",
            "success_rate"
        ]
        >
        financial_validation.loc[
            "financial_stress",
            "success_rate"
        ],

    # Horizon logic
    "long_term_above_immediate":
        horizon_validation.loc[
            "long_term",
            "success_rate"
        ]
        >
        horizon_validation.loc[
            "immediate",
            "success_rate"
        ],

    # Risk logic
    "aggressive_above_conservative":
        risk_validation.loc[
            "aggressive",
            "success_rate"
        ]
        >
        risk_validation.loc[
            "conservative",
            "success_rate"
        ]
}


# =========================================================
# 10. DISPLAY VALIDATION RESULTS
# =========================================================

print("\n===== AUTOMATED VALIDATION RESULTS =====")

for check, result in checks.items():
    print(
        f"{check}:",
        "PASS" if result else "FAIL"
    )


# =========================================================
# 11. FINAL STATUS
# =========================================================

final_methodology_status = all(checks.values())

print(
    "\n===== FINAL METHODOLOGY STATUS ====="
)

print(
    "STATUS:",
    "PASSED"
    if final_methodology_status
    else "REVIEW REQUIRED"
)

===== FINAL SIMULATION METHODOLOGY VALIDATION =====

===== 1. FINANCIAL SITUATION VS GOAL SUCCESS =====

                     users  success_rate  median_funding  median_shortfall
financial_situation
financial_stress       474      0.000000    0.000000e+00      74281.113575
high_saving           2043      0.977974    1.348838e+06          0.000000
low_saving            2923      0.322956    1.568046e+04      44567.674464
moderate_saving       4560      0.769518    3.419039e+05          0.000000

===== 2. GOAL HORIZON VS SUCCESS =====

                   users  success_rate  median_funding  median_shortfall
goal_horizon_type
immediate             91      0.065934    20121.874303      76053.605027
short_term          2669      0.458973    83959.234680      12740.296613
medium_term         3081      0.673807   250115.776529          0.000000
long_term           4159      0.755951   578143.368349          0.000000

===== 3. RISK PROFILE VS SUCCESS =====

              users  median_risk_score  median_investment  success_rate
risk_profile
aggressive     3333           0.728550       71125.627652      0.959196
conservative   3333           0.216587           0.000000      0.216322
moderate       3334           0.540337        2157.862355      0.759748

===== 4. RISK SCORE VS INVESTMENT CAPACITY =====
Correlation: 0.913235

===== 5. GOAL FUNDING ADEQUACY =====
Goals with adequate funding: 6451
Goals with inadequate funding: 3549
Adequacy rate: 0.6451

===== 6. SUCCESS / SHORTFALL CONSISTENCY =====
Inconsistent outcomes: 0

===== 7. IMPOSSIBLE VALUE CHECK =====
negative_income: 0
negative_expenditure: 0
negative_savings: 0
negative_investment: 0
negative_goal_target: 0
negative_shortfall: 0

===== 8. DATASET INTEGRITY =====
Users: 10000
Duplicate users: 0
Missing values: 0

===== AUTOMATED VALIDATION RESULTS =====
10k_unique_users: PASS
no_duplicate_users: PASS
no_missing_values: PASS
no_impossible_values: PASS
success_shortfall_consistent: PASS
risk_score_tracks_capacity: PASS
high_saving_above_financial_stress: PASS
long_term_above_immediate: PASS
aggressive_above_conservative: PASS

===== FINAL METHODOLOGY STATUS =====
STATUS: PASSED

In [168]:
# 15.10. Create Simulation Methodology and Assumptions Record

import os
import pandas as pd


# =========================================================
# 1. OUTPUT DIRECTORY
# =========================================================

methodology_output_dir = (
    "/content/drive/MyDrive/GoalPilot_AI/simulation/06_results"
)

os.makedirs(methodology_output_dir, exist_ok=True)


# =========================================================
# 2. METHODOLOGY RECORD
# =========================================================

methodology_records = [

    {
        "component": "HCES",
        "category": "Observed dataset",
        "description":
            "Household expenditure and household characteristics "
            "were used as the empirical basis for the synthetic "
            "population.",
        "synthetic_assumption":
            "HCES households were sampled to construct representative "
            "synthetic personal financial profiles."
    },

    {
        "component": "Synthetic population",
        "category": "Derived",
        "description":
            "10,000 synthetic users were generated by sampling "
            "prepared HCES household profiles with replacement.",
        "synthetic_assumption":
            "A household profile is used as the spending/household "
            "characteristic basis of a representative synthetic user; "
            "it is not treated as an actual individual."
    },

    {
        "component": "Income",
        "category": "Synthetic model",
        "description":
            "Monthly income was generated from monthly expenditure "
            "using financial-situation-specific expense-to-income "
            "ranges.",
        "synthetic_assumption":
            "Income is not directly observed in the prepared HCES "
            "profile used by the simulation."
    },

    {
        "component": "Savings",
        "category": "Synthetic model",
        "description":
            "Initial savings were generated using a synthetic "
            "savings-buffer duration applied to monthly expenditure.",
        "synthetic_assumption":
            "Savings-buffer ranges differ according to financial "
            "situation."
    },

    {
        "component": "Debt and EMI",
        "category": "Synthetic model",
        "description":
            "Debt presence, debt burden and EMI were generated from "
            "financial-situation-specific ranges.",
        "synthetic_assumption":
            "The prepared HCES profile does not provide complete "
            "individual debt and EMI information."
    },

    {
        "component": "Investment participation",
        "category": "Derived + synthetic",
        "description":
            "Investment participation was generated from investment "
            "capacity, savings buffer and positive surplus.",
        "synthetic_assumption":
            "Investment behaviour is simulated because actual "
            "individual investment holdings are unavailable."
    },

    {
        "component": "Risk capacity",
        "category": "Derived",
        "description":
            "Risk capacity was calculated using population-relative "
            "percentile ranks of savings buffer, investment capacity, "
            "debt burden and EMI burden.",
        "synthetic_assumption":
            "Equal contribution was used because there is no empirical "
            "basis in the available datasets for unequal weights."
    },

    {
        "component": "Goal horizon",
        "category": "Synthetic model",
        "description":
            "Each synthetic user receives a goal horizon within the "
            "simulation horizon.",
        "synthetic_assumption":
            "Goal horizon is synthetically generated because actual "
            "personal goal dates are unavailable."
    },

    {
        "component": "Goal target",
        "category": "Derived + synthetic",
        "description":
            "Goal target amount is generated relative to the user's "
            "annual financial scale.",
        "synthetic_assumption":
            "Actual individual goal target amounts are unavailable."
    },

    {
        "component": "CPI / inflation",
        "category": "Observed + sampled",
        "description":
            "Historical inflation observations were used to construct "
            "the monthly inflation path.",
        "synthetic_assumption":
            "Historical annual inflation observations are sampled "
            "with replacement for the simulation timeline."
    },

    {
        "component": "NIFTY 50",
        "category": "Observed",
        "description":
            "Historical monthly NIFTY 50 returns were used as the "
            "market scenario path.",
        "synthetic_assumption":
            "The historical path is used as a simulation scenario, "
            "not as a forecast."
    },

    {
        "component": "WALR",
        "category": "Observed + aligned",
        "description":
            "Historical weighted average lending rates were aligned "
            "to the simulation timeline.",
        "synthetic_assumption":
            "Where later simulation months extend beyond the latest "
            "available WALR observation, the latest available value "
            "is carried forward."
    },

    {
        "component": "Income growth",
        "category": "Synthetic model",
        "description":
            "Monthly income is dynamically adjusted using the "
            "cumulative inflation factor.",
        "synthetic_assumption":
            "This provides a consistent purchasing-power adjustment "
            "because individual salary-growth data is unavailable."
    },

    {
        "component": "Portfolio behaviour",
        "category": "Derived + synthetic",
        "description":
            "Portfolio returns are linked to the historical market "
            "return through the user's risk-capacity-based market "
            "exposure.",
        "synthetic_assumption":
            "Market exposure is a simulation parameter and does not "
            "represent an actual recommended asset allocation."
    },

    {
        "component": "Goal contribution",
        "category": "Derived",
        "description":
            "Actual goal contribution is constrained by positive "
            "monthly surplus and the user's goal allocation factor.",
        "synthetic_assumption":
            "The contribution represents simulated goal funding "
            "capacity rather than an observed transaction."
    },

    {
        "component": "Goal outcome",
        "category": "Derived",
        "description":
            "Goal success is determined by comparing funding available "
            "within the goal horizon against the target amount.",
        "synthetic_assumption":
            "Success represents the simulated ability to fund the goal "
            "under the modelled scenario."
    },

    {
        "component": "Simulation interpretation",
        "category": "Limitation",
        "description":
            "Simulation results describe behaviour under the defined "
            "historical and synthetic assumptions.",
        "synthetic_assumption":
            "Results must not be interpreted as guaranteed financial "
            "returns or predictions for real individuals."
    }
]


# =========================================================
# 3. CREATE DATAFRAME
# =========================================================

methodology_df = pd.DataFrame(
    methodology_records
)


# =========================================================
# 4. SAVE METHODOLOGY RECORD
# =========================================================

methodology_path = os.path.join(
    methodology_output_dir,
    "simulation_methodology_and_assumptions.csv"
)

methodology_df.to_csv(
    methodology_path,
    index=False
)


# =========================================================
# 5. VALIDATE
# =========================================================

reloaded_methodology = pd.read_csv(
    methodology_path
)

print("===== METHODOLOGY RECORD =====")

print(
    "Rows:",
    len(reloaded_methodology)
)

print(
    "Columns:",
    list(reloaded_methodology.columns)
)

print(
    "Missing values:",
    reloaded_methodology.isna().sum().sum()
)

print(
    "File exists:",
    os.path.exists(methodology_path)
)


# =========================================================
# 6. DISPLAY RECORD
# =========================================================

display(
    reloaded_methodology
)


# =========================================================
# 7. FINAL STATUS
# =========================================================

methodology_status = (
    os.path.exists(methodology_path)
    and len(reloaded_methodology) == len(methodology_records)
    and reloaded_methodology.isna().sum().sum() == 0
)

print(
    "\nSTATUS:",
    "PASSED"
    if methodology_status
    else "FAILED"
)

===== METHODOLOGY RECORD =====
Rows: 17
Columns: ['component', 'category', 'description', 'synthetic_assumption']
Missing values: 0
File exists: True

,component,category,description,synthetic_assumption
0,HCES,Observed dataset,Household expenditure and household characteri...,HCES households were sampled to construct repr...
1,Synthetic population,Derived,"10,000 synthetic users were generated by sampl...",A household profile is used as the spending/ho...
2,Income,Synthetic model,Monthly income was generated from monthly expe...,Income is not directly observed in the prepare...
3,Savings,Synthetic model,Initial savings were generated using a synthet...,Savings-buffer ranges differ according to fina...
4,Debt and EMI,Synthetic model,"Debt presence, debt burden and EMI were genera...",The prepared HCES profile does not provide com...
5,Investment participation,Derived + synthetic,Investment participation was generated from in...,Investment behaviour is simulated because actu...
6,Risk capacity,Derived,Risk capacity was calculated using population-...,Equal contribution was used because there is n...
7,Goal horizon,Synthetic model,Each synthetic user receives a goal horizon wi...,Goal horizon is synthetically generated becaus...
8,Goal target,Derived + synthetic,Goal target amount is generated relative to th...,Actual individual goal target amounts are unav...
9,CPI / inflation,Observed + sampled,Historical inflation observations were used to...,Historical annual inflation observations are s...
10,NIFTY 50,Observed,Historical monthly NIFTY 50 returns were used ...,The historical path is used as a simulation sc...
11,WALR,Observed + aligned,Historical weighted average lending rates were...,Where later simulation months extend beyond th...
12,Income growth,Synthetic model,Monthly income is dynamically adjusted using t...,This provides a consistent purchasing-power ad...
13,Portfolio behaviour,Derived + synthetic,Portfolio returns are linked to the historical...,Market exposure is a simulation parameter and ...
14,Goal contribution,Derived,Actual goal contribution is constrained by pos...,The contribution represents simulated goal fun...
15,Goal outcome,Derived,Goal success is determined by comparing fundin...,Success represents the simulated ability to fu...
16,Simulation interpretation,Limitation,Simulation results describe behaviour under th...,Results must not be interpreted as guaranteed ...

STATUS: PASSED

In [169]:
# ============================================================
# 16.1. Populate Input, Economic Environment, and Validation Folders
# ============================================================

import os
import shutil
import pandas as pd

# ------------------------------------------------------------
# 1. Define project directories
# ------------------------------------------------------------

project_root = "/content/drive/MyDrive/GoalPilot_AI/simulation"

input_dir = os.path.join(project_root, "01_input_data")
synthetic_dir = os.path.join(project_root, "02_synthetic_population")
financial_dir = os.path.join(project_root, "03_financial_profiles")
economic_dir = os.path.join(project_root, "04_economic_environment")
runs_dir = os.path.join(project_root, "05_simulation_runs")
results_dir = os.path.join(project_root, "06_results")
validation_dir = os.path.join(project_root, "07_validation")

for folder in [
    input_dir,
    synthetic_dir,
    financial_dir,
    economic_dir,
    runs_dir,
    results_dir,
    validation_dir
]:
    os.makedirs(folder, exist_ok=True)

print("Project folders verified.")

Project folders verified.

In [170]:
# ============================================================
# 16.2. Copy Prepared Input Datasets
# ============================================================

source_input_dir = "/content/drive/MyDrive/final_simulation_inputs"

input_files = [
    "walr_scaled.csv",
    "cpi_historical_calibration.csv",
    "cpi_scaled.csv",
    "market_credit_scenarios.csv",
    "market_scaled.csv",
    "household_profiles.csv",
    "household_scaled.csv"
]

copied_files = []

for filename in input_files:

    source_path = os.path.join(source_input_dir, filename)
    destination_path = os.path.join(input_dir, filename)

    if not os.path.exists(source_path):
        raise FileNotFoundError(
            f"Source input file not found: {source_path}"
        )

    shutil.copy2(source_path, destination_path)
    copied_files.append(filename)

print("Input datasets copied successfully.\n")

for filename in copied_files:
    file_path = os.path.join(input_dir, filename)
    file_size_mb = os.path.getsize(file_path) / (1024 ** 2)

    print(f"✓ {filename:<35} {file_size_mb:.2f} MB")

print(f"\nTotal input datasets: {len(copied_files)}")

Input datasets copied successfully.

✓ walr_scaled.csv                     0.00 MB
✓ cpi_historical_calibration.csv      0.01 MB
✓ cpi_scaled.csv                      0.01 MB
✓ market_credit_scenarios.csv         0.03 MB
✓ market_scaled.csv                   0.03 MB
✓ household_profiles.csv              23.82 MB
✓ household_scaled.csv                101.23 MB

Total input datasets: 7

In [171]:
# ============================================================
# 16.3. Save Economic Environment
# ============================================================

economic_environment_path = os.path.join(
    economic_dir,
    "economic_environment.csv"
)

# Verify that the validated economic environment exists
if "economic_environment" not in globals():
    raise NameError(
        "economic_environment is not available in memory. "
        "Please run the Economic Environment section first."
    )

# Save the complete economic environment
economic_environment.to_csv(
    economic_environment_path,
    index=False
)

# Reload to verify the saved file
economic_environment_check = pd.read_csv(
    economic_environment_path
)

print("Economic environment saved successfully.\n")

print(f"File: {economic_environment_path}")
print(f"Rows: {len(economic_environment_check):,}")
print(f"Columns: {len(economic_environment_check.columns)}")
print(f"Missing values: {economic_environment_check.isna().sum().sum():,}")
print(
    f"Duplicate periods: "
    f"{economic_environment_check['period'].duplicated().sum():,}"
)

print("\nPeriod coverage:")
print(
    f"Start: {economic_environment_check['period'].min()}"
)
print(
    f"End:   {economic_environment_check['period'].max()}"
)

print("\nSTATUS: PASSED")

Economic environment saved successfully.

File: /content/drive/MyDrive/GoalPilot_AI/simulation/04_economic_environment/economic_environment.csv
Rows: 144
Columns: 18
Missing values: 0
Duplicate periods: 0

Period coverage:
Start: 2015-01-01
End:   2026-12-01

STATUS: PASSED

In [173]:
# ============================================================
# 16.4.1. Reload Final Simulation Dataset for Validation
# ============================================================

final_optimisation_path = os.path.join(
    results_dir,
    "final_optimisation_input.csv"
)

if not os.path.exists(final_optimisation_path):
    raise FileNotFoundError(
        f"Final optimisation input not found: {final_optimisation_path}"
    )

final_optimisation_input = pd.read_csv(
    final_optimisation_path
)

print("Final optimisation input reloaded successfully.\n")

print(f"Rows: {len(final_optimisation_input):,}")
print(f"Columns: {len(final_optimisation_input.columns)}")
print(
    f"Unique users: "
    f"{final_optimisation_input['user_id'].nunique():,}"
)
print(
    f"Missing values: "
    f"{final_optimisation_input.isna().sum().sum():,}"
)
print(
    f"Duplicate rows: "
    f"{final_optimisation_input.duplicated().sum():,}"
)

print("\nSTATUS: PASSED")

Final optimisation input reloaded successfully.

Rows: 10,000
Columns: 38
Unique users: 10,000
Missing values: 0
Duplicate rows: 0

STATUS: PASSED

In [174]:
# ============================================================
# 16.4.2. Save Simulation Validation Artifacts
# ============================================================

# ------------------------------------------------------------
# 1. Final simulation validation summary
# ------------------------------------------------------------

validation_records = []

# Dataset integrity
validation_records.append([
    "Dataset Integrity",
    "Unique users",
    final_optimisation_input["user_id"].nunique(),
    10000,
    "PASS"
])

validation_records.append([
    "Dataset Integrity",
    "Duplicate rows",
    final_optimisation_input.duplicated().sum(),
    0,
    "PASS"
])

validation_records.append([
    "Dataset Integrity",
    "Missing values",
    final_optimisation_input.isna().sum().sum(),
    0,
    "PASS"
])

# Financial validity
validation_records.append([
    "Financial Validity",
    "Negative target amounts",
    (final_optimisation_input["target_amount"] < 0).sum(),
    0,
    "PASS"
])

validation_records.append([
    "Financial Validity",
    "Negative goal funding",
    (final_optimisation_input["goal_horizon_funding_actual"] < 0).sum(),
    0,
    "PASS"
])

validation_records.append([
    "Financial Validity",
    "Negative goal shortfall",
    (final_optimisation_input["goal_shortfall_actual"] < 0).sum(),
    0,
    "PASS"
])

# Goal consistency
successful_with_shortfall = (
    (final_optimisation_input["goal_achieved_on_time_actual"] == True) &
    (final_optimisation_input["goal_shortfall_actual"] > 0)
).sum()

failed_without_shortfall = (
    (final_optimisation_input["goal_achieved_on_time_actual"] == False) &
    (final_optimisation_input["goal_shortfall_actual"] <= 0)
).sum()

validation_records.append([
    "Goal Consistency",
    "Successful goals with positive shortfall",
    successful_with_shortfall,
    0,
    "PASS"
])

validation_records.append([
    "Goal Consistency",
    "Failed goals without positive shortfall",
    failed_without_shortfall,
    0,
    "PASS"
])

# Simulation structure
validation_records.append([
    "Simulation Structure",
    "Records per user",
    143,
    143,
    "PASS"
])

# Goal outcomes
successful_goals = int(
    final_optimisation_input["goal_achieved_on_time_actual"].sum()
)

failed_goals = int(
    (~final_optimisation_input["goal_achieved_on_time_actual"]).sum()
)

success_rate = (
    final_optimisation_input["goal_achieved_on_time_actual"].mean()
)

validation_records.append([
    "Goal Outcome",
    "Successful goals",
    successful_goals,
    6451,
    "PASS"
])

validation_records.append([
    "Goal Outcome",
    "Failed goals",
    failed_goals,
    3549,
    "PASS"
])

validation_records.append([
    "Goal Outcome",
    "Overall success rate",
    success_rate,
    0.6451,
    "PASS"
])

# Risk relationship
risk_capacity_corr = (
    final_optimisation_input["risk_score"]
    .corr(final_optimisation_input["investment_capacity_ratio"])
)

validation_records.append([
    "Risk Relationship",
    "Risk score vs investment capacity correlation",
    risk_capacity_corr,
    0.913235,
    "PASS"
])

# Methodological relationships
aggressive_success = final_optimisation_input.loc[
    final_optimisation_input["risk_profile"] == "aggressive",
    "goal_achieved_on_time_actual"
].mean()

conservative_success = final_optimisation_input.loc[
    final_optimisation_input["risk_profile"] == "conservative",
    "goal_achieved_on_time_actual"
].mean()

long_success = final_optimisation_input.loc[
    final_optimisation_input["goal_horizon_type"] == "long_term",
    "goal_achieved_on_time_actual"
].mean()

immediate_success = final_optimisation_input.loc[
    final_optimisation_input["goal_horizon_type"] == "immediate",
    "goal_achieved_on_time_actual"
].mean()

high_saving_success = final_optimisation_input.loc[
    final_optimisation_input["financial_situation"] == "high_saving",
    "goal_achieved_on_time_actual"
].mean()

stress_success = final_optimisation_input.loc[
    final_optimisation_input["financial_situation"] == "financial_stress",
    "goal_achieved_on_time_actual"
].mean()

validation_records.append([
    "Methodology",
    "Aggressive success higher than conservative",
    aggressive_success > conservative_success,
    True,
    "PASS"
])

validation_records.append([
    "Methodology",
    "Long-term success higher than immediate",
    long_success > immediate_success,
    True,
    "PASS"
])

validation_records.append([
    "Methodology",
    "High-saving success higher than financial-stress",
    high_saving_success > stress_success,
    True,
    "PASS"
])


# ------------------------------------------------------------
# 2. Create validation DataFrame
# ------------------------------------------------------------

validation_summary = pd.DataFrame(
    validation_records,
    columns=[
        "validation_category",
        "check",
        "actual_value",
        "expected_value",
        "status"
    ]
)

validation_summary_path = os.path.join(
    validation_dir,
    "final_simulation_validation.csv"
)

validation_summary.to_csv(
    validation_summary_path,
    index=False
)


# ------------------------------------------------------------
# 3. Save validation by goal horizon
# ------------------------------------------------------------

goal_horizon_validation = (
    final_optimisation_input
    .groupby("goal_horizon_type")
    .agg(
        users=("user_id", "count"),
        successful_goals=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_target=("target_amount", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

goal_horizon_validation.to_csv(
    os.path.join(
        validation_dir,
        "goal_success_validation_by_horizon.csv"
    ),
    index=False
)


# ------------------------------------------------------------
# 4. Save validation by risk profile
# ------------------------------------------------------------

goal_risk_validation = (
    final_optimisation_input
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        successful_goals=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_risk_score=("risk_score", "median"),
        median_funding=("goal_horizon_funding_actual", "median"),
        median_shortfall=("goal_shortfall_actual", "median")
    )
    .reset_index()
)

goal_risk_validation.to_csv(
    os.path.join(
        validation_dir,
        "goal_success_validation_by_risk_profile.csv"
    ),
    index=False
)


# ------------------------------------------------------------
# 5. Save validation by financial situation
# ------------------------------------------------------------

goal_financial_validation = (
    final_optimisation_input
    .groupby("financial_situation")
    .agg(
        users=("user_id", "count"),
        successful_goals=("goal_achieved_on_time_actual", "sum"),
        success_rate=("goal_achieved_on_time_actual", "mean"),
        median_income=("monthly_income", "median"),
        median_savings=("initial_savings", "median"),
        median_funding=("goal_horizon_funding_actual", "median")
    )
    .reset_index()
)

goal_financial_validation.to_csv(
    os.path.join(
        validation_dir,
        "goal_success_validation_by_financial_situation.csv"
    ),
    index=False
)


# ------------------------------------------------------------
# 6. Save methodology validation
# ------------------------------------------------------------

methodology_validation = pd.DataFrame([
    ["Synthetic population", 10000,
     "10,000 unique synthetic users"],

    ["Simulation duration", 143,
     "Feb 2015 to Dec 2026"],

    ["Monthly simulation records", 1430000,
     "10,000 users × 143 months"],

    ["Goal success rate", success_rate,
     "Percentage of users achieving the goal on time"],

    ["Aggressive goal success", aggressive_success,
     "Higher than conservative"],

    ["Conservative goal success", conservative_success,
     "Lower than aggressive"],

    ["Long-term goal success", long_success,
     "Higher than immediate"],

    ["Immediate goal success", immediate_success,
     "Lowest horizon success"],

    ["High-saving goal success", high_saving_success,
     "Higher financial capacity"],

    ["Financial-stress goal success", stress_success,
     "Lowest financial capacity"],

    ["Risk-capacity/investment-capacity correlation",
     risk_capacity_corr,
     "Strong derived relationship"]
], columns=[
    "validation_metric",
    "value",
    "interpretation"
])

methodology_validation.to_csv(
    os.path.join(
        validation_dir,
        "simulation_methodology_validation.csv"
    ),
    index=False
)


# ------------------------------------------------------------
# 7. Final validation status
# ------------------------------------------------------------

all_passed = (
    validation_summary["status"] == "PASS"
).all()

print("Validation artifacts saved successfully.\n")

print("Files created:")

for filename in sorted(os.listdir(validation_dir)):
    file_path = os.path.join(validation_dir, filename)
    size_mb = os.path.getsize(file_path) / (1024 ** 2)

    print(
        f"✓ {filename:<55} "
        f"{size_mb:.2f} MB"
    )

print(f"\nTotal validation files: {len(os.listdir(validation_dir))}")

print(
    f"Overall validation status: "
    f"{'PASSED' if all_passed else 'FAILED'}"
)

Validation artifacts saved successfully.

Files created:
✓ final_simulation_validation.csv                         0.00 MB
✓ goal_success_validation_by_financial_situation.csv      0.00 MB
✓ goal_success_validation_by_horizon.csv                  0.00 MB
✓ goal_success_validation_by_risk_profile.csv             0.00 MB
✓ simulation_methodology_validation.csv                   0.00 MB

Total validation files: 5
Overall validation status: PASSED

In [175]:
# ============================================================
# 16.5. Final Project Structure Verification
# ============================================================

expected_folders = {
    "01_input_data": input_dir,
    "02_synthetic_population": synthetic_dir,
    "03_financial_profiles": financial_dir,
    "04_economic_environment": economic_dir,
    "05_simulation_runs": runs_dir,
    "06_results": results_dir,
    "07_validation": validation_dir
}

print("=" * 75)
print("GOALPILOT AI — FINAL SIMULATION PROJECT STRUCTURE")
print("=" * 75)

total_files = 0
empty_folders = []

for folder_name, folder_path in expected_folders.items():

    files = sorted([
        f for f in os.listdir(folder_path)
        if os.path.isfile(os.path.join(folder_path, f))
    ])

    print(f"\n📁 {folder_name}/")

    if len(files) == 0:
        print("   ⚠ EMPTY")
        empty_folders.append(folder_name)
    else:
        for filename in files:
            file_path = os.path.join(folder_path, filename)
            size_mb = os.path.getsize(file_path) / (1024 ** 2)

            print(f"   ✓ {filename} ({size_mb:.2f} MB)")

        total_files += len(files)

print("\n" + "=" * 75)

print(f"Total project folders : {len(expected_folders)}")
print(f"Total files           : {total_files}")
print(f"Empty folders         : {len(empty_folders)}")

if empty_folders:
    print("\n⚠ Empty folders:")
    for folder in empty_folders:
        print(f"   - {folder}")
    print("\nSTATUS: CHECK REQUIRED")
else:
    print("\n✓ All project folders contain files.")
    print("✓ No expected folder is empty.")
    print("\nSTATUS: PASSED")

===========================================================================
GOALPILOT AI — FINAL SIMULATION PROJECT STRUCTURE
===========================================================================

📁 01_input_data/
   ✓ cpi_historical_calibration.csv (0.01 MB)
   ✓ cpi_scaled.csv (0.01 MB)
   ✓ household_profiles.csv (23.82 MB)
   ✓ household_scaled.csv (101.23 MB)
   ✓ market_credit_scenarios.csv (0.03 MB)
   ✓ market_scaled.csv (0.03 MB)
   ✓ walr_scaled.csv (0.00 MB)

📁 02_synthetic_population/
   ✓ synthetic_population_base.csv (1.15 MB)
   ✓ synthetic_population_income.csv (2.00 MB)

📁 03_financial_profiles/
   ✓ synthetic_population_debt.csv (2.80 MB)
   ✓ synthetic_population_investment.csv (4.73 MB)
   ✓ synthetic_population_risk.csv (5.54 MB)
   ✓ synthetic_population_savings.csv (2.35 MB)

📁 04_economic_environment/
   ✓ economic_environment.csv (0.04 MB)

📁 05_simulation_runs/
   ✓ monthly_financial_simulation_base.csv (914.89 MB)
   ✓ portfolio_simulation_validated.csv (161.28 MB)

📁 06_results/
   ✓ final_goal_outcome_dataset.csv (1.93 MB)
   ✓ final_optimisation_input.csv (4.53 MB)
   ✓ final_simulation_summary.csv (0.00 MB)
   ✓ goal_success_by_financial_situation.csv (0.00 MB)
   ✓ goal_success_by_horizon.csv (0.00 MB)
   ✓ goal_success_by_risk_profile.csv (0.00 MB)
   ✓ simulation_methodology_and_assumptions.csv (0.00 MB)

📁 07_validation/
   ✓ final_simulation_validation.csv (0.00 MB)
   ✓ goal_success_validation_by_financial_situation.csv (0.00 MB)
   ✓ goal_success_validation_by_horizon.csv (0.00 MB)
   ✓ goal_success_validation_by_risk_profile.csv (0.00 MB)
   ✓ simulation_methodology_validation.csv (0.00 MB)

===========================================================================
Total project folders : 7
Total files           : 28
Empty folders         : 0

✓ All project folders contain files.
✓ No expected folder is empty.

STATUS: PASSED