In [81]:
# ============================================================
# GOALPILOT AI — STEP 1A
# LP HANDOFF DATA AUDIT
# ============================================================

import os
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Mount Google Drive
# ------------------------------------------------------------
from google.colab import drive

drive.mount('/content/drive')

# ------------------------------------------------------------
# 2. Define existing simulation paths
# ------------------------------------------------------------
BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"
SIM_DIR = os.path.join(BASE_DIR, "simulation")
RESULT_DIR = os.path.join(SIM_DIR, "06_results")

LP_INPUT = os.path.join(
    RESULT_DIR,
    "final_optimisation_input.csv"
)

print("=" * 70)
print("GOALPILOT AI — LP HANDOFF AUDIT")
print("=" * 70)

print("\nSimulation directory:")
print(SIM_DIR)

print("\nResults directory:")
print(RESULT_DIR)

print("\nLP input:")
print(LP_INPUT)

# ------------------------------------------------------------
# 3. Check directories
# ------------------------------------------------------------
print("\n" + "-" * 70)
print("DIRECTORY CHECK")
print("-" * 70)

print("BASE_DIR exists :", os.path.exists(BASE_DIR))
print("SIM_DIR exists  :", os.path.exists(SIM_DIR))
print("RESULT_DIR exists:", os.path.exists(RESULT_DIR))
print("LP_INPUT exists :", os.path.exists(LP_INPUT))

# ------------------------------------------------------------
# 4. List result files
# ------------------------------------------------------------
if os.path.exists(RESULT_DIR):

    print("\n" + "-" * 70)
    print("FILES IN 06_results")
    print("-" * 70)

    for f in sorted(os.listdir(RESULT_DIR)):
        full_path = os.path.join(RESULT_DIR, f)

        if os.path.isfile(full_path):
            size_mb = os.path.getsize(full_path) / (1024 ** 2)
            print(f"{f:<55} {size_mb:>8.2f} MB")

# ------------------------------------------------------------
# 5. Load actual LP input
# ------------------------------------------------------------
if not os.path.exists(LP_INPUT):

    print("\nERROR:")
    print("final_optimisation_input.csv was not found at the documented path.")

else:

    print("\n" + "-" * 70)
    print("LOADING LP INPUT")
    print("-" * 70)

    df_lp = pd.read_csv(LP_INPUT)

    print("Shape:", df_lp.shape)

    print("\nColumns:")
    for i, col in enumerate(df_lp.columns, start=1):
        print(f"{i:2d}. {col}")

    # --------------------------------------------------------
    # 6. Data types
    # --------------------------------------------------------
    print("\n" + "-" * 70)
    print("DATA TYPES")
    print("-" * 70)

    print(df_lp.dtypes)

    # --------------------------------------------------------
    # 7. Missing values
    # --------------------------------------------------------
    print("\n" + "-" * 70)
    print("MISSING VALUES")
    print("-" * 70)

    missing = df_lp.isna().sum()

    missing_nonzero = missing[missing > 0]

    if len(missing_nonzero) == 0:
        print("No missing values.")
    else:
        print(missing_nonzero)

    # --------------------------------------------------------
    # 8. Inf / -Inf check
    # --------------------------------------------------------
    print("\n" + "-" * 70)
    print("INFINITY CHECK")
    print("-" * 70)

    numeric_df = df_lp.select_dtypes(include=np.number)

    inf_count = np.isinf(numeric_df.to_numpy()).sum()

    print("Numeric columns:", len(numeric_df.columns))
    print("Inf / -Inf values:", inf_count)

    # --------------------------------------------------------
    # 9. Duplicate users
    # --------------------------------------------------------
    print("\n" + "-" * 70)
    print("USER INTEGRITY")
    print("-" * 70)

    if "user_id" in df_lp.columns:

        print("Total rows:", len(df_lp))
        print("Unique users:", df_lp["user_id"].nunique())
        print("Duplicate user IDs:",
              df_lp["user_id"].duplicated().sum())

    # --------------------------------------------------------
    # 10. Display sample
    # --------------------------------------------------------
    print("\n" + "-" * 70)
    print("FIRST 5 ROWS")
    print("-" * 70)

    display(df_lp.head())

    # --------------------------------------------------------
    # 11. Numeric summary
    # --------------------------------------------------------
    print("\n" + "-" * 70)
    print("NUMERIC SUMMARY")
    print("-" * 70)

    display(
        df_lp.describe(include="all").T
    )

    # --------------------------------------------------------
    # 12. Save audit object for later cells
    # --------------------------------------------------------
    print("\nAudit dataframe stored as:")
    print("df_lp")

print("\n" + "=" * 70)
print("STEP 1A COMPLETE")
print("=" * 70)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
GOALPILOT AI — LP HANDOFF AUDIT
======================================================================

Simulation directory:
/content/drive/MyDrive/GoalPilot_AI/simulation

Results directory:
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results

LP input:
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/final_optimisation_input.csv

----------------------------------------------------------------------
DIRECTORY CHECK
----------------------------------------------------------------------
BASE_DIR exists : True
SIM_DIR exists  : True
RESULT_DIR exists: True
LP_INPUT exists : True

----------------------------------------------------------------------
FILES IN 06_results
----------------------------------------------------------------------
final_goal_outcome_dataset.csv                              1.93 MB
final_optimisation_input.csv                                4.53 MB
final_simulation_summary.csv                                0.00 MB
goal_success_by_financial_situation.csv                     0.00 MB
goal_success_by_horizon.csv                                 0.00 MB
goal_success_by_risk_profile.csv                            0.00 MB
simulation_methodology_and_assumptions.csv                  0.00 MB

----------------------------------------------------------------------
LOADING LP INPUT
----------------------------------------------------------------------
Shape: (10000, 38)

Columns:
 1. user_id
 2. monthly_income
 3. monthly_expenditure
 4. monthly_emi
 5. initial_savings
 6. initial_investment
 7. investment_capacity_ratio
 8. financial_situation
 9. risk_score
10. risk_profile
11. goal_horizon_months
12. goal_horizon_type
13. target_amount
14. target_to_annual_income_ratio
15. target_to_savings_ratio
16. goal_specific_monthly_capacity
17. goal_allocation_factor
18. final_monthly_income
19. final_monthly_expenditure
20. final_monthly_surplus
21. final_monthly_emi
22. final_savings_balance
23. final_portfolio_value
24. final_total_financial_wealth
25. final_portfolio_wealth_ratio
26. final_savings_status
27. final_cash_flow_status
28. final_unfunded_deficit
29. goal_horizon_funding_actual
30. goal_progress_at_deadline_actual
31. goal_progress_at_deadline_actual_capped
32. goal_shortfall_actual
33. goal_achieved_on_time_actual
34. goal_shortfall_severity
35. goal_outcome
36. goal_funding_ratio
37. goal_funding_ratio_capped
38. goal_shortfall_ratio

----------------------------------------------------------------------
DATA TYPES
----------------------------------------------------------------------
user_id                                     object
monthly_income                             float64
monthly_expenditure                        float64
monthly_emi                                float64
initial_savings                            float64
initial_investment                         float64
investment_capacity_ratio                  float64
financial_situation                         object
risk_score                                 float64
risk_profile                                object
goal_horizon_months                          int64
goal_horizon_type                           object
target_amount                              float64
target_to_annual_income_ratio              float64
target_to_savings_ratio                    float64
goal_specific_monthly_capacity             float64
goal_allocation_factor                     float64
final_monthly_income                       float64
final_monthly_expenditure                  float64
final_monthly_surplus                      float64
final_monthly_emi                          float64
final_savings_balance                      float64
final_portfolio_value                      float64
final_total_financial_wealth               float64
final_portfolio_wealth_ratio               float64
final_savings_status                        object
final_cash_flow_status                      object
final_unfunded_deficit                     float64
goal_horizon_funding_actual                float64
goal_progress_at_deadline_actual           float64
goal_progress_at_deadline_actual_capped    float64
goal_shortfall_actual                      float64
goal_achieved_on_time_actual                  bool
goal_shortfall_severity                     object
goal_outcome                                object
goal_funding_ratio                         float64
goal_funding_ratio_capped                  float64
goal_shortfall_ratio                       float64
dtype: object

----------------------------------------------------------------------
MISSING VALUES
----------------------------------------------------------------------
No missing values.

----------------------------------------------------------------------
INFINITY CHECK
----------------------------------------------------------------------
Numeric columns: 29
Inf / -Inf values: 0

----------------------------------------------------------------------
USER INTEGRITY
----------------------------------------------------------------------
Total rows: 10000
Unique users: 10000
Duplicate user IDs: 0

----------------------------------------------------------------------
FIRST 5 ROWS
----------------------------------------------------------------------

,user_id,monthly_income,monthly_expenditure,monthly_emi,initial_savings,initial_investment,investment_capacity_ratio,financial_situation,risk_score,risk_profile,...,goal_horizon_funding_actual,goal_progress_at_deadline_actual,goal_progress_at_deadline_actual_capped,goal_shortfall_actual,goal_achieved_on_time_actual,goal_shortfall_severity,goal_outcome,goal_funding_ratio,goal_funding_ratio_capped,goal_shortfall_ratio
0,USER_00001,51351.335334,36870.0,0.000000,178733.652470,45777.548120,0.282005,moderate_saving,0.710500,aggressive,...,5.811302e+05,5.037660,1.000000,0.000000,True,no_shortfall,success,5.037660,1.000000,0.000000
1,USER_00002,26415.417334,27500.0,11814.371436,13659.350863,0.000000,0.000000,financial_stress,0.038363,conservative,...,0.000000e+00,0.000000,0.000000,59340.387689,False,severe_shortfall,failure,0.000000,0.000000,1.000000
2,USER_00003,44467.548430,42000.0,0.000000,85318.549015,0.000000,0.055491,low_saving,0.505350,moderate,...,4.093773e+04,0.409815,0.409815,58955.510123,False,mild_shortfall,failure,0.409815,0.409815,0.590185
3,USER_00004,33598.333991,25500.0,7052.590854,107702.527041,60534.274631,0.031125,moderate_saving,0.313650,conservative,...,4.566919e+04,0.605080,0.605080,29807.117161,False,mild_shortfall,failure,0.605080,0.605080,0.394920
4,USER_00005,91719.010189,51000.0,0.000000,205810.045973,105774.934379,0.443954,high_saving,0.750750,aggressive,...,7.318348e+06,35.519005,1.000000,0.000000,True,no_shortfall,success,35.519005,1.000000,0.000000

----------------------------------------------------------------------
NUMERIC SUMMARY
----------------------------------------------------------------------

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
user_id,10000,10000,USER_09984,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
monthly_income,10000.0,NaN,NaN,NaN,61588.311653,53908.82938,1257.33965,32005.389162,47770.48575,71013.157446,845993.172582
monthly_expenditure,10000.0,NaN,NaN,NaN,44971.4612,37632.718833,850.0,24000.0,35750.0,51316.5,530500.0
monthly_emi,10000.0,NaN,NaN,NaN,5195.49081,9746.159467,0.0,0.0,0.0,8042.87111,139834.65141
initial_savings,10000.0,NaN,NaN,NaN,166794.764388,217534.748504,7.776881,49608.326314,104229.701508,202970.684488,4946442.831614
initial_investment,10000.0,NaN,NaN,NaN,56968.534834,121610.40386,0.0,0.0,9154.054851,67910.432199,3880240.368529
investment_capacity_ratio,10000.0,NaN,NaN,NaN,0.187228,0.149113,0.0,0.036815,0.189573,0.306529,0.499976
financial_situation,10000,4,moderate_saving,4560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_score,10000.0,NaN,NaN,NaN,0.5,0.223233,0.028262,0.313572,0.540337,0.682412,0.854
risk_profile,10000,3,moderate,3334,NaN,NaN,NaN,NaN,NaN,NaN,NaN
goal_horizon_months,10000.0,NaN,NaN,NaN,62.697,33.431233,6.0,33.0,63.0,92.0,120.0
goal_horizon_type,10000,4,long_term,4159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
target_amount,10000.0,NaN,NaN,NaN,138353.834973,121102.41511,2824.525592,71897.868468,107313.055427,159526.091924,1900464.497997
target_to_annual_income_ratio,10000.0,NaN,NaN,NaN,0.187203,0.0,0.187203,0.187203,0.187203,0.187203,0.187203
target_to_savings_ratio,10000.0,NaN,NaN,NaN,1.854005,18.381793,0.29039,0.649122,1.0,1.679511,1751.784507
goal_specific_monthly_capacity,10000.0,NaN,NaN,NaN,10408.069934,18578.095127,0.0,304.680019,3802.625086,12801.743318,401353.251371
goal_allocation_factor,10000.0,NaN,NaN,NaN,0.50005,0.287291,0.10655,0.250075,0.50005,0.750025,1.0
final_monthly_income,10000.0,NaN,NaN,NaN,171047.067784,149719.109775,3491.965514,88887.44995,132671.302313,197222.362966,2349547.302935
final_monthly_expenditure,10000.0,NaN,NaN,NaN,124897.669149,104516.036183,2360.675325,66654.362113,99287.226898,142519.523891,1473339.129207
final_monthly_surplus,10000.0,NaN,NaN,NaN,40953.907825,54983.28704,-210294.161487,10591.99203,27348.749057,53086.667721,1114664.373006
final_monthly_emi,10000.0,NaN,NaN,NaN,5195.49081,9746.159467,0.0,0.0,0.0,8042.87111,139834.65141
final_savings_balance,10000.0,NaN,NaN,NaN,3703610.409912,4997736.154281,0.0,805594.446843,2346684.512641,4794795.393598,105272908.998344
final_portfolio_value,10000.0,NaN,NaN,NaN,115903.569237,262681.353448,0.0,0.0,13458.015923,127451.304112,9121935.133092
final_total_financial_wealth,10000.0,NaN,NaN,NaN,3819513.979149,5196514.756557,0.0,817811.759528,2407303.952042,4924233.576219,114394844.131435
final_portfolio_wealth_ratio,10000.0,NaN,NaN,NaN,0.049856,0.166929,0.0,0.0,0.011903,0.039663,1.0
final_savings_status,10000,2,positive,8715,NaN,NaN,NaN,NaN,NaN,NaN,NaN
final_cash_flow_status,10000,2,surplus,9183,NaN,NaN,NaN,NaN,NaN,NaN,NaN
final_unfunded_deficit,10000.0,NaN,NaN,NaN,126048.694932,606608.831904,0.0,0.0,0.0,0.0,25968010.561177
goal_horizon_funding_actual,10000.0,NaN,NaN,NaN,944964.830723,2156856.829027,0.0,26761.386416,236498.481969,968371.746726,66592877.128021
goal_progress_at_deadline_actual,10000.0,NaN,NaN,NaN,5.191022,6.739802,0.0,0.341658,2.399176,7.58686,40.211537
goal_progress_at_deadline_actual_capped,10000.0,NaN,NaN,NaN,0.726317,0.410213,0.0,0.341658,1.0,1.0,1.0
goal_shortfall_actual,10000.0,NaN,NaN,NaN,30580.490391,66032.898324,0.0,0.0,0.0,42376.022555,996069.975005
goal_achieved_on_time_actual,10000,2,True,6451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
goal_shortfall_severity,10000,4,no_shortfall,6451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
goal_outcome,10000,2,success,6451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
goal_funding_ratio,10000.0,NaN,NaN,NaN,5.191022,6.739802,0.0,0.341658,2.399176,7.58686,40.211537
goal_funding_ratio_capped,10000.0,NaN,NaN,NaN,0.726317,0.410213,0.0,0.341658,1.0,1.0,1.0
goal_shortfall_ratio,10000.0,NaN,NaN,NaN,0.273683,0.410213,0.0,0.0,0.0,0.658342,1.0

Audit dataframe stored as:
df_lp

======================================================================
STEP 1A COMPLETE
======================================================================

In [82]:
# ============================================================
# GOALPILOT AI — STEP 2B
# LP INPUT VARIABLE VALIDATION
# ============================================================

required_lp_columns = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "financial_situation",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual",
    "goal_outcome",
    "final_savings_balance",
    "final_portfolio_value",
    "final_total_financial_wealth"
]

print("=" * 70)
print("GOALPILOT AI — LP INPUT VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. Check required columns
# ------------------------------------------------------------

missing_required = [
    col for col in required_lp_columns
    if col not in df_lp.columns
]

if missing_required:
    print("\n❌ Missing required columns:")
    for col in missing_required:
        print(" -", col)
else:
    print("\n✅ All required LP columns are present.")

# ------------------------------------------------------------
# 2. Calculate available monthly surplus
# ------------------------------------------------------------

df_lp["lp_monthly_surplus"] = (
    df_lp["monthly_income"]
    - df_lp["monthly_expenditure"]
    - df_lp["monthly_emi"]
)

df_lp["lp_available_surplus"] = (
    df_lp["lp_monthly_surplus"].clip(lower=0)
)

# ------------------------------------------------------------
# 3. Basic financial consistency
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("FINANCIAL CAPACITY")
print("-" * 70)

print(
    "Mean monthly income:",
    df_lp["monthly_income"].mean()
)

print(
    "Mean monthly expenditure:",
    df_lp["monthly_expenditure"].mean()
)

print(
    "Mean monthly EMI:",
    df_lp["monthly_emi"].mean()
)

print(
    "Mean calculated surplus:",
    df_lp["lp_monthly_surplus"].mean()
)

print(
    "Mean available surplus:",
    df_lp["lp_available_surplus"].mean()
)

print(
    "Users with positive surplus:",
    (df_lp["lp_monthly_surplus"] > 0).sum()
)

print(
    "Users with zero/negative surplus:",
    (df_lp["lp_monthly_surplus"] <= 0).sum()
)

# ------------------------------------------------------------
# 4. Goal information
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("GOAL INFORMATION")
print("-" * 70)

print(
    "Mean target amount:",
    df_lp["target_amount"].mean()
)

print(
    "Median target amount:",
    df_lp["target_amount"].median()
)

print(
    "Mean goal horizon:",
    df_lp["goal_horizon_months"].mean()
)

print(
    "Minimum goal horizon:",
    df_lp["goal_horizon_months"].min()
)

print(
    "Maximum goal horizon:",
    df_lp["goal_horizon_months"].max()
)

# ------------------------------------------------------------
# 5. Risk information
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("RISK INFORMATION")
print("-" * 70)

print(
    "Risk profile distribution:"
)

display(
    df_lp["risk_profile"]
    .value_counts()
    .to_frame("count")
)

print(
    "\nRisk score range:",
    df_lp["risk_score"].min(),
    "to",
    df_lp["risk_score"].max()
)

# ------------------------------------------------------------
# 6. Investment capacity
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("INVESTMENT CAPACITY")
print("-" * 70)

print(
    "Investment capacity ratio range:",
    df_lp["investment_capacity_ratio"].min(),
    "to",
    df_lp["investment_capacity_ratio"].max()
)

print(
    "Mean investment capacity ratio:",
    df_lp["investment_capacity_ratio"].mean()
)

# ------------------------------------------------------------
# 7. Baseline outcomes
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BASELINE OUTCOME")
print("-" * 70)

display(
    df_lp["goal_outcome"]
    .value_counts()
    .to_frame("count")
)

print(
    "\nMean baseline goal shortfall:",
    df_lp["goal_shortfall_actual"].mean()
)

print(
    "Median baseline goal shortfall:",
    df_lp["goal_shortfall_actual"].median()
)

# ------------------------------------------------------------
# 8. Check newly calculated LP fields
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("LP DERIVED VARIABLES")
print("-" * 70)

display(
    df_lp[
        [
            "user_id",
            "monthly_income",
            "monthly_expenditure",
            "monthly_emi",
            "lp_monthly_surplus",
            "lp_available_surplus",
            "target_amount",
            "goal_horizon_months",
            "investment_capacity_ratio",
            "risk_score"
        ]
    ].head(10)
)

# ------------------------------------------------------------
# 9. Safety checks
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("SAFETY CHECKS")
print("-" * 70)

print(
    "NaN in LP surplus:",
    df_lp["lp_monthly_surplus"].isna().sum()
)

print(
    "Inf in LP surplus:",
    np.isinf(df_lp["lp_monthly_surplus"]).sum()
)

print(
    "Negative available surplus:",
    (df_lp["lp_available_surplus"] < 0).sum()
)

print("\n" + "=" * 70)
print("STEP 2B COMPLETE")
print("=" * 70)

======================================================================
GOALPILOT AI — LP INPUT VALIDATION
======================================================================

✅ All required LP columns are present.

----------------------------------------------------------------------
FINANCIAL CAPACITY
----------------------------------------------------------------------
Mean monthly income: 61588.31165257671
Mean monthly expenditure: 44971.4612
Mean monthly EMI: 5195.490809696185
Mean calculated surplus: 11421.35964288052
Mean available surplus: 12896.268635809962
Users with positive surplus: 7870
Users with zero/negative surplus: 2130

----------------------------------------------------------------------
GOAL INFORMATION
----------------------------------------------------------------------
Mean target amount: 138353.8349725079
Median target amount: 107313.05542741461
Mean goal horizon: 62.697
Minimum goal horizon: 6
Maximum goal horizon: 120

----------------------------------------------------------------------
RISK INFORMATION
----------------------------------------------------------------------
Risk profile distribution:

              count
risk_profile
moderate       3334
aggressive     3333
conservative   3333

Risk score range: 0.0282624999999999 to 0.854

----------------------------------------------------------------------
INVESTMENT CAPACITY
----------------------------------------------------------------------
Investment capacity ratio range: 0.0 to 0.4999763383132914
Mean investment capacity ratio: 0.18722809767877036

----------------------------------------------------------------------
BASELINE OUTCOME
----------------------------------------------------------------------

              count
goal_outcome
success        6451
failure        3549

Mean baseline goal shortfall: 30580.490390871095
Median baseline goal shortfall: 0.0

----------------------------------------------------------------------
LP DERIVED VARIABLES
----------------------------------------------------------------------

,user_id,monthly_income,monthly_expenditure,monthly_emi,lp_monthly_surplus,lp_available_surplus,target_amount,goal_horizon_months,investment_capacity_ratio,risk_score
0,USER_00001,51351.335334,36870.0,0.000000,14481.335334,14481.335334,115357.183592,48,0.282005,0.710500
1,USER_00002,26415.417334,27500.0,11814.371436,-12898.954102,0.000000,59340.387689,51,0.000000,0.038363
2,USER_00003,44467.548430,42000.0,0.000000,2467.548430,2467.548430,99893.237726,46,0.055491,0.505350
3,USER_00004,33598.333991,25500.0,7052.590854,1045.743136,1045.743136,75476.307623,60,0.031125,0.313650
4,USER_00005,91719.010189,51000.0,0.000000,40719.010189,40719.010189,206040.342056,120,0.443954,0.750750
5,USER_00006,49096.549442,27000.0,0.000000,22096.549442,22096.549442,110291.964774,18,0.450063,0.823150
6,USER_00007,56988.382060,30000.0,0.000000,26988.382060,26988.382060,128020.414837,75,0.473577,0.762325
7,USER_00008,120153.382912,100000.0,24786.376525,-4632.993613,0.000000,269916.171830,11,0.000000,0.087587
8,USER_00009,81284.850834,54000.0,0.000000,27284.850834,27284.850834,182600.732773,55,0.335670,0.688500
9,USER_00010,43047.201045,38000.0,0.000000,5047.201045,5047.201045,96702.526658,24,0.117248,0.533300

----------------------------------------------------------------------
SAFETY CHECKS
----------------------------------------------------------------------
NaN in LP surplus: 0
Inf in LP surplus: 0
Negative available surplus: 0

======================================================================
STEP 2B COMPLETE
======================================================================

In [83]:
# ============================================================
# GOALPILOT AI — STEP 3A
# ECONOMIC SCENARIO FILE AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 70)
print("GOALPILOT AI — ECONOMIC SCENARIO AUDIT")
print("=" * 70)

# ------------------------------------------------------------
# Existing project directories
# ------------------------------------------------------------

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"
SIM_DIR = os.path.join(BASE_DIR, "simulation")
ENV_DIR = os.path.join(SIM_DIR, "04_economic_environment")

FINAL_INPUT_DIR = "/content/drive/MyDrive/final_simulation_inputs"

print("\nBASE PROJECT:")
print(BASE_DIR)

print("\nECONOMIC ENVIRONMENT DIRECTORY:")
print(ENV_DIR)

print("\nPREPARED INPUT DIRECTORY:")
print(FINAL_INPUT_DIR)

# ------------------------------------------------------------
# 1. Check directories
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("DIRECTORY STATUS")
print("-" * 70)

for path in [BASE_DIR, SIM_DIR, ENV_DIR, FINAL_INPUT_DIR]:

    print(
        f"{path:<75}",
        "EXISTS" if os.path.exists(path) else "NOT FOUND"
    )

# ------------------------------------------------------------
# 2. List economic environment directory
# ------------------------------------------------------------

if os.path.exists(ENV_DIR):

    print("\n" + "-" * 70)
    print("FILES IN 04_economic_environment")
    print("-" * 70)

    env_files = sorted(os.listdir(ENV_DIR))

    if len(env_files) == 0:
        print("Directory is empty.")

    else:
        for f in env_files:

            full_path = os.path.join(ENV_DIR, f)

            if os.path.isfile(full_path):

                size_mb = os.path.getsize(full_path) / (1024 ** 2)

                print(
                    f"{f:<60} "
                    f"{size_mb:>8.2f} MB"
                )

# ------------------------------------------------------------
# 3. List prepared simulation inputs
# ------------------------------------------------------------

if os.path.exists(FINAL_INPUT_DIR):

    print("\n" + "-" * 70)
    print("FILES IN final_simulation_inputs")
    print("-" * 70)

    prepared_files = sorted(os.listdir(FINAL_INPUT_DIR))

    for f in prepared_files:

        full_path = os.path.join(FINAL_INPUT_DIR, f)

        if os.path.isfile(full_path):

            size_mb = os.path.getsize(full_path) / (1024 ** 2)

            print(
                f"{f:<60} "
                f"{size_mb:>8.2f} MB"
            )

# ------------------------------------------------------------
# 4. Search entire GoalPilot_AI project for CSV files
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("ALL CSV FILES UNDER GoalPilot_AI")
print("-" * 70)

csv_files = []

for root, dirs, files in os.walk(BASE_DIR):

    for f in files:

        if f.lower().endswith(".csv"):

            full_path = os.path.join(root, f)

            csv_files.append(full_path)

for path in sorted(csv_files):

    rel_path = os.path.relpath(path, BASE_DIR)

    size_mb = os.path.getsize(path) / (1024 ** 2)

    print(
        f"{rel_path:<90} "
        f"{size_mb:>8.2f} MB"
    )

print("\nTotal CSV files found:", len(csv_files))

# ------------------------------------------------------------
# 5. Identify likely economic files by filename
# ------------------------------------------------------------

keywords = [
    "market",
    "nifty",
    "cpi",
    "inflation",
    "walr",
    "credit",
    "environment",
    "scenario"
]

candidate_files = []

for path in csv_files:

    filename = os.path.basename(path).lower()

    if any(keyword in filename for keyword in keywords):

        candidate_files.append(path)

print("\n" + "-" * 70)
print("LIKELY ECONOMIC / SCENARIO FILES")
print("-" * 70)

for path in sorted(candidate_files):

    print(
        os.path.relpath(path, BASE_DIR)
    )

print("\nCandidate count:", len(candidate_files))

# ------------------------------------------------------------
# 6. Inspect candidate CSV structures
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CANDIDATE FILE STRUCTURES")
print("=" * 70)

for path in sorted(candidate_files):

    print("\n" + "-" * 70)
    print(
        os.path.relpath(path, BASE_DIR)
    )
    print("-" * 70)

    try:

        temp = pd.read_csv(path)

        print("Shape:", temp.shape)

        print("\nColumns:")

        for i, col in enumerate(temp.columns, start=1):

            print(f"{i:2d}. {col}")

        print("\nData types:")

        print(temp.dtypes)

        print("\nMissing values:")

        missing = temp.isna().sum()

        missing = missing[missing > 0]

        if len(missing) == 0:

            print("None")

        else:

            print(missing)

        print("\nFirst 3 rows:")

        display(temp.head(3))

    except Exception as e:

        print("ERROR READING FILE:")
        print(type(e).__name__, str(e))

print("\n" + "=" * 70)
print("STEP 3A COMPLETE")
print("=" * 70)

======================================================================
GOALPILOT AI — ECONOMIC SCENARIO AUDIT
======================================================================

BASE PROJECT:
/content/drive/MyDrive/GoalPilot_AI

ECONOMIC ENVIRONMENT DIRECTORY:
/content/drive/MyDrive/GoalPilot_AI/simulation/04_economic_environment

PREPARED INPUT DIRECTORY:
/content/drive/MyDrive/final_simulation_inputs

----------------------------------------------------------------------
DIRECTORY STATUS
----------------------------------------------------------------------
/content/drive/MyDrive/GoalPilot_AI                                         EXISTS
/content/drive/MyDrive/GoalPilot_AI/simulation                              EXISTS
/content/drive/MyDrive/GoalPilot_AI/simulation/04_economic_environment      EXISTS
/content/drive/MyDrive/final_simulation_inputs                              EXISTS

----------------------------------------------------------------------
FILES IN 04_economic_environment
----------------------------------------------------------------------
economic_environment.csv                                         0.04 MB

----------------------------------------------------------------------
FILES IN final_simulation_inputs
----------------------------------------------------------------------
cpi_historical_calibration.csv                                   0.01 MB
cpi_scaled.csv                                                   0.01 MB
household_profiles.csv                                          23.82 MB
household_scaled.csv                                           101.23 MB
market_credit_scenarios.csv                                      0.03 MB
market_scaled.csv                                                0.03 MB
walr_scaled.csv                                                  0.00 MB

----------------------------------------------------------------------
ALL CSV FILES UNDER GoalPilot_AI
----------------------------------------------------------------------
optimization/lp_inputs/economic_scenario_diagnostic.csv                                        0.01 MB
optimization/lp_inputs/lp_5c_user_diagnostics.csv                                              2.60 MB
optimization/lp_inputs/lp_5d1_existing_goal_funding_audit.csv                                  1.78 MB
optimization/lp_inputs/lp_5d1_missing_value_audit.csv                                          0.00 MB
optimization/lp_inputs/lp_5e_goal_funding_logic_files.csv                                      0.00 MB
optimization/lp_inputs/lp_5f_simulation_column_inventory.csv                                   0.00 MB
optimization/lp_inputs/lp_5f_simulation_relationship_audit.csv                                 0.00 MB
optimization/lp_inputs/lp_5g_goal_funding_reconstruction_results.csv                           0.00 MB
optimization/lp_inputs/lp_5g_horizon_funding_reconstruction_results.csv                        0.00 MB
optimization/lp_inputs/lp_5g_user_funding_state_audit.csv                                      3.66 MB
optimization/lp_inputs/lp_5h_goal_funding_aggregation_audit.csv                                3.31 MB
optimization/lp_inputs/lp_5h_goal_funding_aggregation_comparison.csv                           0.00 MB
optimization/lp_inputs/lp_5i_goal_funding_formula_audit.csv                                    4.00 MB
optimization/lp_inputs/lp_5i_goal_funding_formula_candidates.csv                               0.00 MB
optimization/lp_inputs/lp_5j_constraint_audit.csv                                              0.00 MB
optimization/lp_inputs/lp_5j_data_support_audit.csv                                            0.00 MB
optimization/lp_inputs/lp_5j_decision_variable_audit.csv                                       0.00 MB
optimization/lp_inputs/lp_5j_formulation_warnings.csv                                          0.00 MB
optimization/lp_inputs/lp_5j_objective_audit.csv                                               0.00 MB
optimization/lp_inputs/lp_5j_parameter_mapping.csv                                             0.00 MB
optimization/lp_inputs/lp_5k_target_formulation_comparison.csv                                 0.06 MB
optimization/lp_inputs/lp_5k_target_objective_formulation_audit.csv                            5.71 MB
optimization/lp_inputs/lp_5l1_feasibility_boundary_audit.csv                                   6.68 MB
optimization/lp_inputs/lp_5l1_feasibility_by_financial_situation.csv                           0.00 MB
optimization/lp_inputs/lp_5l1_feasibility_by_risk_profile.csv                                  0.00 MB
optimization/lp_inputs/lp_5l2_financial_comparison.csv                                         0.00 MB
optimization/lp_inputs/lp_5l2_policy_vs_optimization_audit.csv                                 2.37 MB
optimization/lp_inputs/lp_5l2_risk_comparison.csv                                              0.00 MB
optimization/lp_inputs/lp_5m_investment_tradeoff_audit.csv                                     2.66 MB
optimization/lp_inputs/lp_5m_investment_tradeoff_by_financial_situation.csv                    0.00 MB
optimization/lp_inputs/lp_5m_investment_tradeoff_by_risk.csv                                   0.00 MB
optimization/lp_inputs/lp_5n_actual_portfolio_evolution_audit.csv                              0.00 MB
optimization/lp_inputs/lp_5n_actual_portfolio_user_summary.csv                                 2.10 MB
optimization/lp_inputs/lp_5n_initial_investment_vs_first_portfolio.csv                         0.95 MB
optimization/lp_inputs/lp_5n_unexplained_portfolio_change.csv                                114.25 MB
optimization/lp_inputs/lp_constraint_mapping_audit.csv                                         0.00 MB
optimization/lp_inputs/lp_decision_variable_constraint_mapping.csv                             0.00 MB
optimization/lp_inputs/lp_existing_logic_audit.csv                                             2.21 MB
optimization/lp_inputs/lp_formulation_precheck.csv                                             3.28 MB
optimization/lp_inputs/lp_initial_savings_case_comparison.csv                                  0.00 MB
optimization/lp_inputs/lp_input_formulation_audit.csv                                          0.00 MB
optimization/lp_inputs/lp_representative_users_precheck.csv                                    0.00 MB
optimization/lp_inputs/nifty_walr_reconstruction_audit.csv                                     0.04 MB
simulation/01_input_data/cpi_historical_calibration.csv                                        0.01 MB
simulation/01_input_data/cpi_scaled.csv                                                        0.01 MB
simulation/01_input_data/household_profiles.csv                                               23.82 MB
simulation/01_input_data/household_scaled.csv                                                101.23 MB
simulation/01_input_data/market_credit_scenarios.csv                                           0.03 MB
simulation/01_input_data/market_scaled.csv                                                     0.03 MB
simulation/01_input_data/walr_scaled.csv                                                       0.00 MB
simulation/02_synthetic_population/synthetic_population_base.csv                               1.15 MB
simulation/02_synthetic_population/synthetic_population_income.csv                             2.00 MB
simulation/03_financial_profiles/synthetic_population_debt.csv                                 2.80 MB
simulation/03_financial_profiles/synthetic_population_investment.csv                           4.73 MB
simulation/03_financial_profiles/synthetic_population_risk.csv                                 5.54 MB
simulation/03_financial_profiles/synthetic_population_savings.csv                              2.35 MB
simulation/04_economic_environment/economic_environment.csv                                    0.04 MB
simulation/05_simulation_runs/monthly_financial_simulation_base.csv                          914.89 MB
simulation/05_simulation_runs/portfolio_simulation_validated.csv                             161.28 MB
simulation/06_results/final_goal_outcome_dataset.csv                                           1.93 MB
simulation/06_results/final_optimisation_input.csv                                             4.53 MB
simulation/06_results/final_simulation_summary.csv                                             0.00 MB
simulation/06_results/goal_success_by_financial_situation.csv                                  0.00 MB
simulation/06_results/goal_success_by_horizon.csv                                              0.00 MB
simulation/06_results/goal_success_by_risk_profile.csv                                         0.00 MB
simulation/06_results/simulation_methodology_and_assumptions.csv                               0.00 MB
simulation/07_validation/final_simulation_validation.csv                                       0.00 MB
simulation/07_validation/goal_success_validation_by_financial_situation.csv                    0.00 MB
simulation/07_validation/goal_success_validation_by_horizon.csv                                0.00 MB
simulation/07_validation/goal_success_validation_by_risk_profile.csv                           0.00 MB
simulation/07_validation/simulation_methodology_validation.csv                                 0.00 MB

Total CSV files found: 71

----------------------------------------------------------------------
LIKELY ECONOMIC / SCENARIO FILES
----------------------------------------------------------------------
optimization/lp_inputs/economic_scenario_diagnostic.csv
optimization/lp_inputs/nifty_walr_reconstruction_audit.csv
simulation/01_input_data/cpi_historical_calibration.csv
simulation/01_input_data/cpi_scaled.csv
simulation/01_input_data/market_credit_scenarios.csv
simulation/01_input_data/market_scaled.csv
simulation/01_input_data/walr_scaled.csv
simulation/04_economic_environment/economic_environment.csv

Candidate count: 8

======================================================================
CANDIDATE FILE STRUCTURES
======================================================================

----------------------------------------------------------------------
optimization/lp_inputs/economic_scenario_diagnostic.csv
----------------------------------------------------------------------
Shape: (144, 6)

Columns:
 1. year_month
 2. period
 3. inflation_level
 4. reconstructed_combined_inflation
 5. nifty_monthly_return
 6. average_walr

Data types:
year_month                           object
period                               object
inflation_level                     float64
reconstructed_combined_inflation    float64
nifty_monthly_return                float64
average_walr                        float64
dtype: object

Missing values:
nifty_monthly_return     1
average_walr            99
dtype: int64

First 3 rows:

,year_month,period,inflation_level,reconstructed_combined_inflation,nifty_monthly_return,average_walr
0,2015-01,2015-01-01,0.805801,9.838710,NaN,NaN
1,2015-02,2015-02-01,0.762137,9.540669,0.004053,NaN
2,2015-03,2015-03-01,0.179194,5.561614,-0.039979,11.79

----------------------------------------------------------------------
optimization/lp_inputs/nifty_walr_reconstruction_audit.csv
----------------------------------------------------------------------
Shape: (144, 22)

Columns:
 1. period
 2. inflation_level
 3. inflation_change
 4. inflation_pct_change
 5. inflation_trend
 6. inflation_regime
 7. nifty_monthly_return
 8. nifty_return_volatility
 9. nifty_3m_volatility
10. nifty_ma_gap
11. market_return_regime
12. market_volatility_regime
13. average_walr
14. walr_change
15. credit_pressure
16. walr_3period_ma
17. walr_momentum
18. walr_regime
19. reconstructed_nifty_return
20. reconstructed_walr
21. nifty_nearest_difference
22. walr_nearest_difference

Data types:
period                         object
inflation_level               float64
inflation_change              float64
inflation_pct_change          float64
inflation_trend               float64
inflation_regime               object
nifty_monthly_return          float64
nifty_return_volatility       float64
nifty_3m_volatility           float64
nifty_ma_gap                  float64
market_return_regime           object
market_volatility_regime       object
average_walr                  float64
walr_change                   float64
credit_pressure               float64
walr_3period_ma               float64
walr_momentum                 float64
walr_regime                    object
reconstructed_nifty_return    float64
reconstructed_walr            float64
nifty_nearest_difference      float64
walr_nearest_difference       float64
dtype: object

Missing values:
None

First 3 rows:

,period,inflation_level,inflation_change,inflation_pct_change,inflation_trend,inflation_regime,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,...,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum,walr_regime,reconstructed_nifty_return,reconstructed_walr,nifty_nearest_difference,walr_nearest_difference
0,2015-01-01,0.805801,0.790319,0.790319,0.732548,high,0.637516,0.027470,0.175845,0.714584,...,0.939462,0.266330,1.0,0.40488,0.315726,high,0.009323,11.85,2.428613e-17,0.0
1,2015-02-01,0.762137,0.204009,0.204009,0.207738,medium,0.623620,0.218661,0.175845,0.714584,...,0.939462,0.266330,1.0,0.40488,0.315726,high,0.004053,11.85,3.903128e-17,0.0
2,2015-03-01,0.179194,0.411640,0.411640,0.995795,low,0.507522,0.169805,0.175845,0.590410,...,0.920344,0.437711,1.0,1.00000,0.289898,high,-0.039979,11.79,1.387779e-17,0.0

----------------------------------------------------------------------
simulation/01_input_data/cpi_historical_calibration.csv
----------------------------------------------------------------------
Shape: (48, 11)

Columns:
 1. period
 2. rural_cpi
 3. urban_cpi
 4. combined_cpi
 5. rural_inflation
 6. urban_inflation
 7. combined_inflation
 8. combined_cpi_change
 9. combined_cpi_pct_change
10. rural_urban_avg_cpi
11. combined_cpi_3m_ma

Data types:
period                      object
rural_cpi                  float64
urban_cpi                  float64
combined_cpi               float64
rural_inflation            float64
urban_inflation            float64
combined_inflation         float64
combined_cpi_change        float64
combined_cpi_pct_change    float64
rural_urban_avg_cpi        float64
combined_cpi_3m_ma         float64
dtype: object

Missing values:
None

First 3 rows:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
0,2011-01-01,107.1,104.2,105.9,9.236837,9.70493,9.540669,0.007241,0.007241,105.65,126.05
1,2011-02-01,106.5,103.7,105.3,9.236837,9.70493,9.540669,-0.005666,-0.005666,105.10,126.05
2,2011-03-01,106.9,103.9,105.6,9.236837,9.70493,9.540669,0.002849,0.002849,105.40,105.60

----------------------------------------------------------------------
simulation/01_input_data/cpi_scaled.csv
----------------------------------------------------------------------
Shape: (48, 11)

Columns:
 1. period
 2. rural_cpi
 3. urban_cpi
 4. combined_cpi
 5. rural_inflation
 6. urban_inflation
 7. combined_inflation
 8. combined_cpi_change
 9. combined_cpi_pct_change
10. rural_urban_avg_cpi
11. combined_cpi_3m_ma

Data types:
period                      object
rural_cpi                  float64
urban_cpi                  float64
combined_cpi               float64
rural_inflation            float64
urban_inflation            float64
combined_inflation         float64
combined_cpi_change        float64
combined_cpi_pct_change    float64
rural_urban_avg_cpi        float64
combined_cpi_3m_ma         float64
dtype: object

Missing values:
None

First 3 rows:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
0,2011-01-01,0.014634,0.012723,0.014925,0.681068,0.739506,0.762137,0.622888,0.622888,0.013733,0.51598
1,2011-02-01,0.000000,0.000000,0.000000,0.681068,0.739506,0.762137,0.157750,0.157750,0.000000,0.51598
2,2011-03-01,0.009756,0.005089,0.007463,0.681068,0.739506,0.762137,0.464605,0.464605,0.007491,0.00000

----------------------------------------------------------------------
simulation/01_input_data/market_credit_scenarios.csv
----------------------------------------------------------------------
Shape: (146, 17)

Columns:
 1. period
 2. nifty_open
 3. nifty_high
 4. nifty_low
 5. nifty_close
 6. nifty_avg_close
 7. nifty_total_volume
 8. nifty_avg_daily_return
 9. nifty_return_volatility
10. nifty_monthly_return
11. nifty_3m_volatility
12. nifty_3m_ma
13. nifty_ma_gap
14. average_walr
15. walr_change
16. walr_pct_change
17. walr_momentum

Data types:
period                      object
nifty_open                 float64
nifty_high                 float64
nifty_low                  float64
nifty_close                float64
nifty_avg_close            float64
nifty_total_volume         float64
nifty_avg_daily_return     float64
nifty_return_volatility    float64
nifty_monthly_return       float64
nifty_3m_volatility        float64
nifty_3m_ma                float64
nifty_ma_gap               float64
average_walr               float64
walr_change                float64
walr_pct_change            float64
walr_momentum              float64
dtype: object

Missing values:
nifty_open                  2
nifty_high                  2
nifty_low                   2
nifty_close                 2
nifty_avg_close             2
nifty_total_volume          2
nifty_avg_daily_return      2
nifty_return_volatility     2
nifty_monthly_return        3
nifty_3m_volatility         5
nifty_3m_ma                 4
nifty_ma_gap                4
average_walr               99
walr_change                99
walr_pct_change            99
walr_momentum              99
dtype: int64

First 3 rows:

,period,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap,average_walr,walr_change,walr_pct_change,walr_momentum
0,2014-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.04,-0.063321,-0.006237,-0.086667
1,2014-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.85,-0.190000,-0.015781,-0.086667
2,2015-01-01,8433.400391,8952.349609,7785.850098,8808.900391,8517.880561,3155600.0,0.001717,0.024584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

----------------------------------------------------------------------
simulation/01_input_data/market_scaled.csv
----------------------------------------------------------------------
Shape: (144, 13)

Columns:
 1. period
 2. nifty_open
 3. nifty_high
 4. nifty_low
 5. nifty_close
 6. nifty_avg_close
 7. nifty_total_volume
 8. nifty_avg_daily_return
 9. nifty_return_volatility
10. nifty_monthly_return
11. nifty_3m_volatility
12. nifty_3m_ma
13. nifty_ma_gap

Data types:
period                      object
nifty_open                 float64
nifty_high                 float64
nifty_low                  float64
nifty_close                float64
nifty_avg_close            float64
nifty_total_volume         float64
nifty_avg_daily_return     float64
nifty_return_volatility    float64
nifty_monthly_return       float64
nifty_3m_volatility        float64
nifty_3m_ma                float64
nifty_ma_gap               float64
dtype: object

Missing values:
None

First 3 rows:

,period,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap
0,2015-01-01,0.063711,0.020308,0.049571,0.094810,0.055464,0.098835,0.468737,0.027470,0.637516,0.175845,0.342082,0.714584
1,2015-02-01,0.061725,0.020557,0.045385,0.096667,0.059289,0.094047,0.445944,0.218661,0.623620,0.175845,0.342082,0.714584
2,2015-03-01,0.080619,0.022784,0.051830,0.078266,0.052741,0.117774,0.347115,0.169805,0.507522,0.175845,0.069138,0.590410

----------------------------------------------------------------------
simulation/01_input_data/walr_scaled.csv
----------------------------------------------------------------------
Shape: (47, 7)

Columns:
 1. period
 2. average_walr
 3. walr_change
 4. walr_pct_change
 5. credit_pressure
 6. walr_3period_ma
 7. walr_momentum

Data types:
period              object
average_walr       float64
walr_change        float64
walr_pct_change    float64
credit_pressure    float64
walr_3period_ma    float64
walr_momentum      float64
dtype: object

Missing values:
None

First 3 rows:

,period,average_walr,walr_change,walr_pct_change,credit_pressure,walr_3period_ma,walr_momentum
0,2014-03-01,1.000000,0.433333,0.419612,1.0,0.40488,0.315726
1,2014-12-01,0.939462,0.266330,0.296640,1.0,0.40488,0.315726
2,2015-03-01,0.920344,0.437711,0.434739,1.0,1.00000,0.289898

----------------------------------------------------------------------
simulation/04_economic_environment/economic_environment.csv
----------------------------------------------------------------------
Shape: (144, 18)

Columns:
 1. period
 2. inflation_level
 3. inflation_change
 4. inflation_pct_change
 5. inflation_trend
 6. inflation_regime
 7. nifty_monthly_return
 8. nifty_return_volatility
 9. nifty_3m_volatility
10. nifty_ma_gap
11. market_return_regime
12. market_volatility_regime
13. average_walr
14. walr_change
15. credit_pressure
16. walr_3period_ma
17. walr_momentum
18. walr_regime

Data types:
period                       object
inflation_level             float64
inflation_change            float64
inflation_pct_change        float64
inflation_trend             float64
inflation_regime             object
nifty_monthly_return        float64
nifty_return_volatility     float64
nifty_3m_volatility         float64
nifty_ma_gap                float64
market_return_regime         object
market_volatility_regime     object
average_walr                float64
walr_change                 float64
credit_pressure             float64
walr_3period_ma             float64
walr_momentum               float64
walr_regime                  object
dtype: object

Missing values:
None

First 3 rows:

,period,inflation_level,inflation_change,inflation_pct_change,inflation_trend,inflation_regime,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,market_return_regime,market_volatility_regime,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum,walr_regime
0,2015-01-01,0.805801,0.790319,0.790319,0.732548,high,0.637516,0.027470,0.175845,0.714584,medium,low,0.939462,0.266330,1.0,0.40488,0.315726,high
1,2015-02-01,0.762137,0.204009,0.204009,0.207738,medium,0.623620,0.218661,0.175845,0.714584,medium,high,0.939462,0.266330,1.0,0.40488,0.315726,high
2,2015-03-01,0.179194,0.411640,0.411640,0.995795,low,0.507522,0.169805,0.175845,0.590410,low,medium,0.920344,0.437711,1.0,1.00000,0.289898,high

======================================================================
STEP 3A COMPLETE
======================================================================

In [84]:
# ============================================================
# GOALPILOT AI — STEP 3C
# RAW vs SCALED ECONOMIC SCENARIO VALIDATION
# ============================================================

import os
import pandas as pd
import numpy as np

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

ENV_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "04_economic_environment",
    "economic_environment.csv"
)

CPI_RAW_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "cpi_historical_calibration.csv"
)

CPI_SCALED_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "cpi_scaled.csv"
)

MARKET_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "market_scaled.csv"
)

WALR_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "walr_scaled.csv"
)

MARKET_CREDIT_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "market_credit_scenarios.csv"
)

print("=" * 80)
print("GOALPILOT AI — RAW / SCALED ECONOMIC VARIABLE AUDIT")
print("=" * 80)


# ------------------------------------------------------------
# Helper function
# ------------------------------------------------------------

def inspect_file(path, name):

    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)

    print("Path:", path)

    if not os.path.exists(path):

        print("❌ FILE NOT FOUND")
        return None

    df = pd.read_csv(path)

    print("Shape:", df.shape)

    print("\nColumns:")
    for i, col in enumerate(df.columns, 1):
        print(f"{i:2d}. {col}")

    print("\nNumeric ranges:")

    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns

    if len(numeric_cols) > 0:

        summary = pd.DataFrame({
            "min": df[numeric_cols].min(),
            "max": df[numeric_cols].max(),
            "mean": df[numeric_cols].mean(),
            "median": df[numeric_cols].median(),
            "missing": df[numeric_cols].isna().sum(),
            "inf": [
                np.isinf(df[c].to_numpy()).sum()
                for c in numeric_cols
            ]
        })

        display(summary)

    print("\nFirst 5 rows:")
    display(df.head())

    return df


# ------------------------------------------------------------
# 1. Complete economic environment
# ------------------------------------------------------------

df_environment = inspect_file(
    ENV_FILE,
    "1. COMPLETE ECONOMIC ENVIRONMENT"
)


# ------------------------------------------------------------
# 2. CPI historical calibration
# ------------------------------------------------------------

df_cpi_raw = inspect_file(
    CPI_RAW_FILE,
    "2. CPI HISTORICAL CALIBRATION"
)


# ------------------------------------------------------------
# 3. CPI scaled
# ------------------------------------------------------------

df_cpi_scaled = inspect_file(
    CPI_SCALED_FILE,
    "3. CPI SCALED"
)


# ------------------------------------------------------------
# 4. NIFTY / market scaled file
# ------------------------------------------------------------

df_market = inspect_file(
    MARKET_FILE,
    "4. NIFTY MARKET FILE"
)


# ------------------------------------------------------------
# 5. WALR scaled file
# ------------------------------------------------------------

df_walr = inspect_file(
    WALR_FILE,
    "5. WALR FILE"
)


# ------------------------------------------------------------
# 6. Market-credit scenario file
# ------------------------------------------------------------

df_market_credit = inspect_file(
    MARKET_CREDIT_FILE,
    "6. MARKET CREDIT SCENARIOS"
)


# ------------------------------------------------------------
# 7. Economic environment numerical sanity check
# ------------------------------------------------------------

if df_environment is not None:

    print("\n" + "=" * 80)
    print("ECONOMIC ENVIRONMENT — POTENTIAL LP VARIABLES")
    print("=" * 80)

    candidate_columns = [
        "inflation_level",
        "inflation_change",
        "inflation_pct_change",
        "nifty_monthly_return",
        "nifty_return_volatility",
        "nifty_3m_volatility",
        "nifty_ma_gap",
        "average_walr",
        "walr_change",
        "walr_pct_change",
        "credit_pressure",
        "walr_3period_ma",
        "walr_momentum"
    ]

    existing_candidates = [
        c for c in candidate_columns
        if c in df_environment.columns
    ]

    if existing_candidates:

        display(
            df_environment[
                existing_candidates
            ].describe().T
        )

    else:

        print("No candidate columns found.")


print("\n" + "=" * 80)
print("STEP 3C COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — RAW / SCALED ECONOMIC VARIABLE AUDIT
================================================================================

================================================================================
1. COMPLETE ECONOMIC ENVIRONMENT
================================================================================
Path: /content/drive/MyDrive/GoalPilot_AI/simulation/04_economic_environment/economic_environment.csv
Shape: (144, 18)

Columns:
 1. period
 2. inflation_level
 3. inflation_change
 4. inflation_pct_change
 5. inflation_trend
 6. inflation_regime
 7. nifty_monthly_return
 8. nifty_return_volatility
 9. nifty_3m_volatility
10. nifty_ma_gap
11. market_return_regime
12. market_volatility_regime
13. average_walr
14. walr_change
15. credit_pressure
16. walr_3period_ma
17. walr_momentum
18. walr_regime

Numeric ranges:

                         min       max      mean    median  missing  inf
inflation_level          0.0  0.945091  0.677915  0.762137        0    0
inflation_change         0.0  1.000000  0.599643  0.634226        0    0
inflation_pct_change     0.0  1.000000  0.599643  0.634226        0    0
inflation_trend          0.0  1.000000  0.526449  0.539108        0    0
nifty_monthly_return     0.0  1.000000  0.634001  0.637516        0    0
nifty_return_volatility  0.0  1.000000  0.189451  0.152372        0    0
nifty_3m_volatility      0.0  1.000000  0.196064  0.175845        0    0
nifty_ma_gap             0.0  1.000000  0.709424  0.714584        0    0
average_walr             0.0  0.939462  0.417464  0.410649        0    0
walr_change              0.0  1.000000  0.437729  0.423969        0    0
credit_pressure          0.0  1.000000  0.638889  1.000000        0    0
walr_3period_ma          0.0  1.000000  0.421346  0.403942        0    0
walr_momentum            0.0  1.000000  0.354590  0.312728        0    0

First 5 rows:

,period,inflation_level,inflation_change,inflation_pct_change,inflation_trend,inflation_regime,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,market_return_regime,market_volatility_regime,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum,walr_regime
0,2015-01-01,0.805801,0.790319,0.790319,0.732548,high,0.637516,0.027470,0.175845,0.714584,medium,low,0.939462,0.266330,1.0,0.40488,0.315726,high
1,2015-02-01,0.762137,0.204009,0.204009,0.207738,medium,0.623620,0.218661,0.175845,0.714584,medium,high,0.939462,0.266330,1.0,0.40488,0.315726,high
2,2015-03-01,0.179194,0.411640,0.411640,0.995795,low,0.507522,0.169805,0.175845,0.590410,low,medium,0.920344,0.437711,1.0,1.00000,0.289898,high
3,2015-04-01,0.854063,0.732367,0.732367,0.770395,high,0.516826,0.237883,0.123433,0.545167,low,high,0.920344,0.437711,1.0,1.00000,0.289898,high
4,2015-05-01,0.776332,0.828178,0.828178,0.646762,medium,0.694196,0.064071,0.205132,0.712124,high,low,0.920344,0.437711,1.0,1.00000,0.289898,high

================================================================================
2. CPI HISTORICAL CALIBRATION
================================================================================
Path: /content/drive/MyDrive/GoalPilot_AI/simulation/01_input_data/cpi_historical_calibration.csv
Shape: (48, 11)

Columns:
 1. period
 2. rural_cpi
 3. urban_cpi
 4. combined_cpi
 5. rural_inflation
 6. urban_inflation
 7. combined_inflation
 8. combined_cpi_change
 9. combined_cpi_pct_change
10. rural_urban_avg_cpi
11. combined_cpi_3m_ma

Numeric ranges:

,min,max,mean,median,missing,inf
rural_cpi,106.500000,147.500000,127.339583,127.100000,0,0
urban_cpi,103.700000,143.000000,124.316667,124.450000,0,0
combined_cpi,105.300000,145.500000,126.031250,125.950000,0,0
rural_inflation,4.056437,11.662727,9.015934,9.236837,0,0
urban_inflation,4.692082,11.470728,9.167066,9.704930,0,0
combined_inflation,4.338473,11.164274,9.112749,9.540669,0,0
combined_cpi_change,-0.010043,0.017705,0.006710,0.007241,0,0
combined_cpi_pct_change,-0.010043,0.017705,0.006710,0.007241,0,0
rural_urban_avg_cpi,105.100000,145.150000,125.828125,125.750000,0,0
combined_cpi_3m_ma,105.600000,145.233333,126.059722,126.050000,0,0

First 5 rows:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
0,2011-01-01,107.1,104.2,105.9,9.236837,9.70493,9.540669,0.007241,0.007241,105.65,126.05
1,2011-02-01,106.5,103.7,105.3,9.236837,9.70493,9.540669,-0.005666,-0.005666,105.10,126.05
2,2011-03-01,106.9,103.9,105.6,9.236837,9.70493,9.540669,0.002849,0.002849,105.40,105.60
3,2011-04-01,107.5,104.5,106.2,9.236837,9.70493,9.540669,0.005682,0.005682,106.00,105.70
4,2011-05-01,108.7,105.0,107.1,9.236837,9.70493,9.540669,0.008475,0.008475,106.85,106.30

================================================================================
3. CPI SCALED
================================================================================
Path: /content/drive/MyDrive/GoalPilot_AI/simulation/01_input_data/cpi_scaled.csv
Shape: (48, 11)

Columns:
 1. period
 2. rural_cpi
 3. urban_cpi
 4. combined_cpi
 5. rural_inflation
 6. urban_inflation
 7. combined_inflation
 8. combined_cpi_change
 9. combined_cpi_pct_change
10. rural_urban_avg_cpi
11. combined_cpi_3m_ma

Numeric ranges:

                         min  max      mean    median  missing  inf
rural_cpi                0.0  1.0  0.508283  0.502439        0    0
urban_cpi                0.0  1.0  0.524597  0.527990        0    0
combined_cpi             0.0  1.0  0.515703  0.513682        0    0
rural_inflation          0.0  1.0  0.652026  0.681068        0    0
urban_inflation          0.0  1.0  0.660159  0.739506        0    0
combined_inflation       0.0  1.0  0.699445  0.762137        0    0
combined_cpi_change      0.0  1.0  0.603733  0.622888        0    0
combined_cpi_pct_change  0.0  1.0  0.603733  0.622888        0    0
rural_urban_avg_cpi      0.0  1.0  0.517556  0.515605        0    0
combined_cpi_3m_ma       0.0  1.0  0.516225  0.515980        0    0

First 5 rows:

,period,rural_cpi,urban_cpi,combined_cpi,rural_inflation,urban_inflation,combined_inflation,combined_cpi_change,combined_cpi_pct_change,rural_urban_avg_cpi,combined_cpi_3m_ma
0,2011-01-01,0.014634,0.012723,0.014925,0.681068,0.739506,0.762137,0.622888,0.622888,0.013733,0.515980
1,2011-02-01,0.000000,0.000000,0.000000,0.681068,0.739506,0.762137,0.157750,0.157750,0.000000,0.515980
2,2011-03-01,0.009756,0.005089,0.007463,0.681068,0.739506,0.762137,0.464605,0.464605,0.007491,0.000000
3,2011-04-01,0.024390,0.020356,0.022388,0.681068,0.739506,0.762137,0.566694,0.566694,0.022472,0.002523
4,2011-05-01,0.053659,0.033079,0.044776,0.681068,0.739506,0.762137,0.667339,0.667339,0.043695,0.017662

================================================================================
4. NIFTY MARKET FILE
================================================================================
Path: /content/drive/MyDrive/GoalPilot_AI/simulation/01_input_data/market_scaled.csv
Shape: (144, 13)

Columns:
 1. period
 2. nifty_open
 3. nifty_high
 4. nifty_low
 5. nifty_close
 6. nifty_avg_close
 7. nifty_total_volume
 8. nifty_avg_daily_return
 9. nifty_return_volatility
10. nifty_monthly_return
11. nifty_3m_volatility
12. nifty_3m_ma
13. nifty_ma_gap

Numeric ranges:

                         min  max      mean    median  missing  inf
nifty_open               0.0  1.0  0.404616  0.310506        0    0
nifty_high               0.0  1.0  0.450249  0.407175        0    0
nifty_low                0.0  1.0  0.428847  0.323472        0    0
nifty_close              0.0  1.0  0.434477  0.354973        0    0
nifty_avg_close          0.0  1.0  0.435123  0.355264        0    0
nifty_total_volume       0.0  1.0  0.294905  0.257196        0    0
nifty_avg_daily_return   0.0  1.0  0.449984  0.449489        0    0
nifty_return_volatility  0.0  1.0  0.189451  0.152372        0    0
nifty_monthly_return     0.0  1.0  0.634001  0.637516        0    0
nifty_3m_volatility      0.0  1.0  0.196064  0.175845        0    0
nifty_3m_ma              0.0  1.0  0.423568  0.342082        0    0
nifty_ma_gap             0.0  1.0  0.709424  0.714584        0    0

First 5 rows:

,period,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap
0,2015-01-01,0.063711,0.020308,0.049571,0.094810,0.055464,0.098835,0.468737,0.027470,0.637516,0.175845,0.342082,0.714584
1,2015-02-01,0.061725,0.020557,0.045385,0.096667,0.059289,0.094047,0.445944,0.218661,0.623620,0.175845,0.342082,0.714584
2,2015-03-01,0.080619,0.022784,0.051830,0.078266,0.052741,0.117774,0.347115,0.169805,0.507522,0.175845,0.069138,0.590410
3,2015-04-01,0.078900,0.018634,0.041618,0.062159,0.046457,0.127190,0.361995,0.237883,0.516826,0.123433,0.057887,0.545167
4,2015-05-01,0.060833,0.019485,0.059884,0.075281,0.046950,0.113081,0.473738,0.064071,0.694196,0.205132,0.050518,0.712124

================================================================================
5. WALR FILE
================================================================================
Path: /content/drive/MyDrive/GoalPilot_AI/simulation/01_input_data/walr_scaled.csv
Shape: (47, 7)

Columns:
 1. period
 2. average_walr
 3. walr_change
 4. walr_pct_change
 5. credit_pressure
 6. walr_3period_ma
 7. walr_momentum

Numeric ranges:

                 min  max      mean    median  missing  inf
average_walr     0.0  1.0  0.448440  0.422150        0    0
walr_change      0.0  1.0  0.437368  0.433333        0    0
walr_pct_change  0.0  1.0  0.428339  0.419612        0    0
credit_pressure  0.0  1.0  0.680851  1.000000        0    0
walr_3period_ma  0.0  1.0  0.435865  0.404880        0    0
walr_momentum    0.0  1.0  0.358015  0.315726        0    0

First 5 rows:

,period,average_walr,walr_change,walr_pct_change,credit_pressure,walr_3period_ma,walr_momentum
0,2014-03-01,1.000000,0.433333,0.419612,1.0,0.404880,0.315726
1,2014-12-01,0.939462,0.266330,0.296640,1.0,0.404880,0.315726
2,2015-03-01,0.920344,0.437711,0.434739,1.0,1.000000,0.289898
3,2015-06-01,0.888482,0.384979,0.390690,1.0,0.958939,0.315726
4,2015-09-01,0.856620,0.384979,0.389755,1.0,0.928436,0.295064

================================================================================
6. MARKET CREDIT SCENARIOS
================================================================================
Path: /content/drive/MyDrive/GoalPilot_AI/simulation/01_input_data/market_credit_scenarios.csv
Shape: (146, 17)

Columns:
 1. period
 2. nifty_open
 3. nifty_high
 4. nifty_low
 5. nifty_close
 6. nifty_avg_close
 7. nifty_total_volume
 8. nifty_avg_daily_return
 9. nifty_return_volatility
10. nifty_monthly_return
11. nifty_3m_volatility
12. nifty_3m_ma
13. nifty_ma_gap
14. average_walr
15. walr_change
16. walr_pct_change
17. walr_momentum

Numeric ranges:

,min,max,mean,median,missing,inf
nifty_open,7.215700e+03,2.632855e+04,1.494907e+04,1.315035e+04,2,0
nifty_high,8.592150e+03,2.632855e+04,1.657795e+04,1.581398e+04,2,0
nifty_low,6.970600e+03,2.341655e+04,1.402339e+04,1.229040e+04,2,0
nifty_close,6.987050e+03,2.620295e+04,1.533591e+04,1.380817e+04,2,0
nifty_avg_close,7.523945e+03,2.544426e+04,1.532149e+04,1.389040e+04,2,0
nifty_total_volume,1.491900e+06,1.832500e+07,6.456068e+06,5.821300e+06,2,0
nifty_avg_daily_return,-9.463153e-03,1.438835e-02,1.269649e-03,1.257837e-03,2,0
nifty_return_volatility,2.167300e-02,1.276525e-01,4.175097e-02,3.782135e-02,2,0
nifty_monthly_return,-2.324637e-01,1.468001e-01,7.980785e-03,9.323153e-03,3,0
nifty_3m_volatility,1.156121e-03,1.900092e-01,3.826474e-02,3.436491e-02,5,0
nifty_3m_ma,7.429667e+03,2.601822e+04,1.532452e+04,1.378847e+04,4,0
nifty_ma_gap,-1.879109e-01,8.685877e-02,6.997422e-03,8.435086e-03,4,0
average_walr,8.901485e+00,1.204000e+01,1.030892e+01,1.022641e+01,99,0
walr_change,-3.920220e-01,3.665190e-01,-6.026046e-02,-6.332150e-02,99,0
walr_pct_change,-3.880197e-02,3.880481e-02,-5.559939e-03,-6.237270e-03,99,0
walr_momentum,-2.904037e-01,3.548927e-01,-5.937790e-02,-8.666667e-02,99,0

First 5 rows:

,period,nifty_open,nifty_high,nifty_low,nifty_close,nifty_avg_close,nifty_total_volume,nifty_avg_daily_return,nifty_return_volatility,nifty_monthly_return,nifty_3m_volatility,nifty_3m_ma,nifty_ma_gap,average_walr,walr_change,walr_pct_change,walr_momentum
0,2014-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.04,-0.063321,-0.006237,-0.086667
1,2014-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.85,-0.190000,-0.015781,-0.086667
2,2015-01-01,8433.400391,8952.349609,7785.850098,8808.900391,8517.880561,3155600.0,0.001717,0.024584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-02-01,8395.450195,8956.750000,7717.000000,8844.599609,8586.427707,3075000.0,0.001173,0.044847,0.004053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-03-01,8756.549805,8996.250000,7823.000000,8491.000000,8469.088216,3474400.0,-0.001184,0.039669,-0.039979,NaN,8714.833333,-0.025684,11.79,-0.060000,-0.005063,-0.103333

================================================================================
ECONOMIC ENVIRONMENT — POTENTIAL LP VARIABLES
================================================================================

,count,mean,std,min,25%,50%,75%,max
inflation_level,144.0,0.677915,0.212971,0.0,0.651957,0.762137,0.783425,0.945091
inflation_change,144.0,0.599643,0.242116,0.0,0.464605,0.634226,0.789164,1.000000
inflation_pct_change,144.0,0.599643,0.242116,0.0,0.464605,0.634226,0.789164,1.000000
nifty_monthly_return,144.0,0.634001,0.119870,0.0,0.567605,0.637516,0.705347,1.000000
nifty_return_volatility,144.0,0.189451,0.156633,0.0,0.099576,0.152372,0.216249,1.000000
nifty_3m_volatility,144.0,0.196064,0.142460,0.0,0.119920,0.175845,0.235785,1.000000
nifty_ma_gap,144.0,0.709424,0.120829,0.0,0.648008,0.714584,0.785683,1.000000
average_walr,144.0,0.417464,0.246081,0.0,0.201763,0.410649,0.524859,0.939462
walr_change,144.0,0.437729,0.197192,0.0,0.300762,0.423969,0.511538,1.000000
credit_pressure,144.0,0.638889,0.481999,0.0,0.000000,1.000000,1.000000,1.000000
walr_3period_ma,144.0,0.421346,0.266940,0.0,0.171267,0.403942,0.522540,1.000000
walr_momentum,144.0,0.354590,0.212300,0.0,0.195775,0.312728,0.462867,1.000000

================================================================================
STEP 3C COMPLETE
================================================================================

In [85]:
# ============================================================
# GOALPILOT AI — STEP 4A
# FINAL LP ECONOMIC PARAMETER VERIFICATION
# ============================================================

import os
import pandas as pd
import numpy as np

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

files_to_check = {
    "market_credit_scenarios":
        os.path.join(
            BASE_DIR,
            "simulation",
            "01_input_data",
            "market_credit_scenarios.csv"
        ),

    "economic_environment":
        os.path.join(
            BASE_DIR,
            "simulation",
            "04_economic_environment",
            "economic_environment.csv"
        ),

    "cpi_historical_calibration":
        os.path.join(
            BASE_DIR,
            "simulation",
            "01_input_data",
            "cpi_historical_calibration.csv"
        )
}

print("=" * 80)
print("GOALPILOT AI — FINAL ECONOMIC PARAMETER VERIFICATION")
print("=" * 80)


# ------------------------------------------------------------
# Inspect selected columns
# ------------------------------------------------------------

checks = {
    "market_credit_scenarios": [
        "period",
        "nifty_monthly_return",
        "nifty_return_volatility",
        "nifty_3m_volatility",
        "nifty_ma_gap",
        "average_walr",
        "walr_change",
        "walr_pct_change",
        "walr_momentum"
    ],

    "economic_environment": [
        "period",
        "inflation_level",
        "nifty_monthly_return",
        "nifty_return_volatility",
        "nifty_3m_volatility",
        "average_walr",
        "walr_change",
        "credit_pressure",
        "walr_3period_ma",
        "walr_momentum"
    ],

    "cpi_historical_calibration": [
        "period",
        "combined_inflation",
        "combined_cpi_change",
        "combined_cpi_pct_change",
        "combined_cpi_3m_ma"
    ]
}


for name, path in files_to_check.items():

    print("\n" + "=" * 80)
    print(name.upper())
    print("=" * 80)

    if not os.path.exists(path):

        print("❌ FILE NOT FOUND")
        continue

    df = pd.read_csv(path)

    available = [
        c for c in checks[name]
        if c in df.columns
    ]

    missing = [
        c for c in checks[name]
        if c not in df.columns
    ]

    print("Shape:", df.shape)

    print("\nAvailable required columns:")
    for c in available:
        print(" ✓", c)

    if missing:

        print("\nMissing columns:")
        for c in missing:
            print(" ✗", c)

    print("\nStatistics:")

    numeric = [
        c for c in available
        if c != "period"
        and pd.api.types.is_numeric_dtype(df[c])
    ]

    if numeric:

        stats = pd.DataFrame({
            "min": df[numeric].min(),
            "max": df[numeric].max(),
            "mean": df[numeric].mean(),
            "median": df[numeric].median()
        })

        display(stats)

    print("\nFirst 10 rows:")

    display(
        df[available].head(10)
    )

    print("\nLast 5 rows:")

    display(
        df[available].tail(5)
    )


# ------------------------------------------------------------
# Compare market-credit and economic environment
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("DATE COVERAGE COMPARISON")
print("=" * 80)

for name, path in files_to_check.items():

    if not os.path.exists(path):
        continue

    df = pd.read_csv(path)

    if "period" in df.columns:

        dates = pd.to_datetime(
            df["period"],
            errors="coerce"
        )

        print(
            f"{name:<35} "
            f"{dates.min().date()} → {dates.max().date()} "
            f"({dates.notna().sum()} valid dates)"
        )


print("\n" + "=" * 80)
print("STEP 4A COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — FINAL ECONOMIC PARAMETER VERIFICATION
================================================================================

================================================================================
MARKET_CREDIT_SCENARIOS
================================================================================
Shape: (146, 17)

Available required columns:
 ✓ period
 ✓ nifty_monthly_return
 ✓ nifty_return_volatility
 ✓ nifty_3m_volatility
 ✓ nifty_ma_gap
 ✓ average_walr
 ✓ walr_change
 ✓ walr_pct_change
 ✓ walr_momentum

Statistics:

                              min        max       mean     median
nifty_monthly_return    -0.232464   0.146800   0.007981   0.009323
nifty_return_volatility  0.021673   0.127653   0.041751   0.037821
nifty_3m_volatility      0.001156   0.190009   0.038265   0.034365
nifty_ma_gap            -0.187911   0.086859   0.006997   0.008435
average_walr             8.901485  12.040000  10.308919  10.226409
walr_change             -0.392022   0.366519  -0.060260  -0.063321
walr_pct_change         -0.038802   0.038805  -0.005560  -0.006237
walr_momentum           -0.290404   0.354893  -0.059378  -0.086667

First 10 rows:

,period,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,average_walr,walr_change,walr_pct_change,walr_momentum
0,2014-03-01,NaN,NaN,NaN,NaN,12.04,-0.063321,-0.006237,-0.086667
1,2014-12-01,NaN,NaN,NaN,NaN,11.85,-0.190000,-0.015781,-0.086667
2,2015-01-01,NaN,0.024584,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-02-01,0.004053,0.044847,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-03-01,-0.039979,0.039669,NaN,-0.025684,11.79,-0.060000,-0.005063,-0.103333
5,2015-04-01,-0.036450,0.046884,0.024467,-0.038116,NaN,NaN,NaN,NaN
6,2015-05-01,0.030820,0.028463,0.039896,0.007759,NaN,NaN,NaN,NaN
7,2015-06-01,-0.007725,0.029438,0.033754,0.004877,11.69,-0.100000,-0.008482,-0.086667
8,2015-07-01,0.019639,0.045639,0.019830,0.010403,NaN,NaN,NaN,NaN
9,2015-08-01,-0.065810,0.041623,0.043635,-0.038546,NaN,NaN,NaN,NaN

Last 5 rows:

,period,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,nifty_ma_gap,average_walr,walr_change,walr_pct_change,walr_momentum
141,2026-08-01,-0.017893,0.055661,0.019874,-0.005811,NaN,NaN,NaN,NaN
142,2026-09-01,0.003381,0.049710,0.018478,-0.003791,NaN,NaN,NaN,NaN
143,2026-10-01,0.010187,0.059138,0.014648,0.007896,NaN,NaN,NaN,NaN
144,2026-11-01,-0.043182,0.063444,0.029048,-0.025886,NaN,NaN,NaN,NaN
145,2026-12-01,0.019917,0.070697,0.033971,-0.001728,NaN,NaN,NaN,NaN

================================================================================
ECONOMIC_ENVIRONMENT
================================================================================
Shape: (144, 18)

Available required columns:
 ✓ period
 ✓ inflation_level
 ✓ nifty_monthly_return
 ✓ nifty_return_volatility
 ✓ nifty_3m_volatility
 ✓ average_walr
 ✓ walr_change
 ✓ credit_pressure
 ✓ walr_3period_ma
 ✓ walr_momentum

Statistics:

                         min       max      mean    median
inflation_level          0.0  0.945091  0.677915  0.762137
nifty_monthly_return     0.0  1.000000  0.634001  0.637516
nifty_return_volatility  0.0  1.000000  0.189451  0.152372
nifty_3m_volatility      0.0  1.000000  0.196064  0.175845
average_walr             0.0  0.939462  0.417464  0.410649
walr_change              0.0  1.000000  0.437729  0.423969
credit_pressure          0.0  1.000000  0.638889  1.000000
walr_3period_ma          0.0  1.000000  0.421346  0.403942
walr_momentum            0.0  1.000000  0.354590  0.312728

First 10 rows:

,period,inflation_level,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum
0,2015-01-01,0.805801,0.637516,0.027470,0.175845,0.939462,0.266330,1.0,0.404880,0.315726
1,2015-02-01,0.762137,0.623620,0.218661,0.175845,0.939462,0.266330,1.0,0.404880,0.315726
2,2015-03-01,0.179194,0.507522,0.169805,0.175845,0.920344,0.437711,1.0,1.000000,0.289898
3,2015-04-01,0.854063,0.516826,0.237883,0.123433,0.920344,0.437711,1.0,1.000000,0.289898
4,2015-05-01,0.776332,0.694196,0.064071,0.205132,0.920344,0.437711,1.0,1.000000,0.289898
5,2015-06-01,0.762137,0.592566,0.073268,0.172611,0.888482,0.384979,1.0,0.958939,0.315726
6,2015-07-01,0.762137,0.664716,0.226140,0.098883,0.888482,0.384979,1.0,0.958939,0.315726
7,2015-08-01,0.540113,0.439413,0.188240,0.224933,0.888482,0.384979,1.0,0.958939,0.315726
8,2015-09-01,0.762137,0.605525,0.113610,0.228449,0.856620,0.384979,1.0,0.928436,0.295064
9,2015-10-01,0.794167,0.651710,0.118239,0.218102,0.856620,0.384979,1.0,0.928436,0.295064

Last 5 rows:

,period,inflation_level,nifty_monthly_return,nifty_return_volatility,nifty_3m_volatility,average_walr,walr_change,credit_pressure,walr_3period_ma,walr_momentum
139,2026-08-01,0.000000,0.565757,0.320699,0.099112,0.117761,0.418627,0.0,0.119482,0.263391
140,2026-09-01,0.540113,0.621849,0.264550,0.091721,0.117761,0.418627,0.0,0.119482,0.263391
141,2026-10-01,0.762137,0.639793,0.353508,0.071440,0.117761,0.418627,0.0,0.119482,0.263391
142,2026-11-01,0.776332,0.499077,0.394138,0.147690,0.117761,0.418627,0.0,0.119482,0.263391
143,2026-12-01,0.457041,0.665448,0.462584,0.173760,0.117761,0.418627,0.0,0.119482,0.263391

================================================================================
CPI_HISTORICAL_CALIBRATION
================================================================================
Shape: (48, 11)

Available required columns:
 ✓ period
 ✓ combined_inflation
 ✓ combined_cpi_change
 ✓ combined_cpi_pct_change
 ✓ combined_cpi_3m_ma

Statistics:

                                min         max        mean      median
combined_inflation         4.338473   11.164274    9.112749    9.540669
combined_cpi_change       -0.010043    0.017705    0.006710    0.007241
combined_cpi_pct_change   -0.010043    0.017705    0.006710    0.007241
combined_cpi_3m_ma       105.600000  145.233333  126.059722  126.050000

First 10 rows:

,period,combined_inflation,combined_cpi_change,combined_cpi_pct_change,combined_cpi_3m_ma
0,2011-01-01,9.540669,0.007241,0.007241,126.050000
1,2011-02-01,9.540669,-0.005666,-0.005666,126.050000
2,2011-03-01,9.540669,0.002849,0.002849,105.600000
3,2011-04-01,9.540669,0.005682,0.005682,105.700000
4,2011-05-01,9.540669,0.008475,0.008475,106.300000
5,2011-06-01,9.540669,0.015873,0.015873,107.366667
6,2011-07-01,9.540669,0.015625,0.015625,108.800000
7,2011-08-01,9.540669,0.010860,0.010860,110.333333
8,2011-09-01,9.540669,0.011638,0.011638,111.733333
9,2011-10-01,9.540669,0.007080,0.007080,112.833333

Last 5 rows:

,period,combined_inflation,combined_cpi_change,combined_cpi_pct_change,combined_cpi_3m_ma
43,2014-08-01,7.726597,0.009047,0.009047,143.300000
44,2014-09-01,6.461087,0.000000,0.000000,144.566667
45,2014-10-01,5.561614,0.001379,0.001379,145.066667
46,2014-11-01,4.338473,0.002066,0.002066,145.233333
47,2014-12-01,4.927536,-0.004811,-0.004811,145.166667

================================================================================
DATE COVERAGE COMPARISON
================================================================================
market_credit_scenarios             2014-03-01 → 2026-12-01 (146 valid dates)
economic_environment                2015-01-01 → 2026-12-01 (144 valid dates)
cpi_historical_calibration          2011-01-01 → 2014-12-01 (48 valid dates)

================================================================================
STEP 4A COMPLETE
================================================================================

In [86]:
# ============================================================
# GOALPILOT AI — STEP 4B
# LP INVESTMENT SCENARIO VALIDATION
# ============================================================

import os
import numpy as np
import pandas as pd

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

MARKET_CREDIT_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "market_credit_scenarios.csv"
)

ENV_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "04_economic_environment",
    "economic_environment.csv"
)

LP_INPUT_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

print("=" * 80)
print("GOALPILOT AI — LP INVESTMENT SCENARIO VALIDATION")
print("=" * 80)

# ------------------------------------------------------------
# Load files
# ------------------------------------------------------------

market = pd.read_csv(MARKET_CREDIT_FILE)
environment = pd.read_csv(ENV_FILE)
lp = pd.read_csv(LP_INPUT_FILE)

market["period"] = pd.to_datetime(
    market["period"],
    errors="coerce"
)

environment["period"] = pd.to_datetime(
    environment["period"],
    errors="coerce"
)

# ------------------------------------------------------------
# 1. Market return coverage
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("NIFTY COVERAGE")
print("-" * 80)

nifty = market[
    ["period", "nifty_monthly_return"]
].dropna(
    subset=["period", "nifty_monthly_return"]
).copy()

print("Valid NIFTY observations:", len(nifty))
print("First period:", nifty["period"].min())
print("Last period :", nifty["period"].max())

print("\nReturn statistics:")

display(
    nifty["nifty_monthly_return"]
    .describe()
    .to_frame("nifty_monthly_return")
)

# ------------------------------------------------------------
# 2. Check for impossible returns
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("RETURN VALIDATION")
print("-" * 80)

print(
    "NaN:",
    nifty["nifty_monthly_return"].isna().sum()
)

print(
    "Inf:",
    np.isinf(
        nifty["nifty_monthly_return"].to_numpy()
    ).sum()
)

print(
    "Returns <= -100%:",
    (
        nifty["nifty_monthly_return"] <= -1
    ).sum()
)

# ------------------------------------------------------------
# 3. Economic environment coverage
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("ECONOMIC ENVIRONMENT COVERAGE")
print("-" * 80)

print(
    "Rows:",
    len(environment)
)

print(
    "First period:",
    environment["period"].min()
)

print(
    "Last period:",
    environment["period"].max()
)

# ------------------------------------------------------------
# 4. Compare NIFTY dates with environment
# ------------------------------------------------------------

env_nifty = environment[
    ["period", "nifty_monthly_return"]
].dropna(
    subset=["period", "nifty_monthly_return"]
).copy()

merged = nifty.merge(
    env_nifty,
    on="period",
    how="inner",
    suffixes=("_market_file", "_environment")
)

print("\n" + "-" * 80)
print("NIFTY ALIGNMENT")
print("-" * 80)

print(
    "Market-file observations:",
    len(nifty)
)

print(
    "Environment observations:",
    len(env_nifty)
)

print(
    "Common dates:",
    len(merged)
)

if len(merged) > 0:

    difference = (
        merged["nifty_monthly_return_market_file"]
        -
        merged["nifty_monthly_return_environment"]
    )

    print(
        "Maximum absolute return difference:",
        difference.abs().max()
    )

    print("\nFirst 10 aligned observations:")

    display(
        merged.head(10)
    )

# ------------------------------------------------------------
# 5. Example risk-adjusted returns
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("RISK-ADJUSTED RETURN EXAMPLE")
print("-" * 80)

sample_risk_scores = [
    0.2166,
    0.5403,
    0.7286
]

sample_names = [
    "Conservative median",
    "Moderate median",
    "Aggressive median"
]

first_return = nifty.iloc[0]["nifty_monthly_return"]

example = pd.DataFrame({
    "risk_profile": sample_names,
    "risk_score": sample_risk_scores
})

example["nifty_return"] = first_return

example["simulated_portfolio_return"] = (
    example["risk_score"]
    * example["nifty_return"]
)

display(example)

# ------------------------------------------------------------
# 6. Check LP input risk scores
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("LP RISK SCORE VALIDATION")
print("-" * 80)

print(
    "Minimum risk score:",
    lp["risk_score"].min()
)

print(
    "Maximum risk score:",
    lp["risk_score"].max()
)

print(
    "NaN risk scores:",
    lp["risk_score"].isna().sum()
)

print(
    "Inf risk scores:",
    np.isinf(
        lp["risk_score"].to_numpy()
    ).sum()
)

print(
    "Risk scores < 0:",
    (lp["risk_score"] < 0).sum()
)

print(
    "Risk scores > 1:",
    (lp["risk_score"] > 1).sum()
)

print("\n" + "=" * 80)
print("STEP 4B COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — LP INVESTMENT SCENARIO VALIDATION
================================================================================

--------------------------------------------------------------------------------
NIFTY COVERAGE
--------------------------------------------------------------------------------
Valid NIFTY observations: 143
First period: 2015-02-01 00:00:00
Last period : 2026-12-01 00:00:00

Return statistics:

       nifty_monthly_return
count            143.000000
mean               0.007981
std                0.045622
min               -0.232464
25%               -0.017425
50%                0.009323
75%                0.035068
max                0.146800

--------------------------------------------------------------------------------
RETURN VALIDATION
--------------------------------------------------------------------------------
NaN: 0
Inf: 0
Returns <= -100%: 0

--------------------------------------------------------------------------------
ECONOMIC ENVIRONMENT COVERAGE
--------------------------------------------------------------------------------
Rows: 144
First period: 2015-01-01 00:00:00
Last period: 2026-12-01 00:00:00

--------------------------------------------------------------------------------
NIFTY ALIGNMENT
--------------------------------------------------------------------------------
Market-file observations: 143
Environment observations: 144
Common dates: 143
Maximum absolute return difference: 0.8531999196301359

First 10 aligned observations:

,period,nifty_monthly_return_market_file,nifty_monthly_return_environment
0,2015-02-01,0.004053,0.623620
1,2015-03-01,-0.039979,0.507522
2,2015-04-01,-0.036450,0.516826
3,2015-05-01,0.030820,0.694196
4,2015-06-01,-0.007725,0.592566
5,2015-07-01,0.019639,0.664716
6,2015-08-01,-0.065810,0.439413
7,2015-09-01,-0.002810,0.605525
8,2015-10-01,0.014706,0.651710
9,2015-11-01,-0.016186,0.570258

--------------------------------------------------------------------------------
RISK-ADJUSTED RETURN EXAMPLE
--------------------------------------------------------------------------------

          risk_profile  risk_score  nifty_return  simulated_portfolio_return
0  Conservative median      0.2166      0.004053                    0.000878
1      Moderate median      0.5403      0.004053                    0.002190
2    Aggressive median      0.7286      0.004053                    0.002953

--------------------------------------------------------------------------------
LP RISK SCORE VALIDATION
--------------------------------------------------------------------------------
Minimum risk score: 0.0282624999999999
Maximum risk score: 0.854
NaN risk scores: 0
Inf risk scores: 0
Risk scores < 0: 0
Risk scores > 1: 0

================================================================================
STEP 4B COMPLETE
================================================================================

In [87]:
# ============================================================
# GOALPILOT AI — STEP 4C
# DIAGNOSE EXISTING 144-MONTH ECONOMIC SCENARIO
# ============================================================

import os
import numpy as np
import pandas as pd

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

ENV_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "04_economic_environment",
    "economic_environment.csv"
)

MARKET_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "market_credit_scenarios.csv"
)

CPI_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "cpi_historical_calibration.csv"
)

print("=" * 80)
print("GOALPILOT AI — EXISTING SCENARIO RECONSTRUCTION AUDIT")
print("=" * 80)


# ------------------------------------------------------------
# 1. Load files
# ------------------------------------------------------------

env = pd.read_csv(ENV_FILE)
market = pd.read_csv(MARKET_FILE)
cpi = pd.read_csv(CPI_FILE)


# ------------------------------------------------------------
# 2. Parse dates
# ------------------------------------------------------------

env["period"] = pd.to_datetime(
    env["period"],
    errors="coerce"
)

market["period"] = pd.to_datetime(
    market["period"],
    errors="coerce"
)

cpi["period"] = pd.to_datetime(
    cpi["period"],
    errors="coerce"
)


# ------------------------------------------------------------
# 3. Basic information
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("SOURCE COVERAGE")
print("-" * 80)

for name, df in [
    ("Economic environment", env),
    ("Market/Credit", market),
    ("CPI calibration", cpi)
]:

    print(
        f"{name:<25} "
        f"rows={len(df):<5} "
        f"start={df['period'].min()} "
        f"end={df['period'].max()}"
    )


# ------------------------------------------------------------
# 4. CPI scaling reconstruction
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("CPI SCALING RECONSTRUCTION")
print("=" * 80)

raw_cpi = cpi["combined_inflation"].dropna()

raw_min = raw_cpi.min()
raw_max = raw_cpi.max()

print("Raw CPI minimum :", raw_min)
print("Raw CPI maximum :", raw_max)

# Expected min-max inverse:
#
# scaled = (raw - min) / (max - min)
#
# raw = scaled * (max - min) + min

env["reconstructed_combined_inflation"] = (
    env["inflation_level"]
    * (raw_max - raw_min)
    + raw_min
)


# ------------------------------------------------------------
# 5. Compare reconstructed values with historical CPI
# ------------------------------------------------------------

print("\nFirst 15 reconstructed CPI values:")

display(
    env[
        [
            "period",
            "inflation_level",
            "reconstructed_combined_inflation"
        ]
    ].head(15)
)


# ------------------------------------------------------------
# 6. Determine whether reconstructed values correspond
#    to historical CPI observations
# ------------------------------------------------------------

historical_values = np.sort(
    raw_cpi.to_numpy()
)

def nearest_historical_difference(value):

    return np.min(
        np.abs(
            historical_values - value
        )
    )

env["nearest_cpi_difference"] = (
    env["reconstructed_combined_inflation"]
    .apply(nearest_historical_difference)
)


print("\n" + "-" * 80)
print("CPI RECONSTRUCTION QUALITY")
print("-" * 80)

print(
    "Mean nearest CPI difference:",
    env["nearest_cpi_difference"].mean()
)

print(
    "Maximum nearest CPI difference:",
    env["nearest_cpi_difference"].max()
)

print(
    "Rows within 0.001 percentage points:",
    (
        env["nearest_cpi_difference"] <= 0.001
    ).sum()
)

print(
    "Rows within 0.01 percentage points:",
    (
        env["nearest_cpi_difference"] <= 0.01
    ).sum()
)


# ------------------------------------------------------------
# 7. Inspect actual market-credit dates
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("ACTUAL MARKET/CREDIT DATA")
print("=" * 80)

display(
    market[
        [
            "period",
            "nifty_monthly_return",
            "average_walr"
        ]
    ].head(15)
)


# ------------------------------------------------------------
# 8. Align actual NIFTY/WALR to economic environment
#    by month
# ------------------------------------------------------------

market["year_month"] = (
    market["period"].dt.to_period("M")
)

env["year_month"] = (
    env["period"].dt.to_period("M")
)

market_env = pd.merge(
    env[
        [
            "year_month",
            "period",
            "inflation_level",
            "reconstructed_combined_inflation"
        ]
    ],
    market[
        [
            "year_month",
            "nifty_monthly_return",
            "average_walr"
        ]
    ],
    on="year_month",
    how="left"
)


# ------------------------------------------------------------
# 9. Check market coverage
# ------------------------------------------------------------

print("\n" + "-" * 80)
print("MARKET/CREDIT COVERAGE OF 144-MONTH ENVIRONMENT")
print("-" * 80)

print(
    "Economic environment rows:",
    len(env)
)

print(
    "Rows with actual NIFTY:",
    market_env["nifty_monthly_return"].notna().sum()
)

print(
    "Rows with actual WALR:",
    market_env["average_walr"].notna().sum()
)

print(
    "Missing NIFTY rows:",
    market_env["nifty_monthly_return"].isna().sum()
)

print(
    "Missing WALR rows:",
    market_env["average_walr"].isna().sum()
)


# ------------------------------------------------------------
# 10. Show first and last aligned rows
# ------------------------------------------------------------

print("\nFirst 10 aligned months:")

display(
    market_env[
        [
            "period",
            "inflation_level",
            "reconstructed_combined_inflation",
            "nifty_monthly_return",
            "average_walr"
        ]
    ].head(10)
)

print("\nLast 10 aligned months:")

display(
    market_env[
        [
            "period",
            "inflation_level",
            "reconstructed_combined_inflation",
            "nifty_monthly_return",
            "average_walr"
        ]
    ].tail(10)
)


# ------------------------------------------------------------
# 11. Save diagnostic dataframe ONLY
# ------------------------------------------------------------

DIAGNOSTIC_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(
    DIAGNOSTIC_DIR,
    exist_ok=True
)

DIAGNOSTIC_FILE = os.path.join(
    DIAGNOSTIC_DIR,
    "economic_scenario_diagnostic.csv"
)

market_env.to_csv(
    DIAGNOSTIC_FILE,
    index=False
)

print("\n" + "-" * 80)
print("DIAGNOSTIC OUTPUT")
print("-" * 80)

print(
    "Saved:",
    DIAGNOSTIC_FILE
)

print("\n" + "=" * 80)
print("STEP 4C DIAGNOSTIC COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — EXISTING SCENARIO RECONSTRUCTION AUDIT
================================================================================

--------------------------------------------------------------------------------
SOURCE COVERAGE
--------------------------------------------------------------------------------
Economic environment      rows=144   start=2015-01-01 00:00:00 end=2026-12-01 00:00:00
Market/Credit             rows=146   start=2014-03-01 00:00:00 end=2026-12-01 00:00:00
CPI calibration           rows=48    start=2011-01-01 00:00:00 end=2014-12-01 00:00:00

================================================================================
CPI SCALING RECONSTRUCTION
================================================================================
Raw CPI minimum : 4.33847257081392
Raw CPI maximum : 11.1642743221691

First 15 reconstructed CPI values:

       period  inflation_level  reconstructed_combined_inflation
0  2015-01-01         0.805801                          9.838710
1  2015-02-01         0.762137                          9.540669
2  2015-03-01         0.179194                          5.561614
3  2015-04-01         0.854063                         10.168135
4  2015-05-01         0.776332                          9.637562
5  2015-06-01         0.762137                          9.540669
6  2015-07-01         0.762137                          9.540669
7  2015-08-01         0.540113                          8.025177
8  2015-09-01         0.762137                          9.540669
9  2015-10-01         0.794167                          9.759300
10 2015-11-01         0.179194                          5.561614
11 2015-12-01         0.762137                          9.540669
12 2016-01-01         0.762137                          9.540669
13 2016-02-01         0.759099                          9.519935
14 2016-03-01         0.762137                          9.540669

--------------------------------------------------------------------------------
CPI RECONSTRUCTION QUALITY
--------------------------------------------------------------------------------
Mean nearest CPI difference: 1.356939252319636e-16
Maximum nearest CPI difference: 1.7763568394002505e-15
Rows within 0.001 percentage points: 144
Rows within 0.01 percentage points: 144

================================================================================
ACTUAL MARKET/CREDIT DATA
================================================================================

       period  nifty_monthly_return  average_walr
0  2014-03-01                   NaN         12.04
1  2014-12-01                   NaN         11.85
2  2015-01-01                   NaN           NaN
3  2015-02-01              0.004053           NaN
4  2015-03-01             -0.039979         11.79
5  2015-04-01             -0.036450           NaN
6  2015-05-01              0.030820           NaN
7  2015-06-01             -0.007725         11.69
8  2015-07-01              0.019639           NaN
9  2015-08-01             -0.065810           NaN
10 2015-09-01             -0.002810         11.59
11 2015-10-01              0.014706           NaN
12 2015-11-01             -0.016186           NaN
13 2015-12-01              0.001399         11.39
14 2016-01-01             -0.048173           NaN

--------------------------------------------------------------------------------
MARKET/CREDIT COVERAGE OF 144-MONTH ENVIRONMENT
--------------------------------------------------------------------------------
Economic environment rows: 144
Rows with actual NIFTY: 143
Rows with actual WALR: 45
Missing NIFTY rows: 1
Missing WALR rows: 99

First 10 aligned months:

,period,inflation_level,reconstructed_combined_inflation,nifty_monthly_return,average_walr
0,2015-01-01,0.805801,9.838710,NaN,NaN
1,2015-02-01,0.762137,9.540669,0.004053,NaN
2,2015-03-01,0.179194,5.561614,-0.039979,11.79
3,2015-04-01,0.854063,10.168135,-0.036450,NaN
4,2015-05-01,0.776332,9.637562,0.030820,NaN
5,2015-06-01,0.762137,9.540669,-0.007725,11.69
6,2015-07-01,0.762137,9.540669,0.019639,NaN
7,2015-08-01,0.540113,8.025177,-0.065810,NaN
8,2015-09-01,0.762137,9.540669,-0.002810,11.59
9,2015-10-01,0.794167,9.759300,0.014706,NaN

Last 10 aligned months:

,period,inflation_level,reconstructed_combined_inflation,nifty_monthly_return,average_walr
134,2026-03-01,0.776332,9.637562,-0.113082,9.27108
135,2026-04-01,0.854063,10.168135,0.074610,NaN
136,2026-05-01,0.707575,9.168242,-0.018744,NaN
137,2026-06-01,0.879511,10.341843,0.013504,NaN
138,2026-07-01,0.794167,9.759300,0.018914,NaN
139,2026-08-01,0.000000,4.338473,-0.017893,NaN
140,2026-09-01,0.540113,8.025177,0.003381,NaN
141,2026-10-01,0.762137,9.540669,0.010187,NaN
142,2026-11-01,0.776332,9.637562,-0.043182,NaN
143,2026-12-01,0.457041,7.458143,0.019917,NaN

--------------------------------------------------------------------------------
DIAGNOSTIC OUTPUT
--------------------------------------------------------------------------------
Saved: /content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/economic_scenario_diagnostic.csv

================================================================================
STEP 4C DIAGNOSTIC COMPLETE
================================================================================

In [88]:
# ============================================================
# GOALPILOT AI — STEP 4D
# VERIFY NIFTY + WALR SCALING / RECONSTRUCTION
# ============================================================

import os
import numpy as np
import pandas as pd

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

ENV_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "04_economic_environment",
    "economic_environment.csv"
)

MARKET_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "01_input_data",
    "market_credit_scenarios.csv"
)

print("=" * 80)
print("GOALPILOT AI — NIFTY & WALR RECONSTRUCTION AUDIT")
print("=" * 80)


# ------------------------------------------------------------
# 1. Load files
# ------------------------------------------------------------

env = pd.read_csv(ENV_FILE)
market = pd.read_csv(MARKET_FILE)

env["period"] = pd.to_datetime(
    env["period"],
    errors="coerce"
)

market["period"] = pd.to_datetime(
    market["period"],
    errors="coerce"
)


# ------------------------------------------------------------
# 2. Identify actual source ranges
# ------------------------------------------------------------

nifty_actual = market[
    "nifty_monthly_return"
].dropna()

walr_actual = market[
    "average_walr"
].dropna()


print("\n" + "-" * 80)
print("ACTUAL SOURCE RANGES")
print("-" * 80)

print(
    "NIFTY observations:",
    len(nifty_actual)
)

print(
    "NIFTY min:",
    nifty_actual.min()
)

print(
    "NIFTY max:",
    nifty_actual.max()
)

print(
    "WALR observations:",
    len(walr_actual)
)

print(
    "WALR min:",
    walr_actual.min()
)

print(
    "WALR max:",
    walr_actual.max()
)


# ------------------------------------------------------------
# 3. Reconstruct NIFTY from economic_environment
#
# Assuming existing environment uses min-max scaling:
#
# scaled = (actual - min) / (max - min)
#
# actual = scaled * (max - min) + min
# ------------------------------------------------------------

nifty_min = nifty_actual.min()
nifty_max = nifty_actual.max()

env["reconstructed_nifty_return"] = (
    env["nifty_monthly_return"]
    * (nifty_max - nifty_min)
    + nifty_min
)


# ------------------------------------------------------------
# 4. Reconstruct WALR
# ------------------------------------------------------------

walr_min = walr_actual.min()
walr_max = walr_actual.max()

env["reconstructed_walr"] = (
    env["average_walr"]
    * (walr_max - walr_min)
    + walr_min
)


# ------------------------------------------------------------
# 5. Compare reconstructed values against source
# ------------------------------------------------------------

nifty_source_values = np.sort(
    nifty_actual.to_numpy()
)

walr_source_values = np.sort(
    walr_actual.to_numpy()
)


def nearest_difference(
    value,
    source_values
):
    return np.min(
        np.abs(
            source_values - value
        )
    )


env["nifty_nearest_difference"] = (
    env["reconstructed_nifty_return"]
    .apply(
        nearest_difference,
        source_values=nifty_source_values
    )
)

env["walr_nearest_difference"] = (
    env["reconstructed_walr"]
    .apply(
        nearest_difference,
        source_values=walr_source_values
    )
)


# ------------------------------------------------------------
# 6. NIFTY reconstruction quality
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("NIFTY RECONSTRUCTION QUALITY")
print("=" * 80)

print(
    "Mean nearest difference:",
    env["nifty_nearest_difference"].mean()
)

print(
    "Maximum nearest difference:",
    env["nifty_nearest_difference"].max()
)

print(
    "Within 1e-6:",
    (
        env["nifty_nearest_difference"] <= 1e-6
    ).sum(),
    "/",
    len(env)
)

print(
    "Within 1e-4:",
    (
        env["nifty_nearest_difference"] <= 1e-4
    ).sum(),
    "/",
    len(env)
)


# ------------------------------------------------------------
# 7. WALR reconstruction quality
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("WALR RECONSTRUCTION QUALITY")
print("=" * 80)

print(
    "Mean nearest difference:",
    env["walr_nearest_difference"].mean()
)

print(
    "Maximum nearest difference:",
    env["walr_nearest_difference"].max()
)

print(
    "Within 1e-6:",
    (
        env["walr_nearest_difference"] <= 1e-6
    ).sum(),
    "/",
    len(env)
)

print(
    "Within 1e-4:",
    (
        env["walr_nearest_difference"] <= 1e-4
    ).sum(),
    "/",
    len(env)
)


# ------------------------------------------------------------
# 8. Display reconstructed values
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("FIRST 15 RECONSTRUCTED ECONOMIC PARAMETERS")
print("=" * 80)

display(
    env[
        [
            "period",
            "nifty_monthly_return",
            "reconstructed_nifty_return",
            "average_walr",
            "reconstructed_walr"
        ]
    ].head(15)
)


# ------------------------------------------------------------
# 9. Compare distributions
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("DISTRIBUTION COMPARISON")
print("=" * 80)

comparison = pd.DataFrame({

    "source_nifty": [
        nifty_actual.min(),
        nifty_actual.max(),
        nifty_actual.mean(),
        nifty_actual.median()
    ],

    "reconstructed_nifty": [
        env["reconstructed_nifty_return"].min(),
        env["reconstructed_nifty_return"].max(),
        env["reconstructed_nifty_return"].mean(),
        env["reconstructed_nifty_return"].median()
    ],

    "source_walr": [
        walr_actual.min(),
        walr_actual.max(),
        walr_actual.mean(),
        walr_actual.median()
    ],

    "reconstructed_walr": [
        env["reconstructed_walr"].min(),
        env["reconstructed_walr"].max(),
        env["reconstructed_walr"].mean(),
        env["reconstructed_walr"].median()
    ]

}, index=[
    "min",
    "max",
    "mean",
    "median"
])

display(comparison)


# ------------------------------------------------------------
# 10. Safety checks
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("SAFETY CHECKS")
print("=" * 80)

numeric_cols = [
    "reconstructed_nifty_return",
    "reconstructed_walr"
]

print(
    "NaN:",
    env[numeric_cols].isna().sum().sum()
)

print(
    "Inf:",
    np.isinf(
        env[numeric_cols].to_numpy()
    ).sum()
)

print(
    "NIFTY <= -100%:",
    (
        env["reconstructed_nifty_return"] <= -1
    ).sum()
)

print(
    "WALR <= 0:",
    (
        env["reconstructed_walr"] <= 0
    ).sum()
)


# ------------------------------------------------------------
# 11. Save audit
# ------------------------------------------------------------

AUDIT_FILE = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs",
    "nifty_walr_reconstruction_audit.csv"
)

env.to_csv(
    AUDIT_FILE,
    index=False
)

print("\n" + "-" * 80)
print("AUDIT SAVED")
print("-" * 80)

print(AUDIT_FILE)

print("\n" + "=" * 80)
print("STEP 4D COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — NIFTY & WALR RECONSTRUCTION AUDIT
================================================================================

--------------------------------------------------------------------------------
ACTUAL SOURCE RANGES
--------------------------------------------------------------------------------
NIFTY observations: 143
NIFTY min: -0.2324636775503827
NIFTY max: 0.1468000803698641
WALR observations: 47
WALR min: 8.901485
WALR max: 12.04

================================================================================
NIFTY RECONSTRUCTION QUALITY
================================================================================
Mean nearest difference: 1.409124011052254e-17
Maximum nearest difference: 4.85722573273506e-17
Within 1e-6: 144 / 144
Within 1e-4: 144 / 144

================================================================================
WALR RECONSTRUCTION QUALITY
================================================================================
Mean nearest difference: 3.3306690738754696e-16
Maximum nearest difference: 1.7763568394002505e-15
Within 1e-6: 144 / 144
Within 1e-4: 144 / 144

================================================================================
FIRST 15 RECONSTRUCTED ECONOMIC PARAMETERS
================================================================================

,period,nifty_monthly_return,reconstructed_nifty_return,average_walr,reconstructed_walr
0,2015-01-01,0.637516,0.009323,0.939462,11.85
1,2015-02-01,0.623620,0.004053,0.939462,11.85
2,2015-03-01,0.507522,-0.039979,0.920344,11.79
3,2015-04-01,0.516826,-0.036450,0.920344,11.79
4,2015-05-01,0.694196,0.030820,0.920344,11.79
5,2015-06-01,0.592566,-0.007725,0.888482,11.69
6,2015-07-01,0.664716,0.019639,0.888482,11.69
7,2015-08-01,0.439413,-0.065810,0.888482,11.69
8,2015-09-01,0.605525,-0.002810,0.856620,11.59
9,2015-10-01,0.651710,0.014706,0.856620,11.59
10,2015-11-01,0.570258,-0.016186,0.856620,11.59
11,2015-12-01,0.616622,0.001399,0.792896,11.39
12,2016-01-01,0.485917,-0.048173,0.792896,11.39
13,2016-02-01,0.411964,-0.076221,0.792896,11.39
14,2016-03-01,0.896469,0.107535,0.776965,11.34

================================================================================
DISTRIBUTION COMPARISON
================================================================================

        source_nifty  reconstructed_nifty  source_walr  reconstructed_walr
min        -0.232464            -0.232464     8.901485            8.901485
max         0.146800             0.146800    12.040000           11.850000
mean        0.007981             0.007990    10.308919           10.211703
median      0.009323             0.009323    10.226409           10.190314

================================================================================
SAFETY CHECKS
================================================================================
NaN: 0
Inf: 0
NIFTY <= -100%: 0
WALR <= 0: 0

--------------------------------------------------------------------------------
AUDIT SAVED
--------------------------------------------------------------------------------
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/nifty_walr_reconstruction_audit.csv

================================================================================
STEP 4D COMPLETE
================================================================================

In [89]:
# ============================================================
# GOALPILOT AI — STEP 5A
# LP INPUT & FORMULATION AUDIT
# ============================================================

import os
import numpy as np
import pandas as pd

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

print("=" * 80)
print("GOALPILOT AI — STEP 5A: LP INPUT & FORMULATION AUDIT")
print("=" * 80)

# ------------------------------------------------------------
# 1. LOAD EXISTING LP INPUT
# ------------------------------------------------------------

if not os.path.exists(LP_FILE):
    raise FileNotFoundError(
        f"LP input file not found:\n{LP_FILE}"
    )

df = pd.read_csv(LP_FILE)

print("\nLP INPUT FILE:")
print(LP_FILE)

print("\nShape:", df.shape)

print("\nNumber of unique users:", df["user_id"].nunique())

print("\nDuplicate user IDs:", df["user_id"].duplicated().sum())


# ------------------------------------------------------------
# 2. SHOW ALL COLUMNS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("ALL LP INPUT COLUMNS")
print("=" * 80)

for i, col in enumerate(df.columns, start=1):
    print(f"{i:02d}. {col}")


# ------------------------------------------------------------
# 3. DATA TYPES + MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("DATA QUALITY")
print("=" * 80)

quality = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing": df.isna().sum(),
    "unique": df.nunique()
})

display(quality)


# ------------------------------------------------------------
# 4. CANDIDATE LP INPUT VARIABLES
# ------------------------------------------------------------

candidate_cols = [
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "financial_situation",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "goal_horizon_type",
    "target_amount",
    "target_to_annual_income_ratio",
    "target_to_savings_ratio",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor"
]

available_candidates = [
    c for c in candidate_cols
    if c in df.columns
]

missing_candidates = [
    c for c in candidate_cols
    if c not in df.columns
]

print("\n" + "=" * 80)
print("CANDIDATE LP INPUT VARIABLES")
print("=" * 80)

print("\nAvailable:")
for c in available_candidates:
    print("  ✓", c)

print("\nNot available:")
for c in missing_candidates:
    print("  -", c)


# ------------------------------------------------------------
# 5. SIMULATION OUTPUT COLUMNS
# ------------------------------------------------------------

simulation_output_cols = [
    "final_monthly_income",
    "final_monthly_expenditure",
    "final_monthly_surplus",
    "final_monthly_emi",
    "final_savings_balance",
    "final_portfolio_value",
    "final_total_financial_wealth",
    "final_portfolio_wealth_ratio",
    "final_savings_status",
    "final_cash_flow_status",
    "final_unfunded_deficit",
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual",
    "goal_shortfall_severity",
    "goal_outcome",
    "goal_funding_ratio",
    "goal_funding_ratio_capped",
    "goal_shortfall_ratio"
]

available_outputs = [
    c for c in simulation_output_cols
    if c in df.columns
]

print("\n" + "=" * 80)
print("SIMULATION / OUTCOME COLUMNS")
print("=" * 80)

for c in available_outputs:
    print("  ⚠", c)


# ------------------------------------------------------------
# 6. NUMERIC SUMMARY OF CANDIDATE INPUTS
# ------------------------------------------------------------

numeric_candidates = [
    c for c in available_candidates
    if pd.api.types.is_numeric_dtype(df[c])
]

print("\n" + "=" * 80)
print("NUMERIC LP INPUT SUMMARY")
print("=" * 80)

summary = df[numeric_candidates].describe().T

display(
    summary[
        [
            "count",
            "mean",
            "std",
            "min",
            "25%",
            "50%",
            "75%",
            "max"
        ]
    ]
)


# ------------------------------------------------------------
# 7. IMPORTANT FINANCIAL FEASIBILITY CHECKS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("FINANCIAL FEASIBILITY CHECKS")
print("=" * 80)

if "monthly_income" in df.columns and "monthly_expenditure" in df.columns:
    calculated_surplus = (
        df["monthly_income"]
        - df["monthly_expenditure"]
        - df.get("monthly_emi", 0)
    )

    print(
        "Users with positive calculated surplus:",
        (calculated_surplus > 0).sum()
    )

    print(
        "Users with zero calculated surplus:",
        (calculated_surplus == 0).sum()
    )

    print(
        "Users with negative calculated surplus:",
        (calculated_surplus < 0).sum()
    )

if "goal_specific_monthly_capacity" in df.columns:
    print(
        "\nGoal-specific monthly capacity <= 0:",
        (df["goal_specific_monthly_capacity"] <= 0).sum()
    )

if "goal_horizon_months" in df.columns:
    print(
        "Goal horizon < 1 month:",
        (df["goal_horizon_months"] < 1).sum()
    )

if "target_amount" in df.columns:
    print(
        "Target amount <= 0:",
        (df["target_amount"] <= 0).sum()
    )

if "investment_capacity_ratio" in df.columns:
    print(
        "Investment capacity ratio outside [0,1]:",
        (
            (df["investment_capacity_ratio"] < 0)
            |
            (df["investment_capacity_ratio"] > 1)
        ).sum()
    )


# ------------------------------------------------------------
# 8. RISK PROFILE DISTRIBUTION
# ------------------------------------------------------------

if "risk_profile" in df.columns:

    print("\n" + "=" * 80)
    print("RISK PROFILE DISTRIBUTION")
    print("=" * 80)

    print(
        df["risk_profile"]
        .value_counts(dropna=False)
        .sort_index()
    )


# ------------------------------------------------------------
# 9. FINANCIAL SITUATION DISTRIBUTION
# ------------------------------------------------------------

if "financial_situation" in df.columns:

    print("\n" + "=" * 80)
    print("FINANCIAL SITUATION DISTRIBUTION")
    print("=" * 80)

    print(
        df["financial_situation"]
        .value_counts(dropna=False)
        .sort_index()
    )


# ------------------------------------------------------------
# 10. SAVE AUDIT
# ------------------------------------------------------------

AUDIT_FILE = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs",
    "lp_input_formulation_audit.csv"
)

os.makedirs(os.path.dirname(AUDIT_FILE), exist_ok=True)

quality.to_csv(AUDIT_FILE)

print("\n" + "=" * 80)
print("AUDIT SAVED")
print("=" * 80)

print(AUDIT_FILE)

print("\n" + "=" * 80)
print("STEP 5A COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — STEP 5A: LP INPUT & FORMULATION AUDIT
================================================================================

LP INPUT FILE:
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/final_optimisation_input.csv

Shape: (10000, 38)

Number of unique users: 10000

Duplicate user IDs: 0

================================================================================
ALL LP INPUT COLUMNS
================================================================================
01. user_id
02. monthly_income
03. monthly_expenditure
04. monthly_emi
05. initial_savings
06. initial_investment
07. investment_capacity_ratio
08. financial_situation
09. risk_score
10. risk_profile
11. goal_horizon_months
12. goal_horizon_type
13. target_amount
14. target_to_annual_income_ratio
15. target_to_savings_ratio
16. goal_specific_monthly_capacity
17. goal_allocation_factor
18. final_monthly_income
19. final_monthly_expenditure
20. final_monthly_surplus
21. final_monthly_emi
22. final_savings_balance
23. final_portfolio_value
24. final_total_financial_wealth
25. final_portfolio_wealth_ratio
26. final_savings_status
27. final_cash_flow_status
28. final_unfunded_deficit
29. goal_horizon_funding_actual
30. goal_progress_at_deadline_actual
31. goal_progress_at_deadline_actual_capped
32. goal_shortfall_actual
33. goal_achieved_on_time_actual
34. goal_shortfall_severity
35. goal_outcome
36. goal_funding_ratio
37. goal_funding_ratio_capped
38. goal_shortfall_ratio

================================================================================
DATA QUALITY
================================================================================

                                           dtype  missing  unique
user_id                                   object        0   10000
monthly_income                           float64        0   10000
monthly_expenditure                      float64        0    1449
monthly_emi                              float64        0    4209
initial_savings                          float64        0   10000
initial_investment                       float64        0    5446
investment_capacity_ratio                float64        0    7871
financial_situation                       object        0       4
risk_score                               float64        0    8754
risk_profile                              object        0       3
goal_horizon_months                        int64        0     115
goal_horizon_type                         object        0       4
target_amount                            float64        0   10000
target_to_annual_income_ratio            float64        0       1
target_to_savings_ratio                  float64        0   10000
goal_specific_monthly_capacity           float64        0    7871
goal_allocation_factor                   float64        0    7871
final_monthly_income                     float64        0   10000
final_monthly_expenditure                float64        0    1449
final_monthly_surplus                    float64        0   10000
final_monthly_emi                        float64        0    4209
final_savings_balance                    float64        0    8716
final_portfolio_value                    float64        0    5446
final_total_financial_wealth             float64        0    9004
final_portfolio_wealth_ratio             float64        0    5159
final_savings_status                      object        0       2
final_cash_flow_status                    object        0       2
final_unfunded_deficit                   float64        0    1286
goal_horizon_funding_actual              float64        0    8536
goal_progress_at_deadline_actual         float64        0    8536
goal_progress_at_deadline_actual_capped  float64        0    2086
goal_shortfall_actual                    float64        0    3550
goal_achieved_on_time_actual                bool        0       2
goal_shortfall_severity                   object        0       4
goal_outcome                              object        0       2
goal_funding_ratio                       float64        0    8536
goal_funding_ratio_capped                float64        0    2086
goal_shortfall_ratio                     float64        0    2086

================================================================================
CANDIDATE LP INPUT VARIABLES
================================================================================

Available:
  ✓ monthly_income
  ✓ monthly_expenditure
  ✓ monthly_emi
  ✓ initial_savings
  ✓ initial_investment
  ✓ investment_capacity_ratio
  ✓ financial_situation
  ✓ risk_score
  ✓ risk_profile
  ✓ goal_horizon_months
  ✓ goal_horizon_type
  ✓ target_amount
  ✓ target_to_annual_income_ratio
  ✓ target_to_savings_ratio
  ✓ goal_specific_monthly_capacity
  ✓ goal_allocation_factor

Not available:

================================================================================
SIMULATION / OUTCOME COLUMNS
================================================================================
  ⚠ final_monthly_income
  ⚠ final_monthly_expenditure
  ⚠ final_monthly_surplus
  ⚠ final_monthly_emi
  ⚠ final_savings_balance
  ⚠ final_portfolio_value
  ⚠ final_total_financial_wealth
  ⚠ final_portfolio_wealth_ratio
  ⚠ final_savings_status
  ⚠ final_cash_flow_status
  ⚠ final_unfunded_deficit
  ⚠ goal_horizon_funding_actual
  ⚠ goal_progress_at_deadline_actual
  ⚠ goal_progress_at_deadline_actual_capped
  ⚠ goal_shortfall_actual
  ⚠ goal_achieved_on_time_actual
  ⚠ goal_shortfall_severity
  ⚠ goal_outcome
  ⚠ goal_funding_ratio
  ⚠ goal_funding_ratio_capped
  ⚠ goal_shortfall_ratio

================================================================================
NUMERIC LP INPUT SUMMARY
================================================================================

,count,mean,std,min,25%,50%,75%,max
monthly_income,10000.0,61588.311653,5.390883e+04,1257.339650,32005.389162,47770.485750,71013.157446,8.459932e+05
monthly_expenditure,10000.0,44971.461200,3.763272e+04,850.000000,24000.000000,35750.000000,51316.500000,5.305000e+05
monthly_emi,10000.0,5195.490810,9.746159e+03,0.000000,0.000000,0.000000,8042.871110,1.398347e+05
initial_savings,10000.0,166794.764388,2.175347e+05,7.776881,49608.326314,104229.701508,202970.684488,4.946443e+06
initial_investment,10000.0,56968.534834,1.216104e+05,0.000000,0.000000,9154.054851,67910.432199,3.880240e+06
investment_capacity_ratio,10000.0,0.187228,1.491132e-01,0.000000,0.036815,0.189573,0.306529,4.999763e-01
risk_score,10000.0,0.500000,2.232333e-01,0.028262,0.313572,0.540337,0.682412,8.540000e-01
goal_horizon_months,10000.0,62.697000,3.343123e+01,6.000000,33.000000,63.000000,92.000000,1.200000e+02
target_amount,10000.0,138353.834973,1.211024e+05,2824.525592,71897.868468,107313.055427,159526.091924,1.900464e+06
target_to_annual_income_ratio,10000.0,0.187203,8.521388e-15,0.187203,0.187203,0.187203,0.187203,1.872025e-01
target_to_savings_ratio,10000.0,1.854005,1.838179e+01,0.290390,0.649122,1.000000,1.679511,1.751785e+03
goal_specific_monthly_capacity,10000.0,10408.069934,1.857810e+04,0.000000,304.680019,3802.625086,12801.743318,4.013533e+05
goal_allocation_factor,10000.0,0.500050,2.872913e-01,0.106550,0.250075,0.500050,0.750025,1.000000e+00

================================================================================
FINANCIAL FEASIBILITY CHECKS
================================================================================
Users with positive calculated surplus: 7870
Users with zero calculated surplus: 0
Users with negative calculated surplus: 2130

Goal-specific monthly capacity <= 0: 2130
Goal horizon < 1 month: 0
Target amount <= 0: 0
Investment capacity ratio outside [0,1]: 0

================================================================================
RISK PROFILE DISTRIBUTION
================================================================================
risk_profile
aggressive      3333
conservative    3333
moderate        3334
Name: count, dtype: int64

================================================================================
FINANCIAL SITUATION DISTRIBUTION
================================================================================
financial_situation
financial_stress     474
high_saving         2043
low_saving          2923
moderate_saving     4560
Name: count, dtype: int64

================================================================================
AUDIT SAVED
================================================================================
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_input_formulation_audit.csv

================================================================================
STEP 5A COMPLETE
================================================================================

In [90]:
# ============================================================
# GOALPILOT AI — STEP 5B
# EXISTING SIMULATION LOGIC AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

df = pd.read_csv(LP_FILE)

print("=" * 80)
print("GOALPILOT AI — STEP 5B: EXISTING SIMULATION LOGIC AUDIT")
print("=" * 80)


# ------------------------------------------------------------
# 1. INPUT RELATIONSHIPS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("INPUT RELATIONSHIPS")
print("=" * 80)

df["calculated_surplus"] = (
    df["monthly_income"]
    - df["monthly_expenditure"]
    - df["monthly_emi"]
)

df["capacity_times_factor"] = (
    df["goal_specific_monthly_capacity"]
    * df["goal_allocation_factor"]
)

df["surplus_times_investment_ratio"] = (
    df["calculated_surplus"].clip(lower=0)
    * df["investment_capacity_ratio"]
)

relationship = pd.DataFrame({
    "calculated_surplus": df["calculated_surplus"],
    "goal_specific_monthly_capacity":
        df["goal_specific_monthly_capacity"],
    "goal_allocation_factor":
        df["goal_allocation_factor"],
    "capacity_times_factor":
        df["capacity_times_factor"],
    "investment_capacity_ratio":
        df["investment_capacity_ratio"],
    "surplus_times_investment_ratio":
        df["surplus_times_investment_ratio"],
    "initial_savings":
        df["initial_savings"],
    "initial_investment":
        df["initial_investment"],
    "target_amount":
        df["target_amount"],
    "goal_horizon_months":
        df["goal_horizon_months"],
    "risk_score":
        df["risk_score"]
})

display(relationship.head(20))


# ------------------------------------------------------------
# 2. GOAL CAPACITY VS SURPLUS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("GOAL CAPACITY VS SURPLUS")
print("=" * 80)

capacity_comparison = pd.DataFrame({
    "surplus": df["calculated_surplus"],
    "goal_capacity": df["goal_specific_monthly_capacity"],
    "capacity_factor": df["goal_allocation_factor"],
    "capacity_after_factor":
        df["capacity_times_factor"]
})

display(capacity_comparison.describe())


# ------------------------------------------------------------
# 3. INITIAL WEALTH
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("INITIAL WEALTH")
print("=" * 80)

df["initial_total_wealth"] = (
    df["initial_savings"]
    + df["initial_investment"]
)

wealth_summary = df[
    [
        "initial_savings",
        "initial_investment",
        "initial_total_wealth",
        "target_amount"
    ]
].describe().T

display(wealth_summary)


# ------------------------------------------------------------
# 4. TARGET RELATIONSHIPS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("TARGET RELATIONSHIPS")
print("=" * 80)

df["target_minus_initial_wealth"] = (
    df["target_amount"]
    - df["initial_total_wealth"]
)

df["target_minus_initial_savings"] = (
    df["target_amount"]
    - df["initial_savings"]
)

target_summary = df[
    [
        "target_amount",
        "initial_savings",
        "initial_investment",
        "initial_total_wealth",
        "target_minus_initial_wealth",
        "target_minus_initial_savings"
    ]
].describe().T

display(target_summary)


# ------------------------------------------------------------
# 5. HORIZON × MONTHLY CAPACITY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("HORIZON × MONTHLY CAPACITY")
print("=" * 80)

df["capacity_over_horizon"] = (
    df["goal_specific_monthly_capacity"]
    * df["goal_horizon_months"]
)

df["capacity_factor_over_horizon"] = (
    df["capacity_times_factor"]
    * df["goal_horizon_months"]
)

horizon_capacity = df[
    [
        "goal_horizon_months",
        "goal_specific_monthly_capacity",
        "goal_allocation_factor",
        "capacity_times_factor",
        "capacity_over_horizon",
        "capacity_factor_over_horizon",
        "target_amount"
    ]
].describe().T

display(horizon_capacity)


# ------------------------------------------------------------
# 6. RISK PROFILE → RISK SCORE
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("RISK PROFILE → RISK SCORE")
print("=" * 80)

risk_summary = (
    df.groupby("risk_profile")["risk_score"]
    .agg(["count", "min", "mean", "median", "max"])
)

display(risk_summary)


# ------------------------------------------------------------
# 7. INVESTMENT CAPACITY BY RISK PROFILE
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("INVESTMENT CAPACITY BY RISK PROFILE")
print("=" * 80)

investment_summary = (
    df.groupby("risk_profile")[
        [
            "investment_capacity_ratio",
            "initial_investment",
            "initial_savings"
        ]
    ]
    .agg(["mean", "median", "min", "max"])
)

display(investment_summary)


# ------------------------------------------------------------
# 8. FINANCIAL SITUATION VS CAPACITY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("FINANCIAL SITUATION VS CAPACITY")
print("=" * 80)

financial_summary = (
    df.groupby("financial_situation")[
        [
            "calculated_surplus",
            "goal_specific_monthly_capacity",
            "goal_allocation_factor",
            "investment_capacity_ratio",
            "initial_savings",
            "initial_investment"
        ]
    ]
    .mean()
)

display(financial_summary)


# ------------------------------------------------------------
# 9. POSSIBLE GOAL FEASIBILITY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("BASIC GOAL FEASIBILITY")
print("=" * 80)

df["maximum_goal_contribution"] = (
    df["capacity_times_factor"]
    * df["goal_horizon_months"]
)

df["required_goal_funding"] = (
    df["target_amount"]
    - df["initial_savings"]
)

df["basic_goal_feasible"] = (
    df["maximum_goal_contribution"]
    >= df["required_goal_funding"]
)

print(
    "Users potentially feasible using monthly goal capacity:",
    df["basic_goal_feasible"].sum()
)

print(
    "Users potentially infeasible:",
    (~df["basic_goal_feasible"]).sum()
)


# ------------------------------------------------------------
# 10. SAVE AUDIT
# ------------------------------------------------------------

AUDIT_FILE = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs",
    "lp_existing_logic_audit.csv"
)

audit_columns = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "calculated_surplus",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "capacity_times_factor",
    "maximum_goal_contribution",
    "required_goal_funding",
    "basic_goal_feasible"
]

df[audit_columns].to_csv(
    AUDIT_FILE,
    index=False
)

print("\n" + "=" * 80)
print("AUDIT SAVED")
print("=" * 80)

print(AUDIT_FILE)

print("\n" + "=" * 80)
print("STEP 5B COMPLETE")
print("=" * 80)

================================================================================
GOALPILOT AI — STEP 5B: EXISTING SIMULATION LOGIC AUDIT
================================================================================

================================================================================
INPUT RELATIONSHIPS
================================================================================

,calculated_surplus,goal_specific_monthly_capacity,goal_allocation_factor,capacity_times_factor,investment_capacity_ratio,surplus_times_investment_ratio,initial_savings,initial_investment,target_amount,goal_horizon_months,risk_score
0,14481.335334,10103.627663,0.69770,7049.301020,0.282005,4083.809539,178733.652470,45777.548120,115357.183592,48,0.710500
1,-12898.954102,0.000000,0.10655,0.000000,0.000000,0.000000,13659.350863,0.000000,59340.387689,51,0.038363
2,2467.548430,748.407439,0.30330,226.991976,0.055491,136.926713,85318.549015,0.000000,99893.237726,46,0.505350
3,1045.743136,255.370474,0.24420,62.361470,0.031125,32.548599,107702.527041,60534.274631,75476.307623,60,0.313650
4,40719.010189,38345.091895,0.94170,36109.573038,0.443954,18077.362450,205810.045973,105774.934379,206040.342056,120,0.750750
5,22096.549442,18189.879501,0.82320,14973.908805,0.450063,9944.843432,229003.169045,118987.882781,110291.964774,18,0.823150
6,26988.382060,23523.073803,0.87160,20502.711127,0.473577,12781.074666,126015.560330,90329.680595,128020.414837,75,0.762325
7,-4632.993613,0.000000,0.10655,0.000000,0.000000,0.000000,26481.524416,0.000000,269916.171830,11,0.087587
8,27284.850834,23871.515994,0.87490,20885.189344,0.335670,9158.694116,165575.931991,0.000000,182600.732773,55,0.688500
9,5047.201045,2066.324108,0.40940,845.953090,0.117248,591.774558,76879.539877,15171.499059,96702.526658,24,0.533300
10,7263.792300,3551.994435,0.48900,1736.925279,0.408910,2970.237306,54235.719087,40453.563484,39905.117099,42,0.774625
11,-14578.438079,0.000000,0.10655,0.000000,0.000000,0.000000,61045.416664,8515.989852,153722.614222,18,0.158238
12,-4352.365214,0.000000,0.10655,0.000000,0.000000,0.000000,61114.611407,16162.918447,75699.850293,102,0.167738
13,2436.730582,734.186924,0.30130,221.210520,0.096035,234.010822,38402.341214,14401.269590,56999.623650,88,0.286625
14,48718.138770,46788.900475,0.96040,44936.060016,0.371228,18085.540912,445818.862673,198355.872839,294810.384238,105,0.602350
15,27032.664866,23588.703362,0.87260,20583.502554,0.370145,10006.001713,493682.921253,225494.049270,164062.774110,32,0.815250
16,6094.564062,2724.879592,0.44710,1218.293666,0.202514,1234.233233,102659.833839,41652.757168,67605.333513,12,0.651050
17,23428.589185,19675.329198,0.83980,16523.341460,0.228731,5358.843616,300258.176599,0.000000,230098.662301,65,0.652225
18,11366.928199,7041.812019,0.61950,4362.402546,0.326009,3705.719527,65278.649054,33043.600346,78326.115793,39,0.671800
19,6984.510670,3346.279062,0.47910,1603.202299,0.175671,1226.972502,163482.103389,67196.936642,89316.160080,76,0.481850

================================================================================
GOAL CAPACITY VS SURPLUS
================================================================================

             surplus  goal_capacity  capacity_factor  capacity_after_factor
count   10000.000000   10000.000000     10000.000000           10000.000000
mean    11421.359643   10408.069934         0.500050            8824.989354
std     20379.951180   18578.095127         0.287291           18278.177592
min   -163970.427127       0.000000         0.106550               0.000000
25%      1218.354377     304.680019         0.250075              76.192870
50%      7604.489602    3802.625086         0.500050            1901.502723
75%     17068.422123   12801.743318         0.750025            9601.627575
max    401353.251371  401353.251371         1.000000          401353.251371

================================================================================
INITIAL WEALTH
================================================================================

,count,mean,std,min,25%,50%,75%,max
initial_savings,10000.0,166794.764388,217534.748504,7.776881,49608.326314,104229.701508,202970.684488,4.946443e+06
initial_investment,10000.0,56968.534834,121610.403860,0.000000,0.000000,9154.054851,67910.432199,3.880240e+06
initial_total_wealth,10000.0,223763.299222,323223.004106,7.776881,55950.120437,124328.463129,266703.825714,8.826683e+06
target_amount,10000.0,138353.834973,121102.415110,2824.525592,71897.868468,107313.055427,159526.091924,1.900464e+06

================================================================================
TARGET RELATIONSHIPS
================================================================================

,count,mean,std,min,25%,50%,75%,max
target_amount,10000.0,138353.834973,121102.415110,2.824526e+03,71897.868468,107313.055427,159526.091924,1.900464e+06
initial_savings,10000.0,166794.764388,217534.748504,7.776881e+00,49608.326314,104229.701508,202970.684488,4.946443e+06
initial_investment,10000.0,56968.534834,121610.403860,0.000000e+00,0.000000,9154.054851,67910.432199,3.880240e+06
initial_total_wealth,10000.0,223763.299222,323223.004106,7.776881e+00,55950.120437,124328.463129,266703.825714,8.826683e+06
target_minus_initial_wealth,10000.0,-85409.464250,247470.059705,-6.936642e+06,-120620.201672,-14980.413293,28245.444248,8.682426e+05
target_minus_initial_savings,10000.0,-28440.929416,142025.574401,-3.056402e+06,-59424.886478,9.285262,35310.821605,8.682426e+05

================================================================================
HORIZON × MONTHLY CAPACITY
================================================================================

,count,mean,std,min,25%,50%,75%,max
goal_horizon_months,10000.0,62.697000,3.343123e+01,6.000000,33.000000,63.000000,92.000000,1.200000e+02
goal_specific_monthly_capacity,10000.0,10408.069934,1.857810e+04,0.000000,304.680019,3802.625086,12801.743318,4.013533e+05
goal_allocation_factor,10000.0,0.500050,2.872913e-01,0.106550,0.250075,0.500050,0.750025,1.000000e+00
capacity_times_factor,10000.0,8824.989354,1.827818e+04,0.000000,76.192870,1901.502723,9601.627575,4.013533e+05
capacity_over_horizon,10000.0,663102.649253,1.440565e+06,0.000000,12265.294610,172663.558311,707739.875806,4.374750e+07
capacity_factor_over_horizon,10000.0,564385.766980,1.408652e+06,0.000000,3304.173716,87612.541572,510774.081058,4.374750e+07
target_amount,10000.0,138353.834973,1.211024e+05,2824.525592,71897.868468,107313.055427,159526.091924,1.900464e+06

================================================================================
RISK PROFILE → RISK SCORE
================================================================================

              count       min      mean    median       max
risk_profile
aggressive     3333  0.634950  0.737324  0.728550  0.854000
conservative   3333  0.028262  0.227601  0.216587  0.410750
moderate       3334  0.410925  0.535065  0.540337  0.634875

================================================================================
INVESTMENT CAPACITY BY RISK PROFILE
================================================================================

             investment_capacity_ratio                                \
                                  mean    median       min       max
risk_profile
aggressive                    0.344191  0.338758  0.200011  0.499976
conservative                  0.029605  0.000000  0.000000  0.236647
moderate                      0.187888  0.185813  0.000000  0.439103

             initial_investment                                   \
                           mean        median  min           max
risk_profile
aggressive        114485.540659  71125.627652  0.0  3.880240e+06
conservative       15961.616749      0.000000  0.0  4.850879e+05
moderate           40463.399131   2157.862355  0.0  1.620772e+06

             initial_savings
                        mean         median          min           max
risk_profile
aggressive     263202.362885  187998.624688  2203.059473  4.946443e+06
conservative   101776.574448   69137.015114     7.776881  1.581059e+06
moderate       135414.770771   74453.038153   575.624683  2.928865e+06

================================================================================
FINANCIAL SITUATION VS CAPACITY
================================================================================

,calculated_surplus,goal_specific_monthly_capacity,goal_allocation_factor,investment_capacity_ratio,initial_savings,initial_investment
financial_situation,,,,,,
financial_stress,-10097.540165,39.817180,0.124669,0.003352,35920.292822,618.186633
high_saving,30693.004845,27416.749941,0.803956,0.385517,347327.063376,176392.320916
low_saving,67.107935,1844.980540,0.271973,0.061403,73540.104727,6652.184760
moderate_saving,12302.163394,9354.501699,0.549111,0.198158,159292.655370,41574.228112

================================================================================
BASIC GOAL FEASIBILITY
================================================================================
Users potentially feasible using monthly goal capacity: 7339
Users potentially infeasible: 2661

================================================================================
AUDIT SAVED
================================================================================
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_existing_logic_audit.csv

================================================================================
STEP 5B COMPLETE
================================================================================

In [91]:
# ============================================================
# GOALPILOT AI — STEP 5C
# LP DECISION-VARIABLE & CONSTRAINT MAPPING
# ============================================================

import os
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_INPUT = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Load existing LP input
# ------------------------------------------------------------

df = pd.read_csv(LP_INPUT)

print("=" * 70)
print("STEP 5C — LP DECISION-VARIABLE & CONSTRAINT MAPPING")
print("=" * 70)

print("\nLP input shape:", df.shape)
print("Unique users:", df["user_id"].nunique())

# ------------------------------------------------------------
# 3. Existing columns
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("EXISTING OPTIMIZATION INPUT COLUMNS")
print("=" * 70)

for i, col in enumerate(df.columns, 1):
    print(f"{i:02d}. {col}")

# ------------------------------------------------------------
# 4. Define candidate LP mapping
#    IMPORTANT:
#    These are mappings to be AUDITED, not solver assumptions.
# ------------------------------------------------------------

mapping = [

    # Identity
    {
        "category": "IDENTIFIER",
        "field": "user_id",
        "lp_role": "User identifier",
        "candidate_lp_use": "Index / reporting only",
        "status": "SUPPORTED"
    },

    # Financial state
    {
        "category": "FINANCIAL_PARAMETER",
        "field": "monthly_income",
        "lp_role": "Monthly income",
        "candidate_lp_use": "Budget/resource parameter",
        "status": "SUPPORTED"
    },
    {
        "category": "FINANCIAL_PARAMETER",
        "field": "monthly_expenditure",
        "lp_role": "Monthly expenditure",
        "candidate_lp_use": "Budget/resource parameter",
        "status": "SUPPORTED"
    },
    {
        "category": "FINANCIAL_PARAMETER",
        "field": "monthly_emi",
        "lp_role": "Monthly EMI obligation",
        "candidate_lp_use": "Fixed obligation / budget constraint",
        "status": "SUPPORTED"
    },
    {
        "category": "FINANCIAL_PARAMETER",
        "field": "initial_savings",
        "lp_role": "Initial savings balance",
        "candidate_lp_use": "Initial state; treatment in goal funding must be verified",
        "status": "REQUIRES_FORMULATION_DECISION"
    },
    {
        "category": "FINANCIAL_PARAMETER",
        "field": "initial_investment",
        "lp_role": "Initial investment value",
        "candidate_lp_use": "Initial investment state",
        "status": "SUPPORTED_AS_INITIAL_STATE"
    },

    # Capacity / risk
    {
        "category": "CAPACITY_PARAMETER",
        "field": "investment_capacity_ratio",
        "lp_role": "Investment capacity ratio",
        "candidate_lp_use": "Upper bound on investment allocation",
        "status": "SUPPORTED"
    },
    {
        "category": "RISK_PARAMETER",
        "field": "risk_score",
        "lp_role": "Risk score",
        "candidate_lp_use": "Existing risk descriptor; avoid inventing new thresholds",
        "status": "SUPPORTED_AS_PARAMETER"
    },
    {
        "category": "RISK_PARAMETER",
        "field": "risk_profile",
        "lp_role": "Risk profile",
        "candidate_lp_use": "Existing categorical risk descriptor",
        "status": "SUPPORTED_AS_PARAMETER"
    },

    # Goal
    {
        "category": "GOAL_PARAMETER",
        "field": "goal_horizon_months",
        "lp_role": "Goal horizon",
        "candidate_lp_use": "Number of LP periods",
        "status": "SUPPORTED"
    },
    {
        "category": "GOAL_PARAMETER",
        "field": "goal_horizon_type",
        "lp_role": "Goal horizon type",
        "candidate_lp_use": "Descriptive goal parameter",
        "status": "SUPPORTED_AS_PARAMETER"
    },
    {
        "category": "GOAL_PARAMETER",
        "field": "target_amount",
        "lp_role": "Goal target",
        "candidate_lp_use": "Required target in objective/constraint",
        "status": "SUPPORTED"
    },
    {
        "category": "GOAL_PARAMETER",
        "field": "goal_specific_monthly_capacity",
        "lp_role": "Goal-specific monthly capacity",
        "candidate_lp_use": "Upper bound on goal contribution",
        "status": "SUPPORTED"
    },
    {
        "category": "GOAL_PARAMETER",
        "field": "goal_allocation_factor",
        "lp_role": "Goal allocation factor",
        "candidate_lp_use": "Scales goal contribution capacity",
        "status": "SUPPORTED"
    },

    # Derived current-state information
    {
        "category": "DERIVED_PARAMETER",
        "field": "financial_situation",
        "lp_role": "Financial situation category",
        "candidate_lp_use": "Parameter / segmentation",
        "status": "SUPPORTED_AS_PARAMETER"
    },
    {
        "category": "DERIVED_PARAMETER",
        "field": "target_to_annual_income_ratio",
        "lp_role": "Target relative to annual income",
        "candidate_lp_use": "Diagnostic / validation",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "DERIVED_PARAMETER",
        "field": "target_to_savings_ratio",
        "lp_role": "Target relative to savings",
        "candidate_lp_use": "Diagnostic / validation",
        "status": "VALIDATION_ONLY"
    },

    # Simulation outcomes
    {
        "category": "SIMULATION_OUTCOME",
        "field": "final_monthly_income",
        "lp_role": "Simulated income outcome",
        "candidate_lp_use": "Validation / comparison",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "final_monthly_expenditure",
        "lp_role": "Simulated expenditure outcome",
        "candidate_lp_use": "Validation / comparison",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "final_monthly_surplus",
        "lp_role": "Simulated surplus outcome",
        "candidate_lp_use": "Validation / comparison",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "final_savings_balance",
        "lp_role": "Final savings outcome",
        "candidate_lp_use": "Validation / comparison",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "final_portfolio_value",
        "lp_role": "Final investment portfolio",
        "candidate_lp_use": "Validation / comparison",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "final_total_financial_wealth",
        "lp_role": "Final financial wealth",
        "candidate_lp_use": "Validation / comparison",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "goal_shortfall_actual",
        "lp_role": "Observed simulated goal shortfall",
        "candidate_lp_use": "Validation target",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "goal_achieved_on_time_actual",
        "lp_role": "Observed simulated goal achievement",
        "candidate_lp_use": "Validation target",
        "status": "VALIDATION_ONLY"
    },
    {
        "category": "SIMULATION_OUTCOME",
        "field": "goal_outcome",
        "lp_role": "Observed simulation outcome",
        "candidate_lp_use": "Validation target",
        "status": "VALIDATION_ONLY"
    }
]

mapping_df = pd.DataFrame(mapping)

# ------------------------------------------------------------
# 5. Print mapping
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LP FIELD MAPPING")
print("=" * 70)

print(mapping_df.to_string(index=False))

# ------------------------------------------------------------
# 6. Calculate existing quantities needed for LP mapping
# ------------------------------------------------------------

df["calculated_monthly_surplus"] = (
    df["monthly_income"]
    - df["monthly_expenditure"]
    - df["monthly_emi"]
)

df["positive_monthly_surplus"] = df["calculated_monthly_surplus"].clip(lower=0)

df["goal_monthly_limit"] = (
    df["goal_specific_monthly_capacity"]
    * df["goal_allocation_factor"]
)

df["investment_monthly_limit"] = (
    df["positive_monthly_surplus"]
    * df["investment_capacity_ratio"]
)

df["potential_goal_contribution_over_horizon"] = (
    df["goal_monthly_limit"]
    * df["goal_horizon_months"]
)

# ------------------------------------------------------------
# 7. Candidate decision variables
# ------------------------------------------------------------

decision_variables = pd.DataFrame([
    {
        "decision_variable": "G_t",
        "meaning": "Amount allocated to the financial goal in month t",
        "non_negativity": "G_t >= 0",
        "upper_bound_supported_by_current_data":
            "goal_specific_monthly_capacity × goal_allocation_factor",
        "status":
            "CANDIDATE — requires final formulation confirmation"
    },
    {
        "decision_variable": "I_t",
        "meaning": "Amount allocated to investment in month t",
        "non_negativity": "I_t >= 0",
        "upper_bound_supported_by_current_data":
            "positive monthly surplus × investment_capacity_ratio",
        "status":
            "CANDIDATE — requires final formulation confirmation"
    },
    {
        "decision_variable": "C_t",
        "meaning": "Amount retained as cash/savings in month t",
        "non_negativity": "C_t >= 0",
        "upper_bound_supported_by_current_data":
            "Remaining monthly budget, if cash allocation is explicitly modeled",
        "status":
            "CANDIDATE — requires formulation confirmation"
    },
    {
        "decision_variable": "D",
        "meaning": "Goal shortfall at the end of horizon",
        "non_negativity": "D >= 0",
        "upper_bound_supported_by_current_data":
            "Target minus eligible goal funding",
        "status":
            "CANDIDATE OBJECTIVE VARIABLE"
    }
])

print("\n" + "=" * 70)
print("CANDIDATE DECISION VARIABLES")
print("=" * 70)

print(decision_variables.to_string(index=False))

# ------------------------------------------------------------
# 8. Candidate constraints
# ------------------------------------------------------------

constraints = pd.DataFrame([
    {
        "constraint": "Non-negativity",
        "candidate_form": "G_t >= 0, I_t >= 0, C_t >= 0",
        "data_support": "Direct",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Monthly financial budget",
        "candidate_form":
            "G_t + I_t + C_t <= max(0, income - expenditure - EMI)",
        "data_support":
            "Income, expenditure and EMI exist",
        "status":
            "CANDIDATE — needs confirmation against project methodology"
    },
    {
        "constraint": "Goal monthly capacity",
        "candidate_form":
            "G_t <= goal_specific_monthly_capacity × goal_allocation_factor",
        "data_support":
            "Both fields exist",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Investment capacity",
        "candidate_form":
            "I_t <= positive_surplus × investment_capacity_ratio",
        "data_support":
            "Surplus and investment capacity ratio exist",
        "status":
            "SUPPORTED AS EXISTING LOGIC"
    },
    {
        "constraint": "Goal horizon",
        "candidate_form":
            "t = 1,...,goal_horizon_months",
        "data_support":
            "goal_horizon_months exists",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Goal target",
        "candidate_form":
            "Eligible goal funding + D >= target_amount",
        "data_support":
            "target_amount exists",
        "status":
            "FORMULATION REQUIRES DEFINITION OF ELIGIBLE FUNDING"
    },
    {
        "constraint": "Initial savings treatment",
        "candidate_form":
            "Initial savings may or may not be included in eligible goal funding",
        "data_support":
            "initial_savings exists",
        "status":
            "NOT YET DECIDED"
    },
    {
        "constraint": "Initial investment treatment",
        "candidate_form":
            "Initial investment remains an initial portfolio state unless methodology says otherwise",
        "data_support":
            "initial_investment exists",
        "status":
            "SUPPORTED AS INITIAL STATE"
    },
    {
        "constraint": "Borrowing",
        "candidate_form":
            "No borrowing variable introduced",
        "data_support":
            "No explicit borrowing capacity/principal field identified",
        "status":
            "EXCLUDED FOR NOW"
    },
    {
        "constraint": "WALR",
        "candidate_form":
            "Not directly inserted into LP without an explicit borrowing mechanism",
        "data_support":
            "WALR exists in economic environment, but no borrowing decision variable",
        "status":
            "EXCLUDED FROM BASE LP FOR NOW"
    }
])

print("\n" + "=" * 70)
print("CANDIDATE LP CONSTRAINTS")
print("=" * 70)

print(constraints.to_string(index=False))

# ------------------------------------------------------------
# 9. Economic variables — explicit audit
# ------------------------------------------------------------

economic_fields = [
    "nifty_monthly_return",
    "nifty_return_volatility",
    "nifty_3m_volatility",
    "nifty_ma_gap",
    "market_return_regime",
    "market_volatility_regime",
    "average_walr",
    "walr_change",
    "credit_pressure",
    "walr_3period_ma",
    "walr_momentum",
    "walr_regime"
]

economic_available = [
    c for c in economic_fields if c in df.columns
]

print("\n" + "=" * 70)
print("ECONOMIC VARIABLES PRESENT IN LP INPUT")
print("=" * 70)

if economic_available:
    for c in economic_available:
        print("✓", c)
else:
    print("No economic-environment columns are directly present in final_optimisation_input.csv")

print("\nEconomic treatment:")
print("• NIFTY/WALR should NOT be arbitrarily inserted into the base LP.")
print("• NIFTY can potentially affect portfolio evolution if the optimization")
print("  is explicitly formulated as a multi-period investment/wealth model.")
print("• WALR requires an explicit borrowing/credit decision before it can")
print("  logically become an LP coefficient.")
print("• Therefore both require formulation verification before inclusion.")

# ------------------------------------------------------------
# 10. Goal-funding ambiguity audit
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("GOAL FUNDING AMBIGUITY AUDIT")
print("=" * 70)

print("\nTarget statistics:")
print("Mean target:", df["target_amount"].mean())
print("Mean initial savings:", df["initial_savings"].mean())
print("Mean initial investment:", df["initial_investment"].mean())

target_le_savings = (
    df["target_amount"] <= df["initial_savings"]
).sum()

target_gt_savings = (
    df["target_amount"] > df["initial_savings"]
).sum()

print("\nUsers where target <= initial savings:", target_le_savings)
print("Users where target > initial savings:", target_gt_savings)

print("\nThis does NOT decide whether savings count toward the goal.")
print("It only shows why the treatment of initial_savings materially")
print("changes the LP formulation.")

# ------------------------------------------------------------
# 11. Feasibility diagnostics
# ------------------------------------------------------------

df["goal_capacity_over_horizon"] = (
    df["goal_monthly_limit"]
    * df["goal_horizon_months"]
)

df["target_minus_goal_capacity"] = (
    df["target_amount"]
    - df["goal_capacity_over_horizon"]
)

potentially_feasible = (
    df["goal_capacity_over_horizon"]
    >= df["target_amount"]
).sum()

potentially_infeasible = (
    df["goal_capacity_over_horizon"]
    < df["target_amount"]
).sum()

print("\n" + "=" * 70)
print("GOAL CAPACITY FEASIBILITY")
print("=" * 70)

print("Potentially feasible from monthly goal capacity:",
      potentially_feasible)

print("Potentially infeasible from monthly goal capacity:",
      potentially_infeasible)

print("\nNOTE:")
print("This is only a capacity screening test.")
print("It does not yet represent the final LP because")
print("initial wealth, investment returns and exact funding rules")
print("still need to be defined.")

# ------------------------------------------------------------
# 12. Build consolidated audit table
# ------------------------------------------------------------

audit = df[
    [
        "user_id",
        "monthly_income",
        "monthly_expenditure",
        "monthly_emi",
        "initial_savings",
        "initial_investment",
        "investment_capacity_ratio",
        "risk_score",
        "risk_profile",
        "goal_horizon_months",
        "target_amount",
        "goal_specific_monthly_capacity",
        "goal_allocation_factor",
        "calculated_monthly_surplus",
        "positive_monthly_surplus",
        "goal_monthly_limit",
        "investment_monthly_limit",
        "potential_goal_contribution_over_horizon",
        "goal_capacity_over_horizon",
        "target_minus_goal_capacity"
    ]
].copy()

# ------------------------------------------------------------
# 13. Save — NEW FILE ONLY
# ------------------------------------------------------------

mapping_path = os.path.join(
    OUTPUT_DIR,
    "lp_decision_variable_constraint_mapping.csv"
)

constraint_path = os.path.join(
    OUTPUT_DIR,
    "lp_constraint_mapping_audit.csv"
)

diagnostic_path = os.path.join(
    OUTPUT_DIR,
    "lp_5c_user_diagnostics.csv"
)

mapping_df.to_csv(mapping_path, index=False)
constraints.to_csv(constraint_path, index=False)
audit.to_csv(diagnostic_path, index=False)

# ------------------------------------------------------------
# 14. Final summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 5C COMPLETE")
print("=" * 70)

print("\nFiles saved:")
print("1.", mapping_path)
print("2.", constraint_path)
print("3.", diagnostic_path)

print("\nNo original dataset was modified.")
print("No LP solver was executed.")
print("No borrowing variable was invented.")
print("Initial savings treatment remains explicitly unresolved.")
print("NIFTY/WALR inclusion remains subject to formulation verification.")

print("\nNext step: review this Step 5C output before writing the LP.")

======================================================================
STEP 5C — LP DECISION-VARIABLE & CONSTRAINT MAPPING
======================================================================

LP input shape: (10000, 38)
Unique users: 10000

======================================================================
EXISTING OPTIMIZATION INPUT COLUMNS
======================================================================
01. user_id
02. monthly_income
03. monthly_expenditure
04. monthly_emi
05. initial_savings
06. initial_investment
07. investment_capacity_ratio
08. financial_situation
09. risk_score
10. risk_profile
11. goal_horizon_months
12. goal_horizon_type
13. target_amount
14. target_to_annual_income_ratio
15. target_to_savings_ratio
16. goal_specific_monthly_capacity
17. goal_allocation_factor
18. final_monthly_income
19. final_monthly_expenditure
20. final_monthly_surplus
21. final_monthly_emi
22. final_savings_balance
23. final_portfolio_value
24. final_total_financial_wealth
25. final_portfolio_wealth_ratio
26. final_savings_status
27. final_cash_flow_status
28. final_unfunded_deficit
29. goal_horizon_funding_actual
30. goal_progress_at_deadline_actual
31. goal_progress_at_deadline_actual_capped
32. goal_shortfall_actual
33. goal_achieved_on_time_actual
34. goal_shortfall_severity
35. goal_outcome
36. goal_funding_ratio
37. goal_funding_ratio_capped
38. goal_shortfall_ratio

======================================================================
LP FIELD MAPPING
======================================================================
           category                          field                             lp_role                                          candidate_lp_use                        status
         IDENTIFIER                        user_id                     User identifier                                    Index / reporting only                     SUPPORTED
FINANCIAL_PARAMETER                 monthly_income                      Monthly income                                 Budget/resource parameter                     SUPPORTED
FINANCIAL_PARAMETER            monthly_expenditure                 Monthly expenditure                                 Budget/resource parameter                     SUPPORTED
FINANCIAL_PARAMETER                    monthly_emi              Monthly EMI obligation                      Fixed obligation / budget constraint                     SUPPORTED
FINANCIAL_PARAMETER                initial_savings             Initial savings balance Initial state; treatment in goal funding must be verified REQUIRES_FORMULATION_DECISION
FINANCIAL_PARAMETER             initial_investment            Initial investment value                                  Initial investment state    SUPPORTED_AS_INITIAL_STATE
 CAPACITY_PARAMETER      investment_capacity_ratio           Investment capacity ratio                      Upper bound on investment allocation                     SUPPORTED
     RISK_PARAMETER                     risk_score                          Risk score  Existing risk descriptor; avoid inventing new thresholds        SUPPORTED_AS_PARAMETER
     RISK_PARAMETER                   risk_profile                        Risk profile                      Existing categorical risk descriptor        SUPPORTED_AS_PARAMETER
     GOAL_PARAMETER            goal_horizon_months                        Goal horizon                                      Number of LP periods                     SUPPORTED
     GOAL_PARAMETER              goal_horizon_type                   Goal horizon type                                Descriptive goal parameter        SUPPORTED_AS_PARAMETER
     GOAL_PARAMETER                  target_amount                         Goal target                   Required target in objective/constraint                     SUPPORTED
     GOAL_PARAMETER goal_specific_monthly_capacity      Goal-specific monthly capacity                          Upper bound on goal contribution                     SUPPORTED
     GOAL_PARAMETER         goal_allocation_factor              Goal allocation factor                         Scales goal contribution capacity                     SUPPORTED
  DERIVED_PARAMETER            financial_situation        Financial situation category                                  Parameter / segmentation        SUPPORTED_AS_PARAMETER
  DERIVED_PARAMETER  target_to_annual_income_ratio    Target relative to annual income                                   Diagnostic / validation               VALIDATION_ONLY
  DERIVED_PARAMETER        target_to_savings_ratio          Target relative to savings                                   Diagnostic / validation               VALIDATION_ONLY
 SIMULATION_OUTCOME           final_monthly_income            Simulated income outcome                                   Validation / comparison               VALIDATION_ONLY
 SIMULATION_OUTCOME      final_monthly_expenditure       Simulated expenditure outcome                                   Validation / comparison               VALIDATION_ONLY
 SIMULATION_OUTCOME          final_monthly_surplus           Simulated surplus outcome                                   Validation / comparison               VALIDATION_ONLY
 SIMULATION_OUTCOME          final_savings_balance               Final savings outcome                                   Validation / comparison               VALIDATION_ONLY
 SIMULATION_OUTCOME          final_portfolio_value          Final investment portfolio                                   Validation / comparison               VALIDATION_ONLY
 SIMULATION_OUTCOME   final_total_financial_wealth              Final financial wealth                                   Validation / comparison               VALIDATION_ONLY
 SIMULATION_OUTCOME          goal_shortfall_actual   Observed simulated goal shortfall                                         Validation target               VALIDATION_ONLY
 SIMULATION_OUTCOME   goal_achieved_on_time_actual Observed simulated goal achievement                                         Validation target               VALIDATION_ONLY
 SIMULATION_OUTCOME                   goal_outcome         Observed simulation outcome                                         Validation target               VALIDATION_ONLY

======================================================================
CANDIDATE DECISION VARIABLES
======================================================================
decision_variable                                           meaning non_negativity                              upper_bound_supported_by_current_data                                              status
              G_t Amount allocated to the financial goal in month t       G_t >= 0            goal_specific_monthly_capacity × goal_allocation_factor CANDIDATE — requires final formulation confirmation
              I_t         Amount allocated to investment in month t       I_t >= 0               positive monthly surplus × investment_capacity_ratio CANDIDATE — requires final formulation confirmation
              C_t        Amount retained as cash/savings in month t       C_t >= 0 Remaining monthly budget, if cash allocation is explicitly modeled       CANDIDATE — requires formulation confirmation
                D              Goal shortfall at the end of horizon         D >= 0                                 Target minus eligible goal funding                        CANDIDATE OBJECTIVE VARIABLE

======================================================================
CANDIDATE LP CONSTRAINTS
======================================================================
                  constraint                                                                          candidate_form                                                            data_support                                                     status
              Non-negativity                                                            G_t >= 0, I_t >= 0, C_t >= 0                                                                  Direct                                                  SUPPORTED
    Monthly financial budget                                   G_t + I_t + C_t <= max(0, income - expenditure - EMI)                                       Income, expenditure and EMI exist CANDIDATE — needs confirmation against project methodology
       Goal monthly capacity                          G_t <= goal_specific_monthly_capacity × goal_allocation_factor                                                       Both fields exist                                                  SUPPORTED
         Investment capacity                                     I_t <= positive_surplus × investment_capacity_ratio                             Surplus and investment capacity ratio exist                                SUPPORTED AS EXISTING LOGIC
                Goal horizon                                                           t = 1,...,goal_horizon_months                                              goal_horizon_months exists                                                  SUPPORTED
                 Goal target                                              Eligible goal funding + D >= target_amount                                                    target_amount exists        FORMULATION REQUIRES DEFINITION OF ELIGIBLE FUNDING
   Initial savings treatment                     Initial savings may or may not be included in eligible goal funding                                                  initial_savings exists                                            NOT YET DECIDED
Initial investment treatment Initial investment remains an initial portfolio state unless methodology says otherwise                                               initial_investment exists                                 SUPPORTED AS INITIAL STATE
                   Borrowing                                                        No borrowing variable introduced               No explicit borrowing capacity/principal field identified                                           EXCLUDED FOR NOW
                        WALR                   Not directly inserted into LP without an explicit borrowing mechanism WALR exists in economic environment, but no borrowing decision variable                              EXCLUDED FROM BASE LP FOR NOW

======================================================================
ECONOMIC VARIABLES PRESENT IN LP INPUT
======================================================================
No economic-environment columns are directly present in final_optimisation_input.csv

Economic treatment:
• NIFTY/WALR should NOT be arbitrarily inserted into the base LP.
• NIFTY can potentially affect portfolio evolution if the optimization
  is explicitly formulated as a multi-period investment/wealth model.
• WALR requires an explicit borrowing/credit decision before it can
  logically become an LP coefficient.
• Therefore both require formulation verification before inclusion.

======================================================================
GOAL FUNDING AMBIGUITY AUDIT
======================================================================

Target statistics:
Mean target: 138353.8349725079
Mean initial savings: 166794.7643881863
Mean initial investment: 56968.534834146085

Users where target <= initial savings: 5000
Users where target > initial savings: 5000

This does NOT decide whether savings count toward the goal.
It only shows why the treatment of initial_savings materially
changes the LP formulation.

======================================================================
GOAL CAPACITY FEASIBILITY
======================================================================
Potentially feasible from monthly goal capacity: 4890
Potentially infeasible from monthly goal capacity: 5110

NOTE:
This is only a capacity screening test.
It does not yet represent the final LP because
initial wealth, investment returns and exact funding rules
still need to be defined.

======================================================================
STEP 5C COMPLETE
======================================================================

Files saved:
1. /content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_decision_variable_constraint_mapping.csv
2. /content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_constraint_mapping_audit.csv
3. /content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5c_user_diagnostics.csv

No original dataset was modified.
No LP solver was executed.
No borrowing variable was invented.
Initial savings treatment remains explicitly unresolved.
NIFTY/WALR inclusion remains subject to formulation verification.

Next step: review this Step 5C output before writing the LP.

In [92]:
# ============================================================
# GOALPILOT AI — STEP 5D
# LP FORMULATION PRE-CHECK
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 5D — LP FORMULATION PRE-CHECK")
print("=" * 75)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_INPUT = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Load existing optimization input
# ------------------------------------------------------------

df = pd.read_csv(LP_INPUT)

print("\nInput shape:", df.shape)
print("Unique users:", df["user_id"].nunique())

# ------------------------------------------------------------
# 3. Reconstruct ONLY already-established quantities
# ------------------------------------------------------------

df["calculated_surplus"] = (
    df["monthly_income"]
    - df["monthly_expenditure"]
    - df["monthly_emi"]
)

df["positive_surplus"] = df["calculated_surplus"].clip(lower=0)

# Existing project logic from Step 5B/5C
df["monthly_goal_limit"] = (
    df["goal_specific_monthly_capacity"]
    * df["goal_allocation_factor"]
)

df["monthly_investment_limit"] = (
    df["positive_surplus"]
    * df["investment_capacity_ratio"]
)

df["horizon"] = df["goal_horizon_months"]

# Maximum possible new goal contributions if the
# monthly goal limit can be used throughout the horizon.
df["max_new_goal_contribution"] = (
    df["monthly_goal_limit"]
    * df["horizon"]
)

# ------------------------------------------------------------
# 4. CASE A
# Initial savings NOT counted toward goal
# ------------------------------------------------------------

df["required_funding_case_A"] = (
    df["target_amount"]
)

df["shortfall_case_A"] = (
    df["required_funding_case_A"]
    - df["max_new_goal_contribution"]
).clip(lower=0)

df["potentially_feasible_case_A"] = (
    df["max_new_goal_contribution"]
    >= df["required_funding_case_A"]
)

# ------------------------------------------------------------
# 5. CASE B
# Initial savings counted toward goal
# ------------------------------------------------------------

df["required_funding_case_B"] = (
    df["target_amount"]
    - df["initial_savings"]
).clip(lower=0)

df["shortfall_case_B"] = (
    df["required_funding_case_B"]
    - df["max_new_goal_contribution"]
).clip(lower=0)

df["potentially_feasible_case_B"] = (
    df["max_new_goal_contribution"]
    >= df["required_funding_case_B"]
)

# ------------------------------------------------------------
# 6. Compare the two formulations
# ------------------------------------------------------------

comparison = pd.DataFrame({
    "case": [
        "A_initial_savings_excluded",
        "B_initial_savings_included"
    ],
    "mean_required_funding": [
        df["required_funding_case_A"].mean(),
        df["required_funding_case_B"].mean()
    ],
    "mean_max_new_goal_contribution": [
        df["max_new_goal_contribution"].mean(),
        df["max_new_goal_contribution"].mean()
    ],
    "mean_potential_shortfall": [
        df["shortfall_case_A"].mean(),
        df["shortfall_case_B"].mean()
    ],
    "potentially_feasible_users": [
        df["potentially_feasible_case_A"].sum(),
        df["potentially_feasible_case_B"].sum()
    ],
    "potentially_infeasible_users": [
        (~df["potentially_feasible_case_A"]).sum(),
        (~df["potentially_feasible_case_B"]).sum()
    ]
})

print("\n" + "=" * 75)
print("CASE A vs CASE B")
print("=" * 75)

print(comparison.to_string(index=False))

# ------------------------------------------------------------
# 7. Monthly budget feasibility
# ------------------------------------------------------------

# If both goal and investment are simultaneously allocated,
# their maximum candidate allocations must be compared with
# the available monthly surplus.

df["combined_candidate_allocation"] = (
    df["monthly_goal_limit"]
    + df["monthly_investment_limit"]
)

df["monthly_budget_available"] = df["positive_surplus"]

df["budget_excess_if_both_max"] = (
    df["combined_candidate_allocation"]
    - df["monthly_budget_available"]
)

budget_conflict_users = (
    df["budget_excess_if_both_max"] > 1e-9
).sum()

budget_nonconflict_users = (
    df["budget_excess_if_both_max"] <= 1e-9
).sum()

print("\n" + "=" * 75)
print("MONTHLY BUDGET COMPATIBILITY")
print("=" * 75)

print("Users where goal-limit + investment-limit exceeds surplus:",
      budget_conflict_users)

print("Users where combined limits fit within surplus:",
      budget_nonconflict_users)

print("\nMean monthly surplus:",
      df["monthly_budget_available"].mean())

print("Mean goal monthly limit:",
      df["monthly_goal_limit"].mean())

print("Mean investment monthly limit:",
      df["monthly_investment_limit"].mean())

# ------------------------------------------------------------
# 8. Check whether investment capacity can coexist with goal
# ------------------------------------------------------------

df["goal_plus_investment_ratio_of_surplus"] = np.where(
    df["monthly_budget_available"] > 0,
    df["combined_candidate_allocation"]
    / df["monthly_budget_available"],
    np.nan
)

print("\nMean combined allocation / surplus ratio:",
      df["goal_plus_investment_ratio_of_surplus"].mean())

print("Median combined allocation / surplus ratio:",
      df["goal_plus_investment_ratio_of_surplus"].median())

# ------------------------------------------------------------
# 9. Initial investment diagnostic
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("INITIAL INVESTMENT DIAGNOSTIC")
print("=" * 75)

print("Mean initial investment:",
      df["initial_investment"].mean())

print("Users with initial investment > 0:",
      (df["initial_investment"] > 0).sum())

print("Users with initial investment = 0:",
      (df["initial_investment"] == 0).sum())

print("\nInitial investment is treated as an initial portfolio state.")
print("No return assumption is introduced in this pre-check.")

# ------------------------------------------------------------
# 10. Risk diagnostic
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("RISK PROFILE DIAGNOSTIC")
print("=" * 75)

risk_summary = (
    df.groupby("risk_profile")
      .agg(
          users=("user_id", "count"),
          mean_risk_score=("risk_score", "mean"),
          mean_investment_ratio=("investment_capacity_ratio", "mean"),
          mean_initial_investment=("initial_investment", "mean"),
          mean_monthly_investment_limit=("monthly_investment_limit", "mean")
      )
      .reset_index()
)

print(risk_summary.to_string(index=False))

# ------------------------------------------------------------
# 11. Representative users
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("REPRESENTATIVE USER CHECK")
print("=" * 75)

# Select representative users without modifying the data
representatives = []

# Conservative with positive surplus
x = df[
    (df["risk_profile"] == "conservative") &
    (df["positive_surplus"] > 0)
]

if len(x) > 0:
    representatives.append(
        x.sort_values("target_amount").iloc[len(x)//2]
    )

# Moderate with positive surplus
x = df[
    (df["risk_profile"] == "moderate") &
    (df["positive_surplus"] > 0)
]

if len(x) > 0:
    representatives.append(
        x.sort_values("target_amount").iloc[len(x)//2]
    )

# Aggressive with positive surplus
x = df[
    (df["risk_profile"] == "aggressive") &
    (df["positive_surplus"] > 0)
]

if len(x) > 0:
    representatives.append(
        x.sort_values("target_amount").iloc[len(x)//2]
    )

# Negative original surplus
x = df[df["calculated_surplus"] < 0]

if len(x) > 0:
    representatives.append(
        x.iloc[len(x)//2]
    )

# Target <= initial savings
x = df[
    df["target_amount"] <= df["initial_savings"]
]

if len(x) > 0:
    representatives.append(
        x.iloc[len(x)//2]
    )

rep_df = pd.DataFrame(representatives)

rep_cols = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "calculated_surplus",
    "initial_savings",
    "initial_investment",
    "risk_profile",
    "risk_score",
    "investment_capacity_ratio",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "monthly_goal_limit",
    "monthly_investment_limit",
    "max_new_goal_contribution",
    "required_funding_case_A",
    "shortfall_case_A",
    "required_funding_case_B",
    "shortfall_case_B",
    "potentially_feasible_case_A",
    "potentially_feasible_case_B"
]

rep_df = rep_df[rep_cols]

print(rep_df.to_string(index=False))

# ------------------------------------------------------------
# 12. Check for impossible / invalid quantities
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("SANITY CHECKS")
print("=" * 75)

checks = {
    "negative_goal_monthly_limit":
        (df["monthly_goal_limit"] < 0).sum(),

    "negative_investment_limit":
        (df["monthly_investment_limit"] < 0).sum(),

    "negative_horizon":
        (df["horizon"] <= 0).sum(),

    "negative_target":
        (df["target_amount"] < 0).sum(),

    "negative_income":
        (df["monthly_income"] < 0).sum(),

    "negative_initial_savings":
        (df["initial_savings"] < 0).sum(),

    "negative_initial_investment":
        (df["initial_investment"] < 0).sum(),

    "missing_values":
        df.isna().sum().sum(),

    "duplicate_user_ids":
        df["user_id"].duplicated().sum()
}

for name, value in checks.items():
    print(f"{name}: {value}")

# ------------------------------------------------------------
# 13. Save detailed diagnostic
# ------------------------------------------------------------

diagnostic_cols = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "calculated_surplus",
    "positive_surplus",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "monthly_goal_limit",
    "monthly_investment_limit",
    "max_new_goal_contribution",
    "required_funding_case_A",
    "shortfall_case_A",
    "potentially_feasible_case_A",
    "required_funding_case_B",
    "shortfall_case_B",
    "potentially_feasible_case_B",
    "combined_candidate_allocation",
    "monthly_budget_available",
    "budget_excess_if_both_max"
]

diagnostic_path = os.path.join(
    OUTPUT_DIR,
    "lp_formulation_precheck.csv"
)

comparison_path = os.path.join(
    OUTPUT_DIR,
    "lp_initial_savings_case_comparison.csv"
)

representative_path = os.path.join(
    OUTPUT_DIR,
    "lp_representative_users_precheck.csv"
)

df[diagnostic_cols].to_csv(
    diagnostic_path,
    index=False
)

comparison.to_csv(
    comparison_path,
    index=False
)

rep_df.to_csv(
    representative_path,
    index=False
)

# ------------------------------------------------------------
# 14. Final status
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 5D COMPLETE")
print("=" * 75)

print("\nSaved:")
print(diagnostic_path)
print(comparison_path)
print(representative_path)

print("\nNO LP SOLVER HAS BEEN RUN.")
print("NO ORIGINAL DATASET HAS BEEN MODIFIED.")
print("NO NIFTY/WALR ASSUMPTION HAS BEEN INTRODUCED.")
print("INITIAL SAVINGS TREATMENT HAS NOT BEEN SELECTED.")
print("\nNext step depends on these pre-check results.")

===========================================================================
STEP 5D — LP FORMULATION PRE-CHECK
===========================================================================

Input shape: (10000, 38)
Unique users: 10000

===========================================================================
CASE A vs CASE B
===========================================================================
                      case  mean_required_funding  mean_max_new_goal_contribution  mean_potential_shortfall  potentially_feasible_users  potentially_infeasible_users
A_initial_savings_excluded          138353.834973                    564385.76698              43658.094611                        4890                          5110
B_initial_savings_included           24896.142519                    564385.76698              12240.307624                        7339                          2661

===========================================================================
MONTHLY BUDGET COMPATIBILITY
===========================================================================
Users where goal-limit + investment-limit exceeds surplus: 1782
Users where combined limits fit within surplus: 8218

Mean monthly surplus: 12896.268635809962
Mean goal monthly limit: 8824.98935383048
Mean investment monthly limit: 4126.6312606214005

Mean combined allocation / surplus ratio: 0.6574179985689584
Median combined allocation / surplus ratio: 0.6201358523570883

===========================================================================
INITIAL INVESTMENT DIAGNOSTIC
===========================================================================
Mean initial investment: 56968.534834146085
Users with initial investment > 0: 5445
Users with initial investment = 0: 4555

Initial investment is treated as an initial portfolio state.
No return assumption is introduced in this pre-check.

===========================================================================
RISK PROFILE DIAGNOSTIC
===========================================================================
risk_profile  users  mean_risk_score  mean_investment_ratio  mean_initial_investment  mean_monthly_investment_limit
  aggressive   3333         0.737324               0.344191            114485.540659                    9273.451232
conservative   3333         0.227601               0.029605             15961.616749                     209.321509
    moderate   3334         0.535065               0.187888             40463.399131                    2897.489820

===========================================================================
REPRESENTATIVE USER CHECK
===========================================================================
   user_id  monthly_income  monthly_expenditure  monthly_emi  calculated_surplus  initial_savings  initial_investment risk_profile  risk_score  investment_capacity_ratio  goal_horizon_months  target_amount  goal_specific_monthly_capacity  goal_allocation_factor  monthly_goal_limit  monthly_investment_limit  max_new_goal_contribution  required_funding_case_A  shortfall_case_A  required_funding_case_B  shortfall_case_B  potentially_feasible_case_A  potentially_feasible_case_B
USER_04843    49236.105854              38000.0 11225.011889           11.093965    206688.692539        55729.614387 conservative    0.343675                   0.000225                   85  110605.468493                        2.364124                 0.21310            0.503795                  0.002500               4.282256e+01            110605.468493     110562.645935                      0.0               0.0                        False                         True
USER_02048    46492.736115              43000.0     0.000000         3492.736115    108969.205967            0.000000     moderate    0.538450                   0.075124                   95  104442.680231                     1215.472168                 0.34800          422.984314                262.389495               4.018351e+04            104442.680231      64259.170354                      0.0               0.0                        False                         True
USER_09730    54153.307504              28500.0     0.000000        25653.307504    273095.294391       145911.528265   aggressive    0.834875                   0.473716                   82  121651.618117                    22082.367099                 0.86080        19008.501599              12152.391354               1.558697e+06            121651.618117          0.000000                      0.0               0.0                         True                         True
USER_04883    33824.167347              31800.0  7855.136966        -5830.969619     81499.512536            0.000000 conservative    0.210563                   0.000000                   90   75983.626464                        0.000000                 0.10655            0.000000                  0.000000               0.000000e+00             75983.626464      75983.626464                      0.0               0.0                        False                         True
USER_05036    71330.353563              46500.0     0.000000        24830.353563    233915.278046       130277.341054   aggressive    0.752125                   0.348104                   23  160238.650818                    21210.088013                 0.85420        18117.657181               8643.535708               4.167061e+05            160238.650818          0.000000                      0.0               0.0                         True                         True

===========================================================================
SANITY CHECKS
===========================================================================
negative_goal_monthly_limit: 0
negative_investment_limit: 0
negative_horizon: 0
negative_target: 0
negative_income: 0
negative_initial_savings: 0
negative_initial_investment: 0
missing_values: 2130
duplicate_user_ids: 0

===========================================================================
STEP 5D COMPLETE
===========================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_formulation_precheck.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_initial_savings_case_comparison.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_representative_users_precheck.csv

NO LP SOLVER HAS BEEN RUN.
NO ORIGINAL DATASET HAS BEEN MODIFIED.
NO NIFTY/WALR ASSUMPTION HAS BEEN INTRODUCED.
INITIAL SAVINGS TREATMENT HAS NOT BEEN SELECTED.

Next step depends on these pre-check results.

In [93]:
# ============================================================
# GOALPILOT AI — STEP 5D.1
# DATA INTEGRITY + EXISTING GOAL FUNDING AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 5D.1 — DATA INTEGRITY + EXISTING GOAL FUNDING AUDIT")
print("=" * 75)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_INPUT = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. Load LP input
# ------------------------------------------------------------

df = pd.read_csv(LP_INPUT)

print("\nLP input shape:", df.shape)
print("Unique users:", df["user_id"].nunique())

# ------------------------------------------------------------
# 2. EXACT missing-value audit
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("1. EXACT MISSING-VALUE AUDIT")
print("=" * 75)

missing_counts = df.isna().sum()

missing_table = (
    missing_counts[missing_counts > 0]
    .sort_values(ascending=False)
    .reset_index()
)

missing_table.columns = ["column", "missing_count"]

if len(missing_table) == 0:
    print("NO MISSING VALUES FOUND.")
else:
    print(missing_table.to_string(index=False))

    print("\nTotal missing cells:",
          int(missing_table["missing_count"].sum()))

    print("\nColumns containing missing values:")
    for _, row in missing_table.iterrows():
        print(
            f"  {row['column']}: "
            f"{int(row['missing_count'])}"
        )

# ------------------------------------------------------------
# 3. Missing-value pattern by user
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("2. MISSING-VALUE PATTERN")
print("=" * 75)

df["missing_field_count"] = df.isna().sum(axis=1)

print(
    df["missing_field_count"]
    .value_counts()
    .sort_index()
    .to_string()
)

users_with_missing = (
    df["missing_field_count"] > 0
).sum()

print("\nUsers with at least one missing field:",
      users_with_missing)

# Show first affected users
if users_with_missing > 0:

    affected = df[
        df["missing_field_count"] > 0
    ].copy()

    print("\nFirst affected users and missing columns:")

    for _, row in affected.head(10).iterrows():

        missing_cols = [
            c for c in df.columns
            if pd.isna(row[c])
        ]

        print(
            row["user_id"],
            "->",
            missing_cols
        )

# ------------------------------------------------------------
# 4. Check whether missing values existed in ORIGINAL input
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("3. SOURCE INPUT CONSISTENCY")
print("=" * 75)

source_missing = (
    df.drop(columns=["missing_field_count"])
      .isna()
      .sum()
)

print(
    "Total missing cells in final_optimisation_input.csv:",
    int(source_missing.sum())
)

# ------------------------------------------------------------
# 5. Check core LP fields specifically
# ------------------------------------------------------------

core_fields = [
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor"
]

print("\n" + "=" * 75)
print("4. CORE LP FIELD COMPLETENESS")
print("=" * 75)

core_missing = (
    df[core_fields]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print(core_missing.to_string())

# ------------------------------------------------------------
# 6. Recalculate current quantities
# ------------------------------------------------------------

df["calculated_surplus"] = (
    df["monthly_income"]
    - df["monthly_expenditure"]
    - df["monthly_emi"]
)

df["positive_surplus"] = (
    df["calculated_surplus"].clip(lower=0)
)

df["monthly_goal_limit"] = (
    df["goal_specific_monthly_capacity"]
    * df["goal_allocation_factor"]
)

df["monthly_investment_limit"] = (
    df["positive_surplus"]
    * df["investment_capacity_ratio"]
)

df["max_new_goal_contribution"] = (
    df["monthly_goal_limit"]
    * df["goal_horizon_months"]
)

# ------------------------------------------------------------
# 7. Audit existing simulation goal-funding fields
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("5. EXISTING SIMULATION GOAL-FUNDING FIELDS")
print("=" * 75)

funding_fields = [
    "target_amount",
    "initial_savings",
    "initial_investment",
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual",
    "goal_funding_ratio",
    "goal_funding_ratio_capped",
    "goal_shortfall_ratio",
    "goal_outcome"
]

available_funding_fields = [
    c for c in funding_fields
    if c in df.columns
]

print("Available fields:")
for c in available_funding_fields:
    print("✓", c)

# ------------------------------------------------------------
# 8. Test mathematical relationships in existing simulation
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("6. EXISTING GOAL-FUNDING RELATIONSHIP TESTS")
print("=" * 75)

# Relationship 1:
# shortfall should normally correspond to target - funding,
# but we measure it rather than assuming it.

if all(
    c in df.columns
    for c in [
        "target_amount",
        "goal_horizon_funding_actual",
        "goal_shortfall_actual"
    ]
):

    expected_shortfall = (
        df["target_amount"]
        - df["goal_horizon_funding_actual"]
    ).clip(lower=0)

    difference = (
        df["goal_shortfall_actual"]
        - expected_shortfall
    ).abs()

    print(
        "\nShortfall relationship:"
    )
    print(
        "Mean absolute difference:",
        difference.mean()
    )
    print(
        "Maximum absolute difference:",
        difference.max()
    )
    print(
        "Rows matching within 1e-6:",
        (difference <= 1e-6).sum(),
        "/",
        len(df)
    )

# Relationship 2:
# funding ratio vs funding / target

if all(
    c in df.columns
    for c in [
        "target_amount",
        "goal_horizon_funding_actual",
        "goal_funding_ratio"
    ]
):

    expected_ratio = np.where(
        df["target_amount"] > 0,
        df["goal_horizon_funding_actual"]
        / df["target_amount"],
        np.nan
    )

    ratio_difference = np.abs(
        df["goal_funding_ratio"]
        - expected_ratio
    )

    print(
        "\nFunding-ratio relationship:"
    )
    print(
        "Mean absolute difference:",
        np.nanmean(ratio_difference)
    )
    print(
        "Maximum absolute difference:",
        np.nanmax(ratio_difference)
    )
    print(
        "Rows matching within 1e-6:",
        np.nansum(ratio_difference <= 1e-6),
        "/",
        len(df)
    )

# ------------------------------------------------------------
# 9. Determine whether initial savings appears in
#    existing goal funding
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("7. INITIAL SAVINGS vs EXISTING GOAL FUNDING")
print("=" * 75)

if "goal_horizon_funding_actual" in df.columns:

    df["funding_minus_initial_savings"] = (
        df["goal_horizon_funding_actual"]
        - df["initial_savings"]
    )

    print(
        "Mean existing goal-horizon funding:",
        df["goal_horizon_funding_actual"].mean()
    )

    print(
        "Mean initial savings:",
        df["initial_savings"].mean()
    )

    print(
        "Mean funding - initial savings:",
        df["funding_minus_initial_savings"].mean()
    )

    print(
        "\nFunding >= initial savings:",
        (
            df["goal_horizon_funding_actual"]
            >= df["initial_savings"]
        ).sum()
    )

    print(
        "Funding < initial savings:",
        (
            df["goal_horizon_funding_actual"]
            < df["initial_savings"]
        ).sum()
    )

# ------------------------------------------------------------
# 10. Compare existing funding against our candidate
#     maximum new contributions
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("8. EXISTING FUNDING vs CANDIDATE LP CAPACITY")
print("=" * 75)

if "goal_horizon_funding_actual" in df.columns:

    df["actual_funding_minus_max_new"] = (
        df["goal_horizon_funding_actual"]
        - df["max_new_goal_contribution"]
    )

    print(
        "Mean existing funding:",
        df["goal_horizon_funding_actual"].mean()
    )

    print(
        "Mean maximum new goal contribution:",
        df["max_new_goal_contribution"].mean()
    )

    print(
        "Users where actual funding > candidate maximum:",
        (
            df["actual_funding_minus_max_new"] > 1e-6
        ).sum()
    )

    print(
        "Users where actual funding <= candidate maximum:",
        (
            df["actual_funding_minus_max_new"] <= 1e-6
        ).sum()
    )

# ------------------------------------------------------------
# 11. Inspect representative users
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("9. REPRESENTATIVE FUNDING COMPARISON")
print("=" * 75)

rep_cols = [
    "user_id",
    "initial_savings",
    "initial_investment",
    "target_amount",
    "goal_horizon_months",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "monthly_goal_limit",
    "max_new_goal_contribution",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_funding_ratio",
    "goal_achieved_on_time_actual",
    "goal_outcome"
]

rep_cols = [
    c for c in rep_cols
    if c in df.columns
]

print(
    df[rep_cols]
    .head(10)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 12. Save audit files
# ------------------------------------------------------------

missing_path = os.path.join(
    OUT_DIR,
    "lp_5d1_missing_value_audit.csv"
)

funding_path = os.path.join(
    OUT_DIR,
    "lp_5d1_existing_goal_funding_audit.csv"
)

df[
    [
        c for c in [
            "user_id",
            "initial_savings",
            "initial_investment",
            "target_amount",
            "goal_horizon_months",
            "goal_specific_monthly_capacity",
            "goal_allocation_factor",
            "monthly_goal_limit",
            "max_new_goal_contribution",
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_shortfall_actual",
            "goal_funding_ratio",
            "goal_achieved_on_time_actual",
            "goal_outcome"
        ]
        if c in df.columns
    ]
].to_csv(
    funding_path,
    index=False
)

missing_table.to_csv(
    missing_path,
    index=False
)

# ------------------------------------------------------------
# 13. Final status
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 5D.1 COMPLETE")
print("=" * 75)

print("\nSaved:")
print(missing_path)
print(funding_path)

print("\nIMPORTANT:")
print("• No missing values were filled.")
print("• No original dataset was modified.")
print("• No LP solver was run.")
print("• No initial-savings assumption was imposed.")
print("• Existing simulation funding logic was audited.")

===========================================================================
STEP 5D.1 — DATA INTEGRITY + EXISTING GOAL FUNDING AUDIT
===========================================================================

LP input shape: (10000, 38)
Unique users: 10000

===========================================================================
1. EXACT MISSING-VALUE AUDIT
===========================================================================
NO MISSING VALUES FOUND.

===========================================================================
2. MISSING-VALUE PATTERN
===========================================================================
missing_field_count
0    10000

Users with at least one missing field: 0

===========================================================================
3. SOURCE INPUT CONSISTENCY
===========================================================================
Total missing cells in final_optimisation_input.csv: 0

===========================================================================
4. CORE LP FIELD COMPLETENESS
===========================================================================
monthly_income                    0
monthly_expenditure               0
monthly_emi                       0
initial_savings                   0
initial_investment                0
investment_capacity_ratio         0
risk_score                        0
risk_profile                      0
goal_horizon_months               0
target_amount                     0
goal_specific_monthly_capacity    0
goal_allocation_factor            0

===========================================================================
5. EXISTING SIMULATION GOAL-FUNDING FIELDS
===========================================================================
Available fields:
✓ target_amount
✓ initial_savings
✓ initial_investment
✓ goal_horizon_funding_actual
✓ goal_progress_at_deadline_actual
✓ goal_progress_at_deadline_actual_capped
✓ goal_shortfall_actual
✓ goal_achieved_on_time_actual
✓ goal_funding_ratio
✓ goal_funding_ratio_capped
✓ goal_shortfall_ratio
✓ goal_outcome

===========================================================================
6. EXISTING GOAL-FUNDING RELATIONSHIP TESTS
===========================================================================

Shortfall relationship:
Mean absolute difference: 9.550831236992962e-13
Maximum absolute difference: 1.1641532182693481e-10
Rows matching within 1e-6: 10000 / 10000

Funding-ratio relationship:
Mean absolute difference: 3.280102104779312e-16
Maximum absolute difference: 1.4210854715202004e-14
Rows matching within 1e-6: 10000 / 10000

===========================================================================
7. INITIAL SAVINGS vs EXISTING GOAL FUNDING
===========================================================================
Mean existing goal-horizon funding: 944964.8307231049
Mean initial savings: 166794.7643881863
Mean funding - initial savings: 778170.0663349185

Funding >= initial savings: 6496
Funding < initial savings: 3504

===========================================================================
8. EXISTING FUNDING vs CANDIDATE LP CAPACITY
===========================================================================
Mean existing funding: 944964.8307231049
Mean maximum new goal contribution: 564385.7669796908
Users where actual funding > candidate maximum: 8535
Users where actual funding <= candidate maximum: 1465

===========================================================================
9. REPRESENTATIVE FUNDING COMPARISON
===========================================================================
   user_id  initial_savings  initial_investment  target_amount  goal_horizon_months  goal_specific_monthly_capacity  goal_allocation_factor  monthly_goal_limit  max_new_goal_contribution  goal_horizon_funding_actual  goal_shortfall_actual  goal_funding_ratio  goal_achieved_on_time_actual goal_outcome
USER_00001    178733.652470        45777.548120  115357.183592                   48                    10103.627663                 0.69770         7049.301020               3.383664e+05                 5.811302e+05               0.000000            5.037660                          True      success
USER_00002     13659.350863            0.000000   59340.387689                   51                        0.000000                 0.10655            0.000000               0.000000e+00                 0.000000e+00           59340.387689            0.000000                         False      failure
USER_00003     85318.549015            0.000000   99893.237726                   46                      748.407439                 0.30330          226.991976               1.044163e+04                 4.093773e+04           58955.510123            0.409815                         False      failure
USER_00004    107702.527041        60534.274631   75476.307623                   60                      255.370474                 0.24420           62.361470               3.741688e+03                 4.566919e+04           29807.117161            0.605080                         False      failure
USER_00005    205810.045973       105774.934379  206040.342056                  120                    38345.091895                 0.94170        36109.573038               4.333149e+06                 7.318348e+06               0.000000           35.519005                          True      success
USER_00006    229003.169045       118987.882781  110291.964774                   18                    18189.879501                 0.82320        14973.908805               2.695304e+05                 3.502230e+05               0.000000            3.175418                          True      success
USER_00007    126015.560330        90329.680595  128020.414837                   75                    23523.073803                 0.87160        20502.711127               1.537703e+06                 2.348219e+06               0.000000           18.342532                          True      success
USER_00008     26481.524416            0.000000  269916.171830                   11                        0.000000                 0.10655            0.000000               0.000000e+00                 0.000000e+00          269916.171830            0.000000                         False      failure
USER_00009    165575.931991            0.000000  182600.732773                   55                    23871.515994                 0.87490        20885.189344               1.148685e+06                 1.616717e+06               0.000000            8.853834                          True      success
USER_00010     76879.539877        15171.499059   96702.526658                   24                     2066.324108                 0.40940          845.953090               2.030287e+04                 5.423986e+04           42462.667060            0.560894                         False      failure

===========================================================================
STEP 5D.1 COMPLETE
===========================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5d1_missing_value_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5d1_existing_goal_funding_audit.csv

IMPORTANT:
• No missing values were filled.
• No original dataset was modified.
• No LP solver was run.
• No initial-savings assumption was imposed.
• Existing simulation funding logic was audited.

In [94]:
# ============================================================
# GOALPILOT AI — STEP 5E
# LOCATE EXISTING GOAL-FUNDING / SIMULATION LOGIC
# ============================================================

import os
import glob

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

print("=" * 75)
print("STEP 5E — LOCATING EXISTING SIMULATION LOGIC")
print("=" * 75)

# ------------------------------------------------------------
# 1. Search project files for goal-funding keywords
# ------------------------------------------------------------

search_terms = [
    "goal_horizon_funding_actual",
    "goal_progress_at_deadline_actual",
    "goal_shortfall_actual",
    "goal_funding_ratio",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "goal_outcome"
]

# Search Python files
python_files = glob.glob(
    os.path.join(BASE_DIR, "**", "*.py"),
    recursive=True
)

# Search notebooks
notebook_files = glob.glob(
    os.path.join(BASE_DIR, "**", "*.ipynb"),
    recursive=True
)

all_code_files = python_files + notebook_files

print("\nPython files found:", len(python_files))
print("Notebook files found:", len(notebook_files))
print("Total code files:", len(all_code_files))

# ------------------------------------------------------------
# 2. Search contents
# ------------------------------------------------------------

matches = []

for filepath in all_code_files:

    try:

        with open(
            filepath,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:

            text = f.read()

        found_terms = [
            term for term in search_terms
            if term in text
        ]

        if found_terms:

            matches.append({
                "file": filepath,
                "matched_terms": ", ".join(found_terms)
            })

    except Exception as e:

        print(
            "Could not read:",
            filepath,
            "|",
            str(e)
        )

# ------------------------------------------------------------
# 3. Display matches
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("FILES CONTAINING GOAL-FUNDING LOGIC")
print("=" * 75)

if len(matches) == 0:

    print(
        "No Python/notebook file under GoalPilot_AI "
        "contains the searched fields."
    )

else:

    for i, item in enumerate(matches, 1):

        print(f"\n[{i}]")
        print("File:", item["file"])
        print("Matched:", item["matched_terms"])

# ------------------------------------------------------------
# 4. Search the whole GoalPilot_AI directory for text files
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("OTHER RELEVANT PROJECT FILES")
print("=" * 75)

extensions = [
    "*.txt",
    "*.md",
    "*.csv"
]

other_files = []

for ext in extensions:

    other_files.extend(
        glob.glob(
            os.path.join(BASE_DIR, "**", ext),
            recursive=True
        )
    )

for filepath in other_files:

    filename_lower = os.path.basename(filepath).lower()

    if any(
        keyword.replace("_", "") in
        filename_lower.replace("_", "")
        for keyword in [
            "simulation",
            "methodology",
            "goal",
            "optimization",
            "assumption"
        ]
    ):

        print(filepath)

# ------------------------------------------------------------
# 5. Save search results
# ------------------------------------------------------------

output_dir = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(output_dir, exist_ok=True)

matches_path = os.path.join(
    output_dir,
    "lp_5e_goal_funding_logic_files.csv"
)

import pandas as pd

pd.DataFrame(matches).to_csv(
    matches_path,
    index=False
)

print("\n" + "=" * 75)
print("STEP 5E SEARCH COMPLETE")
print("=" * 75)

print("\nSearch results saved to:")
print(matches_path)

print(
    "\nIMPORTANT: Do not modify any files."
)

print(
    "We are locating the existing simulation formula "
    "before constructing the LP."
)

===========================================================================
STEP 5E — LOCATING EXISTING SIMULATION LOGIC
===========================================================================

Python files found: 0
Notebook files found: 0
Total code files: 0

===========================================================================
FILES CONTAINING GOAL-FUNDING LOGIC
===========================================================================
No Python/notebook file under GoalPilot_AI contains the searched fields.

===========================================================================
OTHER RELEVANT PROJECT FILES
===========================================================================
/content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/portfolio_simulation_validated.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/monthly_financial_simulation_base.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/final_goal_outcome_dataset.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/final_simulation_summary.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/goal_success_by_horizon.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/goal_success_by_risk_profile.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/goal_success_by_financial_situation.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/06_results/simulation_methodology_and_assumptions.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/07_validation/final_simulation_validation.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/07_validation/goal_success_validation_by_horizon.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/07_validation/goal_success_validation_by_risk_profile.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/07_validation/goal_success_validation_by_financial_situation.csv
/content/drive/MyDrive/GoalPilot_AI/simulation/07_validation/simulation_methodology_validation.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5d1_existing_goal_funding_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5e_goal_funding_logic_files.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5f_simulation_column_inventory.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5f_simulation_relationship_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5g_goal_funding_reconstruction_results.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5h_goal_funding_aggregation_comparison.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5h_goal_funding_aggregation_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5i_goal_funding_formula_candidates.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5i_goal_funding_formula_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l2_policy_vs_optimization_audit.csv

===========================================================================
STEP 5E SEARCH COMPLETE
===========================================================================

Search results saved to:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5e_goal_funding_logic_files.csv

IMPORTANT: Do not modify any files.
We are locating the existing simulation formula before constructing the LP.

In [95]:
# ============================================================
# GOALPILOT AI — STEP 5F
# TRACE ACTUAL SIMULATION FUNDING MECHANISM
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5F — TRACE ACTUAL SIMULATION FUNDING MECHANISM")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

MONTHLY_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

PORTFOLIO_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "portfolio_simulation_validated.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. Load simulation files
# ------------------------------------------------------------

monthly = pd.read_csv(MONTHLY_FILE)
portfolio = pd.read_csv(PORTFOLIO_FILE)

print("\nMONTHLY SIMULATION")
print("Shape:", monthly.shape)

print("\nPORTFOLIO SIMULATION")
print("Shape:", portfolio.shape)

# ------------------------------------------------------------
# 2. Display ALL columns
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("1. MONTHLY SIMULATION COLUMNS")
print("=" * 80)

for i, col in enumerate(monthly.columns, 1):
    print(f"{i:03d}. {col}")

print("\n" + "=" * 80)
print("2. PORTFOLIO SIMULATION COLUMNS")
print("=" * 80)

for i, col in enumerate(portfolio.columns, 1):
    print(f"{i:03d}. {col}")

# ------------------------------------------------------------
# 3. Search column names for relevant concepts
# ------------------------------------------------------------

keywords = [
    "goal",
    "saving",
    "surplus",
    "income",
    "expenditure",
    "emi",
    "investment",
    "portfolio",
    "allocation",
    "contribution",
    "fund",
    "target",
    "return"
]

def relevant_columns(dataframe):
    result = []

    for col in dataframe.columns:

        col_lower = str(col).lower()

        if any(
            keyword in col_lower
            for keyword in keywords
        ):
            result.append(col)

    return result

monthly_relevant = relevant_columns(monthly)
portfolio_relevant = relevant_columns(portfolio)

print("\n" + "=" * 80)
print("3. RELEVANT MONTHLY SIMULATION COLUMNS")
print("=" * 80)

for col in monthly_relevant:
    print("✓", col)

print("\n" + "=" * 80)
print("4. RELEVANT PORTFOLIO SIMULATION COLUMNS")
print("=" * 80)

for col in portfolio_relevant:
    print("✓", col)

# ------------------------------------------------------------
# 4. Display sample data for relevant fields
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("5. MONTHLY SIMULATION SAMPLE")
print("=" * 80)

if monthly_relevant:
    print(
        monthly[monthly_relevant]
        .head(10)
        .to_string(index=False)
    )
else:
    print("No relevant columns identified.")

print("\n" + "=" * 80)
print("6. PORTFOLIO SIMULATION SAMPLE")
print("=" * 80)

if portfolio_relevant:
    print(
        portfolio[portfolio_relevant]
        .head(10)
        .to_string(index=False)
    )
else:
    print("No relevant columns identified.")

# ------------------------------------------------------------
# 5. Identify user/time columns
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("7. USER / TIME STRUCTURE")
print("=" * 80)

for name, data in [
    ("monthly", monthly),
    ("portfolio", portfolio)
]:

    print(f"\n{name.upper()}")

    possible_id = [
        c for c in data.columns
        if "user" in str(c).lower() or "id" == str(c).lower()
    ]

    possible_time = [
        c for c in data.columns
        if any(
            x in str(c).lower()
            for x in ["month", "period", "date", "time"]
        )
    ]

    print("Possible ID columns:", possible_id)
    print("Possible time columns:", possible_time)

    if possible_id:
        id_col = possible_id[0]
        print(
            "Unique values in",
            id_col,
            ":",
            data[id_col].nunique()
        )

# ------------------------------------------------------------
# 6. Numerical relationship audit
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("8. NUMERICAL RELATIONSHIP AUDIT")
print("=" * 80)

# Helper function
def test_relationship(data, lhs, rhs, tolerance=1e-6):

    if lhs not in data.columns or rhs not in data.columns:
        return None

    a = pd.to_numeric(data[lhs], errors="coerce")
    b = pd.to_numeric(data[rhs], errors="coerce")

    valid = a.notna() & b.notna()

    if valid.sum() == 0:
        return None

    diff = (a[valid] - b[valid]).abs()

    return {
        "lhs": lhs,
        "rhs": rhs,
        "rows_tested": int(valid.sum()),
        "mean_abs_difference": float(diff.mean()),
        "max_abs_difference": float(diff.max()),
        "matching_rows": int((diff <= tolerance).sum())
    }

# Candidate surplus formulas
income_candidates = [
    c for c in monthly.columns
    if "income" in str(c).lower()
]

expense_candidates = [
    c for c in monthly.columns
    if any(
        x in str(c).lower()
        for x in ["expenditure", "expense", "spending"]
    )
]

emi_candidates = [
    c for c in monthly.columns
    if "emi" in str(c).lower()
]

surplus_candidates = [
    c for c in monthly.columns
    if "surplus" in str(c).lower()
]

print("\nIncome candidates:", income_candidates)
print("Expense candidates:", expense_candidates)
print("EMI candidates:", emi_candidates)
print("Surplus candidates:", surplus_candidates)

# ------------------------------------------------------------
# 7. Test obvious surplus relationship
# ------------------------------------------------------------

relationship_results = []

for income_col in income_candidates:

    for expense_col in expense_candidates:

        for emi_col in emi_candidates:

            for surplus_col in surplus_candidates:

                calculated = (
                    pd.to_numeric(monthly[income_col], errors="coerce")
                    - pd.to_numeric(monthly[expense_col], errors="coerce")
                    - pd.to_numeric(monthly[emi_col], errors="coerce")
                )

                actual = pd.to_numeric(
                    monthly[surplus_col],
                    errors="coerce"
                )

                valid = calculated.notna() & actual.notna()

                if valid.sum() > 0:

                    diff = (
                        calculated[valid]
                        - actual[valid]
                    ).abs()

                    relationship_results.append({
                        "income": income_col,
                        "expense": expense_col,
                        "emi": emi_col,
                        "surplus": surplus_col,
                        "rows_tested": int(valid.sum()),
                        "mean_abs_difference": float(diff.mean()),
                        "max_abs_difference": float(diff.max()),
                        "matching_rows_1e-6":
                            int((diff <= 1e-6).sum())
                    })

if relationship_results:

    relationship_df = pd.DataFrame(
        relationship_results
    )

    print("\nSurplus relationship results:")
    print(
        relationship_df
        .sort_values("mean_abs_difference")
        .head(20)
        .to_string(index=False)
    )

else:

    relationship_df = pd.DataFrame()

    print(
        "\nNo complete income-expense-EMI-surplus "
        "relationship could be tested."
    )

# ------------------------------------------------------------
# 8. Detect possible goal allocation formulas
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("9. GOAL ALLOCATION FORMULA DETECTION")
print("=" * 80)

goal_cols = [
    c for c in monthly.columns
    if "goal" in str(c).lower()
]

allocation_cols = [
    c for c in monthly.columns
    if any(
        x in str(c).lower()
        for x in [
            "allocation",
            "contribution",
            "funding"
        ]
    )
]

print("\nGoal-related columns:")
for c in goal_cols:
    print("✓", c)

print("\nAllocation/contribution/funding columns:")
for c in allocation_cols:
    print("✓", c)

# ------------------------------------------------------------
# 9. Inspect statistics of relevant numeric fields
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("10. RELEVANT NUMERIC FIELD STATISTICS")
print("=" * 80)

relevant_numeric = [
    c for c in monthly_relevant
    if pd.api.types.is_numeric_dtype(monthly[c])
]

if relevant_numeric:

    stats = (
        monthly[relevant_numeric]
        .describe()
        .T[
            [
                "count",
                "mean",
                "min",
                "max"
            ]
        ]
    )

    print(stats.to_string())

# ------------------------------------------------------------
# 10. Check monthly rows per user
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("11. MONTHLY SIMULATION DEPTH")
print("=" * 80)

user_candidates = [
    c for c in monthly.columns
    if "user" in str(c).lower()
]

if user_candidates:

    user_col = user_candidates[0]

    rows_per_user = (
        monthly.groupby(user_col)
        .size()
    )

    print(
        "Rows per user — minimum:",
        rows_per_user.min()
    )

    print(
        "Rows per user — maximum:",
        rows_per_user.max()
    )

    print(
        "Rows per user — mean:",
        rows_per_user.mean()
    )

    print(
        "Rows per user — median:",
        rows_per_user.median()
    )

# ------------------------------------------------------------
# 11. Save column inventories
# ------------------------------------------------------------

column_inventory = []

for source_name, data in [
    ("monthly_financial_simulation_base", monthly),
    ("portfolio_simulation_validated", portfolio)
]:

    for col in data.columns:

        column_inventory.append({
            "source": source_name,
            "column": col,
            "dtype": str(data[col].dtype),
            "non_null": int(data[col].notna().sum()),
            "unique_values": int(data[col].nunique())
        })

column_inventory_df = pd.DataFrame(
    column_inventory
)

inventory_path = os.path.join(
    OUT_DIR,
    "lp_5f_simulation_column_inventory.csv"
)

column_inventory_df.to_csv(
    inventory_path,
    index=False
)

# ------------------------------------------------------------
# 12. Save relationship results
# ------------------------------------------------------------

relationship_path = os.path.join(
    OUT_DIR,
    "lp_5f_simulation_relationship_audit.csv"
)

relationship_df.to_csv(
    relationship_path,
    index=False
)

# ------------------------------------------------------------
# 13. Final
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STEP 5F COMPLETE")
print("=" * 80)

print("\nSaved:")
print(inventory_path)
print(relationship_path)

print("\nNO DATA WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO LP SOLVER WAS RUN.")
print("NO NEW FINANCIAL ASSUMPTIONS WERE INTRODUCED.")

print(
    "\nNext: use the actual simulation columns/formulas "
    "to establish the LP funding equation."
)

================================================================================
STEP 5F — TRACE ACTUAL SIMULATION FUNDING MECHANISM
================================================================================

MONTHLY SIMULATION
Shape: (1430000, 46)

PORTFOLIO SIMULATION
Shape: (1430000, 9)

================================================================================
1. MONTHLY SIMULATION COLUMNS
================================================================================
001. user_id
002. period
003. portfolio_return
004. portfolio_value
005. monthly_income
006. monthly_expenditure
007. monthly_surplus
008. monthly_emi
009. initial_savings
010. initial_investment
011. investment_capacity_ratio
012. risk_score
013. risk_profile
014. inflation_level
015. inflation_change
016. inflation_pct_change
017. inflation_trend
018. inflation_regime
019. nifty_monthly_return
020. nifty_return_volatility
021. nifty_3m_volatility
022. nifty_ma_gap
023. market_return_regime
024. market_volatility_regime
025. average_walr
026. walr_change
027. credit_pressure
028. walr_3period_ma
029. walr_momentum
030. walr_regime
031. annual_inflation_rate
032. monthly_inflation_rate
033. cumulative_inflation_factor
034. monthly_expenditure_dynamic
035. monthly_income_dynamic
036. monthly_surplus_dynamic
037. positive_cash_flow
038. cash_flow_status
039. financial_situation
040. cumulative_cash_flow
041. savings_balance
042. savings_balance_status
043. pre_savings_balance
044. unfunded_deficit
045. total_financial_wealth
046. portfolio_wealth_ratio

================================================================================
2. PORTFOLIO SIMULATION COLUMNS
================================================================================
001. user_id
002. period
003. initial_investment
004. risk_score
005. risk_profile
006. market_exposure
007. nifty_monthly_return
008. portfolio_return
009. portfolio_value

================================================================================
3. RELEVANT MONTHLY SIMULATION COLUMNS
================================================================================
✓ portfolio_return
✓ portfolio_value
✓ monthly_income
✓ monthly_expenditure
✓ monthly_surplus
✓ monthly_emi
✓ initial_savings
✓ initial_investment
✓ investment_capacity_ratio
✓ nifty_monthly_return
✓ nifty_return_volatility
✓ market_return_regime
✓ monthly_expenditure_dynamic
✓ monthly_income_dynamic
✓ monthly_surplus_dynamic
✓ savings_balance
✓ savings_balance_status
✓ pre_savings_balance
✓ unfunded_deficit
✓ portfolio_wealth_ratio

================================================================================
4. RELEVANT PORTFOLIO SIMULATION COLUMNS
================================================================================
✓ initial_investment
✓ nifty_monthly_return
✓ portfolio_return
✓ portfolio_value

================================================================================
5. MONTHLY SIMULATION SAMPLE
================================================================================
 portfolio_return  portfolio_value  monthly_income  monthly_expenditure  monthly_surplus  monthly_emi  initial_savings  initial_investment  investment_capacity_ratio  nifty_monthly_return  nifty_return_volatility market_return_regime  monthly_expenditure_dynamic  monthly_income_dynamic  monthly_surplus_dynamic  savings_balance savings_balance_status  pre_savings_balance  unfunded_deficit  portfolio_wealth_ratio
         0.002879     45909.359714    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.623620                 0.218661               medium                 37151.049489            51742.771909             14591.722421    193325.374891               positive        193325.374891               0.0                0.191901
        -0.028405     44605.295682    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.507522                 0.169805                  low                 37318.993471            51976.678819             14657.685348    207983.060239               positive        207983.060239               0.0                0.176593
        -0.025898     43450.108617    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.516826                 0.237883                  low                 37621.368410            52397.816787             14776.448377    222759.508616               positive        222759.508616               0.0                0.163218
         0.021897     44401.549173    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.694196                 0.064071                 high                 37910.938491            52801.120566             14890.182075    237649.690691               positive        237649.690691               0.0                0.157424
        -0.005489     44157.844623    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.592566                 0.073268                  low                 38199.922756            53203.608440             15003.685684    252653.376375               positive        252653.376375               0.0                0.148774
         0.013954     44774.003918    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.664716                 0.226140               medium                 38491.109867            53609.164365             15118.054498    267771.430874               positive        267771.430874               0.0                0.143256
        -0.046758     42680.449741    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.439413                 0.188240                  low                 38739.515313            53955.135382             15215.620069    282987.050942               positive        282987.050942               0.0                0.131055
        -0.001997     42595.235915    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.605525                 0.113610               medium                 39034.815584            54366.419982             15331.604398    298318.655341               positive        298318.655341               0.0                0.124944
         0.010449     43040.309924    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.651710                 0.118239               medium                 39338.902774            54789.942717             15451.039944    313769.695285               positive        313769.695285               0.0                0.120625
        -0.011500     42545.352023    51351.335334              36870.0     14481.335334          0.0     178733.65247         45777.54812                   0.282005              0.570258                 0.121809                  low                 39516.737103            55037.624581             15520.887478    329290.582762               positive        329290.582762               0.0                0.114420

================================================================================
6. PORTFOLIO SIMULATION SAMPLE
================================================================================
 initial_investment  nifty_monthly_return  portfolio_return  portfolio_value
        45777.54812              0.004053          0.002879     45909.359714
        45777.54812             -0.039979         -0.028405     44605.295682
        45777.54812             -0.036450         -0.025898     43450.108617
        45777.54812              0.030820          0.021897     44401.549173
        45777.54812             -0.007725         -0.005489     44157.844623
        45777.54812              0.019639          0.013954     44774.003918
        45777.54812             -0.065810         -0.046758     42680.449741
        45777.54812             -0.002810         -0.001997     42595.235915
        45777.54812              0.014706          0.010449     43040.309924
        45777.54812             -0.016186         -0.011500     42545.352023

================================================================================
7. USER / TIME STRUCTURE
================================================================================

MONTHLY
Possible ID columns: ['user_id']
Possible time columns: ['period', 'monthly_income', 'monthly_expenditure', 'monthly_surplus', 'monthly_emi', 'nifty_monthly_return', 'walr_3period_ma', 'monthly_inflation_rate', 'monthly_expenditure_dynamic', 'monthly_income_dynamic', 'monthly_surplus_dynamic']
Unique values in user_id : 10000

PORTFOLIO
Possible ID columns: ['user_id']
Possible time columns: ['period', 'nifty_monthly_return']
Unique values in user_id : 10000

================================================================================
8. NUMERICAL RELATIONSHIP AUDIT
================================================================================

Income candidates: ['monthly_income', 'monthly_income_dynamic']
Expense candidates: ['monthly_expenditure', 'monthly_expenditure_dynamic']
EMI candidates: ['monthly_emi']
Surplus candidates: ['monthly_surplus', 'monthly_surplus_dynamic']

Surplus relationship results:
                income                     expense         emi                 surplus  rows_tested  mean_abs_difference  max_abs_difference  matching_rows_1e-6
monthly_income_dynamic monthly_expenditure_dynamic monthly_emi monthly_surplus_dynamic      1430000         4.381543e-12        6.984919e-10             1430000
        monthly_income         monthly_expenditure monthly_emi         monthly_surplus      1430000         5.195491e+03        1.398347e+05              828256
monthly_income_dynamic monthly_expenditure_dynamic monthly_emi         monthly_surplus      1430000         1.211472e+04        7.133111e+05                   0
        monthly_income         monthly_expenditure monthly_emi monthly_surplus_dynamic      1430000         1.253155e+04        7.133111e+05                   0
monthly_income_dynamic         monthly_expenditure monthly_emi monthly_surplus_dynamic      1430000         3.364069e+04        9.428391e+05                   0
        monthly_income monthly_expenditure_dynamic monthly_emi         monthly_surplus      1430000         3.883618e+04        9.428391e+05                   0
monthly_income_dynamic         monthly_expenditure monthly_emi         monthly_surplus      1430000         4.194330e+04        1.503554e+06                   0
        monthly_income monthly_expenditure_dynamic monthly_emi monthly_surplus_dynamic      1430000         4.607085e+04        1.503554e+06                   0

================================================================================
9. GOAL ALLOCATION FORMULA DETECTION
================================================================================

Goal-related columns:

Allocation/contribution/funding columns:

================================================================================
10. RELEVANT NUMERIC FIELD STATISTICS
================================================================================
                                 count          mean           min           max
portfolio_return             1430000.0  3.990393e-03 -1.985240e-01  1.253673e-01
portfolio_value              1430000.0  8.373652e+04  0.000000e+00  9.941608e+06
monthly_income               1430000.0  6.158831e+04  1.257340e+03  8.459932e+05
monthly_expenditure          1430000.0  4.497146e+04  8.500000e+02  5.305000e+05
monthly_surplus              1430000.0  1.661685e+04 -2.606462e+04  4.013533e+05
monthly_emi                  1430000.0  5.195491e+03  0.000000e+00  1.398347e+05
initial_savings              1430000.0  1.667948e+05  7.776881e+00  4.946443e+06
initial_investment           1430000.0  5.696853e+04  0.000000e+00  3.880240e+06
investment_capacity_ratio    1430000.0  1.872281e-01  0.000000e+00  4.999763e-01
nifty_monthly_return         1430000.0  6.339769e-01  0.000000e+00  1.000000e+00
nifty_return_volatility      1430000.0  1.905842e-01  0.000000e+00  1.000000e+00
monthly_expenditure_dynamic  1430000.0  7.861215e+04  8.564793e+02  1.473339e+06
monthly_income_dynamic       1430000.0  1.076592e+05  1.266924e+03  2.349547e+06
monthly_surplus_dynamic      1430000.0  2.385152e+04 -2.102942e+05  1.114664e+06
savings_balance              1430000.0  1.606891e+06  0.000000e+00  1.052729e+08
pre_savings_balance          1430000.0  1.537519e+06 -2.596801e+07  1.052729e+08
unfunded_deficit             1430000.0  6.937227e+04  0.000000e+00  2.596801e+07
portfolio_wealth_ratio       1430000.0  8.001034e-02  0.000000e+00  1.000000e+00

================================================================================
11. MONTHLY SIMULATION DEPTH
================================================================================
Rows per user — minimum: 143
Rows per user — maximum: 143
Rows per user — mean: 143.0
Rows per user — median: 143.0

================================================================================
STEP 5F COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5f_simulation_column_inventory.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5f_simulation_relationship_audit.csv

NO DATA WAS MODIFIED.
NO VALUES WERE FILLED.
NO LP SOLVER WAS RUN.
NO NEW FINANCIAL ASSUMPTIONS WERE INTRODUCED.

Next: use the actual simulation columns/formulas to establish the LP funding equation.

In [96]:
# ============================================================
# GOALPILOT AI — STEP 5G
# RECONSTRUCT EXISTING GOAL-FUNDING CALCULATION
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5G — RECONSTRUCT EXISTING GOAL-FUNDING CALCULATION")
print("=" * 80)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

MONTHLY_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Load data
# ------------------------------------------------------------

monthly = pd.read_csv(MONTHLY_FILE)
lp = pd.read_csv(LP_FILE)

print("\nMonthly simulation shape:", monthly.shape)
print("LP input shape:", lp.shape)

# ------------------------------------------------------------
# 3. Convert period to sortable form
# ------------------------------------------------------------

monthly["period"] = pd.to_datetime(
    monthly["period"],
    errors="coerce"
)

print(
    "\nPeriod range:",
    monthly["period"].min(),
    "to",
    monthly["period"].max()
)

# ------------------------------------------------------------
# 4. Confirm user-level structure
# ------------------------------------------------------------

users_monthly = monthly["user_id"].nunique()
users_lp = lp["user_id"].nunique()

print("\nUsers in monthly simulation:", users_monthly)
print("Users in LP input:", users_lp)

common_users = set(monthly["user_id"]).intersection(
    set(lp["user_id"])
)

print("Common users:", len(common_users))

# ------------------------------------------------------------
# 5. Restrict to common users
# ------------------------------------------------------------

monthly = monthly[
    monthly["user_id"].isin(common_users)
].copy()

lp = lp[
    lp["user_id"].isin(common_users)
].copy()

# ------------------------------------------------------------
# 6. Calculate total financial wealth
# ------------------------------------------------------------

monthly["calculated_total_wealth"] = (
    monthly["savings_balance"]
    + monthly["portfolio_value"]
)

# ------------------------------------------------------------
# 7. Get final simulation row for each user
# ------------------------------------------------------------

monthly_sorted = monthly.sort_values(
    ["user_id", "period"]
)

final_rows = (
    monthly_sorted
    .groupby("user_id", as_index=False)
    .tail(1)
    .copy()
)

print(
    "\nFinal simulation rows:",
    len(final_rows)
)

# ------------------------------------------------------------
# 8. Merge final simulation state with LP outcome
# ------------------------------------------------------------

final_cols = [
    "user_id",
    "period",
    "savings_balance",
    "pre_savings_balance",
    "portfolio_value",
    "calculated_total_wealth",
    "initial_savings",
    "initial_investment",
    "monthly_surplus_dynamic",
    "unfunded_deficit"
]

final_cols = [
    c for c in final_cols
    if c in final_rows.columns
]

final_state = final_rows[final_cols].merge(
    lp[
        [
            "user_id",
            "goal_horizon_months",
            "target_amount",
            "initial_savings",
            "initial_investment",
            "goal_horizon_funding_actual",
            "goal_progress_at_deadline_actual",
            "goal_shortfall_actual",
            "goal_funding_ratio",
            "goal_achieved_on_time_actual",
            "goal_outcome"
        ]
    ],
    on="user_id",
    how="inner",
    suffixes=("_simulation", "_lp")
)

print(
    "Merged final-state rows:",
    len(final_state)
)

# ------------------------------------------------------------
# 9. Candidate funding interpretations
# ------------------------------------------------------------

# Candidate A:
# final savings balance
final_state["candidate_A_final_savings"] = (
    final_state["savings_balance"]
)

# Candidate B:
# final savings + final portfolio
final_state["candidate_B_total_wealth"] = (
    final_state["savings_balance"]
    + final_state["portfolio_value"]
)

# Candidate C:
# final total wealth minus initial total wealth
final_state["candidate_C_wealth_gain"] = (
    final_state["candidate_B_total_wealth"]
    - (
        final_state["initial_savings_lp"]
        + final_state["initial_investment_lp"]
    )
)

# Candidate D:
# final savings minus initial savings
final_state["candidate_D_savings_gain"] = (
    final_state["savings_balance"]
    - final_state["initial_savings_lp"]
)

# Candidate E:
# final total wealth
# minus initial investment only
final_state["candidate_E_wealth_minus_initial_investment"] = (
    final_state["candidate_B_total_wealth"]
    - final_state["initial_investment_lp"]
)

# Actual funding
actual = pd.to_numeric(
    final_state["goal_horizon_funding_actual"],
    errors="coerce"
)

# ------------------------------------------------------------
# 10. Compare candidates numerically
# ------------------------------------------------------------

candidate_cols = [
    "candidate_A_final_savings",
    "candidate_B_total_wealth",
    "candidate_C_wealth_gain",
    "candidate_D_savings_gain",
    "candidate_E_wealth_minus_initial_investment"
]

print("\n" + "=" * 80)
print("CANDIDATE FUNDING RELATIONSHIP TEST")
print("=" * 80)

results = []

for candidate in candidate_cols:

    candidate_values = pd.to_numeric(
        final_state[candidate],
        errors="coerce"
    )

    valid = (
        actual.notna()
        & candidate_values.notna()
    )

    difference = (
        actual[valid]
        - candidate_values[valid]
    ).abs()

    results.append({
        "candidate": candidate,
        "rows_tested": int(valid.sum()),
        "mean_abs_difference": float(
            difference.mean()
        ),
        "median_abs_difference": float(
            difference.median()
        ),
        "max_abs_difference": float(
            difference.max()
        ),
        "matching_within_1e-6": int(
            (difference <= 1e-6).sum()
        ),
        "correlation_with_actual": float(
            actual[valid].corr(
                candidate_values[valid]
            )
        )
    })

results_df = pd.DataFrame(results)

print(
    results_df
    .sort_values("mean_abs_difference")
    .to_string(index=False)
)

# ------------------------------------------------------------
# 11. Ratio analysis
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("ACTUAL FUNDING RELATIVE TO FINAL FINANCIAL STATE")
print("=" * 80)

final_state["actual_to_final_savings"] = np.where(
    final_state["savings_balance"] != 0,
    actual / final_state["savings_balance"],
    np.nan
)

final_state["actual_to_total_wealth"] = np.where(
    final_state["candidate_B_total_wealth"] != 0,
    actual / final_state["candidate_B_total_wealth"],
    np.nan
)

print(
    "Actual funding / final savings:"
)

print(
    final_state["actual_to_final_savings"]
    .replace([np.inf, -np.inf], np.nan)
    .describe()
    .to_string()
)

print(
    "\nActual funding / final total wealth:"
)

print(
    final_state["actual_to_total_wealth"]
    .replace([np.inf, -np.inf], np.nan)
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 12. Inspect representative users
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("REPRESENTATIVE USER FUNDING RECONSTRUCTION")
print("=" * 80)

show_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "initial_savings_lp",
    "initial_investment_lp",
    "savings_balance",
    "portfolio_value",
    "candidate_B_total_wealth",
    "candidate_C_wealth_gain",
    "candidate_D_savings_gain",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_funding_ratio",
    "goal_outcome"
]

print(
    final_state[show_cols]
    .head(15)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 13. Check whether final simulation date equals
#    the user's goal horizon
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("GOAL HORIZON vs SIMULATION END DATE")
print("=" * 80)

simulation_start = (
    monthly.groupby("user_id")["period"]
    .min()
)

simulation_end = (
    monthly.groupby("user_id")["period"]
    .max()
)

horizon_summary = lp[
    [
        "user_id",
        "goal_horizon_months"
    ]
].copy()

horizon_summary["simulation_start"] = (
    horizon_summary["user_id"]
    .map(simulation_start)
)

horizon_summary["simulation_end"] = (
    horizon_summary["user_id"]
    .map(simulation_end)
)

horizon_summary["simulation_months"] = (
    monthly.groupby("user_id")
    .size()
    .reindex(horizon_summary["user_id"])
    .values
)

print(
    horizon_summary[
        [
            "goal_horizon_months",
            "simulation_months"
        ]
    ]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 14. Important: calculate state at each user's
#     actual goal horizon
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("HORIZON-SPECIFIC STATE RECONSTRUCTION")
print("=" * 80)

# Create month number within each user
monthly_sorted["simulation_month_number"] = (
    monthly_sorted
    .groupby("user_id")
    .cumcount()
    + 1
)

horizon_lookup = lp[
    [
        "user_id",
        "goal_horizon_months",
        "target_amount",
        "goal_horizon_funding_actual"
    ]
].copy()

monthly_horizon = monthly_sorted.merge(
    horizon_lookup,
    on="user_id",
    how="inner"
)

horizon_rows = monthly_horizon[
    monthly_horizon["simulation_month_number"]
    == monthly_horizon["goal_horizon_months"]
].copy()

print(
    "Users with an exact simulation row at their goal horizon:",
    len(horizon_rows)
)

# Candidate horizon-specific wealth
horizon_rows["horizon_total_wealth"] = (
    horizon_rows["savings_balance"]
    + horizon_rows["portfolio_value"]
)

horizon_rows["horizon_savings_gain"] = (
    horizon_rows["savings_balance"]
    - horizon_rows["initial_savings"]
)

horizon_rows["horizon_wealth_gain"] = (
    horizon_rows["horizon_total_wealth"]
    - (
        horizon_rows["initial_savings"]
        + horizon_rows["initial_investment"]
    )
)

# ------------------------------------------------------------
# 15. Compare horizon-specific candidates
# ------------------------------------------------------------

horizon_actual = pd.to_numeric(
    horizon_rows["goal_horizon_funding_actual"],
    errors="coerce"
)

horizon_candidates = [
    "savings_balance",
    "horizon_total_wealth",
    "horizon_savings_gain",
    "horizon_wealth_gain"
]

horizon_results = []

for candidate in horizon_candidates:

    values = pd.to_numeric(
        horizon_rows[candidate],
        errors="coerce"
    )

    valid = (
        horizon_actual.notna()
        & values.notna()
    )

    difference = (
        horizon_actual[valid]
        - values[valid]
    ).abs()

    horizon_results.append({
        "candidate": candidate,
        "rows_tested": int(valid.sum()),
        "mean_abs_difference": float(
            difference.mean()
        ),
        "median_abs_difference": float(
            difference.median()
        ),
        "max_abs_difference": float(
            difference.max()
        ),
        "matching_within_1e-6": int(
            (difference <= 1e-6).sum()
        ),
        "correlation_with_actual": float(
            horizon_actual[valid].corr(
                values[valid]
            )
        )
    })

horizon_results_df = pd.DataFrame(
    horizon_results
)

print(
    horizon_results_df
    .sort_values("mean_abs_difference")
    .to_string(index=False)
)

# ------------------------------------------------------------
# 16. Save results
# ------------------------------------------------------------

results_path = os.path.join(
    OUT_DIR,
    "lp_5g_goal_funding_reconstruction_results.csv"
)

horizon_results_path = os.path.join(
    OUT_DIR,
    "lp_5g_horizon_funding_reconstruction_results.csv"
)

state_path = os.path.join(
    OUT_DIR,
    "lp_5g_user_funding_state_audit.csv"
)

results_df.to_csv(
    results_path,
    index=False
)

horizon_results_df.to_csv(
    horizon_results_path,
    index=False
)

final_state.to_csv(
    state_path,
    index=False
)

# ------------------------------------------------------------
# 17. Final status
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STEP 5G COMPLETE")
print("=" * 80)

print("\nSaved:")
print(results_path)
print(horizon_results_path)
print(state_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO MISSING VALUES WERE FILLED.")
print("NO FUNDING FORMULA WAS ASSUMED AS FINAL.")

print(
    "\nNext step: use the reconstruction results to establish "
    "the exact eligible goal-funding equation."
)

================================================================================
STEP 5G — RECONSTRUCT EXISTING GOAL-FUNDING CALCULATION
================================================================================

Monthly simulation shape: (1430000, 46)
LP input shape: (10000, 38)

Period range: 2015-02-01 00:00:00 to 2026-12-01 00:00:00

Users in monthly simulation: 10000
Users in LP input: 10000
Common users: 10000

Final simulation rows: 10000
Merged final-state rows: 10000

================================================================================
CANDIDATE FUNDING RELATIONSHIP TEST
================================================================================
                                  candidate  rows_tested  mean_abs_difference  median_abs_difference  max_abs_difference  matching_within_1e-6  correlation_with_actual
                   candidate_D_savings_gain        10000         2.607772e+06           1.806324e+06        7.206618e+07                     0                 0.804589
                    candidate_C_wealth_gain        10000         2.666455e+06           1.836112e+06        7.206618e+07                     0                 0.805785
                  candidate_A_final_savings        10000         2.758655e+06           1.918528e+06        7.679722e+07                  1232                 0.803232
candidate_E_wealth_minus_initial_investment        10000         2.817589e+06           1.942569e+06        7.679722e+07                   959                 0.804274
                   candidate_B_total_wealth        10000         2.874556e+06           1.966974e+06        7.679722e+07                   959                 0.804370

================================================================================
ACTUAL FUNDING RELATIVE TO FINAL FINANCIAL STATE
================================================================================
Actual funding / final savings:
count    8715.000000
mean        0.176868
std         0.158792
min         0.000000
25%         0.048072
50%         0.129667
75%         0.266337
max         1.289326

Actual funding / final total wealth:
count    9003.000000
mean        0.167019
std         0.154891
min         0.000000
25%         0.041452
50%         0.120677
75%         0.253370
max         1.289326

================================================================================
REPRESENTATIVE USER FUNDING RECONSTRUCTION
================================================================================
   user_id  goal_horizon_months  target_amount  initial_savings_lp  initial_investment_lp  savings_balance  portfolio_value  candidate_B_total_wealth  candidate_C_wealth_gain  candidate_D_savings_gain  goal_horizon_funding_actual  goal_shortfall_actual  goal_funding_ratio goal_outcome
USER_00001                   48  115357.183592       178733.652470           45777.548120     3.798640e+06     95298.759053              3.893939e+06             3.669428e+06              3.619906e+06                 5.811302e+05               0.000000            5.037660      success
USER_00002                   51   59340.387689        13659.350863               0.000000     0.000000e+00         0.000000              0.000000e+00            -1.365935e+04             -1.365935e+04                 0.000000e+00           59340.387689            0.000000      failure
USER_00003                   46   99893.237726        85318.549015               0.000000     7.021328e+05         0.000000              7.021328e+05             6.168143e+05              6.168143e+05                 4.093773e+04           58955.510123            0.409815      failure
USER_00004                   60   75476.307623       107702.527041           60534.274631     1.123526e+06     85296.198075              1.208823e+06             1.040586e+06              1.015824e+06                 4.566919e+04           29807.117161            0.605080      failure
USER_00005                  120  206040.342056       205810.045973          105774.934379     1.038436e+07    228458.998450              1.061282e+07             1.030123e+07              1.017855e+07                 7.318348e+06               0.000000           35.519005      success
USER_00006                   18  110291.964774       229003.169045          118987.882781     5.752488e+06    274237.112721              6.026725e+06             5.678734e+06              5.523485e+06                 3.502230e+05               0.000000            3.175418      success
USER_00007                   75  128020.414837       126015.560330           90329.680595     6.872314e+06    197157.391015              7.069472e+06             6.853127e+06              6.746299e+06                 2.348219e+06               0.000000           18.342532      success
USER_00008                   11  269916.171830        26481.524416               0.000000     1.519781e+06         0.000000              1.519781e+06             1.493299e+06              1.493299e+06                 0.000000e+00          269916.171830            0.000000      failure
USER_00009                   55  182600.732773       165575.931991               0.000000     6.985983e+06         0.000000              6.985983e+06             6.820407e+06              6.820407e+06                 1.616717e+06               0.000000            8.853834      success
USER_00010                   24   96702.526658        76879.539877           15171.499059     1.338531e+06     26694.224964              1.365225e+06             1.273174e+06              1.261651e+06                 5.423986e+04           42462.667060            0.560894      failure
USER_00011                   42   39905.117099        54235.719087           40453.563484     1.869969e+06     89281.509258              1.959251e+06             1.864562e+06              1.815734e+06                 1.746970e+05               0.000000            4.377810      success
USER_00012                   18  153722.614222        61045.416664            8515.989852     0.000000e+00     10162.605188              1.016261e+04            -5.939880e+04             -6.104542e+04                 0.000000e+00          153722.614222            0.000000      failure
USER_00013                  102   75699.850293        61114.611407           16162.918447     0.000000e+00     19489.151566              1.948915e+04            -5.778838e+04             -6.111461e+04                 0.000000e+00           75699.850293            0.000000      failure
USER_00014                   88   56999.623650        38402.341214           14401.269590     1.175594e+06     19724.814625              1.195318e+06             1.142515e+06              1.137191e+06                 1.429149e+05               0.000000            2.507296      success
USER_00015                  105  294810.384238       445818.862673          198355.872839     1.342800e+07    373085.616913              1.380109e+07             1.315692e+07              1.298219e+07                 7.737681e+06               0.000000           26.246296      success

================================================================================
GOAL HORIZON vs SIMULATION END DATE
================================================================================
       goal_horizon_months  simulation_months
count         10000.000000            10000.0
mean             62.697000              143.0
std              33.431233                0.0
min               6.000000              143.0
25%              33.000000              143.0
50%              63.000000              143.0
75%              92.000000              143.0
max             120.000000              143.0

================================================================================
HORIZON-SPECIFIC STATE RECONSTRUCTION
================================================================================
Users with an exact simulation row at their goal horizon: 10000
           candidate  rows_tested  mean_abs_difference  median_abs_difference  max_abs_difference  matching_within_1e-6  correlation_with_actual
horizon_savings_gain        10000        253734.008700          176417.433614        3.146905e+06                     1                 0.993470
 horizon_wealth_gain        10000        275432.136847          189865.262148        4.675817e+06                     0                 0.993580
     savings_balance        10000        399932.265177          343780.773049        4.946443e+06                  1315                 0.992602
horizon_total_wealth        10000        478534.104772          386204.399303        1.350250e+07                  1016                 0.990730

================================================================================
STEP 5G COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5g_goal_funding_reconstruction_results.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5g_horizon_funding_reconstruction_results.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5g_user_funding_state_audit.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO MISSING VALUES WERE FILLED.
NO FUNDING FORMULA WAS ASSUMED AS FINAL.

Next step: use the reconstruction results to establish the exact eligible goal-funding equation.

In [97]:
# ============================================================
# GOALPILOT AI — STEP 5H
# EXISTING GOAL FUNDING AGGREGATION AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5H — EXISTING GOAL FUNDING AGGREGATION AUDIT")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

MONTHLY_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

OUTCOME_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_goal_outcome_dataset.csv"
)

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. Load
# ------------------------------------------------------------

monthly = pd.read_csv(MONTHLY_FILE)
outcome = pd.read_csv(OUTCOME_FILE)
lp = pd.read_csv(LP_FILE)

monthly["period"] = pd.to_datetime(
    monthly["period"],
    errors="coerce"
)

monthly = monthly.sort_values(
    ["user_id", "period"]
)

monthly["simulation_month"] = (
    monthly.groupby("user_id").cumcount() + 1
)

print("\nMonthly:", monthly.shape)
print("Outcome:", outcome.shape)
print("LP:", lp.shape)

# ------------------------------------------------------------
# 2. Inspect final outcome dataset
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("1. FINAL GOAL OUTCOME DATASET COLUMNS")
print("=" * 80)

for i, col in enumerate(outcome.columns, 1):
    print(f"{i:03d}. {col}")

# ------------------------------------------------------------
# 3. Relevant outcome columns
# ------------------------------------------------------------

keywords = [
    "goal",
    "fund",
    "target",
    "saving",
    "wealth",
    "portfolio",
    "surplus",
    "horizon",
    "progress"
]

relevant_outcome = [
    c for c in outcome.columns
    if any(k in str(c).lower() for k in keywords)
]

print("\n" + "=" * 80)
print("2. RELEVANT OUTCOME FIELDS")
print("=" * 80)

for c in relevant_outcome:
    print("✓", c)

# ------------------------------------------------------------
# 4. Check exact final outcome vs LP outcome
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("3. FINAL OUTCOME / LP CONSISTENCY")
print("=" * 80)

common = list(
    set(outcome.columns).intersection(
        set(lp.columns)
    )
)

print("Common columns:", len(common))

important_common = [
    c for c in [
        "user_id",
        "target_amount",
        "goal_horizon_funding_actual",
        "goal_progress_at_deadline_actual",
        "goal_shortfall_actual",
        "goal_funding_ratio",
        "goal_outcome"
    ]
    if c in common
]

print("\nImportant common fields:")

for c in important_common:
    print("✓", c)

if "goal_horizon_funding_actual" in outcome.columns:

    merged_outcome = outcome[
        ["user_id", "goal_horizon_funding_actual"]
    ].merge(
        lp[
            ["user_id", "goal_horizon_funding_actual"]
        ],
        on="user_id",
        suffixes=("_outcome", "_lp")
    )

    difference = (
        merged_outcome["goal_horizon_funding_actual_outcome"]
        - merged_outcome["goal_horizon_funding_actual_lp"]
    ).abs()

    print(
        "\nFunding differences between outcome and LP:"
    )

    print("Mean:", difference.mean())
    print("Max:", difference.max())
    print(
        "Matching:",
        (difference <= 1e-6).sum(),
        "/",
        len(difference)
    )

# ------------------------------------------------------------
# 5. Add target/horizon to monthly data
# ------------------------------------------------------------

user_info = lp[
    [
        "user_id",
        "goal_horizon_months",
        "target_amount",
        "goal_horizon_funding_actual"
    ]
].drop_duplicates("user_id")

m = monthly.merge(
    user_info,
    on="user_id",
    how="inner"
)

# Only months up to each user's horizon
mh = m[
    m["simulation_month"]
    <= m["goal_horizon_months"]
].copy()

print("\nRows within user-specific horizons:", len(mh))

# ------------------------------------------------------------
# 6. Aggregate candidate quantities to each horizon
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("4. HORIZON AGGREGATION CANDIDATES")
print("=" * 80)

# Last state at horizon
horizon = (
    mh.sort_values(
        ["user_id", "simulation_month"]
    )
    .groupby("user_id", as_index=False)
    .tail(1)
    .copy()
)

# Candidate cumulative quantities
agg = mh.groupby("user_id").agg(
    sum_monthly_surplus=(
        "monthly_surplus_dynamic",
        "sum"
    ),
    sum_positive_cash_flow=(
        "positive_cash_flow",
        "sum"
    ),
    sum_unfunded_deficit=(
        "unfunded_deficit",
        "sum"
    ),
    sum_monthly_income_dynamic=(
        "monthly_income_dynamic",
        "sum"
    ),
    sum_monthly_expenditure_dynamic=(
        "monthly_expenditure_dynamic",
        "sum"
    )
).reset_index()

# Horizon state
state_cols = [
    "user_id",
    "savings_balance",
    "pre_savings_balance",
    "portfolio_value",
    "cumulative_cash_flow",
    "unfunded_deficit"
]

state_cols = [
    c for c in state_cols
    if c in horizon.columns
]

agg = agg.merge(
    horizon[state_cols],
    on="user_id",
    how="left"
)

# Initial states
initial = lp[
    [
        "user_id",
        "initial_savings",
        "initial_investment",
        "goal_horizon_funding_actual"
    ]
].drop_duplicates("user_id")

agg = agg.merge(
    initial,
    on="user_id",
    how="left"
)

# ------------------------------------------------------------
# 7. Construct ONLY directly observable candidates
# ------------------------------------------------------------

agg["candidate_1_positive_cash_flow"] = (
    agg["sum_positive_cash_flow"]
)

agg["candidate_2_cumulative_cash_flow"] = (
    agg["cumulative_cash_flow"]
)

agg["candidate_3_final_savings"] = (
    agg["savings_balance"]
)

agg["candidate_4_final_savings_minus_initial"] = (
    agg["savings_balance"]
    - agg["initial_savings"]
)

agg["candidate_5_final_savings_plus_initial_savings"] = (
    agg["savings_balance"]
    + agg["initial_savings"]
)

agg["candidate_6_savings_plus_portfolio"] = (
    agg["savings_balance"]
    + agg["portfolio_value"]
)

agg["candidate_7_total_wealth_change"] = (
    agg["savings_balance"]
    + agg["portfolio_value"]
    - agg["initial_savings"]
    - agg["initial_investment"]
)

agg["candidate_8_positive_cash_flow_minus_deficit"] = (
    agg["sum_positive_cash_flow"]
    - agg["sum_unfunded_deficit"]
)

actual = pd.to_numeric(
    agg["goal_horizon_funding_actual"],
    errors="coerce"
)

# ------------------------------------------------------------
# 8. Compare
# ------------------------------------------------------------

candidate_columns = [
    "candidate_1_positive_cash_flow",
    "candidate_2_cumulative_cash_flow",
    "candidate_3_final_savings",
    "candidate_4_final_savings_minus_initial",
    "candidate_5_final_savings_plus_initial_savings",
    "candidate_6_savings_plus_portfolio",
    "candidate_7_total_wealth_change",
    "candidate_8_positive_cash_flow_minus_deficit"
]

comparison = []

for col in candidate_columns:

    values = pd.to_numeric(
        agg[col],
        errors="coerce"
    )

    valid = (
        actual.notna()
        & values.notna()
    )

    diff = (
        actual[valid] - values[valid]
    ).abs()

    comparison.append({
        "candidate": col,
        "rows": int(valid.sum()),
        "mean_abs_difference": diff.mean(),
        "median_abs_difference": diff.median(),
        "max_abs_difference": diff.max(),
        "match_1e-6": int((diff <= 1e-6).sum()),
        "correlation": actual[valid].corr(values[valid])
    })

comparison_df = pd.DataFrame(comparison)

print(
    comparison_df
    .sort_values("mean_abs_difference")
    .to_string(index=False)
)

# ------------------------------------------------------------
# 9. Inspect strongest candidates
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("5. SAMPLE AGGREGATION VALUES")
print("=" * 80)

show = [
    "user_id",
    "initial_savings",
    "initial_investment",
    "goal_horizon_funding_actual",
    "sum_monthly_surplus",
    "sum_positive_cash_flow",
    "cumulative_cash_flow",
    "savings_balance",
    "pre_savings_balance",
    "portfolio_value",
    "sum_unfunded_deficit",
    "candidate_1_positive_cash_flow",
    "candidate_2_cumulative_cash_flow",
    "candidate_8_positive_cash_flow_minus_deficit"
]

show = [
    c for c in show
    if c in agg.columns
]

print(
    agg[show]
    .head(15)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 10. Save
# ------------------------------------------------------------

comparison_path = os.path.join(
    OUT_DIR,
    "lp_5h_goal_funding_aggregation_comparison.csv"
)

audit_path = os.path.join(
    OUT_DIR,
    "lp_5h_goal_funding_aggregation_audit.csv"
)

comparison_df.to_csv(
    comparison_path,
    index=False
)

agg.to_csv(
    audit_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5H COMPLETE")
print("=" * 80)

print("\nSaved:")
print(comparison_path)
print(audit_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO FUNDING FORMULA WAS ASSUMED.")

================================================================================
STEP 5H — EXISTING GOAL FUNDING AGGREGATION AUDIT
================================================================================

Monthly: (1430000, 47)
Outcome: (10000, 18)
LP: (10000, 38)

================================================================================
1. FINAL GOAL OUTCOME DATASET COLUMNS
================================================================================
001. user_id
002. financial_situation
003. risk_profile
004. risk_score
005. goal_horizon_months
006. goal_horizon_type
007. target_amount
008. goal_horizon_funding_actual
009. goal_progress_at_deadline_actual
010. goal_progress_at_deadline_actual_capped
011. goal_shortfall_actual
012. goal_achieved_on_time_actual
013. goal_shortfall_severity
014. goal_outcome
015. goal_risk_level
016. goal_funding_ratio
017. goal_funding_ratio_capped
018. goal_shortfall_ratio

================================================================================
2. RELEVANT OUTCOME FIELDS
================================================================================
✓ goal_horizon_months
✓ goal_horizon_type
✓ target_amount
✓ goal_horizon_funding_actual
✓ goal_progress_at_deadline_actual
✓ goal_progress_at_deadline_actual_capped
✓ goal_shortfall_actual
✓ goal_achieved_on_time_actual
✓ goal_shortfall_severity
✓ goal_outcome
✓ goal_risk_level
✓ goal_funding_ratio
✓ goal_funding_ratio_capped
✓ goal_shortfall_ratio

================================================================================
3. FINAL OUTCOME / LP CONSISTENCY
================================================================================
Common columns: 17

Important common fields:
✓ user_id
✓ target_amount
✓ goal_horizon_funding_actual
✓ goal_progress_at_deadline_actual
✓ goal_shortfall_actual
✓ goal_funding_ratio
✓ goal_outcome

Funding differences between outcome and LP:
Mean: 0.0
Max: 0.0
Matching: 10000 / 10000

Rows within user-specific horizons: 626970

================================================================================
4. HORIZON AGGREGATION CANDIDATES
================================================================================
                                     candidate  rows  mean_abs_difference  median_abs_difference  max_abs_difference  match_1e-6  correlation
                candidate_1_positive_cash_flow 10000         2.449329e+05          173249.434800        3.149198e+06        1466     0.994062
       candidate_4_final_savings_minus_initial 10000         2.537340e+05          176417.433614        3.146905e+06           1     0.993470
               candidate_7_total_wealth_change 10000         2.754321e+05          189865.262148        4.675817e+06           0     0.993580
              candidate_2_cumulative_cash_flow 10000         3.169016e+05          233443.120950        2.152326e+07           1     0.977706
                     candidate_3_final_savings 10000         3.999323e+05          343780.773049        4.946443e+06        1315     0.992602
            candidate_6_savings_plus_portfolio 10000         4.785341e+05          386204.399303        1.350250e+07        1016     0.990730
candidate_5_final_savings_plus_initial_savings 10000         5.666453e+05          470714.676452        9.892886e+06           0     0.987756
  candidate_8_positive_cash_flow_minus_deficit 10000         2.851461e+06          279198.193677        1.228115e+09         151     0.178021

================================================================================
5. SAMPLE AGGREGATION VALUES
================================================================================
   user_id  initial_savings  initial_investment  goal_horizon_funding_actual  sum_monthly_surplus  sum_positive_cash_flow  cumulative_cash_flow  savings_balance  pre_savings_balance  portfolio_value  sum_unfunded_deficit  candidate_1_positive_cash_flow  candidate_2_cumulative_cash_flow  candidate_8_positive_cash_flow_minus_deficit
USER_00001    178733.652470        45777.548120                 5.811302e+05         8.329228e+05            8.329228e+05          8.329228e+05     1.011656e+06         1.011656e+06     53409.494392          0.000000e+00                    8.329228e+05                      8.329228e+05                                  8.329228e+05
USER_00002     13659.350863            0.000000                 0.000000e+00        -6.695868e+05            0.000000e+00         -6.695868e+05     0.000000e+00        -6.559275e+05         0.000000          1.660787e+07                    0.000000e+00                     -6.695868e+05                                 -1.660787e+07
USER_00003     85318.549015            0.000000                 4.093773e+04         1.349744e+05            1.349744e+05          1.349744e+05     2.202929e+05         2.202929e+05         0.000000          0.000000e+00                    1.349744e+05                      1.349744e+05                                  1.349744e+05
USER_00004    107702.527041        60534.274631                 4.566919e+04         1.870155e+05            1.870155e+05          1.870155e+05     2.947180e+05         2.947180e+05     67238.611103          0.000000e+00                    1.870155e+05                      1.870155e+05                                  1.870155e+05
USER_00005    205810.045973       105774.934379                 7.318348e+06         7.771422e+06            7.771422e+06          7.771422e+06     7.977232e+06         7.977232e+06    226825.336740          0.000000e+00                    7.771422e+06                      7.771422e+06                                  7.771422e+06
USER_00006    229003.169045       118987.882781                 3.502230e+05         4.254410e+05            4.254410e+05          4.254410e+05     6.544442e+05         6.544442e+05    117365.799299          0.000000e+00                    4.254410e+05                      4.254410e+05                                  4.254410e+05
USER_00007    126015.560330        90329.680595                 2.348219e+06         2.694147e+06            2.694147e+06          2.694147e+06     2.820163e+06         2.820163e+06    135602.561692          0.000000e+00                    2.694147e+06                      2.694147e+06                                  2.694147e+06
USER_00008     26481.524416            0.000000                 0.000000e+00        -4.135833e+04            0.000000e+00         -4.135833e+04     0.000000e+00        -1.487681e+04         0.000000          4.272212e+04                    0.000000e+00                     -4.135833e+04                                 -4.272212e+04
USER_00009    165575.931991            0.000000                 1.616717e+06         1.847887e+06            1.847887e+06          1.847887e+06     2.013463e+06         2.013463e+06         0.000000          0.000000e+00                    1.847887e+06                      1.847887e+06                                  1.847887e+06
USER_00010     76879.539877        15171.499059                 5.423986e+04         1.324862e+05            1.324862e+05          1.324862e+05     2.093658e+05         2.093658e+05     15012.452824          0.000000e+00                    1.324862e+05                      1.324862e+05                                  1.324862e+05
USER_00011     54235.719087        40453.563484                 1.746970e+05         3.572536e+05            3.572536e+05          3.572536e+05     4.114893e+05         4.114893e+05     49516.935325          0.000000e+00                    3.572536e+05                      3.572536e+05                                  3.572536e+05
USER_00012     61045.416664         8515.989852                 0.000000e+00        -2.618731e+05            0.000000e+00         -2.618731e+05     0.000000e+00        -2.008277e+05      8508.052115          1.488994e+06                    0.000000e+00                     -2.618731e+05                                 -1.488994e+06
USER_00013     61114.611407        16162.918447                 0.000000e+00        -2.627830e+05            0.000000e+00         -2.627830e+05     0.000000e+00        -2.016684e+05     18835.055587          1.115131e+07                    0.000000e+00                     -2.627830e+05                                 -1.115131e+07
USER_00014     38402.341214        14401.269590                 1.429149e+05         4.743276e+05            4.743276e+05          4.743276e+05     5.127299e+05         5.127299e+05     17673.262228          0.000000e+00                    4.743276e+05                      4.743276e+05                                  4.743276e+05
USER_00015    445818.862673       198355.872839                 7.737681e+06         8.056727e+06            8.056727e+06          8.056727e+06     8.502546e+06         8.502546e+06    325791.256989          0.000000e+00                    8.056727e+06                      8.056727e+06                                  8.056727e+06

================================================================================
STEP 5H COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5h_goal_funding_aggregation_comparison.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5h_goal_funding_aggregation_audit.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO FUNDING FORMULA WAS ASSUMED.

In [98]:
# ============================================================
# GOALPILOT AI — STEP 5I
# REVERSE-ENGINEER GOAL FUNDING FORMULA
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5I — REVERSE-ENGINEER GOAL FUNDING FORMULA")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

MONTHLY_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------------

monthly = pd.read_csv(MONTHLY_FILE)
lp = pd.read_csv(LP_FILE)

monthly["period"] = pd.to_datetime(
    monthly["period"],
    errors="coerce"
)

monthly = monthly.sort_values(
    ["user_id", "period"]
)

monthly["simulation_month"] = (
    monthly.groupby("user_id").cumcount() + 1
)

print("\nMonthly simulation:", monthly.shape)
print("LP input:", lp.shape)

# ------------------------------------------------------------
# 2. USER-LEVEL PARAMETERS
# ------------------------------------------------------------

user_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "investment_capacity_ratio",
    "initial_savings",
    "initial_investment",
    "risk_score",
    "risk_profile"
]

user_cols = [
    c for c in user_cols
    if c in lp.columns
]

users = lp[user_cols].drop_duplicates("user_id")

m = monthly.merge(
    users,
    on="user_id",
    how="inner"
)

# Only months inside each user's goal horizon
mh = m[
    m["simulation_month"] <= m["goal_horizon_months"]
].copy()

print(
    "\nRows inside user-specific horizons:",
    len(mh)
)

# ------------------------------------------------------------
# 3. CREATE MONTHLY CANDIDATE FUNDING COMPONENTS
# ------------------------------------------------------------

# Positive cash flow is already present in simulation.
mh["positive_cash_flow"] = pd.to_numeric(
    mh["positive_cash_flow"],
    errors="coerce"
).fillna(0)

mh["monthly_surplus_dynamic"] = pd.to_numeric(
    mh["monthly_surplus_dynamic"],
    errors="coerce"
).fillna(0)

mh["goal_specific_monthly_capacity"] = pd.to_numeric(
    mh["goal_specific_monthly_capacity"],
    errors="coerce"
).fillna(0)

mh["goal_allocation_factor"] = pd.to_numeric(
    mh["goal_allocation_factor"],
    errors="coerce"
).fillna(0)

# Candidate A
mh["candidate_A"] = (
    mh["positive_cash_flow"]
    * mh["goal_allocation_factor"]
)

# Candidate B
mh["candidate_B"] = (
    mh["monthly_surplus_dynamic"].clip(lower=0)
    * mh["goal_allocation_factor"]
)

# Candidate C
mh["candidate_C"] = (
    mh["goal_specific_monthly_capacity"]
    * mh["goal_allocation_factor"]
)

# Candidate D
mh["candidate_D"] = (
    np.minimum(
        mh["positive_cash_flow"],
        mh["goal_specific_monthly_capacity"]
    )
    * mh["goal_allocation_factor"]
)

# Candidate E
mh["candidate_E"] = np.minimum(
    mh["positive_cash_flow"],
    mh["goal_specific_monthly_capacity"]
)

# Candidate F
mh["candidate_F"] = np.minimum(
    mh["monthly_surplus_dynamic"].clip(lower=0),
    mh["goal_specific_monthly_capacity"]
)

# ------------------------------------------------------------
# 4. AGGREGATE TO USER HORIZON
# ------------------------------------------------------------

candidate_sums = (
    mh.groupby("user_id")
      .agg(
          candidate_A=("candidate_A", "sum"),
          candidate_B=("candidate_B", "sum"),
          candidate_C=("candidate_C", "sum"),
          candidate_D=("candidate_D", "sum"),
          candidate_E=("candidate_E", "sum"),
          candidate_F=("candidate_F", "sum"),
          positive_cash_flow_sum=("positive_cash_flow", "sum"),
          positive_surplus_sum=(
              "monthly_surplus_dynamic",
              lambda x: x.clip(lower=0).sum()
          )
      )
      .reset_index()
)

candidate_sums = candidate_sums.merge(
    users,
    on="user_id",
    how="left"
)

actual = pd.to_numeric(
    candidate_sums["goal_horizon_funding_actual"],
    errors="coerce"
)

# ------------------------------------------------------------
# 5. COMPARE CANDIDATES
# ------------------------------------------------------------

candidate_cols = [
    "candidate_A",
    "candidate_B",
    "candidate_C",
    "candidate_D",
    "candidate_E",
    "candidate_F",
    "positive_cash_flow_sum",
    "positive_surplus_sum"
]

results = []

for col in candidate_cols:

    values = pd.to_numeric(
        candidate_sums[col],
        errors="coerce"
    )

    valid = actual.notna() & values.notna()

    diff = (
        actual[valid] - values[valid]
    ).abs()

    results.append({
        "candidate": col,
        "rows": int(valid.sum()),
        "mean_abs_difference": diff.mean(),
        "median_abs_difference": diff.median(),
        "max_abs_difference": diff.max(),
        "match_1e-6": int(
            (diff <= 1e-6).sum()
        ),
        "match_1e-3": int(
            (diff <= 1e-3).sum()
        ),
        "match_1": int(
            (diff <= 1).sum()
        ),
        "correlation": actual[valid].corr(
            values[valid]
        )
    })

results_df = pd.DataFrame(results)

print("\n" + "=" * 80)
print("1. FUNDING FORMULA CANDIDATE COMPARISON")
print("=" * 80)

print(
    results_df
    .sort_values("mean_abs_difference")
    .to_string(index=False)
)

# ------------------------------------------------------------
# 6. RATIO ANALYSIS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("2. ACTUAL FUNDING RATIOS")
print("=" * 80)

candidate_sums["actual_to_positive_cash_flow"] = (
    actual /
    candidate_sums["positive_cash_flow_sum"].replace(
        0, np.nan
    )
)

candidate_sums["actual_to_candidate_A"] = (
    actual /
    candidate_sums["candidate_A"].replace(
        0, np.nan
    )
)

candidate_sums["actual_to_candidate_C"] = (
    actual /
    candidate_sums["candidate_C"].replace(
        0, np.nan
    )
)

ratio_cols = [
    "actual_to_positive_cash_flow",
    "actual_to_candidate_A",
    "actual_to_candidate_C"
]

print(
    candidate_sums[ratio_cols]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 7. CHECK RELATIONSHIP WITH GOAL ALLOCATION FACTOR
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("3. GOAL ALLOCATION FACTOR")
print("=" * 80)

print(
    candidate_sums[
        [
            "goal_allocation_factor",
            "actual_to_positive_cash_flow"
        ]
    ]
    .corr()
    .to_string()
)

# ------------------------------------------------------------
# 8. REPRESENTATIVE USERS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("4. REPRESENTATIVE USERS")
print("=" * 80)

show_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "positive_cash_flow_sum",
    "candidate_A",
    "candidate_B",
    "candidate_C",
    "candidate_D",
    "candidate_E",
    "candidate_F"
]

show_cols = [
    c for c in show_cols
    if c in candidate_sums.columns
]

print(
    candidate_sums[
        show_cols
    ].head(20).to_string(index=False)
)

# ------------------------------------------------------------
# 9. FIND CLOSEST CANDIDATE FOR EACH USER
# ------------------------------------------------------------

for col in candidate_cols:

    candidate_sums[f"absdiff_{col}"] = (
        actual -
        pd.to_numeric(
            candidate_sums[col],
            errors="coerce"
        )
    ).abs()

diff_cols = [
    f"absdiff_{c}"
    for c in candidate_cols
]

candidate_sums["best_candidate"] = (
    candidate_sums[diff_cols]
    .idxmin(axis=1)
    .str.replace("absdiff_", "", regex=False)
)

print("\n" + "=" * 80)
print("5. BEST CANDIDATE FREQUENCY")
print("=" * 80)

print(
    candidate_sums["best_candidate"]
    .value_counts()
    .to_string()
)

# ------------------------------------------------------------
# 10. SAVE RESULTS
# ------------------------------------------------------------

comparison_path = os.path.join(
    OUT_DIR,
    "lp_5i_goal_funding_formula_candidates.csv"
)

audit_path = os.path.join(
    OUT_DIR,
    "lp_5i_goal_funding_formula_audit.csv"
)

results_df.to_csv(
    comparison_path,
    index=False
)

candidate_sums.to_csv(
    audit_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5I COMPLETE")
print("=" * 80)

print("\nSaved:")
print(comparison_path)
print(audit_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO FUNDING FORMULA WAS ASSUMED.")

================================================================================
STEP 5I — REVERSE-ENGINEER GOAL FUNDING FORMULA
================================================================================

Monthly simulation: (1430000, 47)
LP input: (10000, 38)

Rows inside user-specific horizons: 626970

================================================================================
1. FUNDING FORMULA CANDIDATE COMPARISON
================================================================================
             candidate  rows  mean_abs_difference  median_abs_difference  max_abs_difference  match_1e-6  match_1e-3  match_1  correlation
           candidate_A 10000         2.700399e-11               0.000000        3.725290e-09       10000       10000    10000     1.000000
           candidate_B 10000         2.700399e-11               0.000000        3.725290e-09       10000       10000    10000     1.000000
positive_cash_flow_sum 10000         2.449329e+05          173249.434800        3.149198e+06        1466        1466     1466     0.994062
  positive_surplus_sum 10000         2.449329e+05          173249.434800        3.149198e+06        1466        1466     1466     0.994062
           candidate_F 10000         2.818622e+05           48745.356176        2.330678e+07        1465        1465     1467     0.991827
           candidate_E 10000         2.818622e+05           48745.356176        2.330678e+07        1465        1465     1467     0.991827
           candidate_D 10000         3.805791e+05          116902.125429        2.333006e+07        1465        1465     1467     0.988892
           candidate_C 10000         3.805791e+05          116902.125429        2.333006e+07        1465        1465     1467     0.988892

================================================================================
2. ACTUAL FUNDING RATIOS
================================================================================
       actual_to_positive_cash_flow  actual_to_candidate_A  actual_to_candidate_C
count                   8535.000000           8.535000e+03            7870.000000
mean                       0.567593           1.000000e+00               4.852622
std                        0.256049           8.524346e-17              51.122488
min                        0.106550           1.000000e+00               1.042029
25%                        0.359950           1.000000e+00               1.606132
50%                        0.573300           1.000000e+00               2.168899
75%                        0.786650           1.000000e+00               3.370108
max                        1.000000           1.000000e+00            3880.581152

================================================================================
3. GOAL ALLOCATION FACTOR
================================================================================
                              goal_allocation_factor  actual_to_positive_cash_flow
goal_allocation_factor                           1.0                           1.0
actual_to_positive_cash_flow                     1.0                           1.0

================================================================================
4. REPRESENTATIVE USERS
================================================================================
   user_id  goal_horizon_months  target_amount  goal_horizon_funding_actual  goal_specific_monthly_capacity  goal_allocation_factor  positive_cash_flow_sum  candidate_A  candidate_B  candidate_C  candidate_D  candidate_E  candidate_F
USER_00001                   48  115357.183592                 5.811302e+05                    10103.627663                 0.69770            8.329228e+05 5.811302e+05 5.811302e+05 3.383664e+05 3.383664e+05 4.849741e+05 4.849741e+05
USER_00002                   51   59340.387689                 0.000000e+00                        0.000000                 0.10655            0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
USER_00003                   46   99893.237726                 4.093773e+04                      748.407439                 0.30330            1.349744e+05 4.093773e+04 4.093773e+04 1.044163e+04 1.044163e+04 3.442674e+04 3.442674e+04
USER_00004                   60   75476.307623                 4.566919e+04                      255.370474                 0.24420            1.870155e+05 4.566919e+04 4.566919e+04 3.741688e+03 3.741688e+03 1.532223e+04 1.532223e+04
USER_00005                  120  206040.342056                 7.318348e+06                    38345.091895                 0.94170            7.771422e+06 7.318348e+06 7.318348e+06 4.333149e+06 4.333149e+06 4.601411e+06 4.601411e+06
USER_00006                   18  110291.964774                 3.502230e+05                    18189.879501                 0.82320            4.254410e+05 3.502230e+05 3.502230e+05 2.695304e+05 2.695304e+05 3.274178e+05 3.274178e+05
USER_00007                   75  128020.414837                 2.348219e+06                    23523.073803                 0.87160            2.694147e+06 2.348219e+06 2.348219e+06 1.537703e+06 1.537703e+06 1.764231e+06 1.764231e+06
USER_00008                   11  269916.171830                 0.000000e+00                        0.000000                 0.10655            0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
USER_00009                   55  182600.732773                 1.616717e+06                    23871.515994                 0.87490            1.847887e+06 1.616717e+06 1.616717e+06 1.148685e+06 1.148685e+06 1.312933e+06 1.312933e+06
USER_00010                   24   96702.526658                 5.423986e+04                     2066.324108                 0.40940            1.324862e+05 5.423986e+04 5.423986e+04 2.030287e+04 2.030287e+04 4.959178e+04 4.959178e+04
USER_00011                   42   39905.117099                 1.746970e+05                     3551.994435                 0.48900            3.572536e+05 1.746970e+05 1.746970e+05 7.295086e+04 7.295086e+04 1.491838e+05 1.491838e+05
USER_00012                   18  153722.614222                 0.000000e+00                        0.000000                 0.10655            0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
USER_00013                  102   75699.850293                 0.000000e+00                        0.000000                 0.10655            0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
USER_00014                   88   56999.623650                 1.429149e+05                      734.186924                 0.30130            4.743276e+05 1.429149e+05 1.429149e+05 1.946653e+04 1.946653e+04 6.460845e+04 6.460845e+04
USER_00015                  105  294810.384238                 7.737681e+06                    46788.900475                 0.96040            8.056727e+06 7.737681e+06 7.737681e+06 4.718286e+06 4.718286e+06 4.912835e+06 4.912835e+06
USER_00016                   32  164062.774110                 8.506991e+05                    23588.703362                 0.87260            9.749015e+05 8.506991e+05 8.506991e+05 6.586721e+05 6.586721e+05 7.548385e+05 7.548385e+05
USER_00017                   12   67605.333513                 3.423747e+04                     2724.879592                 0.44710            7.657675e+04 3.423747e+04 3.423747e+04 1.461952e+04 1.461952e+04 3.269856e+04 3.269856e+04
USER_00018                   65  230098.662301                 1.637618e+06                    19675.329198                 0.83980            1.950010e+06 1.637618e+06 1.637618e+06 1.074017e+06 1.074017e+06 1.278896e+06 1.278896e+06
USER_00019                   39   78326.115793                 3.179076e+05                     7041.812019                 0.61950            5.131680e+05 3.179076e+05 3.179076e+05 1.701337e+05 1.701337e+05 2.746307e+05 2.746307e+05
USER_00020                   76   89316.160080                 4.044024e+05                     3346.279062                 0.47910            8.440876e+05 4.044024e+05 4.044024e+05 1.218434e+05 1.218434e+05 2.543172e+05 2.543172e+05

================================================================================
5. BEST CANDIDATE FREQUENCY
================================================================================
best_candidate
candidate_A    10000

================================================================================
STEP 5I COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5i_goal_funding_formula_candidates.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5i_goal_funding_formula_audit.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO FUNDING FORMULA WAS ASSUMED.

In [99]:
# ============================================================
# GOALPILOT AI — STEP 5J
# LP MATHEMATICAL FORMULATION AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5J — LP MATHEMATICAL FORMULATION AUDIT")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD VERIFIED LP INPUT
# ------------------------------------------------------------

df = pd.read_csv(LP_FILE)

print("\nLP input shape:", df.shape)
print("Unique users:", df["user_id"].nunique())
print(
    "Duplicate user IDs:",
    df["user_id"].duplicated().sum()
)

# ------------------------------------------------------------
# 2. DEFINE VERIFIED PARAMETERS
# ------------------------------------------------------------

parameter_mapping = [
    {
        "field": "monthly_income",
        "LP_role": "Parameter",
        "meaning": "Monthly income available to the financial plan",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "monthly_expenditure",
        "LP_role": "Parameter",
        "meaning": "Monthly expenditure",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "monthly_emi",
        "LP_role": "Parameter",
        "meaning": "Monthly EMI obligation",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "initial_savings",
        "LP_role": "Initial state",
        "meaning": "Savings available at start",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "initial_investment",
        "LP_role": "Initial state",
        "meaning": "Existing investment value at start",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "investment_capacity_ratio",
        "LP_role": "Upper-bound parameter",
        "meaning": "User-specific investment capacity ratio",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "risk_score",
        "LP_role": "Parameter",
        "meaning": "User risk score",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "risk_profile",
        "LP_role": "Parameter",
        "meaning": "Aggressive / moderate / conservative profile",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "goal_horizon_months",
        "LP_role": "Parameter",
        "meaning": "Number of months available for goal",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "target_amount",
        "LP_role": "Parameter",
        "meaning": "Required goal target",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "goal_specific_monthly_capacity",
        "LP_role": "Upper-bound parameter",
        "meaning": "Existing monthly goal capacity",
        "verified": "YES",
        "source_basis": "Existing LP input"
    },
    {
        "field": "goal_allocation_factor",
        "LP_role": "Verified allocation parameter",
        "meaning": "Fraction of positive cash flow allocated to goal",
        "verified": "YES",
        "source_basis": "Step 5I exact reconstruction"
    }
]

parameter_df = pd.DataFrame(parameter_mapping)

print("\n" + "=" * 80)
print("1. VERIFIED LP PARAMETERS")
print("=" * 80)

print(
    parameter_df.to_string(index=False)
)

# ------------------------------------------------------------
# 3. VERIFIED EXISTING FUNDING EQUATION
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("2. VERIFIED EXISTING FUNDING EQUATION")
print("=" * 80)

print("""
For each month t:

PositiveCashFlow_t
    = max(MonthlySurplusDynamic_t, 0)

ExistingMonthlyGoalFunding_t
    = PositiveCashFlow_t × GoalAllocationFactor

ExistingGoalFunding
    = SUM(
        PositiveCashFlow_t × GoalAllocationFactor
      )
      over t = 1 ... H
""")

print("\nStep 5I verification:")
print("Candidate A exact matches: 10000 / 10000")
print("Mean absolute difference: approximately 2.7e-11")
print("Maximum absolute difference: approximately 3.73e-09")
print("Correlation: 1.000000")

# ------------------------------------------------------------
# 4. CALCULATE CURRENT MONTHLY SURPLUS
# ------------------------------------------------------------

df["calculated_monthly_surplus"] = (
    df["monthly_income"]
    - df["monthly_expenditure"]
    - df["monthly_emi"]
)

df["positive_monthly_surplus"] = (
    df["calculated_monthly_surplus"]
    .clip(lower=0)
)

# ------------------------------------------------------------
# 5. CANDIDATE LP DECISION VARIABLES
# ------------------------------------------------------------

decision_variables = [
    {
        "variable": "G_t",
        "description": "Goal contribution in month t",
        "unit": "currency/month",
        "nonnegative": "YES",
        "status": "SUPPORTED"
    },
    {
        "variable": "I_t",
        "description": "New investment contribution in month t",
        "unit": "currency/month",
        "nonnegative": "YES",
        "status": "SUPPORTED AS DECISION CONCEPT"
    },
    {
        "variable": "C_t",
        "description": "Cash/savings retained in month t",
        "unit": "currency/month",
        "nonnegative": "YES",
        "status": "SUPPORTED AS DECISION CONCEPT"
    },
    {
        "variable": "D",
        "description": "Goal shortfall at horizon",
        "unit": "currency",
        "nonnegative": "YES",
        "status": "SUPPORTED"
    }
]

decision_df = pd.DataFrame(decision_variables)

print("\n" + "=" * 80)
print("3. CANDIDATE DECISION VARIABLES")
print("=" * 80)

print(
    decision_df.to_string(index=False)
)

# ------------------------------------------------------------
# 6. CONSTRAINT AUDIT
# ------------------------------------------------------------

constraints = [
    {
        "constraint": "Non-negativity",
        "mathematical_form": "G_t >= 0, I_t >= 0, C_t >= 0, D >= 0",
        "basis": "Standard allocation requirement",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Monthly budget",
        "mathematical_form": "G_t + I_t + C_t <= available positive cash flow",
        "basis": "Existing monthly surplus structure",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Goal allocation",
        "mathematical_form": "G_t <= positive_cash_flow_t × goal_allocation_factor",
        "basis": "Step 5I exact existing funding formula",
        "status": "STRONGLY SUPPORTED"
    },
    {
        "constraint": "Goal monthly capacity",
        "mathematical_form": "G_t <= goal_specific_monthly_capacity",
        "basis": "Existing LP field",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Investment capacity",
        "mathematical_form": "I_t <= available_cash_flow × investment_capacity_ratio",
        "basis": "Existing LP field and Step 5B/5D audit",
        "status": "SUPPORTED AS CANDIDATE"
    },
    {
        "constraint": "Horizon",
        "mathematical_form": "t = 1,...,goal_horizon_months",
        "basis": "Existing goal horizon",
        "status": "SUPPORTED"
    },
    {
        "constraint": "Goal target",
        "mathematical_form": "SUM(G_t) + eligible_initial_goal_funding >= target_amount",
        "basis": "Goal target field",
        "status": "FORMULATION DECISION REQUIRED"
    },
    {
        "constraint": "Initial savings",
        "mathematical_form": "Initial savings may be available as initial goal funding",
        "basis": "Existing initial state",
        "status": "FORMULATION DECISION REQUIRED"
    },
    {
        "constraint": "Initial investment",
        "mathematical_form": "Initial investment enters as existing portfolio state",
        "basis": "Existing initial state",
        "status": "SUPPORTED AS INITIAL STATE"
    },
    {
        "constraint": "Borrowing",
        "mathematical_form": "No borrowing variable in base LP",
        "basis": "No borrowing decision field exists",
        "status": "EXCLUDED"
    },
    {
        "constraint": "WALR",
        "mathematical_form": "No WALR term in base LP",
        "basis": "Borrowing is not modeled",
        "status": "EXCLUDED"
    }
]

constraint_df = pd.DataFrame(constraints)

print("\n" + "=" * 80)
print("4. CONSTRAINT AUDIT")
print("=" * 80)

print(
    constraint_df.to_string(index=False)
)

# ------------------------------------------------------------
# 7. OBJECTIVE FUNCTION AUDIT
# ------------------------------------------------------------

objectives = [
    {
        "objective": "Maximize goal funding",
        "form": "max SUM(G_t)",
        "basis": "Directly aligned with goal funding",
        "verified_by_existing_methodology": "NO",
        "status": "CANDIDATE ONLY"
    },
    {
        "objective": "Minimize goal shortfall",
        "form": "min D",
        "basis": "Goal shortfall is an existing outcome",
        "verified_by_existing_methodology": "NO",
        "status": "CANDIDATE ONLY"
    },
    {
        "objective": "Minimize shortfall subject to investment allocation",
        "form": "min D with investment constraints",
        "basis": "Potential optimization formulation",
        "verified_by_existing_methodology": "NO",
        "status": "CANDIDATE ONLY"
    },
    {
        "objective": "Maximize total wealth",
        "form": "max final savings + final investment",
        "basis": "Existing wealth fields",
        "verified_by_existing_methodology": "NO",
        "status": "NOT SELECTED"
    }
]

objective_df = pd.DataFrame(objectives)

print("\n" + "=" * 80)
print("5. OBJECTIVE FUNCTION AUDIT")
print("=" * 80)

print(
    objective_df.to_string(index=False)
)

# ------------------------------------------------------------
# 8. CHECK DATA SUPPORT FOR OBJECTIVE/CONSTRAINTS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("6. DATA SUPPORT CHECK")
print("=" * 80)

required_fields = [
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "goal_horizon_funding_actual"
]

support_rows = []

for col in required_fields:

    exists = col in df.columns

    if exists:
        missing = int(df[col].isna().sum())
        unique = int(df[col].nunique())
    else:
        missing = None
        unique = None

    support_rows.append({
        "field": col,
        "exists": exists,
        "missing_values": missing,
        "unique_values": unique
    })

support_df = pd.DataFrame(support_rows)

print(
    support_df.to_string(index=False)
)

# ------------------------------------------------------------
# 9. BASIC PARAMETER STATISTICS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("7. KEY PARAMETER STATISTICS")
print("=" * 80)

stats_fields = [
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor"
]

stats_fields = [
    c for c in stats_fields
    if c in df.columns
]

print(
    df[stats_fields]
    .describe()
    .T
    .to_string()
)

# ------------------------------------------------------------
# 10. IMPORTANT FORMULATION WARNINGS
# ------------------------------------------------------------

warnings = [
    {
        "issue": "Objective function",
        "finding": "Existing data does not explicitly identify the optimization objective.",
        "action": "Must be selected/formally justified before solver."
    },
    {
        "issue": "Initial savings",
        "finding": "Initial savings exists but its eligibility as goal funding is not established by Step 5I.",
        "action": "Must be explicitly decided."
    },
    {
        "issue": "Initial investment",
        "finding": "Initial investment exists as an initial state.",
        "action": "Do not automatically count it as goal funding."
    },
    {
        "issue": "Investment return",
        "finding": "LP input contains no future monthly return series.",
        "action": "A deterministic LP should not invent return assumptions."
    },
    {
        "issue": "Risk score",
        "finding": "Risk score/profile are available parameters.",
        "action": "Do not invent arbitrary risk thresholds."
    },
    {
        "issue": "WALR",
        "finding": "WALR is available in the economic environment but borrowing is not modeled.",
        "action": "Exclude from base LP unless borrowing is explicitly introduced."
    },
    {
        "issue": "NIFTY",
        "finding": "NIFTY exists in simulation history but is not directly present in the LP input.",
        "action": "Do not insert NIFTY returns into the base LP without a defined investment-return formulation."
    }
]

warning_df = pd.DataFrame(warnings)

print("\n" + "=" * 80)
print("8. FORMULATION WARNINGS")
print("=" * 80)

print(
    warning_df.to_string(index=False)
)

# ------------------------------------------------------------
# 11. SAVE AUDIT FILES
# ------------------------------------------------------------

parameter_path = os.path.join(
    OUT_DIR,
    "lp_5j_parameter_mapping.csv"
)

decision_path = os.path.join(
    OUT_DIR,
    "lp_5j_decision_variable_audit.csv"
)

constraint_path = os.path.join(
    OUT_DIR,
    "lp_5j_constraint_audit.csv"
)

objective_path = os.path.join(
    OUT_DIR,
    "lp_5j_objective_audit.csv"
)

support_path = os.path.join(
    OUT_DIR,
    "lp_5j_data_support_audit.csv"
)

warning_path = os.path.join(
    OUT_DIR,
    "lp_5j_formulation_warnings.csv"
)

parameter_df.to_csv(parameter_path, index=False)
decision_df.to_csv(decision_path, index=False)
constraint_df.to_csv(constraint_path, index=False)
objective_df.to_csv(objective_path, index=False)
support_df.to_csv(support_path, index=False)
warning_df.to_csv(warning_path, index=False)

print("\n" + "=" * 80)
print("STEP 5J COMPLETE")
print("=" * 80)

print("\nSaved:")
print(parameter_path)
print(decision_path)
print(constraint_path)
print(objective_path)
print(support_path)
print(warning_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")
print("NO BORROWING WAS INTRODUCED.")
print("NO RETURN ASSUMPTIONS WERE INVENTED.")

================================================================================
STEP 5J — LP MATHEMATICAL FORMULATION AUDIT
================================================================================

LP input shape: (10000, 38)
Unique users: 10000
Duplicate user IDs: 0

================================================================================
1. VERIFIED LP PARAMETERS
================================================================================
                         field                       LP_role                                          meaning verified                 source_basis
                monthly_income                     Parameter   Monthly income available to the financial plan      YES            Existing LP input
           monthly_expenditure                     Parameter                              Monthly expenditure      YES            Existing LP input
                   monthly_emi                     Parameter                           Monthly EMI obligation      YES            Existing LP input
               initial_savings                 Initial state                       Savings available at start      YES            Existing LP input
            initial_investment                 Initial state               Existing investment value at start      YES            Existing LP input
     investment_capacity_ratio         Upper-bound parameter          User-specific investment capacity ratio      YES            Existing LP input
                    risk_score                     Parameter                                  User risk score      YES            Existing LP input
                  risk_profile                     Parameter     Aggressive / moderate / conservative profile      YES            Existing LP input
           goal_horizon_months                     Parameter              Number of months available for goal      YES            Existing LP input
                 target_amount                     Parameter                             Required goal target      YES            Existing LP input
goal_specific_monthly_capacity         Upper-bound parameter                   Existing monthly goal capacity      YES            Existing LP input
        goal_allocation_factor Verified allocation parameter Fraction of positive cash flow allocated to goal      YES Step 5I exact reconstruction

================================================================================
2. VERIFIED EXISTING FUNDING EQUATION
================================================================================

For each month t:

PositiveCashFlow_t
    = max(MonthlySurplusDynamic_t, 0)

ExistingMonthlyGoalFunding_t
    = PositiveCashFlow_t × GoalAllocationFactor

ExistingGoalFunding
    = SUM(
        PositiveCashFlow_t × GoalAllocationFactor
      )
      over t = 1 ... H


Step 5I verification:
Candidate A exact matches: 10000 / 10000
Mean absolute difference: approximately 2.7e-11
Maximum absolute difference: approximately 3.73e-09
Correlation: 1.000000

================================================================================
3. CANDIDATE DECISION VARIABLES
================================================================================
variable                            description           unit nonnegative                        status
     G_t           Goal contribution in month t currency/month         YES                     SUPPORTED
     I_t New investment contribution in month t currency/month         YES SUPPORTED AS DECISION CONCEPT
     C_t       Cash/savings retained in month t currency/month         YES SUPPORTED AS DECISION CONCEPT
       D              Goal shortfall at horizon       currency         YES                     SUPPORTED

================================================================================
4. CONSTRAINT AUDIT
================================================================================
           constraint                                         mathematical_form                                  basis                        status
       Non-negativity                      G_t >= 0, I_t >= 0, C_t >= 0, D >= 0        Standard allocation requirement                     SUPPORTED
       Monthly budget           G_t + I_t + C_t <= available positive cash flow     Existing monthly surplus structure                     SUPPORTED
      Goal allocation      G_t <= positive_cash_flow_t × goal_allocation_factor Step 5I exact existing funding formula            STRONGLY SUPPORTED
Goal monthly capacity                     G_t <= goal_specific_monthly_capacity                      Existing LP field                     SUPPORTED
  Investment capacity    I_t <= available_cash_flow × investment_capacity_ratio Existing LP field and Step 5B/5D audit        SUPPORTED AS CANDIDATE
              Horizon                             t = 1,...,goal_horizon_months                  Existing goal horizon                     SUPPORTED
          Goal target SUM(G_t) + eligible_initial_goal_funding >= target_amount                      Goal target field FORMULATION DECISION REQUIRED
      Initial savings  Initial savings may be available as initial goal funding                 Existing initial state FORMULATION DECISION REQUIRED
   Initial investment     Initial investment enters as existing portfolio state                 Existing initial state    SUPPORTED AS INITIAL STATE
            Borrowing                          No borrowing variable in base LP     No borrowing decision field exists                      EXCLUDED
                 WALR                                   No WALR term in base LP               Borrowing is not modeled                      EXCLUDED

================================================================================
5. OBJECTIVE FUNCTION AUDIT
================================================================================
                                          objective                                 form                                 basis verified_by_existing_methodology         status
                              Maximize goal funding                         max SUM(G_t)    Directly aligned with goal funding                               NO CANDIDATE ONLY
                            Minimize goal shortfall                                min D Goal shortfall is an existing outcome                               NO CANDIDATE ONLY
Minimize shortfall subject to investment allocation    min D with investment constraints    Potential optimization formulation                               NO CANDIDATE ONLY
                              Maximize total wealth max final savings + final investment                Existing wealth fields                               NO   NOT SELECTED

================================================================================
6. DATA SUPPORT CHECK
================================================================================
                         field  exists  missing_values  unique_values
                monthly_income    True               0          10000
           monthly_expenditure    True               0           1449
                   monthly_emi    True               0           4209
               initial_savings    True               0          10000
            initial_investment    True               0           5446
     investment_capacity_ratio    True               0           7871
                    risk_score    True               0           8754
                  risk_profile    True               0              3
           goal_horizon_months    True               0            115
                 target_amount    True               0          10000
goal_specific_monthly_capacity    True               0           7871
        goal_allocation_factor    True               0           7871
   goal_horizon_funding_actual    True               0           8536

================================================================================
7. KEY PARAMETER STATISTICS
================================================================================
                                  count           mean            std          min           25%            50%            75%           max
monthly_income                  10000.0   61588.311653   53908.829380  1257.339650  32005.389162   47770.485750   71013.157446  8.459932e+05
monthly_expenditure             10000.0   44971.461200   37632.718833   850.000000  24000.000000   35750.000000   51316.500000  5.305000e+05
monthly_emi                     10000.0    5195.490810    9746.159467     0.000000      0.000000       0.000000    8042.871110  1.398347e+05
initial_savings                 10000.0  166794.764388  217534.748504     7.776881  49608.326314  104229.701508  202970.684488  4.946443e+06
initial_investment              10000.0   56968.534834  121610.403860     0.000000      0.000000    9154.054851   67910.432199  3.880240e+06
investment_capacity_ratio       10000.0       0.187228       0.149113     0.000000      0.036815       0.189573       0.306529  4.999763e-01
risk_score                      10000.0       0.500000       0.223233     0.028262      0.313572       0.540337       0.682412  8.540000e-01
goal_horizon_months             10000.0      62.697000      33.431233     6.000000     33.000000      63.000000      92.000000  1.200000e+02
target_amount                   10000.0  138353.834973  121102.415110  2824.525592  71897.868468  107313.055427  159526.091924  1.900464e+06
goal_specific_monthly_capacity  10000.0   10408.069934   18578.095127     0.000000    304.680019    3802.625086   12801.743318  4.013533e+05
goal_allocation_factor          10000.0       0.500050       0.287291     0.106550      0.250075       0.500050       0.750025  1.000000e+00

================================================================================
8. FORMULATION WARNINGS
================================================================================
             issue                                                                                   finding                                                                                        action
Objective function                    Existing data does not explicitly identify the optimization objective.                                            Must be selected/formally justified before solver.
   Initial savings Initial savings exists but its eligibility as goal funding is not established by Step 5I.                                                                   Must be explicitly decided.
Initial investment                                            Initial investment exists as an initial state.                                                Do not automatically count it as goal funding.
 Investment return                                        LP input contains no future monthly return series.                                      A deterministic LP should not invent return assumptions.
        Risk score                                              Risk score/profile are available parameters.                                                      Do not invent arbitrary risk thresholds.
              WALR               WALR is available in the economic environment but borrowing is not modeled.                               Exclude from base LP unless borrowing is explicitly introduced.
             NIFTY           NIFTY exists in simulation history but is not directly present in the LP input. Do not insert NIFTY returns into the base LP without a defined investment-return formulation.

================================================================================
STEP 5J COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5j_parameter_mapping.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5j_decision_variable_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5j_constraint_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5j_objective_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5j_data_support_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5j_formulation_warnings.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO OBJECTIVE FUNCTION WAS ASSUMED.
NO BORROWING WAS INTRODUCED.
NO RETURN ASSUMPTIONS WERE INVENTED.

In [100]:
# ============================================================
# GOALPILOT AI — STEP 5K
# FINAL LP TARGET & OBJECTIVE FORMULATION AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5K — FINAL LP TARGET & OBJECTIVE FORMULATION AUDIT")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD
# ------------------------------------------------------------

df = pd.read_csv(LP_FILE)

print("\nShape:", df.shape)
print("Unique users:", df["user_id"].nunique())

# ------------------------------------------------------------
# 2. NUMERIC CLEANUP
# ------------------------------------------------------------

numeric_cols = [
    "initial_savings",
    "initial_investment",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_achieved_on_time_actual",
    "goal_shortfall_actual",
    "goal_funding_ratio",
    "goal_progress_at_deadline_actual",
    "goal_progress_at_deadline_actual_capped",
    "goal_shortfall_ratio",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "goal_horizon_months",
    "investment_capacity_ratio"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

# ------------------------------------------------------------
# 3. EXISTING GOAL ACHIEVEMENT
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("1. EXISTING GOAL ACHIEVEMENT")
print("=" * 80)

actual_success = (
    df["goal_achieved_on_time_actual"] == 1
)

print(
    "Existing successful users:",
    int(actual_success.sum())
)

print(
    "Existing unsuccessful users:",
    int((~actual_success).sum())
)

print(
    "Existing success rate:",
    actual_success.mean()
)

# ------------------------------------------------------------
# 4. FORMULATION A
# ------------------------------------------------------------

# New goal funding alone must reach target
df["formulation_A_required"] = (
    df["target_amount"]
)

df["formulation_A_success"] = (
    df["goal_horizon_funding_actual"]
    >= df["target_amount"]
)

# ------------------------------------------------------------
# 5. FORMULATION B
# ------------------------------------------------------------

# Initial savings + new goal funding must reach target
df["formulation_B_required"] = (
    df["target_amount"]
    - df["initial_savings"]
).clip(lower=0)

df["formulation_B_success"] = (
    df["initial_savings"]
    + df["goal_horizon_funding_actual"]
    >= df["target_amount"]
)

# ------------------------------------------------------------
# 6. COMPARE BOTH FORMULATIONS WITH ACTUAL RESULT
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("2. TARGET FORMULATION COMPARISON")
print("=" * 80)

comparison = pd.DataFrame({
    "actual_success": actual_success.astype(int),
    "formulation_A_success": (
        df["formulation_A_success"].astype(int)
    ),
    "formulation_B_success": (
        df["formulation_B_success"].astype(int)
    )
})

print("\nActual vs Formulation A:")
print(
    pd.crosstab(
        comparison["actual_success"],
        comparison["formulation_A_success"],
        rownames=["Actual"],
        colnames=["Formulation_A"]
    )
)

print("\nActual vs Formulation B:")
print(
    pd.crosstab(
        comparison["actual_success"],
        comparison["formulation_B_success"],
        rownames=["Actual"],
        colnames=["Formulation_B"]
    )
)

# Agreement
agreement_A = (
    comparison["actual_success"]
    == comparison["formulation_A_success"]
)

agreement_B = (
    comparison["actual_success"]
    == comparison["formulation_B_success"]
)

print("\nAgreement with existing simulation:")
print(
    "Formulation A:",
    int(agreement_A.sum()),
    "/",
    len(df),
    "=",
    agreement_A.mean()
)

print(
    "Formulation B:",
    int(agreement_B.sum()),
    "/",
    len(df),
    "=",
    agreement_B.mean()
)

# ------------------------------------------------------------
# 7. FALSE POSITIVE / FALSE NEGATIVE ANALYSIS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("3. DISAGREEMENT ANALYSIS")
print("=" * 80)

df["A_difference"] = (
    df["goal_horizon_funding_actual"]
    - df["target_amount"]
)

df["B_difference"] = (
    df["initial_savings"]
    + df["goal_horizon_funding_actual"]
    - df["target_amount"]
)

df["A_disagreement"] = (
    df["formulation_A_success"]
    != actual_success
)

df["B_disagreement"] = (
    df["formulation_B_success"]
    != actual_success
)

print(
    "Formulation A disagreements:",
    int(df["A_disagreement"].sum())
)

print(
    "Formulation B disagreements:",
    int(df["B_disagreement"].sum())
)

# ------------------------------------------------------------
# 8. TARGET VS INITIAL SAVINGS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("4. INITIAL SAVINGS VS TARGET")
print("=" * 80)

df["target_minus_initial_savings"] = (
    df["target_amount"]
    - df["initial_savings"]
)

print(
    df[
        [
            "target_amount",
            "initial_savings",
            "target_minus_initial_savings"
        ]
    ]
    .describe()
    .to_string()
)

print(
    "\nUsers where initial savings >= target:",
    int(
        (
            df["initial_savings"]
            >= df["target_amount"]
        ).sum()
    )
)

print(
    "Users where initial savings < target:",
    int(
        (
            df["initial_savings"]
            < df["target_amount"]
        ).sum()
    )
)

# ------------------------------------------------------------
# 9. ACTUAL FUNDING RELATIONSHIP
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("5. ACTUAL FUNDING VS TARGET")
print("=" * 80)

df["actual_funding_minus_target"] = (
    df["goal_horizon_funding_actual"]
    - df["target_amount"]
)

print(
    df[
        [
            "goal_horizon_funding_actual",
            "target_amount",
            "actual_funding_minus_target"
        ]
    ]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 10. SHORTFALL VERIFICATION
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("6. EXISTING SHORTFALL RELATIONSHIP")
print("=" * 80)

expected_shortfall_A = (
    df["target_amount"]
    - df["goal_horizon_funding_actual"]
).clip(lower=0)

shortfall_diff = (
    df["goal_shortfall_actual"]
    - expected_shortfall_A
).abs()

print(
    "Existing shortfall vs target - funding:"
)

print(
    "Mean absolute difference:",
    shortfall_diff.mean()
)

print(
    "Maximum absolute difference:",
    shortfall_diff.max()
)

print(
    "Matches <= 1e-6:",
    int((shortfall_diff <= 1e-6).sum()),
    "/",
    len(df)
)

# ------------------------------------------------------------
# 11. FUNDING RATIO VERIFICATION
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("7. EXISTING FUNDING RATIO")
print("=" * 80)

expected_ratio = (
    df["goal_horizon_funding_actual"]
    / df["target_amount"]
)

ratio_diff = (
    df["goal_funding_ratio"]
    - expected_ratio
).abs()

print(
    "Mean absolute difference:",
    ratio_diff.mean()
)

print(
    "Maximum absolute difference:",
    ratio_diff.max()
)

print(
    "Matches <= 1e-6:",
    int((ratio_diff <= 1e-6).sum()),
    "/",
    len(df)
)

# ------------------------------------------------------------
# 12. OBJECTIVE-RELATED METRICS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("8. OBJECTIVE-RELATED METRICS")
print("=" * 80)

metrics = {
    "Mean target": df["target_amount"].mean(),
    "Mean actual funding": df[
        "goal_horizon_funding_actual"
    ].mean(),
    "Mean actual shortfall": df[
        "goal_shortfall_actual"
    ].mean(),
    "Mean funding ratio": df[
        "goal_funding_ratio"
    ].mean(),
    "Actual success rate": actual_success.mean()
}

for key, value in metrics.items():
    print(f"{key}: {value:.6f}")

# ------------------------------------------------------------
# 13. RISK / OBJECTIVE CHECK
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("9. SUCCESS BY RISK PROFILE")
print("=" * 80)

risk_table = (
    df.groupby("risk_profile")
      .agg(
          users=("user_id", "count"),
          mean_target=("target_amount", "mean"),
          mean_funding=(
              "goal_horizon_funding_actual",
              "mean"
          ),
          mean_shortfall=(
              "goal_shortfall_actual",
              "mean"
          ),
          success_rate=(
              "goal_achieved_on_time_actual",
              "mean"
          ),
          mean_risk_score=("risk_score", "mean")
      )
      .reset_index()
)

print(
    risk_table.to_string(index=False)
)

# ------------------------------------------------------------
# 14. FINANCIAL SITUATION CHECK
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("10. SUCCESS BY FINANCIAL SITUATION")
print("=" * 80)

financial_table = (
    df.groupby("financial_situation")
      .agg(
          users=("user_id", "count"),
          mean_target=("target_amount", "mean"),
          mean_funding=(
              "goal_horizon_funding_actual",
              "mean"
          ),
          mean_shortfall=(
              "goal_shortfall_actual",
              "mean"
          ),
          success_rate=(
              "goal_achieved_on_time_actual",
              "mean"
          )
      )
      .reset_index()
)

print(
    financial_table.to_string(index=False)
)

# ------------------------------------------------------------
# 15. FORMULATION RECOMMENDATION — DATA-BASED ONLY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("11. FORMULATION EVIDENCE SUMMARY")
print("=" * 80)

if agreement_A.mean() > agreement_B.mean():
    print(
        "FORMULATION A has greater agreement with the existing "
        "goal achievement outcome."
    )
elif agreement_B.mean() > agreement_A.mean():
    print(
        "FORMULATION B has greater agreement with the existing "
        "goal achievement outcome."
    )
else:
    print(
        "Both formulations have equal agreement with the existing "
        "goal achievement outcome."
    )

print(
    "\nIMPORTANT:"
)

print(
    "This is an evidence comparison only."
)

print(
    "The optimization objective is NOT being selected automatically."
)

print(
    "No LP solver was run."
)

# ------------------------------------------------------------
# 16. SAVE
# ------------------------------------------------------------

audit_path = os.path.join(
    OUT_DIR,
    "lp_5k_target_objective_formulation_audit.csv"
)

comparison_path = os.path.join(
    OUT_DIR,
    "lp_5k_target_formulation_comparison.csv"
)

df.to_csv(
    audit_path,
    index=False
)

comparison.to_csv(
    comparison_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5K COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(comparison_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5K — FINAL LP TARGET & OBJECTIVE FORMULATION AUDIT
================================================================================

Shape: (10000, 38)
Unique users: 10000

================================================================================
1. EXISTING GOAL ACHIEVEMENT
================================================================================
Existing successful users: 6451
Existing unsuccessful users: 3549
Existing success rate: 0.6451

================================================================================
2. TARGET FORMULATION COMPARISON
================================================================================

Actual vs Formulation A:
Formulation_A     0     1
Actual
0              3549     0
1                 0  6451

Actual vs Formulation B:
Formulation_B     0     1
Actual
0              2000  1549
1                 0  6451

Agreement with existing simulation:
Formulation A: 10000 / 10000 = 1.0
Formulation B: 8451 / 10000 = 0.8451

================================================================================
3. DISAGREEMENT ANALYSIS
================================================================================
Formulation A disagreements: 0
Formulation B disagreements: 1549

================================================================================
4. INITIAL SAVINGS VS TARGET
================================================================================
       target_amount  initial_savings  target_minus_initial_savings
count   1.000000e+04     1.000000e+04                  1.000000e+04
mean    1.383538e+05     1.667948e+05                 -2.844093e+04
std     1.211024e+05     2.175347e+05                  1.420256e+05
min     2.824526e+03     7.776881e+00                 -3.056402e+06
25%     7.189787e+04     4.960833e+04                 -5.942489e+04
50%     1.073131e+05     1.042297e+05                  9.285262e+00
75%     1.595261e+05     2.029707e+05                  3.531082e+04
max     1.900464e+06     4.946443e+06                  8.682426e+05

Users where initial savings >= target: 5000
Users where initial savings < target: 5000

================================================================================
5. ACTUAL FUNDING VS TARGET
================================================================================
       goal_horizon_funding_actual  target_amount  actual_funding_minus_target
count                 1.000000e+04   1.000000e+04                 1.000000e+04
mean                  9.449648e+05   1.383538e+05                 8.066110e+05
std                   2.156857e+06   1.211024e+05                 2.082364e+06
min                   0.000000e+00   2.824526e+03                -9.960700e+05
25%                   2.676139e+04   7.189787e+04                -4.237602e+04
50%                   2.364985e+05   1.073131e+05                 1.297432e+05
75%                   9.683717e+05   1.595261e+05                 8.175241e+05
max                   6.659288e+07   1.900464e+06                 6.470284e+07

================================================================================
6. EXISTING SHORTFALL RELATIONSHIP
================================================================================
Existing shortfall vs target - funding:
Mean absolute difference: 9.550831236992962e-13
Maximum absolute difference: 1.1641532182693481e-10
Matches <= 1e-6: 10000 / 10000

================================================================================
7. EXISTING FUNDING RATIO
================================================================================
Mean absolute difference: 3.280102104779312e-16
Maximum absolute difference: 1.4210854715202004e-14
Matches <= 1e-6: 10000 / 10000

================================================================================
8. OBJECTIVE-RELATED METRICS
================================================================================
Mean target: 138353.834973
Mean actual funding: 944964.830723
Mean actual shortfall: 30580.490391
Mean funding ratio: 5.191022
Actual success rate: 0.645100

================================================================================
9. SUCCESS BY RISK PROFILE
================================================================================
risk_profile  users   mean_target  mean_funding  mean_shortfall  success_rate  mean_risk_score
  aggressive   3333 158150.737279  1.898103e+06     1153.365886      0.959196         0.737324
conservative   3333 123393.710270  1.362033e+05    79344.620272      0.216322         0.227601
    moderate   3334 133518.508112  8.006316e+05    11249.284956      0.759748         0.535065

================================================================================
10. SUCCESS BY FINANCIAL SITUATION
================================================================================
financial_situation  users   mean_target  mean_funding  mean_shortfall  success_rate
   financial_stress    474  97313.534110  3.172216e+03    94141.317967      0.000000
        high_saving   2043 178299.962715  2.450276e+06      553.144002      0.977974
         low_saving   2923 116054.134290  1.738092e+05    63297.246577      0.322956
    moderate_saving   4560 139017.253553  8.627601e+05    16454.823301      0.769518

================================================================================
11. FORMULATION EVIDENCE SUMMARY
================================================================================
FORMULATION A has greater agreement with the existing goal achievement outcome.

IMPORTANT:
This is an evidence comparison only.
The optimization objective is NOT being selected automatically.
No LP solver was run.

================================================================================
STEP 5K COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5k_target_objective_formulation_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5k_target_formulation_comparison.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO OBJECTIVE FUNCTION WAS ASSUMED.

In [101]:
# ============================================================
# GOALPILOT AI — STEP 5L.1
# LP FEASIBILITY BOUNDARY AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5L.1 — LP FEASIBILITY BOUNDARY AUDIT")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD
# ------------------------------------------------------------

df = pd.read_csv(LP_FILE)

print("\nShape:", df.shape)
print("Users:", df["user_id"].nunique())

# ------------------------------------------------------------
# 2. CALCULATE BASE MONTHLY SURPLUS
# ------------------------------------------------------------

df["monthly_surplus_calculated"] = (
    df["monthly_income"]
    - df["monthly_expenditure"]
    - df["monthly_emi"]
)

df["positive_cash_flow"] = (
    df["monthly_surplus_calculated"]
    .clip(lower=0)
)

# ------------------------------------------------------------
# 3. EXISTING GOAL LIMIT
# ------------------------------------------------------------

df["goal_monthly_limit"] = (
    df["positive_cash_flow"]
    * df["goal_allocation_factor"]
)

# ------------------------------------------------------------
# 4. INVESTMENT LIMIT
# ------------------------------------------------------------

df["investment_monthly_limit"] = (
    df["positive_cash_flow"]
    * df["investment_capacity_ratio"]
)

# ------------------------------------------------------------
# 5. MAXIMUM GOAL FUNDING OVER HORIZON
# ------------------------------------------------------------

df["max_goal_funding"] = (
    df["goal_monthly_limit"]
    * df["goal_horizon_months"]
)

# ------------------------------------------------------------
# 6. TARGET GAP
# ------------------------------------------------------------

df["max_goal_funding_minus_target"] = (
    df["max_goal_funding"]
    - df["target_amount"]
)

df["maximum_goal_feasible"] = (
    df["max_goal_funding"]
    >= df["target_amount"]
)

# ------------------------------------------------------------
# 7. REQUIRED MONTHLY GOAL CONTRIBUTION
# ------------------------------------------------------------

df["required_monthly_goal_average"] = (
    df["target_amount"]
    / df["goal_horizon_months"]
)

df["goal_capacity_margin"] = (
    df["goal_monthly_limit"]
    - df["required_monthly_goal_average"]
)

# ------------------------------------------------------------
# 8. AVAILABLE CASH AFTER GOAL + INVESTMENT LIMITS
# ------------------------------------------------------------

df["combined_goal_investment_limit"] = (
    df["goal_monthly_limit"]
    + df["investment_monthly_limit"]
)

df["allocation_capacity_ratio"] = np.where(
    df["positive_cash_flow"] > 0,
    df["combined_goal_investment_limit"]
    / df["positive_cash_flow"],
    0
)

df["cash_remaining_after_max_limits"] = (
    df["positive_cash_flow"]
    - df["combined_goal_investment_limit"]
)

# ------------------------------------------------------------
# 9. CHECK WHETHER GOAL LIMIT IS THE BINDING CONSTRAINT
# ------------------------------------------------------------

df["goal_limit_ratio"] = np.where(
    df["positive_cash_flow"] > 0,
    df["goal_monthly_limit"]
    / df["positive_cash_flow"],
    0
)

df["investment_limit_ratio"] = np.where(
    df["positive_cash_flow"] > 0,
    df["investment_monthly_limit"]
    / df["positive_cash_flow"],
    0
)

# ------------------------------------------------------------
# 10. EXISTING VS MAXIMUM POSSIBLE
# ------------------------------------------------------------

df["existing_funding_gap_to_max"] = (
    df["max_goal_funding"]
    - df["goal_horizon_funding_actual"]
)

# ------------------------------------------------------------
# 11. SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("1. MAXIMUM GOAL FUNDING")
print("=" * 80)

print(
    df[
        [
            "max_goal_funding",
            "target_amount",
            "max_goal_funding_minus_target"
        ]
    ]
    .describe()
    .to_string()
)

print("\nPotentially feasible users:")
print(
    int(df["maximum_goal_feasible"].sum()),
    "/",
    len(df)
)

print("\nPotentially infeasible users:")
print(
    int((~df["maximum_goal_feasible"]).sum()),
    "/",
    len(df)
)

# ------------------------------------------------------------
# 12. REQUIRED MONTHLY VS ALLOWED
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("2. REQUIRED MONTHLY CONTRIBUTION VS GOAL LIMIT")
print("=" * 80)

print(
    df[
        [
            "required_monthly_goal_average",
            "goal_monthly_limit",
            "goal_capacity_margin"
        ]
    ]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 13. GOAL + INVESTMENT CAPACITY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("3. GOAL + INVESTMENT CAPACITY")
print("=" * 80)

print(
    df[
        [
            "positive_cash_flow",
            "goal_monthly_limit",
            "investment_monthly_limit",
            "combined_goal_investment_limit",
            "allocation_capacity_ratio",
            "cash_remaining_after_max_limits"
        ]
    ]
    .describe()
    .to_string()
)

print(
    "\nUsers where goal + investment limits exceed available cash:",
    int(
        (
            df["combined_goal_investment_limit"]
            > df["positive_cash_flow"] + 1e-9
        ).sum()
    )
)

# ------------------------------------------------------------
# 14. EXISTING FUNDING GAP
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("4. EXISTING FUNDING VS MAXIMUM ALLOWED FUNDING")
print("=" * 80)

print(
    df[
        [
            "goal_horizon_funding_actual",
            "max_goal_funding",
            "existing_funding_gap_to_max"
        ]
    ]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 15. REPRESENTATIVE USERS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("5. REPRESENTATIVE USERS")
print("=" * 80)

show_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "positive_cash_flow",
    "goal_allocation_factor",
    "investment_capacity_ratio",
    "goal_monthly_limit",
    "investment_monthly_limit",
    "required_monthly_goal_average",
    "max_goal_funding",
    "goal_horizon_funding_actual",
    "maximum_goal_feasible",
    "cash_remaining_after_max_limits"
]

print(
    df[show_cols]
    .head(20)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 16. RISK PROFILE FEASIBILITY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("6. FEASIBILITY BY RISK PROFILE")
print("=" * 80)

risk_summary = (
    df.groupby("risk_profile")
      .agg(
          users=("user_id", "count"),
          mean_target=("target_amount", "mean"),
          mean_max_goal_funding=(
              "max_goal_funding",
              "mean"
          ),
          feasible_users=(
              "maximum_goal_feasible",
              "sum"
          ),
          mean_goal_factor=(
              "goal_allocation_factor",
              "mean"
          ),
          mean_investment_ratio=(
              "investment_capacity_ratio",
              "mean"
          )
      )
      .reset_index()
)

risk_summary["feasibility_rate"] = (
    risk_summary["feasible_users"]
    / risk_summary["users"]
)

print(
    risk_summary.to_string(index=False)
)

# ------------------------------------------------------------
# 17. FINANCIAL SITUATION FEASIBILITY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("7. FEASIBILITY BY FINANCIAL SITUATION")
print("=" * 80)

financial_summary = (
    df.groupby("financial_situation")
      .agg(
          users=("user_id", "count"),
          mean_target=("target_amount", "mean"),
          mean_max_goal_funding=(
              "max_goal_funding",
              "mean"
          ),
          feasible_users=(
              "maximum_goal_feasible",
              "sum"
          ),
          mean_goal_factor=(
              "goal_allocation_factor",
              "mean"
          )
      )
      .reset_index()
)

financial_summary["feasibility_rate"] = (
    financial_summary["feasible_users"]
    / financial_summary["users"]
)

print(
    financial_summary.to_string(index=False)
)

# ------------------------------------------------------------
# 18. SAVE
# ------------------------------------------------------------

audit_path = os.path.join(
    OUT_DIR,
    "lp_5l1_feasibility_boundary_audit.csv"
)

risk_path = os.path.join(
    OUT_DIR,
    "lp_5l1_feasibility_by_risk_profile.csv"
)

financial_path = os.path.join(
    OUT_DIR,
    "lp_5l1_feasibility_by_financial_situation.csv"
)

df.to_csv(
    audit_path,
    index=False
)

risk_summary.to_csv(
    risk_path,
    index=False
)

financial_summary.to_csv(
    financial_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5L.1 COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(risk_path)
print(financial_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")

================================================================================
STEP 5L.1 — LP FEASIBILITY BOUNDARY AUDIT
================================================================================

Shape: (10000, 38)
Users: 10000

================================================================================
1. MAXIMUM GOAL FUNDING
================================================================================
       max_goal_funding  target_amount  max_goal_funding_minus_target
count      1.000000e+04   1.000000e+04                   1.000000e+04
mean       6.631026e+05   1.383538e+05                   5.247488e+05
std        1.440565e+06   1.211024e+05                   1.364964e+06
min        0.000000e+00   2.824526e+03                  -1.034294e+06
25%        1.226529e+04   7.189787e+04                  -5.343402e+04
50%        1.726636e+05   1.073131e+05                   6.676159e+04
75%        7.077399e+05   1.595261e+05                   5.594541e+05
max        4.374750e+07   1.900464e+06                   4.185746e+07

Potentially feasible users:
5963 / 10000

Potentially infeasible users:
4037 / 10000

================================================================================
2. REQUIRED MONTHLY CONTRIBUTION VS GOAL LIMIT
================================================================================
       required_monthly_goal_average  goal_monthly_limit  goal_capacity_margin
count                   10000.000000        10000.000000          10000.000000
mean                     3771.144311        10408.069934           6636.925623
std                      6110.404427        18578.095127          17179.304400
min                        39.761411            0.000000        -145655.300802
25%                      1069.839427          304.680019          -1062.852657
50%                      1925.006647         3802.625086           1332.335762
75%                      3902.499505        12801.743318           9269.853140
max                    161715.214633       401353.251371         384013.423486

================================================================================
3. GOAL + INVESTMENT CAPACITY
================================================================================
       positive_cash_flow  goal_monthly_limit  investment_monthly_limit  combined_goal_investment_limit  allocation_capacity_ratio  cash_remaining_after_max_limits
count        10000.000000        10000.000000              10000.000000                    10000.000000               10000.000000                     10000.000000
mean         12896.268636        10408.069934               4126.631261                    14534.701194                   0.664583                     -1638.432559
std          18795.227379        18578.095127               7621.782181                    26031.077113                   0.455973                      7652.688612
min              0.000000            0.000000                  0.000000                        0.000000                   0.000000                   -191458.738792
25%           1218.354377          304.680019                 50.344494                      374.544944                   0.300598                      -921.913405
50%           7604.489602         3802.625086               1440.749242                     5344.377647                   0.708155                        10.446568
75%          17068.422123        12801.743318               5093.630833                    17962.556383                   1.052956                      1683.220784
max         401353.251371       401353.251371             191458.738792                   592811.990164                   1.491413                      4018.059977

Users where goal + investment limits exceed available cash: 2865

================================================================================
4. EXISTING FUNDING VS MAXIMUM ALLOWED FUNDING
================================================================================
       goal_horizon_funding_actual  max_goal_funding  existing_funding_gap_to_max
count                 1.000000e+04      1.000000e+04                 1.000000e+04
mean                  9.449648e+05      6.631026e+05                -2.818622e+05
std                   2.156857e+06      1.440565e+06                 7.509082e+05
min                   0.000000e+00      0.000000e+00                -2.330678e+07
25%                   2.676139e+04      1.226529e+04                -2.537008e+05
50%                   2.364985e+05      1.726636e+05                -4.874536e+04
75%                   9.683717e+05      7.077399e+05                -4.703987e+03
max                   6.659288e+07      4.374750e+07                 0.000000e+00

================================================================================
5. REPRESENTATIVE USERS
================================================================================
   user_id  goal_horizon_months  target_amount  positive_cash_flow  goal_allocation_factor  investment_capacity_ratio  goal_monthly_limit  investment_monthly_limit  required_monthly_goal_average  max_goal_funding  goal_horizon_funding_actual  maximum_goal_feasible  cash_remaining_after_max_limits
USER_00001                   48  115357.183592        14481.335334                 0.69770                   0.282005        10103.627663               4083.809539                    2403.274658      4.849741e+05                 5.811302e+05                   True                       293.898133
USER_00002                   51   59340.387689            0.000000                 0.10655                   0.000000            0.000000                  0.000000                    1163.537014      0.000000e+00                 0.000000e+00                  False                         0.000000
USER_00003                   46   99893.237726         2467.548430                 0.30330                   0.055491          748.407439                136.926713                    2171.592124      3.442674e+04                 4.093773e+04                  False                      1582.214278
USER_00004                   60   75476.307623         1045.743136                 0.24420                   0.031125          255.370474                 32.548599                    1257.938460      1.532223e+04                 4.566919e+04                  False                       757.824063
USER_00005                  120  206040.342056        40719.010189                 0.94170                   0.443954        38345.091895              18077.362450                    1717.002850      4.601411e+06                 7.318348e+06                   True                    -15703.444156
USER_00006                   18  110291.964774        22096.549442                 0.82320                   0.450063        18189.879501               9944.843432                    6127.331376      3.274178e+05                 3.502230e+05                   True                     -6038.173491
USER_00007                   75  128020.414837        26988.382060                 0.87160                   0.473577        23523.073803              12781.074666                    1706.938864      1.764231e+06                 2.348219e+06                   True                     -9315.766410
USER_00008                   11  269916.171830            0.000000                 0.10655                   0.000000            0.000000                  0.000000                   24537.833803      0.000000e+00                 0.000000e+00                  False                         0.000000
USER_00009                   55  182600.732773        27284.850834                 0.87490                   0.335670        23871.515994               9158.694116                    3320.013323      1.312933e+06                 1.616717e+06                   True                     -5745.359276
USER_00010                   24   96702.526658         5047.201045                 0.40940                   0.117248         2066.324108                591.774558                    4029.271944      4.959178e+04                 5.423986e+04                  False                      2389.102379
USER_00011                   42   39905.117099         7263.792300                 0.48900                   0.408910         3551.994435               2970.237306                     950.121836      1.491838e+05                 1.746970e+05                   True                       741.560560
USER_00012                   18  153722.614222            0.000000                 0.10655                   0.000000            0.000000                  0.000000                    8540.145235      0.000000e+00                 0.000000e+00                  False                         0.000000
USER_00013                  102   75699.850293            0.000000                 0.10655                   0.000000            0.000000                  0.000000                     742.155395      0.000000e+00                 0.000000e+00                  False                         0.000000
USER_00014                   88   56999.623650         2436.730582                 0.30130                   0.096035          734.186924                234.010822                     647.722996      6.460845e+04                 1.429149e+05                   True                      1468.532836
USER_00015                  105  294810.384238        48718.138770                 0.96040                   0.371228        46788.900475              18085.540912                    2807.717945      4.912835e+06                 7.737681e+06                   True                    -16156.302616
USER_00016                   32  164062.774110        27032.664866                 0.87260                   0.370145        23588.703362              10006.001713                    5126.961691      7.548385e+05                 8.506991e+05                   True                     -6562.040209
USER_00017                   12   67605.333513         6094.564062                 0.44710                   0.202514         2724.879592               1234.233233                    5633.777793      3.269856e+04                 3.423747e+04                  False                      2135.451237
USER_00018                   65  230098.662301        23428.589185                 0.83980                   0.228731        19675.329198               5358.843616                    3539.979420      1.278896e+06                 1.637618e+06                   True                     -1605.583628
USER_00019                   39   78326.115793        11366.928199                 0.61950                   0.326009         7041.812019               3705.719527                    2008.361943      2.746307e+05                 3.179076e+05                   True                       619.396653
USER_00020                   76   89316.160080         6984.510670                 0.47910                   0.175671         3346.279062               1226.972502                    1175.212633      2.543172e+05                 4.044024e+05                   True                      2411.259106

================================================================================
6. FEASIBILITY BY RISK PROFILE
================================================================================
risk_profile  users   mean_target  mean_max_goal_funding  feasible_users  mean_goal_factor  mean_investment_ratio  feasibility_rate
  aggressive   3333 158150.737279           1.375637e+06            3181          0.746799               0.344191          0.954395
conservative   3333 123393.710270           6.314548e+04             418          0.209046               0.029605          0.125413
    moderate   3334 133518.508112           5.505595e+05            2364          0.544293               0.187888          0.709058

================================================================================
7. FEASIBILITY BY FINANCIAL SITUATION
================================================================================
financial_situation  users   mean_target  mean_max_goal_funding  feasible_users  mean_goal_factor  feasibility_rate
   financial_stress    474  97313.534110           2.369478e+03               0          0.124669          0.000000
        high_saving   2043 178299.962715           1.738169e+06            1995          0.803956          0.976505
         low_saving   2923 116054.134290           1.233606e+05             794          0.271973          0.271639
    moderate_saving   4560 139017.253553           5.961054e+05            3174          0.549111          0.696053

================================================================================
STEP 5L.1 COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l1_feasibility_boundary_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l1_feasibility_by_risk_profile.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l1_feasibility_by_financial_situation.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.

In [102]:
# ============================================================
# GOALPILOT AI — STEP 5L.2
# CORRECTED POLICY VS OPTIMIZATION AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5L.2 — CORRECTED POLICY VS OPTIMIZATION LP AUDIT")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ============================================================
# 1. LOAD
# ============================================================

lp = pd.read_csv(LP_FILE)
monthly = pd.read_csv(MONTHLY_FILE)

monthly["period"] = pd.to_datetime(
    monthly["period"],
    errors="coerce"
)

monthly = monthly.sort_values(
    ["user_id", "period"]
)

monthly["simulation_month"] = (
    monthly.groupby("user_id").cumcount() + 1
)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# ============================================================
# 2. USER-LEVEL PARAMETERS
# ============================================================

user_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "investment_capacity_ratio",
    "initial_savings",
    "initial_investment",
    "risk_score",
    "risk_profile"
]

missing_user_cols = [
    c for c in user_cols
    if c not in lp.columns
]

if missing_user_cols:
    raise ValueError(
        "Missing required LP fields: "
        + str(missing_user_cols)
    )

users = (
    lp[user_cols]
    .drop_duplicates("user_id")
    .copy()
)

print(
    "\nUser parameter columns verified:",
    len(user_cols)
)

# ============================================================
# 3. IMPORTANT:
#    REMOVE POSSIBLE DUPLICATE USER-LEVEL FIELDS FROM
#    MONTHLY DATA BEFORE MERGING
# ============================================================

duplicate_parameter_cols = [
    c for c in user_cols
    if c != "user_id" and c in monthly.columns
]

print(
    "\nUser-level fields already present in monthly data:"
)

if duplicate_parameter_cols:
    for c in duplicate_parameter_cols:
        print(" -", c)

    monthly_for_merge = monthly.drop(
        columns=duplicate_parameter_cols
    ).copy()

else:
    print("None")
    monthly_for_merge = monthly.copy()

# ============================================================
# 4. MERGE
# ============================================================

m = monthly_for_merge.merge(
    users,
    on="user_id",
    how="inner",
    validate="many_to_one"
)

print(
    "\nMerged shape:",
    m.shape
)

# ============================================================
# 5. VERIFY REQUIRED FIELDS AFTER MERGE
# ============================================================

required_after_merge = [
    "user_id",
    "simulation_month",
    "monthly_surplus_dynamic",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "investment_capacity_ratio"
]

missing_after_merge = [
    c for c in required_after_merge
    if c not in m.columns
]

if missing_after_merge:
    raise ValueError(
        "Required fields missing after merge: "
        + str(missing_after_merge)
    )

print("\nAll required merged fields verified.")

# ============================================================
# 6. RESTRICT TO USER-SPECIFIC HORIZONS
# ============================================================

mh = m[
    m["simulation_month"]
    <= m["goal_horizon_months"]
].copy()

print(
    "\nRows within user-specific horizons:",
    len(mh)
)

# ============================================================
# 7. NUMERIC CONVERSION
# ============================================================

numeric_fields = [
    "monthly_surplus_dynamic",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "investment_capacity_ratio",
    "target_amount",
    "goal_horizon_funding_actual"
]

for col in numeric_fields:

    mh[col] = pd.to_numeric(
        mh[col],
        errors="coerce"
    )

# Check missing values introduced
missing_check = (
    mh[numeric_fields]
    .isna()
    .sum()
)

print("\nMissing values after numeric conversion:")

print(
    missing_check[
        missing_check > 0
    ].to_string()
    if (missing_check > 0).any()
    else "None"
)

# ============================================================
# 8. DYNAMIC POSITIVE CASH FLOW
# ============================================================

mh["positive_cash_flow"] = (
    mh["monthly_surplus_dynamic"]
    .clip(lower=0)
)

# ============================================================
# 9. BASELINE POLICY
# ============================================================

# This is the EXACT funding rule verified in Step 5I.

mh["baseline_goal"] = (
    mh["positive_cash_flow"]
    * mh["goal_allocation_factor"]
)

# ============================================================
# 10. OPTIMIZATION-BOUNDARY GOAL
# ============================================================

# This represents the maximum amount that could be directed
# toward the goal if the allocation-factor policy were relaxed.

mh["unrestricted_goal"] = np.minimum(
    mh["positive_cash_flow"],
    mh["goal_specific_monthly_capacity"]
)

# ============================================================
# 11. INVESTMENT CAPACITY
# ============================================================

mh["investment_limit"] = (
    mh["positive_cash_flow"]
    * mh["investment_capacity_ratio"]
)

# ============================================================
# 12. AGGREGATE BY USER
# ============================================================

audit = (
    mh.groupby("user_id")
      .agg(
          baseline_goal_funding=(
              "baseline_goal",
              "sum"
          ),

          unrestricted_goal_funding=(
              "unrestricted_goal",
              "sum"
          ),

          total_positive_cash_flow=(
              "positive_cash_flow",
              "sum"
          ),

          total_investment_capacity=(
              "investment_limit",
              "sum"
          ),

          target_amount=(
              "target_amount",
              "first"
          ),

          actual_goal_funding=(
              "goal_horizon_funding_actual",
              "first"
          ),

          horizon=(
              "goal_horizon_months",
              "first"
          ),

          goal_factor=(
              "goal_allocation_factor",
              "first"
          ),

          goal_monthly_capacity=(
              "goal_specific_monthly_capacity",
              "first"
          ),

          investment_ratio=(
              "investment_capacity_ratio",
              "first"
          ),

          initial_savings=(
              "initial_savings",
              "first"
          ),

          initial_investment=(
              "initial_investment",
              "first"
          ),

          risk_score=(
              "risk_score",
              "first"
          ),

          risk_profile=(
              "risk_profile",
              "first"
          )
      )
      .reset_index()
)

print(
    "\nAggregated users:",
    len(audit)
)

# ============================================================
# 13. POLICY FEASIBILITY
# ============================================================

audit["policy_shortfall"] = (
    audit["target_amount"]
    - audit["baseline_goal_funding"]
).clip(lower=0)

audit["policy_feasible"] = (
    audit["baseline_goal_funding"]
    >= audit["target_amount"]
)

# ============================================================
# 14. OPTIMIZATION-BOUNDARY FEASIBILITY
# ============================================================

audit["optimization_shortfall"] = (
    audit["target_amount"]
    - audit["unrestricted_goal_funding"]
).clip(lower=0)

audit["optimization_feasible"] = (
    audit["unrestricted_goal_funding"]
    >= audit["target_amount"]
)

# ============================================================
# 15. ADDITIONAL POTENTIAL GOAL CAPACITY
# ============================================================

audit["additional_goal_capacity"] = (
    audit["unrestricted_goal_funding"]
    - audit["baseline_goal_funding"]
).clip(lower=0)

# ============================================================
# 16. FEASIBILITY SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("1. FEASIBILITY COMPARISON")
print("=" * 80)

policy_count = int(
    audit["policy_feasible"].sum()
)

optimization_count = int(
    audit["optimization_feasible"].sum()
)

additional_users = int(
    (
        (~audit["policy_feasible"])
        &
        audit["optimization_feasible"]
    ).sum()
)

print(
    "Policy-preserving feasible:",
    policy_count,
    "/",
    len(audit)
)

print(
    "Optimization-boundary feasible:",
    optimization_count,
    "/",
    len(audit)
)

print(
    "Additional potentially feasible users:",
    additional_users
)

# ============================================================
# 17. FUNDING COMPARISON
# ============================================================

print("\n" + "=" * 80)
print("2. FUNDING COMPARISON")
print("=" * 80)

print(
    audit[
        [
            "actual_goal_funding",
            "baseline_goal_funding",
            "unrestricted_goal_funding",
            "additional_goal_capacity",
            "target_amount"
        ]
    ]
    .describe()
    .to_string()
)

# ============================================================
# 18. BASELINE VALIDATION
# ============================================================

baseline_diff = (
    audit["actual_goal_funding"]
    - audit["baseline_goal_funding"]
).abs()

print("\n" + "=" * 80)
print("3. BASELINE VALIDATION")
print("=" * 80)

print(
    "Mean absolute difference:",
    baseline_diff.mean()
)

print(
    "Maximum absolute difference:",
    baseline_diff.max()
)

print(
    "Matches <= 1e-6:",
    int(
        (baseline_diff <= 1e-6).sum()
    ),
    "/",
    len(audit)
)

# ============================================================
# 19. ADDITIONAL CAPACITY
# ============================================================

print("\n" + "=" * 80)
print("4. ADDITIONAL GOAL CAPACITY")
print("=" * 80)

print(
    audit[
        "additional_goal_capacity"
    ]
    .describe()
    .to_string()
)

print(
    "\nUsers with additional goal capacity:",
    int(
        (
            audit["additional_goal_capacity"]
            > 1e-9
        ).sum()
    )
)

# ============================================================
# 20. RISK PROFILE
# ============================================================

print("\n" + "=" * 80)
print("5. COMPARISON BY RISK PROFILE")
print("=" * 80)

risk = (
    audit.groupby("risk_profile")
    .agg(
        users=("user_id", "count"),

        policy_feasible=(
            "policy_feasible",
            "sum"
        ),

        optimization_feasible=(
            "optimization_feasible",
            "sum"
        ),

        mean_baseline_funding=(
            "baseline_goal_funding",
            "mean"
        ),

        mean_unrestricted_funding=(
            "unrestricted_goal_funding",
            "mean"
        ),

        mean_additional_capacity=(
            "additional_goal_capacity",
            "mean"
        )
    )
    .reset_index()
)

risk["policy_feasibility_rate"] = (
    risk["policy_feasible"]
    / risk["users"]
)

risk["optimization_feasibility_rate"] = (
    risk["optimization_feasible"]
    / risk["users"]
)

print(
    risk.to_string(index=False)
)

# ============================================================
# 21. FINANCIAL SITUATION
# ============================================================

financial_map = (
    lp[
        [
            "user_id",
            "financial_situation"
        ]
    ]
    .drop_duplicates("user_id")
)

audit = audit.merge(
    financial_map,
    on="user_id",
    how="left",
    validate="one_to_one"
)

print("\n" + "=" * 80)
print("6. COMPARISON BY FINANCIAL SITUATION")
print("=" * 80)

financial = (
    audit.groupby("financial_situation")
    .agg(
        users=("user_id", "count"),

        policy_feasible=(
            "policy_feasible",
            "sum"
        ),

        optimization_feasible=(
            "optimization_feasible",
            "sum"
        ),

        mean_baseline_funding=(
            "baseline_goal_funding",
            "mean"
        ),

        mean_unrestricted_funding=(
            "unrestricted_goal_funding",
            "mean"
        ),

        mean_additional_capacity=(
            "additional_goal_capacity",
            "mean"
        )
    )
    .reset_index()
)

financial["policy_feasibility_rate"] = (
    financial["policy_feasible"]
    / financial["users"]
)

financial["optimization_feasibility_rate"] = (
    financial["optimization_feasible"]
    / financial["users"]
)

print(
    financial.to_string(index=False)
)

# ============================================================
# 22. REPRESENTATIVE USERS
# ============================================================

print("\n" + "=" * 80)
print("7. REPRESENTATIVE USERS")
print("=" * 80)

show_cols = [
    "user_id",
    "target_amount",
    "actual_goal_funding",
    "baseline_goal_funding",
    "unrestricted_goal_funding",
    "additional_goal_capacity",
    "policy_feasible",
    "optimization_feasible",
    "goal_factor",
    "investment_ratio",
    "risk_profile"
]

print(
    audit[
        show_cols
    ]
    .head(20)
    .to_string(index=False)
)

# ============================================================
# 23. FINAL DATA INTEGRITY CHECK
# ============================================================

print("\n" + "=" * 80)
print("8. FINAL DATA INTEGRITY CHECK")
print("=" * 80)

print(
    "Unique users:",
    audit["user_id"].nunique()
)

print(
    "Duplicate users:",
    audit["user_id"].duplicated().sum()
)

print(
    "NaN values:",
    int(audit.isna().sum().sum())
)

print(
    "Infinite values:",
    int(
        np.isinf(
            audit.select_dtypes(
                include=np.number
            )
        ).sum().sum()
    )
)

# ============================================================
# 24. SAVE
# ============================================================

audit_path = os.path.join(
    OUT_DIR,
    "lp_5l2_policy_vs_optimization_audit.csv"
)

risk_path = os.path.join(
    OUT_DIR,
    "lp_5l2_risk_comparison.csv"
)

financial_path = os.path.join(
    OUT_DIR,
    "lp_5l2_financial_comparison.csv"
)

audit.to_csv(
    audit_path,
    index=False
)

risk.to_csv(
    risk_path,
    index=False
)

financial.to_csv(
    financial_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5L.2 COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(risk_path)
print(financial_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")

================================================================================
STEP 5L.2 — CORRECTED POLICY VS OPTIMIZATION LP AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 47)

User parameter columns verified: 11

User-level fields already present in monthly data:
 - investment_capacity_ratio
 - initial_savings
 - initial_investment
 - risk_score
 - risk_profile

Merged shape: (1430000, 52)

All required merged fields verified.

Rows within user-specific horizons: 626970

Missing values after numeric conversion:
None

Aggregated users: 10000

================================================================================
1. FEASIBILITY COMPARISON
================================================================================
Policy-preserving feasible: 6451 / 10000
Optimization-boundary feasible: 5963 / 10000
Additional potentially feasible users: 0

================================================================================
2. FUNDING COMPARISON
================================================================================
       actual_goal_funding  baseline_goal_funding  unrestricted_goal_funding  additional_goal_capacity  target_amount
count         1.000000e+04           1.000000e+04               1.000000e+04                   10000.0   1.000000e+04
mean          9.449648e+05           9.449648e+05               6.631026e+05                       0.0   1.383538e+05
std           2.156857e+06           2.156857e+06               1.440565e+06                       0.0   1.211024e+05
min           0.000000e+00           0.000000e+00               0.000000e+00                       0.0   2.824526e+03
25%           2.676139e+04           2.676139e+04               1.226529e+04                       0.0   7.189787e+04
50%           2.364985e+05           2.364985e+05               1.726636e+05                       0.0   1.073131e+05
75%           9.683717e+05           9.683717e+05               7.077399e+05                       0.0   1.595261e+05
max           6.659288e+07           6.659288e+07               4.374750e+07                       0.0   1.900464e+06

================================================================================
3. BASELINE VALIDATION
================================================================================
Mean absolute difference: 2.7003985403339926e-11
Maximum absolute difference: 3.725290298461914e-09
Matches <= 1e-6: 10000 / 10000

================================================================================
4. ADDITIONAL GOAL CAPACITY
================================================================================
count    10000.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0

Users with additional goal capacity: 0

================================================================================
5. COMPARISON BY RISK PROFILE
================================================================================
risk_profile  users  policy_feasible  optimization_feasible  mean_baseline_funding  mean_unrestricted_funding  mean_additional_capacity  policy_feasibility_rate  optimization_feasibility_rate
  aggressive   3333             3197                   3181           1.898103e+06               1.375637e+06                       0.0                 0.959196                       0.954395
conservative   3333              721                    418           1.362033e+05               6.314548e+04                       0.0                 0.216322                       0.125413
    moderate   3334             2533                   2364           8.006316e+05               5.505595e+05                       0.0                 0.759748                       0.709058

================================================================================
6. COMPARISON BY FINANCIAL SITUATION
================================================================================
financial_situation  users  policy_feasible  optimization_feasible  mean_baseline_funding  mean_unrestricted_funding  mean_additional_capacity  policy_feasibility_rate  optimization_feasibility_rate
   financial_stress    474                0                      0           3.172216e+03               2.369478e+03                       0.0                 0.000000                       0.000000
        high_saving   2043             1998                   1995           2.450276e+06               1.738169e+06                       0.0                 0.977974                       0.976505
         low_saving   2923              944                    794           1.738092e+05               1.233606e+05                       0.0                 0.322956                       0.271639
    moderate_saving   4560             3509                   3174           8.627601e+05               5.961054e+05                       0.0                 0.769518                       0.696053

================================================================================
7. REPRESENTATIVE USERS
================================================================================
   user_id  target_amount  actual_goal_funding  baseline_goal_funding  unrestricted_goal_funding  additional_goal_capacity  policy_feasible  optimization_feasible  goal_factor  investment_ratio risk_profile
USER_00001  115357.183592         5.811302e+05           5.811302e+05               4.849741e+05                       0.0             True                   True      0.69770          0.282005   aggressive
USER_00002   59340.387689         0.000000e+00           0.000000e+00               0.000000e+00                       0.0            False                  False      0.10655          0.000000 conservative
USER_00003   99893.237726         4.093773e+04           4.093773e+04               3.442674e+04                       0.0            False                  False      0.30330          0.055491     moderate
USER_00004   75476.307623         4.566919e+04           4.566919e+04               1.532223e+04                       0.0            False                  False      0.24420          0.031125 conservative
USER_00005  206040.342056         7.318348e+06           7.318348e+06               4.601411e+06                       0.0             True                   True      0.94170          0.443954   aggressive
USER_00006  110291.964774         3.502230e+05           3.502230e+05               3.274178e+05                       0.0             True                   True      0.82320          0.450063   aggressive
USER_00007  128020.414837         2.348219e+06           2.348219e+06               1.764231e+06                       0.0             True                   True      0.87160          0.473577   aggressive
USER_00008  269916.171830         0.000000e+00           0.000000e+00               0.000000e+00                       0.0            False                  False      0.10655          0.000000 conservative
USER_00009  182600.732773         1.616717e+06           1.616717e+06               1.312933e+06                       0.0             True                   True      0.87490          0.335670   aggressive
USER_00010   96702.526658         5.423986e+04           5.423986e+04               4.959178e+04                       0.0            False                  False      0.40940          0.117248     moderate
USER_00011   39905.117099         1.746970e+05           1.746970e+05               1.491838e+05                       0.0             True                   True      0.48900          0.408910   aggressive
USER_00012  153722.614222         0.000000e+00           0.000000e+00               0.000000e+00                       0.0            False                  False      0.10655          0.000000 conservative
USER_00013   75699.850293         0.000000e+00           0.000000e+00               0.000000e+00                       0.0            False                  False      0.10655          0.000000 conservative
USER_00014   56999.623650         1.429149e+05           1.429149e+05               6.460845e+04                       0.0             True                   True      0.30130          0.096035 conservative
USER_00015  294810.384238         7.737681e+06           7.737681e+06               4.912835e+06                       0.0             True                   True      0.96040          0.371228     moderate
USER_00016  164062.774110         8.506991e+05           8.506991e+05               7.548385e+05                       0.0             True                   True      0.87260          0.370145   aggressive
USER_00017   67605.333513         3.423747e+04           3.423747e+04               3.269856e+04                       0.0            False                  False      0.44710          0.202514   aggressive
USER_00018  230098.662301         1.637618e+06           1.637618e+06               1.278896e+06                       0.0             True                   True      0.83980          0.228731   aggressive
USER_00019   78326.115793         3.179076e+05           3.179076e+05               2.746307e+05                       0.0             True                   True      0.61950          0.326009   aggressive
USER_00020   89316.160080         4.044024e+05           4.044024e+05               2.543172e+05                       0.0             True                   True      0.47910          0.175671     moderate

================================================================================
8. FINAL DATA INTEGRITY CHECK
================================================================================
Unique users: 10000
Duplicate users: 0
NaN values: 0
Infinite values: 0

================================================================================
STEP 5L.2 COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l2_policy_vs_optimization_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l2_risk_comparison.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5l2_financial_comparison.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.

In [103]:
# ============================================================
# GOALPILOT AI — STEP 5M
# INVESTMENT ALLOCATION & GOAL/INVESTMENT TRADE-OFF AUDIT
# ============================================================

import os
import pandas as pd
import numpy as np

print("=" * 80)
print("STEP 5M — INVESTMENT ALLOCATION & GOAL/INVESTMENT TRADE-OFF AUDIT")
print("=" * 80)

BASE_DIR = "/content/drive/MyDrive/GoalPilot_AI"

LP_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_FILE = os.path.join(
    BASE_DIR,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

OUT_DIR = os.path.join(
    BASE_DIR,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT_DIR, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD
# ------------------------------------------------------------

lp = pd.read_csv(LP_FILE)
monthly = pd.read_csv(MONTHLY_FILE)

monthly["period"] = pd.to_datetime(
    monthly["period"],
    errors="coerce"
)

monthly = monthly.sort_values(
    ["user_id", "period"]
)

monthly["simulation_month"] = (
    monthly.groupby("user_id").cumcount() + 1
)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# ------------------------------------------------------------
# 2. VERIFY USER PARAMETERS
# ------------------------------------------------------------

user_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "investment_capacity_ratio",
    "initial_savings",
    "initial_investment",
    "risk_score",
    "risk_profile"
]

users = (
    lp[user_cols]
    .drop_duplicates("user_id")
    .copy()
)

# ------------------------------------------------------------
# 3. REMOVE DUPLICATE PARAMETER FIELDS FROM MONTHLY DATA
# ------------------------------------------------------------

duplicate_cols = [
    c for c in user_cols
    if c != "user_id" and c in monthly.columns
]

monthly_for_merge = monthly.drop(
    columns=duplicate_cols,
    errors="ignore"
).copy()

# ------------------------------------------------------------
# 4. MERGE
# ------------------------------------------------------------

m = monthly_for_merge.merge(
    users,
    on="user_id",
    how="inner",
    validate="many_to_one"
)

mh = m[
    m["simulation_month"]
    <= m["goal_horizon_months"]
].copy()

print(
    "\nRows within user-specific horizons:",
    len(mh)
)

# ------------------------------------------------------------
# 5. DYNAMIC CASH FLOW
# ------------------------------------------------------------

mh["monthly_surplus_dynamic"] = pd.to_numeric(
    mh["monthly_surplus_dynamic"],
    errors="coerce"
).fillna(0)

mh["positive_cash_flow"] = (
    mh["monthly_surplus_dynamic"]
    .clip(lower=0)
)

mh["goal_allocation_factor"] = pd.to_numeric(
    mh["goal_allocation_factor"],
    errors="coerce"
).fillna(0)

mh["investment_capacity_ratio"] = pd.to_numeric(
    mh["investment_capacity_ratio"],
    errors="coerce"
).fillna(0)

# ------------------------------------------------------------
# 6. EXISTING GOAL ALLOCATION
# ------------------------------------------------------------

mh["existing_goal_allocation"] = (
    mh["positive_cash_flow"]
    * mh["goal_allocation_factor"]
)

# ------------------------------------------------------------
# 7. INVESTMENT CAPACITY
# ------------------------------------------------------------

mh["investment_capacity"] = (
    mh["positive_cash_flow"]
    * mh["investment_capacity_ratio"]
)

# ------------------------------------------------------------
# 8. CASH LEFT AFTER EXISTING GOAL ALLOCATION
# ------------------------------------------------------------

mh["cash_after_goal"] = (
    mh["positive_cash_flow"]
    - mh["existing_goal_allocation"]
)

# ------------------------------------------------------------
# 9. POTENTIAL INVESTMENT FROM REMAINING CASH
# ------------------------------------------------------------

mh["investment_capacity_from_remaining"] = np.minimum(
    mh["cash_after_goal"].clip(lower=0),
    mh["investment_capacity"]
)

# ------------------------------------------------------------
# 10. RESIDUAL CASH AFTER GOAL + INVESTMENT CAPACITY
# ------------------------------------------------------------

mh["residual_cash"] = (
    mh["positive_cash_flow"]
    - mh["existing_goal_allocation"]
    - mh["investment_capacity_from_remaining"]
)

# ------------------------------------------------------------
# 11. ALLOCATION RATIOS
# ------------------------------------------------------------

mh["goal_share_of_positive_cash"] = np.where(
    mh["positive_cash_flow"] > 0,
    mh["existing_goal_allocation"]
    / mh["positive_cash_flow"],
    0
)

mh["investment_share_of_positive_cash"] = np.where(
    mh["positive_cash_flow"] > 0,
    mh["investment_capacity_from_remaining"]
    / mh["positive_cash_flow"],
    0
)

mh["residual_share_of_positive_cash"] = np.where(
    mh["positive_cash_flow"] > 0,
    mh["residual_cash"]
    / mh["positive_cash_flow"],
    0
)

# ------------------------------------------------------------
# 12. USER-LEVEL AGGREGATION
# ------------------------------------------------------------

audit = (
    mh.groupby("user_id")
    .agg(
        total_positive_cash_flow=(
            "positive_cash_flow",
            "sum"
        ),

        existing_goal_funding=(
            "existing_goal_allocation",
            "sum"
        ),

        total_investment_capacity=(
            "investment_capacity",
            "sum"
        ),

        investment_capacity_from_remaining=(
            "investment_capacity_from_remaining",
            "sum"
        ),

        total_residual_cash=(
            "residual_cash",
            "sum"
        ),

        mean_goal_share=(
            "goal_share_of_positive_cash",
            "mean"
        ),

        mean_investment_share=(
            "investment_share_of_positive_cash",
            "mean"
        ),

        mean_residual_share=(
            "residual_share_of_positive_cash",
            "mean"
        ),

        target_amount=(
            "target_amount",
            "first"
        ),

        horizon=(
            "goal_horizon_months",
            "first"
        ),

        goal_factor=(
            "goal_allocation_factor",
            "first"
        ),

        investment_ratio=(
            "investment_capacity_ratio",
            "first"
        ),

        initial_savings=(
            "initial_savings",
            "first"
        ),

        initial_investment=(
            "initial_investment",
            "first"
        ),

        risk_score=(
            "risk_score",
            "first"
        ),

        risk_profile=(
            "risk_profile",
            "first"
        )
    )
    .reset_index()
)

# ------------------------------------------------------------
# 13. CHECK EXISTING GOAL FORMULA
# ------------------------------------------------------------

goal_formula_diff = (
    audit["existing_goal_funding"]
    -
    (
        audit["total_positive_cash_flow"]
        * audit["goal_factor"]
    )
).abs()

print("\n" + "=" * 80)
print("1. EXISTING GOAL FORMULA RECHECK")
print("=" * 80)

print(
    "Mean absolute difference:",
    goal_formula_diff.mean()
)

print(
    "Maximum absolute difference:",
    goal_formula_diff.max()
)

print(
    "Matches <= 1e-6:",
    int(
        (goal_formula_diff <= 1e-6).sum()
    ),
    "/",
    len(audit)
)

# ------------------------------------------------------------
# 14. GOAL / INVESTMENT / RESIDUAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("2. GOAL / INVESTMENT / RESIDUAL CASH")
print("=" * 80)

summary_cols = [
    "total_positive_cash_flow",
    "existing_goal_funding",
    "total_investment_capacity",
    "investment_capacity_from_remaining",
    "total_residual_cash"
]

print(
    audit[summary_cols]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 15. USER-LEVEL ALLOCATION SHARES
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("3. ALLOCATION SHARES")
print("=" * 80)

share_cols = [
    "mean_goal_share",
    "mean_investment_share",
    "mean_residual_share"
]

print(
    audit[share_cols]
    .describe()
    .to_string()
)

# ------------------------------------------------------------
# 16. CHECK WHETHER GOAL + INVESTMENT EXCEEDS CASH
# ------------------------------------------------------------

audit["goal_plus_investment_ratio"] = (
    audit["mean_goal_share"]
    + audit["mean_investment_share"]
)

print("\n" + "=" * 80)
print("4. ALLOCATION CONSISTENCY")
print("=" * 80)

print(
    "Users where mean goal + investment share > 1:",
    int(
        (
            audit["goal_plus_investment_ratio"]
            > 1 + 1e-9
        ).sum()
    )
)

print(
    "Users where residual cash is negative:",
    int(
        (
            audit["total_residual_cash"]
            < -1e-9
        ).sum()
    )
)

# ------------------------------------------------------------
# 17. RELATIONSHIP BETWEEN GOAL FACTOR AND INVESTMENT RATIO
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("5. GOAL FACTOR VS INVESTMENT CAPACITY")
print("=" * 80)

relationship = (
    audit[
        [
            "goal_factor",
            "investment_ratio",
            "risk_score",
            "mean_goal_share",
            "mean_investment_share",
            "mean_residual_share"
        ]
    ]
    .corr()
)

print(
    relationship.to_string()
)

# ------------------------------------------------------------
# 18. GOAL + INVESTMENT FACTOR SUM
# ------------------------------------------------------------

audit["factor_sum"] = (
    audit["goal_factor"]
    + audit["investment_ratio"]
)

audit["factor_remaining"] = (
    1
    - audit["factor_sum"]
)

print("\n" + "=" * 80)
print("6. GOAL FACTOR + INVESTMENT RATIO")
print("=" * 80)

print(
    audit[
        [
            "goal_factor",
            "investment_ratio",
            "factor_sum",
            "factor_remaining"
        ]
    ]
    .describe()
    .to_string()
)

print(
    "\nUsers where goal factor + investment ratio > 1:",
    int(
        (
            audit["factor_sum"]
            > 1 + 1e-9
        ).sum()
    )
)

# ------------------------------------------------------------
# 19. RISK PROFILE
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("7. ALLOCATION BY RISK PROFILE")
print("=" * 80)

risk = (
    audit.groupby("risk_profile")
    .agg(
        users=("user_id", "count"),

        mean_goal_factor=(
            "goal_factor",
            "mean"
        ),

        mean_investment_ratio=(
            "investment_ratio",
            "mean"
        ),

        mean_goal_share=(
            "mean_goal_share",
            "mean"
        ),

        mean_investment_share=(
            "mean_investment_share",
            "mean"
        ),

        mean_residual_share=(
            "mean_residual_share",
            "mean"
        ),

        mean_initial_investment=(
            "initial_investment",
            "mean"
        )
    )
    .reset_index()
)

print(
    risk.to_string(index=False)
)

# ------------------------------------------------------------
# 20. FINANCIAL SITUATION
# ------------------------------------------------------------

financial_map = lp[
    [
        "user_id",
        "financial_situation"
    ]
].drop_duplicates("user_id")

audit = audit.merge(
    financial_map,
    on="user_id",
    how="left",
    validate="one_to_one"
)

print("\n" + "=" * 80)
print("8. ALLOCATION BY FINANCIAL SITUATION")
print("=" * 80)

financial = (
    audit.groupby("financial_situation")
    .agg(
        users=("user_id", "count"),

        mean_goal_factor=(
            "goal_factor",
            "mean"
        ),

        mean_investment_ratio=(
            "investment_ratio",
            "mean"
        ),

        mean_goal_share=(
            "mean_goal_share",
            "mean"
        ),

        mean_investment_share=(
            "mean_investment_share",
            "mean"
        ),

        mean_residual_share=(
            "mean_residual_share",
            "mean"
        )
    )
    .reset_index()
)

print(
    financial.to_string(index=False)
)

# ------------------------------------------------------------
# 21. REPRESENTATIVE USERS
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("9. REPRESENTATIVE USERS")
print("=" * 80)

show_cols = [
    "user_id",
    "total_positive_cash_flow",
    "existing_goal_funding",
    "total_investment_capacity",
    "investment_capacity_from_remaining",
    "total_residual_cash",
    "goal_factor",
    "investment_ratio",
    "factor_sum",
    "initial_investment",
    "risk_profile"
]

print(
    audit[show_cols]
    .head(20)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 22. SAVE
# ------------------------------------------------------------

audit_path = os.path.join(
    OUT_DIR,
    "lp_5m_investment_tradeoff_audit.csv"
)

risk_path = os.path.join(
    OUT_DIR,
    "lp_5m_investment_tradeoff_by_risk.csv"
)

financial_path = os.path.join(
    OUT_DIR,
    "lp_5m_investment_tradeoff_by_financial_situation.csv"
)

audit.to_csv(
    audit_path,
    index=False
)

risk.to_csv(
    risk_path,
    index=False
)

financial.to_csv(
    financial_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5M COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(risk_path)
print(financial_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5M — INVESTMENT ALLOCATION & GOAL/INVESTMENT TRADE-OFF AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 47)

Rows within user-specific horizons: 626970

================================================================================
1. EXISTING GOAL FORMULA RECHECK
================================================================================
Mean absolute difference: 3.757690536509983e-11
Maximum absolute difference: 7.450580596923828e-09
Matches <= 1e-6: 10000 / 10000

================================================================================
2. GOAL / INVESTMENT / RESIDUAL CASH
================================================================================
       total_positive_cash_flow  existing_goal_funding  total_investment_capacity  investment_capacity_from_remaining  total_residual_cash
count              1.000000e+04           1.000000e+04               1.000000e+04                        1.000000e+04         1.000000e+04
mean               1.189898e+06           9.449648e+05               3.693822e+05                        1.470168e+05         9.791616e+04
std                2.213899e+06           2.156857e+06               8.918388e+05                        1.859875e+05         1.678367e+05
min                0.000000e+00           0.000000e+00               0.000000e+00                        0.000000e+00         0.000000e+00
25%                9.665485e+04           2.676139e+04               3.856983e+03                        3.839146e+03         0.000000e+00
50%                4.777859e+05           2.364985e+05               8.307965e+04                        6.484337e+04         1.839285e+04
75%                1.440379e+06           9.683717e+05               3.793661e+05                        2.278814e+05         1.374892e+05
max                6.659288e+07           6.659288e+07               3.176700e+07                        1.010465e+06         3.149198e+06

================================================================================
3. ALLOCATION SHARES
================================================================================
       mean_goal_share  mean_investment_share  mean_residual_share
count     10000.000000           10000.000000         10000.000000
mean          0.481226               0.128145             0.213957
std           0.314454               0.107937             0.255474
min           0.000000               0.000000             0.000000
25%           0.250075               0.019321             0.000000
50%           0.500050               0.114808             0.083183
75%           0.750025               0.215260             0.413403
max           1.000000               0.486505             0.893450

================================================================================
4. ALLOCATION CONSISTENCY
================================================================================
Users where mean goal + investment share > 1: 0
Users where residual cash is negative: 0

================================================================================
5. GOAL FACTOR VS INVESTMENT CAPACITY
================================================================================
                       goal_factor  investment_ratio  risk_score  mean_goal_share  mean_investment_share  mean_residual_share
goal_factor               1.000000          0.873911    0.829873         0.995622               0.455981            -0.470826
investment_ratio          0.873911          1.000000    0.913235         0.873594               0.641336            -0.477838
risk_score                0.829873          0.913235    1.000000         0.846177               0.665469            -0.306241
mean_goal_share           0.995622          0.873594    0.846177         1.000000               0.487671            -0.392821
mean_investment_share     0.455981          0.641336    0.665469         0.487671               1.000000            -0.201651
mean_residual_share      -0.470826         -0.477838   -0.306241        -0.392821              -0.201651             1.000000

================================================================================
6. GOAL FACTOR + INVESTMENT RATIO
================================================================================
        goal_factor  investment_ratio    factor_sum  factor_remaining
count  10000.000000      10000.000000  10000.000000      10000.000000
mean       0.500050          0.187228      0.687278          0.312722
std        0.287291          0.149113      0.423847          0.423847
min        0.106550          0.000000      0.106550         -0.491413
25%        0.250075          0.036815      0.300598         -0.052956
50%        0.500050          0.189573      0.708155          0.291845
75%        0.750025          0.306529      1.052956          0.699402
max        1.000000          0.499976      1.491413          0.893450

Users where goal factor + investment ratio > 1: 2865

================================================================================
7. ALLOCATION BY RISK PROFILE
================================================================================
risk_profile  users  mean_goal_factor  mean_investment_ratio  mean_goal_share  mean_investment_share  mean_residual_share  mean_initial_investment
  aggressive   3333          0.746799               0.344191         0.746799               0.196449             0.056753            114485.540659
conservative   3333          0.209046               0.029605         0.153973               0.029341             0.299816             15961.616749
    moderate   3334          0.544293               0.187888         0.542886               0.158636             0.285280             40463.399131

================================================================================
8. ALLOCATION BY FINANCIAL SITUATION
================================================================================
financial_situation  users  mean_goal_factor  mean_investment_ratio  mean_goal_share  mean_investment_share  mean_residual_share
   financial_stress    474          0.124669               0.003352         0.031607               0.003352             0.091623
        high_saving   2043          0.803956               0.385517         0.803956               0.171876             0.024168
         low_saving   2923          0.271973               0.061403         0.226754               0.060588             0.288259
    moderate_saving   4560          0.549111               0.198158         0.546489               0.164829             0.264075

================================================================================
9. REPRESENTATIVE USERS
================================================================================
   user_id  total_positive_cash_flow  existing_goal_funding  total_investment_capacity  investment_capacity_from_remaining  total_residual_cash  goal_factor  investment_ratio  factor_sum  initial_investment risk_profile
USER_00001              8.329228e+05           5.811302e+05               2.348884e+05                       234888.427079         16904.135588      0.69770          0.282005    0.979705        45777.548120   aggressive
USER_00002              0.000000e+00           0.000000e+00               0.000000e+00                            0.000000             0.000000      0.10655          0.000000    0.106550            0.000000 conservative
USER_00003              1.349744e+05           4.093773e+04               7.489862e+03                         7489.862070         86546.784224      0.30330          0.055491    0.358791            0.000000     moderate
USER_00004              1.870155e+05           4.566919e+04               5.820830e+03                         5820.830240        135525.501255      0.24420          0.031125    0.275325        60534.274631 conservative
USER_00005              7.771422e+06           7.318348e+06               3.450153e+06                       453073.892390             0.000000      0.94170          0.443954    1.385654       105774.934379   aggressive
USER_00006              4.254410e+05           3.502230e+05               1.914753e+05                        75217.972356             0.000000      0.82320          0.450063    1.273263       118987.882781   aggressive
USER_00007              2.694147e+06           2.348219e+06               1.275886e+06                       345928.474554             0.000000      0.87160          0.473577    1.345177        90329.680595   aggressive
USER_00008              0.000000e+00           0.000000e+00               0.000000e+00                            0.000000             0.000000      0.10655          0.000000    0.106550            0.000000 conservative
USER_00009              1.847887e+06           1.616717e+06               6.202795e+05                       231170.704431             0.000000      0.87490          0.335670    1.210570            0.000000   aggressive
USER_00010              1.324862e+05           5.423986e+04               1.553375e+04                        15533.753316         62712.609847      0.40940          0.117248    0.526648        15171.499059     moderate
USER_00011              3.572536e+05           1.746970e+05               1.460846e+05                       146084.561370         36472.018205      0.48900          0.408910    0.897910        40453.563484   aggressive
USER_00012              0.000000e+00           0.000000e+00               0.000000e+00                            0.000000             0.000000      0.10655          0.000000    0.106550         8515.989852 conservative
USER_00013              0.000000e+00           0.000000e+00               0.000000e+00                            0.000000             0.000000      0.10655          0.000000    0.106550        16162.918447 conservative
USER_00014              4.743276e+05           1.429149e+05               4.555194e+04                        45551.935208        285860.764568      0.30130          0.096035    0.397335        14401.269590 conservative
USER_00015              8.056727e+06           7.737681e+06               2.990883e+06                       319046.387876             0.000000      0.96040          0.371228    1.331628       198355.872839     moderate
USER_00016              9.749015e+05           8.506991e+05               3.608548e+05                       124202.452709             0.000000      0.87260          0.370145    1.242745       225494.049270   aggressive
USER_00017              7.657675e+04           3.423747e+04               1.550785e+04                        15507.847602         26831.437889      0.44710          0.202514    0.649614        41652.757168   aggressive
USER_00018              1.950010e+06           1.637618e+06               4.460277e+05                       312391.608502             0.000000      0.83980          0.228731    1.068531            0.000000   aggressive
USER_00019              5.131680e+05           3.179076e+05               1.672973e+05                       167297.338088         27963.101480      0.61950          0.326009    0.945509        33043.600346   aggressive
USER_00020              8.440876e+05           4.044024e+05               1.482813e+05                       148281.300252        291403.951456      0.47910          0.175671    0.654771        67196.936642     moderate

================================================================================
STEP 5M COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5m_investment_tradeoff_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5m_investment_tradeoff_by_risk.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5m_investment_tradeoff_by_financial_situation.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO OBJECTIVE FUNCTION WAS ASSUMED.

In [104]:
import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

# -------------------------------------------------------------------------
# 1. LOAD DATA
# -------------------------------------------------------------------------

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("=" * 80)
print("STEP 5N — ACTUAL INVESTMENT / PORTFOLIO EVOLUTION AUDIT")
print("=" * 80)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# -------------------------------------------------------------------------
# 2. CHECK REQUIRED COLUMNS
# -------------------------------------------------------------------------

required_lp = [
    "user_id",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months"
]

required_monthly = [
    "user_id",
    "period",
    "portfolio_value",
    "portfolio_return",
    "initial_investment"
]

missing_lp = [c for c in required_lp if c not in lp.columns]
missing_monthly = [c for c in required_monthly if c not in monthly.columns]

print("\nMissing LP columns:", missing_lp)
print("Missing monthly columns:", missing_monthly)

if missing_lp or missing_monthly:
    raise ValueError("Required columns are missing. Stop here and inspect the output.")

# -------------------------------------------------------------------------
# 3. PREPARE DATA
# -------------------------------------------------------------------------

lp_small = lp[required_lp].copy()

monthly_small = monthly[
    [
        "user_id",
        "period",
        "portfolio_value",
        "portfolio_return",
        "initial_investment"
    ]
].copy()

for c in ["portfolio_value", "portfolio_return", "initial_investment"]:
    monthly_small[c] = pd.to_numeric(
        monthly_small[c],
        errors="coerce"
    )

lp_small["initial_investment"] = pd.to_numeric(
    lp_small["initial_investment"],
    errors="coerce"
)

lp_small["goal_horizon_months"] = pd.to_numeric(
    lp_small["goal_horizon_months"],
    errors="coerce"
)

monthly_small["period"] = pd.to_datetime(
    monthly_small["period"],
    errors="coerce"
)

monthly_small = monthly_small.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# -------------------------------------------------------------------------
# 4. BASIC DATA QUALITY
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("1. DATA QUALITY")
print("=" * 80)

print("LP users:", lp_small["user_id"].nunique())
print("Monthly users:", monthly_small["user_id"].nunique())

print("Monthly duplicate user-period rows:",
      monthly_small.duplicated(
          ["user_id", "period"]
      ).sum())

print("Missing portfolio_value:",
      monthly_small["portfolio_value"].isna().sum())

print("Missing portfolio_return:",
      monthly_small["portfolio_return"].isna().sum())

print("Missing initial_investment:",
      monthly_small["initial_investment"].isna().sum())

# -------------------------------------------------------------------------
# 5. CHECK STARTING PORTFOLIO VALUE AGAINST INITIAL INVESTMENT
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. INITIAL INVESTMENT vs FIRST PORTFOLIO VALUE")
print("=" * 80)

first_rows = (
    monthly_small
    .sort_values(["user_id", "period"])
    .groupby("user_id", as_index=False)
    .first()
)

first_compare = lp_small[
    ["user_id", "initial_investment"]
].merge(
    first_rows[
        ["user_id", "period", "portfolio_value", "portfolio_return",
         "initial_investment"]
    ],
    on="user_id",
    how="inner",
    suffixes=["_lp", "_monthly"]
)

first_compare["difference_lp_vs_first_portfolio"] = (
    first_compare["portfolio_value"]
    - first_compare["initial_investment_lp"]
)

first_compare["abs_difference"] = (
    first_compare["difference_lp_vs_first_portfolio"].abs()
)

print("\nFirst monthly portfolio value vs LP initial investment:")
print(
    first_compare["abs_difference"].describe()
)

print(
    "\nExact/near-exact matches <= 1e-6:",
    (
        first_compare["abs_difference"] <= 1e-6
    ).sum(),
    "/",
    len(first_compare)
)

# -------------------------------------------------------------------------
# 6. RECONSTRUCT PORTFOLIO VALUE USING RETURN
#
# If:
# portfolio_t = portfolio_(t-1) * (1 + return_t)
#
# then this tests whether portfolio_return alone explains portfolio_value.
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. PORTFOLIO RETURN RECONSTRUCTION")
print("=" * 80)

m = monthly_small.copy()

m["previous_portfolio_value"] = (
    m.groupby("user_id")["portfolio_value"]
    .shift(1)
)

m["return_implied_portfolio"] = (
    m["previous_portfolio_value"]
    * (1 + m["portfolio_return"])
)

# First month has no previous portfolio value
m["portfolio_reconstruction_error"] = (
    m["portfolio_value"]
    - m["return_implied_portfolio"]
)

m["abs_reconstruction_error"] = (
    m["portfolio_reconstruction_error"].abs()
)

valid_reconstruction = m[
    m["previous_portfolio_value"].notna()
    & m["portfolio_return"].notna()
    & m["portfolio_value"].notna()
].copy()

print("\nValid month-to-month observations:",
      len(valid_reconstruction))

print(
    "\nAbsolute reconstruction error:"
)

print(
    valid_reconstruction[
        "abs_reconstruction_error"
    ].describe()
)

print(
    "\nMatches <= 1e-6:",
    (
        valid_reconstruction[
            "abs_reconstruction_error"
        ] <= 1e-6
    ).sum(),
    "/",
    len(valid_reconstruction)
)

# -------------------------------------------------------------------------
# 7. ESTIMATE WHETHER THERE IS AN UNEXPLAINED CHANGE
#
# residual_change =
# actual portfolio_t
# - previous portfolio_t * (1 + return_t)
#
# If this is consistently non-zero, it may represent contributions,
# withdrawals, fees, or another portfolio mechanism.
# We DO NOT label it as contribution yet.
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. UNEXPLAINED PORTFOLIO CHANGE")
print("=" * 80)

valid_reconstruction["unexplained_change"] = (
    valid_reconstruction["portfolio_value"]
    -
    (
        valid_reconstruction["previous_portfolio_value"]
        * (1 + valid_reconstruction["portfolio_return"])
    )
)

valid_reconstruction["abs_unexplained_change"] = (
    valid_reconstruction["unexplained_change"].abs()
)

print(
    "\nUnexplained change statistics:"
)

print(
    valid_reconstruction[
        "unexplained_change"
    ].describe()
)

print(
    "\nAbsolute unexplained change statistics:"
)

print(
    valid_reconstruction[
        "abs_unexplained_change"
    ].describe()
)

# -------------------------------------------------------------------------
# 8. COUNT MONTHS WITH MATERIAL UNEXPLAINED CHANGE
# -------------------------------------------------------------------------

threshold = 1e-6

material_change = (
    valid_reconstruction[
        "abs_unexplained_change"
    ] > threshold
)

print(
    "\nObservations with unexplained change > 1e-6:",
    material_change.sum(),
    "/",
    len(valid_reconstruction)
)

# -------------------------------------------------------------------------
# 9. USER-LEVEL PORTFOLIO SUMMARY
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. USER-LEVEL PORTFOLIO SUMMARY")
print("=" * 80)

portfolio_summary = (
    monthly_small
    .groupby("user_id")
    .agg(
        months=("period", "count"),
        first_portfolio_value=("portfolio_value", "first"),
        final_portfolio_value=("portfolio_value", "last"),
        minimum_portfolio_value=("portfolio_value", "min"),
        maximum_portfolio_value=("portfolio_value", "max"),
        mean_portfolio_value=("portfolio_value", "mean"),
        mean_portfolio_return=("portfolio_return", "mean"),
        min_portfolio_return=("portfolio_return", "min"),
        max_portfolio_return=("portfolio_return", "max")
    )
    .reset_index()
)

portfolio_summary = portfolio_summary.merge(
    lp_small[
        [
            "user_id",
            "initial_investment",
            "investment_capacity_ratio",
            "risk_score",
            "risk_profile",
            "goal_horizon_months"
        ]
    ],
    on="user_id",
    how="left"
)

portfolio_summary["final_minus_initial"] = (
    portfolio_summary["final_portfolio_value"]
    - portfolio_summary["initial_investment"]
)

portfolio_summary["portfolio_growth_ratio"] = np.where(
    portfolio_summary["initial_investment"] > 0,
    portfolio_summary["final_portfolio_value"]
    /
    portfolio_summary["initial_investment"],
    np.nan
)

print(
    portfolio_summary[
        [
            "first_portfolio_value",
            "initial_investment",
            "final_portfolio_value",
            "final_minus_initial",
            "portfolio_growth_ratio",
            "mean_portfolio_return"
        ]
    ].describe()
)

# -------------------------------------------------------------------------
# 10. CHECK WHETHER FIRST PORTFOLIO VALUE IS CONSISTENT WITH INITIAL STATE
# -------------------------------------------------------------------------

portfolio_summary["first_vs_initial_abs_diff"] = (
    portfolio_summary["first_portfolio_value"]
    - portfolio_summary["initial_investment"]
).abs()

print(
    "\nUsers with first portfolio value matching initial investment <= 1e-6:",
    (
        portfolio_summary["first_vs_initial_abs_diff"]
        <= 1e-6
    ).sum(),
    "/",
    len(portfolio_summary)
)

# -------------------------------------------------------------------------
# 11. RELATIONSHIP WITH INVESTMENT CAPACITY
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. INVESTMENT CAPACITY RELATIONSHIP")
print("=" * 80)

corr_columns = [
    "investment_capacity_ratio",
    "initial_investment",
    "final_portfolio_value",
    "final_minus_initial",
    "mean_portfolio_return",
    "risk_score"
]

print(
    portfolio_summary[
        corr_columns
    ].corr()
)

# -------------------------------------------------------------------------
# 12. REPRESENTATIVE USERS
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. REPRESENTATIVE USERS")
print("=" * 80)

representative_ids = [
    "USER_00001",
    "USER_00002",
    "USER_00003",
    "USER_00004",
    "USER_00005",
    "USER_00006",
    "USER_00007",
    "USER_00008",
    "USER_00009",
    "USER_00010"
]

rep = portfolio_summary[
    portfolio_summary["user_id"].isin(representative_ids)
].copy()

print(
    rep[
        [
            "user_id",
            "initial_investment",
            "first_portfolio_value",
            "final_portfolio_value",
            "final_minus_initial",
            "investment_capacity_ratio",
            "risk_score",
            "risk_profile",
            "months"
        ]
    ].to_string(index=False)
)

# -------------------------------------------------------------------------
# 13. SAVE AUDITS — NEW FILES ONLY
# -------------------------------------------------------------------------

OUTPUT_DIR = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

audit_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_actual_portfolio_evolution_audit.csv"
)

user_summary_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_actual_portfolio_user_summary.csv"
)

unexplained_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_unexplained_portfolio_change.csv"
)

first_compare_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_initial_investment_vs_first_portfolio.csv"
)

# Overall audit table
audit_rows = [
    ["lp_rows", len(lp_small)],
    ["monthly_rows", len(monthly_small)],
    ["lp_unique_users", lp_small["user_id"].nunique()],
    ["monthly_unique_users", monthly_small["user_id"].nunique()],
    [
        "monthly_duplicate_user_period_rows",
        monthly_small.duplicated(
            ["user_id", "period"]
        ).sum()
    ],
    [
        "first_portfolio_vs_initial_matches",
        (
            first_compare["abs_difference"] <= 1e-6
        ).sum()
    ],
    [
        "first_portfolio_vs_initial_mean_abs_diff",
        first_compare["abs_difference"].mean()
    ],
    [
        "return_reconstruction_valid_rows",
        len(valid_reconstruction)
    ],
    [
        "return_reconstruction_mean_abs_error",
        valid_reconstruction["abs_unexplained_change"].mean()
    ],
    [
        "return_reconstruction_max_abs_error",
        valid_reconstruction["abs_unexplained_change"].max()
    ],
    [
        "return_reconstruction_matches_1e-6",
        (
            valid_reconstruction[
                "abs_unexplained_change"
            ] <= 1e-6
        ).sum()
    ],
    [
        "material_unexplained_change_rows",
        material_change.sum()
    ]
]

pd.DataFrame(
    audit_rows,
    columns=["metric", "value"]
).to_csv(
    audit_path,
    index=False
)

portfolio_summary.to_csv(
    user_summary_path,
    index=False
)

valid_reconstruction[
    [
        "user_id",
        "period",
        "previous_portfolio_value",
        "portfolio_return",
        "portfolio_value",
        "unexplained_change",
        "abs_unexplained_change"
    ]
].to_csv(
    unexplained_path,
    index=False
)

first_compare.to_csv(
    first_compare_path,
    index=False
)

# -------------------------------------------------------------------------
# 14. FINAL INTEGRITY
# -------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. STEP 5N COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(user_summary_path)
print(unexplained_path)
print(first_compare_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO MONTHLY INVESTMENT CONTRIBUTION WAS ASSUMED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5N — ACTUAL INVESTMENT / PORTFOLIO EVOLUTION AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Missing LP columns: []
Missing monthly columns: []

================================================================================
1. DATA QUALITY
================================================================================
LP users: 10000
Monthly users: 10000
Monthly duplicate user-period rows: 0
Missing portfolio_value: 0
Missing portfolio_return: 0
Missing initial_investment: 0

================================================================================
2. INITIAL INVESTMENT vs FIRST PORTFOLIO VALUE
================================================================================

First monthly portfolio value vs LP initial investment:
count    10000.000000
mean       156.476509
std        370.696851
min          0.000000
25%          0.000000
50%         11.276223
75%        160.919818
max      13297.605583
Name: abs_difference, dtype: float64

Exact/near-exact matches <= 1e-6: 4555 / 10000

================================================================================
3. PORTFOLIO RETURN RECONSTRUCTION
================================================================================

Valid month-to-month observations: 1420000

Absolute reconstruction error:
count    1.420000e+06
mean     8.978459e-12
std      3.263626e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.637979e-12
max      5.587935e-09
Name: abs_reconstruction_error, dtype: float64

Matches <= 1e-6: 1420000 / 1420000

================================================================================
4. UNEXPLAINED PORTFOLIO CHANGE
================================================================================

Unexplained change statistics:
count    1.420000e+06
mean     4.917215e-13
std      3.384518e-11
min     -5.587935e-09
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.587935e-09
Name: unexplained_change, dtype: float64

Absolute unexplained change statistics:
count    1.420000e+06
mean     8.978459e-12
std      3.263626e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.637979e-12
max      5.587935e-09
Name: abs_unexplained_change, dtype: float64

Observations with unexplained change > 1e-6: 0 / 1420000

================================================================================
5. USER-LEVEL PORTFOLIO SUMMARY
================================================================================
       first_portfolio_value  initial_investment  final_portfolio_value  \
count           1.000000e+04        1.000000e+04           1.000000e+04
mean            5.712501e+04        5.696853e+04           1.159036e+05
std             1.219739e+05        1.216104e+05           2.626814e+05
min             0.000000e+00        0.000000e+00           0.000000e+00
25%             0.000000e+00        0.000000e+00           0.000000e+00
50%             9.166005e+03        9.154055e+03           1.345802e+04
75%             6.804673e+04        6.791043e+04           1.274513e+05
max             3.893538e+06        3.880240e+06           9.121935e+06

       final_minus_initial  portfolio_growth_ratio  mean_portfolio_return
count         1.000000e+04             5445.000000           10000.000000
mean          5.893503e+04                1.866042               0.003990
std           1.428721e+05                0.340167               0.001782
min           0.000000e+00                1.050520               0.000226
25%           0.000000e+00                1.653108               0.002503
50%           3.613765e+03                1.921879               0.004312
75%           5.822956e+04                2.133375               0.005446
max           5.241695e+06                2.368191               0.006816

Users with first portfolio value matching initial investment <= 1e-6: 4555 / 10000

================================================================================
6. INVESTMENT CAPACITY RELATIONSHIP
================================================================================
                           investment_capacity_ratio  initial_investment  \
investment_capacity_ratio                   1.000000            0.421953
initial_investment                          0.421953            1.000000
final_portfolio_value                       0.445814            0.991995
final_minus_initial                         0.460503            0.972675
mean_portfolio_return                       0.913235            0.373067
risk_score                                  0.913235            0.373067

                           final_portfolio_value  final_minus_initial  \
investment_capacity_ratio               0.445814             0.460503
initial_investment                      0.991995             0.972675
final_portfolio_value                   1.000000             0.994207
final_minus_initial                     0.994207             1.000000
mean_portfolio_return                   0.397545             0.413368
risk_score                              0.397545             0.413368

                           mean_portfolio_return  risk_score
investment_capacity_ratio               0.913235    0.913235
initial_investment                      0.373067    0.373067
final_portfolio_value                   0.397545    0.397545
final_minus_initial                     0.413368    0.413368
mean_portfolio_return                   1.000000    1.000000
risk_score                              1.000000    1.000000

================================================================================
7. REPRESENTATIVE USERS
================================================================================
   user_id  initial_investment  first_portfolio_value  final_portfolio_value  final_minus_initial  investment_capacity_ratio  risk_score risk_profile  months
USER_00001        45777.548120           45909.359714           95298.759053         49521.210934                   0.282005    0.710500   aggressive     143
USER_00002            0.000000               0.000000               0.000000             0.000000                   0.000000    0.038363 conservative     143
USER_00003            0.000000               0.000000               0.000000             0.000000                   0.055491    0.505350     moderate     143
USER_00004        60534.274631           60611.220204           85296.198075         24761.923444                   0.031125    0.313650 conservative     143
USER_00005       105774.934379          106096.755919          228458.998450        122684.064071                   0.443954    0.750750   aggressive     143
USER_00006       118987.882781          119384.817167          274237.112721        155249.229940                   0.450063    0.823150   aggressive     143
USER_00007        90329.680595           90608.747053          197157.391015        106827.710420                   0.473577    0.762325   aggressive     143
USER_00008            0.000000               0.000000               0.000000             0.000000                   0.000000    0.087587 conservative     143
USER_00009            0.000000               0.000000               0.000000             0.000000                   0.335670    0.688500   aggressive     143
USER_00010        15171.499059           15204.288732           26694.224964         11522.725905                   0.117248    0.533300     moderate     143

================================================================================
8. STEP 5N COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_actual_portfolio_evolution_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_actual_portfolio_user_summary.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_unexplained_portfolio_change.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_initial_investment_vs_first_portfolio.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO MONTHLY INVESTMENT CONTRIBUTION WAS ASSUMED.
NO OBJECTIVE FUNCTION WAS ASSUMED.

In [105]:
# =============================================================================
# STEP 5N — LOCATE THE ACTUAL MONTHLY SIMULATION FILE
# =============================================================================

import os
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

print("=" * 80)
print("SEARCHING FOR ACTUAL MONTHLY SIMULATION DATA")
print("=" * 80)

search_dirs = [
    os.path.join(BASE, "simulation"),
    os.path.join(BASE, "simulation", "06_results"),
    os.path.join(BASE, "simulation", "05_simulation"),
    os.path.join(BASE, "simulation", "03_simulation"),
    os.path.join(BASE, "simulation", "04_economic_environment"),
]

candidates = []

for folder in search_dirs:
    if not os.path.exists(folder):
        continue

    for root, dirs, files in os.walk(folder):
        for file in files:
            if file.lower().endswith(".csv"):
                path = os.path.join(root, file)

                try:
                    # Read only header first
                    cols = pd.read_csv(path, nrows=0).columns.tolist()

                    required = {
                        "user_id",
                        "period",
                        "portfolio_value",
                        "portfolio_return"
                    }

                    matches = required.intersection(cols)

                    if len(matches) >= 2:
                        candidates.append({
                            "file": file,
                            "path": path,
                            "columns": len(cols),
                            "matched_required_columns": len(matches),
                            "matched_columns": ", ".join(sorted(matches))
                        })

                except Exception:
                    pass

print("\nPotential simulation files:\n")

if candidates:
    result = pd.DataFrame(candidates)
    print(result.to_string(index=False))
else:
    print("No matching CSV found.")

print("\n" + "=" * 80)
print("NOW CHECKING FILE SIZES / ROW COUNTS")
print("=" * 80)

for item in candidates:
    try:
        df_test = pd.read_csv(item["path"])

        print("\nFILE:", item["path"])
        print("Shape:", df_test.shape)
        print("Columns:", df_test.columns.tolist())

    except Exception as e:
        print("\nCould not fully read:", item["path"])
        print("Error:", e)

================================================================================
SEARCHING FOR ACTUAL MONTHLY SIMULATION DATA
================================================================================

Potential simulation files:

                                 file                                                                                                    path  columns  matched_required_columns                                    matched_columns
   portfolio_simulation_validated.csv    /content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/portfolio_simulation_validated.csv        9                         4 period, portfolio_return, portfolio_value, user_id
monthly_financial_simulation_base.csv /content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/monthly_financial_simulation_base.csv       46                         4 period, portfolio_return, portfolio_value, user_id

================================================================================
NOW CHECKING FILE SIZES / ROW COUNTS
================================================================================

FILE: /content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/portfolio_simulation_validated.csv
Shape: (1430000, 9)
Columns: ['user_id', 'period', 'initial_investment', 'risk_score', 'risk_profile', 'market_exposure', 'nifty_monthly_return', 'portfolio_return', 'portfolio_value']

FILE: /content/drive/MyDrive/GoalPilot_AI/simulation/05_simulation_runs/monthly_financial_simulation_base.csv
Shape: (1430000, 46)
Columns: ['user_id', 'period', 'portfolio_return', 'portfolio_value', 'monthly_income', 'monthly_expenditure', 'monthly_surplus', 'monthly_emi', 'initial_savings', 'initial_investment', 'investment_capacity_ratio', 'risk_score', 'risk_profile', 'inflation_level', 'inflation_change', 'inflation_pct_change', 'inflation_trend', 'inflation_regime', 'nifty_monthly_return', 'nifty_return_volatility', 'nifty_3m_volatility', 'nifty_ma_gap', 'market_return_regime', 'market_volatility_regime', 'average_walr', 'walr_change', 'credit_pressure', 'walr_3period_ma', 'walr_momentum', 'walr_regime', 'annual_inflation_rate', 'monthly_inflation_rate', 'cumulative_inflation_factor', 'monthly_expenditure_dynamic', 'monthly_income_dynamic', 'monthly_surplus_dynamic', 'positive_cash_flow', 'cash_flow_status', 'financial_situation', 'cumulative_cash_flow', 'savings_balance', 'savings_balance_status', 'pre_savings_balance', 'unfunded_deficit', 'total_financial_wealth', 'portfolio_wealth_ratio']

In [106]:
# =============================================================================
# STEP 5N — ACTUAL INVESTMENT / PORTFOLIO EVOLUTION AUDIT
# CORRECTED VERSION USING THE VERIFIED MONTHLY SIMULATION FILE
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5N — ACTUAL INVESTMENT / PORTFOLIO EVOLUTION AUDIT")
print("=" * 80)

# =============================================================================
# 1. LOAD VERIFIED FILES
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. VERIFY REQUIRED COLUMNS
# =============================================================================

required_lp = [
    "user_id",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months"
]

required_monthly = [
    "user_id",
    "period",
    "portfolio_value",
    "portfolio_return",
    "initial_investment",
    "risk_score",
    "risk_profile"
]

missing_lp = [
    c for c in required_lp
    if c not in lp.columns
]

missing_monthly = [
    c for c in required_monthly
    if c not in monthly.columns
]

print("\nMissing LP columns:", missing_lp)
print("Missing monthly columns:", missing_monthly)

if missing_lp or missing_monthly:
    raise ValueError(
        "Required columns are missing. Stop and inspect the output."
    )

# =============================================================================
# 3. SELECT ONLY REQUIRED COLUMNS
# =============================================================================

lp_small = lp[required_lp].copy()

monthly_small = monthly[
    [
        "user_id",
        "period",
        "portfolio_value",
        "portfolio_return",
        "initial_investment",
        "risk_score",
        "risk_profile"
    ]
].copy()

# Numeric conversion
for c in [
    "portfolio_value",
    "portfolio_return",
    "initial_investment",
    "risk_score"
]:
    monthly_small[c] = pd.to_numeric(
        monthly_small[c],
        errors="coerce"
    )

lp_small["initial_investment"] = pd.to_numeric(
    lp_small["initial_investment"],
    errors="coerce"
)

lp_small["investment_capacity_ratio"] = pd.to_numeric(
    lp_small["investment_capacity_ratio"],
    errors="coerce"
)

lp_small["risk_score"] = pd.to_numeric(
    lp_small["risk_score"],
    errors="coerce"
)

lp_small["goal_horizon_months"] = pd.to_numeric(
    lp_small["goal_horizon_months"],
    errors="coerce"
)

monthly_small["period"] = pd.to_datetime(
    monthly_small["period"],
    errors="coerce"
)

monthly_small = monthly_small.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# =============================================================================
# 4. BASIC DATA QUALITY
# =============================================================================

print("\n" + "=" * 80)
print("1. DATA QUALITY")
print("=" * 80)

print("LP users:",
      lp_small["user_id"].nunique())

print("Monthly users:",
      monthly_small["user_id"].nunique())

print(
    "Monthly duplicate user-period rows:",
    monthly_small.duplicated(
        ["user_id", "period"]
    ).sum()
)

print(
    "Missing portfolio_value:",
    monthly_small["portfolio_value"].isna().sum()
)

print(
    "Missing portfolio_return:",
    monthly_small["portfolio_return"].isna().sum()
)

print(
    "Missing initial_investment:",
    monthly_small["initial_investment"].isna().sum()
)

# =============================================================================
# 5. NUMBER OF MONTHS PER USER
# =============================================================================

print("\n" + "=" * 80)
print("2. MONTHLY COVERAGE")
print("=" * 80)

months_per_user = (
    monthly_small
    .groupby("user_id")["period"]
    .count()
)

print(months_per_user.describe())

print(
    "\nUsers with exactly 143 months:",
    (months_per_user == 143).sum(),
    "/",
    len(months_per_user)
)

# =============================================================================
# 6. FIRST PORTFOLIO VALUE VS INITIAL INVESTMENT
# =============================================================================

print("\n" + "=" * 80)
print("3. INITIAL INVESTMENT vs FIRST PORTFOLIO VALUE")
print("=" * 80)

first_rows = (
    monthly_small
    .sort_values(["user_id", "period"])
    .groupby("user_id", as_index=False)
    .first()
)

first_compare = lp_small[
    ["user_id", "initial_investment"]
].merge(
    first_rows[
        [
            "user_id",
            "period",
            "portfolio_value",
            "portfolio_return",
            "initial_investment"
        ]
    ],
    on="user_id",
    how="inner",
    suffixes=("_lp", "_monthly")
)

first_compare["difference"] = (
    first_compare["portfolio_value"]
    - first_compare["initial_investment_lp"]
)

first_compare["abs_difference"] = (
    first_compare["difference"].abs()
)

print(
    "\nFirst portfolio value vs LP initial investment:"
)

print(
    first_compare["abs_difference"].describe()
)

print(
    "\nMatches <= 1e-6:",
    (
        first_compare["abs_difference"] <= 1e-6
    ).sum(),
    "/",
    len(first_compare)
)

# =============================================================================
# 7. TEST WHETHER PORTFOLIO RETURN ALONE RECONSTRUCTS PORTFOLIO VALUE
# =============================================================================

print("\n" + "=" * 80)
print("4. PORTFOLIO RETURN RECONSTRUCTION")
print("=" * 80)

m = monthly_small.copy()

m["previous_portfolio_value"] = (
    m.groupby("user_id")["portfolio_value"]
    .shift(1)
)

m["return_implied_portfolio"] = (
    m["previous_portfolio_value"]
    * (1 + m["portfolio_return"])
)

valid = m[
    m["previous_portfolio_value"].notna()
    &
    m["portfolio_value"].notna()
    &
    m["portfolio_return"].notna()
].copy()

valid["reconstruction_error"] = (
    valid["portfolio_value"]
    - valid["return_implied_portfolio"]
)

valid["abs_reconstruction_error"] = (
    valid["reconstruction_error"].abs()
)

print(
    "\nValid month-to-month observations:",
    len(valid)
)

print(
    "\nAbsolute reconstruction error:"
)

print(
    valid["abs_reconstruction_error"].describe()
)

print(
    "\nMatches <= 1e-6:",
    (
        valid["abs_reconstruction_error"] <= 1e-6
    ).sum(),
    "/",
    len(valid)
)

# =============================================================================
# 8. UNEXPLAINED PORTFOLIO CHANGE
# =============================================================================

print("\n" + "=" * 80)
print("5. UNEXPLAINED PORTFOLIO CHANGE")
print("=" * 80)

# This is:
#
# Actual portfolio value
# -
# Previous portfolio value × (1 + portfolio return)
#
# We DO NOT call this an investment contribution.
# It is simply an unexplained residual until the simulation mechanism
# is established.

valid["unexplained_change"] = (
    valid["portfolio_value"]
    -
    (
        valid["previous_portfolio_value"]
        * (1 + valid["portfolio_return"])
    )
)

valid["abs_unexplained_change"] = (
    valid["unexplained_change"].abs()
)

print("\nUnexplained change:")

print(
    valid["unexplained_change"].describe()
)

print("\nAbsolute unexplained change:")

print(
    valid["abs_unexplained_change"].describe()
)

threshold = 1e-6

print(
    "\nObservations with unexplained change > 1e-6:",
    (
        valid["abs_unexplained_change"] > threshold
    ).sum(),
    "/",
    len(valid)
)

# =============================================================================
# 9. USER-LEVEL PORTFOLIO SUMMARY
# =============================================================================

print("\n" + "=" * 80)
print("6. USER-LEVEL PORTFOLIO SUMMARY")
print("=" * 80)

portfolio_summary = (
    monthly_small
    .groupby("user_id")
    .agg(
        months=("period", "count"),

        first_portfolio_value=(
            "portfolio_value",
            "first"
        ),

        final_portfolio_value=(
            "portfolio_value",
            "last"
        ),

        minimum_portfolio_value=(
            "portfolio_value",
            "min"
        ),

        maximum_portfolio_value=(
            "portfolio_value",
            "max"
        ),

        mean_portfolio_value=(
            "portfolio_value",
            "mean"
        ),

        mean_portfolio_return=(
            "portfolio_return",
            "mean"
        ),

        min_portfolio_return=(
            "portfolio_return",
            "min"
        ),

        max_portfolio_return=(
            "portfolio_return",
            "max"
        )
    )
    .reset_index()
)

portfolio_summary = portfolio_summary.merge(
    lp_small[
        [
            "user_id",
            "initial_investment",
            "investment_capacity_ratio",
            "risk_score",
            "risk_profile",
            "goal_horizon_months"
        ]
    ],
    on="user_id",
    how="left"
)

portfolio_summary["final_minus_initial"] = (
    portfolio_summary["final_portfolio_value"]
    - portfolio_summary["initial_investment"]
)

portfolio_summary["first_minus_initial"] = (
    portfolio_summary["first_portfolio_value"]
    - portfolio_summary["initial_investment"]
)

portfolio_summary["portfolio_growth_ratio"] = np.where(
    portfolio_summary["initial_investment"] > 0,

    portfolio_summary["final_portfolio_value"]
    /
    portfolio_summary["initial_investment"],

    np.nan
)

print(
    portfolio_summary[
        [
            "first_portfolio_value",
            "initial_investment",
            "final_portfolio_value",
            "final_minus_initial",
            "portfolio_growth_ratio",
            "mean_portfolio_return"
        ]
    ].describe()
)

# =============================================================================
# 10. INVESTMENT CAPACITY RELATIONSHIP
# =============================================================================

print("\n" + "=" * 80)
print("7. INVESTMENT CAPACITY RELATIONSHIP")
print("=" * 80)

corr_columns = [
    "investment_capacity_ratio",
    "initial_investment",
    "final_portfolio_value",
    "final_minus_initial",
    "mean_portfolio_return",
    "risk_score"
]

print(
    portfolio_summary[
        corr_columns
    ].corr()
)

# =============================================================================
# 11. PORTFOLIO BEHAVIOUR BY RISK PROFILE
# =============================================================================

print("\n" + "=" * 80)
print("8. PORTFOLIO BY RISK PROFILE")
print("=" * 80)

risk_summary = (
    portfolio_summary
    .groupby("risk_profile")
    .agg(
        users=("user_id", "count"),
        mean_initial_investment=(
            "initial_investment",
            "mean"
        ),
        mean_final_portfolio=(
            "final_portfolio_value",
            "mean"
        ),
        mean_portfolio_growth=(
            "final_minus_initial",
            "mean"
        ),
        mean_return=(
            "mean_portfolio_return",
            "mean"
        ),
        mean_risk_score=(
            "risk_score",
            "mean"
        ),
        mean_investment_capacity_ratio=(
            "investment_capacity_ratio",
            "mean"
        )
    )
    .reset_index()
)

print(
    risk_summary.to_string(index=False)
)

# =============================================================================
# 12. REPRESENTATIVE USERS
# =============================================================================

print("\n" + "=" * 80)
print("9. REPRESENTATIVE USERS")
print("=" * 80)

representative_ids = [
    "USER_00001",
    "USER_00002",
    "USER_00003",
    "USER_00004",
    "USER_00005",
    "USER_00006",
    "USER_00007",
    "USER_00008",
    "USER_00009",
    "USER_00010"
]

rep = portfolio_summary[
    portfolio_summary["user_id"].isin(
        representative_ids
    )
].copy()

print(
    rep[
        [
            "user_id",
            "initial_investment",
            "first_portfolio_value",
            "final_portfolio_value",
            "final_minus_initial",
            "investment_capacity_ratio",
            "risk_score",
            "risk_profile",
            "months"
        ]
    ].to_string(index=False)
)

# =============================================================================
# 13. SAVE AUDIT FILES
# =============================================================================

OUTPUT_DIR = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

audit_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_actual_portfolio_evolution_audit.csv"
)

user_summary_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_actual_portfolio_user_summary.csv"
)

unexplained_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_unexplained_portfolio_change.csv"
)

first_compare_path = os.path.join(
    OUTPUT_DIR,
    "lp_5n_initial_investment_vs_first_portfolio.csv"
)

# Overall audit
audit_rows = [
    ["lp_rows", len(lp_small)],
    ["monthly_rows", len(monthly_small)],
    ["lp_unique_users", lp_small["user_id"].nunique()],
    ["monthly_unique_users", monthly_small["user_id"].nunique()],
    [
        "duplicate_user_period_rows",
        monthly_small.duplicated(
            ["user_id", "period"]
        ).sum()
    ],
    [
        "users_with_143_months",
        (months_per_user == 143).sum()
    ],
    [
        "first_portfolio_initial_matches",
        (
            first_compare["abs_difference"] <= 1e-6
        ).sum()
    ],
    [
        "first_portfolio_initial_mean_abs_diff",
        first_compare["abs_difference"].mean()
    ],
    [
        "return_reconstruction_rows",
        len(valid)
    ],
    [
        "return_reconstruction_mean_abs_error",
        valid["abs_reconstruction_error"].mean()
    ],
    [
        "return_reconstruction_max_abs_error",
        valid["abs_reconstruction_error"].max()
    ],
    [
        "return_reconstruction_matches_1e-6",
        (
            valid["abs_reconstruction_error"] <= 1e-6
        ).sum()
    ],
    [
        "material_unexplained_change_rows",
        (
            valid["abs_unexplained_change"] > threshold
        ).sum()
    ]
]

pd.DataFrame(
    audit_rows,
    columns=["metric", "value"]
).to_csv(
    audit_path,
    index=False
)

portfolio_summary.to_csv(
    user_summary_path,
    index=False
)

valid[
    [
        "user_id",
        "period",
        "previous_portfolio_value",
        "portfolio_return",
        "portfolio_value",
        "unexplained_change",
        "abs_unexplained_change"
    ]
].to_csv(
    unexplained_path,
    index=False
)

first_compare.to_csv(
    first_compare_path,
    index=False
)

# =============================================================================
# 14. FINAL INTEGRITY
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5N COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(user_summary_path)
print(unexplained_path)
print(first_compare_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO MONTHLY INVESTMENT CONTRIBUTION WAS ASSUMED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5N — ACTUAL INVESTMENT / PORTFOLIO EVOLUTION AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Missing LP columns: []
Missing monthly columns: []

================================================================================
1. DATA QUALITY
================================================================================
LP users: 10000
Monthly users: 10000
Monthly duplicate user-period rows: 0
Missing portfolio_value: 0
Missing portfolio_return: 0
Missing initial_investment: 0

================================================================================
2. MONTHLY COVERAGE
================================================================================
count    10000.0
mean       143.0
std          0.0
min        143.0
25%        143.0
50%        143.0
75%        143.0
max        143.0
Name: period, dtype: float64

Users with exactly 143 months: 10000 / 10000

================================================================================
3. INITIAL INVESTMENT vs FIRST PORTFOLIO VALUE
================================================================================

First portfolio value vs LP initial investment:
count    10000.000000
mean       156.476509
std        370.696851
min          0.000000
25%          0.000000
50%         11.276223
75%        160.919818
max      13297.605583
Name: abs_difference, dtype: float64

Matches <= 1e-6: 4555 / 10000

================================================================================
4. PORTFOLIO RETURN RECONSTRUCTION
================================================================================

Valid month-to-month observations: 1420000

Absolute reconstruction error:
count    1.420000e+06
mean     8.978459e-12
std      3.263626e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.637979e-12
max      5.587935e-09
Name: abs_reconstruction_error, dtype: float64

Matches <= 1e-6: 1420000 / 1420000

================================================================================
5. UNEXPLAINED PORTFOLIO CHANGE
================================================================================

Unexplained change:
count    1.420000e+06
mean     4.917215e-13
std      3.384518e-11
min     -5.587935e-09
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.587935e-09
Name: unexplained_change, dtype: float64

Absolute unexplained change:
count    1.420000e+06
mean     8.978459e-12
std      3.263626e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.637979e-12
max      5.587935e-09
Name: abs_unexplained_change, dtype: float64

Observations with unexplained change > 1e-6: 0 / 1420000

================================================================================
6. USER-LEVEL PORTFOLIO SUMMARY
================================================================================
       first_portfolio_value  initial_investment  final_portfolio_value  \
count           1.000000e+04        1.000000e+04           1.000000e+04
mean            5.712501e+04        5.696853e+04           1.159036e+05
std             1.219739e+05        1.216104e+05           2.626814e+05
min             0.000000e+00        0.000000e+00           0.000000e+00
25%             0.000000e+00        0.000000e+00           0.000000e+00
50%             9.166005e+03        9.154055e+03           1.345802e+04
75%             6.804673e+04        6.791043e+04           1.274513e+05
max             3.893538e+06        3.880240e+06           9.121935e+06

       final_minus_initial  portfolio_growth_ratio  mean_portfolio_return
count         1.000000e+04             5445.000000           10000.000000
mean          5.893503e+04                1.866042               0.003990
std           1.428721e+05                0.340167               0.001782
min           0.000000e+00                1.050520               0.000226
25%           0.000000e+00                1.653108               0.002503
50%           3.613765e+03                1.921879               0.004312
75%           5.822956e+04                2.133375               0.005446
max           5.241695e+06                2.368191               0.006816

================================================================================
7. INVESTMENT CAPACITY RELATIONSHIP
================================================================================
                           investment_capacity_ratio  initial_investment  \
investment_capacity_ratio                   1.000000            0.421953
initial_investment                          0.421953            1.000000
final_portfolio_value                       0.445814            0.991995
final_minus_initial                         0.460503            0.972675
mean_portfolio_return                       0.913235            0.373067
risk_score                                  0.913235            0.373067

                           final_portfolio_value  final_minus_initial  \
investment_capacity_ratio               0.445814             0.460503
initial_investment                      0.991995             0.972675
final_portfolio_value                   1.000000             0.994207
final_minus_initial                     0.994207             1.000000
mean_portfolio_return                   0.397545             0.413368
risk_score                              0.397545             0.413368

                           mean_portfolio_return  risk_score
investment_capacity_ratio               0.913235    0.913235
initial_investment                      0.373067    0.373067
final_portfolio_value                   0.397545    0.397545
final_minus_initial                     0.413368    0.413368
mean_portfolio_return                   1.000000    1.000000
risk_score                              1.000000    1.000000

================================================================================
8. PORTFOLIO BY RISK PROFILE
================================================================================
risk_profile  users  mean_initial_investment  mean_final_portfolio  mean_portfolio_growth  mean_return  mean_risk_score  mean_investment_capacity_ratio
  aggressive   3333            114485.540659         252576.518177          138090.977519     0.005884         0.737324                        0.344191
conservative   3333             15961.616749          22304.524287            6342.907539     0.001816         0.227601                        0.029605
    moderate   3334             40463.399131          72842.584833           32379.185702     0.004270         0.535065                        0.187888

================================================================================
9. REPRESENTATIVE USERS
================================================================================
   user_id  initial_investment  first_portfolio_value  final_portfolio_value  final_minus_initial  investment_capacity_ratio  risk_score risk_profile  months
USER_00001        45777.548120           45909.359714           95298.759053         49521.210934                   0.282005    0.710500   aggressive     143
USER_00002            0.000000               0.000000               0.000000             0.000000                   0.000000    0.038363 conservative     143
USER_00003            0.000000               0.000000               0.000000             0.000000                   0.055491    0.505350     moderate     143
USER_00004        60534.274631           60611.220204           85296.198075         24761.923444                   0.031125    0.313650 conservative     143
USER_00005       105774.934379          106096.755919          228458.998450        122684.064071                   0.443954    0.750750   aggressive     143
USER_00006       118987.882781          119384.817167          274237.112721        155249.229940                   0.450063    0.823150   aggressive     143
USER_00007        90329.680595           90608.747053          197157.391015        106827.710420                   0.473577    0.762325   aggressive     143
USER_00008            0.000000               0.000000               0.000000             0.000000                   0.000000    0.087587 conservative     143
USER_00009            0.000000               0.000000               0.000000             0.000000                   0.335670    0.688500   aggressive     143
USER_00010        15171.499059           15204.288732           26694.224964         11522.725905                   0.117248    0.533300     moderate     143

================================================================================
STEP 5N COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_actual_portfolio_evolution_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_actual_portfolio_user_summary.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_unexplained_portfolio_change.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5n_initial_investment_vs_first_portfolio.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO MONTHLY INVESTMENT CONTRIBUTION WAS ASSUMED.
NO OBJECTIVE FUNCTION WAS ASSUMED.

In [107]:
# =============================================================================
# STEP 5O — LP DECISION-VARIABLE DEPENDENCY AUDIT
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5O — LP DECISION-VARIABLE DEPENDENCY AUDIT")
print("=" * 80)

# =============================================================================
# 1. LOAD DATA
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. REQUIRED COLUMNS
# =============================================================================

required_lp = [
    "user_id",
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual"
]

required_monthly = [
    "user_id",
    "period",
    "monthly_income_dynamic",
    "monthly_expenditure_dynamic",
    "monthly_emi",
    "monthly_surplus_dynamic",
    "positive_cash_flow",
    "portfolio_value",
    "portfolio_return",
    "initial_investment"
]

missing_lp = [
    c for c in required_lp
    if c not in lp.columns
]

missing_monthly = [
    c for c in required_monthly
    if c not in monthly.columns
]

print("\nMissing LP columns:", missing_lp)
print("Missing monthly columns:", missing_monthly)

if missing_lp or missing_monthly:
    raise ValueError(
        "Required columns missing. Stop here."
    )

# =============================================================================
# 3. PREPARE MONTHLY DATA
# =============================================================================

m = monthly[
    required_monthly
].copy()

m["period"] = pd.to_datetime(
    m["period"],
    errors="coerce"
)

numeric_cols = [
    "monthly_income_dynamic",
    "monthly_expenditure_dynamic",
    "monthly_emi",
    "monthly_surplus_dynamic",
    "positive_cash_flow",
    "portfolio_value",
    "portfolio_return",
    "initial_investment"
]

for c in numeric_cols:
    m[c] = pd.to_numeric(
        m[c],
        errors="coerce"
    )

m = m.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# =============================================================================
# 4. VERIFY SURPLUS EQUATION
# =============================================================================

print("\n" + "=" * 80)
print("1. SURPLUS DEPENDENCY")
print("=" * 80)

m["calculated_surplus"] = (
    m["monthly_income_dynamic"]
    -
    m["monthly_expenditure_dynamic"]
    -
    m["monthly_emi"]
)

m["surplus_error"] = (
    m["monthly_surplus_dynamic"]
    -
    m["calculated_surplus"]
)

print(
    "Surplus reconstruction mean absolute error:",
    m["surplus_error"].abs().mean()
)

print(
    "Surplus reconstruction max absolute error:",
    m["surplus_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (m["surplus_error"].abs() <= 1e-6).sum(),
    "/",
    len(m)
)

# =============================================================================
# 5. VERIFY POSITIVE CASH FLOW DEPENDENCY
# =============================================================================

print("\n" + "=" * 80)
print("2. POSITIVE CASH FLOW DEPENDENCY")
print("=" * 80)

m["calculated_positive_cash_flow"] = (
    m["monthly_surplus_dynamic"].clip(lower=0)
)

m["positive_cash_flow_error"] = (
    m["positive_cash_flow"]
    -
    m["calculated_positive_cash_flow"]
)

print(
    "Positive cash flow mean absolute error:",
    m["positive_cash_flow_error"].abs().mean()
)

print(
    "Positive cash flow max absolute error:",
    m["positive_cash_flow_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        m["positive_cash_flow_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(m)
)

# =============================================================================
# 6. RECONSTRUCT EXISTING GOAL FUNDING MONTH BY MONTH
# =============================================================================

print("\n" + "=" * 80)
print("3. GOAL FUNDING DEPENDENCY")
print("=" * 80)

lp_factor = lp[
    [
        "user_id",
        "goal_allocation_factor",
        "investment_capacity_ratio",
        "initial_investment",
        "risk_score"
    ]
].copy()

m = m.merge(
    lp_factor,
    on="user_id",
    how="left"
)

m["reconstructed_goal_funding"] = (
    m["positive_cash_flow"]
    *
    m["goal_allocation_factor"]
)

# Aggregate over all simulation months.
goal_by_user = (
    m.groupby("user_id")
    .agg(
        reconstructed_goal_funding=(
            "reconstructed_goal_funding",
            "sum"
        ),
        total_positive_cash_flow=(
            "positive_cash_flow",
            "sum"
        ),
        final_portfolio_value=(
            "portfolio_value",
            "last"
        ),
        initial_investment_monthly=(
            "initial_investment",
            "first"
        ),
        mean_portfolio_return=(
            "portfolio_return",
            "mean"
        )
    )
    .reset_index()
)

goal_by_user = goal_by_user.merge(
    lp[
        [
            "user_id",
            "goal_horizon_funding_actual",
            "target_amount",
            "goal_shortfall_actual",
            "goal_achieved_on_time_actual",
            "initial_investment",
            "investment_capacity_ratio",
            "risk_score"
        ]
    ],
    on="user_id",
    how="left"
)

goal_by_user["goal_formula_error"] = (
    goal_by_user["reconstructed_goal_funding"]
    -
    goal_by_user["goal_horizon_funding_actual"]
)

print(
    "\nGoal funding reconstruction mean absolute error:",
    goal_by_user["goal_formula_error"].abs().mean()
)

print(
    "Goal funding reconstruction max absolute error:",
    goal_by_user["goal_formula_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        goal_by_user["goal_formula_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(goal_by_user)
)

# =============================================================================
# 7. TEST WHETHER PORTFOLIO VALUE ENTERS GOAL FUNDING
# =============================================================================

print("\n" + "=" * 80)
print("4. PORTFOLIO → GOAL FUNDING DEPENDENCY")
print("=" * 80)

portfolio_goal_corr = goal_by_user[
    [
        "reconstructed_goal_funding",
        "final_portfolio_value",
        "initial_investment",
        "investment_capacity_ratio",
        "risk_score",
        "mean_portfolio_return"
    ]
].corr()

print(
    portfolio_goal_corr
)

print(
    "\nIMPORTANT:"
)

print(
    "Correlation alone does NOT establish causation."
)

print(
    "The structural test is whether portfolio_value appears in the"
    " reconstructed goal-funding equation."
)

# =============================================================================
# 8. TEST WHETHER INVESTMENT CAPACITY IS PART OF EXISTING GOAL FUNDING
# =============================================================================

print("\n" + "=" * 80)
print("5. INVESTMENT CAPACITY → GOAL FUNDING DEPENDENCY")
print("=" * 80)

# Reconstruct the existing funding without investment_capacity_ratio.
# This is the known exact formula.

goal_without_investment_capacity = (
    m["positive_cash_flow"]
    *
    m["goal_allocation_factor"]
)

goal_formula_difference = (
    m["reconstructed_goal_funding"]
    -
    goal_without_investment_capacity
)

print(
    "Difference when investment capacity is excluded:",
    goal_formula_difference.abs().sum()
)

print(
    "Maximum difference:",
    goal_formula_difference.abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        goal_formula_difference.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(m)
)

# =============================================================================
# 9. TEST FIRST PORTFOLIO VALUE FORMULA
# =============================================================================

print("\n" + "=" * 80)
print("6. FIRST-MONTH PORTFOLIO INITIALIZATION")
print("=" * 80)

first = (
    m.sort_values(["user_id", "period"])
    .groupby("user_id", as_index=False)
    .first()
)

first["implied_first_portfolio"] = (
    first["initial_investment_monthly"]
    *
    (1 + first["portfolio_return"])
)

first["first_portfolio_error"] = (
    first["portfolio_value"]
    -
    first["implied_first_portfolio"]
)

print(
    "First portfolio reconstruction mean absolute error:",
    first["first_portfolio_error"].abs().mean()
)

print(
    "First portfolio reconstruction max absolute error:",
    first["first_portfolio_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        first["first_portfolio_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(first)
)

# =============================================================================
# 10. STRUCTURAL VARIABLE INVENTORY
# =============================================================================

print("\n" + "=" * 80)
print("7. STRUCTURAL LP VARIABLE INVENTORY")
print("=" * 80)

inventory = pd.DataFrame([
    [
        "G_t",
        "Goal funding",
        "Supported by positive_cash_flow × goal_allocation_factor",
        "YES"
    ],
    [
        "I_t",
        "Monthly investment contribution",
        "No explicit monthly contribution field exists",
        "NO — DO NOT INVENT"
    ],
    [
        "C_t",
        "Residual cash",
        "Can be derived arithmetically, but is not an observed simulation variable",
        "DERIVED ONLY"
    ],
    [
        "D",
        "Goal shortfall",
        "Directly supported by target_amount and goal funding",
        "YES"
    ],
    [
        "Portfolio_t",
        "Portfolio state",
        "Observed directly as portfolio_value",
        "STATE VARIABLE"
    ],
    [
        "InitialInvestment",
        "Starting portfolio state",
        "Observed directly",
        "PARAMETER"
    ]
], columns=[
    "variable",
    "meaning",
    "data_support",
    "status"
])

print(
    inventory.to_string(index=False)
)

# =============================================================================
# 11. FINAL DECISION-RELEVANCE SUMMARY
# =============================================================================

print("\n" + "=" * 80)
print("8. DECISION-RELEVANCE SUMMARY")
print("=" * 80)

print("""
Existing simulation structure established so far:

1. Dynamic income, expenditure and EMI determine surplus.
2. Positive cash flow is max(surplus, 0).
3. Goal funding is positive cash flow × goal allocation factor.
4. Portfolio value evolves from its previous value using portfolio return.
5. No explicit monthly investment contribution variable is stored.
6. Initial investment is an initial portfolio state.
7. Therefore, monthly investment contribution should NOT be invented
   as an LP decision variable at this stage.
8. Goal funding and portfolio evolution must be treated as separate
   mechanisms unless the source simulation provides an explicit linkage.
""")

# =============================================================================
# 12. SAVE OUTPUTS
# =============================================================================

OUTPUT_DIR = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

audit_path = os.path.join(
    OUTPUT_DIR,
    "lp_5o_decision_variable_dependency_audit.csv"
)

inventory_path = os.path.join(
    OUTPUT_DIR,
    "lp_5o_structural_variable_inventory.csv"
)

goal_by_user_path = os.path.join(
    OUTPUT_DIR,
    "lp_5o_goal_portfolio_dependency_by_user.csv"
)

audit_rows = [
    [
        "surplus_mean_abs_error",
        m["surplus_error"].abs().mean()
    ],
    [
        "surplus_max_abs_error",
        m["surplus_error"].abs().max()
    ],
    [
        "surplus_matches_1e-6",
        (
            m["surplus_error"].abs()
            <= 1e-6
        ).sum()
    ],
    [
        "positive_cash_flow_mean_abs_error",
        m["positive_cash_flow_error"].abs().mean()
    ],
    [
        "positive_cash_flow_max_abs_error",
        m["positive_cash_flow_error"].abs().max()
    ],
    [
        "positive_cash_flow_matches_1e-6",
        (
            m["positive_cash_flow_error"].abs()
            <= 1e-6
        ).sum()
    ],
    [
        "goal_funding_mean_abs_error",
        goal_by_user["goal_formula_error"].abs().mean()
    ],
    [
        "goal_funding_max_abs_error",
        goal_by_user["goal_formula_error"].abs().max()
    ],
    [
        "goal_funding_matches_1e-6",
        (
            goal_by_user["goal_formula_error"].abs()
            <= 1e-6
        ).sum()
    ],
    [
        "first_portfolio_mean_abs_error",
        first["first_portfolio_error"].abs().mean()
    ],
    [
        "first_portfolio_max_abs_error",
        first["first_portfolio_error"].abs().max()
    ],
    [
        "first_portfolio_matches_1e-6",
        (
            first["first_portfolio_error"].abs()
            <= 1e-6
        ).sum()
    ]
]

pd.DataFrame(
    audit_rows,
    columns=["metric", "value"]
).to_csv(
    audit_path,
    index=False
)

inventory.to_csv(
    inventory_path,
    index=False
)

goal_by_user.to_csv(
    goal_by_user_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5O COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(inventory_path)
print(goal_by_user_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO MONTHLY INVESTMENT CONTRIBUTION WAS INVENTED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5O — LP DECISION-VARIABLE DEPENDENCY AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Missing LP columns: []
Missing monthly columns: []

================================================================================
1. SURPLUS DEPENDENCY
================================================================================
Surplus reconstruction mean absolute error: 4.381543353831896e-12
Surplus reconstruction max absolute error: 6.984919309616089e-10
Matches <= 1e-6: 1430000 / 1430000

================================================================================
2. POSITIVE CASH FLOW DEPENDENCY
================================================================================
Positive cash flow mean absolute error: 0.0
Positive cash flow max absolute error: 0.0
Matches <= 1e-6: 1430000 / 1430000

================================================================================
3. GOAL FUNDING DEPENDENCY
================================================================================

KeyError: "Column(s) ['initial_investment'] do not exist"

In [108]:
# =============================================================================
# STEP 5O — LP DECISION-VARIABLE DEPENDENCY AUDIT
# CORRECTED — NO DUPLICATE USER-LEVEL COLUMNS
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5O — LP DECISION-VARIABLE DEPENDENCY AUDIT")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. REQUIRED COLUMNS
# =============================================================================

required_lp = [
    "user_id",
    "goal_allocation_factor",
    "investment_capacity_ratio",
    "initial_investment",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual"
]

required_monthly = [
    "user_id",
    "period",
    "monthly_income_dynamic",
    "monthly_expenditure_dynamic",
    "monthly_emi",
    "monthly_surplus_dynamic",
    "positive_cash_flow",
    "portfolio_value",
    "portfolio_return",
    "initial_investment"
]

missing_lp = [
    c for c in required_lp
    if c not in lp.columns
]

missing_monthly = [
    c for c in required_monthly
    if c not in monthly.columns
]

print("\nMissing LP columns:", missing_lp)
print("Missing monthly columns:", missing_monthly)

if missing_lp or missing_monthly:
    raise ValueError("Required columns are missing.")

# =============================================================================
# 3. SELECT DATA
# =============================================================================

lp_small = lp[required_lp].copy()

monthly_small = monthly[
    required_monthly
].copy()

# Convert numeric
for c in [
    "monthly_income_dynamic",
    "monthly_expenditure_dynamic",
    "monthly_emi",
    "monthly_surplus_dynamic",
    "positive_cash_flow",
    "portfolio_value",
    "portfolio_return",
    "initial_investment"
]:
    monthly_small[c] = pd.to_numeric(
        monthly_small[c],
        errors="coerce"
    )

for c in [
    "goal_allocation_factor",
    "investment_capacity_ratio",
    "initial_investment",
    "risk_score",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual"
]:
    lp_small[c] = pd.to_numeric(
        lp_small[c],
        errors="coerce"
    )

monthly_small["period"] = pd.to_datetime(
    monthly_small["period"],
    errors="coerce"
)

monthly_small = monthly_small.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# =============================================================================
# 4. DATA QUALITY
# =============================================================================

print("\n" + "=" * 80)
print("1. DATA QUALITY")
print("=" * 80)

print("LP unique users:",
      lp_small["user_id"].nunique())

print("Monthly unique users:",
      monthly_small["user_id"].nunique())

print(
    "Duplicate user-period rows:",
    monthly_small.duplicated(
        ["user_id", "period"]
    ).sum()
)

print(
    "Missing monthly values:",
    monthly_small.isna().sum().sum()
)

print(
    "Missing LP values:",
    lp_small.isna().sum().sum()
)

# =============================================================================
# 5. VERIFY SURPLUS EQUATION
# =============================================================================

print("\n" + "=" * 80)
print("2. SURPLUS DEPENDENCY")
print("=" * 80)

monthly_small["calculated_surplus"] = (
    monthly_small["monthly_income_dynamic"]
    -
    monthly_small["monthly_expenditure_dynamic"]
    -
    monthly_small["monthly_emi"]
)

monthly_small["surplus_error"] = (
    monthly_small["monthly_surplus_dynamic"]
    -
    monthly_small["calculated_surplus"]
)

print(
    "Mean absolute error:",
    monthly_small["surplus_error"].abs().mean()
)

print(
    "Maximum absolute error:",
    monthly_small["surplus_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        monthly_small["surplus_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(monthly_small)
)

# =============================================================================
# 6. VERIFY POSITIVE CASH FLOW
# =============================================================================

print("\n" + "=" * 80)
print("3. POSITIVE CASH FLOW DEPENDENCY")
print("=" * 80)

monthly_small["calculated_positive_cash_flow"] = (
    monthly_small["monthly_surplus_dynamic"]
    .clip(lower=0)
)

monthly_small["positive_cash_flow_error"] = (
    monthly_small["positive_cash_flow"]
    -
    monthly_small["calculated_positive_cash_flow"]
)

print(
    "Mean absolute error:",
    monthly_small["positive_cash_flow_error"].abs().mean()
)

print(
    "Maximum absolute error:",
    monthly_small["positive_cash_flow_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        monthly_small["positive_cash_flow_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(monthly_small)
)

# =============================================================================
# 7. MERGE ONLY PARAMETERS NOT ALREADY IN MONTHLY
# =============================================================================

# IMPORTANT:
# initial_investment already exists in monthly_small.
# Therefore we intentionally do NOT merge it from LP here.

lp_parameters = lp_small[
    [
        "user_id",
        "goal_allocation_factor",
        "investment_capacity_ratio",
        "risk_score"
    ]
].copy()

m = monthly_small.merge(
    lp_parameters,
    on="user_id",
    how="left"
)

print("\nMerged shape:", m.shape)

# =============================================================================
# 8. RECONSTRUCT EXISTING GOAL FUNDING
# =============================================================================

print("\n" + "=" * 80)
print("4. GOAL FUNDING DEPENDENCY")
print("=" * 80)

m["reconstructed_goal_funding_monthly"] = (
    m["positive_cash_flow"]
    *
    m["goal_allocation_factor"]
)

goal_by_user = (
    m.groupby("user_id")
    .agg(
        reconstructed_goal_funding=(
            "reconstructed_goal_funding_monthly",
            "sum"
        ),
        total_positive_cash_flow=(
            "positive_cash_flow",
            "sum"
        ),
        final_portfolio_value=(
            "portfolio_value",
            "last"
        ),
        initial_investment=(
            "initial_investment",
            "first"
        ),
        mean_portfolio_return=(
            "portfolio_return",
            "mean"
        )
    )
    .reset_index()
)

goal_by_user = goal_by_user.merge(
    lp_small[
        [
            "user_id",
            "goal_horizon_funding_actual",
            "target_amount",
            "goal_shortfall_actual",
            "goal_achieved_on_time_actual",
            "investment_capacity_ratio",
            "risk_score"
        ]
    ],
    on="user_id",
    how="left"
)

goal_by_user["goal_formula_error"] = (
    goal_by_user["reconstructed_goal_funding"]
    -
    goal_by_user["goal_horizon_funding_actual"]
)

print(
    "Goal funding mean absolute error:",
    goal_by_user["goal_formula_error"].abs().mean()
)

print(
    "Goal funding maximum absolute error:",
    goal_by_user["goal_formula_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        goal_by_user["goal_formula_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(goal_by_user)
)

# =============================================================================
# 9. TEST PORTFOLIO → GOAL FUNDING STRUCTURAL DEPENDENCY
# =============================================================================

print("\n" + "=" * 80)
print("5. PORTFOLIO → GOAL FUNDING")
print("=" * 80)

corr_columns = [
    "reconstructed_goal_funding",
    "final_portfolio_value",
    "initial_investment",
    "investment_capacity_ratio",
    "risk_score",
    "mean_portfolio_return"
]

print(
    goal_by_user[corr_columns].corr()
)

print("""
Interpretation:
Correlation does not prove causation.

The important structural finding is whether portfolio_value
is present in the exact goal-funding equation.

Current exact equation:

GoalFunding_t =
PositiveCashFlow_t × GoalAllocationFactor
""")

# =============================================================================
# 10. TEST INVESTMENT CAPACITY → GOAL FUNDING
# =============================================================================

print("\n" + "=" * 80)
print("6. INVESTMENT CAPACITY → GOAL FUNDING")
print("=" * 80)

goal_without_investment_capacity = (
    m["positive_cash_flow"]
    *
    m["goal_allocation_factor"]
)

difference = (
    m["reconstructed_goal_funding_monthly"]
    -
    goal_without_investment_capacity
)

print(
    "Total absolute difference:",
    difference.abs().sum()
)

print(
    "Maximum difference:",
    difference.abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        difference.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(m)
)

# =============================================================================
# 11. FIRST-MONTH PORTFOLIO INITIALIZATION
# =============================================================================

print("\n" + "=" * 80)
print("7. FIRST-MONTH PORTFOLIO INITIALIZATION")
print("=" * 80)

first = (
    m.sort_values(
        ["user_id", "period"]
    )
    .groupby("user_id", as_index=False)
    .first()
)

first["implied_first_portfolio"] = (
    first["initial_investment"]
    *
    (1 + first["portfolio_return"])
)

first["first_portfolio_error"] = (
    first["portfolio_value"]
    -
    first["implied_first_portfolio"]
)

print(
    "Mean absolute error:",
    first["first_portfolio_error"].abs().mean()
)

print(
    "Maximum absolute error:",
    first["first_portfolio_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        first["first_portfolio_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(first)
)

# =============================================================================
# 12. STRUCTURAL LP VARIABLE INVENTORY
# =============================================================================

print("\n" + "=" * 80)
print("8. STRUCTURAL LP VARIABLE INVENTORY")
print("=" * 80)

inventory = pd.DataFrame([
    [
        "G_t",
        "Goal funding",
        "Positive cash flow × goal allocation factor",
        "SUPPORTED"
    ],
    [
        "I_t",
        "Monthly investment contribution",
        "No explicit monthly contribution exists",
        "DO NOT INVENT"
    ],
    [
        "C_t",
        "Residual cash",
        "Can be mathematically derived",
        "DERIVED ONLY"
    ],
    [
        "D",
        "Goal shortfall",
        "Target minus goal funding",
        "SUPPORTED"
    ],
    [
        "Portfolio_t",
        "Portfolio state",
        "Observed portfolio_value",
        "STATE VARIABLE"
    ],
    [
        "InitialInvestment",
        "Starting portfolio value",
        "Observed initial_investment",
        "PARAMETER"
    ]
], columns=[
    "variable",
    "meaning",
    "data_support",
    "status"
])

print(
    inventory.to_string(index=False)
)

# =============================================================================
# 13. FINAL STRUCTURAL CONCLUSION
# =============================================================================

print("\n" + "=" * 80)
print("9. STRUCTURAL CONCLUSION")
print("=" * 80)

print("""
ESTABLISHED:

1. Dynamic income, expenditure and EMI determine surplus.

2. Positive cash flow = max(monthly surplus, 0).

3. Existing goal funding =
   positive cash flow × goal allocation factor.

4. Portfolio value evolves independently as:
   Portfolio_t = Portfolio_(t-1) × (1 + portfolio_return_t)

5. Initial investment is a starting portfolio state.

6. No explicit monthly investment contribution field exists.

7. Therefore, I_t must NOT be treated as an observed historical
   monthly contribution.

8. The LP should not invent a contribution mechanism.

9. Any optimization involving portfolio allocation must use an
   explicitly justified mathematical linkage rather than assuming
   that investment capacity automatically changes goal funding.
""")

# =============================================================================
# 14. SAVE
# =============================================================================

OUTPUT_DIR = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

audit_path = os.path.join(
    OUTPUT_DIR,
    "lp_5o_decision_variable_dependency_audit.csv"
)

inventory_path = os.path.join(
    OUTPUT_DIR,
    "lp_5o_structural_variable_inventory.csv"
)

goal_by_user_path = os.path.join(
    OUTPUT_DIR,
    "lp_5o_goal_portfolio_dependency_by_user.csv"
)

audit_rows = [
    [
        "surplus_mean_abs_error",
        monthly_small["surplus_error"].abs().mean()
    ],
    [
        "surplus_max_abs_error",
        monthly_small["surplus_error"].abs().max()
    ],
    [
        "positive_cash_flow_mean_abs_error",
        monthly_small["positive_cash_flow_error"].abs().mean()
    ],
    [
        "positive_cash_flow_max_abs_error",
        monthly_small["positive_cash_flow_error"].abs().max()
    ],
    [
        "goal_funding_mean_abs_error",
        goal_by_user["goal_formula_error"].abs().mean()
    ],
    [
        "goal_funding_max_abs_error",
        goal_by_user["goal_formula_error"].abs().max()
    ],
    [
        "first_portfolio_mean_abs_error",
        first["first_portfolio_error"].abs().mean()
    ],
    [
        "first_portfolio_max_abs_error",
        first["first_portfolio_error"].abs().max()
    ]
]

pd.DataFrame(
    audit_rows,
    columns=["metric", "value"]
).to_csv(
    audit_path,
    index=False
)

inventory.to_csv(
    inventory_path,
    index=False
)

goal_by_user.to_csv(
    goal_by_user_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5O COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(inventory_path)
print(goal_by_user_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO MONTHLY INVESTMENT CONTRIBUTION WAS INVENTED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5O — LP DECISION-VARIABLE DEPENDENCY AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Missing LP columns: []
Missing monthly columns: []

================================================================================
1. DATA QUALITY
================================================================================
LP unique users: 10000
Monthly unique users: 10000
Duplicate user-period rows: 0
Missing monthly values: 0
Missing LP values: 0

================================================================================
2. SURPLUS DEPENDENCY
================================================================================
Mean absolute error: 4.381543353831896e-12
Maximum absolute error: 6.984919309616089e-10
Matches <= 1e-6: 1430000 / 1430000

================================================================================
3. POSITIVE CASH FLOW DEPENDENCY
================================================================================
Mean absolute error: 0.0
Maximum absolute error: 0.0
Matches <= 1e-6: 1430000 / 1430000

Merged shape: (1430000, 17)

================================================================================
4. GOAL FUNDING DEPENDENCY
================================================================================
Goal funding mean absolute error: 1814572.1247206805
Goal funding maximum absolute error: 72058294.28072314
Matches <= 1e-6: 817 / 10000

================================================================================
5. PORTFOLIO → GOAL FUNDING
================================================================================
                            reconstructed_goal_funding  final_portfolio_value  \
reconstructed_goal_funding                    1.000000               0.742033
final_portfolio_value                         0.742033               1.000000
initial_investment                            0.737747               0.991995
investment_capacity_ratio                     0.535748               0.445814
risk_score                                    0.448736               0.397545
mean_portfolio_return                         0.448736               0.397545

                            initial_investment  investment_capacity_ratio  \
reconstructed_goal_funding            0.737747                   0.535748
final_portfolio_value                 0.991995                   0.445814
initial_investment                    1.000000                   0.421953
investment_capacity_ratio             0.421953                   1.000000
risk_score                            0.373067                   0.913235
mean_portfolio_return                 0.373067                   0.913235

                            risk_score  mean_portfolio_return
reconstructed_goal_funding    0.448736               0.448736
final_portfolio_value         0.397545               0.397545
initial_investment            0.373067               0.373067
investment_capacity_ratio     0.913235               0.913235
risk_score                    1.000000               1.000000
mean_portfolio_return         1.000000               1.000000

Interpretation:
Correlation does not prove causation.

The important structural finding is whether portfolio_value
is present in the exact goal-funding equation.

Current exact equation:

GoalFunding_t =
PositiveCashFlow_t × GoalAllocationFactor


================================================================================
6. INVESTMENT CAPACITY → GOAL FUNDING
================================================================================
Total absolute difference: 0.0
Maximum difference: 0.0
Matches <= 1e-6: 1430000 / 1430000

================================================================================
7. FIRST-MONTH PORTFOLIO INITIALIZATION
================================================================================
Mean absolute error: 3.8873110952408755e-12
Maximum absolute error: 4.656612873077393e-10
Matches <= 1e-6: 10000 / 10000

================================================================================
8. STRUCTURAL LP VARIABLE INVENTORY
================================================================================
         variable                         meaning                                data_support         status
              G_t                    Goal funding Positive cash flow × goal allocation factor      SUPPORTED
              I_t Monthly investment contribution     No explicit monthly contribution exists  DO NOT INVENT
              C_t                   Residual cash               Can be mathematically derived   DERIVED ONLY
                D                  Goal shortfall                   Target minus goal funding      SUPPORTED
      Portfolio_t                 Portfolio state                    Observed portfolio_value STATE VARIABLE
InitialInvestment        Starting portfolio value                 Observed initial_investment      PARAMETER

================================================================================
9. STRUCTURAL CONCLUSION
================================================================================

ESTABLISHED:

1. Dynamic income, expenditure and EMI determine surplus.

2. Positive cash flow = max(monthly surplus, 0).

3. Existing goal funding =
   positive cash flow × goal allocation factor.

4. Portfolio value evolves independently as:
   Portfolio_t = Portfolio_(t-1) × (1 + portfolio_return_t)

5. Initial investment is a starting portfolio state.

6. No explicit monthly investment contribution field exists.

7. Therefore, I_t must NOT be treated as an observed historical
   monthly contribution.

8. The LP should not invent a contribution mechanism.

9. Any optimization involving portfolio allocation must use an
   explicitly justified mathematical linkage rather than assuming
   that investment capacity automatically changes goal funding.


================================================================================
STEP 5O COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5o_decision_variable_dependency_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5o_structural_variable_inventory.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5o_goal_portfolio_dependency_by_user.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO MONTHLY INVESTMENT CONTRIBUTION WAS INVENTED.
NO OBJECTIVE FUNCTION WAS ASSUMED.

In [109]:
# =============================================================================
# STEP 5P — HORIZON-RESTRICTED LP FORMULATION AUDIT
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5P — HORIZON-RESTRICTED LP FORMULATION AUDIT")
print("=" * 80)

# -----------------------------------------------------------------------------
# 1. LOAD
# -----------------------------------------------------------------------------

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# -----------------------------------------------------------------------------
# 2. PREPARE LP DATA
# -----------------------------------------------------------------------------

lp_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "investment_capacity_ratio",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_funding_ratio",
    "goal_achieved_on_time_actual"
]

missing = [c for c in lp_cols if c not in lp.columns]

if missing:
    raise ValueError(f"Missing LP columns: {missing}")

lp2 = lp[lp_cols].copy()

for c in lp_cols[1:]:
    lp2[c] = pd.to_numeric(lp2[c], errors="coerce")

# -----------------------------------------------------------------------------
# 3. PREPARE MONTHLY DATA
# -----------------------------------------------------------------------------

monthly_cols = [
    "user_id",
    "period",
    "monthly_surplus_dynamic",
    "positive_cash_flow",
    "portfolio_value",
    "portfolio_return"
]

missing = [c for c in monthly_cols if c not in monthly.columns]

if missing:
    raise ValueError(f"Missing monthly columns: {missing}")

m = monthly[monthly_cols].copy()

m["period"] = pd.to_datetime(
    m["period"],
    errors="coerce"
)

for c in [
    "monthly_surplus_dynamic",
    "positive_cash_flow",
    "portfolio_value",
    "portfolio_return"
]:
    m[c] = pd.to_numeric(
        m[c],
        errors="coerce"
    )

m = m.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# Simulation month number: 1,2,3,...143 for every user
m["simulation_month"] = (
    m.groupby("user_id")
    .cumcount()
    + 1
)

# -----------------------------------------------------------------------------
# 4. MERGE USER HORIZON
# -----------------------------------------------------------------------------

m = m.merge(
    lp2[
        [
            "user_id",
            "goal_horizon_months",
            "target_amount",
            "goal_allocation_factor",
            "goal_specific_monthly_capacity",
            "investment_capacity_ratio",
            "goal_horizon_funding_actual",
            "goal_shortfall_actual",
            "goal_funding_ratio",
            "goal_achieved_on_time_actual"
        ]
    ],
    on="user_id",
    how="left"
)

print("\nMerged shape:", m.shape)

# -----------------------------------------------------------------------------
# 5. RESTRICT TO EACH USER'S ACTUAL HORIZON
# -----------------------------------------------------------------------------

h = m[
    m["simulation_month"]
    <=
    m["goal_horizon_months"]
].copy()

print("\n" + "=" * 80)
print("1. HORIZON RESTRICTION")
print("=" * 80)

print(
    "Rows within user-specific horizons:",
    len(h)
)

expected_rows = int(
    lp2["goal_horizon_months"].sum()
)

print(
    "Expected horizon rows:",
    expected_rows
)

print(
    "Minimum horizon:",
    int(lp2["goal_horizon_months"].min())
)

print(
    "Maximum horizon:",
    int(lp2["goal_horizon_months"].max())
)

# -----------------------------------------------------------------------------
# 6. EXACT EXISTING FUNDING FORMULA
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("2. EXACT EXISTING GOAL FUNDING")
print("=" * 80)

h["goal_funding_reconstructed"] = (
    h["positive_cash_flow"]
    *
    h["goal_allocation_factor"]
)

funding = (
    h.groupby("user_id")["goal_funding_reconstructed"]
    .sum()
    .rename("reconstructed_funding")
    .reset_index()
)

funding = funding.merge(
    lp2[
        [
            "user_id",
            "goal_horizon_funding_actual",
            "target_amount",
            "goal_shortfall_actual",
            "goal_funding_ratio",
            "goal_achieved_on_time_actual"
        ]
    ],
    on="user_id",
    how="left"
)

funding["funding_error"] = (
    funding["reconstructed_funding"]
    -
    funding["goal_horizon_funding_actual"]
)

print(
    "Mean absolute difference:",
    funding["funding_error"].abs().mean()
)

print(
    "Maximum absolute difference:",
    funding["funding_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        funding["funding_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(funding)
)

# -----------------------------------------------------------------------------
# 7. SHORTFALL VERIFICATION
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("3. SHORTFALL EQUATION")
print("=" * 80)

funding["calculated_shortfall"] = (
    funding["target_amount"]
    -
    funding["goal_horizon_funding_actual"]
).clip(lower=0)

funding["shortfall_error"] = (
    funding["calculated_shortfall"]
    -
    funding["goal_shortfall_actual"]
)

print(
    "Mean absolute error:",
    funding["shortfall_error"].abs().mean()
)

print(
    "Maximum absolute error:",
    funding["shortfall_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        funding["shortfall_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(funding)
)

# -----------------------------------------------------------------------------
# 8. FUNDING RATIO VERIFICATION
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("4. FUNDING RATIO EQUATION")
print("=" * 80)

funding["calculated_ratio"] = np.where(
    funding["target_amount"] > 0,
    funding["goal_horizon_funding_actual"]
    /
    funding["target_amount"],
    0
)

funding["ratio_error"] = (
    funding["calculated_ratio"]
    -
    funding["goal_funding_ratio"]
)

print(
    "Mean absolute error:",
    funding["ratio_error"].abs().mean()
)

print(
    "Maximum absolute error:",
    funding["ratio_error"].abs().max()
)

print(
    "Matches <= 1e-6:",
    (
        funding["ratio_error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(funding)
)

# -----------------------------------------------------------------------------
# 9. DATA-SUPPORTED MAXIMUM GOAL FUNDING
#
# The most direct cash-flow bound is:
#
#       0 <= G_t <= PositiveCashFlow_t
#
# We intentionally DO NOT use goal_specific_monthly_capacity as a dynamic
# monthly bound because it is a static user-level parameter.
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("5. DATA-SUPPORTED GOAL FUNDING BOUND")
print("=" * 80)

h["maximum_goal_funding"] = (
    h["positive_cash_flow"]
)

max_funding = (
    h.groupby("user_id")["maximum_goal_funding"]
    .sum()
    .rename("max_goal_funding_cash_bound")
    .reset_index()
)

max_funding = max_funding.merge(
    lp2[
        [
            "user_id",
            "target_amount",
            "goal_horizon_funding_actual",
            "goal_allocation_factor"
        ]
    ],
    on="user_id",
    how="left"
)

max_funding["potential_shortfall"] = (
    max_funding["target_amount"]
    -
    max_funding["max_goal_funding_cash_bound"]
).clip(lower=0)

max_funding["potentially_feasible"] = (
    max_funding["max_goal_funding_cash_bound"]
    >=
    max_funding["target_amount"]
)

max_funding["additional_capacity"] = (
    max_funding["max_goal_funding_cash_bound"]
    -
    max_funding["goal_horizon_funding_actual"]
).clip(lower=0)

print(
    max_funding[
        [
            "max_goal_funding_cash_bound",
            "target_amount",
            "goal_horizon_funding_actual",
            "potential_shortfall"
        ]
    ].describe()
)

print(
    "\nPotentially feasible:",
    max_funding["potentially_feasible"].sum(),
    "/",
    len(max_funding)
)

print(
    "Potentially infeasible:",
    (~max_funding["potentially_feasible"]).sum(),
    "/",
    len(max_funding)
)

print(
    "\nUsers with additional cash-flow capacity:",
    (
        max_funding["additional_capacity"] > 1e-6
    ).sum()
)

# -----------------------------------------------------------------------------
# 10. EXISTING POLICY SUCCESS
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("6. EXISTING POLICY FEASIBILITY")
print("=" * 80)

calculated_success = (
    funding["goal_horizon_funding_actual"]
    >=
    funding["target_amount"]
)

stored_success = (
    funding["goal_achieved_on_time_actual"]
    .astype(bool)
)

print(
    "Calculated successful users:",
    calculated_success.sum(),
    "/",
    len(calculated_success)
)

print(
    "Calculated unsuccessful users:",
    (~calculated_success).sum(),
    "/",
    len(calculated_success)
)

print(
    "Stored success agreement:",
    (
        calculated_success == stored_success
    ).sum(),
    "/",
    len(calculated_success)
)

# -----------------------------------------------------------------------------
# 11. REPRESENTATIVE USERS
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("7. REPRESENTATIVE USERS")
print("=" * 80)

ids = [
    "USER_00001",
    "USER_00002",
    "USER_00003",
    "USER_00004",
    "USER_00005",
    "USER_00006",
    "USER_00007",
    "USER_00008",
    "USER_00009",
    "USER_00010"
]

rep = max_funding[
    max_funding["user_id"].isin(ids)
].copy()

print(
    rep[
        [
            "user_id",
            "target_amount",
            "goal_horizon_funding_actual",
            "max_goal_funding_cash_bound",
            "additional_capacity",
            "potential_shortfall",
            "goal_allocation_factor"
        ]
    ].to_string(index=False)
)

# -----------------------------------------------------------------------------
# 12. FORMULATION SUMMARY
# -----------------------------------------------------------------------------

print("\n" + "=" * 80)
print("8. DATA-SUPPORTED FORMULATION")
print("=" * 80)

print("""
For user u and month t within goal horizon H_u:

PositiveCashFlow(u,t)
    = max(MonthlySurplusDynamic(u,t), 0)

ExistingGoalFunding(u,t)
    = PositiveCashFlow(u,t)
      × GoalAllocationFactor(u)

ExistingTotalGoalFunding(u)
    = SUM[t=1..H_u] ExistingGoalFunding(u,t)

ExistingShortfall(u)
    = max(Target(u) - ExistingTotalGoalFunding(u), 0)

ExistingSuccess(u)
    = 1 if ExistingTotalGoalFunding(u) >= Target(u)

The directly data-supported generic goal-funding bound is:

    0 <= G(u,t) <= PositiveCashFlow(u,t)

No monthly investment contribution variable is introduced.

Portfolio remains a separate state:

    Portfolio(u,t)
      = Portfolio(u,t-1)
        × (1 + PortfolioReturn(u,t))
""")

# -----------------------------------------------------------------------------
# 13. SAVE
# -----------------------------------------------------------------------------

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT, exist_ok=True)

audit_path = os.path.join(
    OUT,
    "lp_5p_horizon_formulation_audit.csv"
)

funding_path = os.path.join(
    OUT,
    "lp_5p_horizon_funding_by_user.csv"
)

bound_path = os.path.join(
    OUT,
    "lp_5p_cash_flow_goal_funding_bound.csv"
)

audit = pd.DataFrame([
    ["horizon_rows", len(h)],
    ["expected_horizon_rows", expected_rows],
    [
        "funding_mean_abs_error",
        funding["funding_error"].abs().mean()
    ],
    [
        "funding_max_abs_error",
        funding["funding_error"].abs().max()
    ],
    [
        "funding_matches_1e-6",
        (
            funding["funding_error"].abs()
            <= 1e-6
        ).sum()
    ],
    [
        "shortfall_mean_abs_error",
        funding["shortfall_error"].abs().mean()
    ],
    [
        "shortfall_max_abs_error",
        funding["shortfall_error"].abs().max()
    ],
    [
        "ratio_mean_abs_error",
        funding["ratio_error"].abs().mean()
    ],
    [
        "ratio_max_abs_error",
        funding["ratio_error"].abs().max()
    ],
    [
        "cash_bound_feasible_users",
        max_funding["potentially_feasible"].sum()
    ],
    [
        "cash_bound_infeasible_users",
        (~max_funding["potentially_feasible"]).sum()
    ],
    [
        "additional_capacity_users",
        (
            max_funding["additional_capacity"]
            > 1e-6
        ).sum()
    ],
    [
        "existing_policy_success_users",
        calculated_success.sum()
    ]
], columns=["metric", "value"])

audit.to_csv(audit_path, index=False)
funding.to_csv(funding_path, index=False)
max_funding.to_csv(bound_path, index=False)

print("\n" + "=" * 80)
print("STEP 5P COMPLETE")
print("=" * 80)

print("\nSaved:")
print(audit_path)
print(funding_path)
print(bound_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO INVESTMENT CONTRIBUTION WAS INVENTED.")
print("NO OBJECTIVE FUNCTION WAS ASSUMED.")

================================================================================
STEP 5P — HORIZON-RESTRICTED LP FORMULATION AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Merged shape: (1430000, 16)

================================================================================
1. HORIZON RESTRICTION
================================================================================
Rows within user-specific horizons: 626970
Expected horizon rows: 626970
Minimum horizon: 6
Maximum horizon: 120

================================================================================
2. EXACT EXISTING GOAL FUNDING
================================================================================
Mean absolute difference: 2.7003985403339926e-11
Maximum absolute difference: 3.725290298461914e-09
Matches <= 1e-6: 10000 / 10000

================================================================================
3. SHORTFALL EQUATION
================================================================================
Mean absolute error: 9.550831236992962e-13
Maximum absolute error: 1.1641532182693481e-10
Matches <= 1e-6: 10000 / 10000

================================================================================
4. FUNDING RATIO EQUATION
================================================================================
Mean absolute error: 3.280102104779312e-16
Maximum absolute error: 1.4210854715202004e-14
Matches <= 1e-6: 10000 / 10000

================================================================================
5. DATA-SUPPORTED GOAL FUNDING BOUND
================================================================================
       max_goal_funding_cash_bound  target_amount  \
count                 1.000000e+04   1.000000e+04
mean                  1.189898e+06   1.383538e+05
std                   2.213899e+06   1.211024e+05
min                   0.000000e+00   2.824526e+03
25%                   9.665485e+04   7.189787e+04
50%                   4.777859e+05   1.073131e+05
75%                   1.440379e+06   1.595261e+05
max                   6.659288e+07   1.900464e+06

       goal_horizon_funding_actual  potential_shortfall
count                 1.000000e+04         10000.000000
mean                  9.449648e+05         22240.827452
std                   2.156857e+06         59426.872318
min                   0.000000e+00             0.000000
25%                   2.676139e+04             0.000000
50%                   2.364985e+05             0.000000
75%                   9.683717e+05             0.000000
max                   6.659288e+07        913206.956331

Potentially feasible: 7582 / 10000
Potentially infeasible: 2418 / 10000

Users with additional cash-flow capacity: 8534

================================================================================
6. EXISTING POLICY FEASIBILITY
================================================================================
Calculated successful users: 6451 / 10000
Calculated unsuccessful users: 3549 / 10000
Stored success agreement: 10000 / 10000

================================================================================
7. REPRESENTATIVE USERS
================================================================================
   user_id  target_amount  goal_horizon_funding_actual  max_goal_funding_cash_bound  additional_capacity  potential_shortfall  goal_allocation_factor
USER_00001  115357.183592                 5.811302e+05                 8.329228e+05        251792.562667             0.000000                 0.69770
USER_00002   59340.387689                 0.000000e+00                 0.000000e+00             0.000000         59340.387689                 0.10655
USER_00003   99893.237726                 4.093773e+04                 1.349744e+05         94036.646294             0.000000                 0.30330
USER_00004   75476.307623                 4.566919e+04                 1.870155e+05        141346.331495             0.000000                 0.24420
USER_00005  206040.342056                 7.318348e+06                 7.771422e+06        453073.892390             0.000000                 0.94170
USER_00006  110291.964774                 3.502230e+05                 4.254410e+05         75217.972356             0.000000                 0.82320
USER_00007  128020.414837                 2.348219e+06                 2.694147e+06        345928.474554             0.000000                 0.87160
USER_00008  269916.171830                 0.000000e+00                 0.000000e+00             0.000000        269916.171830                 0.10655
USER_00009  182600.732773                 1.616717e+06                 1.847887e+06        231170.704431             0.000000                 0.87490
USER_00010   96702.526658                 5.423986e+04                 1.324862e+05         78246.363163             0.000000                 0.40940

================================================================================
8. DATA-SUPPORTED FORMULATION
================================================================================

For user u and month t within goal horizon H_u:

PositiveCashFlow(u,t)
    = max(MonthlySurplusDynamic(u,t), 0)

ExistingGoalFunding(u,t)
    = PositiveCashFlow(u,t)
      × GoalAllocationFactor(u)

ExistingTotalGoalFunding(u)
    = SUM[t=1..H_u] ExistingGoalFunding(u,t)

ExistingShortfall(u)
    = max(Target(u) - ExistingTotalGoalFunding(u), 0)

ExistingSuccess(u)
    = 1 if ExistingTotalGoalFunding(u) >= Target(u)

The directly data-supported generic goal-funding bound is:

    0 <= G(u,t) <= PositiveCashFlow(u,t)

No monthly investment contribution variable is introduced.

Portfolio remains a separate state:

    Portfolio(u,t)
      = Portfolio(u,t-1)
        × (1 + PortfolioReturn(u,t))


================================================================================
STEP 5P COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5p_horizon_formulation_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5p_horizon_funding_by_user.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5p_cash_flow_goal_funding_bound.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO INVESTMENT CONTRIBUTION WAS INVENTED.
NO OBJECTIVE FUNCTION WAS ASSUMED.

In [110]:
# =============================================================================
# STEP 5Q — OBJECTIVE FUNCTION & OPTIMIZATION POLICY AUDIT
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5Q — OBJECTIVE FUNCTION & OPTIMIZATION POLICY AUDIT")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. PREPARE LP DATA
# =============================================================================

lp_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_allocation_factor",
    "goal_specific_monthly_capacity",
    "investment_capacity_ratio",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_funding_ratio",
    "goal_achieved_on_time_actual"
]

lp2 = lp[lp_cols].copy()

for c in lp_cols[1:]:
    lp2[c] = pd.to_numeric(
        lp2[c],
        errors="coerce"
    )

# =============================================================================
# 3. PREPARE MONTHLY DATA
# =============================================================================

monthly_cols = [
    "user_id",
    "period",
    "monthly_surplus_dynamic",
    "positive_cash_flow"
]

m = monthly[monthly_cols].copy()

m["period"] = pd.to_datetime(
    m["period"],
    errors="coerce"
)

for c in [
    "monthly_surplus_dynamic",
    "positive_cash_flow"
]:
    m[c] = pd.to_numeric(
        m[c],
        errors="coerce"
    )

m = m.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# Simulation month within user
m["simulation_month"] = (
    m.groupby("user_id")
    .cumcount()
    + 1
)

# =============================================================================
# 4. MERGE USER PARAMETERS
# =============================================================================

m = m.merge(
    lp2[
        [
            "user_id",
            "goal_horizon_months",
            "target_amount",
            "goal_allocation_factor",
            "goal_specific_monthly_capacity",
            "investment_capacity_ratio",
            "goal_horizon_funding_actual",
            "goal_shortfall_actual",
            "goal_funding_ratio",
            "goal_achieved_on_time_actual"
        ]
    ],
    on="user_id",
    how="left"
)

# =============================================================================
# 5. RESTRICT TO GOAL HORIZON
# =============================================================================

h = m[
    m["simulation_month"]
    <=
    m["goal_horizon_months"]
].copy()

print("\nHorizon rows:", len(h))

# =============================================================================
# 6. EXISTING POLICY
# =============================================================================

h["existing_policy_funding"] = (
    h["positive_cash_flow"]
    *
    h["goal_allocation_factor"]
)

existing = (
    h.groupby("user_id")
    .agg(
        existing_goal_funding=(
            "existing_policy_funding",
            "sum"
        ),
        total_positive_cash_flow=(
            "positive_cash_flow",
            "sum"
        ),
        target_amount=(
            "target_amount",
            "first"
        ),
        goal_factor=(
            "goal_allocation_factor",
            "first"
        )
    )
    .reset_index()
)

existing["existing_shortfall"] = (
    existing["target_amount"]
    -
    existing["existing_goal_funding"]
).clip(lower=0)

existing["existing_success"] = (
    existing["existing_goal_funding"]
    >=
    existing["target_amount"]
)

# =============================================================================
# 7. OBJECTIVE A — MAXIMUM GOAL FUNDING
# =============================================================================
#
# If:
#
#       0 <= G_t <= PositiveCashFlow_t
#
# and the objective is:
#
#       MAX SUM(G_t)
#
# then the optimal solution is:
#
#       G_t = PositiveCashFlow_t
#
# for every month.
#
# This is calculated directly here.
# No solver is run.
# =============================================================================

print("\n" + "=" * 80)
print("1. OBJECTIVE A — MAXIMIZE TOTAL GOAL FUNDING")
print("=" * 80)

existing["objective_A_max_goal_funding"] = (
    existing["total_positive_cash_flow"]
)

existing["objective_A_shortfall"] = (
    existing["target_amount"]
    -
    existing["objective_A_max_goal_funding"]
).clip(lower=0)

existing["objective_A_success"] = (
    existing["objective_A_max_goal_funding"]
    >=
    existing["target_amount"]
)

print(
    existing[
        [
            "objective_A_max_goal_funding",
            "target_amount",
            "objective_A_shortfall"
        ]
    ].describe()
)

print(
    "\nObjective A potentially successful:",
    existing["objective_A_success"].sum(),
    "/",
    len(existing)
)

print(
    "Objective A infeasible:",
    (~existing["objective_A_success"]).sum(),
    "/",
    len(existing)
)

# =============================================================================
# 8. OBJECTIVE B — MINIMIZE SHORTFALL
# =============================================================================
#
# Model:
#
#       MIN D
#
# subject to:
#
#       SUM(G_t) + D = Target
#
#       0 <= G_t <= PositiveCashFlow_t
#
# D >= 0
#
# This produces the same minimum shortfall as Objective A.
# =============================================================================

print("\n" + "=" * 80)
print("2. OBJECTIVE B — MINIMIZE GOAL SHORTFALL")
print("=" * 80)

existing["objective_B_min_shortfall"] = (
    existing["objective_A_shortfall"]
)

existing["objective_B_success"] = (
    existing["objective_B_min_shortfall"]
    <=
    1e-9
)

print(
    existing[
        [
            "objective_B_min_shortfall"
        ]
    ].describe()
)

print(
    "\nObjective B successful:",
    existing["objective_B_success"].sum(),
    "/",
    len(existing)
)

# Verify A and B equivalence
existing["A_B_difference"] = (
    existing["objective_A_shortfall"]
    -
    existing["objective_B_min_shortfall"]
)

print(
    "\nA/B shortfall difference max:",
    existing["A_B_difference"].abs().max()
)

# =============================================================================
# 9. OBJECTIVE C — PRESERVE EXISTING POLICY
# =============================================================================
#
# Existing policy:
#
#       G_t <= PositiveCashFlow_t × GoalAllocationFactor
#
# Maximizing G_t under this bound simply reproduces the historical funding.
#
# =============================================================================

print("\n" + "=" * 80)
print("3. OBJECTIVE C — EXISTING POLICY PRESERVATION")
print("=" * 80)

existing["objective_C_funding"] = (
    existing["existing_goal_funding"]
)

existing["objective_C_shortfall"] = (
    existing["target_amount"]
    -
    existing["objective_C_funding"]
).clip(lower=0)

existing["objective_C_success"] = (
    existing["objective_C_funding"]
    >=
    existing["target_amount"]
)

print(
    "\nObjective C successful:",
    existing["objective_C_success"].sum(),
    "/",
    len(existing)
)

print(
    "Objective C unsuccessful:",
    (~existing["objective_C_success"]).sum(),
    "/",
    len(existing)
)

# =============================================================================
# 10. COMPARE OBJECTIVES
# =============================================================================

print("\n" + "=" * 80)
print("4. OBJECTIVE COMPARISON")
print("=" * 80)

objective_summary = pd.DataFrame([
    [
        "A — Maximize goal funding",
        existing["objective_A_max_goal_funding"].mean(),
        existing["objective_A_shortfall"].mean(),
        existing["objective_A_success"].sum(),
        len(existing)
    ],
    [
        "B — Minimize shortfall",
        (
            existing["target_amount"]
            -
            existing["objective_B_min_shortfall"]
        ).mean(),
        existing["objective_B_min_shortfall"].mean(),
        existing["objective_B_success"].sum(),
        len(existing)
    ],
    [
        "C — Preserve existing policy",
        existing["objective_C_funding"].mean(),
        existing["objective_C_shortfall"].mean(),
        existing["objective_C_success"].sum(),
        len(existing)
    ]
], columns=[
    "objective",
    "mean_goal_funding",
    "mean_shortfall",
    "successful_users",
    "total_users"
])

print(
    objective_summary.to_string(index=False)
)

# =============================================================================
# 11. ADDITIONAL USERS REACHED BY OPTIMIZATION
# =============================================================================

print("\n" + "=" * 80)
print("5. USERS POTENTIALLY REACHED BY BROADER OPTIMIZATION")
print("=" * 80)

additional_success = (
    existing["objective_A_success"]
    &
    ~existing["objective_C_success"]
)

print(
    "Existing policy successful:",
    existing["objective_C_success"].sum()
)

print(
    "Cash-flow-bound optimization successful:",
    existing["objective_A_success"].sum()
)

print(
    "Additional potentially successful users:",
    additional_success.sum()
)

# =============================================================================
# 12. USERS THAT REMAIN INFEASIBLE
# =============================================================================

remaining_infeasible = (
    ~existing["objective_A_success"]
)

print(
    "\nUsers remaining infeasible even under maximum cash allocation:",
    remaining_infeasible.sum()
)

print(
    "Their mean target:",
    existing.loc[
        remaining_infeasible,
        "target_amount"
    ].mean()
)

print(
    "Their mean maximum funding:",
    existing.loc[
        remaining_infeasible,
        "objective_A_max_goal_funding"
    ].mean()
)

print(
    "Their mean unavoidable shortfall:",
    existing.loc[
        remaining_infeasible,
        "objective_A_shortfall"
    ].mean()
)

# =============================================================================
# 13. HOW MUCH FUNDING WOULD CHANGE?
# =============================================================================

print("\n" + "=" * 80)
print("6. FUNDING CHANGE RELATIVE TO EXISTING POLICY")
print("=" * 80)

existing["additional_funding_if_maximized"] = (
    existing["objective_A_max_goal_funding"]
    -
    existing["existing_goal_funding"]
).clip(lower=0)

print(
    existing[
        [
            "existing_goal_funding",
            "objective_A_max_goal_funding",
            "additional_funding_if_maximized"
        ]
    ].describe()
)

print(
    "\nTotal additional theoretical goal funding:",
    existing["additional_funding_if_maximized"].sum()
)

# =============================================================================
# 14. POLICY IMPACT BY FINANCIAL SITUATION
# =============================================================================

# Retrieve financial situation from LP if available.
if "financial_situation" in lp.columns:

    situation = lp[
        [
            "user_id",
            "financial_situation"
        ]
    ].copy()

    existing = existing.merge(
        situation,
        on="user_id",
        how="left"
    )

    situation_summary = (
        existing
        .groupby("financial_situation")
        .agg(
            users=("user_id", "count"),
            existing_success=("objective_C_success", "sum"),
            optimized_success=("objective_A_success", "sum"),
            mean_existing_funding=(
                "existing_goal_funding",
                "mean"
            ),
            mean_optimized_funding=(
                "objective_A_max_goal_funding",
                "mean"
            ),
            mean_existing_shortfall=(
                "objective_C_shortfall",
                "mean"
            ),
            mean_optimized_shortfall=(
                "objective_A_shortfall",
                "mean"
            )
        )
        .reset_index()
    )

    print("\n" + "=" * 80)
    print("7. OBJECTIVE IMPACT BY FINANCIAL SITUATION")
    print("=" * 80)

    print(
        situation_summary.to_string(index=False)
    )

# =============================================================================
# 15. POLICY IMPACT BY RISK PROFILE
# =============================================================================

if "risk_profile" in lp.columns:

    risk = lp[
        [
            "user_id",
            "risk_profile"
        ]
    ].copy()

    existing = existing.merge(
        risk,
        on="user_id",
        how="left"
    )

    risk_summary = (
        existing
        .groupby("risk_profile")
        .agg(
            users=("user_id", "count"),
            existing_success=("objective_C_success", "sum"),
            optimized_success=("objective_A_success", "sum"),
            mean_existing_funding=(
                "existing_goal_funding",
                "mean"
            ),
            mean_optimized_funding=(
                "objective_A_max_goal_funding",
                "mean"
            ),
            mean_existing_shortfall=(
                "objective_C_shortfall",
                "mean"
            ),
            mean_optimized_shortfall=(
                "objective_A_shortfall",
                "mean"
            )
        )
        .reset_index()
    )

    print("\n" + "=" * 80)
    print("8. OBJECTIVE IMPACT BY RISK PROFILE")
    print("=" * 80)

    print(
        risk_summary.to_string(index=False)
    )

# =============================================================================
# 16. REPRESENTATIVE USERS
# =============================================================================

print("\n" + "=" * 80)
print("9. REPRESENTATIVE USERS")
print("=" * 80)

ids = [
    "USER_00001",
    "USER_00002",
    "USER_00003",
    "USER_00004",
    "USER_00005",
    "USER_00006",
    "USER_00007",
    "USER_00008",
    "USER_00009",
    "USER_00010"
]

rep = existing[
    existing["user_id"].isin(ids)
].copy()

print(
    rep[
        [
            "user_id",
            "target_amount",
            "existing_goal_funding",
            "objective_A_max_goal_funding",
            "additional_funding_if_maximized",
            "existing_shortfall",
            "objective_A_shortfall",
            "existing_success",
            "objective_A_success"
        ]
    ].to_string(index=False)
)

# =============================================================================
# 17. OBJECTIVE FUNCTION STATUS
# =============================================================================

print("\n" + "=" * 80)
print("10. OBJECTIVE FUNCTION STATUS")
print("=" * 80)

print("""
OBJECTIVE A:
    Maximize SUM(G_t)

    Supported by the available cash-flow data.

OBJECTIVE B:
    Minimize D

    Supported by target_amount and goal shortfall definition.

    Under:
        SUM(G_t) + D = Target
        0 <= G_t <= PositiveCashFlow_t
        D >= 0

    Objective B is mathematically equivalent to Objective A.

OBJECTIVE C:
    Preserve existing goal allocation policy.

    Constraint:
        G_t <= PositiveCashFlow_t × GoalAllocationFactor

    This reproduces the existing simulation rather than creating
    a materially different optimization policy.

INVESTMENT OBJECTIVE:
    Cannot currently be defined from observed monthly contributions,
    because no monthly investment contribution variable exists.

RESIDUAL-CASH OBJECTIVE:
    Cannot currently be defined without inventing a minimum cash
    reserve or spending policy.

THEREFORE:

The data directly supports a goal-focused LP based on:
    Maximize goal funding / equivalently minimize shortfall.

However, selecting this as the final project objective is a
MODEL DESIGN DECISION, not something discovered from the historical
simulation itself.
""")

# =============================================================================
# 18. SAVE OUTPUTS
# =============================================================================

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(
    OUT,
    exist_ok=True
)

objective_path = os.path.join(
    OUT,
    "lp_5q_objective_function_audit.csv"
)

user_path = os.path.join(
    OUT,
    "lp_5q_objective_comparison_by_user.csv"
)

summary_path = os.path.join(
    OUT,
    "lp_5q_objective_comparison_summary.csv"
)

objective_summary.to_csv(
    summary_path,
    index=False
)

existing.to_csv(
    user_path,
    index=False
)

pd.DataFrame([
    [
        "Objective A",
        "Maximize total goal funding",
        "SUPPORTED",
        "Equivalent to minimizing shortfall under the stated constraints"
    ],
    [
        "Objective B",
        "Minimize goal shortfall",
        "SUPPORTED",
        "Equivalent to maximizing goal funding"
    ],
    [
        "Objective C",
        "Preserve existing allocation factor",
        "SUPPORTED",
        "Reproduces historical policy; limited optimization effect"
    ],
    [
        "Investment optimization",
        "Optimize monthly investment contribution",
        "NOT SUPPORTED",
        "No monthly contribution variable exists"
    ],
    [
        "Residual cash optimization",
        "Optimize unused cash / reserve",
        "NOT YET SUPPORTED",
        "No explicit reserve policy exists"
    ]
], columns=[
    "objective",
    "description",
    "data_status",
    "interpretation"
]).to_csv(
    objective_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5Q COMPLETE")
print("=" * 80)

print("\nSaved:")
print(objective_path)
print(user_path)
print(summary_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO INVESTMENT CONTRIBUTION WAS INVENTED.")
print("NO FINAL OBJECTIVE WAS SELECTED AUTOMATICALLY.")

================================================================================
STEP 5Q — OBJECTIVE FUNCTION & OPTIMIZATION POLICY AUDIT
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Horizon rows: 626970

================================================================================
1. OBJECTIVE A — MAXIMIZE TOTAL GOAL FUNDING
================================================================================
       objective_A_max_goal_funding  target_amount  objective_A_shortfall
count                  1.000000e+04   1.000000e+04           10000.000000
mean                   1.189898e+06   1.383538e+05           22240.827452
std                    2.213899e+06   1.211024e+05           59426.872318
min                    0.000000e+00   2.824526e+03               0.000000
25%                    9.665485e+04   7.189787e+04               0.000000
50%                    4.777859e+05   1.073131e+05               0.000000
75%                    1.440379e+06   1.595261e+05               0.000000
max                    6.659288e+07   1.900464e+06          913206.956331

Objective A potentially successful: 7582 / 10000
Objective A infeasible: 2418 / 10000

================================================================================
2. OBJECTIVE B — MINIMIZE GOAL SHORTFALL
================================================================================
       objective_B_min_shortfall
count               10000.000000
mean                22240.827452
std                 59426.872318
min                     0.000000
25%                     0.000000
50%                     0.000000
75%                     0.000000
max                913206.956331

Objective B successful: 7582 / 10000

A/B shortfall difference max: 0.0

================================================================================
3. OBJECTIVE C — EXISTING POLICY PRESERVATION
================================================================================

Objective C successful: 6451 / 10000
Objective C unsuccessful: 3549 / 10000

================================================================================
4. OBJECTIVE COMPARISON
================================================================================
                   objective  mean_goal_funding  mean_shortfall  successful_users  total_users
   A — Maximize goal funding       1.189898e+06    22240.827452              7582        10000
      B — Minimize shortfall       1.161130e+05    22240.827452              7582        10000
C — Preserve existing policy       9.449648e+05    30580.490391              6451        10000

================================================================================
5. USERS POTENTIALLY REACHED BY BROADER OPTIMIZATION
================================================================================
Existing policy successful: 6451
Cash-flow-bound optimization successful: 7582
Additional potentially successful users: 1131

Users remaining infeasible even under maximum cash allocation: 2418
Their mean target: 115685.12245280677
Their mean maximum funding: 23704.860038449202
Their mean unavoidable shortfall: 91980.26241435757

================================================================================
6. FUNDING CHANGE RELATIVE TO EXISTING POLICY
================================================================================
       existing_goal_funding  objective_A_max_goal_funding  \
count           1.000000e+04                  1.000000e+04
mean            9.449648e+05                  1.189898e+06
std             2.156857e+06                  2.213899e+06
min             0.000000e+00                  0.000000e+00
25%             2.676139e+04                  9.665485e+04
50%             2.364985e+05                  4.777859e+05
75%             9.683717e+05                  1.440379e+06
max             6.659288e+07                  6.659288e+07

       additional_funding_if_maximized
count                     1.000000e+04
mean                      2.449329e+05
std                       2.448743e+05
min                       0.000000e+00
25%                       4.232879e+04
50%                       1.732494e+05
75%                       3.843935e+05
max                       3.149198e+06

Total additional theoretical goal funding: 2449329376.1050773

================================================================================
7. OBJECTIVE IMPACT BY FINANCIAL SITUATION
================================================================================
financial_situation  users  existing_success  optimized_success  mean_existing_funding  mean_optimized_funding  mean_existing_shortfall  mean_optimized_shortfall
   financial_stress    474                 0                 24           3.172216e+03            1.132373e+04             94141.317967              89824.179056
        high_saving   2043              1998               2031           2.450276e+06            2.733128e+06               553.144002                175.500141
         low_saving   2923               944               1412           1.738092e+05            3.088982e+05             63297.246577              50822.194722
    moderate_saving   4560              3509               4115           8.627601e+05            1.185728e+06             16454.823301               6780.656071

================================================================================
8. OBJECTIVE IMPACT BY RISK PROFILE
================================================================================
risk_profile  users  existing_success  optimized_success  mean_existing_funding  mean_optimized_funding  mean_existing_shortfall  mean_optimized_shortfall
  aggressive   3333              3197               3286           1.898103e+06            2.197657e+06              1153.365886                319.054484
conservative   3333               721               1277           1.362033e+05            2.925839e+05             79344.620272              61645.329850
    moderate   3334              2533               3019           8.006316e+05            1.079485e+06             11249.284956               4763.341791

================================================================================
9. REPRESENTATIVE USERS
================================================================================
   user_id  target_amount  existing_goal_funding  objective_A_max_goal_funding  additional_funding_if_maximized  existing_shortfall  objective_A_shortfall  existing_success  objective_A_success
USER_00001  115357.183592           5.811302e+05                  8.329228e+05                    251792.562667            0.000000               0.000000              True                 True
USER_00002   59340.387689           0.000000e+00                  0.000000e+00                         0.000000        59340.387689           59340.387689             False                False
USER_00003   99893.237726           4.093773e+04                  1.349744e+05                     94036.646294        58955.510123               0.000000             False                 True
USER_00004   75476.307623           4.566919e+04                  1.870155e+05                    141346.331495        29807.117161               0.000000             False                 True
USER_00005  206040.342056           7.318348e+06                  7.771422e+06                    453073.892390            0.000000               0.000000              True                 True
USER_00006  110291.964774           3.502230e+05                  4.254410e+05                     75217.972356            0.000000               0.000000              True                 True
USER_00007  128020.414837           2.348219e+06                  2.694147e+06                    345928.474554            0.000000               0.000000              True                 True
USER_00008  269916.171830           0.000000e+00                  0.000000e+00                         0.000000       269916.171830          269916.171830             False                False
USER_00009  182600.732773           1.616717e+06                  1.847887e+06                    231170.704431            0.000000               0.000000              True                 True
USER_00010   96702.526658           5.423986e+04                  1.324862e+05                     78246.363163        42462.667060               0.000000             False                 True

================================================================================
10. OBJECTIVE FUNCTION STATUS
================================================================================

OBJECTIVE A:
    Maximize SUM(G_t)

    Supported by the available cash-flow data.

OBJECTIVE B:
    Minimize D

    Supported by target_amount and goal shortfall definition.

    Under:
        SUM(G_t) + D = Target
        0 <= G_t <= PositiveCashFlow_t
        D >= 0

    Objective B is mathematically equivalent to Objective A.

OBJECTIVE C:
    Preserve existing goal allocation policy.

    Constraint:
        G_t <= PositiveCashFlow_t × GoalAllocationFactor

    This reproduces the existing simulation rather than creating
    a materially different optimization policy.

INVESTMENT OBJECTIVE:
    Cannot currently be defined from observed monthly contributions,
    because no monthly investment contribution variable exists.

RESIDUAL-CASH OBJECTIVE:
    Cannot currently be defined without inventing a minimum cash
    reserve or spending policy.

THEREFORE:

The data directly supports a goal-focused LP based on:
    Maximize goal funding / equivalently minimize shortfall.

However, selecting this as the final project objective is a
MODEL DESIGN DECISION, not something discovered from the historical
simulation itself.


================================================================================
STEP 5Q COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5q_objective_function_audit.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5q_objective_comparison_by_user.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5q_objective_comparison_summary.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO INVESTMENT CONTRIBUTION WAS INVENTED.
NO FINAL OBJECTIVE WAS SELECTED AUTOMATICALLY.

In [111]:
# =============================================================================
# STEP 5R — FORMAL LP MATHEMATICAL FORMULATION VALIDATION
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5R — FORMAL LP MATHEMATICAL FORMULATION VALIDATION")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. REQUIRED DATA
# =============================================================================

lp_required = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_allocation_factor",
    "goal_horizon_funding_actual",
    "goal_shortfall_actual",
    "goal_achieved_on_time_actual"
]

monthly_required = [
    "user_id",
    "period",
    "positive_cash_flow",
    "monthly_surplus_dynamic"
]

missing_lp = [
    c for c in lp_required
    if c not in lp.columns
]

missing_monthly = [
    c for c in monthly_required
    if c not in monthly.columns
]

print("\nMissing LP columns:", missing_lp)
print("Missing monthly columns:", missing_monthly)

if missing_lp or missing_monthly:
    raise ValueError("Required data is missing.")

# =============================================================================
# 3. PREPARE
# =============================================================================

lp2 = lp[lp_required].copy()

for c in lp_required[1:]:
    lp2[c] = pd.to_numeric(
        lp2[c],
        errors="coerce"
    )

m = monthly[
    monthly_required
].copy()

m["period"] = pd.to_datetime(
    m["period"],
    errors="coerce"
)

for c in [
    "positive_cash_flow",
    "monthly_surplus_dynamic"
]:
    m[c] = pd.to_numeric(
        m[c],
        errors="coerce"
    )

m = m.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

m["simulation_month"] = (
    m.groupby("user_id")
    .cumcount()
    + 1
)

m = m.merge(
    lp2[
        [
            "user_id",
            "goal_horizon_months",
            "target_amount",
            "goal_allocation_factor",
            "goal_horizon_funding_actual",
            "goal_shortfall_actual",
            "goal_achieved_on_time_actual"
        ]
    ],
    on="user_id",
    how="left"
)

# =============================================================================
# 4. HORIZON
# =============================================================================

h = m[
    m["simulation_month"]
    <=
    m["goal_horizon_months"]
].copy()

print("\n" + "=" * 80)
print("1. HORIZON VALIDATION")
print("=" * 80)

print(
    "Horizon rows:",
    len(h)
)

print(
    "Expected horizon rows:",
    int(lp2["goal_horizon_months"].sum())
)

print(
    "Users:",
    h["user_id"].nunique()
)

# =============================================================================
# 5. DECISION VARIABLE COUNT
# =============================================================================

print("\n" + "=" * 80)
print("2. DECISION VARIABLE DIMENSION")
print("=" * 80)

# One G variable per user-month inside the goal horizon
G_variables = len(h)

# One D variable per user
D_variables = lp2["user_id"].nunique()

total_variables = G_variables + D_variables

print(
    "G variables:",
    G_variables
)

print(
    "D variables:",
    D_variables
)

print(
    "Total LP decision variables:",
    total_variables
)

# =============================================================================
# 6. CASH-FLOW UPPER-BOUND CHECK
# =============================================================================

print("\n" + "=" * 80)
print("3. GOAL FUNDING UPPER BOUND")
print("=" * 80)

h["upper_bound_G"] = (
    h["positive_cash_flow"]
)

print(
    "Negative positive-cash-flow values:",
    (
        h["upper_bound_G"] < 0
    ).sum()
)

print(
    "Zero upper-bound months:",
    (
        h["upper_bound_G"] == 0
    ).sum()
)

print(
    "Positive upper-bound months:",
    (
        h["upper_bound_G"] > 0
    ).sum()
)

print(
    "Maximum monthly G bound:",
    h["upper_bound_G"].max()
)

# =============================================================================
# 7. TARGET EQUATION
# =============================================================================

print("\n" + "=" * 80)
print("4. TARGET ACCOUNTING EQUATION")
print("=" * 80)

# Maximum funding available under the LP bound
max_funding = (
    h.groupby("user_id")["upper_bound_G"]
    .sum()
    .rename("max_funding")
    .reset_index()
)

target = lp2[
    [
        "user_id",
        "target_amount",
        "goal_horizon_funding_actual",
        "goal_shortfall_actual"
    ]
].copy()

formulation = target.merge(
    max_funding,
    on="user_id",
    how="left"
)

formulation["minimum_possible_D"] = (
    formulation["target_amount"]
    -
    formulation["max_funding"]
).clip(lower=0)

formulation["LP_feasible"] = (
    formulation["max_funding"]
    >=
    formulation["target_amount"]
)

print(
    formulation[
        [
            "target_amount",
            "max_funding",
            "minimum_possible_D"
        ]
    ].describe()
)

print(
    "\nLP potentially feasible:",
    formulation["LP_feasible"].sum(),
    "/",
    len(formulation)
)

print(
    "LP infeasible:",
    (~formulation["LP_feasible"]).sum(),
    "/",
    len(formulation)
)

# =============================================================================
# 8. EXISTING POLICY VS LP BOUND
# =============================================================================

print("\n" + "=" * 80)
print("5. EXISTING POLICY VS LP BOUND")
print("=" * 80)

formulation["existing_funding"] = (
    formulation["goal_horizon_funding_actual"]
)

formulation["additional_available_funding"] = (
    formulation["max_funding"]
    -
    formulation["existing_funding"]
).clip(lower=0)

print(
    "Mean existing funding:",
    formulation["existing_funding"].mean()
)

print(
    "Mean LP maximum funding:",
    formulation["max_funding"].mean()
)

print(
    "Mean additional available funding:",
    formulation["additional_available_funding"].mean()
)

print(
    "Users with additional funding capacity:",
    (
        formulation["additional_available_funding"]
        > 1e-6
    ).sum()
)

# =============================================================================
# 9. EXISTING POLICY RECONSTRUCTION
# =============================================================================

print("\n" + "=" * 80)
print("6. EXISTING POLICY RECONSTRUCTION")
print("=" * 80)

h["existing_goal_funding"] = (
    h["positive_cash_flow"]
    *
    h["goal_allocation_factor"]
)

existing_reconstructed = (
    h.groupby("user_id")["existing_goal_funding"]
    .sum()
    .rename("reconstructed_existing_funding")
    .reset_index()
)

existing_reconstructed = existing_reconstructed.merge(
    lp2[
        [
            "user_id",
            "goal_horizon_funding_actual"
        ]
    ],
    on="user_id",
    how="left"
)

existing_reconstructed["error"] = (
    existing_reconstructed[
        "reconstructed_existing_funding"
    ]
    -
    existing_reconstructed[
        "goal_horizon_funding_actual"
    ]
)

print(
    "Mean absolute error:",
    existing_reconstructed["error"].abs().mean()
)

print(
    "Maximum absolute error:",
    existing_reconstructed["error"].abs().max()
)

print(
    "Exact matches <= 1e-6:",
    (
        existing_reconstructed["error"].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(existing_reconstructed)
)

# =============================================================================
# 10. CONSTRAINT COUNT
# =============================================================================

print("\n" + "=" * 80)
print("7. LP CONSTRAINT DIMENSION")
print("=" * 80)

# For every G_t:
#   G_t >= 0
#   G_t <= PositiveCashFlow_t
#
# D:
#   D >= 0
#
# Target equality:
#   SUM(G_t) + D = Target
#
# We count the explicit constraints conceptually.

G_nonnegativity = G_variables
G_upper_bounds = G_variables
D_nonnegativity = D_variables
target_equalities = D_variables

total_constraints = (
    G_nonnegativity
    +
    G_upper_bounds
    +
    D_nonnegativity
    +
    target_equalities
)

print(
    "G non-negativity constraints:",
    G_nonnegativity
)

print(
    "G upper-bound constraints:",
    G_upper_bounds
)

print(
    "D non-negativity constraints:",
    D_nonnegativity
)

print(
    "Target equality constraints:",
    target_equalities
)

print(
    "Total explicit constraints:",
    total_constraints
)

# =============================================================================
# 11. OBJECTIVE
# =============================================================================

print("\n" + "=" * 80)
print("8. FORMAL OBJECTIVE")
print("=" * 80)

print("""
PRIMARY LP OBJECTIVE:

    MINIMIZE
        Σ D_u

Equivalent:

    MAXIMIZE
        Σ Σ G_(u,t)

subject to:

    0 <= G_(u,t)
    G_(u,t) <= PositiveCashFlow_(u,t)

    Σ[t=1..H_u] G_(u,t) + D_u = Target_u

    D_u >= 0
""")

# =============================================================================
# 12. EXCLUDED VARIABLES / CONSTRAINTS
# =============================================================================

print("\n" + "=" * 80)
print("9. EXCLUDED / UNSUPPORTED MODEL ELEMENTS")
print("=" * 80)

excluded = pd.DataFrame([
    [
        "I_t",
        "Monthly investment contribution",
        "No explicit monthly contribution field",
        "EXCLUDED"
    ],
    [
        "WALR borrowing",
        "Loan/borrowing decision",
        "No borrowing variable/formulation established",
        "EXCLUDED"
    ],
    [
        "NIFTY future return",
        "Decision-dependent future return",
        "No LP return mechanism established",
        "EXCLUDED"
    ],
    [
        "Minimum cash reserve",
        "Residual cash constraint",
        "No explicit reserve policy",
        "EXCLUDED"
    ],
    [
        "goal_specific_monthly_capacity",
        "Dynamic monthly hard cap",
        "Static user parameter; not an exact historical monthly bound",
        "NOT USED AS HARD DYNAMIC CAP"
    ]
], columns=[
    "element",
    "meaning",
    "reason",
    "status"
])

print(
    excluded.to_string(index=False)
)

# =============================================================================
# 13. FORMULATION CONSISTENCY TEST
# =============================================================================

print("\n" + "=" * 80)
print("10. FORMULATION CONSISTENCY")
print("=" * 80)

checks = {
    "all_users_have_horizon": (
        formulation["max_funding"].notna().all()
    ),

    "all_upper_bounds_nonnegative": (
        h["upper_bound_G"] >= 0
    ).all(),

    "existing_funding_not_above_cash_bound": (
        formulation["existing_funding"]
        <=
        formulation["max_funding"] + 1e-6
    ).all(),

    "LP_feasibility_count_matches_7582": (
        formulation["LP_feasible"].sum() == 7582
    )
}

for name, result in checks.items():
    print(
        f"{name}: {result}"
    )

# =============================================================================
# 14. FINAL FORMULATION SPECIFICATION
# =============================================================================

print("\n" + "=" * 80)
print("11. FINAL LP SPECIFICATION")
print("=" * 80)

print("""
SETS:

U = set of 10,000 users

T_u = months 1,...,H_u for user u

PARAMETERS:

P_(u,t) = PositiveCashFlow_(u,t)

Target_u = target amount

H_u = user goal horizon

DECISION VARIABLES:

G_(u,t) >= 0
    Goal funding allocated in month t

D_u >= 0
    Goal shortfall

OBJECTIVE:

minimize Σ_u D_u

CONSTRAINTS:

1. Monthly goal funding:
       0 <= G_(u,t) <= P_(u,t)

2. Goal accounting:
       Σ[t in T_u] G_(u,t) + D_u = Target_u

3. Shortfall:
       D_u >= 0

INTERPRETATION:

The LP determines the maximum achievable goal funding using the
observed positive monthly cash flow within each user's goal horizon.

If the target can be fully funded:
       D_u = 0

If the target cannot be fully funded:
       D_u > 0

The historical simulation remains the baseline policy:

       G_existing(u,t)
       = P_(u,t) × GoalAllocationFactor_u

The LP therefore represents a broader cash-allocation optimization
relative to the historical allocation policy.
""")

# =============================================================================
# 15. SAVE
# =============================================================================

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT, exist_ok=True)

spec_path = os.path.join(
    OUT,
    "lp_5r_formal_lp_specification.csv"
)

dimension_path = os.path.join(
    OUT,
    "lp_5r_lp_dimensions.csv"
)

formulation_path = os.path.join(
    OUT,
    "lp_5r_formulation_by_user.csv"
)

excluded_path = os.path.join(
    OUT,
    "lp_5r_excluded_model_elements.csv"
)

spec = pd.DataFrame([
    [
        "Objective",
        "minimize sum(D_u)",
        "SUPPORTED"
    ],
    [
        "Goal variable",
        "G_(u,t) >= 0",
        "SUPPORTED"
    ],
    [
        "Goal upper bound",
        "G_(u,t) <= PositiveCashFlow_(u,t)",
        "SUPPORTED"
    ],
    [
        "Target accounting",
        "sum(G_(u,t)) + D_u = Target_u",
        "SUPPORTED"
    ],
    [
        "Shortfall",
        "D_u >= 0",
        "SUPPORTED"
    ],
    [
        "Monthly investment I_t",
        "Not included",
        "UNSUPPORTED"
    ],
    [
        "Borrowing/WALR",
        "Not included",
        "UNSUPPORTED"
    ],
    [
        "Future NIFTY return",
        "Not included",
        "UNSUPPORTED"
    ],
    [
        "Minimum reserve",
        "Not included",
        "UNSUPPORTED"
    ]
], columns=[
    "element",
    "formulation",
    "status"
])

spec.to_csv(
    spec_path,
    index=False
)

pd.DataFrame([
    ["users", len(lp2)],
    ["horizon_rows", len(h)],
    ["G_variables", G_variables],
    ["D_variables", D_variables],
    ["total_variables", total_variables],
    ["G_nonnegativity", G_nonnegativity],
    ["G_upper_bounds", G_upper_bounds],
    ["D_nonnegativity", D_nonnegativity],
    ["target_equalities", target_equalities],
    ["total_constraints", total_constraints],
    ["LP_feasible_users", formulation["LP_feasible"].sum()],
    ["LP_infeasible_users", (~formulation["LP_feasible"]).sum()]
], columns=[
    "metric",
    "value"
]).to_csv(
    dimension_path,
    index=False
)

formulation.to_csv(
    formulation_path,
    index=False
)

excluded.to_csv(
    excluded_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5R COMPLETE")
print("=" * 80)

print("\nSaved:")
print(spec_path)
print(dimension_path)
print(formulation_path)
print(excluded_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO INVESTMENT CONTRIBUTION WAS INVENTED.")
print("NO UNSUPPORTED CONSTRAINT WAS ADDED.")

================================================================================
STEP 5R — FORMAL LP MATHEMATICAL FORMULATION VALIDATION
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Missing LP columns: []
Missing monthly columns: []

================================================================================
1. HORIZON VALIDATION
================================================================================
Horizon rows: 626970
Expected horizon rows: 626970
Users: 10000

================================================================================
2. DECISION VARIABLE DIMENSION
================================================================================
G variables: 626970
D variables: 10000
Total LP decision variables: 636970

================================================================================
3. GOAL FUNDING UPPER BOUND
================================================================================
Negative positive-cash-flow values: 0
Zero upper-bound months: 106229
Positive upper-bound months: 520741
Maximum monthly G bound: 874652.8860484292

================================================================================
4. TARGET ACCOUNTING EQUATION
================================================================================
       target_amount   max_funding  minimum_possible_D
count   1.000000e+04  1.000000e+04        10000.000000
mean    1.383538e+05  1.189898e+06        22240.827452
std     1.211024e+05  2.213899e+06        59426.872318
min     2.824526e+03  0.000000e+00            0.000000
25%     7.189787e+04  9.665485e+04            0.000000
50%     1.073131e+05  4.777859e+05            0.000000
75%     1.595261e+05  1.440379e+06            0.000000
max     1.900464e+06  6.659288e+07       913206.956331

LP potentially feasible: 7582 / 10000
LP infeasible: 2418 / 10000

================================================================================
5. EXISTING POLICY VS LP BOUND
================================================================================
Mean existing funding: 944964.8307231049
Mean LP maximum funding: 1189897.7683336125
Mean additional available funding: 244932.93761050774
Users with additional funding capacity: 8534

================================================================================
6. EXISTING POLICY RECONSTRUCTION
================================================================================
Mean absolute error: 2.7003985403339926e-11
Maximum absolute error: 3.725290298461914e-09
Exact matches <= 1e-6: 10000 / 10000

================================================================================
7. LP CONSTRAINT DIMENSION
================================================================================
G non-negativity constraints: 626970
G upper-bound constraints: 626970
D non-negativity constraints: 10000
Target equality constraints: 10000
Total explicit constraints: 1273940

================================================================================
8. FORMAL OBJECTIVE
================================================================================

PRIMARY LP OBJECTIVE:

    MINIMIZE
        Σ D_u

Equivalent:

    MAXIMIZE
        Σ Σ G_(u,t)

subject to:

    0 <= G_(u,t)
    G_(u,t) <= PositiveCashFlow_(u,t)

    Σ[t=1..H_u] G_(u,t) + D_u = Target_u

    D_u >= 0


================================================================================
9. EXCLUDED / UNSUPPORTED MODEL ELEMENTS
================================================================================
                       element                          meaning                                                       reason                       status
                           I_t  Monthly investment contribution                       No explicit monthly contribution field                     EXCLUDED
                WALR borrowing          Loan/borrowing decision                No borrowing variable/formulation established                     EXCLUDED
           NIFTY future return Decision-dependent future return                           No LP return mechanism established                     EXCLUDED
          Minimum cash reserve         Residual cash constraint                                   No explicit reserve policy                     EXCLUDED
goal_specific_monthly_capacity         Dynamic monthly hard cap Static user parameter; not an exact historical monthly bound NOT USED AS HARD DYNAMIC CAP

================================================================================
10. FORMULATION CONSISTENCY
================================================================================
all_users_have_horizon: True
all_upper_bounds_nonnegative: True
existing_funding_not_above_cash_bound: True
LP_feasibility_count_matches_7582: True

================================================================================
11. FINAL LP SPECIFICATION
================================================================================

SETS:

U = set of 10,000 users

T_u = months 1,...,H_u for user u

PARAMETERS:

P_(u,t) = PositiveCashFlow_(u,t)

Target_u = target amount

H_u = user goal horizon

DECISION VARIABLES:

G_(u,t) >= 0
    Goal funding allocated in month t

D_u >= 0
    Goal shortfall

OBJECTIVE:

minimize Σ_u D_u

CONSTRAINTS:

1. Monthly goal funding:
       0 <= G_(u,t) <= P_(u,t)

2. Goal accounting:
       Σ[t in T_u] G_(u,t) + D_u = Target_u

3. Shortfall:
       D_u >= 0

INTERPRETATION:

The LP determines the maximum achievable goal funding using the
observed positive monthly cash flow within each user's goal horizon.

If the target can be fully funded:
       D_u = 0

If the target cannot be fully funded:
       D_u > 0

The historical simulation remains the baseline policy:

       G_existing(u,t)
       = P_(u,t) × GoalAllocationFactor_u

The LP therefore represents a broader cash-allocation optimization
relative to the historical allocation policy.


================================================================================
STEP 5R COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5r_formal_lp_specification.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5r_lp_dimensions.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5r_formulation_by_user.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5r_excluded_model_elements.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO INVESTMENT CONTRIBUTION WAS INVENTED.
NO UNSUPPORTED CONSTRAINT WAS ADDED.

In [112]:
# =============================================================================
# STEP 5S — LP SOLVER PROTOTYPE VALIDATION
# =============================================================================
#
# IMPORTANT:
# - Small sample only
# - NO full 10,000-user solve yet
# - NO original data modified
# - Tests the mathematically validated formulation
# =============================================================================

import os
import numpy as np
import pandas as pd
from scipy.optimize import linprog

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

print("=" * 80)
print("STEP 5S — LP SOLVER PROTOTYPE VALIDATION")
print("=" * 80)

# =============================================================================
# 1. LOAD DATA
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. PREPARE USER PARAMETERS
# =============================================================================

lp_cols = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual"
]

lp2 = lp[lp_cols].copy()

lp2["goal_horizon_months"] = pd.to_numeric(
    lp2["goal_horizon_months"],
    errors="coerce"
)

lp2["target_amount"] = pd.to_numeric(
    lp2["target_amount"],
    errors="coerce"
)

lp2["goal_horizon_funding_actual"] = pd.to_numeric(
    lp2["goal_horizon_funding_actual"],
    errors="coerce"
)

# =============================================================================
# 3. PREPARE MONTHLY DATA
# =============================================================================

m = monthly[
    [
        "user_id",
        "period",
        "positive_cash_flow"
    ]
].copy()

m["period"] = pd.to_datetime(
    m["period"],
    errors="coerce"
)

m["positive_cash_flow"] = pd.to_numeric(
    m["positive_cash_flow"],
    errors="coerce"
)

m = m.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

m["simulation_month"] = (
    m.groupby("user_id")
    .cumcount()
    + 1
)

# =============================================================================
# 4. MERGE HORIZON
# =============================================================================

m = m.merge(
    lp2[
        [
            "user_id",
            "goal_horizon_months",
            "target_amount",
            "goal_horizon_funding_actual"
        ]
    ],
    on="user_id",
    how="left"
)

# =============================================================================
# 5. RESTRICT TO USER HORIZON
# =============================================================================

h = m[
    m["simulation_month"]
    <=
    m["goal_horizon_months"]
].copy()

print("\nHorizon rows:", len(h))

# =============================================================================
# 6. SELECT REPRESENTATIVE SAMPLE
# =============================================================================
#
# We deliberately include:
# - successful existing-policy users
# - unsuccessful but potentially feasible users
# - genuinely infeasible users
#
# This allows the solver to be tested across different cases.
# =============================================================================

user_bound = (
    h.groupby("user_id")
    .agg(
        max_available_funding=(
            "positive_cash_flow",
            "sum"
        ),
        target_amount=(
            "target_amount",
            "first"
        ),
        actual_funding=(
            "goal_horizon_funding_actual",
            "first"
        )
    )
    .reset_index()
)

user_bound["potentially_feasible"] = (
    user_bound["max_available_funding"]
    >=
    user_bound["target_amount"]
)

user_bound["existing_success"] = (
    user_bound["actual_funding"]
    >=
    user_bound["target_amount"]
)

# Three groups
existing_success = user_bound[
    user_bound["existing_success"]
]

additional_feasible = user_bound[
    (~user_bound["existing_success"])
    &
    (user_bound["potentially_feasible"])
]

infeasible = user_bound[
    ~user_bound["potentially_feasible"]
]

# Take up to 5 from each group
sample_ids = []

sample_ids.extend(
    existing_success["user_id"]
    .head(5)
    .tolist()
)

sample_ids.extend(
    additional_feasible["user_id"]
    .head(5)
    .tolist()
)

sample_ids.extend(
    infeasible["user_id"]
    .head(5)
    .tolist()
)

sample_ids = list(dict.fromkeys(sample_ids))

print("\nSample users:", len(sample_ids))

print(
    "\nSample category counts:"
)

print(
    "Existing-policy successful:",
    len(
        set(sample_ids)
        &
        set(existing_success["user_id"])
    )
)

print(
    "Additional potentially feasible:",
    len(
        set(sample_ids)
        &
        set(additional_feasible["user_id"])
    )
)

print(
    "Infeasible:",
    len(
        set(sample_ids)
        &
        set(infeasible["user_id"])
    )
)

# =============================================================================
# 7. SOLVE EACH SAMPLE USER
# =============================================================================

results = []

print("\n" + "=" * 80)
print("SOLVING SAMPLE USERS")
print("=" * 80)

for user_id in sample_ids:

    user_rows = h[
        h["user_id"] == user_id
    ].copy()

    user_rows = user_rows.sort_values(
        "simulation_month"
    )

    P = (
        user_rows[
            "positive_cash_flow"
        ]
        .to_numpy(
            dtype=float
        )
    )

    target = float(
        user_rows[
            "target_amount"
        ].iloc[0]
    )

    actual_funding = float(
        user_rows[
            "goal_horizon_funding_actual"
        ].iloc[0]
    )

    n = len(P)

    # -------------------------------------------------------------------------
    # Decision variables:
    #
    # x = [G_1, G_2, ..., G_H, D]
    #
    # Objective:
    #
    # min D
    # -------------------------------------------------------------------------

    c = np.zeros(
        n + 1
    )

    c[-1] = 1.0

    # -------------------------------------------------------------------------
    # Bounds:
    #
    # 0 <= G_t <= PositiveCashFlow_t
    # 0 <= D
    # -------------------------------------------------------------------------

    bounds = [
        (
            0,
            float(p)
        )
        for p in P
    ]

    bounds.append(
        (
            0,
            None
        )
    )

    # -------------------------------------------------------------------------
    # Equality:
    #
    # sum(G_t) + D = Target
    # -------------------------------------------------------------------------

    A_eq = np.zeros(
        (1, n + 1)
    )

    A_eq[0, :n] = 1.0
    A_eq[0, n] = 1.0

    b_eq = np.array([
        target
    ])

    # -------------------------------------------------------------------------
    # SOLVE
    # -------------------------------------------------------------------------

    solution = linprog(
        c=c,
        A_eq=A_eq,
        b_eq=b_eq,
        bounds=bounds,
        method="highs"
    )

    # -------------------------------------------------------------------------
    # Expected analytical solution
    # -------------------------------------------------------------------------

    total_cash = P.sum()

    expected_goal_funding = min(
        target,
        total_cash
    )

    expected_shortfall = max(
        target - total_cash,
        0
    )

    # -------------------------------------------------------------------------
    # Solver result
    # -------------------------------------------------------------------------

    if solution.success:

        solver_goal_funding = (
            solution.x[:n].sum()
        )

        solver_shortfall = (
            solution.x[-1]
        )

        goal_error = (
            solver_goal_funding
            -
            expected_goal_funding
        )

        shortfall_error = (
            solver_shortfall
            -
            expected_shortfall
        )

        target_constraint_error = (
            solver_goal_funding
            +
            solver_shortfall
            -
            target
        )

        upper_bound_violation = max(
            0,
            (
                solution.x[:n]
                -
                P
            ).max()
        )

        results.append([
            user_id,
            n,
            target,
            actual_funding,
            total_cash,
            expected_goal_funding,
            solver_goal_funding,
            expected_shortfall,
            solver_shortfall,
            goal_error,
            shortfall_error,
            target_constraint_error,
            upper_bound_violation,
            solution.success,
            solution.message
        ])

        print(
            f"{user_id}: SUCCESS | "
            f"Target={target:.2f} | "
            f"Expected funding={expected_goal_funding:.2f} | "
            f"Solver funding={solver_goal_funding:.2f} | "
            f"Expected D={expected_shortfall:.2f} | "
            f"Solver D={solver_shortfall:.2f}"
        )

    else:

        results.append([
            user_id,
            n,
            target,
            actual_funding,
            total_cash,
            expected_goal_funding,
            np.nan,
            expected_shortfall,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            solution.success,
            solution.message
        ])

        print(
            f"{user_id}: SOLVER FAILED | "
            f"{solution.message}"
        )

# =============================================================================
# 8. RESULTS TABLE
# =============================================================================

results_df = pd.DataFrame(
    results,
    columns=[
        "user_id",
        "horizon_months",
        "target_amount",
        "existing_funding",
        "total_positive_cash",
        "expected_goal_funding",
        "solver_goal_funding",
        "expected_shortfall",
        "solver_shortfall",
        "goal_funding_error",
        "shortfall_error",
        "target_constraint_error",
        "upper_bound_violation",
        "solver_success",
        "solver_message"
    ]
)

print("\n" + "=" * 80)
print("SOLVER VALIDATION RESULTS")
print("=" * 80)

print(
    results_df.to_string(
        index=False
    )
)

# =============================================================================
# 9. VALIDATION TESTS
# =============================================================================

print("\n" + "=" * 80)
print("VALIDATION TESTS")
print("=" * 80)

successful = results_df[
    results_df["solver_success"]
]

print(
    "Solver successful:",
    len(successful),
    "/",
    len(results_df)
)

if len(successful) > 0:

    print(
        "Maximum goal-funding error:",
        successful[
            "goal_funding_error"
        ].abs().max()
    )

    print(
        "Maximum shortfall error:",
        successful[
            "shortfall_error"
        ].abs().max()
    )

    print(
        "Maximum target constraint error:",
        successful[
            "target_constraint_error"
        ].abs().max()
    )

    print(
        "Maximum upper-bound violation:",
        successful[
            "upper_bound_violation"
        ].max()
    )

    print(
        "Goal funding matches expected <=1e-6:",
        (
            successful[
                "goal_funding_error"
            ].abs()
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

    print(
        "Shortfall matches expected <=1e-6:",
        (
            successful[
                "shortfall_error"
            ].abs()
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

    print(
        "Target equality satisfied <=1e-6:",
        (
            successful[
                "target_constraint_error"
            ].abs()
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

    print(
        "G upper bounds satisfied <=1e-6:",
        (
            successful[
                "upper_bound_violation"
            ]
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

# =============================================================================
# 10. COMPARE WITH HISTORICAL POLICY
# =============================================================================

print("\n" + "=" * 80)
print("HISTORICAL POLICY vs LP PROTOTYPE")
print("=" * 80)

results_df["additional_funding"] = (
    results_df["solver_goal_funding"]
    -
    results_df["existing_funding"]
)

print(
    results_df[
        [
            "user_id",
            "target_amount",
            "existing_funding",
            "solver_goal_funding",
            "additional_funding",
            "solver_shortfall"
        ]
    ].to_string(index=False)
)

# =============================================================================
# 11. SAVE
# =============================================================================

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(
    OUT,
    exist_ok=True
)

result_path = os.path.join(
    OUT,
    "lp_5s_solver_prototype_results.csv"
)

results_df.to_csv(
    result_path,
    index=False
)

print("\n" + "=" * 80)
print("STEP 5S COMPLETE")
print("=" * 80)

print("\nSaved:")
print(result_path)

print("\nLP SOLVER WAS RUN ONLY ON THE SMALL VALIDATION SAMPLE.")
print("NO FULL DATASET SOLVE WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO VALUES WERE FILLED.")
print("NO INVESTMENT CONTRIBUTION WAS INVENTED.")

================================================================================
STEP 5S — LP SOLVER PROTOTYPE VALIDATION
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Horizon rows: 626970

Sample users: 15

Sample category counts:
Existing-policy successful: 5
Additional potentially feasible: 5
Infeasible: 5

================================================================================
SOLVING SAMPLE USERS
================================================================================
USER_00001: SUCCESS | Target=115357.18 | Expected funding=115357.18 | Solver funding=115357.18 | Expected D=0.00 | Solver D=0.00
USER_00005: SUCCESS | Target=206040.34 | Expected funding=206040.34 | Solver funding=206040.34 | Expected D=0.00 | Solver D=0.00
USER_00006: SUCCESS | Target=110291.96 | Expected funding=110291.96 | Solver funding=110291.96 | Expected D=0.00 | Solver D=0.00
USER_00007: SUCCESS | Target=128020.41 | Expected funding=128020.41 | Solver funding=128020.41 | Expected D=0.00 | Solver D=0.00
USER_00009: SUCCESS | Target=182600.73 | Expected funding=182600.73 | Solver funding=182600.73 | Expected D=0.00 | Solver D=0.00
USER_00003: SUCCESS | Target=99893.24 | Expected funding=99893.24 | Solver funding=99893.24 | Expected D=0.00 | Solver D=0.00
USER_00004: SUCCESS | Target=75476.31 | Expected funding=75476.31 | Solver funding=75476.31 | Expected D=0.00 | Solver D=0.00
USER_00010: SUCCESS | Target=96702.53 | Expected funding=96702.53 | Solver funding=96702.53 | Expected D=0.00 | Solver D=0.00
USER_00017: SUCCESS | Target=67605.33 | Expected funding=67605.33 | Solver funding=67605.33 | Expected D=0.00 | Solver D=0.00
USER_00025: SUCCESS | Target=114910.07 | Expected funding=114910.07 | Solver funding=114910.07 | Expected D=0.00 | Solver D=0.00
USER_00002: SUCCESS | Target=59340.39 | Expected funding=0.00 | Solver funding=0.00 | Expected D=59340.39 | Solver D=59340.39
USER_00008: SUCCESS | Target=269916.17 | Expected funding=0.00 | Solver funding=0.00 | Expected D=269916.17 | Solver D=269916.17
USER_00012: SUCCESS | Target=153722.61 | Expected funding=0.00 | Solver funding=0.00 | Expected D=153722.61 | Solver D=153722.61
USER_00013: SUCCESS | Target=75699.85 | Expected funding=0.00 | Solver funding=0.00 | Expected D=75699.85 | Solver D=75699.85
USER_00034: SUCCESS | Target=27059.63 | Expected funding=0.00 | Solver funding=0.00 | Expected D=27059.63 | Solver D=27059.63

================================================================================
SOLVER VALIDATION RESULTS
================================================================================
   user_id  horizon_months  target_amount  existing_funding  total_positive_cash  expected_goal_funding  solver_goal_funding  expected_shortfall  solver_shortfall  goal_funding_error  shortfall_error  target_constraint_error  upper_bound_violation  solver_success                                                  solver_message
USER_00001              48  115357.183592      5.811302e+05         8.329228e+05          115357.183592        115357.183592            0.000000          0.000000        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00005             120  206040.342056      7.318348e+06         7.771422e+06          206040.342056        206040.342056            0.000000          0.000000        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00006              18  110291.964774      3.502230e+05         4.254410e+05          110291.964774        110291.964774            0.000000          0.000000       -1.455192e-11              0.0            -1.455192e-11                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00007              75  128020.414837      2.348219e+06         2.694147e+06          128020.414837        128020.414837            0.000000          0.000000        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00009              55  182600.732773      1.616717e+06         1.847887e+06          182600.732773        182600.732773            0.000000          0.000000       -2.910383e-11              0.0            -2.910383e-11                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00003              46   99893.237726      4.093773e+04         1.349744e+05           99893.237726         99893.237726            0.000000          0.000000        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00004              60   75476.307623      4.566919e+04         1.870155e+05           75476.307623         75476.307623            0.000000          0.000000        1.455192e-11              0.0             1.455192e-11                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00010              24   96702.526658      5.423986e+04         1.324862e+05           96702.526658         96702.526658            0.000000          0.000000        1.455192e-11              0.0             1.455192e-11                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00017              12   67605.333513      3.423747e+04         7.657675e+04           67605.333513         67605.333513            0.000000          0.000000        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00025              78  114910.074967      8.638129e+04         3.768817e+05          114910.074967        114910.074967            0.000000          0.000000        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00002              51   59340.387689      0.000000e+00         0.000000e+00               0.000000             0.000000        59340.387689      59340.387689        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00008              11  269916.171830      0.000000e+00         0.000000e+00               0.000000             0.000000       269916.171830     269916.171830        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00012              18  153722.614222      0.000000e+00         0.000000e+00               0.000000             0.000000       153722.614222     153722.614222        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00013             102   75699.850293      0.000000e+00         0.000000e+00               0.000000             0.000000        75699.850293      75699.850293        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)
USER_00034              10   27059.631670      0.000000e+00         0.000000e+00               0.000000             0.000000        27059.631670      27059.631670        0.000000e+00              0.0             0.000000e+00                      0            True Optimization terminated successfully. (HiGHS Status 7: Optimal)

================================================================================
VALIDATION TESTS
================================================================================
Solver successful: 15 / 15
Maximum goal-funding error: 2.9103830456733704e-11
Maximum shortfall error: 0.0
Maximum target constraint error: 2.9103830456733704e-11
Maximum upper-bound violation: 0
Goal funding matches expected <=1e-6: 15 / 15
Shortfall matches expected <=1e-6: 15 / 15
Target equality satisfied <=1e-6: 15 / 15
G upper bounds satisfied <=1e-6: 15 / 15

================================================================================
HISTORICAL POLICY vs LP PROTOTYPE
================================================================================
   user_id  target_amount  existing_funding  solver_goal_funding  additional_funding  solver_shortfall
USER_00001  115357.183592      5.811302e+05        115357.183592       -4.657731e+05          0.000000
USER_00005  206040.342056      7.318348e+06        206040.342056       -7.112308e+06          0.000000
USER_00006  110291.964774      3.502230e+05        110291.964774       -2.399311e+05          0.000000
USER_00007  128020.414837      2.348219e+06        128020.414837       -2.220198e+06          0.000000
USER_00009  182600.732773      1.616717e+06        182600.732773       -1.434116e+06          0.000000
USER_00003   99893.237726      4.093773e+04         99893.237726        5.895551e+04          0.000000
USER_00004   75476.307623      4.566919e+04         75476.307623        2.980712e+04          0.000000
USER_00010   96702.526658      5.423986e+04         96702.526658        4.246267e+04          0.000000
USER_00017   67605.333513      3.423747e+04         67605.333513        3.336787e+04          0.000000
USER_00025  114910.074967      8.638129e+04        114910.074967        2.852879e+04          0.000000
USER_00002   59340.387689      0.000000e+00             0.000000        0.000000e+00      59340.387689
USER_00008  269916.171830      0.000000e+00             0.000000        0.000000e+00     269916.171830
USER_00012  153722.614222      0.000000e+00             0.000000        0.000000e+00     153722.614222
USER_00013   75699.850293      0.000000e+00             0.000000        0.000000e+00      75699.850293
USER_00034   27059.631670      0.000000e+00             0.000000        0.000000e+00      27059.631670

================================================================================
STEP 5S COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5s_solver_prototype_results.csv

LP SOLVER WAS RUN ONLY ON THE SMALL VALIDATION SAMPLE.
NO FULL DATASET SOLVE WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO VALUES WERE FILLED.
NO INVESTMENT CONTRIBUTION WAS INVENTED.

In [113]:
# =============================================================================
# STEP 5T — FULL 10,000-USER LP OPTIMIZATION
# =============================================================================
#
# FORMULATION VALIDATED IN STEPS 5R + 5S
#
# Objective:
#     MINIMIZE D_u
#
# Equivalent:
#     MAXIMIZE total goal funding
#
# Subject to:
#     0 <= G_(u,t) <= PositiveCashFlow_(u,t)
#
#     SUM(G_(u,t)) + D_u = Target_u
#
#     D_u >= 0
#
# IMPORTANT:
# - Full 10,000-user solve
# - Uses actual user horizons
# - No investment contribution invented
# - No borrowing/WALR
# - No future NIFTY return assumption
# - No static goal capacity as dynamic hard cap
# - Original files are NOT modified
# =============================================================================

import os
import time
import gc
import numpy as np
import pandas as pd
from scipy.optimize import linprog

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

os.makedirs(OUT, exist_ok=True)

print("=" * 80)
print("STEP 5T — FULL 10,000-USER LP OPTIMIZATION")
print("=" * 80)

# =============================================================================
# 1. LOAD DATA
# =============================================================================

start_time = time.time()

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)

print("\nLP shape:", lp.shape)
print("Monthly shape:", monthly.shape)

# =============================================================================
# 2. REQUIRED COLUMNS
# =============================================================================

required_lp = [
    "user_id",
    "goal_horizon_months",
    "target_amount",
    "goal_horizon_funding_actual"
]

required_monthly = [
    "user_id",
    "period",
    "positive_cash_flow"
]

missing_lp = [
    c for c in required_lp
    if c not in lp.columns
]

missing_monthly = [
    c for c in required_monthly
    if c not in monthly.columns
]

print("\nMissing LP columns:", missing_lp)
print("Missing monthly columns:", missing_monthly)

if missing_lp or missing_monthly:
    raise ValueError(
        "Required columns are missing. Stop before optimization."
    )

# =============================================================================
# 3. PREPARE USER PARAMETERS
# =============================================================================

user_params = lp[
    required_lp
].copy()

user_params["goal_horizon_months"] = pd.to_numeric(
    user_params["goal_horizon_months"],
    errors="coerce"
)

user_params["target_amount"] = pd.to_numeric(
    user_params["target_amount"],
    errors="coerce"
)

user_params["goal_horizon_funding_actual"] = pd.to_numeric(
    user_params["goal_horizon_funding_actual"],
    errors="coerce"
)

# Integrity
if user_params["user_id"].duplicated().any():
    raise ValueError(
        "Duplicate user_id found in LP input."
    )

if user_params[
    ["goal_horizon_months", "target_amount"]
].isna().any().any():
    raise ValueError(
        "Missing horizon or target detected."
    )

print(
    "\nUnique LP users:",
    user_params["user_id"].nunique()
)

# =============================================================================
# 4. PREPARE MONTHLY DATA
# =============================================================================

m = monthly[
    [
        "user_id",
        "period",
        "positive_cash_flow"
    ]
].copy()

m["period"] = pd.to_datetime(
    m["period"],
    errors="coerce"
)

m["positive_cash_flow"] = pd.to_numeric(
    m["positive_cash_flow"],
    errors="coerce"
)

if m["positive_cash_flow"].isna().any():
    raise ValueError(
        "Missing positive_cash_flow detected."
    )

# Sort exactly as simulation chronology
m = m.sort_values(
    ["user_id", "period"]
).reset_index(drop=True)

# Month index within each user
m["simulation_month"] = (
    m.groupby("user_id")
    .cumcount()
    + 1
)

# =============================================================================
# 5. MERGE USER HORIZON
# =============================================================================

m = m.merge(
    user_params[
        [
            "user_id",
            "goal_horizon_months",
            "target_amount",
            "goal_horizon_funding_actual"
        ]
    ],
    on="user_id",
    how="left",
    validate="many_to_one"
)

if m["goal_horizon_months"].isna().any():
    raise ValueError(
        "Some monthly rows could not be matched to LP users."
    )

# =============================================================================
# 6. RESTRICT TO GOAL HORIZON
# =============================================================================

h = m[
    m["simulation_month"]
    <=
    m["goal_horizon_months"]
].copy()

print(
    "\nHorizon rows:",
    len(h)
)

expected_horizon_rows = int(
    user_params["goal_horizon_months"].sum()
)

print(
    "Expected horizon rows:",
    expected_horizon_rows
)

if len(h) != expected_horizon_rows:
    raise ValueError(
        "Horizon row count does not match expected value."
    )

# =============================================================================
# 7. GROUP HORIZON DATA BY USER
# =============================================================================

grouped = h.groupby(
    "user_id",
    sort=False
)

# =============================================================================
# 8. RUN FULL LP
# =============================================================================

print("\n" + "=" * 80)
print("STARTING FULL LP SOLVE")
print("=" * 80)

optimization_summary = []
optimization_monthly = []

solver_failures = []

total_users = user_params["user_id"].nunique()

completed = 0

for user_id, user_rows in grouped:

    user_rows = user_rows.sort_values(
        "simulation_month"
    )

    P = user_rows[
        "positive_cash_flow"
    ].to_numpy(dtype=float)

    target = float(
        user_rows[
            "target_amount"
        ].iloc[0]
    )

    actual_funding = float(
        user_rows[
            "goal_horizon_funding_actual"
        ].iloc[0]
    )

    horizon = len(P)

    # -------------------------------------------------------------------------
    # Decision variables:
    #
    # [G_1, G_2, ..., G_H, D]
    # -------------------------------------------------------------------------

    c = np.zeros(
        horizon + 1
    )

    # Minimize D
    c[-1] = 1.0

    # -------------------------------------------------------------------------
    # Variable bounds
    #
    # 0 <= G_t <= PositiveCashFlow_t
    # D >= 0
    # -------------------------------------------------------------------------

    bounds = [
        (0.0, float(p))
        for p in P
    ]

    bounds.append(
        (0.0, None)
    )

    # -------------------------------------------------------------------------
    # Target equality
    #
    # SUM(G_t) + D = Target
    # -------------------------------------------------------------------------

    A_eq = np.zeros(
        (1, horizon + 1)
    )

    A_eq[0, :horizon] = 1.0
    A_eq[0, horizon] = 1.0

    b_eq = np.array([
        target
    ])

    # -------------------------------------------------------------------------
    # Solve
    # -------------------------------------------------------------------------

    solution = linprog(
        c=c,
        A_eq=A_eq,
        b_eq=b_eq,
        bounds=bounds,
        method="highs"
    )

    # -------------------------------------------------------------------------
    # Analytical expected result
    # -------------------------------------------------------------------------

    total_positive_cash = float(
        P.sum()
    )

    expected_funding = min(
        target,
        total_positive_cash
    )

    expected_shortfall = max(
        target - total_positive_cash,
        0.0
    )

    # -------------------------------------------------------------------------
    # Process solution
    # -------------------------------------------------------------------------

    if solution.success:

        G = solution.x[:horizon]

        D = float(
            solution.x[-1]
        )

        optimized_funding = float(
            G.sum()
        )

        # Constraint diagnostics
        target_error = (
            optimized_funding
            + D
            - target
        )

        bound_violation = float(
            max(
                0.0,
                np.max(G - P)
            )
        )

        lower_violation = float(
            max(
                0.0,
                -np.min(G)
            )
        )

        funding_error = (
            optimized_funding
            -
            expected_funding
        )

        shortfall_error = (
            D
            -
            expected_shortfall
        )

        # ---------------------------------------------------------------------
        # Monthly optimization output
        # ---------------------------------------------------------------------

        for i, (_, row) in enumerate(
            user_rows.iterrows()
        ):

            optimization_monthly.append([
                user_id,
                row["period"],
                int(row["simulation_month"]),
                float(row["positive_cash_flow"]),
                float(G[i]),
                float(
                    row["positive_cash_flow"]
                    -
                    G[i]
                ),
                target,
                D
            ])

        # ---------------------------------------------------------------------
        # User summary
        # ---------------------------------------------------------------------

        optimization_summary.append([
            user_id,
            horizon,
            target,
            actual_funding,
            total_positive_cash,
            optimized_funding,
            D,
            expected_funding,
            expected_shortfall,
            optimized_funding - actual_funding,
            int(
                optimized_funding >= target - 1e-6
            ),
            target_error,
            bound_violation,
            lower_violation,
            funding_error,
            shortfall_error,
            True
        ])

    else:

        solver_failures.append([
            user_id,
            horizon,
            target,
            solution.message
        ])

        optimization_summary.append([
            user_id,
            horizon,
            target,
            actual_funding,
            total_positive_cash,
            np.nan,
            np.nan,
            expected_funding,
            expected_shortfall,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            False
        ])

    completed += 1

    # Progress every 500 users
    if (
        completed % 500 == 0
        or completed == total_users
    ):
        elapsed = time.time() - start_time

        print(
            f"Processed {completed:,} / "
            f"{total_users:,} users | "
            f"Elapsed: {elapsed:.1f}s"
        )

# =============================================================================
# 9. CREATE SUMMARY DATAFRAME
# =============================================================================

summary_columns = [
    "user_id",
    "horizon_months",
    "target_amount",
    "existing_funding",
    "total_positive_cash",
    "optimized_goal_funding",
    "optimized_shortfall",
    "expected_goal_funding",
    "expected_shortfall",
    "additional_funding_vs_existing",
    "optimized_success",
    "target_constraint_error",
    "upper_bound_violation",
    "lower_bound_violation",
    "goal_funding_error",
    "shortfall_error",
    "solver_success"
]

summary_df = pd.DataFrame(
    optimization_summary,
    columns=summary_columns
)

# =============================================================================
# 10. CREATE MONTHLY OPTIMIZATION DATAFRAME
# =============================================================================

monthly_columns = [
    "user_id",
    "period",
    "simulation_month",
    "positive_cash_flow",
    "optimized_goal_funding",
    "residual_cash",
    "target_amount",
    "optimized_shortfall"
]

monthly_opt_df = pd.DataFrame(
    optimization_monthly,
    columns=monthly_columns
)

# =============================================================================
# 11. BASIC SOLVER RESULTS
# =============================================================================

print("\n" + "=" * 80)
print("FULL LP SOLVE RESULTS")
print("=" * 80)

print(
    "\nUsers in LP input:",
    total_users
)

print(
    "Users solved successfully:",
    summary_df[
        "solver_success"
    ].sum()
)

print(
    "Solver failures:",
    len(solver_failures)
)

print(
    "Optimized monthly rows:",
    len(monthly_opt_df)
)

# =============================================================================
# 12. ANALYTICAL VALIDATION
# =============================================================================

successful = summary_df[
    summary_df["solver_success"]
].copy()

print("\n" + "=" * 80)
print("ANALYTICAL VALIDATION")
print("=" * 80)

if len(successful) > 0:

    print(
        "\nMaximum goal-funding error:",
        successful[
            "goal_funding_error"
        ].abs().max()
    )

    print(
        "Maximum shortfall error:",
        successful[
            "shortfall_error"
        ].abs().max()
    )

    print(
        "Maximum target equality error:",
        successful[
            "target_constraint_error"
        ].abs().max()
    )

    print(
        "Maximum upper-bound violation:",
        successful[
            "upper_bound_violation"
        ].max()
    )

    print(
        "Maximum lower-bound violation:",
        successful[
            "lower_bound_violation"
        ].max()
    )

    print(
        "\nFunding matches analytical solution <=1e-6:",
        (
            successful[
                "goal_funding_error"
            ].abs()
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

    print(
        "Shortfall matches analytical solution <=1e-6:",
        (
            successful[
                "shortfall_error"
            ].abs()
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

    print(
        "Target equality <=1e-6:",
        (
            successful[
                "target_constraint_error"
            ].abs()
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

    print(
        "Upper bounds satisfied <=1e-6:",
        (
            successful[
                "upper_bound_violation"
            ]
            <= 1e-6
        ).sum(),
        "/",
        len(successful)
    )

# =============================================================================
# 13. OPTIMIZATION PERFORMANCE
# =============================================================================

print("\n" + "=" * 80)
print("OPTIMIZATION PERFORMANCE")
print("=" * 80)

existing_success = (
    summary_df[
        "existing_funding"
    ]
    >=
    summary_df[
        "target_amount"
    ]
)

optimized_success = (
    summary_df[
        "optimized_goal_funding"
    ]
    >=
    summary_df[
        "target_amount"
    ]
)

print(
    "\nExisting-policy successful:",
    existing_success.sum(),
    "/",
    len(summary_df)
)

print(
    "Optimized successful:",
    optimized_success.sum(),
    "/",
    len(summary_df)
)

print(
    "Existing-policy success rate:",
    existing_success.mean()
)

print(
    "Optimized success rate:",
    optimized_success.mean()
)

print(
    "Additional users becoming successful:",
    (
        (~existing_success)
        &
        optimized_success
    ).sum()
)

print(
    "Users remaining unsuccessful:",
    (
        ~optimized_success
    ).sum()
)

# =============================================================================
# 14. FUNDING COMPARISON
# =============================================================================

print("\n" + "=" * 80)
print("FUNDING COMPARISON")
print("=" * 80)

print(
    "\nMean existing funding:",
    summary_df[
        "existing_funding"
    ].mean()
)

print(
    "Mean optimized funding:",
    summary_df[
        "optimized_goal_funding"
    ].mean()
)

print(
    "Mean additional funding:",
    summary_df[
        "additional_funding_vs_existing"
    ].mean()
)

print(
    "Total additional funding:",
    summary_df[
        "additional_funding_vs_existing"
    ].sum()
)

print(
    "\nMean existing shortfall:",
    np.maximum(
        summary_df["target_amount"]
        -
        summary_df["existing_funding"],
        0
    ).mean()
)

print(
    "Mean optimized shortfall:",
    summary_df[
        "optimized_shortfall"
    ].mean()
)

# =============================================================================
# 15. SAVE RESULTS
# =============================================================================

summary_path = os.path.join(
    OUT,
    "lp_5t_full_optimization_user_summary.csv"
)

monthly_path = os.path.join(
    OUT,
    "lp_5t_full_optimization_monthly.csv"
)

failure_path = os.path.join(
    OUT,
    "lp_5t_solver_failures.csv"
)

summary_df.to_csv(
    summary_path,
    index=False
)

monthly_opt_df.to_csv(
    monthly_path,
    index=False
)

pd.DataFrame(
    solver_failures,
    columns=[
        "user_id",
        "horizon_months",
        "target_amount",
        "solver_message"
    ]
).to_csv(
    failure_path,
    index=False
)

# =============================================================================
# 16. FINAL INTEGRITY
# =============================================================================

print("\n" + "=" * 80)
print("FINAL INTEGRITY CHECK")
print("=" * 80)

print(
    "Summary users:",
    len(summary_df)
)

print(
    "Unique summary users:",
    summary_df[
        "user_id"
    ].nunique()
)

print(
    "Duplicate summary users:",
    summary_df[
        "user_id"
    ].duplicated()
    .sum()
)

print(
    "Summary missing values:",
    summary_df.isna().sum().sum()
)

print(
    "Monthly optimization rows:",
    len(monthly_opt_df)
)

print(
    "Expected monthly optimization rows:",
    expected_horizon_rows
)

print(
    "Monthly missing values:",
    monthly_opt_df.isna().sum().sum()
)

print(
    "Maximum absolute constraint error:",
    successful[
        "target_constraint_error"
    ].abs().max()
    if len(successful)
    else np.nan
)

print(
    "Maximum upper-bound violation:",
    successful[
        "upper_bound_violation"
    ].max()
    if len(successful)
    else np.nan
)

elapsed = time.time() - start_time

print(
    "\nTotal runtime:",
    round(elapsed, 2),
    "seconds"
)

print("\n" + "=" * 80)
print("STEP 5T COMPLETE")
print("=" * 80)

print("\nSaved:")
print(summary_path)
print(monthly_path)
print(failure_path)

print("\nOriginal LP input was NOT modified.")
print("Original simulation data was NOT modified.")
print("No investment contribution was invented.")
print("No unsupported constraint was added.")

================================================================================
STEP 5T — FULL 10,000-USER LP OPTIMIZATION
================================================================================

LP shape: (10000, 38)
Monthly shape: (1430000, 46)

Missing LP columns: []
Missing monthly columns: []

Unique LP users: 10000

Horizon rows: 626970
Expected horizon rows: 626970

================================================================================
STARTING FULL LP SOLVE
================================================================================
Processed 500 / 10,000 users | Elapsed: 21.5s
Processed 1,000 / 10,000 users | Elapsed: 25.9s
Processed 1,500 / 10,000 users | Elapsed: 31.8s
Processed 2,000 / 10,000 users | Elapsed: 35.8s
Processed 2,500 / 10,000 users | Elapsed: 39.8s
Processed 3,000 / 10,000 users | Elapsed: 44.8s
Processed 3,500 / 10,000 users | Elapsed: 50.1s
Processed 4,000 / 10,000 users | Elapsed: 54.0s
Processed 4,500 / 10,000 users | Elapsed: 58.0s
Processed 5,000 / 10,000 users | Elapsed: 64.3s
Processed 5,500 / 10,000 users | Elapsed: 68.9s
Processed 6,000 / 10,000 users | Elapsed: 72.9s
Processed 6,500 / 10,000 users | Elapsed: 77.4s
Processed 7,000 / 10,000 users | Elapsed: 83.3s
Processed 7,500 / 10,000 users | Elapsed: 87.3s
Processed 8,000 / 10,000 users | Elapsed: 91.3s
Processed 8,500 / 10,000 users | Elapsed: 96.2s
Processed 9,000 / 10,000 users | Elapsed: 101.5s
Processed 9,500 / 10,000 users | Elapsed: 105.4s
Processed 10,000 / 10,000 users | Elapsed: 109.4s

================================================================================
FULL LP SOLVE RESULTS
================================================================================

Users in LP input: 10000
Users solved successfully: 10000
Solver failures: 0
Optimized monthly rows: 626970

================================================================================
ANALYTICAL VALIDATION
================================================================================

Maximum goal-funding error: 2.3283064365386963e-10
Maximum shortfall error: 2.3283064365386963e-10
Maximum target equality error: 2.3283064365386963e-10
Maximum upper-bound violation: 0.0
Maximum lower-bound violation: 0.0

Funding matches analytical solution <=1e-6: 10000 / 10000
Shortfall matches analytical solution <=1e-6: 10000 / 10000
Target equality <=1e-6: 10000 / 10000
Upper bounds satisfied <=1e-6: 10000 / 10000

================================================================================
OPTIMIZATION PERFORMANCE
================================================================================

Existing-policy successful: 6451 / 10000
Optimized successful: 6540 / 10000
Existing-policy success rate: 0.6451
Optimized success rate: 0.654
Additional users becoming successful: 856
Users remaining unsuccessful: 3460

================================================================================
FUNDING COMPARISON
================================================================================

Mean existing funding: 944964.8307231049
Mean optimized funding: 116113.00752071626
Mean additional funding: -828851.8232023886
Total additional funding: -8288518232.023886

Mean existing shortfall: 30580.490390871095
Mean optimized shortfall: 22240.82745179166

================================================================================
FINAL INTEGRITY CHECK
================================================================================
Summary users: 10000
Unique summary users: 10000
Duplicate summary users: 0
Summary missing values: 0
Monthly optimization rows: 626970
Expected monthly optimization rows: 626970
Monthly missing values: 0
Maximum absolute constraint error: 2.3283064365386963e-10
Maximum upper-bound violation: 0.0

Total runtime: 120.64 seconds

================================================================================
STEP 5T COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5t_full_optimization_user_summary.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5t_full_optimization_monthly.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5t_solver_failures.csv

Original LP input was NOT modified.
Original simulation data was NOT modified.
No investment contribution was invented.
No unsupported constraint was added.

In [114]:
# =============================================================================
# STEP 5U — FULL LP SOLUTION INDEPENDENT VALIDATION
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

MONTHLY_PATH = os.path.join(
    BASE,
    "simulation",
    "05_simulation_runs",
    "monthly_financial_simulation_base.csv"
)

OPT_USER_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_user_summary.csv"
)

OPT_MONTHLY_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_monthly.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

print("=" * 80)
print("STEP 5U — FULL LP SOLUTION INDEPENDENT VALIDATION")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
monthly = pd.read_csv(MONTHLY_PATH)
opt_user = pd.read_csv(OPT_USER_PATH)
opt_monthly = pd.read_csv(OPT_MONTHLY_PATH)

print("\nOriginal LP:", lp.shape)
print("Original monthly:", monthly.shape)
print("Optimization user:", opt_user.shape)
print("Optimization monthly:", opt_monthly.shape)

# =============================================================================
# 2. USER-LEVEL INTEGRITY
# =============================================================================

print("\n" + "=" * 80)
print("1. USER-LEVEL INTEGRITY")
print("=" * 80)

print(
    "Original LP users:",
    lp["user_id"].nunique()
)

print(
    "Optimization users:",
    opt_user["user_id"].nunique()
)

print(
    "Duplicate optimization users:",
    opt_user["user_id"].duplicated().sum()
)

missing_users = set(lp["user_id"]) - set(opt_user["user_id"])
extra_users = set(opt_user["user_id"]) - set(lp["user_id"])

print(
    "Missing users:",
    len(missing_users)
)

print(
    "Unexpected users:",
    len(extra_users)
)

# =============================================================================
# 3. MONTHLY ROW INTEGRITY
# =============================================================================

print("\n" + "=" * 80)
print("2. MONTHLY ROW INTEGRITY")
print("=" * 80)

expected_horizon_rows = int(
    lp["goal_horizon_months"].sum()
)

print(
    "Expected horizon rows:",
    expected_horizon_rows
)

print(
    "Optimization monthly rows:",
    len(opt_monthly)
)

print(
    "Duplicate user-period rows:",
    opt_monthly[
        ["user_id", "period"]
    ].duplicated().sum()
)

# =============================================================================
# 4. NULL / INF CHECK
# =============================================================================

print("\n" + "=" * 80)
print("3. MISSING / INFINITE VALUES")
print("=" * 80)

print(
    "Optimization user missing values:",
    opt_user.isna().sum().sum()
)

print(
    "Optimization monthly missing values:",
    opt_monthly.isna().sum().sum()
)

numeric_user = opt_user.select_dtypes(
    include=np.number
)

numeric_monthly = opt_monthly.select_dtypes(
    include=np.number
)

print(
    "Optimization user infinite values:",
    np.isinf(numeric_user.to_numpy()).sum()
)

print(
    "Optimization monthly infinite values:",
    np.isinf(numeric_monthly.to_numpy()).sum()
)

# =============================================================================
# 5. MONTHLY NON-NEGATIVITY
# =============================================================================

print("\n" + "=" * 80)
print("4. MONTHLY NON-NEGATIVITY")
print("=" * 80)

negative_G = (
    opt_monthly[
        "optimized_goal_funding"
    ] < -1e-6
).sum()

negative_residual = (
    opt_monthly[
        "residual_cash"
    ] < -1e-6
).sum()

print(
    "Negative optimized G values:",
    negative_G
)

print(
    "Negative residual cash values:",
    negative_residual
)

# =============================================================================
# 6. G <= POSITIVE CASH FLOW
# =============================================================================

print("\n" + "=" * 80)
print("5. GOAL FUNDING UPPER-BOUND VALIDATION")
print("=" * 80)

upper_check = opt_monthly[
    "optimized_goal_funding"
] - opt_monthly[
    "positive_cash_flow"
]

max_upper_violation = max(
    0,
    upper_check.max()
)

print(
    "Maximum G - PositiveCashFlow:",
    upper_check.max()
)

print(
    "Maximum upper-bound violation:",
    max_upper_violation
)

print(
    "Rows satisfying G <= PositiveCashFlow:",
    (
        upper_check <= 1e-6
    ).sum(),
    "/",
    len(opt_monthly)
)

# =============================================================================
# 7. RESIDUAL CASH RECONSTRUCTION
# =============================================================================

print("\n" + "=" * 80)
print("6. RESIDUAL CASH VALIDATION")
print("=" * 80)

reconstructed_residual = (
    opt_monthly[
        "positive_cash_flow"
    ]
    -
    opt_monthly[
        "optimized_goal_funding"
    ]
)

residual_error = (
    opt_monthly[
        "residual_cash"
    ]
    -
    reconstructed_residual
)

print(
    "Maximum residual reconstruction error:",
    residual_error.abs().max()
)

print(
    "Rows matching <=1e-6:",
    (
        residual_error.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(opt_monthly)
)

# =============================================================================
# 8. INDEPENDENTLY AGGREGATE MONTHLY OPTIMIZATION
# =============================================================================

print("\n" + "=" * 80)
print("7. INDEPENDENT MONTHLY → USER RECONSTRUCTION")
print("=" * 80)

reconstructed = (
    opt_monthly
    .groupby("user_id")
    .agg(
        reconstructed_funding=(
            "optimized_goal_funding",
            "sum"
        ),
        reconstructed_positive_cash=(
            "positive_cash_flow",
            "sum"
        ),
        reconstructed_residual_cash=(
            "residual_cash",
            "sum"
        ),
        reconstructed_months=(
            "simulation_month",
            "count"
        )
    )
    .reset_index()
)

check = opt_user.merge(
    reconstructed,
    on="user_id",
    how="left",
    validate="one_to_one"
)

funding_reconstruction_error = (
    check[
        "optimized_goal_funding"
    ]
    -
    check[
        "reconstructed_funding"
    ]
)

print(
    "Maximum funding reconstruction error:",
    funding_reconstruction_error.abs().max()
)

print(
    "Users matching <=1e-6:",
    (
        funding_reconstruction_error.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

# =============================================================================
# 9. TARGET ACCOUNTING
# =============================================================================

print("\n" + "=" * 80)
print("8. TARGET ACCOUNTING VALIDATION")
print("=" * 80)

target_error = (
    check[
        "optimized_goal_funding"
    ]
    +
    check[
        "optimized_shortfall"
    ]
    -
    check[
        "target_amount"
    ]
)

print(
    "Maximum target accounting error:",
    target_error.abs().max()
)

print(
    "Users satisfying target equation <=1e-6:",
    (
        target_error.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

negative_D = (
    check[
        "optimized_shortfall"
    ] < -1e-6
).sum()

print(
    "Negative D values:",
    negative_D
)

# =============================================================================
# 10. INDEPENDENT OPTIMAL FUNDING RECONSTRUCTION
# =============================================================================

print("\n" + "=" * 80)
print("9. INDEPENDENT OPTIMALITY VALIDATION")
print("=" * 80)

check[
    "analytical_max_funding"
] = np.minimum(
    check["target_amount"],
    check["reconstructed_positive_cash"]
)

check[
    "analytical_shortfall"
] = np.maximum(
    check["target_amount"]
    -
    check["reconstructed_positive_cash"],
    0
)

funding_optimality_error = (
    check[
        "optimized_goal_funding"
    ]
    -
    check[
        "analytical_max_funding"
    ]
)

shortfall_optimality_error = (
    check[
        "optimized_shortfall"
    ]
    -
    check[
        "analytical_shortfall"
    ]
)

print(
    "Maximum funding optimality error:",
    funding_optimality_error.abs().max()
)

print(
    "Maximum shortfall optimality error:",
    shortfall_optimality_error.abs().max()
)

print(
    "Optimal funding matches <=1e-6:",
    (
        funding_optimality_error.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

print(
    "Optimal shortfall matches <=1e-6:",
    (
        shortfall_optimality_error.abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

# =============================================================================
# 11. HISTORICAL FUNDING MUST REMAIN UNCHANGED
# =============================================================================

print("\n" + "=" * 80)
print("10. HISTORICAL FUNDING INTEGRITY")
print("=" * 80)

historical = lp[
    [
        "user_id",
        "goal_horizon_funding_actual",
        "target_amount",
        "goal_horizon_months"
    ]
].copy()

historical = historical.rename(
    columns={
        "goal_horizon_funding_actual":
            "historical_funding"
    }
)

hist_check = check.merge(
    historical,
    on="user_id",
    how="left",
    validate="one_to_one"
)

print(
    "Historical funding missing after merge:",
    hist_check[
        "historical_funding"
    ].isna().sum()
)

# =============================================================================
# 12. SUCCESS CLASSIFICATION
# =============================================================================

print("\n" + "=" * 80)
print("11. SUCCESS CLASSIFICATION")
print("=" * 80)

hist_check[
    "historical_success"
] = (
    hist_check[
        "historical_funding"
    ]
    >=
    hist_check[
        "target_amount"
    ]
    -
    1e-6
)

hist_check[
    "optimized_success_reconstructed"
] = (
    hist_check[
        "optimized_goal_funding"
    ]
    >=
    hist_check[
        "target_amount"
    ]
    -
    1e-6
)

print(
    "Historical success:",
    hist_check[
        "historical_success"
    ].sum()
)

print(
    "Optimized success:",
    hist_check[
        "optimized_success_reconstructed"
    ].sum()
)

print(
    "Newly successful:",
    (
        (~hist_check["historical_success"])
        &
        hist_check["optimized_success_reconstructed"]
    ).sum()
)

print(
    "Still unsuccessful:",
    (
        ~hist_check[
            "optimized_success_reconstructed"
        ]
    ).sum()
)

# =============================================================================
# 13. IMPORTANT FEASIBILITY RECHECK
# =============================================================================

print("\n" + "=" * 80)
print("12. FEASIBILITY BOUNDARY RECHECK")
print("=" * 80)

hist_check[
    "cash_flow_feasible"
] = (
    hist_check[
        "reconstructed_positive_cash"
    ]
    >=
    hist_check[
        "target_amount"
    ]
    -
    1e-6
)

print(
    "Cash-flow feasible users:",
    hist_check[
        "cash_flow_feasible"
    ].sum(),
    "/",
    len(hist_check)
)

print(
    "Cash-flow infeasible users:",
    (
        ~hist_check[
            "cash_flow_feasible"
        ]
    ).sum()
)

print(
    "LP optimized successful:",
    hist_check[
        "optimized_success_reconstructed"
    ].sum()
)

# Users who have enough cash according to the exact bound
# but were not classified successful by the saved LP result.
boundary_discrepancy = hist_check[
    hist_check["cash_flow_feasible"]
    &
    (~hist_check["optimized_success_reconstructed"])
].copy()

print(
    "Feasible-but-not-successful users:",
    len(boundary_discrepancy)
)

# =============================================================================
# 14. DISCREPANCY DETAILS
# =============================================================================

if len(boundary_discrepancy) > 0:

    boundary_discrepancy[
        "feasibility_margin"
    ] = (
        boundary_discrepancy[
            "reconstructed_positive_cash"
        ]
        -
        boundary_discrepancy[
            "target_amount"
        ]
    )

    print(
        "\nFeasibility discrepancy summary:"
    )

    print(
        boundary_discrepancy[
            [
                "user_id",
                "target_amount",
                "reconstructed_positive_cash",
                "optimized_goal_funding",
                "optimized_shortfall",
                "feasibility_margin"
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

    print(
        "\nMean feasibility margin:",
        boundary_discrepancy[
            "feasibility_margin"
        ].mean()
    )

    print(
        "Minimum feasibility margin:",
        boundary_discrepancy[
            "feasibility_margin"
        ].min()
    )

    print(
        "Maximum feasibility margin:",
        boundary_discrepancy[
            "feasibility_margin"
        ].max()
    )

# =============================================================================
# 15. SAVE VALIDATION
# =============================================================================

validation_columns = [
    "user_id",
    "horizon_months",
    "target_amount",
    "existing_funding",
    "optimized_goal_funding",
    "optimized_shortfall",
    "reconstructed_funding",
    "reconstructed_positive_cash",
    "analytical_max_funding",
    "analytical_shortfall",
    "historical_success",
    "optimized_success_reconstructed",
    "cash_flow_feasible",
    "target_constraint_error",
    "goal_funding_error",
    "shortfall_error"
]

validation_df = hist_check.copy()

# Rename errors into clear validation names
validation_df[
    "target_constraint_error"
] = target_error

validation_df[
    "goal_funding_error"
] = funding_optimality_error

validation_df[
    "shortfall_error"
] = shortfall_optimality_error

validation_df[
    validation_columns
].to_csv(
    os.path.join(
        OUT,
        "lp_5u_full_solution_validation.csv"
    ),
    index=False
)

# Save discrepancy separately
boundary_discrepancy.to_csv(
    os.path.join(
        OUT,
        "lp_5u_feasibility_discrepancy.csv"
    ),
    index=False
)

# =============================================================================
# 16. FINAL SUMMARY
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5U VALIDATION SUMMARY")
print("=" * 80)

print(
    "Users:",
    len(hist_check)
)

print(
    "Unique users:",
    hist_check["user_id"].nunique()
)

print(
    "Duplicate users:",
    hist_check["user_id"].duplicated().sum()
)

print(
    "Monthly rows:",
    len(opt_monthly)
)

print(
    "Expected horizon rows:",
    expected_horizon_rows
)

print(
    "Maximum target error:",
    target_error.abs().max()
)

print(
    "Maximum funding reconstruction error:",
    funding_reconstruction_error.abs().max()
)

print(
    "Maximum upper-bound violation:",
    max_upper_violation
)

print(
    "Maximum residual reconstruction error:",
    residual_error.abs().max()
)

print(
    "Cash-flow feasible:",
    hist_check["cash_flow_feasible"].sum()
)

print(
    "Optimized successful:",
    hist_check[
        "optimized_success_reconstructed"
    ].sum()
)

print(
    "Feasible but unsuccessful:",
    len(boundary_discrepancy)
)

print("\nSaved:")
print(
    os.path.join(
        OUT,
        "lp_5u_full_solution_validation.csv"
    )
)

print(
    os.path.join(
        OUT,
        "lp_5u_feasibility_discrepancy.csv"
    )
)

print("\n" + "=" * 80)
print("STEP 5U COMPLETE")
print("=" * 80)

================================================================================
STEP 5U — FULL LP SOLUTION INDEPENDENT VALIDATION
================================================================================

Original LP: (10000, 38)
Original monthly: (1430000, 46)
Optimization user: (10000, 17)
Optimization monthly: (626970, 8)

================================================================================
1. USER-LEVEL INTEGRITY
================================================================================
Original LP users: 10000
Optimization users: 10000
Duplicate optimization users: 0
Missing users: 0
Unexpected users: 0

================================================================================
2. MONTHLY ROW INTEGRITY
================================================================================
Expected horizon rows: 626970
Optimization monthly rows: 626970
Duplicate user-period rows: 0

================================================================================
3. MISSING / INFINITE VALUES
================================================================================
Optimization user missing values: 0
Optimization monthly missing values: 0
Optimization user infinite values: 0
Optimization monthly infinite values: 0

================================================================================
4. MONTHLY NON-NEGATIVITY
================================================================================
Negative optimized G values: 0
Negative residual cash values: 0

================================================================================
5. GOAL FUNDING UPPER-BOUND VALIDATION
================================================================================
Maximum G - PositiveCashFlow: 0.0
Maximum upper-bound violation: 0
Rows satisfying G <= PositiveCashFlow: 626970 / 626970

================================================================================
6. RESIDUAL CASH VALIDATION
================================================================================
Maximum residual reconstruction error: 5.820766091346741e-11
Rows matching <=1e-6: 626970 / 626970

================================================================================
7. INDEPENDENT MONTHLY → USER RECONSTRUCTION
================================================================================
Maximum funding reconstruction error: 2.3283064365386963e-10
Users matching <=1e-6: 10000 / 10000

================================================================================
8. TARGET ACCOUNTING VALIDATION
================================================================================
Maximum target accounting error: 2.3283064365386963e-10
Users satisfying target equation <=1e-6: 10000 / 10000
Negative D values: 0

================================================================================
9. INDEPENDENT OPTIMALITY VALIDATION
================================================================================
Maximum funding optimality error: 2.3283064365386963e-10
Maximum shortfall optimality error: 1.7462298274040222e-10
Optimal funding matches <=1e-6: 10000 / 10000
Optimal shortfall matches <=1e-6: 10000 / 10000

================================================================================
10. HISTORICAL FUNDING INTEGRITY
================================================================================
Historical funding missing after merge: 0

================================================================================
11. SUCCESS CLASSIFICATION
================================================================================

KeyError: 'target_amount'

In [115]:
# =============================================================================
# STEP 5U — CORRECTED CONTINUATION
# Starts from the saved optimization outputs.
# No LP solver is run again.
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OPT_USER_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_user_summary.csv"
)

OPT_MONTHLY_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_monthly.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

print("=" * 80)
print("STEP 5U — CORRECTED CONTINUATION")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
opt_user = pd.read_csv(OPT_USER_PATH)
opt_monthly = pd.read_csv(OPT_MONTHLY_PATH)

print("\nLP:", lp.shape)
print("Optimization user:", opt_user.shape)
print("Optimization monthly:", opt_monthly.shape)

# =============================================================================
# 2. CREATE CLEAN HISTORICAL REFERENCE
# =============================================================================

historical = lp[
    [
        "user_id",
        "goal_horizon_funding_actual",
        "target_amount",
        "goal_horizon_months"
    ]
].copy()

historical = historical.rename(
    columns={
        "goal_horizon_funding_actual":
            "historical_funding",
        "target_amount":
            "historical_target",
        "goal_horizon_months":
            "historical_horizon"
    }
)

# =============================================================================
# 3. CREATE CLEAN OPTIMIZATION REFERENCE
# =============================================================================

opt = opt_user[
    [
        "user_id",
        "target_amount",
        "optimized_goal_funding",
        "optimized_shortfall"
    ]
].copy()

# =============================================================================
# 4. MERGE WITHOUT COLUMN COLLISION
# =============================================================================

check = opt.merge(
    historical,
    on="user_id",
    how="left",
    validate="one_to_one"
)

print("\nMerged validation shape:", check.shape)

# =============================================================================
# 5. HISTORICAL SUCCESS
# =============================================================================

check[
    "historical_success"
] = (
    check["historical_funding"]
    >=
    check["target_amount"]
    - 1e-6
)

# =============================================================================
# 6. OPTIMIZED SUCCESS
# =============================================================================

check[
    "optimized_success"
] = (
    check["optimized_goal_funding"]
    >=
    check["target_amount"]
    - 1e-6
)

# =============================================================================
# 7. INDEPENDENT MONTHLY RECONSTRUCTION
# =============================================================================

monthly_reconstructed = (
    opt_monthly
    .groupby("user_id")
    .agg(
        reconstructed_funding=(
            "optimized_goal_funding",
            "sum"
        ),
        reconstructed_positive_cash=(
            "positive_cash_flow",
            "sum"
        ),
        reconstructed_months=(
            "simulation_month",
            "count"
        )
    )
    .reset_index()
)

check = check.merge(
    monthly_reconstructed,
    on="user_id",
    how="left",
    validate="one_to_one"
)

# =============================================================================
# 8. OPTIMAL FUNDING
# =============================================================================

check[
    "analytical_max_funding"
] = np.minimum(
    check["target_amount"],
    check["reconstructed_positive_cash"]
)

check[
    "analytical_shortfall"
] = np.maximum(
    check["target_amount"]
    -
    check["reconstructed_positive_cash"],
    0
)

# =============================================================================
# 9. ERROR CHECKS
# =============================================================================

check[
    "funding_reconstruction_error"
] = (
    check["optimized_goal_funding"]
    -
    check["reconstructed_funding"]
)

check[
    "target_accounting_error"
] = (
    check["optimized_goal_funding"]
    +
    check["optimized_shortfall"]
    -
    check["target_amount"]
)

check[
    "funding_optimality_error"
] = (
    check["optimized_goal_funding"]
    -
    check["analytical_max_funding"]
)

check[
    "shortfall_optimality_error"
] = (
    check["optimized_shortfall"]
    -
    check["analytical_shortfall"]
)

# =============================================================================
# 10. CASH-FLOW FEASIBILITY
# =============================================================================

check[
    "cash_flow_feasible"
] = (
    check["reconstructed_positive_cash"]
    >=
    check["target_amount"]
    - 1e-6
)

# =============================================================================
# 11. IMPORTANT SUCCESS ANALYSIS
# =============================================================================

print("\n" + "=" * 80)
print("SUCCESS CLASSIFICATION")
print("=" * 80)

historical_success_count = int(
    check["historical_success"].sum()
)

optimized_success_count = int(
    check["optimized_success"].sum()
)

feasible_count = int(
    check["cash_flow_feasible"].sum()
)

new_success_count = int(
    (
        (~check["historical_success"])
        &
        check["optimized_success"]
    ).sum()
)

still_unsuccessful = int(
    (~check["optimized_success"]).sum()
)

print(
    "Historical-policy successful:",
    historical_success_count,
    "/ 10000"
)

print(
    "Optimized successful:",
    optimized_success_count,
    "/ 10000"
)

print(
    "Cash-flow feasible:",
    feasible_count,
    "/ 10000"
)

print(
    "Newly successful:",
    new_success_count
)

print(
    "Still unsuccessful:",
    still_unsuccessful
)

# =============================================================================
# 12. INVESTIGATE THE 7,582 vs 6,540 ISSUE
# =============================================================================

print("\n" + "=" * 80)
print("FEASIBILITY DISCREPANCY ANALYSIS")
print("=" * 80)

discrepancy = check[
    check["cash_flow_feasible"]
    &
    (~check["optimized_success"])
].copy()

print(
    "Feasible but optimized unsuccessful:",
    len(discrepancy)
)

if len(discrepancy) > 0:

    discrepancy[
        "feasibility_margin"
    ] = (
        discrepancy["reconstructed_positive_cash"]
        -
        discrepancy["target_amount"]
    )

    print("\nFirst 20 discrepancy users:")

    print(
        discrepancy[
            [
                "user_id",
                "target_amount",
                "reconstructed_positive_cash",
                "optimized_goal_funding",
                "optimized_shortfall",
                "feasibility_margin"
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

    print(
        "\nMean feasibility margin:",
        discrepancy["feasibility_margin"].mean()
    )

    print(
        "Minimum feasibility margin:",
        discrepancy["feasibility_margin"].min()
    )

    print(
        "Maximum feasibility margin:",
        discrepancy["feasibility_margin"].max()
    )

# =============================================================================
# 13. WHY THE 7,582 FIGURE MAY DIFFER
# =============================================================================
#
# Check whether reconstructed_positive_cash really corresponds to the exact
# horizon for every user.
# =============================================================================

print("\n" + "=" * 80)
print("HORIZON RECONSTRUCTION CHECK")
print("=" * 80)

horizon_mismatch = (
    check["reconstructed_months"]
    !=
    check["historical_horizon"]
)

print(
    "Users with reconstructed horizon mismatch:",
    horizon_mismatch.sum()
)

print(
    "Minimum reconstructed months:",
    check["reconstructed_months"].min()
)

print(
    "Maximum reconstructed months:",
    check["reconstructed_months"].max()
)

# =============================================================================
# 14. VALIDATION SUMMARY
# =============================================================================

print("\n" + "=" * 80)
print("VALIDATION SUMMARY")
print("=" * 80)

print(
    "Maximum funding reconstruction error:",
    check[
        "funding_reconstruction_error"
    ].abs().max()
)

print(
    "Maximum target accounting error:",
    check[
        "target_accounting_error"
    ].abs().max()
)

print(
    "Maximum funding optimality error:",
    check[
        "funding_optimality_error"
    ].abs().max()
)

print(
    "Maximum shortfall optimality error:",
    check[
        "shortfall_optimality_error"
    ].abs().max()
)

print(
    "Funding reconstruction <=1e-6:",
    (
        check[
            "funding_reconstruction_error"
        ].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

print(
    "Target accounting <=1e-6:",
    (
        check[
            "target_accounting_error"
        ].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

print(
    "Optimal funding <=1e-6:",
    (
        check[
            "funding_optimality_error"
        ].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

print(
    "Optimal shortfall <=1e-6:",
    (
        check[
            "shortfall_optimality_error"
        ].abs()
        <= 1e-6
    ).sum(),
    "/",
    len(check)
)

# =============================================================================
# 15. SAVE CLEAN VALIDATION
# =============================================================================

validation_path = os.path.join(
    OUT,
    "lp_5u_full_solution_validation.csv"
)

discrepancy_path = os.path.join(
    OUT,
    "lp_5u_feasibility_discrepancy.csv"
)

check.to_csv(
    validation_path,
    index=False
)

discrepancy.to_csv(
    discrepancy_path,
    index=False
)

# =============================================================================
# 16. FINAL
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5U COMPLETE")
print("=" * 80)

print("\nSaved:")
print(validation_path)
print(discrepancy_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO OPTIMIZATION VALUES WERE CHANGED.")
print("ONLY VALIDATION FILES WERE CREATED.")

================================================================================
STEP 5U — CORRECTED CONTINUATION
================================================================================

LP: (10000, 38)
Optimization user: (10000, 17)
Optimization monthly: (626970, 8)

Merged validation shape: (10000, 7)

================================================================================
SUCCESS CLASSIFICATION
================================================================================
Historical-policy successful: 6451 / 10000
Optimized successful: 7582 / 10000
Cash-flow feasible: 7582 / 10000
Newly successful: 1131
Still unsuccessful: 2418

================================================================================
FEASIBILITY DISCREPANCY ANALYSIS
================================================================================
Feasible but optimized unsuccessful: 0

================================================================================
HORIZON RECONSTRUCTION CHECK
================================================================================
Users with reconstructed horizon mismatch: 0
Minimum reconstructed months: 6
Maximum reconstructed months: 120

================================================================================
VALIDATION SUMMARY
================================================================================
Maximum funding reconstruction error: 2.3283064365386963e-10
Maximum target accounting error: 2.3283064365386963e-10
Maximum funding optimality error: 2.3283064365386963e-10
Maximum shortfall optimality error: 1.7462298274040222e-10
Funding reconstruction <=1e-6: 10000 / 10000
Target accounting <=1e-6: 10000 / 10000
Optimal funding <=1e-6: 10000 / 10000
Optimal shortfall <=1e-6: 10000 / 10000

================================================================================
STEP 5U COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5u_full_solution_validation.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5u_feasibility_discrepancy.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO OPTIMIZATION VALUES WERE CHANGED.
ONLY VALIDATION FILES WERE CREATED.

In [116]:
# =============================================================================
# STEP 5V — HISTORICAL VS OPTIMIZED PERFORMANCE ANALYSIS
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OPT_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_user_summary.csv"
)

VALIDATION_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5u_full_solution_validation.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

print("=" * 80)
print("STEP 5V — HISTORICAL VS OPTIMIZED PERFORMANCE ANALYSIS")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
opt = pd.read_csv(OPT_PATH)
validation = pd.read_csv(VALIDATION_PATH)

print("\nLP:", lp.shape)
print("Optimization:", opt.shape)
print("Validation:", validation.shape)

# =============================================================================
# 2. BUILD CLEAN COMPARISON DATASET
# =============================================================================

base_cols = [
    "user_id",
    "target_amount",
    "goal_horizon_months",
    "goal_horizon_funding_actual"
]

comparison = lp[
    base_cols
].copy()

comparison = comparison.rename(
    columns={
        "goal_horizon_funding_actual":
            "historical_funding"
    }
)

opt_cols = [
    "user_id",
    "optimized_goal_funding",
    "optimized_shortfall"
]

comparison = comparison.merge(
    opt[
        opt_cols
    ],
    on="user_id",
    how="left",
    validate="one_to_one"
)

# =============================================================================
# 3. HISTORICAL SHORTFALL
# =============================================================================

comparison[
    "historical_shortfall"
] = np.maximum(
    comparison["target_amount"]
    -
    comparison["historical_funding"],
    0
)

# =============================================================================
# 4. SUCCESS FLAGS
# =============================================================================

comparison[
    "historical_success"
] = (
    comparison["historical_funding"]
    >=
    comparison["target_amount"]
    -
    1e-6
)

comparison[
    "optimized_success"
] = (
    comparison["optimized_goal_funding"]
    >=
    comparison["target_amount"]
    -
    1e-6
)

# =============================================================================
# 5. TRANSITION CATEGORIES
# =============================================================================

def classify_transition(row):

    historical = row["historical_success"]
    optimized = row["optimized_success"]

    if historical and optimized:
        return "Successful → Successful"

    if (not historical) and optimized:
        return "Failed → Successful"

    if historical and (not optimized):
        return "Successful → Failed"

    return "Failed → Failed"


comparison[
    "success_transition"
] = comparison.apply(
    classify_transition,
    axis=1
)

# =============================================================================
# 6. FUNDING DIFFERENCE
# =============================================================================

comparison[
    "funding_change"
] = (
    comparison["optimized_goal_funding"]
    -
    comparison["historical_funding"]
)

comparison[
    "shortfall_reduction"
] = (
    comparison["historical_shortfall"]
    -
    comparison["optimized_shortfall"]
)

# =============================================================================
# 7. CORE PERFORMANCE
# =============================================================================

print("\n" + "=" * 80)
print("CORE PERFORMANCE")
print("=" * 80)

historical_success = int(
    comparison["historical_success"].sum()
)

optimized_success = int(
    comparison["optimized_success"].sum()
)

total_users = len(comparison)

historical_rate = (
    historical_success
    /
    total_users
)

optimized_rate = (
    optimized_success
    /
    total_users
)

print(
    "\nHistorical successful:",
    historical_success,
    "/",
    total_users
)

print(
    "Historical success rate:",
    historical_rate
)

print(
    "\nOptimized successful:",
    optimized_success,
    "/",
    total_users
)

print(
    "Optimized success rate:",
    optimized_rate
)

print(
    "\nAbsolute success-rate improvement:",
    optimized_rate - historical_rate
)

print(
    "Percentage-point improvement:",
    (optimized_rate - historical_rate) * 100
)

# =============================================================================
# 8. TRANSITION ANALYSIS
# =============================================================================

print("\n" + "=" * 80)
print("SUCCESS TRANSITIONS")
print("=" * 80)

transition_counts = (
    comparison[
        "success_transition"
    ]
    .value_counts()
)

for category in [
    "Successful → Successful",
    "Failed → Successful",
    "Successful → Failed",
    "Failed → Failed"
]:

    print(
        f"{category}:",
        int(
            transition_counts.get(
                category,
                0
            )
        )
    )

# =============================================================================
# 9. FUNDING STATISTICS
# =============================================================================

print("\n" + "=" * 80)
print("FUNDING STATISTICS")
print("=" * 80)

print(
    "\nMean historical funding:",
    comparison[
        "historical_funding"
    ].mean()
)

print(
    "Mean optimized funding:",
    comparison[
        "optimized_goal_funding"
    ].mean()
)

print(
    "Median historical funding:",
    comparison[
        "historical_funding"
    ].median()
)

print(
    "Median optimized funding:",
    comparison[
        "optimized_goal_funding"
    ].median()
)

print(
    "Mean funding change:",
    comparison[
        "funding_change"
    ].mean()
)

print(
    "Median funding change:",
    comparison[
        "funding_change"
    ].median()
)

print(
    "Total historical funding:",
    comparison[
        "historical_funding"
    ].sum()
)

print(
    "Total optimized funding:",
    comparison[
        "optimized_goal_funding"
    ].sum()
)

# =============================================================================
# 10. SHORTFALL STATISTICS
# =============================================================================

print("\n" + "=" * 80)
print("SHORTFALL ANALYSIS")
print("=" * 80)

print(
    "\nMean historical shortfall:",
    comparison[
        "historical_shortfall"
    ].mean()
)

print(
    "Mean optimized shortfall:",
    comparison[
        "optimized_shortfall"
    ].mean()
)

print(
    "Mean shortfall reduction:",
    comparison[
        "shortfall_reduction"
    ].mean()
)

print(
    "Total historical shortfall:",
    comparison[
        "historical_shortfall"
    ].sum()
)

print(
    "Total optimized shortfall:",
    comparison[
        "optimized_shortfall"
    ].sum()
)

print(
    "Total shortfall reduction:",
    comparison[
        "shortfall_reduction"
    ].sum()
)

# =============================================================================
# 11. NEWLY SUCCESSFUL USERS
# =============================================================================

newly_successful = comparison[
    (~comparison["historical_success"])
    &
    comparison["optimized_success"]
].copy()

print("\n" + "=" * 80)
print("NEWLY SUCCESSFUL USERS")
print("=" * 80)

print(
    "\nNewly successful:",
    len(newly_successful)
)

if len(newly_successful) > 0:

    print(
        "Mean target:",
        newly_successful[
            "target_amount"
        ].mean()
    )

    print(
        "Mean historical funding:",
        newly_successful[
            "historical_funding"
        ].mean()
    )

    print(
        "Mean optimized funding:",
        newly_successful[
            "optimized_goal_funding"
        ].mean()
    )

    print(
        "Mean historical shortfall:",
        newly_successful[
            "historical_shortfall"
        ].mean()
    )

    print(
        "Mean optimized shortfall:",
        newly_successful[
            "optimized_shortfall"
        ].mean()
    )

    print(
        "Mean shortfall reduction:",
        newly_successful[
            "shortfall_reduction"
        ].mean()
    )

# =============================================================================
# 12. STILL UNSUCCESSFUL
# =============================================================================

still_failed = comparison[
    ~comparison["optimized_success"]
].copy()

print("\n" + "=" * 80)
print("USERS STILL UNSUCCESSFUL")
print("=" * 80)

print(
    "\nStill unsuccessful:",
    len(still_failed)
)

if len(still_failed) > 0:

    print(
        "Mean target:",
        still_failed[
            "target_amount"
        ].mean()
    )

    print(
        "Mean optimized funding:",
        still_failed[
            "optimized_goal_funding"
        ].mean()
    )

    print(
        "Mean optimized shortfall:",
        still_failed[
            "optimized_shortfall"
        ].mean()
    )

# =============================================================================
# 13. SUCCESSFUL USERS UNDER BOTH
# =============================================================================

both_successful = comparison[
    comparison["historical_success"]
    &
    comparison["optimized_success"]
]

print("\n" + "=" * 80)
print("USERS SUCCESSFUL UNDER BOTH POLICIES")
print("=" * 80)

print(
    "Users successful under both:",
    len(both_successful)
)

# =============================================================================
# 14. UNSUPPORTED REGRESSION CHECK
# =============================================================================

regressions = comparison[
    comparison["historical_success"]
    &
    (~comparison["optimized_success"])
]

print("\n" + "=" * 80)
print("REGRESSION CHECK")
print("=" * 80)

print(
    "Historical-success → optimized-failure:",
    len(regressions)
)

# =============================================================================
# 15. VALIDATION AGAINST STEP 5U
# =============================================================================

print("\n" + "=" * 80)
print("VALIDATION AGAINST STEP 5U")
print("=" * 80)

validated_optimized = int(
    validation[
        "optimized_success"
    ].sum()
)

print(
    "Step 5U optimized success:",
    validated_optimized
)

print(
    "Step 5V optimized success:",
    optimized_success
)

print(
    "Success-count agreement:",
    validated_optimized
    ==
    optimized_success
)

# =============================================================================
# 16. SAVE USER-LEVEL COMPARISON
# =============================================================================

comparison_path = os.path.join(
    OUT,
    "lp_5v_historical_vs_optimized_user_comparison.csv"
)

comparison.to_csv(
    comparison_path,
    index=False
)

# =============================================================================
# 17. SAVE TRANSITION SUMMARY
# =============================================================================

transition_summary = pd.DataFrame({
    "transition": [
        "Successful → Successful",
        "Failed → Successful",
        "Successful → Failed",
        "Failed → Failed"
    ],
    "users": [
        int(
            (
                comparison[
                    "success_transition"
                ]
                ==
                "Successful → Successful"
            ).sum()
        ),
        int(
            (
                comparison[
                    "success_transition"
                ]
                ==
                "Failed → Successful"
            ).sum()
        ),
        int(
            (
                comparison[
                    "success_transition"
                ]
                ==
                "Successful → Failed"
            ).sum()
        ),
        int(
            (
                comparison[
                    "success_transition"
                ]
                ==
                "Failed → Failed"
            ).sum()
        )
    ]
})

transition_path = os.path.join(
    OUT,
    "lp_5v_success_transition_summary.csv"
)

transition_summary.to_csv(
    transition_path,
    index=False
)

# =============================================================================
# 18. FINAL
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5V COMPLETE")
print("=" * 80)

print("\nSaved:")
print(comparison_path)
print(transition_path)

print("\nNO ORIGINAL DATASET WAS MODIFIED.")
print("NO LP SOLVER WAS RUN.")
print("THIS STEP ONLY ANALYZED THE VALIDATED OPTIMIZATION OUTPUT.")

================================================================================
STEP 5V — HISTORICAL VS OPTIMIZED PERFORMANCE ANALYSIS
================================================================================

LP: (10000, 38)
Optimization: (10000, 17)
Validation: (10000, 19)

================================================================================
CORE PERFORMANCE
================================================================================

Historical successful: 6451 / 10000
Historical success rate: 0.6451

Optimized successful: 7582 / 10000
Optimized success rate: 0.7582

Absolute success-rate improvement: 0.11309999999999998
Percentage-point improvement: 11.309999999999999

================================================================================
SUCCESS TRANSITIONS
================================================================================
Successful → Successful: 6451
Failed → Successful: 1131
Successful → Failed: 0
Failed → Failed: 2418

================================================================================
FUNDING STATISTICS
================================================================================

Mean historical funding: 944964.8307231049
Mean optimized funding: 116113.00752071626
Median historical funding: 236498.48196910552
Median optimized funding: 92956.38643156183
Mean funding change: -828851.8232023886
Median funding change: -129743.17303522985
Total historical funding: 9449648307.231049
Total optimized funding: 1161130075.2071626

================================================================================
SHORTFALL ANALYSIS
================================================================================

Mean historical shortfall: 30580.490390871095
Mean optimized shortfall: 22240.82745179166
Mean shortfall reduction: 8339.662939079435
Total historical shortfall: 305804903.90871096
Total optimized shortfall: 222408274.51791662
Total shortfall reduction: 83396629.39079435

================================================================================
NEWLY SUCCESSFUL USERS
================================================================================

Newly successful: 1131
Mean target: 103122.30849752916
Mean historical funding: 59910.19855825913
Mean optimized funding: 103122.30849752916
Mean historical shortfall: 43212.109939270034
Mean optimized shortfall: 0.0
Mean shortfall reduction: 43212.109939270034

================================================================================
USERS STILL UNSUCCESSFUL
================================================================================

Still unsuccessful: 2418
Mean target: 115685.12245280677
Mean optimized funding: 23704.860038449202
Mean optimized shortfall: 91980.26241435757

================================================================================
USERS SUCCESSFUL UNDER BOTH POLICIES
================================================================================
Users successful under both: 6451

================================================================================
REGRESSION CHECK
================================================================================
Historical-success → optimized-failure: 0

================================================================================
VALIDATION AGAINST STEP 5U
================================================================================
Step 5U optimized success: 7582
Step 5V optimized success: 7582
Success-count agreement: True

================================================================================
STEP 5V COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5v_historical_vs_optimized_user_comparison.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5v_success_transition_summary.csv

NO ORIGINAL DATASET WAS MODIFIED.
NO LP SOLVER WAS RUN.
THIS STEP ONLY ANALYZED THE VALIDATED OPTIMIZATION OUTPUT.

In [117]:
# =============================================================================
# STEP 5W — SEGMENT-WISE OPTIMIZATION ANALYSIS
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

COMPARISON_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5v_historical_vs_optimized_user_comparison.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

print("=" * 80)
print("STEP 5W — SEGMENT-WISE OPTIMIZATION ANALYSIS")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
comparison = pd.read_csv(COMPARISON_PATH)

print("\nLP:", lp.shape)
print("Comparison:", comparison.shape)

# =============================================================================
# 2. ADD SEGMENT VARIABLES
# =============================================================================

segment_cols = [
    "user_id",
    "financial_situation",
    "risk_profile",
    "risk_score",
    "goal_horizon_months",
    "target_amount"
]

segments = lp[
    segment_cols
].copy()

comparison = comparison.merge(
    segments,
    on="user_id",
    how="left",
    validate="one_to_one"
)

# =============================================================================
# 3. COMMON DERIVED METRICS
# =============================================================================

comparison[
    "historical_success"
] = (
    comparison["historical_funding"]
    >=
    comparison["target_amount"]
    - 1e-6
)

comparison[
    "optimized_success"
] = (
    comparison["optimized_goal_funding"]
    >=
    comparison["target_amount"]
    - 1e-6
)

comparison[
    "newly_successful"
] = (
    (~comparison["historical_success"])
    &
    comparison["optimized_success"]
)

comparison[
    "shortfall_reduction"
] = (
    comparison["historical_shortfall"]
    -
    comparison["optimized_shortfall"]
)

# =============================================================================
# 4. ANALYSIS FUNCTION
# =============================================================================

def segment_analysis(
    df,
    segment
):

    result = (
        df.groupby(segment)
        .agg(
            users=(
                "user_id",
                "nunique"
            ),

            historical_successful=(
                "historical_success",
                "sum"
            ),

            optimized_successful=(
                "optimized_success",
                "sum"
            ),

            newly_successful=(
                "newly_successful",
                "sum"
            ),

            historical_success_rate=(
                "historical_success",
                "mean"
            ),

            optimized_success_rate=(
                "optimized_success",
                "mean"
            ),

            mean_target=(
                "target_amount",
                "mean"
            ),

            mean_historical_funding=(
                "historical_funding",
                "mean"
            ),

            mean_optimized_funding=(
                "optimized_goal_funding",
                "mean"
            ),

            mean_historical_shortfall=(
                "historical_shortfall",
                "mean"
            ),

            mean_optimized_shortfall=(
                "optimized_shortfall",
                "mean"
            ),

            mean_shortfall_reduction=(
                "shortfall_reduction",
                "mean"
            )
        )
        .reset_index()
    )

    result[
        "success_rate_improvement_pp"
    ] = (
        result[
            "optimized_success_rate"
        ]
        -
        result[
            "historical_success_rate"
        ]
    ) * 100

    return result


# =============================================================================
# 5. FINANCIAL SITUATION ANALYSIS
# =============================================================================

print("\n" + "=" * 80)
print("A. FINANCIAL SITUATION")
print("=" * 80)

financial_analysis = segment_analysis(
    comparison,
    "financial_situation"
)

print(
    financial_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 6. RISK PROFILE ANALYSIS
# =============================================================================

print("\n" + "=" * 80)
print("B. RISK PROFILE")
print("=" * 80)

risk_analysis = segment_analysis(
    comparison,
    "risk_profile"
)

print(
    risk_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 7. GOAL HORIZON GROUPS
# =============================================================================
#
# Group horizons into descriptive ranges.
# These are analytical bins only; they do not change the LP.
# =============================================================================

comparison[
    "horizon_group"
] = pd.cut(
    comparison[
        "goal_horizon_months"
    ],
    bins=[
        0,
        12,
        24,
        36,
        60,
        120
    ],
    labels=[
        "1-12 months",
        "13-24 months",
        "25-36 months",
        "37-60 months",
        "61-120 months"
    ],
    include_lowest=True
)

print("\n" + "=" * 80)
print("C. GOAL HORIZON")
print("=" * 80)

horizon_analysis = segment_analysis(
    comparison,
    "horizon_group"
)

print(
    horizon_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 8. RISK SCORE BANDS
# =============================================================================
#
# Analytical grouping only.
# No new risk thresholds are used in the LP.
# =============================================================================

comparison[
    "risk_score_band"
] = pd.cut(
    comparison[
        "risk_score"
    ],
    bins=[
        0,
        0.25,
        0.50,
        0.75,
        1.00
    ],
    labels=[
        "0.00-0.25",
        "0.25-0.50",
        "0.50-0.75",
        "0.75-1.00"
    ],
    include_lowest=True
)

print("\n" + "=" * 80)
print("D. RISK SCORE BAND")
print("=" * 80)

risk_score_analysis = segment_analysis(
    comparison,
    "risk_score_band"
)

print(
    risk_score_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 9. OVERALL SUMMARY
# =============================================================================

print("\n" + "=" * 80)
print("E. OVERALL SUMMARY")
print("=" * 80)

print(
    "Users:",
    len(comparison)
)

print(
    "Historical success:",
    comparison["historical_success"].sum()
)

print(
    "Optimized success:",
    comparison["optimized_success"].sum()
)

print(
    "Newly successful:",
    comparison["newly_successful"].sum()
)

print(
    "Historical success rate:",
    comparison["historical_success"].mean()
)

print(
    "Optimized success rate:",
    comparison["optimized_success"].mean()
)

print(
    "Success improvement (percentage points):",
    (
        comparison["optimized_success"].mean()
        -
        comparison["historical_success"].mean()
    ) * 100
)

print(
    "Mean shortfall reduction:",
    comparison[
        "shortfall_reduction"
    ].mean()
)

# =============================================================================
# 10. CROSS-SEGMENT CHECK
# =============================================================================

print("\n" + "=" * 80)
print("F. CROSS-SEGMENT DATA INTEGRITY")
print("=" * 80)

print(
    "Missing financial situation:",
    comparison[
        "financial_situation"
    ].isna().sum()
)

print(
    "Missing risk profile:",
    comparison[
        "risk_profile"
    ].isna().sum()
)

print(
    "Missing risk score:",
    comparison[
        "risk_score"
    ].isna().sum()
)

print(
    "Missing horizon:",
    comparison[
        "goal_horizon_months"
    ].isna().sum()
)

# =============================================================================
# 11. SAVE RESULTS
# =============================================================================

financial_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_financial_situation.csv"
)

risk_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_risk_profile.csv"
)

horizon_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_goal_horizon.csv"
)

risk_score_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_risk_score_band.csv"
)

financial_analysis.to_csv(
    financial_path,
    index=False
)

risk_analysis.to_csv(
    risk_path,
    index=False
)

horizon_analysis.to_csv(
    horizon_path,
    index=False
)

risk_score_analysis.to_csv(
    risk_score_path,
    index=False
)

# =============================================================================
# 12. FINAL
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5W COMPLETE")
print("=" * 80)

print("\nSaved:")
print(financial_path)
print(risk_path)
print(horizon_path)
print(risk_score_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO OPTIMIZATION RESULTS WERE CHANGED.")
print("ANALYTICAL GROUPING ONLY.")

================================================================================
STEP 5W — SEGMENT-WISE OPTIMIZATION ANALYSIS
================================================================================

LP: (10000, 38)
Comparison: (10000, 12)

KeyError: 'target_amount'

In [118]:
# =============================================================================
# STEP 5W — SEGMENT-WISE OPTIMIZATION ANALYSIS
# CORRECTED VERSION
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

COMPARISON_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5v_historical_vs_optimized_user_comparison.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

print("=" * 80)
print("STEP 5W — SEGMENT-WISE OPTIMIZATION ANALYSIS")
print("=" * 80)

# =============================================================================
# 1. LOAD
# =============================================================================

lp = pd.read_csv(LP_PATH)
comparison = pd.read_csv(COMPARISON_PATH)

print("\nLP:", lp.shape)
print("Comparison:", comparison.shape)

# =============================================================================
# 2. CHECK EXISTING COLUMNS
# =============================================================================

print("\nExisting comparison columns:")
print(
    comparison.columns.tolist()
)

# =============================================================================
# 3. ADD ONLY SEGMENT COLUMNS
# =============================================================================
#
# target_amount and goal_horizon_months already exist in comparison.
# Do NOT merge them again.
# =============================================================================

segment_cols = [
    "user_id",
    "financial_situation",
    "risk_profile",
    "risk_score"
]

segments = lp[
    segment_cols
].copy()

comparison = comparison.merge(
    segments,
    on="user_id",
    how="left",
    validate="one_to_one"
)

# =============================================================================
# 4. VERIFY REQUIRED DATA
# =============================================================================

required = [
    "user_id",
    "target_amount",
    "goal_horizon_months",
    "financial_situation",
    "risk_profile",
    "risk_score",
    "historical_funding",
    "optimized_goal_funding",
    "historical_shortfall",
    "optimized_shortfall"
]

missing = [
    c for c in required
    if c not in comparison.columns
]

print(
    "\nMissing required columns:",
    missing
)

if missing:
    raise ValueError(
        "Required analysis columns are missing."
    )

# =============================================================================
# 5. SUCCESS FLAGS
# =============================================================================

comparison[
    "historical_success"
] = (
    comparison[
        "historical_funding"
    ]
    >=
    comparison[
        "target_amount"
    ]
    - 1e-6
)

comparison[
    "optimized_success"
] = (
    comparison[
        "optimized_goal_funding"
    ]
    >=
    comparison[
        "target_amount"
    ]
    - 1e-6
)

comparison[
    "newly_successful"
] = (
    (~comparison["historical_success"])
    &
    comparison["optimized_success"]
)

comparison[
    "shortfall_reduction"
] = (
    comparison[
        "historical_shortfall"
    ]
    -
    comparison[
        "optimized_shortfall"
    ]
)

# =============================================================================
# 6. SEGMENT ANALYSIS FUNCTION
# =============================================================================

def segment_analysis(df, segment):

    result = (
        df.groupby(segment)
        .agg(
            users=(
                "user_id",
                "nunique"
            ),

            historical_successful=(
                "historical_success",
                "sum"
            ),

            optimized_successful=(
                "optimized_success",
                "sum"
            ),

            newly_successful=(
                "newly_successful",
                "sum"
            ),

            historical_success_rate=(
                "historical_success",
                "mean"
            ),

            optimized_success_rate=(
                "optimized_success",
                "mean"
            ),

            mean_target=(
                "target_amount",
                "mean"
            ),

            mean_historical_funding=(
                "historical_funding",
                "mean"
            ),

            mean_optimized_funding=(
                "optimized_goal_funding",
                "mean"
            ),

            mean_historical_shortfall=(
                "historical_shortfall",
                "mean"
            ),

            mean_optimized_shortfall=(
                "optimized_shortfall",
                "mean"
            ),

            mean_shortfall_reduction=(
                "shortfall_reduction",
                "mean"
            )
        )
        .reset_index()
    )

    result[
        "success_rate_improvement_pp"
    ] = (
        result[
            "optimized_success_rate"
        ]
        -
        result[
            "historical_success_rate"
        ]
    ) * 100

    return result

# =============================================================================
# 7. FINANCIAL SITUATION
# =============================================================================

print("\n" + "=" * 80)
print("A. FINANCIAL SITUATION")
print("=" * 80)

financial_analysis = segment_analysis(
    comparison,
    "financial_situation"
)

print(
    financial_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 8. RISK PROFILE
# =============================================================================

print("\n" + "=" * 80)
print("B. RISK PROFILE")
print("=" * 80)

risk_analysis = segment_analysis(
    comparison,
    "risk_profile"
)

print(
    risk_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 9. GOAL HORIZON
# =============================================================================
#
# Analytical grouping only.
# Does NOT modify the LP.
# =============================================================================

comparison[
    "horizon_group"
] = pd.cut(
    comparison[
        "goal_horizon_months"
    ],
    bins=[
        0,
        12,
        24,
        36,
        60,
        120
    ],
    labels=[
        "1-12 months",
        "13-24 months",
        "25-36 months",
        "37-60 months",
        "61-120 months"
    ],
    include_lowest=True
)

print("\n" + "=" * 80)
print("C. GOAL HORIZON")
print("=" * 80)

horizon_analysis = segment_analysis(
    comparison,
    "horizon_group"
)

print(
    horizon_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 10. RISK SCORE BANDS
# =============================================================================
#
# Analytical grouping only.
# No new risk thresholds are introduced into the LP.
# =============================================================================

comparison[
    "risk_score_band"
] = pd.cut(
    comparison[
        "risk_score"
    ],
    bins=[
        0,
        0.25,
        0.50,
        0.75,
        1.00
    ],
    labels=[
        "0.00-0.25",
        "0.25-0.50",
        "0.50-0.75",
        "0.75-1.00"
    ],
    include_lowest=True
)

print("\n" + "=" * 80)
print("D. RISK SCORE BAND")
print("=" * 80)

risk_score_analysis = segment_analysis(
    comparison,
    "risk_score_band"
)

print(
    risk_score_analysis.to_string(
        index=False
    )
)

# =============================================================================
# 11. OVERALL
# =============================================================================

print("\n" + "=" * 80)
print("E. OVERALL SUMMARY")
print("=" * 80)

total_users = len(comparison)

historical_success = int(
    comparison[
        "historical_success"
    ].sum()
)

optimized_success = int(
    comparison[
        "optimized_success"
    ].sum()
)

newly_successful = int(
    comparison[
        "newly_successful"
    ].sum()
)

print(
    "Users:",
    total_users
)

print(
    "Historical success:",
    historical_success
)

print(
    "Optimized success:",
    optimized_success
)

print(
    "Newly successful:",
    newly_successful
)

print(
    "Historical success rate:",
    historical_success / total_users
)

print(
    "Optimized success rate:",
    optimized_success / total_users
)

print(
    "Success improvement (percentage points):",
    (
        optimized_success
        -
        historical_success
    )
    /
    total_users
    * 100
)

print(
    "Mean shortfall reduction:",
    comparison[
        "shortfall_reduction"
    ].mean()
)

# =============================================================================
# 12. DATA INTEGRITY
# =============================================================================

print("\n" + "=" * 80)
print("F. DATA INTEGRITY")
print("=" * 80)

print(
    "Users:",
    comparison["user_id"].nunique()
)

print(
    "Duplicate users:",
    comparison["user_id"].duplicated().sum()
)

print(
    "Missing financial situation:",
    comparison[
        "financial_situation"
    ].isna().sum()
)

print(
    "Missing risk profile:",
    comparison[
        "risk_profile"
    ].isna().sum()
)

print(
    "Missing risk score:",
    comparison[
        "risk_score"
    ].isna().sum()
)

print(
    "Missing target:",
    comparison[
        "target_amount"
    ].isna().sum()
)

print(
    "Missing horizon:",
    comparison[
        "goal_horizon_months"
    ].isna().sum()
)

# =============================================================================
# 13. SAVE RESULTS
# =============================================================================

financial_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_financial_situation.csv"
)

risk_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_risk_profile.csv"
)

horizon_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_goal_horizon.csv"
)

risk_score_path = os.path.join(
    OUT,
    "lp_5w_analysis_by_risk_score_band.csv"
)

comparison_path = os.path.join(
    OUT,
    "lp_5w_segment_analysis_user_level.csv"
)

financial_analysis.to_csv(
    financial_path,
    index=False
)

risk_analysis.to_csv(
    risk_path,
    index=False
)

horizon_analysis.to_csv(
    horizon_path,
    index=False
)

risk_score_analysis.to_csv(
    risk_score_path,
    index=False
)

comparison.to_csv(
    comparison_path,
    index=False
)

# =============================================================================
# 14. FINAL
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5W COMPLETE")
print("=" * 80)

print("\nSaved:")
print(financial_path)
print(risk_path)
print(horizon_path)
print(risk_score_path)
print(comparison_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO OPTIMIZATION RESULTS WERE CHANGED.")
print("ANALYTICAL SEGMENTATION ONLY.")

================================================================================
STEP 5W — SEGMENT-WISE OPTIMIZATION ANALYSIS
================================================================================

LP: (10000, 38)
Comparison: (10000, 12)

Existing comparison columns:
['user_id', 'target_amount', 'goal_horizon_months', 'historical_funding', 'optimized_goal_funding', 'optimized_shortfall', 'historical_shortfall', 'historical_success', 'optimized_success', 'success_transition', 'funding_change', 'shortfall_reduction']

Missing required columns: []

================================================================================
A. FINANCIAL SITUATION
================================================================================
financial_situation  users  historical_successful  optimized_successful  newly_successful  historical_success_rate  optimized_success_rate   mean_target  mean_historical_funding  mean_optimized_funding  mean_historical_shortfall  mean_optimized_shortfall  mean_shortfall_reduction  success_rate_improvement_pp
   financial_stress    474                      0                    24                24                 0.000000                0.050633  97313.534110             3.172216e+03             7489.355054               94141.317967              89824.179056               4317.138911                     5.063291
        high_saving   2043                   1998                  2031                33                 0.977974                0.994126 178299.962715             2.450276e+06           178124.462574                 553.144002                175.500141                377.643862                     1.615272
         low_saving   2923                    944                  1412               468                 0.322956                0.483065 116054.134290             1.738092e+05            65231.939568               63297.246577              50822.194722              12475.051855                    16.010948
    moderate_saving   4560                   3509                  4115               606                 0.769518                0.902412 139017.253553             8.627601e+05           132236.597482               16454.823301               6780.656071               9674.167229                    13.289474

================================================================================
B. RISK PROFILE
================================================================================
risk_profile  users  historical_successful  optimized_successful  newly_successful  historical_success_rate  optimized_success_rate   mean_target  mean_historical_funding  mean_optimized_funding  mean_historical_shortfall  mean_optimized_shortfall  mean_shortfall_reduction  success_rate_improvement_pp
  aggressive   3333                   3197                  3286                89                 0.959196                0.985899 158150.737279             1.898103e+06           157831.682795                1153.365886                319.054484                834.311402                     2.670267
conservative   3333                    721                  1277               556                 0.216322                0.383138 123393.710270             1.362033e+05            61748.380420               79344.620272              61645.329850              17699.290421                    16.681668
    moderate   3334                   2533                  3019               486                 0.759748                0.905519 133518.508112             8.006316e+05           128755.166321               11249.284956               4763.341791               6485.943165                    14.577085

================================================================================
C. GOAL HORIZON
================================================================================

/tmp/ipykernel_2355/698385706.py:170: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(segment)
/tmp/ipykernel_2355/698385706.py:170: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(segment)

horizon_group  users  historical_successful  optimized_successful  newly_successful  historical_success_rate  optimized_success_rate   mean_target  mean_historical_funding  mean_optimized_funding  mean_historical_shortfall  mean_optimized_shortfall  mean_shortfall_reduction  success_rate_improvement_pp
  1-12 months    636                    143                   252               109                 0.224843                0.396226 137549.935798             9.931015e+04            93146.101976               58555.483979              44403.833822              14151.650157                    17.138365
 13-24 months   1081                    478                   664               186                 0.442183                0.614246 137545.723840             1.976957e+05           104246.439044               44642.154841              33299.284796              11342.870045                    17.206290
 25-36 months   1043                    610                   771               161                 0.584851                0.739214 135568.785701             3.656355e+05           112162.692499               33225.898388              23406.093202               9819.805186                    15.436242
 37-60 months   2045                   1323                  1605               282                 0.646944                0.784841 138225.705834             6.075440e+05           115143.685327               31400.818205              23082.020507               8318.797698                    13.789731
61-120 months   5195                   3897                  4290               393                 0.750144                0.825794 139230.000225             1.453127e+06           122568.667753               23375.584498              16661.332473               6714.252025                     7.564966

================================================================================
D. RISK SCORE BAND
================================================================================
risk_score_band  users  historical_successful  optimized_successful  newly_successful  historical_success_rate  optimized_success_rate   mean_target  mean_historical_funding  mean_optimized_funding  mean_historical_shortfall  mean_optimized_shortfall  mean_shortfall_reduction  success_rate_improvement_pp
      0.00-0.25   1961                     84                   299               215                 0.042835                0.152473 116286.359086             2.281042e+04            28608.912276              103260.020348              87677.446809              15582.573539                    10.963794
      0.25-0.50   2414                   1249                  1822               573                 0.517399                0.754764 130219.212125             3.768077e+05           111689.397952               35245.718045              18529.814173              16715.903872                    23.736537
      0.50-0.75   4281                   3786                  4117               331                 0.884373                0.961691 142298.659288             1.162154e+06           140957.423616                4232.702609               1341.235672               2891.466937                     7.731838
      0.75-1.00   1344                   1332                  1344                12                 0.991071                1.000000 172597.515683             2.619138e+06           172597.515683                  80.833912                  0.000000                 80.833912                     0.892857

================================================================================
E. OVERALL SUMMARY
================================================================================
Users: 10000
Historical success: 6451
Optimized success: 7582
Newly successful: 1131
Historical success rate: 0.6451
Optimized success rate: 0.7582
Success improvement (percentage points): 11.31
Mean shortfall reduction: 8339.662939079435

================================================================================
F. DATA INTEGRITY
================================================================================
Users: 10000
Duplicate users: 0
Missing financial situation: 0
Missing risk profile: 0
Missing risk score: 0
Missing target: 0
Missing horizon: 0

================================================================================
STEP 5W COMPLETE
================================================================================

Saved:
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5w_analysis_by_financial_situation.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5w_analysis_by_risk_profile.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5w_analysis_by_goal_horizon.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5w_analysis_by_risk_score_band.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/lp_inputs/lp_5w_segment_analysis_user_level.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO OPTIMIZATION RESULTS WERE CHANGED.
ANALYTICAL SEGMENTATION ONLY.

In [119]:
# =============================================================================
# STEP 5X — FINAL CONSOLIDATED OPTIMIZATION DATASET
# CORRECTED VERSION
# =============================================================================

import os
import numpy as np
import pandas as pd

BASE = "/content/drive/MyDrive/GoalPilot_AI"

LP_PATH = os.path.join(
    BASE,
    "simulation",
    "06_results",
    "final_optimisation_input.csv"
)

OPT_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_user_summary.csv"
)

VALIDATION_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5u_full_solution_validation.csv"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "final_outputs"
)

os.makedirs(OUT, exist_ok=True)

print("=" * 80)
print("STEP 5X — FINAL CONSOLIDATED OPTIMIZATION DATASET")
print("=" * 80)

# =============================================================================
# 1. LOAD FILES
# =============================================================================

lp = pd.read_csv(LP_PATH)
opt = pd.read_csv(OPT_PATH)
validation = pd.read_csv(VALIDATION_PATH)

print("\nOriginal LP input:", lp.shape)
print("Optimization results:", opt.shape)
print("Validation results:", validation.shape)

# =============================================================================
# 2. DISPLAY ACTUAL VALIDATION COLUMNS
# =============================================================================

print("\nValidation columns:")
print(validation.columns.tolist())

# =============================================================================
# 3. SELECT ONLY REQUIRED OPTIMIZATION COLUMNS THAT EXIST
# =============================================================================

required_opt_columns = [
    "user_id",
    "optimized_goal_funding",
    "optimized_shortfall",
    "additional_funding_vs_existing",
    "optimized_success",
    "solver_success"
]

missing_opt = [
    c for c in required_opt_columns
    if c not in opt.columns
]

if missing_opt:
    raise ValueError(
        f"Missing optimization columns: {missing_opt}"
    )

optimization_data = opt[
    required_opt_columns
].copy()

# =============================================================================
# 4. MERGE OPTIMIZATION RESULTS WITH ORIGINAL LP
# =============================================================================

final = lp.merge(
    optimization_data,
    on="user_id",
    how="left",
    validate="one_to_one"
)

print("\nAfter optimization merge:", final.shape)

# =============================================================================
# 5. RECONSTRUCT HISTORICAL SHORTFALL
# =============================================================================

final["historical_shortfall_recalculated"] = np.maximum(
    final["target_amount"]
    -
    final["goal_horizon_funding_actual"],
    0
)

# =============================================================================
# 6. HISTORICAL SUCCESS
# =============================================================================

final["historical_success"] = (
    final["goal_horizon_funding_actual"]
    >=
    final["target_amount"] - 1e-6
)

# =============================================================================
# 7. OPTIMIZED SUCCESS
# =============================================================================

final["optimized_success"] = (
    final["optimized_goal_funding"]
    >=
    final["target_amount"] - 1e-6
)

# =============================================================================
# 8. SUCCESS TRANSITION
# =============================================================================

conditions = [
    final["historical_success"] & final["optimized_success"],
    (~final["historical_success"]) & final["optimized_success"],
    final["historical_success"] & (~final["optimized_success"]),
    (~final["historical_success"]) & (~final["optimized_success"])
]

choices = [
    "Successful → Successful",
    "Failed → Successful",
    "Successful → Failed",
    "Failed → Failed"
]

final["success_transition"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

# =============================================================================
# 9. SHORTFALL REDUCTION
# =============================================================================

final["shortfall_reduction"] = (
    final["historical_shortfall_recalculated"]
    -
    final["optimized_shortfall"]
)

# =============================================================================
# 10. SUCCESS IMPROVEMENT FLAG
# =============================================================================

final["success_improved"] = (
    (~final["historical_success"])
    &
    final["optimized_success"]
)

# =============================================================================
# 11. FEASIBILITY STATUS
# =============================================================================

final["lp_feasibility_status"] = np.where(
    final["optimized_success"],
    "Target achievable",
    "Target not fully achievable"
)

# =============================================================================
# 12. OPTIMIZATION FUNDING CHANGE
# =============================================================================

final["optimization_gain"] = (
    final["optimized_goal_funding"]
    -
    final["goal_horizon_funding_actual"]
)

# =============================================================================
# 13. INDEPENDENT OPTIMALITY VALIDATION
# =============================================================================
#
# The formal LP solution is:
#
# max funding = min(target, total positive cash flow within horizon)
#
# Therefore we reconstruct the theoretical optimum from the monthly
# optimization solution.
#
# IMPORTANT:
# This does NOT rerun the LP solver.
# It only validates the already-saved solution.
# =============================================================================

MONTHLY_OPT_PATH = os.path.join(
    BASE,
    "optimization",
    "lp_inputs",
    "lp_5t_full_optimization_monthly.csv"
)

monthly_opt = pd.read_csv(MONTHLY_OPT_PATH)

print("\nOptimization monthly data:", monthly_opt.shape)

# Find available funding column
possible_funding_cols = [
    "optimized_goal_funding",
    "goal_funding",
    "G_t"
]

funding_col = None

for c in possible_funding_cols:
    if c in monthly_opt.columns:
        funding_col = c
        break

if funding_col is None:
    raise ValueError(
        "Could not identify optimized funding column in monthly "
        "optimization results."
    )

# Find positive cash-flow column
possible_cash_cols = [
    "positive_cash_flow",
    "positive_cash_flow_dynamic"
]

cash_col = None

for c in possible_cash_cols:
    if c in monthly_opt.columns:
        cash_col = c
        break

if cash_col is None:
    raise ValueError(
        "Could not identify positive cash-flow column in monthly "
        "optimization results."
    )

print("Funding column used:", funding_col)
print("Cash-flow column used:", cash_col)

# Aggregate optimized funding by user
opt_funding_check = (
    monthly_opt
    .groupby("user_id", as_index=False)
    .agg(
        reconstructed_funding=(funding_col, "sum")
    )
)

# =============================================================================
# 14. MERGE INDEPENDENT FUNDING VALIDATION
# =============================================================================

final = final.merge(
    opt_funding_check,
    on="user_id",
    how="left",
    validate="one_to_one"
)

final["funding_reconstruction_error"] = (
    final["optimized_goal_funding"]
    -
    final["reconstructed_funding"]
).abs()

# =============================================================================
# 15. THEORETICAL LP OPTIMUM
# =============================================================================

# Total positive cash flow over each user's optimization horizon
#
# The monthly optimization file already contains only the optimized
# horizon rows, so summing positive cash flow here gives the maximum
# cash-flow-based funding capacity.

cash_capacity = (
    monthly_opt
    .groupby("user_id", as_index=False)
    .agg(
        total_positive_cash_flow=(
            cash_col,
            lambda x: np.maximum(x, 0).sum()
        )
    )
)

final = final.merge(
    cash_capacity,
    on="user_id",
    how="left",
    validate="one_to_one"
)

# Formal analytical optimum
final["analytical_optimal_funding"] = np.minimum(
    final["target_amount"],
    final["total_positive_cash_flow"]
)

final["optimality_error"] = (
    final["optimized_goal_funding"]
    -
    final["analytical_optimal_funding"]
).abs()

# =============================================================================
# 16. TARGET ACCOUNTING
# =============================================================================

final["target_accounting_error"] = (
    final["optimized_goal_funding"]
    +
    final["optimized_shortfall"]
    -
    final["target_amount"]
).abs()

# =============================================================================
# 17. OPTIMIZED SUCCESS VALIDATION
# =============================================================================

final["validated_optimized_success"] = (
    final["analytical_optimal_funding"]
    >=
    final["target_amount"] - 1e-6
)

# =============================================================================
# 18. VALIDATION AGREEMENT
# =============================================================================

if "optimized_success" in validation.columns:

    validation_success = validation[
        ["user_id", "optimized_success"]
    ].copy()

    validation_success = validation_success.rename(
        columns={
            "optimized_success":
                "step5u_optimized_success"
        }
    )

    final = final.merge(
        validation_success,
        on="user_id",
        how="left",
        validate="one_to_one"
    )

else:

    final["step5u_optimized_success"] = np.nan

# =============================================================================
# 19. FINAL INTEGRITY CHECKS
# =============================================================================

print("\n" + "=" * 80)
print("FINAL INTEGRITY CHECKS")
print("=" * 80)

print("Final rows:", len(final))
print("Final columns:", len(final.columns))
print("Unique users:", final["user_id"].nunique())
print(
    "Duplicate users:",
    final["user_id"].duplicated().sum()
)

print(
    "Missing optimized funding:",
    final["optimized_goal_funding"].isna().sum()
)

print(
    "Missing optimized shortfall:",
    final["optimized_shortfall"].isna().sum()
)

print(
    "Missing analytical optimum:",
    final["analytical_optimal_funding"].isna().sum()
)

# =============================================================================
# 20. SUCCESS RESULTS
# =============================================================================

historical_success = int(
    final["historical_success"].sum()
)

optimized_success = int(
    final["optimized_success"].sum()
)

new_success = int(
    final["success_improved"].sum()
)

still_unsuccessful = int(
    (~final["optimized_success"]).sum()
)

print("\n" + "=" * 80)
print("FINAL SUCCESS RESULTS")
print("=" * 80)

print(
    "Historical success:",
    historical_success,
    "/ 10000"
)

print(
    "Optimized success:",
    optimized_success,
    "/ 10000"
)

print(
    "Newly successful:",
    new_success
)

print(
    "Still unsuccessful:",
    still_unsuccessful
)

print(
    "Historical success rate:",
    historical_success / 10000
)

print(
    "Optimized success rate:",
    optimized_success / 10000
)

print(
    "Success improvement (percentage points):",
    (
        optimized_success
        -
        historical_success
    ) / 10000 * 100
)

# =============================================================================
# 21. SUCCESS TRANSITIONS
# =============================================================================

print("\n" + "=" * 80)
print("SUCCESS TRANSITIONS")
print("=" * 80)

print(
    final["success_transition"].value_counts()
)

# =============================================================================
# 22. SHORTFALL ANALYSIS
# =============================================================================

print("\n" + "=" * 80)
print("SHORTFALL ANALYSIS")
print("=" * 80)

print(
    "Mean historical shortfall:",
    final[
        "historical_shortfall_recalculated"
    ].mean()
)

print(
    "Mean optimized shortfall:",
    final[
        "optimized_shortfall"
    ].mean()
)

print(
    "Mean shortfall reduction:",
    final[
        "shortfall_reduction"
    ].mean()
)

print(
    "Total historical shortfall:",
    final[
        "historical_shortfall_recalculated"
    ].sum()
)

print(
    "Total optimized shortfall:",
    final[
        "optimized_shortfall"
    ].sum()
)

print(
    "Total shortfall reduction:",
    final[
        "shortfall_reduction"
    ].sum()
)

# =============================================================================
# 23. MATHEMATICAL VALIDATION
# =============================================================================

print("\n" + "=" * 80)
print("MATHEMATICAL VALIDATION")
print("=" * 80)

print(
    "Maximum funding reconstruction error:",
    final[
        "funding_reconstruction_error"
    ].max()
)

print(
    "Maximum optimality error:",
    final[
        "optimality_error"
    ].max()
)

print(
    "Maximum target accounting error:",
    final[
        "target_accounting_error"
    ].max()
)

print(
    "Funding reconstruction <= 1e-6:",
    (
        final[
            "funding_reconstruction_error"
        ] <= 1e-6
    ).all()
)

print(
    "Optimality <= 1e-6:",
    (
        final[
            "optimality_error"
        ] <= 1e-6
    ).all()
)

print(
    "Target accounting <= 1e-6:",
    (
        final[
            "target_accounting_error"
        ] <= 1e-6
    ).all()
)

# =============================================================================
# 24. STEP 5U AGREEMENT
# =============================================================================

if final["step5u_optimized_success"].notna().any():

    agreement = (
        final["optimized_success"]
        ==
        final["step5u_optimized_success"]
    ).all()

    print(
        "Agreement with Step 5U optimized success:",
        agreement
    )

# =============================================================================
# 25. SAVE FINAL MASTER DATASET
# =============================================================================

final_path = os.path.join(
    OUT,
    "GoalPilot_AI_final_LP_optimization_dataset.csv"
)

final.to_csv(
    final_path,
    index=False
)

# =============================================================================
# 26. SAVE FINAL SUMMARY
# =============================================================================

summary = pd.DataFrame({
    "metric": [
        "Total users",
        "Historical successful users",
        "Optimized successful users",
        "Newly successful users",
        "Still unsuccessful users",
        "Historical success rate",
        "Optimized success rate",
        "Success improvement percentage points",
        "Mean historical shortfall",
        "Mean optimized shortfall",
        "Mean shortfall reduction",
        "Total historical shortfall",
        "Total optimized shortfall",
        "Total shortfall reduction",
        "Maximum funding reconstruction error",
        "Maximum optimality error",
        "Maximum target accounting error"
    ],
    "value": [
        len(final),
        historical_success,
        optimized_success,
        new_success,
        still_unsuccessful,
        historical_success / 10000,
        optimized_success / 10000,
        (
            optimized_success
            -
            historical_success
        ) / 10000 * 100,
        final[
            "historical_shortfall_recalculated"
        ].mean(),
        final[
            "optimized_shortfall"
        ].mean(),
        final[
            "shortfall_reduction"
        ].mean(),
        final[
            "historical_shortfall_recalculated"
        ].sum(),
        final[
            "optimized_shortfall"
        ].sum(),
        final[
            "shortfall_reduction"
        ].sum(),
        final[
            "funding_reconstruction_error"
        ].max(),
        final[
            "optimality_error"
        ].max(),
        final[
            "target_accounting_error"
        ].max()
    ]
})

summary_path = os.path.join(
    OUT,
    "GoalPilot_AI_final_optimization_summary.csv"
)

summary.to_csv(
    summary_path,
    index=False
)

# =============================================================================
# 27. COMPLETE
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5X COMPLETE")
print("=" * 80)

print("\nFinal master dataset:")
print(final_path)

print("\nFinal summary:")
print(summary_path)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO OPTIMIZATION RESULTS WERE RECALCULATED.")
print("ONLY VALIDATED RESULTS WERE CONSOLIDATED.")

================================================================================
STEP 5X — FINAL CONSOLIDATED OPTIMIZATION DATASET
================================================================================

Original LP input: (10000, 38)
Optimization results: (10000, 17)
Validation results: (10000, 19)

Validation columns:
['user_id', 'target_amount', 'optimized_goal_funding', 'optimized_shortfall', 'historical_funding', 'historical_target', 'historical_horizon', 'historical_success', 'optimized_success', 'reconstructed_funding', 'reconstructed_positive_cash', 'reconstructed_months', 'analytical_max_funding', 'analytical_shortfall', 'funding_reconstruction_error', 'target_accounting_error', 'funding_optimality_error', 'shortfall_optimality_error', 'cash_flow_feasible']

After optimization merge: (10000, 43)

Optimization monthly data: (626970, 8)
Funding column used: optimized_goal_funding
Cash-flow column used: positive_cash_flow

================================================================================
FINAL INTEGRITY CHECKS
================================================================================
Final rows: 10000
Final columns: 58
Unique users: 10000
Duplicate users: 0
Missing optimized funding: 0
Missing optimized shortfall: 0
Missing analytical optimum: 0

================================================================================
FINAL SUCCESS RESULTS
================================================================================
Historical success: 6451 / 10000
Optimized success: 7582 / 10000
Newly successful: 1131
Still unsuccessful: 2418
Historical success rate: 0.6451
Optimized success rate: 0.7582
Success improvement (percentage points): 11.31

================================================================================
SUCCESS TRANSITIONS
================================================================================
success_transition
Successful → Successful    6451
Failed → Failed            2418
Failed → Successful        1131
Name: count, dtype: int64

================================================================================
SHORTFALL ANALYSIS
================================================================================
Mean historical shortfall: 30580.490390871095
Mean optimized shortfall: 22240.82745179166
Mean shortfall reduction: 8339.662939079435
Total historical shortfall: 305804903.90871096
Total optimized shortfall: 222408274.51791662
Total shortfall reduction: 83396629.39079435

================================================================================
MATHEMATICAL VALIDATION
================================================================================
Maximum funding reconstruction error: 2.3283064365386963e-10
Maximum optimality error: 2.3283064365386963e-10
Maximum target accounting error: 2.3283064365386963e-10
Funding reconstruction <= 1e-6: True
Optimality <= 1e-6: True
Target accounting <= 1e-6: True
Agreement with Step 5U optimized success: True

================================================================================
STEP 5X COMPLETE
================================================================================

Final master dataset:
/content/drive/MyDrive/GoalPilot_AI/optimization/final_outputs/GoalPilot_AI_final_LP_optimization_dataset.csv

Final summary:
/content/drive/MyDrive/GoalPilot_AI/optimization/final_outputs/GoalPilot_AI_final_optimization_summary.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO OPTIMIZATION RESULTS WERE RECALCULATED.
ONLY VALIDATED RESULTS WERE CONSOLIDATED.

In [120]:
# =============================================================================
# STEP 5Y — FINAL DOCUMENTATION & REPORT SUMMARY
# =============================================================================

import os
import pandas as pd
import numpy as np

BASE = "/content/drive/MyDrive/GoalPilot_AI"

FINAL_DATASET = os.path.join(
    BASE,
    "optimization",
    "final_outputs",
    "GoalPilot_AI_final_LP_optimization_dataset.csv"
)

FINAL_SUMMARY = os.path.join(
    BASE,
    "optimization",
    "final_outputs",
    "GoalPilot_AI_final_optimization_summary.csv"
)

SEGMENT_DIR = os.path.join(
    BASE,
    "optimization",
    "lp_inputs"
)

OUT = os.path.join(
    BASE,
    "optimization",
    "final_outputs"
)

os.makedirs(OUT, exist_ok=True)

print("=" * 80)
print("STEP 5Y — FINAL DOCUMENTATION & REPORT OUTPUTS")
print("=" * 80)

# =============================================================================
# 1. LOAD FINAL DATA
# =============================================================================

df = pd.read_csv(FINAL_DATASET)

print("\nFinal master dataset:", df.shape)

# =============================================================================
# 2. LOAD SEGMENT ANALYSIS
# =============================================================================

financial_path = os.path.join(
    SEGMENT_DIR,
    "lp_5w_analysis_by_financial_situation.csv"
)

risk_path = os.path.join(
    SEGMENT_DIR,
    "lp_5w_analysis_by_risk_profile.csv"
)

horizon_path = os.path.join(
    SEGMENT_DIR,
    "lp_5w_analysis_by_goal_horizon.csv"
)

risk_band_path = os.path.join(
    SEGMENT_DIR,
    "lp_5w_analysis_by_risk_score_band.csv"
)

financial = pd.read_csv(financial_path)
risk = pd.read_csv(risk_path)
horizon = pd.read_csv(horizon_path)
risk_band = pd.read_csv(risk_band_path)

# =============================================================================
# 3. FINAL METRICS
# =============================================================================

total_users = len(df)

historical_success = int(
    df["historical_success"].sum()
)

optimized_success = int(
    df["optimized_success"].sum()
)

new_success = int(
    df["success_improved"].sum()
)

still_unsuccessful = int(
    (~df["optimized_success"]).sum()
)

historical_rate = (
    historical_success / total_users
)

optimized_rate = (
    optimized_success / total_users
)

success_improvement_pp = (
    optimized_rate - historical_rate
) * 100

mean_historical_shortfall = (
    df["historical_shortfall_recalculated"].mean()
)

mean_optimized_shortfall = (
    df["optimized_shortfall"].mean()
)

mean_shortfall_reduction = (
    df["shortfall_reduction"].mean()
)

total_historical_shortfall = (
    df["historical_shortfall_recalculated"].sum()
)

total_optimized_shortfall = (
    df["optimized_shortfall"].sum()
)

total_shortfall_reduction = (
    df["shortfall_reduction"].sum()
)

# =============================================================================
# 4. DATASET / MODEL DESCRIPTION
# =============================================================================

documentation = []

documentation.append({
    "section": "Project",
    "item": "Project name",
    "value": "GoalPilot AI"
})

documentation.append({
    "section": "Optimization",
    "item": "Optimization type",
    "value": "Linear Programming (LP)"
})

documentation.append({
    "section": "Optimization scope",
    "item": "Primary optimization objective",
    "value": "Maximize achievable goal funding within observed positive cash flow"
})

documentation.append({
    "section": "Population",
    "item": "Number of users",
    "value": total_users
})

documentation.append({
    "section": "Historical baseline",
    "item": "Historical goal funding logic",
    "value": "Positive cash flow × goal allocation factor, aggregated over the user's goal horizon"
})

documentation.append({
    "section": "Decision variable",
    "item": "Goal contribution G(u,t)",
    "value": "Monthly goal funding allocated from positive cash flow"
})

documentation.append({
    "section": "Slack variable",
    "item": "Goal shortfall D(u)",
    "value": "Remaining amount required to reach the target"
})

documentation.append({
    "section": "Constraint",
    "item": "Goal funding upper bound",
    "value": "0 <= G(u,t) <= PositiveCashFlow(u,t)"
})

documentation.append({
    "section": "Constraint",
    "item": "Target accounting",
    "value": "Sum of monthly goal funding + shortfall = target amount"
})

documentation.append({
    "section": "Objective",
    "item": "Formal objective",
    "value": "Minimize total goal shortfall, equivalently maximize total achievable goal funding"
})

documentation.append({
    "section": "Time",
    "item": "Optimization horizon",
    "value": "User-specific goal horizon, 6–120 months"
})

documentation.append({
    "section": "Solver",
    "item": "LP solver",
    "value": "HiGHS"
})

documentation.append({
    "section": "Solver scope",
    "item": "Users optimized",
    "value": total_users
})

documentation.append({
    "section": "Validation",
    "item": "Independent solution validation",
    "value": "Completed"
})

documentation.append({
    "section": "Validation",
    "item": "Maximum optimality error",
    "value": df["optimality_error"].max()
})

documentation.append({
    "section": "Validation",
    "item": "Maximum target accounting error",
    "value": df["target_accounting_error"].max()
})

documentation.append({
    "section": "Validation",
    "item": "Maximum funding reconstruction error",
    "value": df["funding_reconstruction_error"].max()
})

# =============================================================================
# 5. FINAL PERFORMANCE RESULTS
# =============================================================================

documentation.extend([
    {
        "section": "Results",
        "item": "Historical successful users",
        "value": historical_success
    },
    {
        "section": "Results",
        "item": "Optimized successful users",
        "value": optimized_success
    },
    {
        "section": "Results",
        "item": "Newly successful users",
        "value": new_success
    },
    {
        "section": "Results",
        "item": "Still unsuccessful users",
        "value": still_unsuccessful
    },
    {
        "section": "Results",
        "item": "Historical success rate",
        "value": historical_rate
    },
    {
        "section": "Results",
        "item": "Optimized success rate",
        "value": optimized_rate
    },
    {
        "section": "Results",
        "item": "Success improvement (percentage points)",
        "value": success_improvement_pp
    },
    {
        "section": "Results",
        "item": "Mean historical shortfall",
        "value": mean_historical_shortfall
    },
    {
        "section": "Results",
        "item": "Mean optimized shortfall",
        "value": mean_optimized_shortfall
    },
    {
        "section": "Results",
        "item": "Mean shortfall reduction",
        "value": mean_shortfall_reduction
    },
    {
        "section": "Results",
        "item": "Total historical shortfall",
        "value": total_historical_shortfall
    },
    {
        "section": "Results",
        "item": "Total optimized shortfall",
        "value": total_optimized_shortfall
    },
    {
        "section": "Results",
        "item": "Total shortfall reduction",
        "value": total_shortfall_reduction
    }
])

# =============================================================================
# 6. SUCCESS TRANSITIONS
# =============================================================================

transition_counts = (
    df["success_transition"]
    .value_counts()
    .to_dict()
)

for transition, count in transition_counts.items():

    documentation.append({
        "section": "Success transitions",
        "item": transition,
        "value": int(count)
    })

# =============================================================================
# 7. MODEL INPUTS
# =============================================================================

model_input_columns = [
    "monthly_income",
    "monthly_expenditure",
    "monthly_emi",
    "initial_savings",
    "initial_investment",
    "investment_capacity_ratio",
    "financial_situation",
    "risk_score",
    "risk_profile",
    "goal_horizon_months",
    "target_amount",
    "goal_specific_monthly_capacity",
    "goal_allocation_factor"
]

for col in model_input_columns:

    if col in df.columns:

        documentation.append({
            "section": "Model inputs",
            "item": col,
            "value": "Present in final optimization dataset"
        })

# =============================================================================
# 8. EXCLUDED MODEL COMPONENTS
# =============================================================================

excluded = [
    (
        "Monthly investment contribution",
        "No explicit monthly investment-contribution variable exists in the validated simulation."
    ),
    (
        "Borrowing",
        "Borrowing was not included in the final LP."
    ),
    (
        "WALR-based borrowing cost",
        "WALR was not used as a borrowing decision constraint in the final LP."
    ),
    (
        "Future NIFTY return decision",
        "No future investment-return decision was introduced into the LP."
    ),
    (
        "Minimum cash reserve",
        "No reserve requirement was established in the validated formulation."
    ),
    (
        "Initial savings as goal funding",
        "Initial savings were not counted toward the target-funding achievement."
    ),
    (
        "Static goal capacity as dynamic hard cap",
        "The static user-level goal-specific monthly capacity was not imposed as a dynamic monthly hard constraint."
    )
]

for item, explanation in excluded:

    documentation.append({
        "section": "Model exclusions",
        "item": item,
        "value": explanation
    })

# =============================================================================
# 9. SEGMENT SUMMARY — FINANCIAL SITUATION
# =============================================================================

for _, row in financial.iterrows():

    documentation.append({
        "section": "Financial situation analysis",
        "item": str(row["financial_situation"]),
        "value": (
            f'Users={int(row["users"])}, '
            f'Historical success rate={row["historical_success_rate"]:.4f}, '
            f'Optimized success rate={row["optimized_success_rate"]:.4f}, '
            f'Newly successful={int(row["newly_successful"])}, '
            f'Shortfall reduction={row["mean_shortfall_reduction"]:.2f}'
        )
    })

# =============================================================================
# 10. SEGMENT SUMMARY — RISK PROFILE
# =============================================================================

for _, row in risk.iterrows():

    documentation.append({
        "section": "Risk profile analysis",
        "item": str(row["risk_profile"]),
        "value": (
            f'Users={int(row["users"])}, '
            f'Historical success rate={row["historical_success_rate"]:.4f}, '
            f'Optimized success rate={row["optimized_success_rate"]:.4f}, '
            f'Newly successful={int(row["newly_successful"])}, '
            f'Shortfall reduction={row["mean_shortfall_reduction"]:.2f}'
        )
    })

# =============================================================================
# 11. SEGMENT SUMMARY — HORIZON
# =============================================================================

for _, row in horizon.iterrows():

    documentation.append({
        "section": "Goal horizon analysis",
        "item": str(row["horizon_group"]),
        "value": (
            f'Users={int(row["users"])}, '
            f'Historical success rate={row["historical_success_rate"]:.4f}, '
            f'Optimized success rate={row["optimized_success_rate"]:.4f}, '
            f'Newly successful={int(row["newly_successful"])}, '
            f'Shortfall reduction={row["mean_shortfall_reduction"]:.2f}'
        )
    })

# =============================================================================
# 12. SEGMENT SUMMARY — RISK SCORE
# =============================================================================

for _, row in risk_band.iterrows():

    documentation.append({
        "section": "Risk score band analysis",
        "item": str(row["risk_score_band"]),
        "value": (
            f'Users={int(row["users"])}, '
            f'Historical success rate={row["historical_success_rate"]:.4f}, '
            f'Optimized success rate={row["optimized_success_rate"]:.4f}, '
            f'Newly successful={int(row["newly_successful"])}, '
            f'Shortfall reduction={row["mean_shortfall_reduction"]:.2f}'
        )
    })

# =============================================================================
# 13. LIMITATIONS
# =============================================================================

limitations = [
    (
        "Goal-funding optimization",
        "The LP optimizes goal funding capacity; it is not a complete portfolio-allocation optimizer."
    ),
    (
        "Observed cash-flow basis",
        "Optimization uses the observed simulated positive cash-flow series within each user's horizon."
    ),
    (
        "Investment decisions",
        "The validated simulation does not provide an explicit monthly investment contribution variable."
    ),
    (
        "Market forecasting",
        "The LP does not independently forecast future NIFTY returns."
    ),
    (
        "Credit decisions",
        "The final LP does not optimize borrowing or credit usage."
    ),
    (
        "Reserve policy",
        "A minimum emergency-cash or liquidity reserve was not defined in the validated LP."
    ),
    (
        "Historical comparison",
        "Historical funding can exceed the target, whereas optimized funding is capped at the target for success accounting; therefore raw funding totals should not be interpreted as direct performance losses."
    )
]

for item, explanation in limitations:

    documentation.append({
        "section": "Limitations",
        "item": item,
        "value": explanation
    })

# =============================================================================
# 14. FINAL CONCLUSION
# =============================================================================

documentation.extend([
    {
        "section": "Conclusion",
        "item": "Historical baseline",
        "value": f"{historical_success / total_users:.2%} of users achieved their target."
    },
    {
        "section": "Conclusion",
        "item": "Optimized outcome",
        "value": f"{optimized_success / total_users:.2%} of users can achieve their target under the validated LP."
    },
    {
        "section": "Conclusion",
        "item": "Additional successful users",
        "value": f"{new_success} users move from unsuccessful to successful."
    },
    {
        "section": "Conclusion",
        "item": "Shortfall",
        "value": f"Mean shortfall decreases by {mean_shortfall_reduction:.2f}."
    },
    {
        "section": "Conclusion",
        "item": "Total shortfall reduction",
        "value": f"{total_shortfall_reduction:.2f} across the 10,000-user population."
    },
    {
        "section": "Conclusion",
        "item": "Validation",
        "value": "The final saved LP solution agrees with the independent analytical formulation within numerical tolerance."
    }
])

# =============================================================================
# 15. SAVE DOCUMENTATION CSV
# =============================================================================

documentation_df = pd.DataFrame(documentation)

documentation_path = os.path.join(
    OUT,
    "GoalPilot_AI_final_optimization_documentation.csv"
)

documentation_df.to_csv(
    documentation_path,
    index=False
)

# =============================================================================
# 16. SAVE KEY REPORT TABLES
# =============================================================================

# Overall results
overall = pd.DataFrame({
    "metric": [
        "Total users",
        "Historical successful",
        "Optimized successful",
        "Newly successful",
        "Still unsuccessful",
        "Historical success rate",
        "Optimized success rate",
        "Success improvement (percentage points)",
        "Mean historical shortfall",
        "Mean optimized shortfall",
        "Mean shortfall reduction",
        "Total historical shortfall",
        "Total optimized shortfall",
        "Total shortfall reduction"
    ],
    "value": [
        total_users,
        historical_success,
        optimized_success,
        new_success,
        still_unsuccessful,
        historical_rate,
        optimized_rate,
        success_improvement_pp,
        mean_historical_shortfall,
        mean_optimized_shortfall,
        mean_shortfall_reduction,
        total_historical_shortfall,
        total_optimized_shortfall,
        total_shortfall_reduction
    ]
})

overall_path = os.path.join(
    OUT,
    "GoalPilot_AI_final_report_overall_results.csv"
)

overall.to_csv(
    overall_path,
    index=False
)

# =============================================================================
# 17. FINAL VALIDATION
# =============================================================================

print("\n" + "=" * 80)
print("FINAL DOCUMENTATION VALIDATION")
print("=" * 80)

print("Users:", total_users)
print("Historical success:", historical_success)
print("Optimized success:", optimized_success)
print("Newly successful:", new_success)
print("Still unsuccessful:", still_unsuccessful)

print(
    "Success improvement:",
    round(success_improvement_pp, 4),
    "percentage points"
)

print(
    "Mean shortfall reduction:",
    round(mean_shortfall_reduction, 4)
)

print(
    "Maximum optimality error:",
    df["optimality_error"].max()
)

print(
    "Maximum target accounting error:",
    df["target_accounting_error"].max()
)

print(
    "Maximum funding reconstruction error:",
    df["funding_reconstruction_error"].max()
)

print(
    "All optimality checks <= 1e-6:",
    (
        df["optimality_error"] <= 1e-6
    ).all()
)

print(
    "All target accounting checks <= 1e-6:",
    (
        df["target_accounting_error"] <= 1e-6
    ).all()
)

print(
    "All funding reconstruction checks <= 1e-6:",
    (
        df["funding_reconstruction_error"] <= 1e-6
    ).all()
)

# =============================================================================
# 18. FILES
# =============================================================================

print("\n" + "=" * 80)
print("STEP 5Y COMPLETE")
print("=" * 80)

print("\nCreated:")
print(documentation_path)
print(overall_path)

print("\nExisting final master dataset:")
print(FINAL_DATASET)

print("\nExisting final summary:")
print(FINAL_SUMMARY)

print("\nNO LP SOLVER WAS RUN.")
print("NO ORIGINAL DATASET WAS MODIFIED.")
print("NO OPTIMIZATION RESULTS WERE CHANGED.")
print("FINAL DOCUMENTATION ONLY.")

================================================================================
STEP 5Y — FINAL DOCUMENTATION & REPORT OUTPUTS
================================================================================

Final master dataset: (10000, 58)

================================================================================
FINAL DOCUMENTATION VALIDATION
================================================================================
Users: 10000
Historical success: 6451
Optimized success: 7582
Newly successful: 1131
Still unsuccessful: 2418
Success improvement: 11.31 percentage points
Mean shortfall reduction: 8339.6629
Maximum optimality error: 2.3283064365386963e-10
Maximum target accounting error: 2.3283064365386963e-10
Maximum funding reconstruction error: 2.3283064365386963e-10
All optimality checks <= 1e-6: True
All target accounting checks <= 1e-6: True
All funding reconstruction checks <= 1e-6: True

================================================================================
STEP 5Y COMPLETE
================================================================================

Created:
/content/drive/MyDrive/GoalPilot_AI/optimization/final_outputs/GoalPilot_AI_final_optimization_documentation.csv
/content/drive/MyDrive/GoalPilot_AI/optimization/final_outputs/GoalPilot_AI_final_report_overall_results.csv

Existing final master dataset:
/content/drive/MyDrive/GoalPilot_AI/optimization/final_outputs/GoalPilot_AI_final_LP_optimization_dataset.csv

Existing final summary:
/content/drive/MyDrive/GoalPilot_AI/optimization/final_outputs/GoalPilot_AI_final_optimization_summary.csv

NO LP SOLVER WAS RUN.
NO ORIGINAL DATASET WAS MODIFIED.
NO OPTIMIZATION RESULTS WERE CHANGED.
FINAL DOCUMENTATION ONLY.